// Dynamic BECE Past Questions & Admin-Uploaded Examination Portal
// All questions are uploaded and published directly by the Administrator
// Supporting all 19 examination cohorts from 2008 to 2026

import { BECEPastQuestion, BECEPaperMeta } from './types';

export type { BECEPastQuestion, BECEPaperMeta };

export const BECE_PAPERS_CATALOG: BECEPaperMeta[] = [
  {
    "id": "bece-math-2026",
    "year": 2026,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "BECE 2026 WAEC Standard National Prediction Paper for Mathematics based on NaCCA Common Core standards."
  },
  {
    "id": "bece-science-2026",
    "year": 2026,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "BECE 2026 WAEC Standard National Prediction Paper for Integrated Science based on NaCCA Common Core standards."
  },
  {
    "id": "bece-english-2026",
    "year": 2026,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "BECE 2026 WAEC Standard National Prediction Paper for English Language based on NaCCA Common Core standards."
  },
  {
    "id": "bece-social-2026",
    "year": 2026,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "BECE 2026 WAEC Standard National Prediction Paper for Social Studies based on NaCCA Common Core standards."
  },
  {
    "id": "bece-ict-2026",
    "year": 2026,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "BECE 2026 WAEC Standard National Prediction Paper for Computing / ICT based on NaCCA Common Core standards."
  },
  {
    "id": "bece-rme-2026",
    "year": 2026,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "BECE 2026 WAEC Standard National Prediction Paper for Religious & Moral Education based on NaCCA Common Core standards."
  },
  {
    "id": "bece-french-2026",
    "year": 2026,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "BECE 2026 WAEC Standard National Prediction Paper for French Language based on NaCCA Common Core standards."
  },
  {
    "id": "bece-twi-2026",
    "year": 2026,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "BECE 2026 WAEC Standard National Prediction Paper for Akuapem Twi based on NaCCA Common Core standards."
  },
  {
    "id": "bece-career-tech-2026",
    "year": 2026,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "BECE 2026 WAEC Standard National Prediction Paper for Career Technology based on NaCCA Common Core standards."
  },
  {
    "id": "bece-math-2025",
    "year": 2025,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "BECE 2025 WAEC Standard National Prediction Paper for Mathematics testing new Common Core inquiry standards."
  },
  {
    "id": "bece-science-2025",
    "year": 2025,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "BECE 2025 WAEC Standard National Prediction Paper for Integrated Science testing new Common Core inquiry standards."
  },
  {
    "id": "bece-english-2025",
    "year": 2025,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "BECE 2025 WAEC Standard National Prediction Paper for English Language testing new Common Core inquiry standards."
  },
  {
    "id": "bece-social-2025",
    "year": 2025,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "BECE 2025 WAEC Standard National Prediction Paper for Social Studies testing new Common Core inquiry standards."
  },
  {
    "id": "bece-ict-2025",
    "year": 2025,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "BECE 2025 WAEC Standard National Prediction Paper for Computing / ICT testing new Common Core inquiry standards."
  },
  {
    "id": "bece-rme-2025",
    "year": 2025,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "BECE 2025 WAEC Standard National Prediction Paper for Religious & Moral Education testing new Common Core inquiry standards."
  },
  {
    "id": "bece-french-2025",
    "year": 2025,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "BECE 2025 WAEC Standard National Prediction Paper for French Language testing new Common Core inquiry standards."
  },
  {
    "id": "bece-twi-2025",
    "year": 2025,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "BECE 2025 WAEC Standard National Prediction Paper for Akuapem Twi testing new Common Core inquiry standards."
  },
  {
    "id": "bece-career-tech-2025",
    "year": 2025,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "BECE 2025 WAEC Standard National Prediction Paper for Career Technology testing new Common Core inquiry standards."
  },
  {
    "id": "bece-math-2024",
    "year": 2024,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official 2024 WAEC BECE Mathematics examination under the NaCCA Common Core Programme."
  },
  {
    "id": "bece-science-2024",
    "year": 2024,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official 2024 WAEC BECE Integrated Science examination under the NaCCA Common Core Programme."
  },
  {
    "id": "bece-english-2024",
    "year": 2024,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official 2024 WAEC BECE English Language examination under the NaCCA Common Core Programme."
  },
  {
    "id": "bece-social-2024",
    "year": 2024,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official 2024 WAEC BECE Social Studies examination under the NaCCA Common Core Programme."
  },
  {
    "id": "bece-ict-2024",
    "year": 2024,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official 2024 WAEC BECE Computing / ICT examination under the NaCCA Common Core Programme."
  },
  {
    "id": "bece-rme-2024",
    "year": 2024,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official 2024 WAEC BECE Religious & Moral Education examination under the NaCCA Common Core Programme."
  },
  {
    "id": "bece-french-2024",
    "year": 2024,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official 2024 WAEC BECE French Language examination under the NaCCA Common Core Programme."
  },
  {
    "id": "bece-twi-2024",
    "year": 2024,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official 2024 WAEC BECE Akuapem Twi examination under the NaCCA Common Core Programme."
  },
  {
    "id": "bece-career-tech-2024",
    "year": 2024,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Common Core (CCP)",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official 2024 WAEC BECE Career Technology examination under the NaCCA Common Core Programme."
  },
  {
    "id": "bece-math-2023",
    "year": 2023,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2023 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2023",
    "year": 2023,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2023 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2023",
    "year": 2023,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2023 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2023",
    "year": 2023,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2023 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2023",
    "year": 2023,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2023 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2023",
    "year": 2023,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2023 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2023",
    "year": 2023,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2023 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2023",
    "year": 2023,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2023 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2023",
    "year": 2023,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2023 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2022",
    "year": 2022,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2022 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2022",
    "year": 2022,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2022 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2022",
    "year": 2022,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2022 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2022",
    "year": 2022,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2022 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2022",
    "year": 2022,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2022 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2022",
    "year": 2022,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2022 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2022",
    "year": 2022,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2022 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2022",
    "year": 2022,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2022 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2022",
    "year": 2022,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2022 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2021",
    "year": 2021,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2021 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2021",
    "year": 2021,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2021 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2021",
    "year": 2021,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2021 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2021",
    "year": 2021,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2021 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2021",
    "year": 2021,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2021 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2021",
    "year": 2021,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2021 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2021",
    "year": 2021,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2021 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2021",
    "year": 2021,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2021 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2021",
    "year": 2021,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2021 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2020",
    "year": 2020,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2020 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2020",
    "year": 2020,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2020 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2020",
    "year": 2020,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2020 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2020",
    "year": 2020,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2020 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2020",
    "year": 2020,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2020 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2020",
    "year": 2020,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2020 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2020",
    "year": 2020,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2020 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2020",
    "year": 2020,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2020 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2020",
    "year": 2020,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2020 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2019",
    "year": 2019,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2019 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2019",
    "year": 2019,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2019 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2019",
    "year": 2019,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2019 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2019",
    "year": 2019,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2019 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2019",
    "year": 2019,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2019 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2019",
    "year": 2019,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2019 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2019",
    "year": 2019,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2019 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2019",
    "year": 2019,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2019 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2019",
    "year": 2019,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2019 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2018",
    "year": 2018,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2018 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2018",
    "year": 2018,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2018 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2018",
    "year": 2018,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2018 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2018",
    "year": 2018,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2018 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2018",
    "year": 2018,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2018 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2018",
    "year": 2018,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2018 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2018",
    "year": 2018,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2018 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2018",
    "year": 2018,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2018 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2018",
    "year": 2018,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2018 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2017",
    "year": 2017,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2017 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2017",
    "year": 2017,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2017 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2017",
    "year": 2017,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2017 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2017",
    "year": 2017,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2017 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2017",
    "year": 2017,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2017 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2017",
    "year": 2017,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2017 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2017",
    "year": 2017,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2017 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2017",
    "year": 2017,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2017 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2017",
    "year": 2017,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2017 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2016",
    "year": 2016,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2016 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2016",
    "year": 2016,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2016 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2016",
    "year": 2016,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2016 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2016",
    "year": 2016,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2016 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2016",
    "year": 2016,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2016 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2016",
    "year": 2016,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2016 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2016",
    "year": 2016,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2016 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2016",
    "year": 2016,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2016 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2016",
    "year": 2016,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2016 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2015",
    "year": 2015,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2015 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2015",
    "year": 2015,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2015 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2015",
    "year": 2015,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2015 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2015",
    "year": 2015,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2015 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2015",
    "year": 2015,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2015 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2015",
    "year": 2015,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2015 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2015",
    "year": 2015,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2015 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2015",
    "year": 2015,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2015 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2015",
    "year": 2015,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2015 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2014",
    "year": 2014,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2014 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2014",
    "year": 2014,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2014 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2014",
    "year": 2014,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2014 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2014",
    "year": 2014,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2014 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2014",
    "year": 2014,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2014 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2014",
    "year": 2014,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2014 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2014",
    "year": 2014,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2014 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2014",
    "year": 2014,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2014 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2014",
    "year": 2014,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2014 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2013",
    "year": 2013,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2013 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2013",
    "year": 2013,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2013 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2013",
    "year": 2013,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2013 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2013",
    "year": 2013,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2013 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2013",
    "year": 2013,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2013 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2013",
    "year": 2013,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2013 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2013",
    "year": 2013,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2013 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2013",
    "year": 2013,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2013 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2013",
    "year": 2013,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2013 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2012",
    "year": 2012,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2012 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2012",
    "year": 2012,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2012 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2012",
    "year": 2012,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2012 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2012",
    "year": 2012,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2012 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2012",
    "year": 2012,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2012 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2012",
    "year": 2012,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2012 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2012",
    "year": 2012,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2012 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2012",
    "year": 2012,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2012 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2012",
    "year": 2012,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2012 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2011",
    "year": 2011,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2011 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2011",
    "year": 2011,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2011 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2011",
    "year": 2011,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2011 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2011",
    "year": 2011,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2011 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2011",
    "year": 2011,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2011 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2011",
    "year": 2011,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2011 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2011",
    "year": 2011,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2011 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2011",
    "year": 2011,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2011 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2011",
    "year": 2011,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2011 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2010",
    "year": 2010,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2010 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2010",
    "year": 2010,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2010 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2010",
    "year": 2010,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2010 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2010",
    "year": 2010,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2010 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2010",
    "year": 2010,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2010 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2010",
    "year": 2010,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2010 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2010",
    "year": 2010,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2010 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2010",
    "year": 2010,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2010 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2010",
    "year": 2010,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2010 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2009",
    "year": 2009,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2009 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2009",
    "year": 2009,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2009 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2009",
    "year": 2009,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2009 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2009",
    "year": 2009,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2009 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2009",
    "year": 2009,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2009 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2009",
    "year": 2009,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2009 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2009",
    "year": 2009,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2009 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2009",
    "year": 2009,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2009 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2009",
    "year": 2009,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2009 examination paper for Career Technology under the GES Junior High School curriculum."
  },
  {
    "id": "bece-math-2008",
    "year": 2008,
    "subjectId": "math",
    "subjectName": "Mathematics",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 60,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2008 examination paper for Mathematics under the GES Junior High School curriculum."
  },
  {
    "id": "bece-science-2008",
    "year": 2008,
    "subjectId": "science",
    "subjectName": "Integrated Science",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2008 examination paper for Integrated Science under the GES Junior High School curriculum."
  },
  {
    "id": "bece-english-2008",
    "year": 2008,
    "subjectId": "english",
    "subjectName": "English Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2008 examination paper for English Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-social-2008",
    "year": 2008,
    "subjectId": "social",
    "subjectName": "Social Studies",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 6,
    "overview": "Official WAEC BECE 2008 examination paper for Social Studies under the GES Junior High School curriculum."
  },
  {
    "id": "bece-ict-2008",
    "year": 2008,
    "subjectId": "ict",
    "subjectName": "Computing / ICT",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2008 examination paper for Computing / ICT under the GES Junior High School curriculum."
  },
  {
    "id": "bece-rme-2008",
    "year": 2008,
    "subjectId": "rme",
    "subjectName": "Religious & Moral Education",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2008 examination paper for Religious & Moral Education under the GES Junior High School curriculum."
  },
  {
    "id": "bece-french-2008",
    "year": 2008,
    "subjectId": "french",
    "subjectName": "French Language",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 3,
    "overview": "Official WAEC BECE 2008 examination paper for French Language under the GES Junior High School curriculum."
  },
  {
    "id": "bece-twi-2008",
    "year": 2008,
    "subjectId": "twi",
    "subjectName": "Akuapem Twi",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 60,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 4,
    "overview": "Official WAEC BECE 2008 examination paper for Akuapem Twi under the GES Junior High School curriculum."
  },
  {
    "id": "bece-career-tech-2008",
    "year": 2008,
    "subjectId": "career-tech",
    "subjectName": "Career Technology",
    "syllabusEra": "Standard JHS Syllabus",
    "paper1DurationMinutes": 45,
    "paper2DurationMinutes": 75,
    "totalPaper1Questions": 40,
    "totalPaper2Questions": 5,
    "overview": "Official WAEC BECE 2008 examination paper for Career Technology under the GES Junior High School curriculum."
  }
];

// Empty by default - All questions are uploaded dynamically by the Admin
export const BECE_PAST_QUESTIONS: BECEPastQuestion[] = [];

export function getBeceQuestionsByYearAndSubject(questions: BECEPastQuestion[], year: number, subjectId: string): BECEPastQuestion[] {
  return questions.filter(q => q.year === year && q.subjectId === subjectId);
}

export function getAllBeceYears(): number[] {
  return [2026,2025,2024,2023,2022,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008];
}

export function getBecePaperMeta(year: number, subjectId: string): BECEPaperMeta | undefined {
  return BECE_PAPERS_CATALOG.find(p => p.year === year && p.subjectId === subjectId);
}
