// Ghanaian JHS 2 Ghanaian Language (Akuapem Twi) Quizzes
// Based on NaCCA / GES Common Core Programme (CCP) Curriculum
// 10 Topics × 10 Questions = 100 BECE-Standard Questions

import { TopicQuiz } from './types';

export const JHS2_TWI_QUIZZES: Record<string, TopicQuiz> = {
  "jhs2-twi-t1-nkyia-ne-abusuabɔ": {
    "id": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
    "topicId": "jhs2-twi-t1-nkyia-ne-abusuabɔ",
    "title": "Nkyia, Nsɛm-Bisa ne Abusuabɔ BECE Nsɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs2-twi-t1-q1",
        "quizId": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
        "questionText": "Sɛ wokɔbɔ anɔpa nkyia a, mmuae bɛn na wode ma onipa a n'ani gye ho no?",
        "optionA": "Yaa agya / Yaa ɛna",
        "optionB": "Yaa anyemi",
        "optionC": "Yaa awɔ",
        "optionD": "Yaa anua",
        "correctOption": "A",
        "subConcept": "Nkyia, Nsɛm-Bisa ne Abusuabɔ",
        "explanation": "Wɔ Akanfo nkyia mu, mmuae a wɔde ma anɔpa nkyia 'Makye' ne 'Yaa agya' sɛ ɔyɛ panyin barima, anaa 'Yaa ɛna' sɛ ɔyɛ ɔbaa.",
        "remediationTip": "Kae Akanfo nkyia mmuae: Makye -> Yaa agya/ɛna, Maaha -> Yaa nua/ɔba."
      },
      {
        "id": "jhs2-twi-t1-q2",
        "quizId": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
        "questionText": "Dɛn nti na Akanfo de wɔn nsa nifa na ɛkyea na ɛnyɛ wɔn nsa benkum?",
        "optionA": "Ɛkyerɛ obu ne animuonyamhyɛ",
        "optionB": "Efikɛse wom",
        "optionC": "Ɛnyɛ biribiara ho mfaso",
        "optionD": "Wɔde nsa benkum kyea anwummere nko ara",
        "correctOption": "A",
        "subConcept": "Nkyia, Nsɛm-Bisa ne Abusuabɔ",
        "explanation": "Nsa nifa kyerɛ obu, ahoteɛ ne animuonyamhyɛ. Nsa benkum deɛ Akanfo bu no sɛ ɛyɛ abusua bɔne anaa akyiwade wɔ nkyia mu.",
        "remediationTip": "Akan amammere mu, fa nifa kyea na bu nkyia nhyehyɛe fa nifa kɔ benkum so animuonyamhyɛ nti."
      },
      {
        "id": "jhs2-twi-t1-q3",
        "quizId": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
        "questionText": "Wɔ abusuabɔ a ɛyɛ ɛna fam deɛ (matrilineal) mu, hena na ɔhwɛ mmɔfra so sen obiara sɛ agya nni hɔ a?",
        "optionA": "Wɔfa",
        "optionB": "Agyakumaa",
        "optionC": "Papa nua kumaa",
        "optionD": "Sewaapanyin",
        "correctOption": "A",
        "subConcept": "Nkyia, Nsɛm-Bisa ne Abusuabɔ",
        "explanation": "Wɔ Akanfo abusuabɔ mu, mmusuakuw akyi deɛ kɔ ɛna fam (mogya). Wɔfa (ɛna nua barima) na ɔwɔ asodi titiriw wɔ ne nuabean mma so.",
        "remediationTip": "Akanfo mogya fi ɛna nkyɛn; enti Wɔfa ne obi titiriw a ɔwɔ tumi ne asodi wɔ abusuani so."
      },
      {
        "id": "jhs2-twi-t1-q4",
        "quizId": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
        "questionText": "Wo papa nuabean yɛ wo dɛn wɔ Akanfo kasa mu?",
        "optionA": "Sewa / Sewaa",
        "optionB": "Awoa",
        "optionC": "Maame panyin",
        "optionD": "Nana",
        "correctOption": "A",
        "subConcept": "Nkyia, Nsɛm-Bisa ne Abusuabɔ",
        "explanation": "Papa nuabean yɛ 'Sewaa' anaa 'Agya-baa'.",
        "remediationTip": "Hwɛ din a yɛde frɛ abusuafo yiye: Papa nuabean = Sewaa; Ɛna nua barima = Wɔfa."
      },
      {
        "id": "jhs2-twi-t1-q5",
        "quizId": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
        "questionText": "Sɛ worekyea nnipa kuw bi a wɔte hɔ a, ɛhefa na wofi hyɛ ase kyea?",
        "optionA": "Fi nifa kɔ benkum",
        "optionB": "Fi benkum kɔ nifa",
        "optionC": "Fi mfinimfini",
        "optionD": "Baabiara a wopɛ",
        "correctOption": "A",
        "subConcept": "Nkyia, Nsɛm-Bisa ne Abusuabɔ",
        "explanation": "Akanfo kyea a, wofi nifa na wɔkɔ benkum, gye sɛ ɔhene te mu a wodi kan kyea no animuonyam nti.",
        "remediationTip": "Nkyia kwan kɔ: nifa so kɔ benkum so daa."
      },
      {
        "id": "jhs2-twi-t1-q6",
        "quizId": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
        "questionText": "Sɛ obi bepue wo fie anwummere bɛyɛ dɔn nsia a, nkyia bɛn na ɔde ma?",
        "optionA": "M'adwo",
        "optionB": "Makye",
        "optionC": "Maaha",
        "optionD": "Kuta mu",
        "correctOption": "A",
        "subConcept": "Nkyia, Nsɛm-Bisa ne Abusuabɔ",
        "explanation": "Anwummere nkyia a efi bɛyɛ awiabere reko dɔn anan kɔpem anadwo no yɛ 'M'adwo' (Membraced peace).",
        "remediationTip": "Bere nhyehyɛe: Anɔpa = Makye; Awia = Maaha; Anwummere = M'adwo."
      },
      {
        "id": "jhs2-twi-t1-q7",
        "quizId": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
        "questionText": "Agya ntɔn (ntoro) a ɔde ma ne ba no de dɛn na ɛhyɛ abofra no mu?",
        "optionA": "Suban, sunsum ne akyiwade",
        "optionB": "Mogya a ɔde bɛdi ade",
        "optionC": "Abusua kɛse a ɔbɛtena mu",
        "optionD": "Nifa so nkyia nkutoo",
        "correctOption": "A",
        "subConcept": "Nkyia, Nsɛm-Bisa ne Abusuabɔ",
        "explanation": "Ntoro/Ntɔn fi agya na ɛma suban, honhom mu ahoɔden, ne akyiwade ahorow a abofra no di so.",
        "remediationTip": "Akanfo gyidi: Mogya fi ɛna (abusua); Sunsum/Ntoro fi agya (suban ne akyiwade)."
      },
      {
        "id": "jhs2-twi-t1-q8",
        "quizId": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
        "questionText": "Sɛ ahɔho ba fie a, dɛn na wodi kan yɛ ma no ansa na wɔabisa n'amanneɛ?",
        "optionA": "Wɔma no nsu nom na wɔkyea no yiye",
        "optionB": "Wɔma no aduane bebrebe",
        "optionC": "Wɔbisa ne sika dodoɔ",
        "optionD": "Wɔpam no kɔ",
        "correctOption": "A",
        "subConcept": "Nkyia, Nsɛm-Bisa ne Abusuabɔ",
        "explanation": "Ahɔho ba fie a, wɔkyea no, wɔma no nsu nom de gye n'ahome ansa na wobisa amanneɛ.",
        "remediationTip": "Ahɔhodwuma mu, nsu a wɔma ahɔho nom no kyerɛ ahobrɛase, asomdwoe ne atenae pa."
      },
      {
        "id": "jhs2-twi-t1-q9",
        "quizId": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
        "questionText": "Wo nuabarima anaa wo nuabean ba yɛ wo dɛn?",
        "optionA": "Wɔfaba / Wofase anaa Wɔfabarima",
        "optionB": "Nana",
        "optionC": "Agya",
        "optionD": "Sewaaba",
        "correctOption": "A",
        "subConcept": "Nkyia, Nsɛm-Bisa ne Abusuabɔ",
        "explanation": "Sɛ woyɛ ɔbarima a, wo nuabean mma yɛ wo 'wofase' (wɔfa ba/mma).",
        "remediationTip": "Kae abusuabɔ nkyerɛwee: Wɔfa mma no yɛ wofase nom wɔ Akanfo ahyɛde mu."
      },
      {
        "id": "jhs2-twi-t1-q10",
        "quizId": "quiz-jhs2-twi-t1-nkyia-ne-abusuabɔ",
        "questionText": "Sɛ obi bɔ kɔkɔkɔ wɔ wo pon ano a, asɛm bɛn na wode gye no so?",
        "optionA": "Agoo / Ameee",
        "optionB": "Makye pa ara",
        "optionC": "Dabi koraa",
        "optionD": "Bra ha ntɛm",
        "correctOption": "A",
        "subConcept": "Nkyia, Nsɛm-Bisa ne Abusuabɔ",
        "explanation": "Sɛ obi bɔ pon ano ka sɛ 'Agoo' a, nea ɔte dan mu no gye so sɛ 'Ameee' a ɛkyerɛ sɛ ɔbɛtumi abue pon no aba mu.",
        "remediationTip": "Agoo ne Ameee yɛ kwan a wɔfa so bɔ amanneɛ ansa na obi awura ofie bi mu."
      }
    ]
  },
  "jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu": {
    "id": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
    "topicId": "jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
    "title": "Kasa Mmara: Edin ne Adinanmu BECE Nsɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs2-twi-t2-q1",
        "quizId": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
        "questionText": "Asɛmfua bɛn na ɛyɛ 'Edinpa' (Proper Noun) wɔ kasamu yi mu: 'Kwame kɔɔ Kumase kɔtɔɔ nwoma'?",
        "optionA": "Kwame ne Kumase",
        "optionB": "Kɔɔ ne kɔtɔɔ",
        "optionC": "Nwoma nkutoo",
        "optionD": "Kumase nkutoo",
        "correctOption": "A",
        "subConcept": "Kasa Mmara: Edin ne Adinanmu",
        "explanation": "Kwame (onipa din) ne Kumase (kuro din) nyinaa yɛ edinpa efisɛ ɛyɛ beae ne onipa titiriw bi din na wɔde nkyerɛwde kɛse hyɛ ase.",
        "remediationTip": "Edinpa yɛ onipa, kuro, asubɔnten anaa anansesɛm bea din pɔtee na wɔtwerɛ no nkyerɛwde kɛse so."
      },
      {
        "id": "jhs2-twi-t2-q2",
        "quizId": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
        "questionText": "Dɛn ne edin dodoɔ kwan a wɔfa so yɛ asɛmfua 'Abofra' kɔ dodoɔ mu?",
        "optionA": "Mmɔfra",
        "optionB": "Nnipa",
        "optionC": "Abofra-nom",
        "optionD": "Mma",
        "correctOption": "A",
        "subConcept": "Kasa Mmara: Edin ne Adinanmu",
        "explanation": "'Abofra' baako dodow yɛ 'Mmɔfra'. Wɔsesa ahyɛase 'a-' kɔ 'm-' so na wɔde dodoɔ nsɛnkyerɛnne aka ho.",
        "remediationTip": "Hwɛ Twi edin dodoɔ nhyehyɛe: abofra -> mmɔfra; dua -> nnua; oburoni -> aborɔfo."
      },
      {
        "id": "jhs2-twi-t2-q3",
        "quizId": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
        "questionText": "Adinanmu (Pronoun) bɛn na egyina hɔ ma dodoɔ a ɛto so mmienu (2nd Person Plural)?",
        "optionA": "Mo",
        "optionB": "Wɔn",
        "optionC": "Yɛn",
        "optionD": "Me",
        "correctOption": "A",
        "subConcept": "Kasa Mmara: Edin ne Adinanmu",
        "explanation": "'Mo' gyina hɔ ma nnipa dodoɔ a worekasa akyerɛ wɔn pɔtee (2nd person plural - you all).",
        "remediationTip": "Adinanmu: Me (1st sing), Wo (2nd sing), Ɔno (3rd sing), Yɛn (1st plur), Mo (2nd plur), Wɔn (3rd plur)."
      },
      {
        "id": "jhs2-twi-t2-q4",
        "quizId": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
        "questionText": "Kasamu yi mu adinanmu ne hefa: 'Ɔno na ɔbɔɔ bɔɔl no guu dan mu'?",
        "optionA": "Ɔno",
        "optionB": "Bɔɔl",
        "optionC": "Dan",
        "optionD": "Guu",
        "correctOption": "A",
        "subConcept": "Kasa Mmara: Edin ne Adinanmu",
        "explanation": "'Ɔno' yɛ adinanmu a egyina hɔ ma onipa a yɛreka ne ho asɛm no na yɛammɔ ne din pɔtee.",
        "remediationTip": "Adinanmu si edin ananmu wɔ kasamu mu sɛnea yɛrentĩ edin no mu mprenpren."
      },
      {
        "id": "jhs2-twi-t2-q5",
        "quizId": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
        "questionText": "Edin a yɛrentumi nfa yɛn nsa nka anaa yɛrentumi nhu no anim nanso ɛwɔ adwenem pɛ no yɛfrɛ no dɛn?",
        "optionA": "Edin a Enni Hɔnammɔ (Abstract Noun)",
        "optionB": "Edin-Kɛse",
        "optionC": "Edin-Hunu a Ɛda Hɔ",
        "optionD": "Edin-Kuw",
        "correctOption": "A",
        "subConcept": "Kasa Mmara: Edin ne Adinanmu",
        "explanation": "Edin a ɛfa adwene, atenka, su anaa gyidi ho te sɛ 'ɔdɔ', 'anidaso', 'akokoduru' yɛ Abstract noun (edin a enni hɔnammɔ).",
        "remediationTip": "Edin a wunhu no te sɛ 'anigye', 'nyansa', 'ahoteɛ' yɛ adwenem anaa su ho edin."
      },
      {
        "id": "jhs2-twi-t2-q6",
        "quizId": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
        "questionText": "Asɛmfua 'Dua' dodow kyerɛw kwan bɛn na ɛteɛ?",
        "optionA": "Nnua",
        "optionB": "Adua",
        "optionC": "Mmadua",
        "optionD": "Duano",
        "correctOption": "A",
        "subConcept": "Kasa Mmara: Edin ne Adinanmu",
        "explanation": "Dua dodoɔ yɛ Nnua. Wɔsesa 'd' no kɔ 'nn' na ɛkyerɛ dodoɔ wɔ Akan kasa mu.",
        "remediationTip": "Dua -> Nnua; Dadeɛ -> Nnadeɛ."
      },
      {
        "id": "jhs2-twi-t2-q7",
        "quizId": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
        "questionText": "Wɔ kasamu 'Kofi maa me sika' mu no, adinanmu 'me' no gyina hɔ sɛ dɛn?",
        "optionA": "Asɛntɔdwe (Object pronoun)",
        "optionB": "Ayɛfo (Subject pronoun)",
        "optionC": "Ɔkyerɛfo",
        "optionD": "Adeyɛ",
        "correctOption": "A",
        "subConcept": "Kasa Mmara: Edin ne Adinanmu",
        "explanation": "'Me' wɔ kasamu no mu di dwuma sɛ 'object' (asɛntɔdwe) efisɛ ɛno na adeyɛ 'maa' no kɔɔ ne so.",
        "remediationTip": "Adinanmu a ɛdi dwuma sɛ adeyɛfafo (object) na ɛba adeyɛ akyi."
      },
      {
        "id": "jhs2-twi-t2-q8",
        "quizId": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
        "questionText": "Edin-kuw (Collective Noun) kyerɛ dɛn?",
        "optionA": "Nneɛma anaa nnipa kuw a yɛka wɔn bom bu wɔn sɛ ade baako",
        "optionB": "Onipa baako pɔtee din",
        "optionC": "Kuro kɛse pɔtee bi din",
        "optionD": "Adeyɛ asɛmfua biara",
        "correctOption": "A",
        "subConcept": "Kasa Mmara: Edin ne Adinanmu",
        "explanation": "Edin-kuw te sɛ 'dɔm', 'asraafo', 'kuw', 'mmoa dɔm' gyina hɔ ma nnipa anaa mmoa bebrebe a wɔaka wɔn abom sɛ ade koro.",
        "remediationTip": "Edin-kuw gyina hɔ ma 'group/collective' concept wɔ Twi kasa mu."
      },
      {
        "id": "jhs2-twi-t2-q9",
        "quizId": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
        "questionText": "Kyerɛ adinanmu a ɛkyerɛ dea ɔde ade no (Possessive Pronoun) wɔ 'Ne poma no abu' mu:",
        "optionA": "Ne",
        "optionB": "Poma",
        "optionC": "Abu",
        "optionD": "No",
        "correctOption": "A",
        "subConcept": "Kasa Mmara: Edin ne Adinanmu",
        "explanation": "'Ne' kyerɛ dea ade no yɛ ne dea (his/her possessive pronoun).",
        "remediationTip": "Me (my), Wo (your), Ne (his/her), Yɛn (our), Mo (your pl.), Wɔn (their)."
      },
      {
        "id": "jhs2-twi-t2-q10",
        "quizId": "quiz-jhs2-twi-t2-kasa-mmara-edin-ne-adinanmu",
        "questionText": "Dɛn ne botae titiriw a yɛde adinanmu di dwuma wɔ twerɛ mu?",
        "optionA": "Sɛnea yɛbɛkwati edin a yɛbɛka no mprenpren agyimi so",
        "optionB": "Sɛnea yɛbɛsesa kasa no kɔ brofo mu",
        "optionC": "Sɛnea yɛbɛma asɛm no ayɛ tia koraa",
        "optionD": "Sɛnea yebetumi akyerɛ akyiwade",
        "correctOption": "A",
        "subConcept": "Kasa Mmara: Edin ne Adinanmu",
        "explanation": "Adinanmu si edin ananmu ma twerɛ anaa kasa no yɛ dɛ na ɛkwati edin baako a wɔbɛbɔ no mprenpren a ɛbrɛ atiefo.",
        "remediationTip": "Adinanmu ma kasa kɔ so tenteenten a mfutukasa nni mu."
      }
    ]
  },
  "jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe": {
    "id": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
    "topicId": "jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
    "title": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe BECE Nsɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs2-twi-t3-q1",
        "quizId": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
        "questionText": "Adeyɛ (Verb) dwumadi bɛn na ɛwɔ kasamu mu?",
        "optionA": "Ɛkyerɛ dwuma anaa ade a obi anaa biribi reyɛ",
        "optionB": "Ɛkyerɛ faako a obi te",
        "optionC": "Ɛbɔ onipa din pɔtee",
        "optionD": "Ɛkyerɛ bea ko a dua da",
        "correctOption": "A",
        "subConcept": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe",
        "explanation": "Adeyɛ yɛ asɛmfua a ɛkyerɛ dwumadi, kankyee anaa tebea a biribi wom wɔ kasamu no mu.",
        "remediationTip": "Adeyɛ = Action/state verb: didi, tu mmirika, kasa, da, kyerɛw."
      },
      {
        "id": "jhs2-twi-t3-q2",
        "quizId": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
        "questionText": "Asɛmfua a ɛkyerɛ edin su (Adjective / Ɔkyerɛfo) wɔ 'Kofi tɔɔ kuruwa kɔkɔɔ' mu ne:",
        "optionA": "Kɔkɔɔ",
        "optionB": "Kuruwa",
        "optionC": "Kofi",
        "optionD": "Tɔɔ",
        "correctOption": "A",
        "subConcept": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe",
        "explanation": "'Kɔkɔɔ' yɛ ɔkyerɛfo efisɛ ɛkyerɛ ahosuo anaa su a kuruwa no kuta.",
        "remediationTip": "Ɔkyerɛfo kyerɛ su, ahosuo, kɛseɛ anaa suban a edin kuta: tenten, kumaa, fitaa, kɔkɔɔ."
      },
      {
        "id": "jhs2-twi-t3-q3",
        "quizId": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
        "questionText": "Kasamu Teatea (Simple Sentence) kuta dɛn?",
        "optionA": "Ayɛfo (Subject) baako ne adeyɛ (Predicate/Verb) titiriw baako",
        "optionB": "Nkabomdeɛ nnan",
        "optionC": "Adeyɛ dumien",
        "optionD": "Edinpa du",
        "correctOption": "A",
        "subConcept": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe",
        "explanation": "Kasamu teatea kuta adwene koro a ɛda adi pɛ a ayɛfo koro ne adeyɛ koro na ɛwom.",
        "remediationTip": "Kasamu Teatea (Simple sentence): 'Yaw didi.' 'Ama kɔ sukuu.'"
      },
      {
        "id": "jhs2-twi-t3-q4",
        "quizId": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
        "questionText": "Nkabomdeɛ (Conjunction) bɛn na yɛde ka kasamu mmienu yi bom: 'Ama kɔɔ dwa mu. Ɔtɔɔ nkosua'?",
        "optionA": "Na",
        "optionB": "Efisɛ",
        "optionC": "Nanso",
        "optionD": "Gye sɛ",
        "correctOption": "A",
        "subConcept": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe",
        "explanation": "'Na' yɛ nkabomdeɛ a ɛka nsɛm mmienu a ɛkɔ so toatoa so bom: 'Ama kɔɔ dwa mu na ɔtɔɔ nkosua.'",
        "remediationTip": "Nkabomdeɛ ahodoɔ: na (and), nanso (but), efisɛ (because), anaa (or)."
      },
      {
        "id": "jhs2-twi-t3-q5",
        "quizId": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
        "questionText": "Hena ne Ayɛfo (Subject) wɔ kasamu yi mu: 'Ɔkyerɛkyerɛfo no kyerɛɛ mmɔfra no akontabuo'?",
        "optionA": "Ɔkyerɛkyerɛfo no",
        "optionB": "Mmɔfra no",
        "optionC": "Akontabuo",
        "optionD": "Kyerɛɛ",
        "correctOption": "A",
        "subConcept": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe",
        "explanation": "'Ɔkyerɛkyerɛfo no' na ɔyɛɛ dwuma no, enti ɔno na ɔyɛ Ayɛfo (Subject).",
        "remediationTip": "Ayɛfo yɛ nea ɔreyɛ dwuma no wɔ kasamu mu."
      },
      {
        "id": "jhs2-twi-t3-q6",
        "quizId": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
        "questionText": "Sɛ yɛka sɛ 'Kasamu Nkabom' (Compound Sentence) a, ɛkyerɛ dɛn?",
        "optionA": "Kasamu teatea mmienu anaa nea ɛboro saa a wɔde nkabomdeɛ aka abom",
        "optionB": "Kasamu a adeyɛ nni mu koraa",
        "optionC": "Kasamu a ɛkuta akyiwade",
        "optionD": "Krataa a wɔatwerɛ no tenten",
        "correctOption": "A",
        "subConcept": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe",
        "explanation": "Kasamu nkabom yɛ kasamu atitiriw mmienu a emu biara tumi gyina ne ho nanso wɔde nkabomde te sɛ 'na', 'nanso' aka abom.",
        "remediationTip": "Compound sentence = Independent clause + Conjunction + Independent clause."
      },
      {
        "id": "jhs2-twi-t3-q7",
        "quizId": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
        "questionText": "Asɛm-kyerɛfo (Adverb) bɛn na ɛwɔ kasamu yi mu: 'Kojo tuu mmirika ntɛmntɛm kɔɔ fie'?",
        "optionA": "Ntɛmntɛm",
        "optionB": "Mmirika",
        "optionC": "Tuu",
        "optionD": "Kojo",
        "correctOption": "A",
        "subConcept": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe",
        "explanation": "'Ntɛmntɛm' kyerɛ kwan a adeyɛ 'tuu mmirika' no faa so kɔe, enti ɛyɛ asɛm-kyerɛfo (adverb of manner).",
        "remediationTip": "Asɛm-kyerɛfo (Adverb) kyerɛ bere, beae anaa kwan a adeyɛ bi fa so ba: ntɛmntɛm, bɔkɔɔ, nnamnnam."
      },
      {
        "id": "jhs2-twi-t3-q8",
        "quizId": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
        "questionText": "Adeyɛ bɛn na ɛda kasamua 'Kofi bɛkɔ Kumase ɔkyena' mu?",
        "optionA": "Bɛkɔ (Daakye bere / Future tense)",
        "optionB": "Kɔɔ (Bere a atwam)",
        "optionC": "Rɛkɔ (Mprempren bere)",
        "optionD": "Akɔ (Bere a awie pɛ)",
        "correctOption": "A",
        "subConcept": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe",
        "explanation": "'Bɛkɔ' de ahyɛnsew 'bɛ-' kyerɛ Daakye bere (Future tense).",
        "remediationTip": "Adeyɛ mmere: Bere a atwam (-eɛ/-i), Mprempren bere (re-), Daakye bere (bɛ-)."
      },
      {
        "id": "jhs2-twi-t3-q9",
        "quizId": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
        "questionText": "Kasamu a ɛhyɛ da bɔ kɔkɔ anaa ɛkyerɛ ahyɛde (Imperative) nhwɛso ne:",
        "optionA": "Bra ha ntɛm!",
        "optionB": "Kwasi guare nsuo.",
        "optionC": "Ɔkyena mɛba fie.",
        "optionD": "Mani gye wo ho.",
        "correctOption": "A",
        "subConcept": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe",
        "explanation": "'Bra ha ntɛm!' yɛ ahyɛde (command/imperative) a wɔde rema obi ntɛm ara.",
        "remediationTip": "Kasamu ahodoɔ: Asɛmpa (declarative), Asɛmbisa (interrogative), Ahyɛde (imperative)."
      },
      {
        "id": "jhs2-twi-t3-q10",
        "quizId": "quiz-jhs2-twi-t3-ɔkasa-fãhorow-asɛntɔdwe",
        "questionText": "Dɛn na asɛntɔdwe (Object) kyerɛ wɔ kasamu nhyehyɛe mu?",
        "optionA": "Nea adeyɛ no tɔ ne so anaa egye dwumadi no",
        "optionB": "Nea ɔtɔɔ nsa no",
        "optionC": "Nkyia mmuae kɛse no",
        "optionD": "Kasamu no ahyɛase",
        "correctOption": "A",
        "subConcept": "Ɔkasa Fãhorow ne Kasamu Nhyehyɛe",
        "explanation": "Asɛntɔdwe (Object) yɛ nea ayɛfo no dwumadi kɔtɔ ne so wɔ kasamu mu (Subject-Verb-Object).",
        "remediationTip": "Akan kasa nhyehyɛe fa S-V-O so: Ayɛfo + Adeyɛ + Asɛntɔdwe."
      }
    ]
  },
  "jhs2-twi-t4-akɛntenyensɛm-atitiriw": {
    "id": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
    "topicId": "jhs2-twi-t4-akɛntenyensɛm-atitiriw",
    "title": "Akenkan ne Ntease BECE Nsɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs2-twi-t4-q1",
        "quizId": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
        "questionText": "Sɛ woresua akenkansɛm bi wɔ BECE nsɔhwɛ mu a, dɛn na ɛsɛ sɛ wodi kan yɛ?",
        "optionA": "Kan asɛm no nyinaa yiye fa w'adwene mu ansa na woakan nsɛmmisa no",
        "optionB": "Twerɛ mmuae no ntɛmntɛm a wonkanii",
        "optionC": "Kan asɛmmisa a ɛtwa toɔ no nko ara",
        "optionD": "Hunu asɛmfua a ɛyɛ den pɛ na gyae",
        "correctOption": "A",
        "subConcept": "Akenkan ne Ntease",
        "explanation": "Ɛsɛ sɛ wodi kan kan asɛm no nyinaa penpem baako anaa mmienu ma wote asɛntitiriw no ase ansa na woabua nsɛmmisa.",
        "remediationTip": "Akenkan ne Ntease mu, kenkan asɛm no nyinaa fi mfiase kɔ awiei de hwehwɛ adwene titiriw."
      },
      {
        "id": "jhs2-twi-t4-q2",
        "quizId": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
        "questionText": "Dɛn ne asɛntitiriw (Main Idea) a ɛwɔ nkyekyem bi mu?",
        "optionA": "Adwene titiriw a otwerɛfo no gyina so twerɛɛ asɛm no",
        "optionB": "Nsɛmfua a ɛyɛ den nyinaa",
        "optionC": "Kasamu a edi akyiri pɛ",
        "optionD": "Din a ɛwɔ asɛm no mfitiase",
        "correctOption": "A",
        "subConcept": "Akenkan ne Ntease",
        "explanation": "Asɛntitiriw yɛ asɛm tsitsir a otwerɛfo no de rema atiefo anaa akenkanfo wɔ nkyekyem no mu.",
        "remediationTip": "Asɛntitiriw taa da adi wɔ nkyekyem no kasamu a edi kan anaa deɛ ɛka akyi no mu."
      },
      {
        "id": "jhs2-twi-t4-q3",
        "quizId": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
        "questionText": "Sɛ wohyia asɛmfua bi a wunnim ne nkyerɛase wɔ akenkan mu a, kwan bɛn na wobɛfa so ahu ne nkyerɛase?",
        "optionA": "Hwɛ kasamu a asɛmfua no wom no nkyerɛkyerɛmu (Context clues)",
        "optionB": "Gyaa akenkan no hɔ kɔ fie",
        "optionC": "Sesa asɛmfua no kɔ Borɔfo koraa",
        "optionD": "Sɔre tu mmirika fi sukuu",
        "correctOption": "A",
        "subConcept": "Akenkan ne Ntease",
        "explanation": "Kasamu a ɛtwa asɛmfua no ho ahyia no nkyerɛase (Context clues) ma wohu deɛ asɛmfua no kyerɛ wɔ saa beae pɔtee no.",
        "remediationTip": "Fa kasamu no nyinaa adwene bɔ mu de hu asɛmfua a ɛyɛ foforo no asekyerɛ."
      },
      {
        "id": "jhs2-twi-t4-q4",
        "quizId": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
        "questionText": "Dɛn ne 'Nsɛnkyerɛnne a ɛto asɛm tiawa' (Summary writing) botae?",
        "optionA": "Sɛ worebɛtwa asɛm tenten no atiawa ama asɛntitiriw no ada adi a nsɛm hunu nni mu",
        "optionB": "Sɛ worebɛtwerɛ asɛm no afi ahyɛase kɔ awiei bio",
        "optionC": "Sɛ wobɛsesa otwerɛfo no din",
        "optionD": "Sɛ wobɛtwerɛ anwonsɛm foforo",
        "correctOption": "A",
        "subConcept": "Akenkan ne Ntease",
        "explanation": "Asɛmtiawa twerɛ (Summary) kyerɛ sɛ woyi nsɛm hunu ne mfatoho firi mu na wode w'ankasa kasamu tiawa twerɛ adwene atitiriw no.",
        "remediationTip": "Summary twerɛ mu, kwati mfatoho ne nsɛm a ɛnhia; fa nsɛntitiriw no nkutoo yɛ adwuma."
      },
      {
        "id": "jhs2-twi-t4-q5",
        "quizId": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
        "questionText": "Sɛ akenkansɛm bi bisa sɛ 'Kyerɛ asɛmfua foforo a wotumi de si eyi ananmu' a, ɛhwehwɛ dɛn?",
        "optionA": "Nsɛm a ɛkyerɛ ade koro (Synonyms)",
        "optionB": "Nsɛm a ɛne ne ho bɔ abira (Antonyms)",
        "optionC": "Adeyɛ asɛmfua biara",
        "optionD": "Edinpa a ɛwɔ mu",
        "correctOption": "A",
        "subConcept": "Akenkan ne Ntease",
        "explanation": "Asɛmfua a wotumi de si foforo ananmu a ɛnsɛe nkyerɛase yɛ Asɛm-a-ɛne-no-sɛ (Synonym).",
        "remediationTip": "Synonyms = Nsɛmfua a ɛkuta nkyerɛase koro; Antonyms = Nsɛmfua a ɛbɔ abira."
      },
      {
        "id": "jhs2-twi-t4-q6",
        "quizId": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
        "questionText": "Dɛn ne asɛmfua 'Ahobrɛase' abirabɔ (Antonym)?",
        "optionA": "Ahantan / Ahomaso",
        "optionB": "Obrɛ",
        "optionC": "Akokoa",
        "optionD": "Animuonyam",
        "correctOption": "A",
        "subConcept": "Akenkan ne Ntease",
        "explanation": "Ahobrɛase abirabɔ ne Ahantan anaa Ahomaso (pride/arrogance).",
        "remediationTip": "Ahobrɛase (humility) <-> Ahantan / Ahomaso (pride)."
      },
      {
        "id": "jhs2-twi-t4-q7",
        "quizId": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
        "questionText": "Sɛ otwerɛfo bi ka sɛ 'Obi nkyerɛ abofra Nyame' a, dɛn na ɛkyerɛ?",
        "optionA": "Nyame adebɔ ne Ne tumi da adi pefee ma obiara te ase a obi nkyerɛɛ no",
        "optionB": "Nyame nte baabiara",
        "optionC": "Abofra biara rentumi nkan nwoma",
        "optionD": "Ɛnyɛ anansesɛm pa",
        "correctOption": "A",
        "subConcept": "Akenkan ne Ntease",
        "explanation": "Ɛkyerɛ sɛ Onyankopɔn tumi ne n'anuonyam da adi pefee wɔ abɔde mu a obiara nim no ntɛm ara.",
        "remediationTip": "Kasa mu ntease hwehwɛ mmɛbusɛm ne kasakoa asekyerɛ yiye."
      },
      {
        "id": "jhs2-twi-t4-q8",
        "quizId": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
        "questionText": "Wɔ akenkan mu, hefa na yɛtaa hu asɛm no ti (Title) a ɛbata ho?",
        "optionA": "Asɛm no mfitiase pɛɛ wɔ atifi",
        "optionB": "Asɛm no awiei koraa",
        "optionC": "Mfinimfini nkyekyem mu",
        "optionD": "Kasamu a ɛtwa toɔ no mu",
        "correctOption": "A",
        "subConcept": "Akenkan ne Ntease",
        "explanation": "Asɛmti (Title) da asɛm no atifi pɛɛ na ɛkyerɛ dza asɛm no nyinaa fa ho kɔ.",
        "remediationTip": "Asɛmti yɛ asɛm no mu nsɛm nyinaa nnyinasosɛm a ɛtwa no tiawa pɛ."
      },
      {
        "id": "jhs2-twi-t4-q9",
        "quizId": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
        "questionText": "Sɛ yɛrebua akenkan nsɛmmisa a, adɛn nti na ɛnyɛ pa sɛ yɛfa otwerɛfo no kasamu no ara de bua?",
        "optionA": "Ɛsɛ sɛ wode w'ankasa nsɛm kyerɛ sɛ woate asɛm no ase ampa",
        "optionB": "Otwerɛfo no bɛbofuw",
        "optionC": "Ɛnyɛ biribiara ho mfaso",
        "optionD": "Nsɛmmisa no nnye kwan mma saa",
        "correctOption": "A",
        "subConcept": "Akenkan ne Ntease",
        "explanation": "Sɛ wode w'ankasa kasa bua a, ɛkyerɛ nsɔhwɛhwɛfo no pefee sɛ wote asɛm no ase ampa na wonnyɛ kɔpii nko ara.",
        "remediationTip": "Fa w'ankasa nsɛmfua kyerɛkyerɛ mmuae no mu wɔ akenkan ne ntease mu."
      },
      {
        "id": "jhs2-twi-t4-q10",
        "quizId": "quiz-jhs2-twi-t4-akɛntenyensɛm-atitiriw",
        "questionText": "Dɛn na 'ntease' (comprehension) kyerɛ ampa?",
        "optionA": "Sɛ worebɛte asɛm a woakenkan no ase na woatumi akyerɛkyerɛ mu na woabua ne ho nsɛm",
        "optionB": "Sɛ wobɛkan asɛm no ntɛmntɛm koraa",
        "optionC": "Sɛ wobɛka nsɛm no akyere w'adamfo",
        "optionD": "Sɛ wobɛtwerɛ brofo afra mu",
        "correctOption": "A",
        "subConcept": "Akenkan ne Ntease",
        "explanation": "Ntease kyerɛ nimdeɛ a obi nya fi asɛm a wakan no mu a ɔtumi de di dwuma bua nsɛm na ɔtumi de toto asetenam nsɛm ho.",
        "remediationTip": "Kenkan na te ase; ɛno ne akenkan dwumadi ahyɛase kɛse."
      }
    ]
  },
  "jhs2-twi-t5-nsɛm-twerɛ-anwensɛm": {
    "id": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
    "topicId": "jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
    "title": "Nsɛm Twerɛ ne Anwensɛm BECE Nsɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs2-twi-t5-q1",
        "quizId": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
        "questionText": "Adesua krataa a yɛtwerɛ kɔma yɛn adamfo anaa yɛn busuani yɛ krataa bɛn?",
        "optionA": "Adɔfonom krataa (Informal letter)",
        "optionB": "Aban anaa adwuma krataa (Formal letter)",
        "optionC": "Amanneɛbɔ krataa",
        "optionD": "Nsɔhwɛ krataa",
        "correctOption": "A",
        "subConcept": "Nsɛm Twerɛ ne Anwensɛm",
        "explanation": "Krataa a wɔtwerɛ kɔma adamfo, awofo anaa busuani yɛ adɔfonom krataa a wɔde akyi tebea ne kɔkɔɔkɔ kasa na ɛtwerɛ.",
        "remediationTip": "Krataa ahodoɔ mmienu: Adɔfonom krataa (Informal) ne Adwuma krataa (Formal)."
      },
      {
        "id": "jhs2-twi-t5-q2",
        "quizId": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
        "questionText": "Aderese (Address) ahe na ɛsɛ sɛ ɛda Adɔfonom Krataa (Informal Letter) atifi nifa fam?",
        "optionA": "Aderese baako (Otwerɛfo dea)",
        "optionB": "Aderese mmienu",
        "optionC": "Aderese mmiɛnsa",
        "optionD": "Aderese biara nni hɔ",
        "correctOption": "A",
        "subConcept": "Nsɛm Twerɛ ne Anwensɛm",
        "explanation": "Adɔfonom krataa kuta otwerɛfo koro pɛ aderese wɔ atifi nifa so a da a wɔtwerɛɛ krataa no da ase pɛɛ.",
        "remediationTip": "Informal letter = 1 address (sender's address + date); Formal letter = 2 addresses."
      },
      {
        "id": "jhs2-twi-t5-q3",
        "quizId": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
        "questionText": "Dɛn ne krataa mmuae a edi akyiri a wɔde gyae adɔfonom krataa twerɛ?",
        "optionA": "Mene wo nua pa / Wo adamfo nokwafo",
        "optionB": "Yɛn wura a ɔsom bo",
        "optionC": "Otitenani kɛse",
        "optionD": "Me nua panyin a ɔsen biara",
        "correctOption": "A",
        "subConcept": "Nsɛm Twerɛ ne Anwensɛm",
        "explanation": "Adɔfonom krataa mu no, wɔde 'Mene wo nua nokwafo', 'Wo adamfo pa' anaa ade a ɛte saa na ɛwie na wɔatwerɛ wɔn edin.",
        "remediationTip": "Subscription ma informal letter yɛ dɔfonom kwan so nkabom."
      },
      {
        "id": "jhs2-twi-t5-q4",
        "quizId": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
        "questionText": "Anwensɛm (Poetry) twerɛfo bɔ mmɔden de dɛn na ɛkanyan akenkanfo atenka?",
        "optionA": "Nsɛm a ɛyɛ anika, mfatoho ne kasakoa a ɛyɛ dɛ",
        "optionB": "Kasamu a ɛyɛ tia koraa a nkyerɛase nni mu",
        "optionC": "Borɔfo nsɛmfua bebrebe",
        "optionD": "Nkabomdeɛ nko ara",
        "correctOption": "A",
        "subConcept": "Nsɛm Twerɛ ne Anwensɛm",
        "explanation": "Anwensɛm twerɛfo de anwensɛm nnyigyei (rhyme/rhythm), kasakoa, mfatoho ne nsɛm dɛdɛ na ɛkanyan akenkanfo atenka.",
        "remediationTip": "Anwensɛm nhyehyɛe: Anwonsɛm kasamu (lines), Nkyekyem (stanzas), Kasakoa (imagery)."
      },
      {
        "id": "jhs2-twi-t5-q5",
        "quizId": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
        "questionText": "Anwensɛm mu kasamu baako biara yɛfrɛ no dɛn?",
        "optionA": "Anwensɛm nkyekyem kasamu (Poetic Line)",
        "optionB": "Kasamu teatea",
        "optionC": "Edinpa",
        "optionD": "Akenkansɛm",
        "correctOption": "A",
        "subConcept": "Nsɛm Twerɛ ne Anwensɛm",
        "explanation": "Kasamu baako biara a ɛwɔ anwensɛm nkyekyem (stanza) mu no yɛ Poetic line (anwensɛm nkyerɛw kasamu).",
        "remediationTip": "Anwensɛm nkyekyem (stanza) kuta poetic lines pii a ɛka bom yɛ anwonsɛm no."
      },
      {
        "id": "jhs2-twi-t5-q6",
        "quizId": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
        "questionText": "Sɛ yɛretwerɛ Agyinatuo Twerɛ (Essay / Composition) a, nhyehyɛe bɛn na edi kan?",
        "optionA": "Asɛmti, Mfitiase, Akyi nsɛm (nkyekyem afãhorow), ne Awiei",
        "optionB": "Awiei, Aderese, Asɛmti",
        "optionC": "Krataa mmuae, Edin, Mfitiase",
        "optionD": "Akyi nsɛm nkutoo",
        "correctOption": "A",
        "subConcept": "Nsɛm Twerɛ ne Anwensɛm",
        "explanation": "Agyinatuo twerɛ nhyehyɛe pa ne: Asɛmti (Title) -> Mfitiase (Introduction) -> Akyi Nsɛm (Body paragraphs) -> Awiei (Conclusion).",
        "remediationTip": "Twerɛ nkyekyem ahyɛase pa ma BECE nsɔhwɛ mu ma wubenya nkontaa pa."
      },
      {
        "id": "jhs2-twi-t5-q7",
        "quizId": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
        "questionText": "Mfatoho (Metaphor / Simile) a yɛde 'sɛ' anaa 'te sɛ' toto nneɛma mmienu ho yɛfrɛ no dɛn?",
        "optionA": "Nsɛsodeɛ (Simile)",
        "optionB": "Adesɛsodeɛ a enni kwan (Metaphor)",
        "optionC": "Edin-Kɛse",
        "optionD": "Kasamu Teatea",
        "correctOption": "A",
        "subConcept": "Nsɛm Twerɛ ne Anwensɛm",
        "explanation": "Sɛ yɛde 'te sɛ' anaa 'sɛ' toto ade bi ho (e.g., 'Kofi ho yɛ hare te sɛ osutɔbrɔ') a, ɛyɛ Nsɛsodeɛ (Simile).",
        "remediationTip": "Nsɛsodeɛ (Simile) fa 'sɛ' anaa 'te sɛ' so toto nneɛma mmienu a ɛnteɛ ho."
      },
      {
        "id": "jhs2-twi-t5-q8",
        "quizId": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
        "questionText": "Sɛ anwensɛm ka sɛ 'Esum kabii regu asase so, ewiem resu awerɛhow' a, kasakoa bɛn na ɛwɔ mu?",
        "optionA": "Nnipadwuma-mma-abɔde (Personification)",
        "optionB": "Nsɛsodeɛ",
        "optionC": "Edinpa",
        "optionD": "Mfatoho hunu",
        "correctOption": "A",
        "subConcept": "Nsɛm Twerɛ ne Anwensɛm",
        "explanation": "Wɔde onipa suban (resu, regu) ama ewiem a ɛnyɛ onipa; ɛno yɛ Personification (nnipadwuma-mma-abɔde).",
        "remediationTip": "Personification kyerɛ abɔde a wonkasa a wɔde onipa suban anaa nneyɛe ma no."
      },
      {
        "id": "jhs2-twi-t5-q9",
        "quizId": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
        "questionText": "Dɛn nti na akyerɛw kwan pa (Punctuation) ho hia wɔ nsɛm twerɛ mu?",
        "optionA": "Ɛma asɛm no nkyerɛase da adi pefee na ɛkwati adwenetu",
        "optionB": "Ɛyɛ kwan a wɔfa so bɔ amanneɛ anadwo",
        "optionC": "Ɛma nwoma no yɛ hare",
        "optionD": "Ɛnsɛe hwee koraa",
        "correctOption": "A",
        "subConcept": "Nsɛm Twerɛ ne Anwensɛm",
        "explanation": "Akyerɛw kwan pa te sɛ aponsafo (.), akyi nkyerɛwe (,), ne ahyɛnsew kyerɛ akenkanfo faako a wogyina na ɛma nkyerɛase da adi pefee.",
        "remediationTip": "Fa punctuation marks (., ?, !, ', \") di dwuma yiye wɔ Twi twerɛ mu."
      },
      {
        "id": "jhs2-twi-t5-q10",
        "quizId": "quiz-jhs2-twi-t5-nsɛm-twerɛ-anwensɛm",
        "questionText": "Wɔ krataa a yɛtwerɛ kɔma adwumawura bi mu no, asɛmti (Heading/Subject) da he?",
        "optionA": "Nkyia no akyi pɛɛ ansa na akyi nsɛm no afi ase",
        "optionB": "Aderese no anim pɛɛ",
        "optionC": "Krataa no awiei koraa",
        "optionD": "Mmuae a ɛto so abien mu",
        "correctOption": "A",
        "subConcept": "Nsɛm Twerɛ ne Anwensɛm",
        "explanation": "Wɔ formal letter mu, asɛmti (heading) da nkyia 'Owura Pa,' akyi pɛ ansa na asɛm no ankasa afi ase.",
        "remediationTip": "Formal letter kuta Heading/Subject line a ɛda nkyia akyi pɛɛ."
      }
    ]
  },
  "jhs2-twi-t6-amammere-awo-ne-abato": {
    "id": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
    "topicId": "jhs2-twi-t6-amammere-awo-ne-abato",
    "title": "Akanfo Amammere: Awo ne Abadinto BECE Nsɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs2-twi-t6-q1",
        "quizId": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
        "questionText": "Dabɛn pɔtee na Akanfo taa yɛ Abadinto (kradin ne dinto) amammere no?",
        "optionA": "Da a ɛto so awɔtwe (8th day) a wɔawo abofra no",
        "optionB": "Da a ɛto so aduanan",
        "optionC": "Da a wɔawo abofra no ara pɛ",
        "optionD": "Bosome a edi kan no awiei",
        "correctOption": "A",
        "subConcept": "Akanfo Amammere: Awo ne Abadinto",
        "explanation": "Akanfo yɛ abadinto da a ɛto so awɔtwe (nnawɔtwe) efisɛ wogye di sɛ abofra no ayɛ 'onipa' ampa a ɔrentu kwan nsan nkɔ baabi a ofii.",
        "remediationTip": "Abadinto da yɛ da a ɛto so awɔtwe (8th day) anɔpahecheche."
      },
      {
        "id": "jhs2-twi-t6-q2",
        "quizId": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
        "questionText": "Hena na ɔwɔ asodi sɛ ɔbɔ abofra foforo din wɔ Akanfo amammere mu?",
        "optionA": "Abofra no agya",
        "optionB": "Abofra no wɔfa",
        "optionC": "Abofra no sewaa",
        "optionD": "Ɔhemmaa no",
        "correctOption": "A",
        "subConcept": "Akanfo Amammere: Awo ne Abadinto",
        "explanation": "Akanfo amammere kyerɛ sɛ agya na ɔwɔ fahodi ne asodi kɛse sɛ ɔto ne ba din, efisɛ agya ntɔn na ɛba abofra no so.",
        "remediationTip": "Agya na ɔto abofra din na ɔtaa de ne maame, ne papa anaa ne busuani bi din to abofra no."
      },
      {
        "id": "jhs2-twi-t6-q3",
        "quizId": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
        "questionText": "Dɛn na nsuo ne nsa a wɔde sɔ abofra tɛkrɛma so wɔ dinto bere no kyerɛ?",
        "optionA": "Nokwarewaredi: Sɛ ɔka nsu a ɛnyɛ nsu, na sɛ ɔka nsa nso a ɛnyɛ nsa",
        "optionB": "Sɛ abofra no bɛnom nsa kɛse daakye",
        "optionC": "Sɛ abofra no bɛyɛ okuafo",
        "optionD": "Sɛ ɔbɛyɛ ɔhoho daa",
        "correctOption": "A",
        "subConcept": "Akanfo Amammere: Awo ne Abadinto",
        "explanation": "Nsuo ne nsa kyerɛ nokwaredi: 'Sɛ woka nsu a, ka nsu; na sɛ woka nsa a, ka nsa'—ɛkyerɛ nokwarewaredi a ɛnni nkontompo.",
        "remediationTip": "Nsuo ne nsa ahyɛnsew kyerɛ nokwaredi ne adifudepɛ a wɔbɛkwati wɔ asetenam."
      },
      {
        "id": "jhs2-twi-t6-q4",
        "quizId": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
        "questionText": "Sɛ wɔwo ɔbaabarima Benada a, kradin bɛn na Akanfo de ma no?",
        "optionA": "Kwabena",
        "optionB": "Kwaku",
        "optionC": "Kofi",
        "optionD": "Kwame",
        "correctOption": "A",
        "subConcept": "Akanfo Amammere: Awo ne Abadinto",
        "explanation": "Benada barima kradin ne Kwabena (ɔbaa ne Abenaa anaa Abena).",
        "remediationTip": "Kradin: Dwoada = Kojo/Adwoa, Benada = Kwabena/Abenaa, Wukuada = Kwaku/Akua, Yawoada = Yaw/Yaa, Fiada = Kofi/Afia, Memeneda = Kwame/Ama, Kwasiada = Kwasi/Akosua."
      },
      {
        "id": "jhs2-twi-t6-q5",
        "quizId": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
        "questionText": "Sɛ wɔwo mmɔfra mmienu prɛko pɛ a, dɛn na Akanfo frɛ wɔn?",
        "optionA": "Ntaafo (Ata ne Ataa)",
        "optionB": "Apesi",
        "optionC": "Tawia",
        "optionD": "Nyankomago",
        "correctOption": "A",
        "subConcept": "Akanfo Amammere: Awo ne Abadinto",
        "explanation": "Mmɔfra mmienu a wɔawo wɔn beroro koro pɛ yɛ Ntaafo (Ata barima, Ataa ɔbaa).",
        "remediationTip": "Akan awo nhyehyɛe: Ata ne Ataa (twins), Tawia (abofra a odi ntaafo akyi), Nyankomago (nea odi Tawia akyi)."
      },
      {
        "id": "jhs2-twi-t6-q6",
        "quizId": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
        "questionText": "Abofra a odi ntaafo akyi pɛɛ no dinto kwan ne hene?",
        "optionA": "Tawia",
        "optionB": "Apesi",
        "optionC": "Kronti",
        "optionD": "Badu",
        "correctOption": "A",
        "subConcept": "Akanfo Amammere: Awo ne Abadinto",
        "explanation": "Abofra a odi ntaafo akyi pɛɛ dinto ne Tawia.",
        "remediationTip": "Hwɛ Twi awo ahodoɔ din: Ata/Ataa -> Tawia -> Nyankomago."
      },
      {
        "id": "jhs2-twi-t6-q7",
        "quizId": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
        "questionText": "Nneɛma bɛn na agya de brɛ ne yere ne ne ba foforo wɔ abadinto amammere mu?",
        "optionA": "Ntama, duku, dadesɛn, sika ne abofra nnoɔma",
        "optionB": "Tuo ne akofena",
        "optionC": "Bɔɔl ne ntade a wɔagyae hyɛ",
        "optionD": "Kente mmienu nkutoo",
        "correctOption": "A",
        "subConcept": "Akanfo Amammere: Awo ne Abadinto",
        "explanation": "Agya no de akyɛde ahorow te sɛ ntama, duku, samina, sika, ne nnoɔma a abofra no ne ɔbaatan bɛhia brɛ wɔn de da obu ne anigye adi.",
        "remediationTip": "Agya no kyɛfa wɔ dinto bere kyerɛ n'asodi sɛ ofie wura a ɔbɛhwɛ ne fiefo so."
      },
      {
        "id": "jhs2-twi-t6-q8",
        "quizId": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
        "questionText": "Hena na ɔbɔ guankɔn / apam gu nsuo anaa nsa de gu nsa hyira abofra no so?",
        "optionA": "Abusuapanyin anaa agya a ɔrebɔ abofra no din",
        "optionB": "Ɔpanyin biara a ɔwɔ abɔnten",
        "optionC": "Ɔbaa a ɔto so mmiɛnsa",
        "optionD": "Sukuuni kɛse no",
        "correctOption": "A",
        "subConcept": "Akanfo Amammere: Awo ne Abadinto",
        "explanation": "Abusuapanyin anaa ɔkyeame a agya no apaw no na ogu nsa hyira abofra no ne awofo no so na ɔbɔ abofra no din kyerɛ ekuw no.",
        "remediationTip": "Nsamgu/Nsahyira ma nananom ne abosom te abofra no din na wɔbɔ ne ho ban."
      },
      {
        "id": "jhs2-twi-t6-q9",
        "quizId": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
        "questionText": "Dɛn nti na abofra kuta din mmienu: Kradin ne Abusuadin?",
        "optionA": "Kradin fi da a wɔwoo no mu, na abusuadin nso fi agya anaa nananom a wɔde ne din bɔɔ no no mu",
        "optionB": "Sɛnea ɔbɛtumi atua sika mprɛnsa",
        "optionC": "Sɛnea ɔbɛkɔ amannɔne",
        "optionD": "Sɛnea otumi kɔ sukuu mprɛ mmienu",
        "correctOption": "A",
        "subConcept": "Akanfo Amammere: Awo ne Abadinto",
        "explanation": "Kradin kyerɛ da a wɔwoo no ne kra su; Abusuadin kyerɛ onipa pa anaa nana bi a wɔpɛ sɛ abofra no suasua ne nneyɛe pa.",
        "remediationTip": "Kradin (Day name) + Edinpa/Abusuadin (Ancestral name) na ɛka bom yɛ onipa din koraa."
      },
      {
        "id": "jhs2-twi-t6-q10",
        "quizId": "quiz-jhs2-twi-t6-amammere-awo-ne-abato",
        "questionText": "Sɛ abofra no di mfe a ɔreba mpanyinsem mu a, Akanfo ka sɛ abofra ntetee yɛ hena asodi?",
        "optionA": "Krom hɔ mpanyimfo ne kurow no nyinaa asodi",
        "optionB": "Agya no nkutoo",
        "optionC": "Ɛna no nkutoo",
        "optionD": "Ɔkyerɛkyerɛfo nko ara",
        "correctOption": "A",
        "subConcept": "Akanfo Amammere: Awo ne Abadinto",
        "explanation": "Akanfo ka sɛ 'Obi awo ba a, ɛnyɛ ne ba nko ara'—kurom hɔfo nyinaa kuta asodi sɛ wɔtete abofra ma ɔyɛ nipa pa.",
        "remediationTip": "Abofra ntetee yɛ ɔman ne abusua nyinaa akyɛde ne asodi a wɔbom yɛ."
      }
    ]
  },
  "jhs2-twi-t7-mmɛbusɛm-kasakoa": {
    "id": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
    "topicId": "jhs2-twi-t7-mmɛbusɛm-kasakoa",
    "title": "Kasakoa, Mmɛbusɛm ne Ebisa BECE Nsɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs2-twi-t7-q1",
        "quizId": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
        "questionText": "Ɛbɛ 'Baanu so a emmia' kyerɛ dɛn?",
        "optionA": "Nkabom ne biakoyɛ ma adwuma a ɛyɛ den yɛ hare",
        "optionB": "Nnipa mmienu nni sika",
        "optionC": "Ɛnsɛ sɛ obi ne ne yɔnko kasa",
        "optionD": "Obi baako na obetumi asoa adesoa nyinaa",
        "correctOption": "A",
        "subConcept": "Kasakoa, Mmɛbusɛm ne Ebisa",
        "explanation": "Ɛbɛ yi kyerɛ nkabom ne baanu mmoa mfaso—sɛ nnipa mmienu anaa nea ɛboro saa ka wɔn ho bom a, biribiara renka wɔn nko.",
        "remediationTip": "Baanu so a emmia = Nkabom wom a, adwuma yɛ hare."
      },
      {
        "id": "jhs2-twi-t7-q2",
        "quizId": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
        "questionText": "Sɛ Akanfo ka sɛ obi 'akɔ baabi' anaa 'n'ani agye' wɔ owuo ho a, kasakoa bɛn na wɔde redi dwuma?",
        "optionA": "Kasakoa a wɔde kata owuo akyi (Euphemism)",
        "optionB": "Nsɛsodeɛ",
        "optionC": "Edin-Kɛse",
        "optionD": "Anwensɛm",
        "correctOption": "A",
        "subConcept": "Kasakoa, Mmɛbusɛm ne Ebisa",
        "explanation": "Kasakoa (Euphemism) te sɛ 'wafa ne nsa akyi', 'wawu', 'n'ani agye' ma yɛkwati nsɛm a ɛyɛ den, keka anaa ɛsɛe atiefo adwene te sɛ owuo.",
        "remediationTip": "Kasakoa (Euphemism) ma kasa yɛ mmerɛw na ɛkata asɛm a ɛyɛ den akyi: wafa ne nsa akyi = wawu."
      },
      {
        "id": "jhs2-twi-t7-q3",
        "quizId": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
        "questionText": "Kyerɛ kasakoa 'Ne nsa yɛ hare' nkyerɛase pa:",
        "optionA": "Ɔyɛ owifo (ɔkorɔmfo)",
        "optionB": "Ɔbɔ mmirika yiye",
        "optionC": "Ɔtumi tu ade ntɛm",
        "optionD": "Ɔyɛ abɔfra kumaa",
        "correctOption": "A",
        "subConcept": "Kasakoa, Mmɛbusɛm ne Ebisa",
        "explanation": "'Ne nsa yɛ hare' yɛ kasakoa a Akanfo de kyerɛ obi a n'ani gye awudie anaa korɔnbɔ ho.",
        "remediationTip": "Ne nsa yɛ hare = ɔkorɔmfo; Ne nsa dɔ kɔkɔɔ = owudifo; N'ano yɛ hare = ɔkasa dodo."
      },
      {
        "id": "jhs2-twi-t7-q4",
        "quizId": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
        "questionText": "Bue ɛbɛ yi ano yiye: 'Abofra hu ne nsa hohorow a, ...'?",
        "optionA": "Ɔne mpanyimfo didi",
        "optionB": "Ɔkɔ fie ntɛm",
        "optionC": "Ɔtɔ ntade foforo",
        "optionD": "Ɔnyin bɔkɔɔ",
        "correctOption": "A",
        "subConcept": "Kasakoa, Mmɛbusɛm ne Ebisa",
        "explanation": "'Abofra hu ne nsa hohorow a, ɔne mpanyimfo didi' kyerɛ sɛ sɛ abofra bi nya suban pa ne nyansa a, mpanyimfo de no bɔ.",
        "remediationTip": "Mmɛ a agye din wɔ BECE: Abofra hu ne nsa hohorow a, ɔne mpanyimfo didi."
      },
      {
        "id": "jhs2-twi-t7-q5",
        "quizId": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
        "questionText": "Dɛn ne Ebisa (Agya rekɔ ogyaa me biribi...) yi nkyerɛase: 'Agya rekɔ ogyaa me abɔfra bi a sɛ ɔdidie a ɔnyin, na sɛ ɔnom nsu a owu'?",
        "optionA": "Ogya",
        "optionB": "Dua",
        "optionC": "Bɔɔl",
        "optionD": "Nsuo",
        "correctOption": "A",
        "subConcept": "Kasakoa, Mmɛbusɛm ne Ebisa",
        "explanation": "Ogya na sɛ wuma no nnyina anaa nneɛma a ɛhye a ɛkɔ so nyin, nanso sɛ wugu nsuo gu so a ɛdum koraa (owu).",
        "remediationTip": "Ebisa (Riddle) yi mmuae ne OGYA."
      },
      {
        "id": "jhs2-twi-t7-q6",
        "quizId": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
        "questionText": "Kasakoa bɛn na Akanfo de ma nyinsɛn (pregnancy)?",
        "optionA": "Ɔyem / Ne ho yɛ duru / Ogyina ahotɔ kwan mu",
        "optionB": "Ne nsa yɛ duru",
        "optionC": "N'ani abue",
        "optionD": "Wada",
        "correctOption": "A",
        "subConcept": "Kasakoa, Mmɛbusɛm ne Ebisa",
        "explanation": "Kasakoa a wɔde kata nyinsɛn ho ne: 'Ne ho yɛ duru', 'Ɔkuta afuru', 'Ɔkuta nyinsɛn'.",
        "remediationTip": "Kasakoa ma nyinsɛn: Ne ho yɛ duru / Ɔwɔ ahotɔ kwan mu."
      },
      {
        "id": "jhs2-twi-t7-q7",
        "quizId": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
        "questionText": "Bue ɛbɛ yi ano: 'Tikro nko agyina, ...'?",
        "optionA": "Ɛbɔ afi",
        "optionB": "Ɛkɔ baabiara",
        "optionC": "Ɛyɛ kɛse",
        "optionD": "Ɛma sika ba",
        "correctOption": "A",
        "subConcept": "Kasakoa, Mmɛbusɛm ne Ebisa",
        "explanation": "'Tikro nko agyina, ɛbɔ afi' kyerɛ sɛ onipa baako pɛ rentumi nni asɛm kɛse a ntease wom a afoforo mmoa nni mu.",
        "remediationTip": "Tikro nko agyina, ɛbɔ afi = Baanu afotu sen obiako."
      },
      {
        "id": "jhs2-twi-t7-q8",
        "quizId": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
        "questionText": "Ebisa: 'Agya rekɔ ogyaa me akwadaa bi, woto no tuo a, ɔntɔ fam, na mmom ɔforo kɔ soro'—dɛn na ɛkyerɛ?",
        "optionA": "Wusiw",
        "optionB": "Anomaa",
        "optionC": "Nsoroma",
        "optionD": "Osuo",
        "correctOption": "A",
        "subConcept": "Kasakoa, Mmɛbusɛm ne Ebisa",
        "explanation": "Wusiw (smoke) na sɛ wuto no tuo (wobɔ no asɛm) anaa ogya bɔ a, ɛkɔ soro na ɛnhwe fam.",
        "remediationTip": "Agya rekɔ ogyaa me akwadaa a sɛ wotu tuo a ɔforo soro = Wusiw."
      },
      {
        "id": "jhs2-twi-t7-q9",
        "quizId": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
        "questionText": "Sɛ obi 'kuta adifudepɛ' a, kasakoa bɛn na Akanfo de ka ne ho asɛm?",
        "optionA": "N'ani abere anaa N'ani agye sika ho dodo",
        "optionB": "N'aso yɛ den",
        "optionC": "Ne nsa mu teɛ",
        "optionD": "Ne tirim yɛ den",
        "correctOption": "A",
        "subConcept": "Kasakoa, Mmɛbusɛm ne Ebisa",
        "explanation": "'N'ani abere' anaa obi a n'ani teɛ ade dodo kyerɛ adifudepɛ ne anibere a ɛnteɛ.",
        "remediationTip": "Kasakoa a ɛfa suban bɔne ho hwehwɛ adwene pa wɔ kasa mu."
      },
      {
        "id": "jhs2-twi-t7-q10",
        "quizId": "quiz-jhs2-twi-t7-mmɛbusɛm-kasakoa",
        "questionText": "Dɛn na Akanfo gyina so ka sɛ 'Ɛbɛ ne asɛm ntam agyinafo'?",
        "optionA": "Mmɛ ma asɛm yɛ dɛ, emu dɔ, na ɛma atiefo te anansesɛm ne nsɛntitiriw ase ntɛm",
        "optionB": "Mmɛ ma asɛm no yɛ den dodo",
        "optionC": "Mmɛ ma obi pɛ asɛm",
        "optionD": "Mmɛ mfaso biara nni hɔ",
        "correctOption": "A",
        "subConcept": "Kasakoa, Mmɛbusɛm ne Ebisa",
        "explanation": "Akanfo ka sɛ mmɛ yɛ ngo a wɔde we nsɛm—ɛma kasa tu mpon, emu dɔ na ɛkyerɛ obi nyansa ne nimdeɛ.",
        "remediationTip": "Ɛbɛ ma Akan kasa yɛ dɛ na ɛhyɛ ntease mu den."
      }
    ]
  },
  "jhs2-twi-t8-anansesɛm-agoru": {
    "id": "quiz-jhs2-twi-t8-anansesɛm-agoru",
    "topicId": "jhs2-twi-t8-anansesɛm-agoru",
    "title": "Akanfo Anansesɛm ne Mmoguo BECE Nsɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs2-twi-t8-q1",
        "quizId": "quiz-jhs2-twi-t8-anansesɛm-agoru",
        "questionText": "Hena ne nipasu titiriw (Central character) a odi akoten wɔ Akanfo anansesɛm pii mu?",
        "optionA": "Kwaku Ananse",
        "optionB": "Onyankopɔn",
        "optionC": "Ɔkraman",
        "optionD": "Kweku Tsir",
        "correctOption": "A",
        "subConcept": "Akanfo Anansesɛm ne Mmoguo",
        "explanation": "Kwaku Ananse ne anansesɛm agodifo titiriw wɔ Akanfo mu a ɔwɔ anifere, aniteɛ, adifudepɛ ne nyansa afã horow.",
        "remediationTip": "Kwaku Ananse ne Akan amammerɛ anansesɛm titsir."
      },
      {
        "id": "jhs2-twi-t8-q2",
        "quizId": "quiz-jhs2-twi-t8-anansesɛm-agoru",
        "questionText": "Dɛn ne Ananse yere din wɔ anansesɛm dodoɔ no ara mu?",
        "optionA": "Okɔnɔre Yaa (Aso)",
        "optionB": "Afua Mansa",
        "optionC": "Akua Donkor",
        "optionD": "Yaa Asantewaa",
        "correctOption": "A",
        "subConcept": "Akanfo Anansesɛm ne Mmoguo",
        "explanation": "Okɔnɔre Yaa (anaa Aso) ne Kwaku Ananse yere a ɔtaa boa no anaa ɔpaw ne nyansa bere a ɔyɛ aniteɛ.",
        "remediationTip": "Ananse abusuafo: Yere = Okɔnɔre Yaa / Aso; Ba panyin = Ntikuma."
      },
      {
        "id": "jhs2-twi-t8-q3",
        "quizId": "quiz-jhs2-twi-t8-anansesɛm-agoru",
        "questionText": "Dɛn ne Mmoguo (Storytelling interludes / songs) dwumadi kɛse wɔ anansesɛm mu?",
        "optionA": "Ɛma atiefo ahomegye, ɛma agorɔ no yɛ anigye, na ɛbɔ asɛm no ti kyerɛ",
        "optionB": "Ɛpam atiefo ma wɔkɔ da",
        "optionC": "Ɛsɛe anansesɛm no ahyɛase",
        "optionD": "Ɛma anansesɛm no gyae ntɛm",
        "correctOption": "A",
        "subConcept": "Akanfo Anansesɛm ne Mmoguo",
        "explanation": "Mmoguo kanyan atiefo anigye, ɛma wɔhome fi anansesɛm tenten akenkan mu, na ɛka asɛm no mfitiase anaa afotu no toatoa so.",
        "remediationTip": "Mmoguo yɛ dwom a wɔto wɔ anansesɛm akyi de kanyan atiefo na ɛhyɛ nkyerɛkyerɛ mu den."
      },
      {
        "id": "jhs2-twi-t8-q4",
        "quizId": "quiz-jhs2-twi-t8-anansesɛm-agoru",
        "questionText": "Sɛ obi reto ananse a, asɛm bɛn na ɔde bɔ atiefo amanneɛ?",
        "optionA": "Yɛnse sɛ, nse sɛ o!",
        "optionB": "M'adwo mo nyinaa!",
        "optionC": "Monkɔ fie!",
        "optionD": "Monntie me koraa!",
        "correctOption": "A",
        "subConcept": "Akanfo Anansesɛm ne Mmoguo",
        "explanation": "Otwerɛfo anaa okasani no ka sɛ 'Yɛnse sɛ, nse sɛ o!' na atiefo nso agye so sɛ 'Yensa so o!' de akyerɛ sɛ wɔwɔ hɔ retie.",
        "remediationTip": "Anansesɛm ahyɛase kasa: 'Yɛnse sɛ, nse sɛ o!' -> 'Yensa so o!'"
      },
      {
        "id": "jhs2-twi-t8-q5",
        "quizId": "quiz-jhs2-twi-t8-anansesɛm-agoru",
        "questionText": "Anansesɛm mu, suban bɛn na Kwaku Ananse kuta a Akanfo taa bɔ ho kɔkɔ?",
        "optionA": "Adifudepɛ, nkontompo ne pɛsɛmenkominya",
        "optionB": "Ahobrɛase ne ayamye",
        "optionC": "Akokoduru ne nokwaredi",
        "optionD": "Akuafo su",
        "correctOption": "A",
        "subConcept": "Akanfo Anansesɛm ne Mmoguo",
        "explanation": "Kwaku Ananse taa nya anifere a adifudepɛ ne pɛsɛmenkominya wom, na awiei koraa no ne ho kɔtɔ asɛm mu de ma afotu.",
        "remediationTip": "Ananse suban kyerɛ asotwe a ɛbata adifudepɛ ne pɛsɛmenkominya akyi."
      },
      {
        "id": "jhs2-twi-t8-q6",
        "quizId": "quiz-jhs2-twi-t8-anansesɛm-agoru",
        "questionText": "Akanfo agorukrɔnkrɔn (indigenous game) bɛn na wɔde dade kɔɔpɔ anaa nnua abaa na ɛbɔ?",
        "optionA": "Ɔware",
        "optionB": "Bɔɔlbɔ",
        "optionC": "Ampe",
        "optionD": "Ludo",
        "correctOption": "A",
        "subConcept": "Akanfo Anansesɛm ne Mmoguo",
        "explanation": "Ɔware yɛ agoru kɛse a wɔde dua a wɔasen tokuro dumien ne aba (nkyekyerew) na ɛbɔ a nyansapɛ ne akontabuo wom.",
        "remediationTip": "Ɔware yɛ Akan amammerɛ agorukrɔnkrɔn a akontabuo ne akokoduru wom."
      },
      {
        "id": "jhs2-twi-t8-q7",
        "quizId": "quiz-jhs2-twi-t8-anansesɛm-agoru",
        "questionText": "Mmmaa agoru bɛn na wɔde mmirika, ahurisie ne nsam-bɔ na ɛbɔ wɔ awiabere anaa anwummere?",
        "optionA": "Ampe",
        "optionB": "Ɔware",
        "optionC": "Dami",
        "optionD": "Ka-bi-ma-menka-bi",
        "correctOption": "A",
        "subConcept": "Akanfo Anansesɛm ne Mmoguo",
        "explanation": "Ampe yɛ mmaayewa agoru kɛse a wɔhuri kɔ soro bɔ wɔn nsa teɛ wɔn nan baako gu anim ma wɔkan nkontaa.",
        "remediationTip": "Ampe yɛ Akan mmaayewa agoru a ahokeka, ahurisie ne akontabuo wom."
      },
      {
        "id": "jhs2-twi-t8-q8",
        "quizId": "quiz-jhs2-twi-t8-anansesɛm-agoru",
        "questionText": "Dɛn na Akanfo anansesɛm de ba awiei daa?",
        "optionA": "Asuade anaa afotu (Moral lesson) a akenkanfo nya",
        "optionB": "Owuo nkutoo",
        "optionC": "Sika kɛse a wɔkyɛ",
        "optionD": "Ahenkwaa baako pɛ din",
        "correctOption": "A",
        "subConcept": "Akanfo Anansesɛm ne Mmoguo",
        "explanation": "Anansesɛm biara ba awiei no, wɔka asuade anaa afotu a ɛbɛma mmɔfra anya suban pa na wɔakwati anifere bɔne.",
        "remediationTip": "Anansesɛm botae kɛse ne sɛ ɛbɛma afotu ne asuade pa akyerɛ mmɔfra."
      },
      {
        "id": "jhs2-twi-t8-q9",
        "quizId": "quiz-jhs2-twi-t8-anansesɛm-agoru",
        "questionText": "Hena ne Kwaku Ananse ba panyin a ɔkuta nyansa ne obu wɔ anansesɛm mu?",
        "optionA": "Ntikuma",
        "optionB": "Afurudohwedohwe",
        "optionC": "Tikokroko",
        "optionD": "Nanankoroma",
        "correctOption": "A",
        "subConcept": "Akanfo Anansesɛm ne Mmoguo",
        "explanation": "Ntikuma ne Kwaku Ananse ba panyin a ɔtaa hu Ananse nkontompo ne n'anifere nyinaa na ɔpam no.",
        "remediationTip": "Ananse mma: Ntikuma, Tikokroko, Nankonhwea, Afurudohwedohwe."
      },
      {
        "id": "jhs2-twi-t8-q10",
        "quizId": "quiz-jhs2-twi-t8-anansesɛm-agoru",
        "questionText": "Dɛn nti na Akanfo mmɔ anansesɛm awia kɛse?",
        "optionA": "Wɔkuta gyidi sɛ sɛ wobɔ anansesɛm awia a, wo maame anaa wo papa bɛyera anaa wobɛyɛ kɛkɛw",
        "optionB": "Efisɛ sukuu kɔ so",
        "optionC": "Efisɛ owia hyɛ kɛse",
        "optionD": "Efisɛ obiara nni hɔ",
        "correctOption": "A",
        "subConcept": "Akanfo Anansesɛm ne Mmoguo",
        "explanation": "Akanfo kuta akyiwade sɛ wɔmmɔ anansesɛm awia efisɛ awiabere yɛ adwumayɛ bere, na gyidi a ɛwɔ akyi kyerɛ sɛ ɛbɛde mfuturo aba.",
        "remediationTip": "Akanfo bɔ anansesɛm anadwo bere a wɔawie adwuma nyinaa ahomegye bere mu."
      }
    ]
  },
  "jhs2-twi-t9-abosom-nananom-nsamanfo": {
    "id": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
    "topicId": "jhs2-twi-t9-abosom-nananom-nsamanfo",
    "title": "Akanfo Gyidi ne Som BECE Nsɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs2-twi-t9-q1",
        "quizId": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
        "questionText": "Akanfo gyidi mu, hena ne Ɔbɔadeɛ a ɔbɔɔ soro ne asase ne biribiara?",
        "optionA": "Tweduampɔn Kwame / Onyankopɔn",
        "optionB": "Tano",
        "optionC": "Asase Yaa",
        "optionD": "Nsamanfo",
        "correctOption": "A",
        "subConcept": "Akanfo Gyidi ne Som",
        "explanation": "Onyankopɔn (Tweduampɔn Kwame, Onyame, Ɔdomankoma) ne Ɔbɔadeɛ Kɛse a ɔwɔ soro a ɔyɛ biribiara Fitiase.",
        "remediationTip": "Onyankopɔn din ahodoɔ: Tweduampɔn Kwame, Ɔbɔadeɛ, Ɔdomankoma, Tetekwaframoa."
      },
      {
        "id": "jhs2-twi-t9-q2",
        "quizId": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
        "questionText": "Asase Yaa yɛ dɛn wɔ Akanfo gyidi ne amammere mu?",
        "optionA": "Asase Honhom a ɔkyerɛ awoɔ, kuayɛ ne aduane ma nnipa",
        "optionB": "Ɔsoro Bosome",
        "optionC": "Abosom baako pɛ",
        "optionD": "Nsaman panyin",
        "correctOption": "A",
        "subConcept": "Akanfo Gyidi ne Som",
        "explanation": "Asase Yaa yɛ asaase honhom a ɔwɔ tumi wɔ asase a wɔdɔw so no so, na Akanfo bu no kɛse na wonkɔ afuom Yawoada anaa wonsɛe asase.",
        "remediationTip": "Asase Yaa: ne da yɛ Yawoada; obi ntu asase anaa nndɔw afuw saa da no koraa."
      },
      {
        "id": "jhs2-twi-t9-q3",
        "quizId": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
        "questionText": "Hena na yɛfrɛ no 'Nsamanfo' wɔ Akanfo asetenam?",
        "optionA": "Nananom a wɔtenaa ase yiye na wanya owuo pa akɔ asamando",
        "optionB": "Nnipa bɔne a wɔawu akwanhyia mu",
        "optionC": "Mmɔfra a wɔawu da a wɔwoo wɔn",
        "optionD": "Abosom a ɛwɔ wuram",
        "correctOption": "A",
        "subConcept": "Akanfo Gyidi ne Som",
        "explanation": "Nsamanfo (Ancestors) yɛ nananom mpanyimfo a wɔbɔɔ bra pa, woo mma na wowuu owuo pa kɔɔ Asamando na wɔhwɛ abusua no so.",
        "remediationTip": "Nsamanfo yɛ nananom a wɔwɔ Asamando a wɔbɔ abusua no ho ban na wogye mpaebɔ."
      },
      {
        "id": "jhs2-twi-t9-q4",
        "quizId": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
        "questionText": "Nsamgu (Libation) amammere kuta dɛn?",
        "optionA": "Nsa anaa nsuo a wɔgu fam de bɔ mpae frɛ Onyame, Asase Yaa ne Nananom Nsamanfo",
        "optionB": "Nsa a wɔnom awia kɛse",
        "optionC": "Adidie a wɔyɛ anadwo",
        "optionD": "Dwom a wɔto wɔ afahyɛ mu",
        "correctOption": "A",
        "subConcept": "Akanfo Gyidi ne Som",
        "explanation": "Nsamgu yɛ mpaebɔ amammere kɛse a wɔka asɛm de nsa anaa nsuo gu fam frɛ Onyankopɔn, abosom ne nananom nsamanfo sɛ wonhyira wɔn.",
        "remediationTip": "Nsamgu/Apaebɔ fa nsa anaa nsuo so ka honhom fam ade ne asetenam bom."
      },
      {
        "id": "jhs2-twi-t9-q5",
        "quizId": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
        "questionText": "Abosom bɛn na yɛtaa hu wɔ Akanfo mu te sɛ Tano, Bosomtwe ne Bia?",
        "optionA": "Abosom a wɔte asubɔnten, mmepɔw anaa atare akɛse mu (Atano / Abosom)",
        "optionB": "Abosom a wɔkyere afie",
        "optionC": "Nkuro ahodoɔ akyɛde",
        "optionD": "Abusua kɛse bi",
        "correctOption": "A",
        "subConcept": "Akanfo Gyidi ne Som",
        "explanation": "Akan abosom pii te sɛ Tano, Densu, Pra, Bosomtwe gyina nsubɔnten, atare ne abo akɛse a wɔbu no sɛ Nyame asomafo.",
        "remediationTip": "Abosom yɛ Onyankopɔn asomafo wɔ Akan gyidi mu a wɔhwɛ asase ne nsubɔnten so."
      },
      {
        "id": "jhs2-twi-t9-q6",
        "quizId": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
        "questionText": "Ɔkɔmfo dwumadi bɛn na ɔyɛ wɔ abosom som mu?",
        "optionA": "Ɔyɛ ntamgyinafo wɔ nnipa ne abosom ntam na ɔsa nyarewa",
        "optionB": "Ɔyɛ sukuuni panyin",
        "optionC": "Ɔkɔ dwa mu kɔtɔ nneɛma",
        "optionD": "Ɔtwerɛ nwoma ma aban",
        "correctOption": "A",
        "subConcept": "Akanfo Gyidi ne Som",
        "explanation": "Ɔkɔmfo yɛ onipa a abosom ba ne so a ɔbɔ amanneɛ fi honhom fam ma nnipa na ɔtumi sa yare kyerɛ abusuafo.",
        "remediationTip": "Ɔkɔmfo / Ɔsɔfo yɛ ntamgyinafo wɔ sunsum fam ne nnipa ntam."
      },
      {
        "id": "jhs2-twi-t9-q7",
        "quizId": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
        "questionText": "Dɛn na Akanfo frɛ baabi a Nsamanfo te?",
        "optionA": "Asamando",
        "optionB": "Abɔnten",
        "optionC": "Soro kɛse",
        "optionD": "Akyi kuro",
        "correctOption": "A",
        "subConcept": "Akanfo Gyidi ne Som",
        "explanation": "Akanfo gyidi sɛ baabi a nsamanfo kɔtena bere a wɔawu no ne Asamando.",
        "remediationTip": "Asamando yɛ nananom nsamanfo tenabea wɔ honhom mu."
      },
      {
        "id": "jhs2-twi-t9-q8",
        "quizId": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
        "questionText": "Dɛn ne asotwe a obi a obu amammere akyiwade so nya fi nsamanfo anaa kurow no hɔ?",
        "optionA": "Musuo, ayiyare anaa afobu a obetua guankoɔ",
        "optionB": "Sika kɛse a wɔkyɛ no",
        "optionC": "Ahenkye a wɔde bɛbɔ no",
        "optionD": "Ahotɔ daa",
        "correctOption": "A",
        "subConcept": "Akanfo Gyidi ne Som",
        "explanation": "Sɛ obi bu akyiwade (taboo) so a, wogye di sɛ ɔde musuo reba abusua no so, enti ɛsɛ sɛ ɔtua guankoɔ anaa nsamgu de pata abosom no.",
        "remediationTip": "Akyiwade a wobu so de musuo ba; enti wɔpata ma asomdwoe ba bio."
      },
      {
        "id": "jhs2-twi-t9-q9",
        "quizId": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
        "questionText": "Kyerɛ afã baako a Akanfo fa so bu Onyankopɔn sɛ Ɔbɔadeɛ a Ɔsen Biribiara:",
        "optionA": "Abosom nyinaa hyɛ N'ase na N'ankasa nni abosodan baabiara pɔtee efisɛ Ɔwɔ baabiara",
        "optionB": "Wɔyɛ Ne ho mfonini gu afie mu",
        "optionC": "Ɔda dua mu nkutoo",
        "optionD": "Wɔnom nsa ma no anadwo pɛ",
        "correctOption": "A",
        "subConcept": "Akanfo Gyidi ne Som",
        "explanation": "Akanfo nsi abosodan nsi abosom ma Onyankopɔn efisɛ Ɔsen biribiara na Ɔte baabiara bere koro mu (Omnipresent).",
        "remediationTip": "Akanfo daa gyidi kyerɛ sɛ Onyankopɔn kɛseyɛ nti, obi nsi dan nsie No."
      },
      {
        "id": "jhs2-twi-t9-q10",
        "quizId": "quiz-jhs2-twi-t9-abosom-nananom-nsamanfo",
        "questionText": "Mfaso bɛn na Akanfo gyidi wɔ nsamanfo mu de ba asetenam?",
        "optionA": "Ɛkanyan nnipa ma wɔbɔ bra pa na wɔyɛ nokware na wɔanhu aniwuo asetenam",
        "optionB": "Ɛma nnipa yɛ akorɔmfo",
        "optionC": "Ɛma obiara gyae adwumayɛ",
        "optionD": "Ɛsɛe amanmmerɛ nyinaa",
        "correctOption": "A",
        "subConcept": "Akanfo Gyidi ne Som",
        "explanation": "Gyidi a Akanfo wɔ sɛ nsamanfo hwɛ wɔn bra daa no ma obiara bɔ mmɔden yɛ papa, bu mpanyimfo na ɔkwati bɔne.",
        "remediationTip": "Nsamanfo gyidi hyɛ suban pa, nokwaredi ne abusua biakoyɛ den."
      }
    ]
  },
  "jhs2-twi-t10-afahyɛ-ne-asaw": {
    "id": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
    "topicId": "jhs2-twi-t10-afahyɛ-ne-asaw",
    "title": "Akanfo Afahyɛ ne Asaw BECE Nsɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs2-twi-t10-q1",
        "quizId": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
        "questionText": "Afahyɛ bɛn na Akuapemfo ne Akwamufo di de hyɛ ahotɔ, abusua biakoyɛ ne odwira ahotew bere agyirae?",
        "optionA": "Odwira Afahyɛ",
        "optionB": "Homowo",
        "optionC": "Hogbetsotso",
        "optionD": "Kundum",
        "correctOption": "A",
        "subConcept": "Akanfo Afahyɛ ne Asaw",
        "explanation": "Odwira afahyɛ yɛ Akuapemfo ne Akwamufo afahyɛ kɛse a wɔdi de tew ɔman no ho fi fi ne akyiwade ho na wɔda nananom ase.",
        "remediationTip": "Odwira = Akuapemfo ne Akwamufo afahyɛ a wɔde tew kuro no ho fi musuo ho."
      },
      {
        "id": "jhs2-twi-t10-q2",
        "quizId": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
        "questionText": "Akwasidae afahyɛ a Asantehene ne Akanfo ahemfo taa di no ba mfe no mu mmere ahe biara?",
        "optionA": "Nnafua aduanan mmienu (42 days) biara",
        "optionB": "Bosome dumien biara",
        "optionC": "Kwasiada biara",
        "optionD": "Mfe mmienu biara",
        "correctOption": "A",
        "subConcept": "Akanfo Afahyɛ ne Asaw",
        "explanation": "Akwasidae ba nnafua aduanan mmienu (42 days) biara wɔ Akan adaedae kalenda mu a ahemfo de kɔ nkonguafie kɔhyira nkonnwa tuntum.",
        "remediationTip": "Akwasidae = nna 42 biara; Adaedae kuta Awukudae ne Akwasidae."
      },
      {
        "id": "jhs2-twi-t10-q3",
        "quizId": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
        "questionText": "Afahyɛ bɛn na Akyemfo di de gye ahome na wɔde hyɛ aburow ne bayerɛ foforo bere agyirae?",
        "optionA": "Ohum Afahyɛ (Ohumkan ne Ohumkyire)",
        "optionB": "Damba",
        "optionC": "Aboakyer",
        "optionD": "Fetu Afahye",
        "correctOption": "A",
        "subConcept": "Akanfo Afahyɛ ne Asaw",
        "explanation": "Akyemfo di Ohum afahyɛ (Ohumkan ne Ohumkyire) de da Onyankopɔn ne abosom ase wɔ nnɔbae foforo ho.",
        "remediationTip": "Ohum = Akyemfo afahyɛ; Odwira = Akuapemfo; Akwasidae = Asantefo; Aboakyer = Effutu (Winneba)."
      },
      {
        "id": "jhs2-twi-t10-q4",
        "quizId": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
        "questionText": "Asaw a agye din a mmaa ne mmarima saw no brɛoo a nsa kankyee kyerɛ asɛm pii wɔ Akanfo mu ne:",
        "optionA": "Adowa",
        "optionB": "Apatampa",
        "optionC": "Agbadza",
        "optionD": "Kpalogo",
        "correctOption": "A",
        "subConcept": "Akanfo Afahyɛ ne Asaw",
        "explanation": "Adowa yɛ asaw kɛse a agye din wɔ Akanfo mu a wɔsaw no brɛoo de nsa ne nan nneyɛe kyerɛ atenka ne asɛm kɛse.",
        "remediationTip": "Adowa asaw: Nsa kankyee kyerɛ obu, awerɛhow, anigye anaa ahotɔ."
      },
      {
        "id": "jhs2-twi-t10-q5",
        "quizId": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
        "questionText": "Twene kɛse bɛn na wɔka bom bɔ ma ahemfo akɛse saw nnamnnam wɔ ahemfi nhyiam kɛse ase?",
        "optionA": "Fontomfrom (Bɔmmaa ne Atumpan)",
        "optionB": "Dondo",
        "optionC": "Pɛtɛ",
        "optionD": "Pataraku",
        "correctOption": "A",
        "subConcept": "Akanfo Afahyɛ ne Asaw",
        "explanation": "Fontomfrom ne twene kɛse a ahemfo ka ho bɔ a ɛyɛ dɛ na ɛkuta tumi kɛse a ahemfo nko ara na wɔtaa saw wɔ bagua mu.",
        "remediationTip": "Fontomfrom yɛ ahemfo ne atitiriw twene kɛse a Bɔmmaa ne Atumpan ka ho."
      },
      {
        "id": "jhs2-twi-t10-q6",
        "quizId": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
        "questionText": "Dɛn ne twene a wɔfrɛ no 'Atumpan' dwumadi titiriw wɔ ahemfi?",
        "optionA": "Twene a ɛkasa (Talking drum) a wɔde bɔ ahemfo abodin ne amanneɛbɔ",
        "optionB": "Wɔde pam mmɔfra",
        "optionC": "Wɔde kan sika",
        "optionD": "Ɛyɛ agoru hunu",
        "correctOption": "A",
        "subConcept": "Akanfo Afahyɛ ne Asaw",
        "explanation": "Atumpan yɛ twene a ɛkasa a ɛtumi susuw Twi kasamua pɛpɛɛpɛ de bɔ amanneɛ, hyɛ hene animuonyam na ɛbɔ mmɛbusɛm.",
        "remediationTip": "Atumpan = Kasa twene (Talking drum) a ɛkasa Akan kasa pɛpɛɛpɛ."
      },
      {
        "id": "jhs2-twi-t10-q7",
        "quizId": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
        "questionText": "Kete asaw yɛ asaw a henanom na wɔtaa saw wɔ ahemfi?",
        "optionA": "Ahemfo, ahemaa ne adehye wɔ ahemfi amammere ase",
        "optionB": "Abɔfra kumaa biara",
        "optionC": "Ahɔho a wɔba sukuu",
        "optionD": "Akuafo nko ara",
        "correctOption": "A",
        "subConcept": "Akanfo Afahyɛ ne Asaw",
        "explanation": "Kete yɛ ahemfi asaw kronkron a ahemaa ne adehye saw no fɛfɛɛfɛ wɔ kete sankuo ne twene nnyigyei ase.",
        "remediationTip": "Kete asaw yɛ ahemfi asaw fɛfɛ a adehye ne ahemaa de kyerɛ ahobrɛase ne animuonyam."
      },
      {
        "id": "jhs2-twi-t10-q8",
        "quizId": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
        "questionText": "Dɛn ne mfaso titiriw a afahyɛ de brɛ ɔman anaa kuro bi?",
        "optionA": "Abusua nkabom, mpuntudwuma sika boaboa ano, ne amammere kura mu",
        "optionB": "Akasakasa ne ntɔkwa kɛse",
        "optionC": "Afuo a wɔbɛsɛe no nyinaa",
        "optionD": "Sukuu a wɔbɛto mu daa",
        "correctOption": "A",
        "subConcept": "Akanfo Afahyɛ ne Asaw",
        "explanation": "Afahyɛ de nkabom ba, ɛma mmapɔmma bɔ mu siesie kuro no ho mpuntudwuma na ɛma amammerɛ tena hɔ daa.",
        "remediationTip": "Afahyɛ mfaso: Nkabom, mpuntudwuma (development projects), ne amammere ahobanbɔ."
      },
      {
        "id": "jhs2-twi-t10-q9",
        "quizId": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
        "questionText": "Wɔ afahyɛ bere mu, dɛn na ɔhene yɛ de kyerɛ sɛ ɔne ne manfo wɔ asomdwoe ne biakoyɛ mu?",
        "optionA": "Ɔtene kwan hyia ne manfo, gu nsa hyira wɔn, na ɔdi adidie bom ne wɔn",
        "optionB": "Ɔkata ne pon mu gu ne fiefo so",
        "optionC": "Ɔpam ahɔho nyinaa kɔ",
        "optionD": "Ɔbɔ n'asuafo tuo",
        "correctOption": "A",
        "subConcept": "Akanfo Afahyɛ ne Asaw",
        "explanation": "Ɔhene ba bagua mu a ne manfo kyea no, ɔbɔ apam bio ma asomdwoe tena kuro no mu na ɔda anigye adi.",
        "remediationTip": "Ahemfo bagua ne ahotɔ ma biakoyɛ ne dɔ kɔ anim wɔ Akanfo amammere mu."
      },
      {
        "id": "jhs2-twi-t10-q10",
        "quizId": "quiz-jhs2-twi-t10-afahyɛ-ne-asaw",
        "questionText": "Sɛ obi resaw Fontomfrom a, dɛn na ɛsɛ sɛ ɔyɛ ansa na wafi ase asaw?",
        "optionA": "Ɔbɔ nsam koto twenebɔfo no de kyerɛ obu na ɔwura asaw no mu brɛoo",
        "optionB": "Ɔtu mmirika hyɛ ase ntɛmntɛm",
        "optionC": "Ɔsi twene no mu bɔkɔɔ",
        "optionD": "Ɔka atumpan no gu fam",
        "correctOption": "A",
        "subConcept": "Akanfo Afahyɛ ne Asaw",
        "explanation": "Fontomfrom asaw hwehwɛ obu kɛse; obi koto kyea twene no ansa na wafi ase asaw sɛnea amammere ahyɛde teɛ.",
        "remediationTip": "Fontomfrom asaw obu kwan: Kotow kyea twenebɔfo no ansa na woasaw."
      }
    ]
  }
};
