// Ghanaian JHS 2 French Language Diagnostic & BECE Quizzes
// 12 Topics x 10 Questions = 120 High-Yield BECE-style Multiple-Choice Questions
// Tagged with subConcept, detailed explanation, and remediationTip

import { TopicQuiz } from './types';

export const JHS2_FRENCH_QUIZZES: Record<string, TopicQuiz> = {
  "jhs2-fre-t1-saluer-se-presenter": {
    "id": "quiz-jhs2-fre-t1-saluer-se-presenter",
    "topicId": "jhs2-fre-t1-saluer-se-presenter",
    "title": "Les Salutations et Présentations Approfondies BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t1-1",
        "quizId": "quiz-jhs2-fre-t1-saluer-se-presenter",
        "questionText": "Quelle formule de salutation convient le mieux le matin lorsqu'on s'adresse poliment à son directeur d'école ?",
        "optionA": "Salut !",
        "optionB": "Bonjour, Monsieur le Directeur !",
        "optionC": "Bonne nuit, mon ami !",
        "optionD": "Coucou, monsieur !",
        "correctOption": "B",
        "subConcept": "Salutations formelles",
        "explanation": "Avec une figure d'autorité comme un directeur, on utilise la formule de politesse formelle 'Bonjour, Monsieur le Directeur' au lieu de termes informels.",
        "remediationTip": "Utilisez 'Bonjour Monsieur' pour vous adresser respectueusement aux adultes."
      },
      {
        "id": "q-jhs2fre-t1-2",
        "quizId": "quiz-jhs2-fre-t1-saluer-se-presenter",
        "questionText": "Comment dit-on correctement en français : 'I am fourteen years old' ?",
        "optionA": "Je suis quatorze ans.",
        "optionB": "J'ai quatorze ans.",
        "optionC": "Je fais quatorze ans.",
        "optionD": "J'habite quatorze ans.",
        "correctOption": "B",
        "subConcept": "Expression de l'âge",
        "explanation": "En français, on exprime l'âge avec le verbe AVOIR ('J'ai 14 ans'), contrairement à l'anglais qui utilise le verbe être ('I am 14').",
        "remediationTip": "Retenez: En français, on A un âge (verbe avoir), on ne l'est pas."
      },
      {
        "id": "q-jhs2fre-t1-3",
        "quizId": "quiz-jhs2-fre-t1-saluer-se-presenter",
        "questionText": "Si Kofi habite au Ghana, quelle est sa nationalité au masculin ?",
        "optionA": "ghanéenne",
        "optionB": "ghanéen",
        "optionC": "ghanaise",
        "optionD": "ghanéens",
        "correctOption": "B",
        "subConcept": "Nationalité masculine",
        "explanation": "Au masculin singulier, un citoyen du Ghana est 'ghanéen'. La forme 'ghanéenne' est le féminin.",
        "remediationTip": "Kofi est ghanéen (masculin); Ama est ghanéenne (féminin)."
      },
      {
        "id": "q-jhs2fre-t1-4",
        "quizId": "quiz-jhs2-fre-t1-saluer-se-presenter",
        "questionText": "Quelle préposition utilise-t-on devant un nom de ville comme Accra ou Kumasi ?",
        "optionA": "au",
        "optionB": "en",
        "optionC": "à",
        "optionD": "du",
        "correctOption": "C",
        "subConcept": "Préposition de lieu devant ville",
        "explanation": "Les noms de villes prennent toujours la préposition 'à' (ex: à Accra, à Kumasi, à Paris).",
        "remediationTip": "On utilise toujours 'à' devant les villes: J'habite à Kumasi."
      },
      {
        "id": "q-jhs2fre-t1-5",
        "quizId": "quiz-jhs2-fre-t1-saluer-se-presenter",
        "questionText": "Complétez : 'Chers amis, je vous ... mon camarade de classe, Kwame.'",
        "optionA": "appelle",
        "optionB": "présente",
        "optionC": "salut",
        "optionD": "demande",
        "correctOption": "B",
        "subConcept": "Présenter autrui",
        "explanation": "La structure formelle pour présenter quelqu'un à un groupe est 'Je vous présente...'.",
        "remediationTip": "'Je vous présente [Nom]' sert à introduire une tierce personne."
      },
      {
        "id": "q-jhs2fre-t1-6",
        "quizId": "quiz-jhs2-fre-t1-saluer-se-presenter",
        "questionText": "Que dit-on à un ami que l'on retrouvera le lendemain en classe ?",
        "optionA": "Bonne nuit !",
        "optionB": "À demain !",
        "optionC": "Adieu pour toujours !",
        "optionD": "À l'année prochaine !",
        "correctOption": "B",
        "subConcept": "Prise de congé",
        "explanation": "'À demain !' signifie 'See you tomorrow', adapté lorsqu'on revoit la personne le jour suivant.",
        "remediationTip": "'À demain' = See you tomorrow."
      },
      {
        "id": "q-jhs2fre-t1-7",
        "quizId": "quiz-jhs2-fre-t1-saluer-se-presenter",
        "questionText": "Conjuguez correctement le verbe s'appeler : 'Comment ...-tu ?'",
        "optionA": "t'appelles",
        "optionB": "s'appelle",
        "optionC": "vous appelez",
        "optionD": "t'appelle",
        "correctOption": "A",
        "subConcept": "Conjugaison de s'appeler",
        "explanation": "Avec le pronom 'tu', la terminaison régulière des verbes en -er prend un 's': 'Comment t'appelles-tu ?'.",
        "remediationTip": "Tu t'appelles (avec -es à la fin)."
      },
      {
        "id": "q-jhs2fre-t1-8",
        "quizId": "quiz-jhs2-fre-t1-saluer-se-presenter",
        "questionText": "Quelle formule est appropriée pour demander poliment l'état de santé d'un aîné ?",
        "optionA": "Ça gaze ?",
        "optionB": "Comment allez-vous, Monsieur ?",
        "optionC": "Quoi de neuf ?",
        "optionD": "Tu es malade ?",
        "correctOption": "B",
        "subConcept": "Vouvoiement de politesse",
        "explanation": "Le vouvoiement ('Comment allez-vous ?') exprime le respect exigé envers les personnes âgées ou supérieures.",
        "remediationTip": "Utilisez 'Comment allez-vous ?' avec les adultes pour marquer le respect."
      },
      {
        "id": "q-jhs2fre-t1-9",
        "quizId": "quiz-jhs2-fre-t1-saluer-se-presenter",
        "questionText": "Quelle expression signifie 'Pleased to meet you' lorsqu'on rencontre quelqu'un pour la première fois ?",
        "optionA": "Enchanté !",
        "optionB": "Merci beaucoup !",
        "optionC": "S'il vous plaît !",
        "optionD": "De rien !",
        "correctOption": "A",
        "subConcept": "Expressions de politesse",
        "explanation": "'Enchanté !' (ou 'Enchantée !' pour une femme) est l'équivalent français de 'Pleased to meet you / Nice to meet you'.",
        "remediationTip": "'Enchanté' s'utilise lors d'une première présentation."
      },
      {
        "id": "q-jhs2fre-t1-10",
        "quizId": "quiz-jhs2-fre-t1-saluer-se-presenter",
        "questionText": "À quel moment de la journée dit-on 'Bonsoir !' ?",
        "optionA": "À six heures du matin",
        "optionB": "À midi pile",
        "optionC": "En fin d'après-midi et pendant la soirée (à partir de 18 heures)",
        "optionD": "Uniquement le dimanche matin",
        "correctOption": "C",
        "subConcept": "Moments de la journée",
        "explanation": "'Bonsoir' s'utilise à partir de la fin d'après-midi (vers 18h) et durant toute la soirée.",
        "remediationTip": "Bonjour = matin/après-midi; Bonsoir = à partir de 18h."
      }
    ]
  },
  "jhs2-fre-t2-famille-relations": {
    "id": "quiz-jhs2-fre-t2-famille-relations",
    "topicId": "jhs2-fre-t2-famille-relations",
    "title": "La Famille et les Liens de Parenté BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t2-1",
        "quizId": "quiz-jhs2-fre-t2-famille-relations",
        "questionText": "Qui est le frère de mon père ou de ma mère ?",
        "optionA": "mon grand-père",
        "optionB": "mon oncle",
        "optionC": "mon cousin",
        "optionD": "mon neveu",
        "correctOption": "B",
        "subConcept": "Liens de parenté",
        "explanation": "Le frère du père ou de la mère est l'oncle (uncle).",
        "remediationTip": "Frère de ton père ou de ta mère = ton oncle."
      },
      {
        "id": "q-jhs2fre-t2-2",
        "quizId": "quiz-jhs2-fre-t2-famille-relations",
        "questionText": "Complétez correctement : 'Akosua va à l'église avec ... mère.'",
        "optionA": "son",
        "optionB": "sa",
        "optionC": "ses",
        "optionD": "leur",
        "correctOption": "B",
        "subConcept": "Adjectifs possessifs féminins",
        "explanation": "'mère' est un nom féminin singulier. L'adjectif possessif pour 'il/elle' au féminin singulier est 'sa'.",
        "remediationTip": "L'adjectif possessif s'accorde avec le nom possédé: 'sa mère' (mère est féminin)."
      },
      {
        "id": "q-jhs2fre-t2-3",
        "quizId": "quiz-jhs2-fre-t2-famille-relations",
        "questionText": "Pourquoi dit-on 'mon amie' et non 'ma amie', bien que 'amie' soit un nom féminin ?",
        "optionA": "Parce que 'amie' est un mot étranger",
        "optionB": "Pour éviter la rencontre de deux voyelles (hiatus phonétique)",
        "optionC": "Parce que le sujet est masculin",
        "optionD": "C'est une erreur de grammaire",
        "correctOption": "B",
        "subConcept": "Élision possessive devant voyelle",
        "explanation": "Devant un nom féminin commençant par une voyelle ou un 'h' muet, 'ma, ta, sa' deviennent 'mon, ton, son' pour la fluidité sonore.",
        "remediationTip": "Devant une voyelle, utilisez mon/ton/son même pour un nom féminin (mon amie, son école)."
      },
      {
        "id": "q-jhs2fre-t2-4",
        "quizId": "quiz-jhs2-fre-t2-famille-relations",
        "questionText": "Comment appelle-t-on la fille de mon oncle ou de ma tante ?",
        "optionA": "ma nièce",
        "optionB": "ma sœur",
        "optionC": "ma cousine",
        "optionD": "ma grand-mère",
        "correctOption": "C",
        "subConcept": "Liens de parenté",
        "explanation": "L'enfant d'un oncle ou d'une tante est un cousin (garçon) ou une cousine (fille).",
        "remediationTip": "Fille de l'oncle/tante = ta cousine."
      },
      {
        "id": "q-jhs2fre-t2-5",
        "quizId": "quiz-jhs2-fre-t2-famille-relations",
        "questionText": "Complétez avec le bon possessif pluriel : 'Kofi et Ama aiment beaucoup ... parents.'",
        "optionA": "leur",
        "optionB": "leurs",
        "optionC": "ses",
        "optionD": "nos",
        "correctOption": "B",
        "subConcept": "Possessif pluriel (ils/elles)",
        "explanation": "Le sujet est 'ils' (Kofi et Ama) et le nom possédé est au pluriel ('parents') -> 'leurs parents'.",
        "remediationTip": "Leur + singulier (leur maison); Leurs + pluriel (leurs parents)."
      },
      {
        "id": "q-jhs2fre-t2-6",
        "quizId": "quiz-jhs2-fre-t2-famille-relations",
        "questionText": "Que signifie le mot 'fils' en anglais et comment le prononce-t-on ?",
        "optionA": "Daughter, prononcé /fil/",
        "optionB": "Son, prononcé /fis/ (le 'l' est muet)",
        "optionC": "Brother, prononcé /filz/",
        "optionD": "Father, prononcé /fis/",
        "correctOption": "B",
        "subConcept": "Prononciation de fils",
        "explanation": "'Fils' signifie 'son' et se prononce /fis/ (avec 's' sonore et 'l' muet).",
        "remediationTip": "'Fils' = son, prononcé /fis/ sans le son 'l'."
      },
      {
        "id": "q-jhs2fre-t2-7",
        "quizId": "quiz-jhs2-fre-t2-famille-relations",
        "questionText": "Comment appelle-t-on le premier enfant né dans une famille ?",
        "optionA": "le benjamin",
        "optionB": "l'aîné (ou l'aînée)",
        "optionC": "le jumeau",
        "optionD": "le cousin",
        "correctOption": "B",
        "subConcept": "Ordre de naissance",
        "explanation": "Le premier-né est 'l'aîné' (masc.) ou 'l'aînée' (fém.). Le dernier-né est 'le benjamin' ou 'la benjamine'.",
        "remediationTip": "Premier enfant = aîné(e); dernier enfant = benjamin(e)."
      },
      {
        "id": "q-jhs2fre-t2-8",
        "quizId": "quiz-jhs2-fre-t2-famille-relations",
        "questionText": "Complétez : 'Monsieur et Madame Mensah ont trois enfants : deux ... et une fille.'",
        "optionA": "garçons",
        "optionB": "fils",
        "optionC": "pères",
        "optionD": "oncles",
        "correctOption": "B",
        "subConcept": "Vocabulaire de descendance",
        "explanation": "Dans le cadre de la descendance parentale, on dit 'deux fils et une fille' (two sons and one daughter).",
        "remediationTip": "Par rapport aux parents, les enfants sont des 'fils' (sons) ou des 'filles' (daughters)."
      },
      {
        "id": "q-jhs2fre-t2-9",
        "quizId": "quiz-jhs2-fre-t2-famille-relations",
        "questionText": "Quelle phrase est grammaticalement CORRECTE ?",
        "optionA": "Kofi visite son tante.",
        "optionB": "Kofi visite sa tante.",
        "optionC": "Kofi visite ses tante.",
        "optionD": "Kofi visite leur tante.",
        "correctOption": "B",
        "subConcept": "Accord possessif",
        "explanation": "'tante' est féminin singulier, donc on utilise 'sa' : 'Kofi visite sa tante'.",
        "remediationTip": "Tante est féminin -> 'sa tante'."
      },
      {
        "id": "q-jhs2fre-t2-10",
        "quizId": "quiz-jhs2-fre-t2-famille-relations",
        "questionText": "Qui sont les 'grands-parents' ?",
        "optionA": "Les parents de mes parents (le grand-père et la grand-mère)",
        "optionB": "Les frères aînés de mon père",
        "optionC": "Tous les voisins du quartier",
        "optionD": "Les enfants de ma tante",
        "correctOption": "A",
        "subConcept": "Définition des grands-parents",
        "explanation": "Les grands-parents désignent collectivement le grand-père et la grand-mère, c'est-à-dire les parents du père ou de la mère.",
        "remediationTip": "Grands-parents = grandfather and grandmother."
      }
    ]
  },
  "jhs2-fre-t3-description-physique-morale": {
    "id": "quiz-jhs2-fre-t3-description-physique-morale",
    "topicId": "jhs2-fre-t3-description-physique-morale",
    "title": "La Description Physique et Morale des Personnes BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t3-1",
        "quizId": "quiz-jhs2-fre-t3-description-physique-morale",
        "questionText": "Complétez avec l'adjectif correctement accordé : 'Akosua est une fille très ... et travailleuse.'",
        "optionA": "intelligent",
        "optionB": "intelligente",
        "optionC": "intelligents",
        "optionD": "intelligentes",
        "correctOption": "B",
        "subConcept": "Accord de l'adjectif qualificatif",
        "explanation": "'fille' est féminin singulier, donc l'adjectif s'accorde au féminin singulier avec '-e' : 'intelligente'.",
        "remediationTip": "Nom féminin singulier -> adjectif avec '-e' (intelligente)."
      },
      {
        "id": "q-jhs2fre-t3-2",
        "quizId": "quiz-jhs2-fre-t3-description-physique-morale",
        "questionText": "Quelle est la forme féminine de l'adjectif 'beau' ?",
        "optionA": "belle",
        "optionB": "beauté",
        "optionC": "beaux",
        "optionD": "bel",
        "correctOption": "A",
        "subConcept": "Féminin irrégulier de beau",
        "explanation": "L'adjectif 'beau' a un féminin irrégulier: 'belle' (ex: une belle fille).",
        "remediationTip": "Beau (masc.) -> Belle (fém.)."
      },
      {
        "id": "q-jhs2fre-t3-3",
        "quizId": "quiz-jhs2-fre-t3-description-physique-morale",
        "questionText": "Quel adjectif de couleur est STRICTEMENT INVARIABLE (ne prend jamais de 'e' ni de 's') ?",
        "optionA": "noir",
        "optionB": "marron",
        "optionC": "bleu",
        "optionD": "vert",
        "correctOption": "B",
        "subConcept": "Adjectifs de couleur invariables",
        "explanation": "'marron' et 'orange' sont des noms de fruits utilisés comme adjectifs de couleur; ils sont totalement invariables.",
        "remediationTip": "Marron et orange ne prennent jamais d'accord: 'des chaussures marron'."
      },
      {
        "id": "q-jhs2fre-t3-4",
        "quizId": "quiz-jhs2-fre-t3-description-physique-morale",
        "questionText": "Comment dit-on en français : 'He has short black hair' ?",
        "optionA": "Il a les cheveux courts et noirs.",
        "optionB": "Ses cheveux sont courtes et noires.",
        "optionC": "Il est les cheveux court.",
        "optionD": "Il porte les cheveux petite et noire.",
        "correctOption": "A",
        "subConcept": "Description des cheveux",
        "explanation": "'cheveux' est masculin pluriel en français; les adjectifs 'courts' et 'noirs' s'accordent au masculin pluriel.",
        "remediationTip": "Cheveux est masculin pluriel -> les cheveux courts et noirs."
      },
      {
        "id": "q-jhs2fre-t3-5",
        "quizId": "quiz-jhs2-fre-t3-description-physique-morale",
        "questionText": "Quelle est la forme féminine de l'adjectif 'paresseux' (lazy) ?",
        "optionA": "paresseux",
        "optionB": "paresseuse",
        "optionC": "paresseure",
        "optionD": "paresseusse",
        "correctOption": "B",
        "subConcept": "Féminin des adjectifs en -eux",
        "explanation": "Les adjectifs terminés par '-eux' forment leur féminin en '-euse' (paresseux -> paresseuse; courageux -> courageuse).",
        "remediationTip": "-eux devient -euse au féminin (paresseux -> paresseuse)."
      },
      {
        "id": "q-jhs2fre-t3-6",
        "quizId": "quiz-jhs2-fre-t3-description-physique-morale",
        "questionText": "Quel trait moral qualifie une personne qui partage volontiers ses biens avec les autres ?",
        "optionA": "avare",
        "optionB": "généreux (généreuse)",
        "optionC": "méchant",
        "optionD": "timide",
        "correctOption": "B",
        "subConcept": "Vocabulaire moral",
        "explanation": "Une personne 'généreuse' aime donner et partager, à l'opposé d'une personne 'avare' (radine/stingy).",
        "remediationTip": "Généreux = generous (aime donner); Avare = stingy (garde tout)."
      },
      {
        "id": "q-jhs2fre-t3-7",
        "quizId": "quiz-jhs2-fre-t3-description-physique-morale",
        "questionText": "Quelle forme de 'vieux' utilise-t-on devant un nom masculin singulier commençant par une voyelle (ex: ... homme) ?",
        "optionA": "vieux",
        "optionB": "vieil",
        "optionC": "vieille",
        "optionD": "vielle",
        "correctOption": "B",
        "subConcept": "Forme euphonique de vieux",
        "explanation": "Devant un nom masculin commençant par une voyelle ou un h muet, 'vieux' devient 'vieil' (ex: un vieil homme, un vieil ami).",
        "remediationTip": "Vieux -> vieil devant voyelle (un vieil arbre, un vieil homme)."
      },
      {
        "id": "q-jhs2fre-t3-8",
        "quizId": "quiz-jhs2-fre-t3-description-physique-morale",
        "questionText": "Complétez : 'Cette fille est très polie, mais son frère est ...'",
        "optionA": "impoli",
        "optionB": "impolie",
        "optionC": "impolis",
        "optionD": "impolies",
        "correctOption": "A",
        "subConcept": "Accord au masculin",
        "explanation": "'frère' est masculin singulier, donc l'antonyme s'accorde au masculin singulier: 'impoli'.",
        "remediationTip": "Frère est masculin -> impoli (sans 'e')."
      },
      {
        "id": "q-jhs2fre-t3-9",
        "quizId": "quiz-jhs2-fre-t3-description-physique-morale",
        "questionText": "Quelle phrase décrit correctement la stature d'un élève ?",
        "optionA": "Kweku a grand.",
        "optionB": "Kweku est grand et mince.",
        "optionC": "Kweku a grande et mince.",
        "optionD": "Kweku est grandeur.",
        "correctOption": "B",
        "subConcept": "Verbe pour la taille",
        "explanation": "Pour la taille et la corpulence, on utilise le verbe être ('est grand et mince'), et non le verbe avoir.",
        "remediationTip": "Utilisez 'être' pour la taille: 'Il est grand'."
      },
      {
        "id": "q-jhs2fre-t3-10",
        "quizId": "quiz-jhs2-fre-t3-description-physique-morale",
        "questionText": "Quel est le féminin de 'gros' ?",
        "optionA": "grose",
        "optionB": "grosse",
        "optionC": "groce",
        "optionD": "grossesse",
        "correctOption": "B",
        "subConcept": "Doublement de consonne au féminin",
        "explanation": "L'adjectif 'gros' double sa consonne finale au féminin: 'grosse'.",
        "remediationTip": "Gros (masc.) -> Grosse (fém.)."
      }
    ]
  },
  "jhs2-fre-t4-activites-quotidiennes": {
    "id": "quiz-jhs2-fre-t4-activites-quotidiennes",
    "topicId": "jhs2-fre-t4-activites-quotidiennes",
    "title": "La Routine Quotidienne et l'Heure BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t4-1",
        "quizId": "quiz-jhs2-fre-t4-activites-quotidiennes",
        "questionText": "Comment dit-on 'I wake up at six o'clock' en français ?",
        "optionA": "Je réveille à six heures.",
        "optionB": "Je me réveille à six heures.",
        "optionC": "Je lève à six heures.",
        "optionD": "Je me dors à six heures.",
        "correctOption": "B",
        "subConcept": "Verbes pronominaux de routine",
        "explanation": "'Se réveiller' est un verbe pronominal qui exige le pronom réfléchi 'me' à la première personne : 'Je me réveille'.",
        "remediationTip": "N'oubliez pas le pronom réfléchi: 'Je me réveille'."
      },
      {
        "id": "q-jhs2fre-t4-2",
        "quizId": "quiz-jhs2-fre-t4-activites-quotidiennes",
        "questionText": "Quelle heure est-il quand la petite aiguille est sur le 7 et la grande sur le 3 ?",
        "optionA": "Il est sept heures et demie.",
        "optionB": "Il est sept heures et quart.",
        "optionC": "Il est huit heures moins le quart.",
        "optionD": "Il est sept heures pile.",
        "correctOption": "B",
        "subConcept": "Lecture de l'heure - et quart",
        "explanation": "La grande aiguille sur le 3 indique 15 minutes, c'est-à-dire 'et quart' (7h15 = sept heures et quart).",
        "remediationTip": "15 minutes = et quart; 30 minutes = et demie."
      },
      {
        "id": "q-jhs2fre-t4-3",
        "quizId": "quiz-jhs2-fre-t4-activites-quotidiennes",
        "questionText": "Pourquoi écrit-on 'demie' avec un 'e' dans 'Il est huit heures et demie' ?",
        "optionA": "C'est une faute d'orthographe facultative",
        "optionB": "Parce qu'il s'accorde en genre avec le nom féminin 'heure'",
        "optionC": "Parce que le chiffre huit est féminin",
        "optionD": "Pour faire joli",
        "correctOption": "B",
        "subConcept": "Orthographe de demie",
        "explanation": "Après le nom 'heure' (qui est féminin), l'adjectif 'demi' s'accorde au féminin: 'et demie'.",
        "remediationTip": "Écrivez toujours 'et demie' avec un 'e' après 'heures'."
      },
      {
        "id": "q-jhs2fre-t4-4",
        "quizId": "quiz-jhs2-fre-t4-activites-quotidiennes",
        "questionText": "Comment dit-on exactement 12h00 (le milieu de la journée) en français ?",
        "optionA": "Il est douze heures du matin.",
        "optionB": "Il est midi.",
        "optionC": "Il est minuit.",
        "optionD": "Il est treize heures.",
        "correctOption": "B",
        "subConcept": "Midi et minuit",
        "explanation": "12h00 le jour se dit 'Il est midi'. 12h00 la nuit se dit 'Il est minuit'.",
        "remediationTip": "12h00 le jour = midi; 12h00 la nuit = minuit."
      },
      {
        "id": "q-jhs2fre-t4-5",
        "quizId": "quiz-jhs2-fre-t4-activites-quotidiennes",
        "questionText": "Quel connecteur temporel utilise-t-on pour introduire la première action d'une journée ?",
        "optionA": "Enfin",
        "optionB": "D'abord",
        "optionC": "Puis",
        "optionD": "Après cela",
        "correctOption": "B",
        "subConcept": "Connecteurs chronologiques",
        "explanation": "'D'abord' (ou 'Premièrement') indique le point de départ d'une suite chronologique d'actions.",
        "remediationTip": "Ordre chronologique: D'abord -> Ensuite / Puis -> Enfin."
      },
      {
        "id": "q-jhs2fre-t4-6",
        "quizId": "quiz-jhs2-fre-t4-activites-quotidiennes",
        "questionText": "Conjuguez correctement : 'Les élèves ... à sept heures pour l'école.'",
        "optionA": "s'habillent",
        "optionB": "s'habille",
        "optionC": "m'habille",
        "optionD": "vous habillez",
        "correctOption": "A",
        "subConcept": "Conjugaison au pluriel",
        "explanation": "'Les élèves' est un sujet à la 3e personne du pluriel (ils), donc la terminaison est '-ent' : 's'habillent'.",
        "remediationTip": "Ils/Elles s'habillent (terminaison -ent)."
      },
      {
        "id": "q-jhs2fre-t4-7",
        "quizId": "quiz-jhs2-fre-t4-activites-quotidiennes",
        "questionText": "Comment exprime-t-on 7h45 (quinze minutes avant huit heures) ?",
        "optionA": "Il est sept heures moins le quart.",
        "optionB": "Il est huit heures moins le quart.",
        "optionC": "Il est huit heures et quart.",
        "optionD": "Il est sept heures quarante.",
        "correctOption": "B",
        "subConcept": "Moins le quart",
        "explanation": "7h45 signifie qu'il reste un quart d'heure pour atteindre 8h: 'Il est huit heures moins le quart'.",
        "remediationTip": "7h45 = huit heures moins le quart (mentionnez l'heure suivante !)."
      },
      {
        "id": "q-jhs2fre-t4-8",
        "quizId": "quiz-jhs2-fre-t4-activites-quotidiennes",
        "questionText": "Que fait-on immédiatement après s'être réveillé pour nettoyer sa bouche ?",
        "optionA": "On se couche",
        "optionB": "On se brosse les dents",
        "optionC": "On joue au football",
        "optionD": "On repasse l'uniforme",
        "correctOption": "B",
        "subConcept": "Hygiène corporelle",
        "explanation": "'Se brosser les dents' est l'action hygiénique de nettoyage des dents après le réveil.",
        "remediationTip": "Se brosser les dents = to brush one's teeth."
      },
      {
        "id": "q-jhs2fre-t4-9",
        "quizId": "quiz-jhs2-fre-t4-activites-quotidiennes",
        "questionText": "Quelle action clôture habituellement la routine d'un collégien en fin de soirée ?",
        "optionA": "se coucher (aller au lit)",
        "optionB": "prendre le petit déjeuner",
        "optionC": "aller à l'école",
        "optionD": "faire du sport matinal",
        "correctOption": "A",
        "subConcept": "Fin de journée",
        "explanation": "En fin de soirée, on se couche ('aller au lit / dormir') pour se reposer.",
        "remediationTip": "Se coucher = to go to bed."
      },
      {
        "id": "q-jhs2fre-t4-10",
        "quizId": "quiz-jhs2-fre-t4-activites-quotidiennes",
        "questionText": "Comment pose-t-on la question de l'heure en français ?",
        "optionA": "Quel temps fait-il ?",
        "optionB": "Quelle heure est-il ?",
        "optionC": "Combien d'heures avez-vous ?",
        "optionD": "Où est la montre ?",
        "correctOption": "B",
        "subConcept": "Demander l'heure",
        "explanation": "'Quelle heure est-il ?' est l'interrogation standard pour demander l'heure.",
        "remediationTip": "'Quelle heure est-il ?' = What time is it?"
      }
    ]
  },
  "jhs2-fre-t5-ecole-matieres": {
    "id": "quiz-jhs2-fre-t5-ecole-matieres",
    "topicId": "jhs2-fre-t5-ecole-matieres",
    "title": "L'École, les Matières Scolaires et l'Emploi du Temps BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t5-1",
        "quizId": "quiz-jhs2-fre-t5-ecole-matieres",
        "questionText": "Où les élèves vont-ils pour emprunter ou lire des livres de recherche à l'école ?",
        "optionA": "À la cantine",
        "optionB": "À la bibliothèque",
        "optionC": "Au terrain de football",
        "optionD": "Dans les toilettes",
        "correctOption": "B",
        "subConcept": "Bâtiments scolaires",
        "explanation": "La bibliothèque est le lieu dédié à la lecture, au silence et au prêt de livres scolaires.",
        "remediationTip": "Bibliothèque = library."
      },
      {
        "id": "q-jhs2fre-t5-2",
        "quizId": "quiz-jhs2-fre-t5-ecole-matieres",
        "questionText": "Comment traduit-on 'Computing / ICT' en français ?",
        "optionA": "les sciences intégrées",
        "optionB": "l'informatique (ou les TIC)",
        "optionC": "l'histoire-géographie",
        "optionD": "les mathématiques",
        "correctOption": "B",
        "subConcept": "Matières scolaires",
        "explanation": "'Computing / ICT' se traduit par 'l'informatique' ou 'les Technologies de l'Information et de la Communication (TIC)'.",
        "remediationTip": "Computing = l'informatique."
      },
      {
        "id": "q-jhs2fre-t5-3",
        "quizId": "quiz-jhs2-fre-t5-ecole-matieres",
        "questionText": "Complétez avec la conjonction causale élidée : 'J'aime le français ... il est très utile.'",
        "optionA": "parce que",
        "optionB": "parce qu'",
        "optionC": "pourquoi",
        "optionD": "mais",
        "correctOption": "B",
        "subConcept": "Élision de parce que",
        "explanation": "Devant le pronom 'il' commençant par une voyelle, 'parce que' s'élide obligatoirement en 'parce qu''.",
        "remediationTip": "'parce que' + voyelle devient 'parce qu'' (parce qu'il)."
      },
      {
        "id": "q-jhs2fre-t5-4",
        "quizId": "quiz-jhs2-fre-t5-ecole-matieres",
        "questionText": "Quelle matière scolaire enseigne les calculs, les fractions, l'algèbre et la géométrie ?",
        "optionA": "l'anglais",
        "optionB": "les mathématiques (les maths)",
        "optionC": "l'éducation religieuse",
        "optionD": "les études sociales",
        "correctOption": "B",
        "subConcept": "Matières scolaires",
        "explanation": "Les mathématiques s'occupent des nombres, des équations et des figures géométriques.",
        "remediationTip": "Mathematics = les mathématiques (les maths)."
      },
      {
        "id": "q-jhs2fre-t5-5",
        "quizId": "quiz-jhs2-fre-t5-ecole-matieres",
        "questionText": "Que signifie le verbe 'détester' dans : 'Ama déteste les devoirs trop difficiles' ?",
        "optionA": "aimer passionnément",
        "optionB": "haïr / ne pas aimer du tout (to hate)",
        "optionC": "oublier facilement",
        "optionD": "corriger proprement",
        "correctOption": "B",
        "subConcept": "Verbes de sentiment",
        "explanation": "'Détester' exprime un sentiment de fort dégoût ou rejet (to hate / to detest).",
        "remediationTip": "Détester = to hate / not like at all."
      },
      {
        "id": "q-jhs2fre-t5-6",
        "quizId": "quiz-jhs2-fre-t5-ecole-matieres",
        "questionText": "Comment écrit-on correctement les jours de la semaine en français ?",
        "optionA": "Avec une majuscule obligatoire (Lundi, Mardi...)",
        "optionB": "En lettres minuscules (lundi, mardi, mercredi...)",
        "optionC": "Toujours en abrégé seulement",
        "optionD": "Avec des accents sur toutes les lettres",
        "correctOption": "B",
        "subConcept": "Orthographe des jours",
        "explanation": "Contrairement à l'anglais, les jours de la semaine s'écrivent avec une lettre initiale minuscule en français.",
        "remediationTip": "Les jours de la semaine s'écrivent en minuscule en français: lundi, mardi..."
      },
      {
        "id": "q-jhs2fre-t5-7",
        "quizId": "quiz-jhs2-fre-t5-ecole-matieres",
        "questionText": "Comment appelle-t-on le temps de pause entre les cours où les élèves jouent et mangent ?",
        "optionA": "l'assemblée matinale",
        "optionB": "la récréation",
        "optionC": "la punition",
        "optionD": "l'examen final",
        "correctOption": "B",
        "subConcept": "Vie scolaire",
        "explanation": "La récréation (recess / break time) est la pause entre deux sessions de cours.",
        "remediationTip": "Break time = la récréation."
      },
      {
        "id": "q-jhs2fre-t5-8",
        "quizId": "quiz-jhs2-fre-t5-ecole-matieres",
        "questionText": "Complétez la phrase : 'Dans notre salle de classe, le professeur écrit sur le ... avec une craie.'",
        "optionA": "tableau",
        "optionB": "pupitre",
        "optionC": "plafond",
        "optionD": "balai",
        "correctOption": "A",
        "subConcept": "Mobilier de classe",
        "explanation": "Le tableau (noir ou vert) est le support mural sur lequel l'enseignant écrit avec de la craie.",
        "remediationTip": "Blackboard = le tableau."
      },
      {
        "id": "q-jhs2fre-t5-9",
        "quizId": "quiz-jhs2-fre-t5-ecole-matieres",
        "questionText": "Que signifie : 'Le vendredi après-midi, nous avons deux heures d'EPS' ?",
        "optionA": "Cours d'espagnol",
        "optionB": "Éducation Physique et Sportive (sports/physical education)",
        "optionC": "Économie politique",
        "optionD": "Examen de passage",
        "correctOption": "B",
        "subConcept": "Sigles scolaires",
        "explanation": "L'EPS désigne l'Éducation Physique et Sportive (Physical Education / PE).",
        "remediationTip": "EPS = Éducation Physique et Sportive (P.E.)."
      },
      {
        "id": "q-jhs2fre-t5-10",
        "quizId": "quiz-jhs2-fre-t5-ecole-matieres",
        "questionText": "Quelle préposition utilise-t-on pour introduire un jour récurrent : '... lundi matin, nous chantons l'hymne national' ?",
        "optionA": "À",
        "optionB": "Le",
        "optionC": "En",
        "optionD": "Sur",
        "correctOption": "B",
        "subConcept": "Expression de l'habitude temporelle",
        "explanation": "L'article défini 'le' devant un jour de la semaine exprime l'habitude régulière ('Le lundi' = every Monday).",
        "remediationTip": "'Le lundi' signifie chaque lundi / tous les lundis."
      }
    ]
  },
  "jhs2-fre-t6-aliments-repas": {
    "id": "quiz-jhs2-fre-t6-aliments-repas",
    "topicId": "jhs2-fre-t6-aliments-repas",
    "title": "Les Aliments, les Boissons et les Repas BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t6-1",
        "quizId": "quiz-jhs2-fre-t6-aliments-repas",
        "questionText": "Quel article partitif utilise-t-on devant un nom masculin singulier comme 'pain' ou 'riz' ?",
        "optionA": "de la",
        "optionB": "du",
        "optionC": "des",
        "optionD": "de l'",
        "correctOption": "B",
        "subConcept": "Article partitif masculin",
        "explanation": "'du' est la contraction de 'de + le', utilisée devant les noms masculins singuliers non comptables : du pain, du riz.",
        "remediationTip": "Masculin singulier -> 'du' (du riz, du pain)."
      },
      {
        "id": "q-jhs2fre-t6-2",
        "quizId": "quiz-jhs2-fre-t6-aliments-repas",
        "questionText": "Transformez à la forme négative : 'Ama mange de la viande.'",
        "optionA": "Ama ne mange pas de la viande.",
        "optionB": "Ama ne mange pas de viande.",
        "optionC": "Ama ne mange pas du viande.",
        "optionD": "Ama ne mange pas la viande.",
        "correctOption": "B",
        "subConcept": "Négation des articles partitifs",
        "explanation": "À la forme négative, 'du, de la, de l', des' deviennent TOUJOURS 'de' ou 'd'' : 'Ama ne mange pas DE viande.'",
        "remediationTip": "Ne... pas + DE (ou D' devant voyelle). Jamais 'pas de la' !"
      },
      {
        "id": "q-jhs2fre-t6-3",
        "quizId": "quiz-jhs2-fre-t6-aliments-repas",
        "questionText": "Quel article partitif convient devant le mot féminin 'eau' qui commence par une voyelle ?",
        "optionA": "de la",
        "optionB": "de l'",
        "optionC": "du",
        "optionD": "des",
        "correctOption": "B",
        "subConcept": "Partitif devant voyelle",
        "explanation": "Devant un nom singulier commençant par une voyelle, on utilise 'de l'' : 'de l'eau', 'de l'huile'.",
        "remediationTip": "Devant une voyelle -> 'de l'' (de l'eau)."
      },
      {
        "id": "q-jhs2fre-t6-4",
        "quizId": "quiz-jhs2-fre-t6-aliments-repas",
        "questionText": "Comment dit-on 'I am hungry' et 'I am thirsty' en français ?",
        "optionA": "Je suis faim et je suis soif.",
        "optionB": "J'ai faim et j'ai soif.",
        "optionC": "Je fais faim et je fais soif.",
        "optionD": "J'aime faim et j'aime soif.",
        "correctOption": "B",
        "subConcept": "Verbe avoir pour sensations",
        "explanation": "La faim et la soif s'expriment obligatoirement avec le verbe AVOIR : 'J'ai faim' / 'J'ai soif'.",
        "remediationTip": "Utilisez le verbe avoir: J'ai faim (I am hungry), J'ai soif (I am thirsty)."
      },
      {
        "id": "q-jhs2fre-t6-5",
        "quizId": "quiz-jhs2-fre-t6-aliments-repas",
        "questionText": "Quel plat populaire ghanéen à base de riz cuit dans une sauce tomate épicée est appelé 'riz gras' en français ?",
        "optionA": "le fufu",
        "optionB": "le riz jollof",
        "optionC": "le banku",
        "optionD": "le kenkey",
        "correctOption": "B",
        "subConcept": "Plats traditionnels",
        "explanation": "Le riz jollof est communément désigné sous le nom de 'riz gras' dans les pays francophones ouest-africains.",
        "remediationTip": "Jollof rice = le riz gras ou le riz jollof."
      },
      {
        "id": "q-jhs2fre-t6-6",
        "quizId": "quiz-jhs2-fre-t6-aliments-repas",
        "questionText": "Complétez la commande au restaurant : 'Garçon, s'il vous plaît, je ... une assiette de riz.'",
        "optionA": "voudrais",
        "optionB": "suis",
        "optionC": "fais",
        "optionD": "vais",
        "correctOption": "A",
        "subConcept": "Commander poliment",
        "explanation": "'Je voudrais...' (conditionnel de politesse de vouloir) est la formule standard polie pour commander au restaurant.",
        "remediationTip": "'Je voudrais...' = I would like..."
      },
      {
        "id": "q-jhs2fre-t6-7",
        "quizId": "quiz-jhs2-fre-t6-aliments-repas",
        "questionText": "Quel repas prend-on généralement entre 6 heures et 8 heures du matin ?",
        "optionA": "le dîner",
        "optionB": "le déjeuner",
        "optionC": "le petit déjeuner",
        "optionD": "le goûter",
        "correctOption": "C",
        "subConcept": "Moments des repas",
        "explanation": "Le premier repas du matin est le 'petit déjeuner' (breakfast).",
        "remediationTip": "Matin = petit déjeuner; Midi = déjeuner; Soir = dîner."
      },
      {
        "id": "q-jhs2fre-t6-8",
        "quizId": "quiz-jhs2-fre-t6-aliments-repas",
        "questionText": "Que demande un client pour payer son repas à la fin du service au restaurant ?",
        "optionA": "le menu",
        "optionB": "l'addition",
        "optionC": "la recette",
        "optionD": "la cuillère",
        "correctOption": "B",
        "subConcept": "Vocabulaire du restaurant",
        "explanation": "L'addition (the bill) est le document indiquant le montant à payer pour le repas consommé.",
        "remediationTip": "The bill = l'addition."
      },
      {
        "id": "q-jhs2fre-t6-9",
        "quizId": "quiz-jhs2-fre-t6-aliments-repas",
        "questionText": "Complétez avec le bon article : 'Kofi n'aime pas le café, il préfère boire ... thé chaud.'",
        "optionA": "du",
        "optionB": "de la",
        "optionC": "des",
        "optionD": "de",
        "correctOption": "A",
        "subConcept": "Partitif masculin avec boisson",
        "explanation": "'thé' est un nom masculin singulier dans une phrase affirmative, donc on utilise 'du' : boire du thé.",
        "remediationTip": "'thé' est masculin -> du thé."
      },
      {
        "id": "q-jhs2fre-t6-10",
        "quizId": "quiz-jhs2-fre-t6-aliments-repas",
        "questionText": "Dans quelle phrase l'article est-il utilisé avec le sens général après un verbe de goût ?",
        "optionA": "Je mange du poisson.",
        "optionB": "J'adore le poisson.",
        "optionC": "Je voudrais du poisson.",
        "optionD": "Donne-moi du poisson.",
        "correctOption": "B",
        "subConcept": "Article défini vs partitif",
        "explanation": "Après les verbes de goût (aimer, adorer, préférer, détester), on emploie l'article défini (le, la, les) pour désigner la chose en général.",
        "remediationTip": "Après aimer/adorer -> article défini: J'adore LE poisson."
      }
    ]
  },
  "jhs2-fre-t7-vetements-accessoires": {
    "id": "quiz-jhs2-fre-t7-vetements-accessoires",
    "topicId": "jhs2-fre-t7-vetements-accessoires",
    "title": "Les Vêtements, les Couleurs et les Accessoires BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t7-1",
        "quizId": "quiz-jhs2-fre-t7-vetements-accessoires",
        "questionText": "Quel adjectif démonstratif convient devant le nom masculin commençant par une voyelle : '... uniforme scolaire est propre' ?",
        "optionA": "ce",
        "optionB": "cet",
        "optionC": "cette",
        "optionD": "ces",
        "correctOption": "B",
        "subConcept": "Adjectif démonstratif devant voyelle",
        "explanation": "Devant un nom masculin singulier commençant par une voyelle ou un h muet, on emploie 'cet' (ex: cet uniforme, cet habit).",
        "remediationTip": "Masculin singulier commençant par voyelle = CET (cet uniforme)."
      },
      {
        "id": "q-jhs2fre-t7-2",
        "quizId": "quiz-jhs2-fre-t7-vetements-accessoires",
        "questionText": "Quelle couleur reste INVARIABLE et ne prend jamais de 's' au pluriel ?",
        "optionA": "blanche",
        "optionB": "marron",
        "optionC": "bleue",
        "optionD": "verte",
        "correctOption": "B",
        "subConcept": "Couleur invariable",
        "explanation": "'marron' (et 'orange') est un adjectif de couleur dérivé d'un nom de fruit; il est invariable au féminin et au pluriel.",
        "remediationTip": "Marron et orange sont invariables: des chaussures marron."
      },
      {
        "id": "q-jhs2fre-t7-3",
        "quizId": "quiz-jhs2-fre-t7-vetements-accessoires",
        "questionText": "Quel vêtement féminin en une seule pièce s'étend des épaules jusqu'aux genoux ou chevilles ?",
        "optionA": "le pantalon",
        "optionB": "la robe",
        "optionC": "le short",
        "optionD": "la cravate",
        "correctOption": "B",
        "subConcept": "Vocabulaire des vêtements",
        "explanation": "'la robe' (dress) est le vêtement féminin recouvrant le corps du haut jusqu'au bas.",
        "remediationTip": "Dress = la robe; Skirt = la jupe."
      },
      {
        "id": "q-jhs2fre-t7-4",
        "quizId": "quiz-jhs2-fre-t7-vetements-accessoires",
        "questionText": "Complétez : 'Akosua porte une jupe ... pour aller au culte le dimanche.'",
        "optionA": "blanc",
        "optionB": "blanche",
        "optionC": "blancs",
        "optionD": "blanches",
        "correctOption": "B",
        "subConcept": "Accord de l'adjectif blanc",
        "explanation": "'jupe' est féminin singulier; le féminin de 'blanc' est 'blanche'.",
        "remediationTip": "Blanc (masc.) -> Blanche (fém.)."
      },
      {
        "id": "q-jhs2fre-t7-5",
        "quizId": "quiz-jhs2-fre-t7-vetements-accessoires",
        "questionText": "Quel adjectif démonstratif utilise-t-on devant un nom féminin singulier comme 'robe' ou 'chemise' ?",
        "optionA": "ce",
        "optionB": "cet",
        "optionC": "cette",
        "optionD": "ces",
        "correctOption": "C",
        "subConcept": "Adjectif démonstratif féminin",
        "explanation": "'cette' est l'adjectif démonstratif féminin singulier (cette robe, cette fille).",
        "remediationTip": "Féminin singulier = CETTE (cette robe)."
      },
      {
        "id": "q-jhs2fre-t7-6",
        "quizId": "quiz-jhs2-fre-t7-vetements-accessoires",
        "questionText": "Quel tissu traditionnel tissé à la main est un symbole mondial de la culture et de la royauté ghanéennes ?",
        "optionA": "le denim",
        "optionB": "le tissu Kente",
        "optionC": "le nylon",
        "optionD": "le velours",
        "correctOption": "B",
        "subConcept": "Tissus ghanéens",
        "explanation": "Le Kente est le tissu traditionnel prestigieux originaire de Bonwire dans la région Ashanti du Ghana.",
        "remediationTip": "Kente = tissu traditionnel royal tissé au Ghana."
      },
      {
        "id": "q-jhs2fre-t7-7",
        "quizId": "quiz-jhs2-fre-t7-vetements-accessoires",
        "questionText": "Quel verbe régulier du 1er groupe signifie 'to wear' ou 'to carry' en français ?",
        "optionA": "manger",
        "optionB": "porter",
        "optionC": "écouter",
        "optionD": "fermer",
        "correctOption": "B",
        "subConcept": "Verbe porter",
        "explanation": "Le verbe 'porter' signifie 'to wear' lorsqu'il s'applique aux habits (ex: Je porte un pantalon noir).",
        "remediationTip": "Porter = to wear."
      },
      {
        "id": "q-jhs2fre-t7-8",
        "quizId": "quiz-jhs2-fre-t7-vetements-accessoires",
        "questionText": "Complétez avec le démonstratif pluriel : '... chaussures coûtent très cher.'",
        "optionA": "ce",
        "optionB": "ces",
        "optionC": "cet",
        "optionD": "cette",
        "correctOption": "B",
        "subConcept": "Adjectif démonstratif pluriel",
        "explanation": "'chaussures' est au pluriel; le démonstratif pluriel (masculin et féminin) est 'ces'.",
        "remediationTip": "Pluriel = CES (ces chaussures, ces garçons)."
      },
      {
        "id": "q-jhs2fre-t7-9",
        "quizId": "quiz-jhs2-fre-t7-vetements-accessoires",
        "questionText": "Comment demande-t-on le prix d'un vêtement dans un magasin ?",
        "optionA": "Quelle heure est-il ?",
        "optionB": "Combien coûte cette chemise ?",
        "optionC": "Où habitez-vous ?",
        "optionD": "Comment vous appelez-vous ?",
        "correctOption": "B",
        "subConcept": "Demander le prix",
        "explanation": "'Combien coûte... ?' ou 'C'est combien ?' est l'expression pour demander le prix.",
        "remediationTip": "Combien coûte... ? = How much does ... cost?"
      },
      {
        "id": "q-jhs2fre-t7-10",
        "quizId": "quiz-jhs2-fre-t7-vetements-accessoires",
        "questionText": "Quel accessoire masculin en cuir entoure la taille pour maintenir un pantalon ?",
        "optionA": "la cravate",
        "optionB": "la ceinture",
        "optionC": "la casquette",
        "optionD": "la bague",
        "correctOption": "B",
        "subConcept": "Accessoires vestimentaires",
        "explanation": "La ceinture (belt) est la lanière de cuir ou de tissu qui maintient le pantalon autour de la taille.",
        "remediationTip": "Belt = la ceinture."
      }
    ]
  },
  "jhs2-fre-t8-maison-pieces": {
    "id": "quiz-jhs2-fre-t8-maison-pieces",
    "topicId": "jhs2-fre-t8-maison-pieces",
    "title": "La Maison, les Pièces et les Tâches Ménagères BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t8-1",
        "quizId": "quiz-jhs2-fre-t8-maison-pieces",
        "questionText": "Dans quelle pièce de la maison prépare-t-on la nourriture et lave-t-on les casseroles ?",
        "optionA": "le salon",
        "optionB": "la cuisine",
        "optionC": "la chambre à coucher",
        "optionD": "le garage",
        "correctOption": "B",
        "subConcept": "Pièces de la maison",
        "explanation": "La cuisine (kitchen) est la pièce réservée à la cuisson des aliments et à la vaisselle.",
        "remediationTip": "Kitchen = la cuisine."
      },
      {
        "id": "q-jhs2fre-t8-2",
        "quizId": "quiz-jhs2-fre-t8-maison-pieces",
        "questionText": "Quelle préposition signifie 'on top of' dans : 'Le livre de français est ... la table' ?",
        "optionA": "sous",
        "optionB": "sur",
        "optionC": "derrière",
        "optionD": "entre",
        "correctOption": "B",
        "subConcept": "Prépositions de lieu (sur/sous)",
        "explanation": "'sur' signifie 'on / on top of', tandis que 'sous' signifie 'under'.",
        "remediationTip": "Sur = on; Sous = under."
      },
      {
        "id": "q-jhs2fre-t8-3",
        "quizId": "quiz-jhs2-fre-t8-maison-pieces",
        "questionText": "Que signifie l'action ménagère 'faire la vaisselle' ?",
        "optionA": "balayer la cour",
        "optionB": "laver les assiettes, verres et couverts après le repas",
        "optionC": "repasser les vêtements d'école",
        "optionD": "faire le lit le matin",
        "correctOption": "B",
        "subConcept": "Tâches ménagères",
        "explanation": "'Faire la vaisselle' signifie nettoyer les assiettes et ustensiles de cuisine après le repas (washing dishes).",
        "remediationTip": "Faire la vaisselle = to wash the dishes."
      },
      {
        "id": "q-jhs2fre-t8-4",
        "quizId": "quiz-jhs2-fre-t8-maison-pieces",
        "questionText": "Comment contracte-t-on 'à côté de + le salon' ?",
        "optionA": "à côté de le salon",
        "optionB": "à côté du salon",
        "optionC": "à côté des salon",
        "optionD": "à côté au salon",
        "correctOption": "B",
        "subConcept": "Article contracté après locution de lieu",
        "explanation": "La préposition 'de' se contracte avec l'article défini masculin 'le' pour donner 'du' : à côté du salon.",
        "remediationTip": "de + le = DU (à côté du salon)."
      },
      {
        "id": "q-jhs2fre-t8-5",
        "quizId": "quiz-jhs2-fre-t8-maison-pieces",
        "questionText": "Quel appareil ménager électrique permet de garder les aliments et boissons au frais ?",
        "optionA": "la cuisinière",
        "optionB": "le réfrigérateur (le frigo)",
        "optionC": "le fer à repasser",
        "optionD": "le ventilateur",
        "correctOption": "B",
        "subConcept": "Appareils électroménagers",
        "explanation": "Le réfrigérateur (frigo / fridge) produit du froid pour conserver les aliments périssables.",
        "remediationTip": "Refrigerator = le réfrigérateur (le frigo)."
      },
      {
        "id": "q-jhs2fre-t8-6",
        "quizId": "quiz-jhs2-fre-t8-maison-pieces",
        "questionText": "Quelle corvée ménagère consiste à nettoyer le sol à l'aide d'un balai ?",
        "optionA": "repasser",
        "optionB": "balayer",
        "optionC": "cuisiner",
        "optionD": "peindre",
        "correctOption": "B",
        "subConcept": "Verbes de corvée ménagère",
        "explanation": "'Balayer' (to sweep) est l'action de nettoyer la poussière et les débris au sol avec un balai.",
        "remediationTip": "Balayer = to sweep."
      },
      {
        "id": "q-jhs2fre-t8-7",
        "quizId": "quiz-jhs2-fre-t8-maison-pieces",
        "questionText": "Où se trouve le canapé généralement dans une maison ?",
        "optionA": "au salon (salle de séjour)",
        "optionB": "dans les toilettes",
        "optionC": "au garage",
        "optionD": "sur le toit",
        "correctOption": "A",
        "subConcept": "Disposition du mobilier",
        "explanation": "Le canapé (sofa / couch) est le meuble principal du salon où s'assoient les hôtes et la famille.",
        "remediationTip": "Canapé / fauteuil = meuble du salon."
      },
      {
        "id": "q-jhs2fre-t8-8",
        "quizId": "quiz-jhs2-fre-t8-maison-pieces",
        "questionText": "Quelle préposition de lieu traduit 'between' dans : 'La table est ... les deux fauteuils' ?",
        "optionA": "devant",
        "optionB": "entre",
        "optionC": "derrière",
        "optionD": "dans",
        "correctOption": "B",
        "subConcept": "Préposition entre",
        "explanation": "'entre' signifie 'between' (au milieu de deux éléments distincts).",
        "remediationTip": "Between = entre."
      },
      {
        "id": "q-jhs2fre-t8-9",
        "quizId": "quiz-jhs2-fre-t8-maison-pieces",
        "questionText": "Quel meuble de la chambre à coucher sert à ranger les vêtements repassés ?",
        "optionA": "l'armoire",
        "optionB": "le lit",
        "optionC": "le miroir",
        "optionD": "la chaise",
        "correctOption": "A",
        "subConcept": "Meubles de la chambre",
        "explanation": "L'armoire (wardrobe / closet) est le grand meuble fermé utilisé pour suspendre et ranger les habits.",
        "remediationTip": "Wardrobe = l'armoire."
      },
      {
        "id": "q-jhs2fre-t8-10",
        "quizId": "quiz-jhs2-fre-t8-maison-pieces",
        "questionText": "Que fait un élève lorsqu'il 'repasse' son uniforme le dimanche soir ?",
        "optionA": "Il le lave avec de l'eau savonneuse",
        "optionB": "Il défroisse le tissu à l'aide d'un fer à repasser chaud",
        "optionC": "Il le jette à la poubelle",
        "optionD": "Il le prête à son voisin",
        "correctOption": "B",
        "subConcept": "Action de repasser",
        "explanation": "'Repasser' signifie lisser les plis d'un vêtement avec un fer à repasser (to iron clothes).",
        "remediationTip": "Repasser = to iron clothes."
      }
    ]
  },
  "jhs2-fre-t9-loisirs-sports": {
    "id": "quiz-jhs2-fre-t9-loisirs-sports",
    "topicId": "jhs2-fre-t9-loisirs-sports",
    "title": "Les Loisirs, les Sports et les Vacances BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t9-1",
        "quizId": "quiz-jhs2-fre-t9-loisirs-sports",
        "questionText": "Complétez avec le bon article contracté pour ce sport d'équipe : 'Kwame joue ... football après les cours.'",
        "optionA": "du",
        "optionB": "au",
        "optionC": "à la",
        "optionD": "aux",
        "correctOption": "B",
        "subConcept": "Jouer à + sport masculin",
        "explanation": "Le verbe jouer avec un sport masculin (le football) donne la contraction: à + le = AU (jouer au football).",
        "remediationTip": "Jouer + sport masculin -> AU (jouer au football, jouer au basketball)."
      },
      {
        "id": "q-jhs2fre-t9-2",
        "quizId": "quiz-jhs2-fre-t9-loisirs-sports",
        "questionText": "Complétez avec la préposition appropriée pour le verbe faire : 'Pendant le week-end, Ama fait ... natation.'",
        "optionA": "à la",
        "optionB": "de la",
        "optionC": "du",
        "optionD": "au",
        "correctOption": "B",
        "subConcept": "Faire de + activité féminine",
        "explanation": "Le verbe FAIRE s'utilise avec 'de'. 'natation' est un nom féminin : de + la = 'de la natation'.",
        "remediationTip": "Faire + nom féminin -> DE LA (faire de la natation, de la musique)."
      },
      {
        "id": "q-jhs2fre-t9-3",
        "quizId": "quiz-jhs2-fre-t9-loisirs-sports",
        "questionText": "Quelle préposition emploie-t-on avec le verbe JOUER quand il s'agit d'un instrument de musique (ex: piano) ?",
        "optionA": "à (au piano)",
        "optionB": "de (du piano)",
        "optionC": "dans",
        "optionD": "en",
        "correctOption": "B",
        "subConcept": "Jouer de + instrument",
        "explanation": "Avec un instrument de musique, le verbe jouer s'associe à la préposition 'de' : de + le = du (jouer du piano, jouer de la guitare).",
        "remediationTip": "Sport = jouer AU; Instrument de musique = jouer DU (piano)."
      },
      {
        "id": "q-jhs2fre-t9-4",
        "quizId": "quiz-jhs2-fre-t9-loisirs-sports",
        "questionText": "Comment forme-t-on le 'Futur Proche' en français ?",
        "optionA": "Sujet + avoir au présent + participe passé",
        "optionB": "Sujet + ALLER au présent + verbe à l'INFINITIF",
        "optionC": "Sujet + être au présent + adjectif",
        "optionD": "Sujet + faire + nom",
        "correctOption": "B",
        "subConcept": "Structure du futur proche",
        "explanation": "Le futur proche se construit avec le verbe ALLER conjugué au présent suivi du verbe d'action à l'infinitif (ex: Je vais voyager).",
        "remediationTip": "Futur proche = ALLER + INFINITIF (Je vais manger)."
      },
      {
        "id": "q-jhs2fre-t9-5",
        "quizId": "quiz-jhs2-fre-t9-loisirs-sports",
        "questionText": "Conjuguez au futur proche : 'Pendant les vacances, nous ... visiter le parc de Kakum.'",
        "optionA": "allons",
        "optionB": "va",
        "optionC": "vont",
        "optionD": "allez",
        "correctOption": "A",
        "subConcept": "Conjugaison du futur proche avec nous",
        "explanation": "Avec le pronom sujet 'nous', le verbe aller au présent est 'allons' : 'nous allons visiter'.",
        "remediationTip": "Nous allons + infinitif."
      },
      {
        "id": "q-jhs2fre-t9-6",
        "quizId": "quiz-jhs2-fre-t9-loisirs-sports",
        "questionText": "Quel jeu de société traditionnel à pions noirs et blancs s'écrit au pluriel : 'jouer ... dames' ?",
        "optionA": "au",
        "optionB": "aux",
        "optionC": "à la",
        "optionD": "des",
        "correctOption": "B",
        "subConcept": "Jouer à + jeu pluriel",
        "explanation": "'dames' est un nom pluriel; à + les se contracte en 'aux' : 'jouer aux dames' (draughts/checkers).",
        "remediationTip": "Jeu pluriel -> AUX (jouer aux dames, jouer aux cartes)."
      },
      {
        "id": "q-jhs2fre-t9-7",
        "quizId": "quiz-jhs2-fre-t9-loisirs-sports",
        "questionText": "Quel loisir intellectuel consiste à déchiffrer des livres, des journaux ou des romans ?",
        "optionA": "la natation",
        "optionB": "la lecture",
        "optionC": "la boxe",
        "optionD": "le football",
        "correctOption": "B",
        "subConcept": "Vocabulaire des loisirs",
        "explanation": "'la lecture' (reading) est l'activité qui consiste à lire des ouvrages littéraires ou instructifs.",
        "remediationTip": "Reading = la lecture; to read = lire."
      },
      {
        "id": "q-jhs2fre-t9-8",
        "quizId": "quiz-jhs2-fre-t9-loisirs-sports",
        "questionText": "Complétez : 'Mon frère aîné aime faire ... vélo le samedi matin.'",
        "optionA": "au",
        "optionB": "du",
        "optionC": "de la",
        "optionD": "à",
        "correctOption": "B",
        "subConcept": "Faire de + activité masculine",
        "explanation": "'vélo' est masculin; faire + de + le = 'faire du vélo' (cycling).",
        "remediationTip": "Faire + nom masculin -> DU (faire du vélo)."
      },
      {
        "id": "q-jhs2fre-t9-9",
        "quizId": "quiz-jhs2-fre-t9-loisirs-sports",
        "questionText": "Où se place la négation 'ne... pas' au futur proche dans la phrase : 'Je vais nager' ?",
        "optionA": "Je ne vais pas nager.",
        "optionB": "Je vais ne nager pas.",
        "optionC": "Je vais pas nager ne.",
        "optionD": "Je nager pas vais.",
        "correctOption": "A",
        "subConcept": "Négation au futur proche",
        "explanation": "Au futur proche, 'ne... pas' encadre l'auxiliaire 'aller' : 'Je ne vais pas nager'.",
        "remediationTip": "La négation encadre le verbe aller: Je ne vais pas + infinitif."
      },
      {
        "id": "q-jhs2fre-t9-10",
        "quizId": "quiz-jhs2-fre-t9-loisirs-sports",
        "questionText": "Quel célèbre parc national ghanéen possède un pont de corde suspendu dans les arbres (canopy walkway) ?",
        "optionA": "Le parc de Mole",
        "optionB": "Le parc national de Kakum",
        "optionC": "Le lac Bosomtwe",
        "optionD": "Le barrage d'Akosombo",
        "correctOption": "B",
        "subConcept": "Tourisme ghanéen en français",
        "explanation": "Le parc national de Kakum près de Cape Coast est mondialement réputé pour sa passerelle suspendue dans la canopée.",
        "remediationTip": "Canopy walkway = Parc national de Kakum."
      }
    ]
  },
  "jhs2-fre-t10-metiers-professions": {
    "id": "quiz-jhs2-fre-t10-metiers-professions",
    "topicId": "jhs2-fre-t10-metiers-professions",
    "title": "Les Métiers, les Professions et l'Avenir BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t10-1",
        "quizId": "quiz-jhs2-fre-t10-metiers-professions",
        "questionText": "Quelle est la forme féminine de la profession 'un infirmier' (nurse) ?",
        "optionA": "une infirmière",
        "optionB": "une infirmiere",
        "optionC": "une infirmienne",
        "optionD": "une infirmiette",
        "correctOption": "A",
        "subConcept": "Féminin des noms en -er",
        "explanation": "Les noms masculins de métiers terminés par '-er' font leur féminin en '-ère' avec accent grave : un infirmier -> une infirmière.",
        "remediationTip": "-er devient -ère au féminin (infirmier -> infirmière; cuisinier -> cuisinière)."
      },
      {
        "id": "q-jhs2fre-t10-2",
        "quizId": "quiz-jhs2-fre-t10-metiers-professions",
        "questionText": "Quelle règle s'applique à l'article indéfini quand on déclare sa profession après le verbe être ('Je suis...') ?",
        "optionA": "On met obligatoirement 'un' ou 'une'",
        "optionB": "On omet totalement l'article indéfini ('Je suis médecin')",
        "optionC": "On met toujours l'article défini 'le'",
        "optionD": "On utilise l'article partitif 'du'",
        "correctOption": "B",
        "subConcept": "Omission de l'article avec profession",
        "explanation": "En français, après les verbes 'être' ou 'devenir', le nom de profession s'emploie sans article : 'Je suis médecin' / 'Elle est avocate'.",
        "remediationTip": "Ne mettez pas 'un/une' après être: Je suis professeur (correct); Je suis un professeur (incorrect)."
      },
      {
        "id": "q-jhs2fre-t10-3",
        "quizId": "quiz-jhs2-fre-t10-metiers-professions",
        "questionText": "Quel professionnel de santé examine, diagnostique et traite les maladies dans un hôpital ?",
        "optionA": "l'avocat",
        "optionB": "le médecin (le docteur)",
        "optionC": "le menuisier",
        "optionD": "le chauffeur",
        "correctOption": "B",
        "subConcept": "Métiers de la santé",
        "explanation": "Le médecin (doctor) est le praticien médical diplômé qui soigne les patients malades.",
        "remediationTip": "Doctor = le médecin ou le docteur."
      },
      {
        "id": "q-jhs2fre-t10-4",
        "quizId": "quiz-jhs2-fre-t10-metiers-professions",
        "questionText": "Quel est le féminin de 'un informaticien' (computer professional) ?",
        "optionA": "une informaticienne",
        "optionB": "une informaticière",
        "optionC": "une informaticieuse",
        "optionD": "une informaticite",
        "correctOption": "A",
        "subConcept": "Féminin des noms en -ien",
        "explanation": "Les métiers terminés par '-ien' doublent le 'n' et ajoutent un 'e' au féminin : informaticien -> informaticienne; pharmacien -> pharmacienne.",
        "remediationTip": "-ien devient -ienne au féminin (informaticien -> informaticienne)."
      },
      {
        "id": "q-jhs2fre-t10-5",
        "quizId": "quiz-jhs2-fre-t10-metiers-professions",
        "questionText": "Quel artisan travaille le bois pour fabriquer des portes, des tables et des armoires ?",
        "optionA": "le maçon",
        "optionB": "le menuisier",
        "optionC": "l'électricien",
        "optionD": "le mécanicien",
        "correctOption": "B",
        "subConcept": "Métiers de l'artisanat",
        "explanation": "Le menuisier (carpenter) façonne le bois pour produire du mobilier et des ouvertures de bâtiment.",
        "remediationTip": "Carpenter = le menuisier."
      },
      {
        "id": "q-jhs2fre-t10-6",
        "quizId": "quiz-jhs2-fre-t10-metiers-professions",
        "questionText": "Quel est le féminin de 'directeur' ?",
        "optionA": "directeuse",
        "optionB": "directrice",
        "optionC": "directère",
        "optionD": "direction",
        "correctOption": "B",
        "subConcept": "Féminin en -trice",
        "explanation": "La plupart des noms en '-teur' forment leur féminin en '-trice' : directeur -> directrice; acteur -> actrice.",
        "remediationTip": "-teur devient -trice au féminin (directeur -> directrice)."
      },
      {
        "id": "q-jhs2fre-t10-7",
        "quizId": "quiz-jhs2-fre-t10-metiers-professions",
        "questionText": "Qui défend les accusés et conseille les citoyens devant un tribunal de justice ?",
        "optionA": "l'avocat (l'avocate)",
        "optionB": "le pharmacien",
        "optionC": "le cultivateur",
        "optionD": "le maçon",
        "correctOption": "A",
        "subConcept": "Métiers du droit",
        "explanation": "L'avocat (lawyer) est le juriste professionnel chargé de défendre ses clients devant la cour de justice.",
        "remediationTip": "Lawyer = l'avocat."
      },
      {
        "id": "q-jhs2fre-t10-8",
        "quizId": "quiz-jhs2-fre-t10-metiers-professions",
        "questionText": "Quelle structure permet d'exprimer poliment son ambition d'avenir ?",
        "optionA": "Je déteste travailler.",
        "optionB": "À l'avenir, je voudrais devenir ingénieur.",
        "optionC": "J'ai fini mon travail hier.",
        "optionD": "Je refuse de grandir.",
        "correctOption": "B",
        "subConcept": "Expression des ambitions",
        "explanation": "'Je voudrais devenir...' exprime un projet d'avenir respectueux et déterminé.",
        "remediationTip": "'Je voudrais devenir...' = I would like to become..."
      },
      {
        "id": "q-jhs2fre-t10-9",
        "quizId": "quiz-jhs2-fre-t10-metiers-professions",
        "questionText": "Quel nom de métier ne change PAS de forme au féminin (reste identique avec 'une') ?",
        "optionA": "journaliste",
        "optionB": "enseignant",
        "optionC": "vendeur",
        "optionD": "boulanger",
        "correctOption": "A",
        "subConcept": "Métiers épicènes invariables",
        "explanation": "Les métiers déjà terminés par un 'e' muet au masculin ont la même forme au féminin : un journaliste -> une journaliste; un dentiste -> une dentiste.",
        "remediationTip": "Terminé par -e au masculin -> même forme au féminin: un/une journaliste."
      },
      {
        "id": "q-jhs2fre-t10-10",
        "quizId": "quiz-jhs2-fre-t10-metiers-professions",
        "questionText": "Quel professionnel répare les moteurs d'automobiles et les véhicules en panne ?",
        "optionA": "le mécanicien",
        "optionB": "le boulanger",
        "optionC": "le tailleur",
        "optionD": "le médecin",
        "correctOption": "A",
        "subConcept": "Métiers de la mécanique",
        "explanation": "Le mécanicien (mechanic) inspecte, entretient et répare les moteurs et véhicules.",
        "remediationTip": "Mechanic = le mécanicien."
      }
    ]
  },
  "jhs2-fre-t11-sante-maladies": {
    "id": "quiz-jhs2-fre-t11-sante-maladies",
    "topicId": "jhs2-fre-t11-sante-maladies",
    "title": "Le Corps Humain, la Santé et les Maladies BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t11-1",
        "quizId": "quiz-jhs2-fre-t11-sante-maladies",
        "questionText": "Complétez l'expression de douleur pour un nom masculin singulier : 'Kofi mange trop de piment, il a mal ... ventre.'",
        "optionA": "à la",
        "optionB": "au",
        "optionC": "aux",
        "optionD": "à l'",
        "correctOption": "B",
        "subConcept": "Avoir mal à + nom masculin",
        "explanation": "'ventre' est masculin singulier; la contraction de 'à + le' donne 'au' : avoir mal au ventre.",
        "remediationTip": "Masculin singulier -> AU (mal au ventre, au dos, au pied)."
      },
      {
        "id": "q-jhs2fre-t11-2",
        "quizId": "quiz-jhs2-fre-t11-sante-maladies",
        "questionText": "Quelle formule contractée utilise-t-on avec un nom pluriel : 'Elle ne peut pas mâcher car elle a mal ... dents' ?",
        "optionA": "au",
        "optionB": "aux",
        "optionC": "à la",
        "optionD": "de",
        "correctOption": "B",
        "subConcept": "Avoir mal à + nom pluriel",
        "explanation": "'dents' est au pluriel; la contraction de 'à + les' donne 'aux' : avoir mal aux dents.",
        "remediationTip": "Nom pluriel -> AUX (mal aux dents, aux yeux, aux oreilles)."
      },
      {
        "id": "q-jhs2fre-t11-3",
        "quizId": "quiz-jhs2-fre-t11-sante-maladies",
        "questionText": "Quel insecte femelle transmet le paludisme (malaria) par sa piqûre ?",
        "optionA": "la mouche",
        "optionB": "le moustique (l'anophèle)",
        "optionC": "l'abeille",
        "optionD": "la fourmi",
        "correctOption": "B",
        "subConcept": "Causes du paludisme",
        "explanation": "Le paludisme est causé par un parasite transmis par la piqûre du moustique femelle (l'anophèle).",
        "remediationTip": "Moustique = mosquito (vecteur du paludisme)."
      },
      {
        "id": "q-jhs2fre-t11-4",
        "quizId": "quiz-jhs2-fre-t11-sante-maladies",
        "questionText": "Complétez : 'J'ai trop marché sous le soleil brûlant, j'ai mal ... tête.'",
        "optionA": "au",
        "optionB": "à la",
        "optionC": "aux",
        "optionD": "à l'",
        "correctOption": "B",
        "subConcept": "Avoir mal à + nom féminin",
        "explanation": "'tête' est un nom féminin singulier : avoir mal à la tête (headache).",
        "remediationTip": "Féminin singulier -> À LA (mal à la tête, à la gorge)."
      },
      {
        "id": "q-jhs2fre-t11-5",
        "quizId": "quiz-jhs2-fre-t11-sante-maladies",
        "questionText": "Quel est le pluriel irrégulier du mot 'l'œil' (the eye) ?",
        "optionA": "les œils",
        "optionB": "les yeux",
        "optionC": "les œiles",
        "optionD": "les yeuxes",
        "correctOption": "B",
        "subConcept": "Pluriel irrégulier œil/yeux",
        "explanation": "Le mot 'œil' a un pluriel complètement irrégulier: 'un œil' -> 'les yeux'.",
        "remediationTip": "Un œil -> les yeux (irrégulier absolu)."
      },
      {
        "id": "q-jhs2fre-t11-6",
        "quizId": "quiz-jhs2-fre-t11-sante-maladies",
        "questionText": "Quels sont les symptômes majeurs d'une crise de paludisme ?",
        "optionA": "Une forte fièvre, des frissons et des maux de tête",
        "optionB": "Une excellente vision de nuit",
        "optionC": "Des cheveux qui poussent très vite",
        "optionD": "Une faim insatiable",
        "correctOption": "A",
        "subConcept": "Symptômes du paludisme",
        "explanation": "La malaria se manifeste par des poussées de fièvre élevée, des frissons (tremblements) et des céphalées (maux de tête).",
        "remediationTip": "Fièvre + frissons + mal de tête = paludisme."
      },
      {
        "id": "q-jhs2fre-t11-7",
        "quizId": "quiz-jhs2-fre-t11-sante-maladies",
        "questionText": "Quel conseil médical préventif protège les enfants contre les piqûres de moustiques la nuit ?",
        "optionA": "Dormir sous une moustiquaire imprégnée d'insecticide",
        "optionB": "Laisser les fenêtres grandes ouvertes sans grillage",
        "optionC": "Ne jamais se laver",
        "optionD": "Boire beaucoup de café glacé",
        "correctOption": "A",
        "subConcept": "Prévention du paludisme",
        "explanation": "Dormir sous une moustiquaire imprégnée constitue la barrière physique et chimique la plus efficace contre les moustiques.",
        "remediationTip": "Moustiquaire imprégnée = protection contre le paludisme."
      },
      {
        "id": "q-jhs2fre-t11-8",
        "quizId": "quiz-jhs2-fre-t11-sante-maladies",
        "questionText": "Complétez avec le bon article : 'L'enfant a couru et il est tombé, maintenant il a mal ... genou.'",
        "optionA": "à la",
        "optionB": "au",
        "optionC": "aux",
        "optionD": "en",
        "correctOption": "B",
        "subConcept": "Avoir mal à + genou",
        "explanation": "'genou' (knee) est masculin singulier : à + le = au genou.",
        "remediationTip": "Genou est masculin -> au genou."
      },
      {
        "id": "q-jhs2fre-t11-9",
        "quizId": "quiz-jhs2-fre-t11-sante-maladies",
        "questionText": "Que signifie le verbe 'tousser' ?",
        "optionA": "to sleep",
        "optionB": "to cough",
        "optionC": "to sneeze",
        "optionD": "to vomit",
        "correctOption": "B",
        "subConcept": "Vocabulaire des symptômes",
        "explanation": "'tousser' signifie 'to cough'. 'éternuer' signifie 'to sneeze'.",
        "remediationTip": "Tousser = to cough."
      },
      {
        "id": "q-jhs2fre-t11-10",
        "quizId": "quiz-jhs2-fre-t11-sante-maladies",
        "questionText": "Comment un médecin ordonne-t-il la prise de médicaments à l'impératif ?",
        "optionA": "Prenez ces comprimés deux fois par jour après le repas !",
        "optionB": "Vous prenez peut-être les comprimés.",
        "optionC": "Comprimés sont bons pour vous.",
        "optionD": "Ne prenez jamais de comprimés.",
        "correctOption": "A",
        "subConcept": "Impératif médical",
        "explanation": "Le médecin utilise l'impératif de politesse 'Prenez...' (Take...) pour donner une consigne thérapeutique claire.",
        "remediationTip": "Prenez vos médicaments ! (impératif de conseil médical)."
      }
    ]
  },
  "jhs2-fre-t12-voyages-transports": {
    "id": "quiz-jhs2-fre-t12-voyages-transports",
    "topicId": "jhs2-fre-t12-voyages-transports",
    "title": "Les Moyens de Transport et les Directions BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs2fre-t12-1",
        "quizId": "quiz-jhs2-fre-t12-voyages-transports",
        "questionText": "Quelle préposition utilise-t-on pour la marche à pied : 'Kwame va à l'école ... pied' ?",
        "optionA": "en",
        "optionB": "à",
        "optionC": "par",
        "optionD": "sur",
        "correctOption": "B",
        "subConcept": "Préposition avec pied",
        "explanation": "On dit obligatoirement 'À PIED' (on foot) en français, jamais 'en pied'.",
        "remediationTip": "Règle d'or: Toujours À PIED, jamais 'en pied'."
      },
      {
        "id": "q-jhs2fre-t12-2",
        "quizId": "quiz-jhs2-fre-t12-voyages-transports",
        "questionText": "Quelle préposition utilise-t-on pour les véhicules fermés comme la voiture, le bus ou le taxi ?",
        "optionA": "à",
        "optionB": "en",
        "optionC": "de",
        "optionD": "vers",
        "correctOption": "B",
        "subConcept": "Préposition avec véhicules fermés",
        "explanation": "Pour les moyens de transport fermés où l'on entre à l'intérieur, on emploie 'en' : en bus, en voiture, en taxi, en train, en avion.",
        "remediationTip": "Véhicules fermés = EN (en voiture, en bus, en avion)."
      },
      {
        "id": "q-jhs2fre-t12-3",
        "quizId": "quiz-jhs2-fre-t12-voyages-transports",
        "questionText": "Comment indique-t-on 'Go straight ahead' en français ?",
        "optionA": "Tournez à droite !",
        "optionB": "Allez tout droit !",
        "optionC": "Tournez à gauche !",
        "optionD": "Faites demi-tour !",
        "correctOption": "B",
        "subConcept": "Indiquer une direction",
        "explanation": "'Allez tout droit !' ou 'Continuez tout droit !' signifie avancer en ligne droite sans tourner.",
        "remediationTip": "Allez tout droit = Go straight ahead; Tournez à droite = Turn right."
      },
      {
        "id": "q-jhs2fre-t12-4",
        "quizId": "quiz-jhs2-fre-t12-voyages-transports",
        "questionText": "Comment appelle-t-on le minibus de transport en commun très populaire au Ghana ?",
        "optionA": "le tramway",
        "optionB": "le trotro",
        "optionC": "le téléphérique",
        "optionD": "la calèche",
        "correctOption": "B",
        "subConcept": "Transports locaux",
        "explanation": "Le 'trotro' est le terme national ghanéen désignant les minibus de transport en commun.",
        "remediationTip": "Trotro = minibus de transport urbain au Ghana."
      },
      {
        "id": "q-jhs2fre-t12-5",
        "quizId": "quiz-jhs2-fre-t12-voyages-transports",
        "questionText": "Quelle préposition utilise-t-on avec un deux-roues : 'Kweku se déplace ... vélo' ?",
        "optionA": "en",
        "optionB": "à",
        "optionC": "sous",
        "optionD": "dans",
        "correctOption": "B",
        "subConcept": "Préposition avec deux-roues",
        "explanation": "Pour les engins sur lesquels on monte à califourchon, la norme grammaticale exige 'à' : à vélo, à bicyclette, à moto, à cheval.",
        "remediationTip": "Deux-roues = À VÉLO, À MOTO."
      },
      {
        "id": "q-jhs2fre-t12-6",
        "quizId": "quiz-jhs2-fre-t12-voyages-transports",
        "questionText": "Comment dit-on 'Turn left' en français ?",
        "optionA": "Tournez à gauche !",
        "optionB": "Tournez à droite !",
        "optionC": "Allez tout droit !",
        "optionD": "Traversez le pont !",
        "correctOption": "A",
        "subConcept": "Directions - gauche",
        "explanation": "'à gauche' signifie 'to the left' ; 'à droite' signifie 'to the right'.",
        "remediationTip": "Gauche = left; Droite = right."
      },
      {
        "id": "q-jhs2fre-t12-7",
        "quizId": "quiz-jhs2-fre-t12-voyages-transports",
        "questionText": "D'où décollent et atterrissent les avions à Accra ?",
        "optionA": "À la gare maritime de Takoradi",
        "optionB": "À l'Aéroport International Kotoka",
        "optionC": "À la gare routière de Kaneshie",
        "optionD": "Au stade d'Accra",
        "correctOption": "B",
        "subConcept": "Infrastructures de transport",
        "explanation": "L'Aéroport International Kotoka (KIA) d'Accra est la principale porte d'entrée aérienne du Ghana.",
        "remediationTip": "Aéroport = airport (avions)."
      },
      {
        "id": "q-jhs2fre-t12-8",
        "quizId": "quiz-jhs2-fre-t12-voyages-transports",
        "questionText": "Comment demande-t-on son chemin poliment à un passant inconnu ?",
        "optionA": "Hé toi, amène-moi au marché !",
        "optionB": "Pardon Monsieur, où se trouve la poste, s'il vous plaît ?",
        "optionC": "Donne-moi ta voiture tout de suite !",
        "optionD": "Pourquoi es-tu ici ?",
        "correctOption": "B",
        "subConcept": "Demander la direction avec courtoisie",
        "explanation": "'Pardon Monsieur, où se trouve... s'il vous plaît ?' combine les formules de respect nécessaires envers un inconnu.",
        "remediationTip": "Toujours dire 'Pardon Monsieur/Madame' et 's'il vous plaît'."
      },
      {
        "id": "q-jhs2fre-t12-9",
        "quizId": "quiz-jhs2-fre-t12-voyages-transports",
        "questionText": "Que signifie le verbe 'traverser' dans : 'Traversez la route avec prudence !' ?",
        "optionA": "to run along",
        "optionB": "to cross",
        "optionC": "to stop",
        "optionD": "to sleep on",
        "correctOption": "B",
        "subConcept": "Verbes de déplacement",
        "explanation": "'traverser' signifie passer d'un côté à l'autre d'une rue, d'un pont ou d'un carrefour (to cross).",
        "remediationTip": "Traverser = to cross."
      },
      {
        "id": "q-jhs2fre-t12-10",
        "quizId": "quiz-jhs2-fre-t12-voyages-transports",
        "questionText": "Quel moyen de transport aquatique traditionnel les pêcheurs ghanéens utilisent-ils en mer ou sur le lac Volta ?",
        "optionA": "le sous-marin",
        "optionB": "la pirogue",
        "optionC": "l'aéroglisseur",
        "optionD": "le paquebot géant",
        "correctOption": "B",
        "subConcept": "Transports fluviaux et maritimes",
        "explanation": "La pirogue (canoe) taillée dans un tronc d'arbre est le moyen traditionnel d'embarcation des pêcheurs au Ghana.",
        "remediationTip": "Pirogue = traditional canoe."
      }
    ]
  }
};
