// Ghanaian JHS 1 Mathematics Comprehensive Practice Quizzes
// Based on NaCCA / GES Common Core Programme (CCP) Curriculum
// 15 Topics × 10 Questions = 150 BECE-Standard Questions

import { TopicQuiz } from './types';

export const JHS1_MATH_QUIZZES: Record<string, TopicQuiz> = {
  "jhs1-math-t1-sets": {
    "id": "quiz-jhs1-math-sets",
    "topicId": "jhs1-math-t1-sets",
    "title": "Sets & Operations Mastery Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-sets-1",
        "quizId": "quiz-jhs1-math-sets",
        "questionText": "If set P = {x, y, z}, how many total subsets does P have in all?",
        "optionA": "3",
        "optionB": "6",
        "optionC": "8",
        "optionD": "9",
        "correctOption": "C",
        "subConcept": "Number of Subsets Formula (2^n)",
        "explanation": "The number of subsets of any set with n elements is given by 2^n. For n = 3, 2³ = 2 × 2 × 2 = 8 subsets (including the empty set and the set itself).",
        "remediationTip": "Always calculate total subsets using 2^n, where n is the number of members in the set."
      },
      {
        "id": "q-sets-2",
        "quizId": "quiz-jhs1-math-sets",
        "questionText": "Which of the following notations correctly represents an empty or null set?",
        "optionA": "{0}",
        "optionB": "{∅}",
        "optionC": "∅ or {}",
        "optionD": "{null}",
        "correctOption": "C",
        "subConcept": "Null / Empty Set Notation",
        "explanation": "An empty set contains no elements and is written either as ∅ or {}. Writing {∅} represents a set with one element (the symbol ∅), and {0} is a set containing the number 0.",
        "remediationTip": "Never put the null symbol ∅ inside curly braces. Use either ∅ or {} alone."
      },
      {
        "id": "q-sets-3",
        "quizId": "quiz-jhs1-math-sets",
        "questionText": "Given A = {2, 3, 5, 7, 11} and B = {1, 3, 5, 7, 9}, what is A ∩ B?",
        "optionA": "{2, 11}",
        "optionB": "{3, 5, 7}",
        "optionC": "{1, 2, 3, 5, 7, 9, 11}",
        "optionD": "∅",
        "correctOption": "B",
        "subConcept": "Intersection of Sets (A ∩ B)",
        "explanation": "The intersection (A ∩ B) consists of elements appearing in BOTH set A and set B. The numbers 3, 5, and 7 appear in both sets.",
        "remediationTip": "Intersection means \"common to both sets\". Look only for numbers present in both lists."
      },
      {
        "id": "q-sets-4",
        "quizId": "quiz-jhs1-math-sets",
        "questionText": "Given X = {a, b, c} and Y = {c, d, e}, determine the union X ∪ Y.",
        "optionA": "{c}",
        "optionB": "{a, b, c, c, d, e}",
        "optionC": "{a, b, d, e}",
        "optionD": "{a, b, c, d, e}",
        "correctOption": "D",
        "subConcept": "Union of Sets (X ∪ Y)",
        "explanation": "The union of sets combines all distinct elements from both sets without repeating duplicates. Therefore, X ∪ Y = {a, b, c, d, e}.",
        "remediationTip": "In set union, merge all members from both sets and eliminate duplicate listings."
      },
      {
        "id": "q-sets-5",
        "quizId": "quiz-jhs1-math-sets",
        "questionText": "Let the Universal set U = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10} and set P = {2, 3, 5, 7}. Find P' (the complement of P).",
        "optionA": "{1, 4, 6, 8, 9, 10}",
        "optionB": "{2, 3, 5, 7}",
        "optionC": "{0, 1, 4, 6, 8}",
        "optionD": "{4, 6, 8, 10}",
        "correctOption": "A",
        "subConcept": "Complement of a Set (P')",
        "explanation": "The complement P' contains all elements in universal set U that are NOT in set P. Removing {2, 3, 5, 7} from U leaves {1, 4, 6, 8, 9, 10}.",
        "remediationTip": "To find the complement of a set, cross out its members from the Universal set U; the remaining elements form the complement."
      },
      {
        "id": "q-sets-6",
        "quizId": "quiz-jhs1-math-sets",
        "questionText": "Two sets A and B are described as disjoint. What does this mean about their relationship?",
        "optionA": "A = B",
        "optionB": "A ∩ B = ∅",
        "optionC": "A ⊆ B",
        "optionD": "n(A) = n(B)",
        "correctOption": "B",
        "subConcept": "Disjoint Sets",
        "explanation": "Disjoint sets share no common elements at all, meaning their intersection is empty: A ∩ B = ∅.",
        "remediationTip": "Disjoint means \"mutually exclusive\" or non-overlapping: intersection is equal to ∅."
      },
      {
        "id": "q-sets-7",
        "quizId": "quiz-jhs1-math-sets",
        "questionText": "In a class of 30 pupils, 18 play Football (F), 14 play Volleyball (V), and 6 play both games. How many pupils play Football ONLY?",
        "optionA": "18",
        "optionB": "14",
        "optionC": "12",
        "optionD": "8",
        "correctOption": "C",
        "subConcept": "Two-Set Venn Diagrams (Only Region)",
        "explanation": "Football ONLY is found by subtracting pupils playing both from total football players: n(F only) = n(F) - n(F ∩ V) = 18 - 6 = 12.",
        "remediationTip": "In Venn diagrams, always subtract the intersection (both) from the total circle to find the \"only\" region."
      },
      {
        "id": "q-sets-8",
        "quizId": "quiz-jhs1-math-sets",
        "questionText": "If U = {x : x is an integer, 1 ≤ x ≤ 10} and set K = {x : x is a multiple of 3}, list the elements of K.",
        "optionA": "{3, 6, 9}",
        "optionB": "{3, 6, 9, 12}",
        "optionC": "{1, 3, 6, 9}",
        "optionD": "{3, 6}",
        "correctOption": "A",
        "subConcept": "Set-Builder Notation",
        "explanation": "Multiples of 3 between 1 and 10 inclusive are 3, 6, and 9. 12 is outside the universal set U.",
        "remediationTip": "Always check the boundary constraints of the universal set when generating members from set-builder notation."
      },
      {
        "id": "q-sets-9",
        "quizId": "quiz-jhs1-math-sets",
        "questionText": "Set M has 4 members and Set N has 4 members, but their elements are different. What term best describes sets M and N?",
        "optionA": "Equal sets",
        "optionB": "Equivalent sets",
        "optionC": "Universal sets",
        "optionD": "Subset pairs",
        "correctOption": "B",
        "subConcept": "Equal vs Equivalent Sets",
        "explanation": "Equivalent sets have the exact same number of elements (same cardinality, n(M) = n(N)), even if the elements themselves are different.",
        "remediationTip": "Equal sets have identical elements. Equivalent sets have the same quantity of elements."
      },
      {
        "id": "q-sets-10",
        "quizId": "quiz-jhs1-math-sets",
        "questionText": "In a group of 40 students, 22 study French, 18 study Twi, and 8 study both. How many students study NEITHER French nor Twi?",
        "optionA": "8",
        "optionB": "10",
        "optionC": "14",
        "optionD": "12",
        "correctOption": "A",
        "subConcept": "Universal Set & Neither Region in Venn Diagrams",
        "explanation": "French only = 22 - 8 = 14. Twi only = 18 - 8 = 10. Both = 8. Students taking at least one = 14 + 10 + 8 = 32. Neither = Total - 32 = 40 - 32 = 8.",
        "remediationTip": "Add [Only A] + [Only B] + [Both], then subtract that sum from the Universal total to find \"Neither\"."
      }
    ]
  },
  "jhs1-math-t2-realnumbers": {
    "id": "quiz-jhs1-math-realnumbers",
    "topicId": "jhs1-math-t2-realnumbers",
    "title": "Real Numbers & Place Value Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-real-1",
        "quizId": "quiz-jhs1-math-realnumbers",
        "questionText": "What is the place value of the digit 7 in the numeral 4,785,210?",
        "optionA": "Ten thousands",
        "optionB": "Hundred thousands",
        "optionC": "Millions",
        "optionD": "Thousands",
        "correctOption": "B",
        "subConcept": "Place Value Identification",
        "explanation": "In 4,785,210, reading from right: 0 is units, 1 is tens, 2 is hundreds, 5 is thousands, 8 is ten thousands, and 7 is hundred thousands.",
        "remediationTip": "Count place value columns starting from the right: Units, Tens, Hundreds, Thousands, Ten Thousands, Hundred Thousands."
      },
      {
        "id": "q-real-2",
        "quizId": "quiz-jhs1-math-realnumbers",
        "questionText": "What is the actual value of the digit 6 in 962,415?",
        "optionA": "600",
        "optionB": "6,000",
        "optionC": "60,000",
        "optionD": "600,000",
        "correctOption": "C",
        "subConcept": "Digit Value vs Place Value",
        "explanation": "The digit 6 is in the ten thousands column. Its value is 6 × 10,000 = 60,000.",
        "remediationTip": "Remember: Total Value = Digit × Place Value."
      },
      {
        "id": "q-real-3",
        "quizId": "quiz-jhs1-math-realnumbers",
        "questionText": "Which of the following numbers is prime?",
        "optionA": "1",
        "optionB": "9",
        "optionC": "15",
        "optionD": "29",
        "correctOption": "D",
        "subConcept": "Prime Numbers Definition",
        "explanation": "A prime number has exactly two distinct factors: 1 and itself. 29 has only 1 and 29 as factors. (1 is not prime; 9 has factor 3; 15 has factors 3 and 5).",
        "remediationTip": "Remember that 1 is not a prime number, and 2 is the only even prime number."
      },
      {
        "id": "q-real-4",
        "quizId": "quiz-jhs1-math-realnumbers",
        "questionText": "Express 72 as a product of its prime factors in index notation.",
        "optionA": "2³ × 3²",
        "optionB": "2² × 3³",
        "optionC": "8 × 9",
        "optionD": "2⁴ × 3",
        "correctOption": "A",
        "subConcept": "Prime Factorization in Index Form",
        "explanation": "72 ÷ 2 = 36; 36 ÷ 2 = 18; 18 ÷ 2 = 9; 9 ÷ 3 = 3; 3 ÷ 3 = 1. So 72 = 2 × 2 × 2 × 3 × 3 = 2³ × 3².",
        "remediationTip": "Always break down composite numbers into prime bases using continuous division."
      },
      {
        "id": "q-real-5",
        "quizId": "quiz-jhs1-math-realnumbers",
        "questionText": "Find the Highest Common Factor (HCF) of 24 and 36.",
        "optionA": "6",
        "optionB": "12",
        "optionC": "18",
        "optionD": "72",
        "correctOption": "B",
        "subConcept": "Highest Common Factor (HCF)",
        "explanation": "24 = 2³ × 3; 36 = 2² × 3². The HCF takes the lowest power of common prime factors: 2² × 3¹ = 4 × 3 = 12.",
        "remediationTip": "For HCF, take only common prime factors raised to their lowest powers."
      },
      {
        "id": "q-real-6",
        "quizId": "quiz-jhs1-math-realnumbers",
        "questionText": "Find the Least Common Multiple (LCM) of 12, 18, and 24.",
        "optionA": "36",
        "optionB": "48",
        "optionC": "72",
        "optionD": "144",
        "correctOption": "C",
        "subConcept": "Least Common Multiple (LCM)",
        "explanation": "12 = 2² × 3; 18 = 2 × 3²; 24 = 2³ × 3. LCM takes the highest power of all prime factors: 2³ × 3² = 8 × 9 = 72.",
        "remediationTip": "For LCM, take the highest power of every prime factor that appears in any of the factorizations."
      },
      {
        "id": "q-real-7",
        "quizId": "quiz-jhs1-math-realnumbers",
        "questionText": "Write the number 405,027 in expanded form.",
        "optionA": "(4 × 100,000) + (5 × 1,000) + (2 × 10) + (7 × 1)",
        "optionB": "(4 × 10,000) + (5 × 1,000) + (2 × 10) + (7 × 1)",
        "optionC": "(4 × 100,000) + (5 × 10,000) + (2 × 100) + (7 × 1)",
        "optionD": "(4 × 1,000,000) + (5 × 10,000) + (27 × 1)",
        "correctOption": "A",
        "subConcept": "Expanded Notation of Numbers",
        "explanation": "405,027 = 400,000 + 5,000 + 20 + 7 = (4 × 100,000) + (5 × 1,000) + (2 × 10) + (7 × 1).",
        "remediationTip": "Skip columns with digit 0 when writing the standard expanded form, or write 0 × place value."
      },
      {
        "id": "q-real-8",
        "quizId": "quiz-jhs1-math-realnumbers",
        "questionText": "Round off 84,672 to the nearest thousand.",
        "optionA": "84,000",
        "optionB": "84,600",
        "optionC": "84,700",
        "optionD": "85,000",
        "correctOption": "D",
        "subConcept": "Approximation & Rounding Off",
        "explanation": "To round to the nearest thousand, examine the hundreds digit (6). Since 6 ≥ 5, round the thousands digit (4) up by 1 to 5, giving 85,000.",
        "remediationTip": "Check the digit immediately to the right of your target place: if 5 or greater, round up; if less than 5, round down."
      },
      {
        "id": "q-real-9",
        "quizId": "quiz-jhs1-math-realnumbers",
        "questionText": "Which set of numbers contains only whole numbers?",
        "optionA": "{-2, -1, 0, 1, 2}",
        "optionB": "{0, 1, 2, 3, 4, 5}",
        "optionC": "{1, 2, 3, 4, 5}",
        "optionD": "{1/2, 1, 3/2, 2}",
        "correctOption": "B",
        "subConcept": "Real Number System Hierarchy",
        "explanation": "Whole numbers (W) consist of 0 and all positive counting numbers: {0, 1, 2, 3...}. Negative numbers are integers, not whole numbers.",
        "remediationTip": "Remember: Natural numbers = {1, 2, 3...}; Whole numbers = {0, 1, 2, 3...}; Integers = {... -2, -1, 0, 1, 2 ...}."
      },
      {
        "id": "q-real-10",
        "quizId": "quiz-jhs1-math-realnumbers",
        "questionText": "Two traffic lights flash at intervals of 12 seconds and 20 seconds. If they flash together now, after how many seconds will they flash together again?",
        "optionA": "32 seconds",
        "optionB": "40 seconds",
        "optionC": "60 seconds",
        "optionD": "120 seconds",
        "correctOption": "C",
        "subConcept": "Real-Life LCM Applications",
        "explanation": "The time they flash together again is the LCM of 12 and 20. 12 = 2² × 3, 20 = 2² × 5. LCM = 2² × 3 × 5 = 60 seconds.",
        "remediationTip": "Whenever a problem involves repeating cycles occurring together at the same time, find the LCM."
      }
    ]
  },
  "jhs1-math-t3-integers": {
    "id": "quiz-jhs1-math-integers",
    "topicId": "jhs1-math-t3-integers",
    "title": "Integers & Operations Mastery Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-int-1",
        "quizId": "quiz-jhs1-math-integers",
        "questionText": "Arrange the following integers in ascending order (least to greatest): 5, -8, 2, -3, 0.",
        "optionA": "-8, -3, 0, 2, 5",
        "optionB": "0, -3, -8, 2, 5",
        "optionC": "-3, -8, 0, 2, 5",
        "optionD": "5, 2, 0, -3, -8",
        "correctOption": "A",
        "subConcept": "Ordering Integers on a Number Line",
        "explanation": "On a horizontal number line, numbers furthest to the left have smaller values. -8 is smaller than -3, followed by 0, 2, and 5.",
        "remediationTip": "For negative numbers, the larger the magnitude, the smaller its actual value (-8 < -3)."
      },
      {
        "id": "q-int-2",
        "quizId": "quiz-jhs1-math-integers",
        "questionText": "Evaluate: (-9) + (-7)",
        "optionA": "16",
        "optionB": "-16",
        "optionC": "-2",
        "optionD": "2",
        "correctOption": "B",
        "subConcept": "Addition of Negative Integers",
        "explanation": "When adding two numbers with the same negative sign, add their absolute values and retain the negative sign: -(9 + 7) = -16.",
        "remediationTip": "Negative plus negative equals a larger negative: (-a) + (-b) = -(a + b)."
      },
      {
        "id": "q-int-3",
        "quizId": "quiz-jhs1-math-integers",
        "questionText": "Calculate: 6 - (-11)",
        "optionA": "-5",
        "optionB": "5",
        "optionC": "-17",
        "optionD": "17",
        "correctOption": "D",
        "subConcept": "Subtraction of Negative Integers",
        "explanation": "Subtracting a negative number is equivalent to adding its positive counterpart: 6 - (-11) = 6 + 11 = 17.",
        "remediationTip": "Two minus signs together turn into a plus: a - (-b) = a + b."
      },
      {
        "id": "q-int-4",
        "quizId": "quiz-jhs1-math-integers",
        "questionText": "What is the product of (-7) and (-8)?",
        "optionA": "-56",
        "optionB": "56",
        "optionC": "-15",
        "optionD": "1",
        "correctOption": "B",
        "subConcept": "Multiplication Sign Rules",
        "explanation": "Multiplying two numbers with like signs gives a positive result: negative × negative = positive. Thus (-7) × (-8) = +56.",
        "remediationTip": "Multiplication rule: Negative × Negative = Positive."
      },
      {
        "id": "q-int-5",
        "quizId": "quiz-jhs1-math-integers",
        "questionText": "Evaluate: (-54) ÷ (+9)",
        "optionA": "6",
        "optionB": "-6",
        "optionC": "-45",
        "optionD": "-63",
        "correctOption": "B",
        "subConcept": "Division Sign Rules",
        "explanation": "Dividing numbers with unlike signs always yields a negative quotient: negative ÷ positive = negative. (-54) ÷ 9 = -6.",
        "remediationTip": "Division rule: Negative ÷ Positive = Negative."
      },
      {
        "id": "q-int-6",
        "quizId": "quiz-jhs1-math-integers",
        "questionText": "Simplify: 12 - 4 × (-3) + 5",
        "optionA": "-5",
        "optionB": "29",
        "optionC": "-19",
        "optionD": "11",
        "correctOption": "B",
        "subConcept": "BODMAS with Negative Numbers",
        "explanation": "Multiplication first: 4 × (-3) = -12. Then: 12 - (-12) + 5 = 12 + 12 + 5 = 24 + 5 = 29.",
        "remediationTip": "Always follow BODMAS: multiply before subtracting or adding, and watch the double minus."
      },
      {
        "id": "q-int-7",
        "quizId": "quiz-jhs1-math-integers",
        "questionText": "What is the value of |-25| - |14|?",
        "optionA": "-39",
        "optionB": "-11",
        "optionC": "11",
        "optionD": "39",
        "correctOption": "C",
        "subConcept": "Absolute Value Properties",
        "explanation": "The absolute value is the distance from 0, always non-negative: |-25| = 25 and |14| = 14. So 25 - 14 = 11.",
        "remediationTip": "Absolute value makes any number non-negative: |-x| = x."
      },
      {
        "id": "q-int-8",
        "quizId": "quiz-jhs1-math-integers",
        "questionText": "At 6:00 AM the temperature was -3°C. By 2:00 PM the temperature rose by 14°C. What was the temperature at 2:00 PM?",
        "optionA": "-17°C",
        "optionB": "-11°C",
        "optionC": "11°C",
        "optionD": "17°C",
        "correctOption": "C",
        "subConcept": "Integer Word Problems (Temperature)",
        "explanation": "Initial temp + rise = -3 + 14 = 11°C.",
        "remediationTip": "A rise or increase means addition: initial + rise."
      },
      {
        "id": "q-int-9",
        "quizId": "quiz-jhs1-math-integers",
        "questionText": "Simplify: (-3) × [8 - (-2)]",
        "optionA": "-18",
        "optionB": "-30",
        "optionC": "30",
        "optionD": "-14",
        "correctOption": "B",
        "subConcept": "Nested Brackets with Integers",
        "explanation": "Work inside brackets first: 8 - (-2) = 8 + 2 = 10. Then (-3) × 10 = -30.",
        "remediationTip": "Always solve inside parentheses/brackets completely before multiplying the outside factor."
      },
      {
        "id": "q-int-10",
        "quizId": "quiz-jhs1-math-integers",
        "questionText": "Which of the following inequality statements is TRUE?",
        "optionA": "-15 > -8",
        "optionB": "-10 < -12",
        "optionC": "-7 < -4",
        "optionD": "0 < -5",
        "correctOption": "C",
        "subConcept": "Comparing Integers with Inequalities",
        "explanation": "-7 is further to the left on the number line than -4, which means -7 is strictly less than -4 (-7 < -4).",
        "remediationTip": "On a number line, a number to the left is always strictly less than a number to its right."
      }
    ]
  },
  "jhs1-math-t4-numberbases": {
    "id": "quiz-jhs1-math-numberbases",
    "topicId": "jhs1-math-t4-numberbases",
    "title": "Number Bases (Base 2 & 10) Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-base-1",
        "quizId": "quiz-jhs1-math-numberbases",
        "questionText": "Which digits are permissible in Base 2 (binary) numbers?",
        "optionA": "0, 1, and 2",
        "optionB": "1 and 2 only",
        "optionC": "0 and 1 only",
        "optionD": "Any single digit from 0 to 9",
        "correctOption": "C",
        "subConcept": "Base Digits Rule",
        "explanation": "In any base n, the allowed digits run from 0 to n - 1. Therefore, in base 2, the only digits used are 0 and 1.",
        "remediationTip": "A number in base n cannot contain the digit n itself or any digit higher than n - 1."
      },
      {
        "id": "q-base-2",
        "quizId": "quiz-jhs1-math-numberbases",
        "questionText": "What is the place value of the leftmost digit in the binary number 1000₂?",
        "optionA": "2",
        "optionB": "4",
        "optionC": "8",
        "optionD": "16",
        "correctOption": "C",
        "subConcept": "Binary Place Values",
        "explanation": "Reading binary place values from right: 2⁰ = 1, 2¹ = 2, 2² = 4, 2³ = 8. The leftmost digit is in the 2³ (8) column.",
        "remediationTip": "Binary powers start at 2⁰ = 1 on the far right, then double each step to the left: 1, 2, 4, 8, 16..."
      },
      {
        "id": "q-base-3",
        "quizId": "quiz-jhs1-math-numberbases",
        "questionText": "Convert the binary numeral 1101₂ to base 10 (denary).",
        "optionA": "11",
        "optionB": "13",
        "optionC": "15",
        "optionD": "26",
        "correctOption": "B",
        "subConcept": "Binary to Denary Conversion",
        "explanation": "1101₂ = (1 × 2³) + (1 × 2²) + (0 × 2¹) + (1 × 2⁰) = (1 × 8) + (1 × 4) + (0 × 2) + (1 × 1) = 8 + 4 + 0 + 1 = 13.",
        "remediationTip": "Multiply each binary digit by its corresponding power of 2 and sum the results."
      },
      {
        "id": "q-base-4",
        "quizId": "quiz-jhs1-math-numberbases",
        "questionText": "Convert 10110₂ to base 10.",
        "optionA": "18",
        "optionB": "20",
        "optionC": "22",
        "optionD": "24",
        "correctOption": "C",
        "subConcept": "Binary to Denary Conversion",
        "explanation": "10110₂ = (1 × 16) + (0 × 8) + (1 × 4) + (1 × 2) + (0 × 1) = 16 + 0 + 4 + 2 + 0 = 22.",
        "remediationTip": "Assign powers: 16, 8, 4, 2, 1. Add columns with digit 1: 16 + 4 + 2 = 22."
      },
      {
        "id": "q-base-5",
        "quizId": "quiz-jhs1-math-numberbases",
        "questionText": "Convert the base 10 number 25 to binary (base 2).",
        "optionA": "11001₂",
        "optionB": "10101₂",
        "optionC": "11010₂",
        "optionD": "11100₂",
        "correctOption": "A",
        "subConcept": "Denary to Binary Conversion",
        "explanation": "25 ÷ 2 = 12 r1; 12 ÷ 2 = 6 r0; 6 ÷ 2 = 3 r0; 3 ÷ 2 = 1 r1; 1 ÷ 2 = 0 r1. Reading remainders from bottom to top gives 11001₂.",
        "remediationTip": "Use repeated division by 2 and read remainders from the bottom-most quotient up to the top."
      },
      {
        "id": "q-base-6",
        "quizId": "quiz-jhs1-math-numberbases",
        "questionText": "Convert the decimal number 19 to binary.",
        "optionA": "10011₂",
        "optionB": "10101₂",
        "optionC": "11001₂",
        "optionD": "1111₂",
        "correctOption": "A",
        "subConcept": "Denary to Binary Conversion",
        "explanation": "19 = 16 + 2 + 1 = 2⁴ + 2¹ + 2⁰ = 10011₂.",
        "remediationTip": "Break down the number into powers of 2 (16, 8, 4, 2, 1): 19 = 16 + 2 + 1 -> 1 0 0 1 1₂."
      },
      {
        "id": "q-base-7",
        "quizId": "quiz-jhs1-math-numberbases",
        "questionText": "Evaluate the binary addition: 101₂ + 110₂",
        "optionA": "1011₂",
        "optionB": "1111₂",
        "optionC": "1001₂",
        "optionD": "1101₂",
        "correctOption": "A",
        "subConcept": "Binary Addition",
        "explanation": "In column addition: 1 + 0 = 1; 0 + 1 = 1; 1 + 1 = 10₂. So 101₂ + 110₂ = 1011₂. (Checking in base 10: 5 + 6 = 11, and 1011₂ = 11).",
        "remediationTip": "In binary: 1 + 1 = 0 carry 1. Always verify by converting to base 10."
      },
      {
        "id": "q-base-8",
        "quizId": "quiz-jhs1-math-numberbases",
        "questionText": "Calculate: 111₂ + 011₂ in base 2.",
        "optionA": "1000₂",
        "optionB": "1010₂",
        "optionC": "1100₂",
        "optionD": "1110₂",
        "correctOption": "B",
        "subConcept": "Binary Addition with Carrying",
        "explanation": "111₂ (7) + 011₂ (3) = 10 in denary = 1010₂.",
        "remediationTip": "Remember that 1 + 1 + 1 (with carry) = 11₂ (write 1, carry 1)."
      },
      {
        "id": "q-base-9",
        "quizId": "quiz-jhs1-math-numberbases",
        "questionText": "Evaluate the binary subtraction: 1101₂ - 1001₂",
        "optionA": "100₂",
        "optionB": "10₂",
        "optionC": "1000₂",
        "optionD": "110₂",
        "correctOption": "A",
        "subConcept": "Binary Subtraction",
        "explanation": "Subtracting place by place: 1 - 1 = 0; 0 - 0 = 0; 1 - 0 = 1; 1 - 1 = 0. Result = 100₂. (In base 10: 13 - 9 = 4, and 100₂ = 4).",
        "remediationTip": "Subtract columns from right to left; check your final answer in base 10."
      },
      {
        "id": "q-base-10",
        "quizId": "quiz-jhs1-math-numberbases",
        "questionText": "Which represents 11010₂ written in expanded power of 2 form?",
        "optionA": "(1 × 2⁴) + (1 × 2³) + (0 × 2²) + (1 × 2¹) + (0 × 2⁰)",
        "optionB": "(1 × 2⁵) + (1 × 2⁴) + (0 × 2³) + (1 × 2²) + (0 × 2¹)",
        "optionC": "(1 × 10⁴) + (1 × 10³) + (1 × 10¹)",
        "optionD": "(1 × 2⁴) + (1 × 2²) + (0 × 2⁰)",
        "correctOption": "A",
        "subConcept": "Expanded Binary Form",
        "explanation": "There are 5 digits, so powers run from 2⁴ down to 2⁰: (1 × 2⁴) + (1 × 2³) + (0 × 2²) + (1 × 2¹) + (0 × 2⁰).",
        "remediationTip": "Count digits: if there are k digits, the highest power is 2^(k-1)."
      }
    ]
  },
  "jhs1-math-t5-fractions": {
    "id": "quiz-jhs1-math-fractions",
    "topicId": "jhs1-math-t5-fractions",
    "title": "Fractions, Decimals & Percentages Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-frac-1",
        "quizId": "quiz-jhs1-math-fractions",
        "questionText": "Find the missing value x in the equivalent fractions: 3/5 = x/20.",
        "optionA": "8",
        "optionB": "12",
        "optionC": "15",
        "optionD": "16",
        "correctOption": "B",
        "subConcept": "Equivalent Fractions",
        "explanation": "The denominator 5 was multiplied by 4 to get 20. Multiplying the numerator 3 by 4 gives x = 12.",
        "remediationTip": "Whatever multiplier connects the denominators must also be multiplied to the numerator."
      },
      {
        "id": "q-frac-2",
        "quizId": "quiz-jhs1-math-fractions",
        "questionText": "Simplify the fraction 36/48 to its simplest form.",
        "optionA": "6/8",
        "optionB": "18/24",
        "optionC": "3/4",
        "optionD": "2/3",
        "correctOption": "C",
        "subConcept": "Simplifying Fractions to Lowest Terms",
        "explanation": "The HCF of 36 and 48 is 12. Dividing numerator and denominator by 12: 36 ÷ 12 = 3, 48 ÷ 12 = 4 -> 3/4.",
        "remediationTip": "Divide both top and bottom by their HCF until no common factor remains except 1."
      },
      {
        "id": "q-frac-3",
        "quizId": "quiz-jhs1-math-fractions",
        "questionText": "Calculate: 2/3 + 1/4",
        "optionA": "3/7",
        "optionB": "11/12",
        "optionC": "8/12",
        "optionD": "5/12",
        "correctOption": "B",
        "subConcept": "Addition of Fractions with Unlike Denominators",
        "explanation": "LCM of 3 and 4 is 12. 2/3 = 8/12 and 1/4 = 3/12. Adding gives (8 + 3)/12 = 11/12.",
        "remediationTip": "Never add denominators directly! Always find the LCM of denominators first."
      },
      {
        "id": "q-frac-4",
        "quizId": "quiz-jhs1-math-fractions",
        "questionText": "Evaluate: 3 1/2 - 1 3/4",
        "optionA": "1 1/2",
        "optionB": "1 3/4",
        "optionC": "2 1/4",
        "optionD": "1 1/4",
        "correctOption": "B",
        "subConcept": "Subtraction of Mixed Numbers",
        "explanation": "Convert to improper fractions: 7/2 - 7/4 = 14/4 - 7/4 = 7/4 = 1 3/4.",
        "remediationTip": "Convert mixed numbers to improper fractions before subtracting to avoid borrow errors."
      },
      {
        "id": "q-frac-5",
        "quizId": "quiz-jhs1-math-fractions",
        "questionText": "Calculate: 4/9 × 3/8",
        "optionA": "1/6",
        "optionB": "7/17",
        "optionC": "12/72",
        "optionD": "1/4",
        "correctOption": "A",
        "subConcept": "Multiplication of Fractions",
        "explanation": "Cancel common factors: 4 and 8 cancel to 1 and 2. 3 and 9 cancel to 1 and 3. Result = (1 × 1) / (3 × 2) = 1/6.",
        "remediationTip": "Cross-cancel numerator and denominator factors before multiplying to keep numbers small."
      },
      {
        "id": "q-frac-6",
        "quizId": "quiz-jhs1-math-fractions",
        "questionText": "Evaluate: 5/6 ÷ 2/3",
        "optionA": "5/9",
        "optionB": "1 1/4",
        "optionC": "10/18",
        "optionD": "1/2",
        "correctOption": "B",
        "subConcept": "Division of Fractions (Keep-Change-Flip)",
        "explanation": "Keep 5/6, change ÷ to ×, flip 2/3 to 3/2: 5/6 × 3/2 = (5 × 3) / (6 × 2) = 15/12 = 5/4 = 1 1/4.",
        "remediationTip": "Remember the rule: Keep first fraction, Change division to multiplication, Flip second fraction."
      },
      {
        "id": "q-frac-7",
        "quizId": "quiz-jhs1-math-fractions",
        "questionText": "Convert the fraction 3/8 into a decimal.",
        "optionA": "0.3",
        "optionB": "0.375",
        "optionC": "0.38",
        "optionD": "0.83",
        "correctOption": "B",
        "subConcept": "Fraction to Decimal Conversion",
        "explanation": "Divide 3 by 8: 3.000 ÷ 8 = 0.375.",
        "remediationTip": "Carry out long division of numerator ÷ denominator by adding decimal zeroes."
      },
      {
        "id": "q-frac-8",
        "quizId": "quiz-jhs1-math-fractions",
        "questionText": "Convert the decimal 0.65 into a fraction in its lowest terms.",
        "optionA": "65/10",
        "optionB": "13/20",
        "optionC": "65/1000",
        "optionD": "7/10",
        "correctOption": "B",
        "subConcept": "Decimal to Fraction Conversion",
        "explanation": "0.65 = 65/100. Divide both by 5: 65 ÷ 5 = 13, 100 ÷ 5 = 20 -> 13/20.",
        "remediationTip": "Count decimal digits to find the power of 10 denominator (2 digits = 100), then reduce."
      },
      {
        "id": "q-frac-9",
        "quizId": "quiz-jhs1-math-fractions",
        "questionText": "Calculate 15% of GH₵ 240.",
        "optionA": "GH₵ 24",
        "optionB": "GH₵ 30",
        "optionC": "GH₵ 36",
        "optionD": "GH₵ 40",
        "correctOption": "C",
        "subConcept": "Percentage of a Quantity",
        "explanation": "(15 / 100) × 240 = 0.15 × 240 = 36.",
        "remediationTip": "Write percentage as a fraction over 100 and multiply by the total amount."
      },
      {
        "id": "q-frac-10",
        "quizId": "quiz-jhs1-math-fractions",
        "questionText": "In a class test, Kwesi scored 28 out of 40 marks. What was his percentage score?",
        "optionA": "65%",
        "optionB": "70%",
        "optionC": "75%",
        "optionD": "80%",
        "correctOption": "B",
        "subConcept": "Expressing Quantities as Percentages",
        "explanation": "Percentage = (Score / Total) × 100% = (28 / 40) × 100% = (7 / 10) × 100% = 70%.",
        "remediationTip": "Formula: (Part / Whole) × 100%."
      }
    ]
  },
  "jhs1-math-t6-algebra": {
    "id": "quiz-jhs1-math-algebra",
    "topicId": "jhs1-math-t6-algebra",
    "title": "Algebraic Expressions Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-alg-1",
        "quizId": "quiz-jhs1-math-algebra",
        "questionText": "Which of the following pairs represents LIKE terms?",
        "optionA": "3a and 3b",
        "optionB": "5xy and -2yx",
        "optionC": "4x² and 4x",
        "optionD": "7m and 7",
        "correctOption": "B",
        "subConcept": "Identifying Like Terms",
        "explanation": "Like terms have identical variable parts raised to identical powers. xy and yx are identical because order in multiplication does not matter.",
        "remediationTip": "Like terms must have identical letter combinations and powers; coefficients do not need to match."
      },
      {
        "id": "q-alg-2",
        "quizId": "quiz-jhs1-math-algebra",
        "questionText": "Simplify: 5x - 3y + 2x + 8y",
        "optionA": "7x + 5y",
        "optionB": "7x - 5y",
        "optionC": "3x + 11y",
        "optionD": "12xy",
        "correctOption": "A",
        "subConcept": "Combining Like Terms",
        "explanation": "Group like terms: (5x + 2x) + (-3y + 8y) = 7x + 5y.",
        "remediationTip": "Group x-terms together and y-terms together; never combine unlike terms."
      },
      {
        "id": "q-alg-3",
        "quizId": "quiz-jhs1-math-algebra",
        "questionText": "Expand the expression: 4(3x - 5)",
        "optionA": "12x - 5",
        "optionB": "12x - 20",
        "optionC": "7x - 20",
        "optionD": "12x + 20",
        "correctOption": "B",
        "subConcept": "Expanding Single Brackets",
        "explanation": "Multiply the outside term 4 by both terms inside: 4 × 3x - 4 × 5 = 12x - 20.",
        "remediationTip": "Distribute the outside number to EVERY term inside the bracket."
      },
      {
        "id": "q-alg-4",
        "quizId": "quiz-jhs1-math-algebra",
        "questionText": "Expand and simplify: -3(2y - 4)",
        "optionA": "-6y - 12",
        "optionB": "-6y + 12",
        "optionC": "6y - 12",
        "optionD": "-5y + 7",
        "correctOption": "B",
        "subConcept": "Expanding Brackets with Negative Signs",
        "explanation": "(-3) × 2y = -6y, and (-3) × (-4) = +12. Result = -6y + 12.",
        "remediationTip": "Careful with signs: negative times negative equals positive (+12)."
      },
      {
        "id": "q-alg-5",
        "quizId": "quiz-jhs1-math-algebra",
        "questionText": "If a = 3 and b = -2, find the value of 2a² - 3b.",
        "optionA": "12",
        "optionB": "18",
        "optionC": "24",
        "optionD": "30",
        "correctOption": "C",
        "subConcept": "Algebraic Substitution",
        "explanation": "2(3)² - 3(-2) = 2(9) - (-6) = 18 + 6 = 24.",
        "remediationTip": "Square the variable first before multiplying by the coefficient, and remember -(-6) = +6."
      },
      {
        "id": "q-alg-6",
        "quizId": "quiz-jhs1-math-algebra",
        "questionText": "Factorize completely: 12x + 18y",
        "optionA": "6(2x + 3y)",
        "optionB": "3(4x + 6y)",
        "optionC": "2(6x + 9y)",
        "optionD": "12(x + 1.5y)",
        "correctOption": "A",
        "subConcept": "Factorization by Highest Common Factor",
        "explanation": "The highest common factor of 12 and 18 is 6. Factoring out 6 gives 6(2x + 3y).",
        "remediationTip": "Always factor out the HIGHEST common factor (HCF) for complete factorization."
      },
      {
        "id": "q-alg-7",
        "quizId": "quiz-jhs1-math-algebra",
        "questionText": "Translate into an algebraic expression: \"5 less than twice a number x\"",
        "optionA": "5 - 2x",
        "optionB": "2x - 5",
        "optionC": "2(x - 5)",
        "optionD": "5 < 2x",
        "correctOption": "B",
        "subConcept": "Word Problem Translation to Algebra",
        "explanation": "\"Twice a number x\" is 2x. \"5 less than\" means subtracting 5 from that amount, giving 2x - 5.",
        "remediationTip": "\"Less than\" reverses order: \"5 less than Y\" means Y - 5, NOT 5 - Y."
      },
      {
        "id": "q-alg-8",
        "quizId": "quiz-jhs1-math-algebra",
        "questionText": "Simplify the algebraic fraction: (8a²b) / (2ab)",
        "optionA": "4a",
        "optionB": "4ab",
        "optionC": "4b",
        "optionD": "6a",
        "correctOption": "A",
        "subConcept": "Simplifying Algebraic Fractions",
        "explanation": "8 ÷ 2 = 4; a² ÷ a = a; b ÷ b = 1. Result is 4a.",
        "remediationTip": "Divide the numbers, then subtract the indices of matching variables."
      },
      {
        "id": "q-alg-9",
        "quizId": "quiz-jhs1-math-algebra",
        "questionText": "Expand the binomial expression: (x + 3)(x + 4)",
        "optionA": "x² + 7x + 12",
        "optionB": "x² + 12x + 7",
        "optionC": "x² + 7x + 7",
        "optionD": "2x + 7",
        "correctOption": "A",
        "subConcept": "Expanding Two Binomial Brackets",
        "explanation": "Using FOIL: x(x) + x(4) + 3(x) + 3(4) = x² + 4x + 3x + 12 = x² + 7x + 12.",
        "remediationTip": "Remember FOIL: First, Outside, Inside, Last, then combine the middle like terms."
      },
      {
        "id": "q-alg-10",
        "quizId": "quiz-jhs1-math-algebra",
        "questionText": "In the expression 9 - 7x + 4x², what is the coefficient of x?",
        "optionA": "7",
        "optionB": "-7",
        "optionC": "4",
        "optionD": "9",
        "correctOption": "B",
        "subConcept": "Identifying Coefficients",
        "explanation": "The coefficient of x includes the sign in front of the term. The term is -7x, so the coefficient is -7.",
        "remediationTip": "Always include the negative sign in front of a term when stating its coefficient."
      }
    ]
  },
  "jhs1-math-t7-equations": {
    "id": "quiz-jhs1-math-equations",
    "topicId": "jhs1-math-t7-equations",
    "title": "Linear Equations in One Variable Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-eqn-1",
        "quizId": "quiz-jhs1-math-equations",
        "questionText": "Solve the equation: x + 9 = 23",
        "optionA": "12",
        "optionB": "14",
        "optionC": "16",
        "optionD": "32",
        "correctOption": "B",
        "subConcept": "One-Step Linear Equations",
        "explanation": "Subtract 9 from both sides: x = 23 - 9 = 14.",
        "remediationTip": "Isolate the variable by performing the inverse operation on both sides."
      },
      {
        "id": "q-eqn-2",
        "quizId": "quiz-jhs1-math-equations",
        "questionText": "Solve: 3x - 5 = 16",
        "optionA": "5",
        "optionB": "7",
        "optionC": "9",
        "optionD": "11",
        "correctOption": "B",
        "subConcept": "Two-Step Linear Equations",
        "explanation": "Add 5 to both sides: 3x = 21. Divide both sides by 3: x = 21 / 3 = 7.",
        "remediationTip": "First eliminate the constant term (+ or -), then divide by the coefficient of x."
      },
      {
        "id": "q-eqn-3",
        "quizId": "quiz-jhs1-math-equations",
        "questionText": "Find x if 5x - 4 = 2x + 11.",
        "optionA": "3",
        "optionB": "4",
        "optionC": "5",
        "optionD": "7",
        "correctOption": "C",
        "subConcept": "Linear Equations with Variables on Both Sides",
        "explanation": "Subtract 2x from both sides: 3x - 4 = 11. Add 4 to both sides: 3x = 15. Divide by 3: x = 5.",
        "remediationTip": "Collect variable terms on one side and numerical constants on the opposite side."
      },
      {
        "id": "q-eqn-4",
        "quizId": "quiz-jhs1-math-equations",
        "questionText": "Solve the equation: 2(3x - 1) = 28",
        "optionA": "3",
        "optionB": "4",
        "optionC": "5",
        "optionD": "6",
        "correctOption": "C",
        "subConcept": "Equations with Brackets",
        "explanation": "Expand brackets: 6x - 2 = 28. Add 2: 6x = 30. Divide by 6: x = 5.",
        "remediationTip": "Expand brackets first, or divide both sides by the outside factor if it divides evenly."
      },
      {
        "id": "q-eqn-5",
        "quizId": "quiz-jhs1-math-equations",
        "questionText": "Solve: x/4 + 3 = 8",
        "optionA": "14",
        "optionB": "18",
        "optionC": "20",
        "optionD": "24",
        "correctOption": "C",
        "subConcept": "Linear Equations with Fractions",
        "explanation": "Subtract 3 from both sides: x/4 = 5. Multiply both sides by 4: x = 5 × 4 = 20.",
        "remediationTip": "Clear addition/subtraction before multiplying to eliminate the fractional denominator."
      },
      {
        "id": "q-eqn-6",
        "quizId": "quiz-jhs1-math-equations",
        "questionText": "Solve: (2x + 3) / 5 = 3",
        "optionA": "4",
        "optionB": "6",
        "optionC": "7",
        "optionD": "9",
        "correctOption": "B",
        "subConcept": "Cross-Multiplication in Linear Equations",
        "explanation": "Multiply both sides by 5: 2x + 3 = 15. Subtract 3: 2x = 12. Divide by 2: x = 6.",
        "remediationTip": "Cross-multiply denominator across the equals sign to turn fraction into a linear line."
      },
      {
        "id": "q-eqn-7",
        "quizId": "quiz-jhs1-math-equations",
        "questionText": "Kofi is 5 years older than Ama. If the sum of their ages is 31, how old is Ama?",
        "optionA": "11 years",
        "optionB": "13 years",
        "optionC": "15 years",
        "optionD": "18 years",
        "correctOption": "B",
        "subConcept": "Word Problems on Ages",
        "explanation": "Let Ama = x, Kofi = x + 5. Equation: x + (x + 5) = 31 -> 2x + 5 = 31 -> 2x = 26 -> x = 13 years.",
        "remediationTip": "Assign variable x to the smaller quantity, express the other in terms of x, then equate to the total."
      },
      {
        "id": "q-eqn-8",
        "quizId": "quiz-jhs1-math-equations",
        "questionText": "The sum of three consecutive integers is 48. What is the smallest integer?",
        "optionA": "14",
        "optionB": "15",
        "optionC": "16",
        "optionD": "17",
        "correctOption": "B",
        "subConcept": "Consecutive Integer Equations",
        "explanation": "Let the numbers be x, x + 1, x + 2. x + x + 1 + x + 2 = 48 -> 3x + 3 = 48 -> 3x = 45 -> x = 15.",
        "remediationTip": "Consecutive integers increase by 1: x, x + 1, x + 2."
      },
      {
        "id": "q-eqn-9",
        "quizId": "quiz-jhs1-math-equations",
        "questionText": "Solve: 17 - 3x = 5",
        "optionA": "2",
        "optionB": "4",
        "optionC": "-4",
        "optionD": "6",
        "correctOption": "B",
        "subConcept": "Equations with Negative Variable Coefficients",
        "explanation": "Subtract 17: -3x = 5 - 17 = -12. Divide by -3: x = -12 / -3 = 4.",
        "remediationTip": "When dividing by a negative coefficient, remember that negative ÷ negative = positive."
      },
      {
        "id": "q-eqn-10",
        "quizId": "quiz-jhs1-math-equations",
        "questionText": "Which value of y makes 4y - 7 = 17 true?",
        "optionA": "4",
        "optionB": "5",
        "optionC": "6",
        "optionD": "7",
        "correctOption": "C",
        "subConcept": "Verifying Solutions of Equations",
        "explanation": "4(6) - 7 = 24 - 7 = 17, which satisfies the equation. Thus y = 6.",
        "remediationTip": "You can always check your test answer by substituting it back into the original equation."
      }
    ]
  },
  "jhs1-math-t8-ratio": {
    "id": "quiz-jhs1-math-ratio",
    "topicId": "jhs1-math-t8-ratio",
    "title": "Ratio, Proportion & Sharing Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-rat-1",
        "quizId": "quiz-jhs1-math-ratio",
        "questionText": "Simplify the ratio 24 : 36 to its simplest form.",
        "optionA": "4 : 6",
        "optionB": "3 : 2",
        "optionC": "2 : 3",
        "optionD": "6 : 9",
        "correctOption": "C",
        "subConcept": "Simplifying Ratios",
        "explanation": "Divide both terms by their HCF of 12: 24 ÷ 12 = 2, 36 ÷ 12 = 3. Ratio is 2 : 3.",
        "remediationTip": "Divide all terms of a ratio by their HCF until no common factor remains."
      },
      {
        "id": "q-rat-2",
        "quizId": "quiz-jhs1-math-ratio",
        "questionText": "Find the missing value x if 3 : 5 = 18 : x.",
        "optionA": "25",
        "optionB": "30",
        "optionC": "35",
        "optionD": "40",
        "correctOption": "B",
        "subConcept": "Equivalent Ratios",
        "explanation": "3 was multiplied by 6 to give 18. Multiplying 5 by 6 gives x = 30.",
        "remediationTip": "Set as fractions: 3/5 = 18/x -> 3x = 90 -> x = 30."
      },
      {
        "id": "q-rat-3",
        "quizId": "quiz-jhs1-math-ratio",
        "questionText": "Express 400 m to 2 km as a ratio in its simplest form.",
        "optionA": "200 : 1",
        "optionB": "1 : 5",
        "optionC": "2 : 1",
        "optionD": "1 : 50",
        "correctOption": "B",
        "subConcept": "Ratios with Unit Conversions",
        "explanation": "Convert both quantities to meters: 2 km = 2,000 m. 400 : 2,000 = 400/400 : 2,000/400 = 1 : 5.",
        "remediationTip": "Always convert both quantities to the same unit before simplifying a ratio."
      },
      {
        "id": "q-rat-4",
        "quizId": "quiz-jhs1-math-ratio",
        "questionText": "Share GH₵ 450 between Kofi and Ama in the ratio 3 : 2. What is Kofi's share?",
        "optionA": "GH₵ 180",
        "optionB": "GH₵ 225",
        "optionC": "GH₵ 270",
        "optionD": "GH₵ 300",
        "correctOption": "C",
        "subConcept": "Sharing Quantities in a Given Ratio",
        "explanation": "Total parts = 3 + 2 = 5. Value of one part = 450 / 5 = GH₵ 90. Kofi gets 3 parts = 3 × 90 = GH₵ 270.",
        "remediationTip": "Divide the total amount by total parts, then multiply by the individual person's ratio shares."
      },
      {
        "id": "q-rat-5",
        "quizId": "quiz-jhs1-math-ratio",
        "questionText": "If 6 exercise books cost GH₵ 48, how much will 10 exercise books cost at the same rate?",
        "optionA": "GH₵ 60",
        "optionB": "GH₵ 72",
        "optionC": "GH₵ 80",
        "optionD": "GH₵ 96",
        "correctOption": "C",
        "subConcept": "Direct Proportion (Unitary Method)",
        "explanation": "Cost of 1 book = 48 ÷ 6 = GH₵ 8. Cost of 10 books = 10 × 8 = GH₵ 80.",
        "remediationTip": "Find the unit cost first (Total ÷ Quantity), then multiply by the new quantity."
      },
      {
        "id": "q-rat-6",
        "quizId": "quiz-jhs1-math-ratio",
        "questionText": "4 workers can weed a school farm in 6 days. How many days will 8 workers take working at the same pace?",
        "optionA": "2 days",
        "optionB": "3 days",
        "optionC": "4 days",
        "optionD": "12 days",
        "correctOption": "B",
        "subConcept": "Inverse Proportion",
        "explanation": "Total work = 4 × 6 = 24 worker-days. For 8 workers: 24 ÷ 8 = 3 days.",
        "remediationTip": "More workers take fewer days! In inverse proportion, product remains constant: W1 × D1 = W2 × D2."
      },
      {
        "id": "q-rat-7",
        "quizId": "quiz-jhs1-math-ratio",
        "questionText": "Esi and Kojo shared some oranges in the ratio 5 : 7. If Kojo received 35 oranges, what was the total number of oranges shared?",
        "optionA": "50",
        "optionB": "60",
        "optionC": "70",
        "optionD": "84",
        "correctOption": "B",
        "subConcept": "Finding Totals from a Single Ratio Part",
        "explanation": "Kojo's 7 parts = 35 oranges -> 1 part = 35 ÷ 7 = 5 oranges. Total parts = 5 + 7 = 12. Total oranges = 12 × 5 = 60.",
        "remediationTip": "Find the value of 1 ratio part by dividing the given quantity by its corresponding ratio share."
      },
      {
        "id": "q-rat-8",
        "quizId": "quiz-jhs1-math-ratio",
        "questionText": "Increase 80 kg in the ratio 5 : 4.",
        "optionA": "90 kg",
        "optionB": "100 kg",
        "optionC": "105 kg",
        "optionD": "120 kg",
        "correctOption": "B",
        "subConcept": "Increasing Quantities in a Ratio",
        "explanation": "To increase in ratio 5 : 4, multiply by (5 / 4): 80 × (5/4) = 20 × 5 = 100 kg.",
        "remediationTip": "To increase: multiply by (larger number / smaller number)."
      },
      {
        "id": "q-rat-9",
        "quizId": "quiz-jhs1-math-ratio",
        "questionText": "Decrease GH₵ 150 in the ratio 3 : 5.",
        "optionA": "GH₵ 60",
        "optionB": "GH₵ 75",
        "optionC": "GH₵ 90",
        "optionD": "GH₵ 100",
        "correctOption": "C",
        "subConcept": "Decreasing Quantities in a Ratio",
        "explanation": "To decrease in ratio 3 : 5, multiply by (3 / 5): 150 × (3/5) = 30 × 3 = GH₵ 90.",
        "remediationTip": "To decrease: multiply by (smaller number / larger number)."
      },
      {
        "id": "q-rat-10",
        "quizId": "quiz-jhs1-math-ratio",
        "questionText": "A map scale is 1 : 50,000. What actual ground distance in kilometers is represented by 6 cm on the map?",
        "optionA": "3 km",
        "optionB": "30 km",
        "optionC": "0.3 km",
        "optionD": "300 km",
        "correctOption": "A",
        "subConcept": "Map Scales and Ratio Distances",
        "explanation": "Ground distance = 6 cm × 50,000 = 300,000 cm. Since 100,000 cm = 1 km, 300,000 ÷ 100,000 = 3 km.",
        "remediationTip": "Multiply map length by scale factor, then divide by 100,000 to convert centimeters to kilometers."
      }
    ]
  },
  "jhs1-math-t9-linesangles": {
    "id": "quiz-jhs1-math-linesangles",
    "topicId": "jhs1-math-t9-linesangles",
    "title": "Lines & Angles Geometric Properties Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-ang-1",
        "quizId": "quiz-jhs1-math-linesangles",
        "questionText": "Angles on a straight line add up to 180°. If one angle is 115°, what is the size of the adjacent supplementary angle?",
        "optionA": "55°",
        "optionB": "65°",
        "optionC": "75°",
        "optionD": "85°",
        "correctOption": "B",
        "subConcept": "Angles on a Straight Line",
        "explanation": "Angles on a straight line sum to 180°: 180° - 115° = 65°.",
        "remediationTip": "Straight line angles always equal 180°."
      },
      {
        "id": "q-ang-2",
        "quizId": "quiz-jhs1-math-linesangles",
        "questionText": "What is the sum of all adjacent angles around a single point (vertex)?",
        "optionA": "90°",
        "optionB": "180°",
        "optionC": "270°",
        "optionD": "360°",
        "correctOption": "D",
        "subConcept": "Angles at a Point",
        "explanation": "A complete full rotation of angles meeting at a point equals 360°.",
        "remediationTip": "Angles at a point add up to 360°."
      },
      {
        "id": "q-ang-3",
        "quizId": "quiz-jhs1-math-linesangles",
        "questionText": "Two straight lines intersect. If one of the angles formed is 72°, what is the size of its vertically opposite angle?",
        "optionA": "18°",
        "optionB": "72°",
        "optionC": "108°",
        "optionD": "288°",
        "correctOption": "B",
        "subConcept": "Vertically Opposite Angles",
        "explanation": "Vertically opposite angles formed by intersecting straight lines are always equal: 72° = 72°.",
        "remediationTip": "Opposite angles across an X-intersection are always equal."
      },
      {
        "id": "q-ang-4",
        "quizId": "quiz-jhs1-math-linesangles",
        "questionText": "Two parallel lines are crossed by a transversal line. Which geometric angle pair forms a \"Z\" shape and are equal?",
        "optionA": "Complementary angles",
        "optionB": "Alternate angles",
        "optionC": "Co-interior angles",
        "optionD": "Adjacent angles",
        "correctOption": "B",
        "subConcept": "Alternate Angles (Z-angles)",
        "explanation": "Alternate angles form a \"Z\" pattern on opposite sides of a transversal between parallel lines and are equal in magnitude.",
        "remediationTip": "Remember: Z-angles are Alternate angles, and they are equal."
      },
      {
        "id": "q-ang-5",
        "quizId": "quiz-jhs1-math-linesangles",
        "questionText": "Which geometric angle pair forms an \"F\" pattern along parallel lines and are equal?",
        "optionA": "Corresponding angles",
        "optionB": "Supplementary angles",
        "optionC": "Allied angles",
        "optionD": "Reflex angles",
        "correctOption": "A",
        "subConcept": "Corresponding Angles (F-angles)",
        "explanation": "Corresponding angles lie in the same relative position at each intersection, forming an \"F\" shape, and are equal.",
        "remediationTip": "Remember: F-angles are Corresponding angles, and they are equal."
      },
      {
        "id": "q-ang-6",
        "quizId": "quiz-jhs1-math-linesangles",
        "questionText": "Co-interior (allied) angles between two parallel lines form a \"C\" or \"U\" shape. What do they add up to?",
        "optionA": "90°",
        "optionB": "180°",
        "optionC": "270°",
        "optionD": "360°",
        "correctOption": "B",
        "subConcept": "Co-interior (Allied) Angles",
        "explanation": "Co-interior angles on the same side of the transversal are supplementary and always sum to 180°.",
        "remediationTip": "Remember: C-angles (co-interior) add up to 180°."
      },
      {
        "id": "q-ang-7",
        "quizId": "quiz-jhs1-math-linesangles",
        "questionText": "If angle A and angle B are complementary, and angle A = 38°, what is angle B?",
        "optionA": "52°",
        "optionB": "62°",
        "optionC": "142°",
        "optionD": "152°",
        "correctOption": "A",
        "subConcept": "Complementary Angles",
        "explanation": "Complementary angles sum to 90°: 90° - 38° = 52°.",
        "remediationTip": "Complementary = 90°; Supplementary = 180°."
      },
      {
        "id": "q-ang-8",
        "quizId": "quiz-jhs1-math-linesangles",
        "questionText": "An angle measuring 145° is classified as which type of angle?",
        "optionA": "Acute angle",
        "optionB": "Right angle",
        "optionC": "Obtuse angle",
        "optionD": "Reflex angle",
        "correctOption": "C",
        "subConcept": "Classification of Angles",
        "explanation": "An obtuse angle is greater than 90° but less than 180°. 145° falls in this range.",
        "remediationTip": "Acute < 90°; Right = 90°; Obtuse is 90° to 180°; Reflex is 180° to 360°."
      },
      {
        "id": "q-ang-9",
        "quizId": "quiz-jhs1-math-linesangles",
        "questionText": "In triangle ABC, angle A = 55° and angle B = 65°. Calculate angle C.",
        "optionA": "50°",
        "optionB": "60°",
        "optionC": "70°",
        "optionD": "80°",
        "correctOption": "B",
        "subConcept": "Sum of Angles in a Triangle",
        "explanation": "The angles of any triangle sum to 180°: 180° - (55° + 65°) = 180° - 120° = 60°.",
        "remediationTip": "The three interior angles of any triangle must add up to 180°."
      },
      {
        "id": "q-ang-10",
        "quizId": "quiz-jhs1-math-linesangles",
        "questionText": "In an isosceles triangle, the angle between the two equal sides is 40°. What is the size of each of the base angles?",
        "optionA": "60°",
        "optionB": "70°",
        "optionC": "80°",
        "optionD": "140°",
        "correctOption": "B",
        "subConcept": "Properties of Isosceles Triangles",
        "explanation": "Base angles are equal: (180° - 40°) ÷ 2 = 140° ÷ 2 = 70° each.",
        "remediationTip": "In an isosceles triangle, the angles opposite the equal sides are equal."
      }
    ]
  },
  "jhs1-math-t10-polygons": {
    "id": "quiz-jhs1-math-polygons",
    "topicId": "jhs1-math-t10-polygons",
    "title": "Plane Shapes & Polygons Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-poly-1",
        "quizId": "quiz-jhs1-math-polygons",
        "questionText": "What two conditions must be satisfied for a polygon to be REGULAR?",
        "optionA": "All sides equal and all interior angles equal",
        "optionB": "Opposite sides parallel and all angles 90°",
        "optionC": "At least 5 sides and all diagonals equal",
        "optionD": "All exterior angles acute",
        "correctOption": "A",
        "subConcept": "Definition of Regular Polygons",
        "explanation": "A regular polygon is both equilateral (all side lengths are equal) and equiangular (all interior angles are equal).",
        "remediationTip": "Regular = all sides equal AND all angles equal."
      },
      {
        "id": "q-poly-2",
        "quizId": "quiz-jhs1-math-polygons",
        "questionText": "What is the sum of interior angles of a pentagon (5-sided polygon)?",
        "optionA": "360°",
        "optionB": "540°",
        "optionC": "720°",
        "optionD": "900°",
        "correctOption": "B",
        "subConcept": "Sum of Interior Angles Formula",
        "explanation": "Formula: (n - 2) × 180°. For n = 5: (5 - 2) × 180° = 3 × 180° = 540°.",
        "remediationTip": "Always calculate total interior angles using: Sum = (n - 2) × 180°."
      },
      {
        "id": "q-poly-3",
        "quizId": "quiz-jhs1-math-polygons",
        "questionText": "Calculate the size of ONE interior angle of a regular hexagon (6-sided polygon).",
        "optionA": "108°",
        "optionB": "120°",
        "optionC": "135°",
        "optionD": "144°",
        "correctOption": "B",
        "subConcept": "Interior Angles of Regular Polygons",
        "explanation": "Sum = (6 - 2) × 180° = 720°. Since it is regular, each angle = 720° ÷ 6 = 120°.",
        "remediationTip": "Divide total interior sum by number of sides n to find one interior angle of a regular polygon."
      },
      {
        "id": "q-poly-4",
        "quizId": "quiz-jhs1-math-polygons",
        "questionText": "What is the sum of the exterior angles of ANY convex polygon?",
        "optionA": "180°",
        "optionB": "270°",
        "optionC": "360°",
        "optionD": "540°",
        "correctOption": "C",
        "subConcept": "Sum of Exterior Angles",
        "explanation": "The exterior angles of any convex polygon always sum to 360°, no matter how many sides it has.",
        "remediationTip": "Sum of exterior angles is always 360° for every convex polygon."
      },
      {
        "id": "q-poly-5",
        "quizId": "quiz-jhs1-math-polygons",
        "questionText": "If each exterior angle of a regular polygon is 45°, how many sides does the polygon have?",
        "optionA": "6 sides",
        "optionB": "8 sides",
        "optionC": "10 sides",
        "optionD": "12 sides",
        "correctOption": "B",
        "subConcept": "Finding Number of Sides from Exterior Angle",
        "explanation": "Number of sides n = 360° ÷ exterior angle = 360° ÷ 45° = 8 sides (an octagon).",
        "remediationTip": "Formula: n = 360° ÷ (exterior angle)."
      },
      {
        "id": "q-poly-6",
        "quizId": "quiz-jhs1-math-polygons",
        "questionText": "How many lines of symmetry does an equilateral triangle have?",
        "optionA": "1",
        "optionB": "2",
        "optionC": "3",
        "optionD": "6",
        "correctOption": "C",
        "subConcept": "Lines of Symmetry in Regular Polygons",
        "explanation": "A regular polygon with n sides has exactly n lines of symmetry. An equilateral triangle has 3 sides, so it has 3 lines of symmetry.",
        "remediationTip": "Any regular polygon has as many lines of symmetry as it has sides."
      },
      {
        "id": "q-poly-7",
        "quizId": "quiz-jhs1-math-polygons",
        "questionText": "Which of the following properties is TRUE for a rhombus?",
        "optionA": "All angles are 90°",
        "optionB": "Diagonals bisect each other at right angles (90°)",
        "optionC": "Diagonals are always equal in length",
        "optionD": "Only two sides are equal",
        "correctOption": "B",
        "subConcept": "Properties of Special Quadrilaterals (Rhombus)",
        "explanation": "In a rhombus, all 4 sides are equal and the diagonals bisect each other perpendicularly at 90°.",
        "remediationTip": "Rhombus diagonals cross at 90° and cut each other in half."
      },
      {
        "id": "q-poly-8",
        "quizId": "quiz-jhs1-math-polygons",
        "questionText": "The relationship between an interior angle and its adjacent exterior angle in any polygon is that they:",
        "optionA": "Add up to 90°",
        "optionB": "Add up to 180°",
        "optionC": "Are always equal",
        "optionD": "Add up to 360°",
        "correctOption": "B",
        "subConcept": "Interior and Exterior Angle Linear Pair",
        "explanation": "An interior angle and its adjacent exterior angle lie along a straight line, so Interior + Exterior = 180°.",
        "remediationTip": "Interior Angle + Exterior Angle = 180°."
      },
      {
        "id": "q-poly-9",
        "quizId": "quiz-jhs1-math-polygons",
        "questionText": "Three angles of a quadrilateral are 85°, 115°, and 60°. What is the fourth angle?",
        "optionA": "90°",
        "optionB": "100°",
        "optionC": "110°",
        "optionD": "120°",
        "correctOption": "B",
        "subConcept": "Quadrilateral Angle Sum",
        "explanation": "The interior angles of any quadrilateral sum to 360°: 360° - (85° + 115° + 60°) = 360° - 260° = 100°.",
        "remediationTip": "The sum of all four interior angles in any quadrilateral is 360°."
      },
      {
        "id": "q-poly-10",
        "quizId": "quiz-jhs1-math-polygons",
        "questionText": "A polygon with 7 sides is called a:",
        "optionA": "Hexagon",
        "optionB": "Heptagon",
        "optionC": "Nonagon",
        "optionD": "Decagon",
        "correctOption": "B",
        "subConcept": "Polygon Names by Sides",
        "explanation": "A 7-sided polygon is a Heptagon (or Septagon). 6 sides is a Hexagon, 8 is an Octagon, 9 is a Nonagon, 10 is a Decagon.",
        "remediationTip": "Memorize: 5=Pentagon, 6=Hexagon, 7=Heptagon, 8=Octagon, 9=Nonagon, 10=Decagon."
      }
    ]
  },
  "jhs1-math-t11-construction": {
    "id": "quiz-jhs1-math-construction",
    "topicId": "jhs1-math-t11-construction",
    "title": "Geometric Construction Mastery Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-con-1",
        "quizId": "quiz-jhs1-math-construction",
        "questionText": "To construct the perpendicular bisector of a line segment AB of length 8 cm, the compass radius must be set to:",
        "optionA": "Exactly 4 cm",
        "optionB": "More than half of AB (greater than 4 cm)",
        "optionC": "Less than half of AB (less than 4 cm)",
        "optionD": "Any radius smaller than 2 cm",
        "correctOption": "B",
        "subConcept": "Perpendicular Bisector Radius Rule",
        "explanation": "To ensure the arcs intersect above and below the line, the compass radius must be opened to more than half the length of the line segment.",
        "remediationTip": "Always open compass radius to more than half the line length when bisecting."
      },
      {
        "id": "q-con-2",
        "quizId": "quiz-jhs1-math-construction",
        "questionText": "What is the purpose of constructing an angle bisector?",
        "optionA": "To double the size of an angle",
        "optionB": "To divide an angle into two equal parts",
        "optionC": "To draw a 90° angle",
        "optionD": "To measure angle degrees with a protractor",
        "correctOption": "B",
        "subConcept": "Angle Bisector Definition",
        "explanation": "Bisecting an angle divides it into two congruent (equal) angles.",
        "remediationTip": "Bisect means \"cut into two equal halves\"."
      },
      {
        "id": "q-con-3",
        "quizId": "quiz-jhs1-math-construction",
        "questionText": "Which basic angle is created naturally by drawing an arc and cutting it with the UNCHANGED compass radius?",
        "optionA": "30°",
        "optionB": "45°",
        "optionC": "60°",
        "optionD": "90°",
        "correctOption": "C",
        "subConcept": "Constructing 60° Angles",
        "explanation": "Keeping the compass radius unchanged creates an equilateral triangle geometry, producing an angle of 60° at the center.",
        "remediationTip": "First arc cut with unchanged radius from the baseline always yields 60°."
      },
      {
        "id": "q-con-4",
        "quizId": "quiz-jhs1-math-construction",
        "questionText": "How is an angle of 90° constructed geometrically from a point on a straight line?",
        "optionA": "By bisecting a 60° angle",
        "optionB": "By bisecting the straight line angle (180°)",
        "optionC": "By drawing three 30° arcs",
        "optionD": "By setting the compass to 9 cm",
        "correctOption": "B",
        "subConcept": "Constructing 90° Perpendiculars",
        "explanation": "A straight line is 180°. Erecting a perpendicular bisector of the straight angle cuts it into two 90° right angles.",
        "remediationTip": "A perpendicular line creates two 90° angles by bisecting 180°."
      },
      {
        "id": "q-con-5",
        "quizId": "quiz-jhs1-math-construction",
        "questionText": "To construct an angle of 45°, which angle should be constructed first and then bisected?",
        "optionA": "30°",
        "optionB": "60°",
        "optionC": "90°",
        "optionD": "120°",
        "correctOption": "C",
        "subConcept": "Constructing 45° by Bisecting 90°",
        "explanation": "Half of 90° is 45°. Therefore, construct a 90° perpendicular first and bisect it.",
        "remediationTip": "45° = 90° ÷ 2. Construct 90° first, then bisect."
      },
      {
        "id": "q-con-6",
        "quizId": "quiz-jhs1-math-construction",
        "questionText": "To construct an angle of 30°, which angle should be constructed first and bisected?",
        "optionA": "45°",
        "optionB": "60°",
        "optionC": "75°",
        "optionD": "90°",
        "correctOption": "B",
        "subConcept": "Constructing 30° by Bisecting 60°",
        "explanation": "Half of 60° is 30°. Construct a 60° arc and bisect it.",
        "remediationTip": "30° = 60° ÷ 2. Construct 60° first, then bisect."
      },
      {
        "id": "q-con-7",
        "quizId": "quiz-jhs1-math-construction",
        "questionText": "How do you construct an angle of 75° using compass and ruler only?",
        "optionA": "Bisect 150° directly",
        "optionB": "Bisect the 30° interval between 60° and 90°",
        "optionC": "Add 45° to 45°",
        "optionD": "Triple a 25° angle",
        "correctOption": "B",
        "subConcept": "Constructing 75° Composite Angles",
        "explanation": "The difference between 60° and 90° is 30°. Bisecting this 30° interval adds 15° to 60°, giving 60° + 15° = 75°.",
        "remediationTip": "75° lies halfway between 60° and 90°: 60° + 15° = 75°."
      },
      {
        "id": "q-con-8",
        "quizId": "quiz-jhs1-math-construction",
        "questionText": "Under WAEC / BECE examination rules, which instrument is STRICTLY NOT allowed for constructing angles like 60°, 90°, and 45°?",
        "optionA": "Pair of compasses",
        "optionB": "Ruler (straight edge)",
        "optionC": "Protractor",
        "optionD": "Sharp pencil",
        "correctOption": "C",
        "subConcept": "BECE Examination Construction Tools & Rules",
        "explanation": "In BECE, using a protractor to draw required angles results in zero marks for the construction. Protractors may only be used to verify measurements.",
        "remediationTip": "Always construct angles using compass and ruler only; never draw angles with a protractor."
      },
      {
        "id": "q-con-9",
        "quizId": "quiz-jhs1-math-construction",
        "questionText": "What is the locus of points that are equidistant from two fixed points P and Q?",
        "optionA": "A circle with diameter PQ",
        "optionB": "The perpendicular bisector of the line segment PQ",
        "optionC": "An angle bisector of line PQ",
        "optionD": "A parallel line to PQ",
        "correctOption": "B",
        "subConcept": "Locus Equidistant from Two Points",
        "explanation": "The set of all points that are the same distance from two points P and Q is the perpendicular bisector of PQ.",
        "remediationTip": "Equidistant from two points = Perpendicular bisector of the line segment between them."
      },
      {
        "id": "q-con-10",
        "quizId": "quiz-jhs1-math-construction",
        "questionText": "The center of a circumscribed circle (circle passing through all three vertices of a triangle) is found by:",
        "optionA": "Intersecting the angle bisectors",
        "optionB": "Intersecting the perpendicular bisectors of the sides",
        "optionC": "Finding the midpoint of the longest side only",
        "optionD": "Intersecting the medians",
        "correctOption": "B",
        "subConcept": "Circumscribed Circle Construction",
        "explanation": "The circumcenter of a triangle is the point where the perpendicular bisectors of the sides intersect.",
        "remediationTip": "Perpendicular bisectors of sides give the circumcenter (outside circle); angle bisectors give the incenter (inside circle)."
      }
    ]
  },
  "jhs1-math-t12-perimeterarea": {
    "id": "quiz-jhs1-math-perimeterarea",
    "topicId": "jhs1-math-t12-perimeterarea",
    "title": "Perimeter & Area of Plane Figures Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-pea-1",
        "quizId": "quiz-jhs1-math-perimeterarea",
        "questionText": "A rectangular field has length 18 m and width 12 m. What is its perimeter?",
        "optionA": "30 m",
        "optionB": "60 m",
        "optionC": "216 m",
        "optionD": "120 m",
        "correctOption": "B",
        "subConcept": "Perimeter of Rectangles",
        "explanation": "Perimeter P = 2(length + width) = 2(18 + 12) = 2(30) = 60 m.",
        "remediationTip": "Formula: P = 2(l + w). Add length and width, then multiply by 2."
      },
      {
        "id": "q-pea-2",
        "quizId": "quiz-jhs1-math-perimeterarea",
        "questionText": "Calculate the area of a rectangular classroom whose length is 15 m and width is 8 m.",
        "optionA": "46 m²",
        "optionB": "60 m²",
        "optionC": "120 m²",
        "optionD": "240 m²",
        "correctOption": "C",
        "subConcept": "Area of Rectangles",
        "explanation": "Area A = length × width = 15 m × 8 m = 120 m².",
        "remediationTip": "Area = length × width. Always state units in square units (m²)."
      },
      {
        "id": "q-pea-3",
        "quizId": "quiz-jhs1-math-perimeterarea",
        "questionText": "The perimeter of a square table is 52 cm. Find the length of one side.",
        "optionA": "11 cm",
        "optionB": "13 cm",
        "optionC": "26 cm",
        "optionD": "169 cm",
        "correctOption": "B",
        "subConcept": "Side of Square from Perimeter",
        "explanation": "A square has 4 equal sides. Side s = Perimeter ÷ 4 = 52 ÷ 4 = 13 cm.",
        "remediationTip": "For a square, side = Perimeter ÷ 4."
      },
      {
        "id": "q-pea-4",
        "quizId": "quiz-jhs1-math-perimeterarea",
        "questionText": "A square garden has sides of length 14 m. Calculate its area.",
        "optionA": "28 m²",
        "optionB": "56 m²",
        "optionC": "196 m²",
        "optionD": "210 m²",
        "correctOption": "C",
        "subConcept": "Area of Squares",
        "explanation": "Area of square = side × side = 14 × 14 = 196 m².",
        "remediationTip": "Area of a square = side²."
      },
      {
        "id": "q-pea-5",
        "quizId": "quiz-jhs1-math-perimeterarea",
        "questionText": "Find the area of a triangle with base 12 cm and perpendicular height 7 cm.",
        "optionA": "19 cm²",
        "optionB": "42 cm²",
        "optionC": "84 cm²",
        "optionD": "54 cm²",
        "correctOption": "B",
        "subConcept": "Area of Triangles",
        "explanation": "Area = 1/2 × base × height = 1/2 × 12 × 7 = 6 × 7 = 42 cm².",
        "remediationTip": "Always multiply by 1/2: Area = (base × height) / 2."
      },
      {
        "id": "q-pea-6",
        "quizId": "quiz-jhs1-math-perimeterarea",
        "questionText": "Calculate the circumference of a circular plate of diameter 14 cm. (Take π = 22/7)",
        "optionA": "22 cm",
        "optionB": "44 cm",
        "optionC": "88 cm",
        "optionD": "154 cm",
        "correctOption": "B",
        "subConcept": "Circumference of Circles",
        "explanation": "Circumference C = πd = (22/7) × 14 = 22 × 2 = 44 cm.",
        "remediationTip": "Circumference = πd or 2πr."
      },
      {
        "id": "q-pea-7",
        "quizId": "quiz-jhs1-math-perimeterarea",
        "questionText": "Find the area of a circle with radius 7 cm. (Take π = 22/7)",
        "optionA": "22 cm²",
        "optionB": "44 cm²",
        "optionC": "154 cm²",
        "optionD": "308 cm²",
        "correctOption": "C",
        "subConcept": "Area of Circles",
        "explanation": "Area = πr² = (22/7) × 7 × 7 = 22 × 7 = 154 cm².",
        "remediationTip": "Area = π × r × r. If given diameter, divide by 2 first to get radius!"
      },
      {
        "id": "q-pea-8",
        "quizId": "quiz-jhs1-math-perimeterarea",
        "questionText": "What is the total perimeter of a semi-circle with radius 7 cm? (Take π = 22/7)",
        "optionA": "22 cm",
        "optionB": "29 cm",
        "optionC": "36 cm",
        "optionD": "44 cm",
        "correctOption": "C",
        "subConcept": "Perimeter of Semi-Circles",
        "explanation": "Perimeter of semi-circle = curved arc (πr) + straight diameter (2r). Curved arc = (22/7) × 7 = 22 cm. Diameter = 2 × 7 = 14 cm. Total = 22 + 14 = 36 cm.",
        "remediationTip": "Do not forget the straight diameter edge! Perimeter = πr + 2r."
      },
      {
        "id": "q-pea-9",
        "quizId": "quiz-jhs1-math-perimeterarea",
        "questionText": "Find the area of a parallelogram with base 16 cm and perpendicular height 9 cm.",
        "optionA": "50 cm²",
        "optionB": "72 cm²",
        "optionC": "144 cm²",
        "optionD": "288 cm²",
        "correctOption": "C",
        "subConcept": "Area of Parallelograms",
        "explanation": "Area = base × perpendicular height = 16 × 9 = 144 cm².",
        "remediationTip": "Area of parallelogram = base × perpendicular height (no 1/2 factor)."
      },
      {
        "id": "q-pea-10",
        "quizId": "quiz-jhs1-math-perimeterarea",
        "questionText": "A trapezium has parallel sides of lengths 8 cm and 12 cm, and perpendicular height 6 cm. Calculate its area.",
        "optionA": "60 cm²",
        "optionB": "120 cm²",
        "optionC": "48 cm²",
        "optionD": "72 cm²",
        "correctOption": "A",
        "subConcept": "Area of Trapeziums",
        "explanation": "Area = 1/2 × (a + b) × h = 1/2 × (8 + 12) × 6 = 1/2 × 20 × 6 = 60 cm².",
        "remediationTip": "Trapezium Area = 1/2 × (sum of parallel sides) × height."
      }
    ]
  },
  "jhs1-math-t13-datacollection": {
    "id": "quiz-jhs1-math-datacollection",
    "topicId": "jhs1-math-t13-datacollection",
    "title": "Data Collection & Frequency Tables Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-dat-1",
        "quizId": "quiz-jhs1-math-datacollection",
        "questionText": "How is the number 5 correctly represented using tally marks?",
        "optionA": "Five vertical strokes |||||",
        "optionB": "Four vertical strokes crossed diagonally by a fifth stroke",
        "optionC": "Three vertical and two horizontal strokes",
        "optionD": "A square with a dot",
        "correctOption": "B",
        "subConcept": "Tally Marks Representation",
        "explanation": "In tally charts, groups of 5 are written as four vertical bars crossed diagonally by the fifth stroke.",
        "remediationTip": "Tallies bundle in fives: 4 vertical strokes + 1 diagonal cross."
      },
      {
        "id": "q-dat-2",
        "quizId": "quiz-jhs1-math-datacollection",
        "questionText": "In statistics, what does the term \"frequency\" represent?",
        "optionA": "The highest score recorded",
        "optionB": "The number of times a particular data value appears",
        "optionC": "The difference between highest and lowest values",
        "optionD": "The average score of the group",
        "correctOption": "B",
        "subConcept": "Definition of Frequency",
        "explanation": "Frequency refers to the count of occurrences of a specific item or score within a dataset.",
        "remediationTip": "Frequency means \"how often\" or \"how many times\" an event/number happens."
      },
      {
        "id": "q-dat-3",
        "quizId": "quiz-jhs1-math-datacollection",
        "questionText": "Data collected directly by a student through counting or conducting their own survey is called:",
        "optionA": "Secondary data",
        "optionB": "Primary data",
        "optionC": "Historical data",
        "optionD": "Sampled census data",
        "correctOption": "B",
        "subConcept": "Primary vs Secondary Data",
        "explanation": "Primary data is collected first-hand by the researcher directly for their own investigation.",
        "remediationTip": "Primary data = gathered first-hand by you; Secondary data = obtained from books/records."
      },
      {
        "id": "q-dat-4",
        "quizId": "quiz-jhs1-math-datacollection",
        "questionText": "The ages of 5 students are: 12, 16, 11, 19, 14. What is the RANGE of their ages?",
        "optionA": "7 years",
        "optionB": "8 years",
        "optionC": "11 years",
        "optionD": "19 years",
        "correctOption": "B",
        "subConcept": "Calculating the Range",
        "explanation": "Range = Highest value - Lowest value = 19 - 11 = 8 years.",
        "remediationTip": "Range = Maximum score - Minimum score."
      },
      {
        "id": "q-dat-5",
        "quizId": "quiz-jhs1-math-datacollection",
        "questionText": "Which of the following is an essential feature of a standard bar chart?",
        "optionA": "Bars must touch each other with zero gaps",
        "optionB": "Bars must have equal widths with uniform spaces between categories",
        "optionC": "Categories must always be circular",
        "optionD": "Bars must always be horizontal",
        "correctOption": "B",
        "subConcept": "Bar Chart Rules & Structure",
        "explanation": "In a standard bar chart for discrete categories, bars have uniform widths separated by equal spaces.",
        "remediationTip": "Bar charts have spaces between bars; histograms (continuous data) touch."
      },
      {
        "id": "q-dat-6",
        "quizId": "quiz-jhs1-math-datacollection",
        "questionText": "In a school survey of 120 students, 30 students ride bicycles to school. What sector angle represents this on a pie chart?",
        "optionA": "30°",
        "optionB": "60°",
        "optionC": "90°",
        "optionD": "120°",
        "correctOption": "C",
        "subConcept": "Pie Chart Sector Angles",
        "explanation": "Sector angle = (Frequency ÷ Total) × 360° = (30 ÷ 120) × 360° = 1/4 × 360° = 90°.",
        "remediationTip": "Sector angle = (Category frequency / Total frequency) × 360°."
      },
      {
        "id": "q-dat-7",
        "quizId": "quiz-jhs1-math-datacollection",
        "questionText": "On a pie chart representing 720 poultry birds, the sector angle for layers is 120°. How many layers are on the farm?",
        "optionA": "120 birds",
        "optionB": "200 birds",
        "optionC": "240 birds",
        "optionD": "360 birds",
        "correctOption": "C",
        "subConcept": "Calculating Quantities from Pie Charts",
        "explanation": "Quantity = (Sector angle ÷ 360°) × Total = (120° ÷ 360°) × 720 = 1/3 × 720 = 240 birds.",
        "remediationTip": "Quantity = (Angle / 360°) × Total Population."
      },
      {
        "id": "q-dat-8",
        "quizId": "quiz-jhs1-math-datacollection",
        "questionText": "In a frequency table, the sum of all frequencies (∑f) always represents:",
        "optionA": "The range of values",
        "optionB": "The total sample size (total number of observations)",
        "optionC": "The mode",
        "optionD": "The average score",
        "correctOption": "B",
        "subConcept": "Sum of Frequencies (∑f)",
        "explanation": "Adding all frequencies gives the total number of individuals or items observed.",
        "remediationTip": "Sum of frequencies ∑f = Total count of observations (N)."
      },
      {
        "id": "q-dat-9",
        "quizId": "quiz-jhs1-math-datacollection",
        "questionText": "In the class interval 20 - 29, what is the lower class limit?",
        "optionA": "20",
        "optionB": "24.5",
        "optionC": "29",
        "optionD": "9",
        "correctOption": "A",
        "subConcept": "Class Limits in Grouped Data",
        "explanation": "The lower class limit is the smallest data value that can belong to the class, which is 20.",
        "remediationTip": "In interval A - B, A is the lower limit and B is the upper limit."
      },
      {
        "id": "q-dat-10",
        "quizId": "quiz-jhs1-math-datacollection",
        "questionText": "Why is data grouped into class intervals like 10-19, 20-29, etc.?",
        "optionA": "To make the numbers bigger",
        "optionB": "To condense large sets of wide-ranging data into manageable tables",
        "optionC": "To eliminate all errors",
        "optionD": "To change percentages to decimals",
        "correctOption": "B",
        "subConcept": "Grouped Data Organization",
        "explanation": "Grouped frequency distribution simplifies large, widely dispersed datasets into structured categories.",
        "remediationTip": "Grouping organizes large ranges of continuous data into clear summaries."
      }
    ]
  },
  "jhs1-math-t14-centraltendency": {
    "id": "quiz-jhs1-math-centraltendency",
    "topicId": "jhs1-math-t14-centraltendency",
    "title": "Measures of Central Tendency Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-ct-1",
        "quizId": "quiz-jhs1-math-centraltendency",
        "questionText": "Find the mean of the scores: 6, 8, 9, 11, 16.",
        "optionA": "8",
        "optionB": "9",
        "optionC": "10",
        "optionD": "12",
        "correctOption": "C",
        "subConcept": "Mean of Ungrouped Data",
        "explanation": "Sum = 6 + 8 + 9 + 11 + 16 = 50. Total count n = 5. Mean = 50 ÷ 5 = 10.",
        "remediationTip": "Mean = (Sum of all values) ÷ (Total count of items)."
      },
      {
        "id": "q-ct-2",
        "quizId": "quiz-jhs1-math-centraltendency",
        "questionText": "Determine the MODE of this set of numbers: 4, 7, 5, 8, 7, 6, 7, 5.",
        "optionA": "5",
        "optionB": "6",
        "optionC": "7",
        "optionD": "8",
        "correctOption": "C",
        "subConcept": "Identifying the Mode",
        "explanation": "7 appears three times, which is more frequent than any other number.",
        "remediationTip": "Mode is the number with the highest frequency in the dataset."
      },
      {
        "id": "q-ct-3",
        "quizId": "quiz-jhs1-math-centraltendency",
        "questionText": "Find the MEDIAN of: 15, 7, 12, 4, 9.",
        "optionA": "7",
        "optionB": "9",
        "optionC": "12",
        "optionD": "15",
        "correctOption": "B",
        "subConcept": "Median with Odd Number of Items",
        "explanation": "First arrange in ascending order: 4, 7, 9, 12, 15. The middle number is 9.",
        "remediationTip": "Always sort numbers in ascending order before picking the middle value!"
      },
      {
        "id": "q-ct-4",
        "quizId": "quiz-jhs1-math-centraltendency",
        "questionText": "Find the MEDIAN of the six numbers: 3, 11, 6, 8, 14, 5.",
        "optionA": "6",
        "optionB": "7",
        "optionC": "8",
        "optionD": "8.5",
        "correctOption": "B",
        "subConcept": "Median with Even Number of Items",
        "explanation": "Arrange ascending: 3, 5, 6, 8, 11, 14. The two middle values are 6 and 8. Median = (6 + 8) ÷ 2 = 7.",
        "remediationTip": "For an even count, sort ascending, add the two middle numbers, and divide by 2."
      },
      {
        "id": "q-ct-5",
        "quizId": "quiz-jhs1-math-centraltendency",
        "questionText": "What is the mean calculated from a frequency table where values are x and frequencies are f?",
        "optionA": "∑x ÷ ∑f",
        "optionB": "∑(fx) ÷ ∑f",
        "optionC": "∑(fx) ÷ n²",
        "optionD": "∑f ÷ ∑(fx)",
        "correctOption": "B",
        "subConcept": "Mean from Frequency Tables",
        "explanation": "In a frequency table, the mean is the sum of products ∑(fx) divided by total frequency ∑f.",
        "remediationTip": "Multiply each value by its frequency, sum them (∑fx), and divide by total frequency (∑f)."
      },
      {
        "id": "q-ct-6",
        "quizId": "quiz-jhs1-math-centraltendency",
        "questionText": "Which measure of central tendency is MOST affected by an extreme outlier (such as a score of 100 in a list of 5s)?",
        "optionA": "Mode",
        "optionB": "Median",
        "optionC": "Mean",
        "optionD": "All are equally affected",
        "correctOption": "C",
        "subConcept": "Outlier Effects on Averages",
        "explanation": "The Mean takes every value into account, so extreme high or low numbers distort it significantly.",
        "remediationTip": "Mean is heavily affected by outliers; Median is resistant to outliers."
      },
      {
        "id": "q-ct-7",
        "quizId": "quiz-jhs1-math-centraltendency",
        "questionText": "The mean of four numbers 5, 9, x, and 14 is 10. Find the value of x.",
        "optionA": "8",
        "optionB": "10",
        "optionC": "12",
        "optionD": "14",
        "correctOption": "C",
        "subConcept": "Finding Missing Values from the Mean",
        "explanation": "Total sum = 4 × 10 = 40. 5 + 9 + x + 14 = 40 -> 28 + x = 40 -> x = 12.",
        "remediationTip": "Total sum = Mean × count. Subtract known values from the total to find x."
      },
      {
        "id": "q-ct-8",
        "quizId": "quiz-jhs1-math-centraltendency",
        "questionText": "What is the mode of: 2, 4, 4, 5, 7, 7, 9?",
        "optionA": "5 only",
        "optionB": "4 only",
        "optionC": "4 and 7 (bimodal)",
        "optionD": "No mode",
        "correctOption": "C",
        "subConcept": "Bimodal Datasets",
        "explanation": "Both 4 and 7 appear twice, which is the highest frequency. The distribution is bimodal with modes 4 and 7.",
        "remediationTip": "If two different values tie for the highest frequency, the dataset has two modes (bimodal)."
      },
      {
        "id": "q-ct-9",
        "quizId": "quiz-jhs1-math-centraltendency",
        "questionText": "In a grouped frequency table, what is the MODAL CLASS?",
        "optionA": "The class interval in the exact middle of the table",
        "optionB": "The class interval with the highest frequency",
        "optionC": "The class interval with the lowest frequency",
        "optionD": "The class interval with the largest limits",
        "correctOption": "B",
        "subConcept": "Modal Class Identification",
        "explanation": "The modal class is the interval that contains the greatest frequency.",
        "remediationTip": "Look down the frequency column: the biggest frequency marks the modal class."
      },
      {
        "id": "q-ct-10",
        "quizId": "quiz-jhs1-math-centraltendency",
        "questionText": "Ama scored 65, 70, and 85 in three tests. What must she score in the 4th test to achieve an overall mean of 75?",
        "optionA": "75",
        "optionB": "80",
        "optionC": "85",
        "optionD": "90",
        "correctOption": "B",
        "subConcept": "Target Average Word Problems",
        "explanation": "Total needed for 4 tests = 4 × 75 = 300. Current total = 65 + 70 + 85 = 220. 4th test score = 300 - 220 = 80.",
        "remediationTip": "Required total = New Mean × New Total Count. Subtract current sum to find the required score."
      }
    ]
  },
  "jhs1-math-t15-probability": {
    "id": "quiz-jhs1-math-probability",
    "topicId": "jhs1-math-t15-probability",
    "title": "Basic Probability & Chance Events Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-prb-1",
        "quizId": "quiz-jhs1-math-probability",
        "questionText": "Which of the following values CANNOT represent a probability?",
        "optionA": "0",
        "optionB": "0.75",
        "optionC": "1.25",
        "optionD": "2/5",
        "correctOption": "C",
        "subConcept": "Probability Range Rules (0 to 1)",
        "explanation": "Probability is always between 0 (impossible) and 1 (certain). A probability of 1.25 is greater than 1 and impossible.",
        "remediationTip": "Probability values must always be between 0 and 1 inclusive (0% to 100%)."
      },
      {
        "id": "q-prb-2",
        "quizId": "quiz-jhs1-math-probability",
        "questionText": "What is the formula for the theoretical probability of an event E occurring?",
        "optionA": "P(E) = Total outcomes ÷ Favorable outcomes",
        "optionB": "P(E) = Number of favorable outcomes ÷ Total number of possible outcomes",
        "optionC": "P(E) = Favorable outcomes × 100",
        "optionD": "P(E) = Total outcomes - Favorable outcomes",
        "correctOption": "B",
        "subConcept": "Basic Probability Formula",
        "explanation": "P(E) = n(E) / n(S), where n(E) is favorable outcomes and n(S) is total sample space.",
        "remediationTip": "Probability = (Number of wanted outcomes) ÷ (Total possible outcomes)."
      },
      {
        "id": "q-prb-3",
        "quizId": "quiz-jhs1-math-probability",
        "questionText": "A fair 6-sided die is rolled once. What is the probability of rolling an EVEN number?",
        "optionA": "1/6",
        "optionB": "1/3",
        "optionC": "1/2",
        "optionD": "2/3",
        "correctOption": "C",
        "subConcept": "Single Die Probability (Even Numbers)",
        "explanation": "Even numbers are {2, 4, 6} (3 outcomes). Total outcomes = 6. Probability = 3/6 = 1/2.",
        "remediationTip": "Sample space on a die is {1, 2, 3, 4, 5, 6}. Three are even, three are odd (each 1/2)."
      },
      {
        "id": "q-prb-4",
        "quizId": "quiz-jhs1-math-probability",
        "questionText": "A fair 6-sided die is rolled once. What is the probability of obtaining a PRIME number?",
        "optionA": "1/6",
        "optionB": "1/3",
        "optionC": "1/2",
        "optionD": "2/3",
        "correctOption": "C",
        "subConcept": "Prime Numbers on a Die",
        "explanation": "The prime numbers on a die are 2, 3, and 5 (3 numbers). Remember 1 is NOT prime. Probability = 3/6 = 1/2.",
        "remediationTip": "1 is NOT prime! Primes on a 6-sided die are 2, 3, and 5 (3 out of 6 = 1/2)."
      },
      {
        "id": "q-prb-5",
        "quizId": "quiz-jhs1-math-probability",
        "questionText": "When two fair coins are tossed simultaneously, what is the probability of getting TWO HEADS (HH)?",
        "optionA": "1/2",
        "optionB": "1/4",
        "optionC": "3/4",
        "optionD": "1/8",
        "correctOption": "B",
        "subConcept": "Two Coins Sample Space",
        "explanation": "Sample space has 4 outcomes: {HH, HT, TH, TT}. Only HH has two heads: 1/4.",
        "remediationTip": "Listing all combinations helps: {HH, HT, TH, TT}. HH is 1 out of 4 = 1/4."
      },
      {
        "id": "q-prb-6",
        "quizId": "quiz-jhs1-math-probability",
        "questionText": "A bag contains 5 red balls, 3 blue balls, and 2 green balls. A ball is drawn at random. What is the probability that it is BLUE?",
        "optionA": "3/10",
        "optionB": "1/5",
        "optionC": "1/2",
        "optionD": "3/7",
        "correctOption": "A",
        "subConcept": "Selection from a Container",
        "explanation": "Total balls = 5 + 3 + 2 = 10. Blue balls = 3. P(Blue) = 3/10.",
        "remediationTip": "Sum all items first to find the denominator, then put the specific color count on top."
      },
      {
        "id": "q-prb-7",
        "quizId": "quiz-jhs1-math-probability",
        "questionText": "If the probability that it will rain tomorrow is 0.35, what is the probability that it will NOT rain tomorrow?",
        "optionA": "0.35",
        "optionB": "0.55",
        "optionC": "0.65",
        "optionD": "0.75",
        "correctOption": "C",
        "subConcept": "Complementary Events",
        "explanation": "P(not rain) = 1 - P(rain) = 1 - 0.35 = 0.65.",
        "remediationTip": "Formula: P(not Event) = 1 - P(Event)."
      },
      {
        "id": "q-prb-8",
        "quizId": "quiz-jhs1-math-probability",
        "questionText": "An event that cannot possibly happen under any circumstance has a probability of:",
        "optionA": "-1",
        "optionB": "0",
        "optionC": "0.5",
        "optionD": "1",
        "correctOption": "B",
        "subConcept": "Impossible vs Certain Events",
        "explanation": "An impossible event has a probability of exactly 0. A certain event has a probability of 1.",
        "remediationTip": "Impossible event = 0; Certain event = 1."
      },
      {
        "id": "q-prb-9",
        "quizId": "quiz-jhs1-math-probability",
        "questionText": "A card is drawn from a box containing cards numbered 1 to 20. What is the probability that the number drawn is a MULTIPLE OF 5?",
        "optionA": "1/4",
        "optionB": "1/5",
        "optionC": "3/20",
        "optionD": "1/10",
        "correctOption": "B",
        "subConcept": "Multiples & Divisibility Probability",
        "explanation": "Multiples of 5 from 1 to 20 are: 5, 10, 15, 20 (4 numbers). P(multiple of 5) = 4/20 = 1/5.",
        "remediationTip": "List all multiples within the range, count them, and divide by the total cards."
      },
      {
        "id": "q-prb-10",
        "quizId": "quiz-jhs1-math-probability",
        "questionText": "In a JHS 1 class of 18 boys and 22 girls, one student is chosen at random as class prefect. What is the probability of selecting a GIRL?",
        "optionA": "9/20",
        "optionB": "11/20",
        "optionC": "11/9",
        "optionD": "22/18",
        "correctOption": "B",
        "subConcept": "Selection Probability in Groups",
        "explanation": "Total students = 18 + 22 = 40. Girls = 22. P(Girl) = 22 / 40. Dividing numerator and denominator by 2 gives 11 / 20.",
        "remediationTip": "Always simplify the resulting fraction to its lowest terms."
      }
    ]
  }
};
