// Ghanaian SHS 1 Core Mathematics Comprehensive Practice Quizzes
// Based on WAEC / WASSCE Syllabus
// 17 Topics × 10 Questions = 170 WASSCE-Standard Questions

import { TopicQuiz } from './types';

export const SHS1_MATH_QUIZZES: Record<string, TopicQuiz> = {
  // ==========================================
  // TOPIC 1: Sets, Set Operations & 3-Set Venn Diagrams
  // ==========================================
  "shs1-math-t1-sets-venn": {
    id: "quiz-shs1-math-sets",
    topicId: "shs1-math-t1-sets-venn",
    title: "Sets & 3-Set Venn Diagrams Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m1-1",
        quizId: "quiz-shs1-math-sets",
        questionText: "If a set P has 6 elements, how many subsets does P have in total?",
        optionA: "12",
        optionB: "36",
        optionC: "64",
        optionD: "128",
        correctOption: "C",
        subConcept: "Number of Subsets Formula (2ⁿ)",
        explanation: "The total number of subsets of a set with n elements is 2ⁿ. Here, n = 6, so 2⁶ = 64.",
        remediationTip: "Calculate 2ⁿ where n is the number of elements."
      },
      {
        id: "q-shs1-m1-2",
        quizId: "quiz-shs1-math-sets",
        questionText: "According to De Morgan's Law, (A ∪ B)' is equivalent to which set?",
        optionA: "A' ∪ B'",
        optionB: "A' ∩ B'",
        optionC: "(A ∩ B)'",
        optionD: "A ∩ B",
        correctOption: "B",
        subConcept: "De Morgan's Laws",
        explanation: "De Morgan's Law states that the complement of a union is the intersection of individual complements: (A ∪ B)' = A' ∩ B'.",
        remediationTip: "Complement flips union (∪) to intersection (∩)."
      },
      {
        id: "q-shs1-m1-3",
        quizId: "quiz-shs1-math-sets",
        questionText: "In a class of 50 students, 30 like Yam, 25 like Rice, and 10 like both. How many students like neither?",
        optionA: "5",
        optionB: "10",
        optionC: "15",
        optionD: "20",
        correctOption: "A",
        subConcept: "Two-Set Venn Inclusion-Exclusion",
        explanation: "n(Y ∪ R) = n(Y) + n(R) - n(Y ∩ R) = 30 + 25 - 10 = 45. Neither = 50 - 45 = 5.",
        remediationTip: "Subtract intersection once to find the union, then subtract from the universal total."
      },
      {
        id: "q-shs1-m1-4",
        quizId: "quiz-shs1-math-sets",
        questionText: "If set A has 5 elements, how many PROPER subsets does set A have?",
        optionA: "32",
        optionB: "31",
        optionC: "25",
        optionD: "10",
        correctOption: "B",
        subConcept: "Proper Subsets Formula (2ⁿ - 1)",
        explanation: "Total subsets = 2⁵ = 32. The number of PROPER subsets excludes the set itself: 2ⁿ - 1 = 32 - 1 = 31.",
        remediationTip: "Proper subsets exclude the set itself, so formula is 2ⁿ - 1."
      },
      {
        id: "q-shs1-m1-5",
        quizId: "quiz-shs1-math-sets",
        questionText: "Which of the following is equivalent to De Morgan's second law: (A ∩ B)'?",
        optionA: "A' ∩ B'",
        optionB: "A' ∪ B'",
        optionC: "A ∪ B",
        optionD: "(A ∪ B)'",
        correctOption: "B",
        subConcept: "De Morgan's Laws",
        explanation: "(A ∩ B)' = A' ∪ B'. Complement of intersection equals union of complements.",
        remediationTip: "Complement flips intersection (∩) to union (∪)."
      },
      {
        id: "q-shs1-m1-6",
        quizId: "quiz-shs1-math-sets",
        questionText: "In a survey of 100 people, 60 drink tea, 50 drink coffee, and 20 drink both. How many drink tea ONLY?",
        optionA: "30",
        optionB: "40",
        optionC: "50",
        optionD: "60",
        correctOption: "B",
        subConcept: "Set Difference (Only region)",
        explanation: "Tea only = Total tea - Both = 60 - 20 = 40 people.",
        remediationTip: "To find 'Tea only', subtract the intersection from total tea drinkers."
      },
      {
        id: "q-shs1-m1-7",
        quizId: "quiz-shs1-math-sets",
        questionText: "If sets A and B are disjoint, what is n(A ∩ B)?",
        optionA: "1",
        optionB: "0",
        optionC: "n(A) + n(B)",
        optionD: "Undefined",
        correctOption: "B",
        subConcept: "Disjoint Sets",
        explanation: "Disjoint sets have no elements in common, meaning A ∩ B = ∅ and n(A ∩ B) = 0.",
        remediationTip: "Disjoint sets have zero intersection."
      },
      {
        id: "q-shs1-m1-8",
        quizId: "quiz-shs1-math-sets",
        questionText: "In a 3-set Venn diagram, what region should always be populated FIRST when solving with unknown variables?",
        optionA: "The universal set complement",
        optionB: "The three-set intersection n(A ∩ B ∩ C)",
        optionC: "Set A only",
        optionD: "The pairwise intersection n(A ∩ B)",
        correctOption: "B",
        subConcept: "3-Set Venn Problem Solving Strategy",
        explanation: "Always assign or populate the central triple intersection n(A ∩ B ∩ C) first, as dual and solo regions depend on subtracting it.",
        remediationTip: "Work from the innermost center region outwards."
      },
      {
        id: "q-shs1-m1-9",
        quizId: "quiz-shs1-math-sets",
        questionText: "If universal set ξ = {x : 1 ≤ x ≤ 10, x is an integer} and A = {prime numbers}, what is A'?",
        optionA: "{2, 3, 5, 7}",
        optionB: "{1, 4, 6, 8, 9, 10}",
        optionC: "{4, 6, 8, 9, 10}",
        optionD: "{1, 2, 4, 6, 8, 9, 10}",
        correctOption: "B",
        subConcept: "Set Complement",
        explanation: "Prime numbers between 1 and 10 are {2, 3, 5, 7}. Notice 1 is neither prime nor composite, so 1 is in A'. Thus A' = {1, 4, 6, 8, 9, 10}.",
        remediationTip: "Remember 1 is not a prime number, so it belongs to the complement."
      },
      {
        id: "q-shs1-m1-10",
        quizId: "quiz-shs1-math-sets",
        questionText: "For three sets A, B, and C, if n(A)=20, n(B)=22, n(C)=18, n(A∩B)=7, n(B∩C)=8, n(A∩C)=6, and n(A∩B∩C)=3, what is n(A∪B∪C)?",
        optionA: "40",
        optionB: "42",
        optionC: "45",
        optionD: "60",
        correctOption: "B",
        subConcept: "Three-Set Inclusion-Exclusion Formula",
        explanation: "n(A∪B∪C) = 20 + 22 + 18 - (7 + 8 + 6) + 3 = 60 - 21 + 3 = 42.",
        remediationTip: "Add individual sets, subtract dual intersections, and add back the triple intersection."
      }
    ]
  },

  // ==========================================
  // TOPIC 2: Real Number System, Surds & Standard Form
  // ==========================================
  "shs1-math-t1-real-numbers-surds": {
    id: "quiz-shs1-math-surds",
    topicId: "shs1-math-t1-real-numbers-surds",
    title: "Surds & Real Numbers Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m2-1",
        quizId: "quiz-shs1-math-surds",
        questionText: "Simplify √75 - √12 in simplest surd form.",
        optionA: "√63",
        optionB: "3√3",
        optionC: "5√3",
        optionD: "7√3",
        correctOption: "B",
        subConcept: "Simplifying Surds",
        explanation: "√75 = √(25 × 3) = 5√3. √12 = √(4 × 3) = 2√3. Therefore 5√3 - 2√3 = 3√3.",
        remediationTip: "Extract square factors: √75 = 5√3 and √12 = 2√3."
      },
      {
        id: "q-shs1-m2-2",
        quizId: "quiz-shs1-math-surds",
        questionText: "What is the conjugate of the binomial surd (4 - √5)?",
        optionA: "-4 - √5",
        optionB: "-(4 - √5)",
        optionC: "4 + √5",
        optionD: "1 / (4 - √5)",
        correctOption: "C",
        subConcept: "Conjugate Surd",
        explanation: "The conjugate of (a - √b) is (a + √b). Therefore, conjugate of (4 - √5) is 4 + √5.",
        remediationTip: "Change the minus sign to plus between terms."
      },
      {
        id: "q-shs1-m2-3",
        quizId: "quiz-shs1-math-surds",
        questionText: "Express 0.0000782 in standard form.",
        optionA: "7.82 × 10⁻⁴",
        optionB: "7.82 × 10⁻⁵",
        optionC: "78.2 × 10⁻⁶",
        optionD: "7.82 × 10⁵",
        correctOption: "B",
        subConcept: "Standard Form",
        explanation: "Move decimal point 5 places to the right to obtain 7.82 × 10⁻⁵.",
        remediationTip: "Count decimal shifts to the right; each shift gives a negative power of 10."
      },
      {
        id: "q-shs1-m2-4",
        quizId: "quiz-shs1-math-surds",
        questionText: "Simplify: √48 + √27.",
        optionA: "7√3",
        optionB: "√75",
        optionC: "12√3",
        optionD: "5√3",
        correctOption: "A",
        subConcept: "Addition of Like Surds",
        explanation: "√48 = √(16 × 3) = 4√3. √27 = √(9 × 3) = 3√3. 4√3 + 3√3 = 7√3.",
        remediationTip: "Break into square factors: 4√3 + 3√3 = 7√3."
      },
      {
        id: "q-shs1-m2-5",
        quizId: "quiz-shs1-math-surds",
        questionText: "Rationalize the denominator of 6 / √3.",
        optionA: "2",
        optionB: "2√3",
        optionC: "3√3",
        optionD: "6√3",
        correctOption: "B",
        subConcept: "Monomial Rationalization",
        explanation: "Multiply numerator and denominator by √3: (6 × √3) / (√3 × √3) = 6√3 / 3 = 2√3.",
        remediationTip: "Multiply numerator and denominator by √3, then divide 6 by 3."
      },
      {
        id: "q-shs1-m2-6",
        quizId: "quiz-shs1-math-surds",
        questionText: "Expand and simplify: (√5 + √2)(√5 - √2).",
        optionA: "3",
        optionB: "7",
        optionC: "√3",
        optionD: "3 + 2√10",
        correctOption: "A",
        subConcept: "Difference of Two Squares in Surds",
        explanation: "(√5 + √2)(√5 - √2) = (√5)² - (√2)² = 5 - 2 = 3.",
        remediationTip: "Use difference of two squares: (a + b)(a - b) = a² - b²."
      },
      {
        id: "q-shs1-m2-7",
        quizId: "quiz-shs1-math-surds",
        questionText: "Which of the following numbers is an IRRATIONAL number?",
        optionA: "√16",
        optionB: "0.333...",
        optionC: "√7",
        optionD: "22/7",
        correctOption: "C",
        subConcept: "Classification of Real Numbers",
        explanation: "√7 cannot be written as a ratio of two integers and has a non-repeating decimal. √16 = 4, 0.333... = 1/3, and 22/7 are all rational.",
        remediationTip: "A square root of a non-perfect square is irrational."
      },
      {
        id: "q-shs1-m2-8",
        quizId: "quiz-shs1-math-surds",
        questionText: "Evaluate (2.5 × 10⁴) × (4.0 × 10³) in standard form.",
        optionA: "1.0 × 10⁷",
        optionB: "1.0 × 10⁸",
        optionC: "10.0 × 10⁷",
        optionD: "1.0 × 10⁶",
        correctOption: "B",
        subConcept: "Operations in Standard Form",
        explanation: "2.5 × 4.0 = 10.0. 10⁴ × 10³ = 10⁷. So 10.0 × 10⁷ = 1.0 × 10⁸ in proper standard form.",
        remediationTip: "Adjust 10.0 × 10⁷ to 1.0 × 10⁸ so that 1 ≤ A < 10."
      },
      {
        id: "q-shs1-m2-9",
        quizId: "quiz-shs1-math-surds",
        questionText: "Expand (√3 + 2)².",
        optionA: "7",
        optionB: "5 + 2√3",
        optionC: "7 + 4√3",
        optionD: "7 + 2√3",
        correctOption: "C",
        subConcept: "Binomial Surd Expansion",
        explanation: "(√3 + 2)² = (√3)² + 2(√3)(2) + 2² = 3 + 4√3 + 4 = 7 + 4√3.",
        remediationTip: "Don't forget the middle term: 2ab = 4√3."
      },
      {
        id: "q-shs1-m2-10",
        quizId: "quiz-shs1-math-surds",
        questionText: "Rationalize the denominator of 1 / (√3 - 1).",
        optionA: "(√3 + 1) / 2",
        optionB: "(√3 - 1) / 2",
        optionC: "√3 + 1",
        optionD: "(√3 + 1) / 4",
        correctOption: "A",
        subConcept: "Binomial Denominator Rationalization",
        explanation: "Multiply top and bottom by (√3 + 1): 1(√3 + 1) / ((√3)² - 1²) = (√3 + 1) / (3 - 1) = (√3 + 1) / 2.",
        remediationTip: "Multiply by conjugate (√3 + 1); denominator becomes 3 - 1 = 2."
      }
    ]
  },

  // ==========================================
  // TOPIC 3: Indices & Logarithms
  // ==========================================
  "shs1-math-t1-indices-logarithms": {
    id: "quiz-shs1-math-indices-log",
    topicId: "shs1-math-t1-indices-logarithms",
    title: "Indices & Logarithms Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m3-1",
        quizId: "quiz-shs1-math-indices-log",
        questionText: "Evaluate (64)^(2/3).",
        optionA: "8",
        optionB: "16",
        optionC: "32",
        optionD: "4",
        correctOption: "B",
        subConcept: "Fractional Indices",
        explanation: "(64)^(1/3) = 4, and 4² = 16. Alternatively, (4³)^(2/3) = 4² = 16.",
        remediationTip: "Take the cube root first, then square."
      },
      {
        id: "q-shs1-m3-2",
        quizId: "quiz-shs1-math-indices-log",
        questionText: "If log₁₀(2) = 0.3010 and log₁₀(3) = 0.4771, find log₁₀(18).",
        optionA: "0.7781",
        optionB: "1.2552",
        optionC: "1.0791",
        optionD: "0.9542",
        correctOption: "B",
        subConcept: "Laws of Logarithms",
        explanation: "18 = 2 × 3² = 2 × 9. log(18) = log(2) + 2·log(3) = 0.3010 + 2(0.4771) = 0.3010 + 0.9542 = 1.2552.",
        remediationTip: "Prime factorize 18: 18 = 2 × 3²."
      },
      {
        id: "q-shs1-m3-3",
        quizId: "quiz-shs1-math-indices-log",
        questionText: "Solve for x if 2^(3x - 1) = 16.",
        optionA: "1",
        optionB: "5/3",
        optionC: "2",
        optionD: "3",
        correctOption: "B",
        subConcept: "Exponential Equations",
        explanation: "16 = 2⁴. So 3x - 1 = 4 → 3x = 5 → x = 5/3.",
        remediationTip: "Equate powers: 3x - 1 = 4, so 3x = 5."
      },
      {
        id: "q-shs1-m3-4",
        quizId: "quiz-shs1-math-indices-log",
        questionText: "What is the value of 5⁰ + 5⁻¹?",
        optionA: "1/5",
        optionB: "6/5",
        optionC: "0",
        optionD: "-5",
        correctOption: "B",
        subConcept: "Zero and Negative Indices",
        explanation: "5⁰ = 1 and 5⁻¹ = 1/5. 1 + 1/5 = 6/5 (or 1.2).",
        remediationTip: "Any non-zero number to power 0 equals 1; a⁻¹ = 1/a."
      },
      {
        id: "q-shs1-m3-5",
        quizId: "quiz-shs1-math-indices-log",
        questionText: "Solve for x: log₂(x) = 5.",
        optionA: "10",
        optionB: "25",
        optionC: "32",
        optionD: "64",
        correctOption: "C",
        subConcept: "Definition of Logarithm",
        explanation: "log_b(y) = x means y = bˣ. Here, x = 2⁵ = 32.",
        remediationTip: "Convert log form to index form: base 2 raised to power 5."
      },
      {
        id: "q-shs1-m3-6",
        quizId: "quiz-shs1-math-indices-log",
        questionText: "Simplify: (x³y⁴) / (x⁵y²).",
        optionA: "x²y²",
        optionB: "y² / x²",
        optionC: "x⁸y⁶",
        optionD: "x² / y²",
        correctOption: "B",
        subConcept: "Quotient Law of Indices",
        explanation: "x^(3 - 5) · y^(4 - 2) = x⁻²y² = y² / x².",
        remediationTip: "Subtract powers of matching variables: 3 - 5 = -2, 4 - 2 = 2."
      },
      {
        id: "q-shs1-m3-7",
        quizId: "quiz-shs1-math-indices-log",
        questionText: "What is log₃(81)?",
        optionA: "3",
        optionB: "4",
        optionC: "9",
        optionD: "27",
        correctOption: "B",
        subConcept: "Evaluating Logarithms",
        explanation: "3⁴ = 81, so log₃(81) = 4.",
        remediationTip: "Ask: 3 raised to what power equals 81? Answer is 4."
      },
      {
        id: "q-shs1-m3-8",
        quizId: "quiz-shs1-math-indices-log",
        questionText: "If 3^(2x) = 1/27, find x.",
        optionA: "-3",
        optionB: "-3/2",
        optionC: "3/2",
        optionD: "-1",
        correctOption: "B",
        subConcept: "Negative Exponent Equations",
        explanation: "1/27 = 3⁻³. So 2x = -3 → x = -3/2.",
        remediationTip: "Express 1/27 as 3⁻³, then equate 2x = -3."
      },
      {
        id: "q-shs1-m3-9",
        quizId: "quiz-shs1-math-indices-log",
        questionText: "Express log(a) + 2·log(b) - log(c) as a single logarithm.",
        optionA: "log(ab² / c)",
        optionB: "log(2ab / c)",
        optionC: "log(a + b² - c)",
        optionD: "log(ab / 2c)",
        correctOption: "A",
        subConcept: "Condensing Logarithms",
        explanation: "2·log(b) = log(b²). Then log(a) + log(b²) = log(ab²). Subtracting log(c) gives log(ab² / c).",
        remediationTip: "Power moves inside exponent: 2·log(b) = log(b²)."
      },
      {
        id: "q-shs1-m3-10",
        quizId: "quiz-shs1-math-indices-log",
        questionText: "Solve for x: log(x + 3) + log(2) = 1 (base 10).",
        optionA: "2",
        optionB: "3.5",
        optionC: "5",
        optionD: "7",
        correctOption: "A",
        subConcept: "Logarithmic Equations",
        explanation: "log[2(x + 3)] = 1 → 2(x + 3) = 10¹ = 10 → 2x + 6 = 10 → 2x = 4 → x = 2.",
        remediationTip: "Combine logs on LHS into log[2(x + 3)], then convert to base 10 index form."
      }
    ]
  },

  // ==========================================
  // TOPIC 4: Algebraic Expressions, Expansion & Factorization
  // ==========================================
  "shs1-math-t1-algebra-factorization": {
    id: "quiz-shs1-math-algebra",
    topicId: "shs1-math-t1-algebra-factorization",
    title: "Algebraic Factorization Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m4-1",
        quizId: "quiz-shs1-math-algebra",
        questionText: "Factorize completely: 25x² - 36y².",
        optionA: "(5x - 6y)²",
        optionB: "(25x - 36y)(x + y)",
        optionC: "(5x - 6y)(5x + 6y)",
        optionD: "(5x + 6y)²",
        correctOption: "C",
        subConcept: "Difference of Two Squares",
        explanation: "25x² = (5x)² and 36y² = (6y)². By difference of two squares, a² - b² = (a - b)(a + b) = (5x - 6y)(5x + 6y).",
        remediationTip: "Remember: a² - b² = (a - b)(a + b)."
      },
      {
        id: "q-shs1-m4-2",
        quizId: "quiz-shs1-math-algebra",
        questionText: "Factorize: 3x² - 5x - 2.",
        optionA: "(3x + 1)(x - 2)",
        optionB: "(3x - 1)(x + 2)",
        optionC: "(3x - 2)(x + 1)",
        optionD: "(3x + 2)(x - 1)",
        correctOption: "A",
        subConcept: "Trinomial Factorization",
        explanation: "ac = 3 × (-2) = -6. Factors giving sum -5 are -6 and +1. 3x² - 6x + x - 2 = 3x(x - 2) + 1(x - 2) = (3x + 1)(x - 2).",
        remediationTip: "Check product by FOIL: (3x)(x) - 6x + x - 2 = 3x² - 5x - 2."
      },
      {
        id: "q-shs1-m4-3",
        quizId: "quiz-shs1-math-algebra",
        questionText: "Expand and simplify: (2x - 3)²',",
        optionA: "4x² - 9",
        optionB: "4x² - 6x + 9",
        optionC: "4x² - 12x + 9",
        optionD: "4x² + 12x - 9",
        correctOption: "C",
        subConcept: "Binomial Expansion",
        explanation: "(2x - 3)² = (2x)² - 2(2x)(3) + 3² = 4x² - 12x + 9.",
        remediationTip: "Don't forget the middle term: -2ab."
      },
      {
        id: "q-shs1-m4-4",
        quizId: "quiz-shs1-math-algebra",
        questionText: "Factorize by grouping: ax + ay + bx + by.",
        optionA: "(a + b)(x + y)",
        optionB: "(a + x)(b + y)",
        optionC: "(ax + by)(a + b)",
        optionD: "(a - b)(x - y)",
        correctOption: "A",
        subConcept: "Factorization by Grouping",
        explanation: "a(x + y) + b(x + y) = (a + b)(x + y).",
        remediationTip: "Factor 'a' from first pair and 'b' from second pair."
      },
      {
        id: "q-shs1-m4-5",
        quizId: "quiz-shs1-math-algebra",
        questionText: "Factorize completely: 2x² - 18.",
        optionA: "2(x - 3)²",
        optionB: "2(x - 3)(x + 3)",
        optionC: "(2x - 6)(x + 3)",
        optionD: "(x - 9)(x + 9)",
        correctOption: "B",
        subConcept: "Common Factor then Difference of Squares",
        explanation: "Factor out 2: 2(x² - 9) = 2(x - 3)(x + 3).",
        remediationTip: "Always pull out the common factor first."
      },
      {
        id: "q-shs1-m4-6",
        quizId: "quiz-shs1-math-algebra",
        questionText: "Factorize: x² - 7x + 12.",
        optionA: "(x - 3)(x - 4)",
        optionB: "(x + 3)(x + 4)",
        optionC: "(x - 2)(x - 6)",
        optionD: "(x - 1)(x - 12)",
        correctOption: "A",
        subConcept: "Quadratic Trinomial (a=1)",
        explanation: "Two numbers multiplying to +12 and adding to -7 are -3 and -4: (x - 3)(x - 4).",
        remediationTip: "Find two numbers with product +12 and sum -7."
      },
      {
        id: "q-shs1-m4-7",
        quizId: "quiz-shs1-math-algebra",
        questionText: "Expand: (3x + 4)(2x - 5).",
        optionA: "6x² - 7x - 20",
        optionB: "6x² + 7x - 20",
        optionC: "6x² - 20",
        optionD: "6x² - 15x - 20",
        correctOption: "A",
        subConcept: "FOIL Binomial Multiplication",
        explanation: "(3x)(2x) + (3x)(-5) + (4)(2x) + (4)(-5) = 6x² - 15x + 8x - 20 = 6x² - 7x - 20.",
        remediationTip: "Combine middle terms: -15x + 8x = -7x."
      },
      {
        id: "q-shs1-m4-8",
        quizId: "quiz-shs1-math-algebra",
        questionText: "What must be added to x² + 8x to make it a perfect square trinomial?",
        optionA: "4",
        optionB: "8",
        optionC: "16",
        optionD: "64",
        correctOption: "C",
        subConcept: "Completing the Square Term",
        explanation: "Half of 8 is 4; squaring 4 gives 4² = 16. (x + 4)² = x² + 8x + 16.",
        remediationTip: "Take (b/2)² = (8/2)² = 4² = 16."
      },
      {
        id: "q-shs1-m4-9",
        quizId: "quiz-shs1-math-algebra",
        questionText: "Factorize: 6ab - 9a + 4b - 6.",
        optionA: "(3a + 2)(2b - 3)",
        optionB: "(3a - 2)(2b + 3)",
        optionC: "(2a + 3)(3b - 2)",
        optionD: "(6a + 4)(b - 3)",
        correctOption: "A",
        subConcept: "4-Term Grouping",
        explanation: "3a(2b - 3) + 2(2b - 3) = (3a + 2)(2b - 3).",
        remediationTip: "Notice common bracket (2b - 3) in both halves."
      },
      {
        id: "q-shs1-m4-10",
        quizId: "quiz-shs1-math-algebra",
        questionText: "Factorize: 4x² - 12x + 9.",
        optionA: "(2x - 3)²",
        optionB: "(2x + 3)²",
        optionC: "(4x - 9)(x - 1)",
        optionD: "(2x - 9)(2x - 1)",
        correctOption: "A",
        subConcept: "Perfect Square Trinomial",
        explanation: "(2x)² - 2(2x)(3) + 3² = (2x - 3)².",
        remediationTip: "Recognize form a² - 2ab + b² = (a - b)²."
      }
    ]
  },

  // ==========================================
  // TOPIC 5: Algebraic Fractions & Undefined Fractions
  // ==========================================
  "shs1-math-t1-algebraic-fractions": {
    id: "quiz-shs1-math-alg-fractions",
    topicId: "shs1-math-t1-algebraic-fractions",
    title: "Algebraic Fractions Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m5b-1",
        quizId: "quiz-shs1-math-alg-fractions",
        questionText: "For what value of x is the fraction (3x + 1) / (x - 4) UNDEFINED?",
        optionA: "-1/3",
        optionB: "0",
        optionC: "4",
        optionD: "-4",
        correctOption: "C",
        subConcept: "Undefined Fractions Condition",
        explanation: "A fraction is undefined when its denominator equals zero: x - 4 = 0 → x = 4.",
        remediationTip: "Set the denominator equal to 0 and solve for x."
      },
      {
        id: "q-shs1-m5b-2",
        quizId: "quiz-shs1-math-alg-fractions",
        questionText: "Simplify: (x² - 9) / (x² + 5x + 6).",
        optionA: "(x - 3) / (x + 2)",
        optionB: "(x + 3) / (x + 2)",
        optionC: "(x - 3) / (x - 2)",
        optionD: "1 / (5x + 6)",
        correctOption: "A",
        subConcept: "Simplifying Algebraic Fractions",
        explanation: "(x - 3)(x + 3) / [(x + 2)(x + 3)]. Canceling (x + 3) gives (x - 3) / (x + 2).",
        remediationTip: "Factorize both numerator and denominator completely, then cancel common factors."
      },
      {
        id: "q-shs1-m5b-3",
        quizId: "quiz-shs1-math-alg-fractions",
        questionText: "Find the values of x for which (x + 5) / (x² - 2x - 8) is undefined.",
        optionA: "x = 4 and x = -2",
        optionB: "x = -4 and x = 2",
        optionC: "x = -5",
        optionD: "x = 8 and x = 1",
        correctOption: "A",
        subConcept: "Quadratic Denominator Restrictions",
        explanation: "x² - 2x - 8 = 0 → (x - 4)(x + 2) = 0 → x = 4 or x = -2.",
        remediationTip: "Factor the denominator (x - 4)(x + 2) and set each factor to 0."
      },
      {
        id: "q-shs1-m5b-4",
        quizId: "quiz-shs1-math-alg-fractions",
        questionText: "Simplify: (2 / x) + (3 / 2x).",
        optionA: "5 / 2x",
        optionB: "7 / 2x",
        optionC: "5 / 3x",
        optionD: "6 / x²",
        correctOption: "B",
        subConcept: "Adding Algebraic Fractions",
        explanation: "LCM of x and 2x is 2x. (4 / 2x) + (3 / 2x) = 7 / 2x.",
        remediationTip: "Convert 2/x to 4/2x so denominators match."
      },
      {
        id: "q-shs1-m5b-5",
        quizId: "quiz-shs1-math-alg-fractions",
        questionText: "Simplify: (a / b) ÷ (a² / b²).",
        optionA: "a / b",
        optionB: "b / a",
        optionC: "a³ / b³",
        optionD: "1",
        correctOption: "B",
        subConcept: "Dividing Algebraic Fractions",
        explanation: "(a / b) × (b² / a²) = (a · b²) / (b · a²) = b / a.",
        remediationTip: "Invert second fraction and multiply."
      },
      {
        id: "q-shs1-m5b-6",
        quizId: "quiz-shs1-math-alg-fractions",
        questionText: "What is the LCM of the denominators in 1/(x - 1) and 2/(x + 1)?",
        optionA: "x² - 1",
        optionB: "2(x - 1)",
        optionC: "x + 1",
        optionD: "x² + 1",
        correctOption: "A",
        subConcept: "LCM of Binomial Denominators",
        explanation: "The denominators are distinct linear binomials, so their LCM is their product: (x - 1)(x + 1) = x² - 1.",
        remediationTip: "Multiply unlike linear denominators to find their LCM."
      },
      {
        id: "q-shs1-m5b-7",
        quizId: "quiz-shs1-math-alg-fractions",
        questionText: "Simplify: (x² - 4) / (2x - 4).",
        optionA: "(x + 2) / 2",
        optionB: "(x - 2) / 2",
        optionC: "x / 2",
        optionD: "x + 2",
        correctOption: "A",
        subConcept: "Canceling Common Binomial Factors",
        explanation: "(x - 2)(x + 2) / [2(x - 2)] = (x + 2) / 2.",
        remediationTip: "Factor 2 out of the denominator: 2(x - 2)."
      },
      {
        id: "q-shs1-m5b-8",
        quizId: "quiz-shs1-math-alg-fractions",
        questionText: "For what value of x does the fraction (2x - 6) / (x + 3) equal ZERO?",
        optionA: "-3",
        optionB: "3",
        optionC: "0",
        optionD: "6",
        correctOption: "B",
        subConcept: "Fraction Equaling Zero",
        explanation: "A fraction equals 0 when its NUMERATOR is 0 (and denominator ≠ 0): 2x - 6 = 0 → 2x = 6 → x = 3.",
        remediationTip: "A fraction is zero when its numerator is zero."
      },
      {
        id: "q-shs1-m5b-9",
        quizId: "quiz-shs1-math-alg-fractions",
        questionText: "Simplify: 1/(x + 2) - 1/(x + 3).",
        optionA: "1 / [(x + 2)(x + 3)]",
        optionB: "-1 / [(x + 2)(x + 3)]",
        optionC: "5 / [(x + 2)(x + 3)]",
        optionD: "2x + 5",
        correctOption: "A",
        subConcept: "Subtracting Algebraic Fractions",
        explanation: "[(x + 3) - (x + 2)] / [(x + 2)(x + 3)] = (x + 3 - x - 2) / [(x + 2)(x + 3)] = 1 / [(x + 2)(x + 3)].",
        remediationTip: "Distribute the negative sign: -(x + 2) = -x - 2."
      },
      {
        id: "q-shs1-m5b-10",
        quizId: "quiz-shs1-math-alg-fractions",
        questionText: "Simplify: (4x²y) / (6xy³).",
        optionA: "2x / 3y²",
        optionB: "2x² / 3y",
        optionC: "2 / 3xy",
        optionD: "3x / 2y²",
        correctOption: "A",
        subConcept: "Simplifying Monomial Fractions",
        explanation: "4/6 reduces to 2/3. x²/x = x. y/y³ = 1/y². Result is 2x / 3y².",
        remediationTip: "Reduce numbers first, then apply index laws on variables."
      }
    ]
  },

  // ==========================================
  // TOPIC 6: Linear Equations in One Variable (Including Fractional Equations)
  // ==========================================
  "shs1-math-t1-linear-equations-fractions": {
    id: "quiz-shs1-math-linear-eq",
    topicId: "shs1-math-t1-linear-equations-fractions",
    title: "Linear Equations Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m6b-1",
        quizId: "quiz-shs1-math-linear-eq",
        questionText: "Solve for x: (x + 2) / 3 = (2x - 1) / 5.",
        optionA: "13",
        optionB: "-13",
        optionC: "7",
        optionD: "-7",
        correctOption: "A",
        subConcept: "Cross-Multiplication",
        explanation: "5(x + 2) = 3(2x - 1) → 5x + 10 = 6x - 3 → 13 = x.",
        remediationTip: "Cross-multiply: 5(x + 2) = 3(2x - 1)."
      },
      {
        id: "q-shs1-m6b-2",
        quizId: "quiz-shs1-math-linear-eq",
        questionText: "Solve: 3(2x - 4) = 4(x + 1).",
        optionA: "4",
        optionB: "6",
        optionC: "8",
        optionD: "10",
        correctOption: "C",
        subConcept: "Expanding and Collecting Terms",
        explanation: "6x - 12 = 4x + 4 → 6x - 4x = 4 + 12 → 2x = 16 → x = 8.",
        remediationTip: "Expand both brackets, group x on the left, constants on the right."
      },
      {
        id: "q-shs1-m6b-3",
        quizId: "quiz-shs1-math-linear-eq",
        questionText: "Solve for y: (y/2) - (y/3) = 4.",
        optionA: "12",
        optionB: "18",
        optionC: "24",
        optionD: "36",
        correctOption: "C",
        subConcept: "Clearing Denominators with LCM",
        explanation: "LCM of 2 and 3 is 6. Multiply all terms by 6: 3y - 2y = 24 → y = 24.",
        remediationTip: "Multiply EVERY term by 6, including the 4."
      },
      {
        id: "q-shs1-m6b-4",
        quizId: "quiz-shs1-math-linear-eq",
        questionText: "Solve for m: 5 - 2(m - 3) = 15.",
        optionA: "-2",
        optionB: "2",
        optionC: "-5",
        optionD: "5",
        correctOption: "A",
        subConcept: "Negative Bracket Expansion",
        explanation: "5 - 2m + 6 = 15 → 11 - 2m = 15 → -2m = 4 → m = -2.",
        remediationTip: "-2 × (-3) = +6. Be careful with signs."
      },
      {
        id: "q-shs1-m6b-5",
        quizId: "quiz-shs1-math-linear-eq",
        questionText: "If 4x - 7 = 2x + 9, what is the value of 3x?",
        optionA: "8",
        optionB: "16",
        optionC: "24",
        optionD: "32",
        correctOption: "C",
        subConcept: "Solving for Derived Expressions",
        explanation: "4x - 2x = 9 + 7 → 2x = 16 → x = 8. The question asks for 3x = 3(8) = 24.",
        remediationTip: "Read carefully: solve for x first, then multiply by 3."
      },
      {
        id: "q-shs1-m6b-6",
        quizId: "quiz-shs1-math-linear-eq",
        questionText: "Solve: (2x - 3) / 4 - (x - 2) / 3 = 1.",
        optionA: "6.5",
        optionB: "13",
        optionC: "15",
        optionD: "8",
        correctOption: "A",
        subConcept: "Fractional Equation Distribution",
        explanation: "Multiply by 12: 3(2x - 3) - 4(x - 2) = 12 → 6x - 9 - 4x + 8 = 12 → 2x - 1 = 12 → 2x = 13 → x = 6.5.",
        remediationTip: "-4 × (-2) = +8."
      },
      {
        id: "q-shs1-m6b-7",
        quizId: "quiz-shs1-math-linear-eq",
        questionText: "A father is 3 times as old as his son. In 12 years, he will be twice as old as his son. How old is the son now?",
        optionA: "10",
        optionB: "12",
        optionC: "15",
        optionD: "18",
        correctOption: "B",
        subConcept: "Word Problem Modeling",
        explanation: "Let son's age = s, father = 3s. In 12 years: (3s + 12) = 2(s + 12) → 3s + 12 = 2s + 24 → s = 12 years.",
        remediationTip: "Set up the equation for their future ages."
      },
      {
        id: "q-shs1-m6b-8",
        quizId: "quiz-shs1-math-linear-eq",
        questionText: "Solve for k: (k - 1)/2 + (k + 1)/3 = 5.",
        optionA: "5",
        optionB: "6.2",
        optionC: "7",
        optionD: "8",
        correctOption: "B",
        subConcept: "Linear Equation with Fractions",
        explanation: "Multiply by 6: 3(k - 1) + 2(k + 1) = 30 → 3k - 3 + 2k + 2 = 30 → 5k - 1 = 30 → 5k = 31 → k = 6.2.",
        remediationTip: "Multiply both sides by LCM = 6."
      },
      {
        id: "q-shs1-m6b-9",
        quizId: "quiz-shs1-math-linear-eq",
        questionText: "Solve: 2(3x - 1) - 3(x + 4) = 4.",
        optionA: "6",
        optionB: "4",
        optionC: "8",
        optionD: "5",
        correctOption: "A",
        subConcept: "Expanding Multiple Brackets",
        explanation: "6x - 2 - 3x - 12 = 4 → 3x - 14 = 4 → 3x = 18 → x = 6.",
        remediationTip: "Expand brackets carefully: -3(x + 4) = -3x - 12."
      },
      {
        id: "q-shs1-m6b-10",
        quizId: "quiz-shs1-math-linear-eq",
        questionText: "The sum of three consecutive integers is 72. What is the largest integer?",
        optionA: "23",
        optionB: "24",
        optionC: "25",
        optionD: "26",
        correctOption: "C",
        subConcept: "Consecutive Numbers Word Problem",
        explanation: "Let integers be n, n+1, n+2. Sum: 3n + 3 = 72 → 3n = 69 → n = 23. The integers are 23, 24, 25. The largest is 25.",
        remediationTip: "The three integers are 23, 24, 25. The largest is 25."
      }
    ]
  },

  // ==========================================
  // TOPIC 7: Linear Inequalities in One Variable & Number Line
  // ==========================================
  "shs1-math-t2-linear-inequalities": {
    id: "quiz-shs1-math-inequalities",
    topicId: "shs1-math-t2-linear-inequalities",
    title: "Linear Inequalities Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m7b-1",
        quizId: "quiz-shs1-math-inequalities",
        questionText: "Solve the inequality: 5 - 2x ≥ 11.",
        optionA: "x ≥ -3",
        optionB: "x ≤ -3",
        optionC: "x ≥ 3",
        optionD: "x ≤ 3",
        correctOption: "B",
        subConcept: "Inequality Sign Reversal",
        explanation: "-2x ≥ 11 - 5 → -2x ≥ 6. Dividing by -2 reverses the inequality symbol: x ≤ -3.",
        remediationTip: "Dividing by a negative number flips ≥ to ≤."
      },
      {
        id: "q-shs1-m7b-2",
        quizId: "quiz-shs1-math-inequalities",
        questionText: "Which integers satisfy the compound inequality -2 < x ≤ 2?",
        optionA: "{-2, -1, 0, 1, 2}",
        optionB: "{-1, 0, 1, 2}",
        optionC: "{-1, 0, 1}",
        optionD: "{0, 1, 2}",
        correctOption: "B",
        subConcept: "Compound Inequalities Integer Set",
        explanation: "-2 is excluded (<), while 2 is included (≤). Integers are -1, 0, 1, 2.",
        remediationTip: "Strict < means do not include the endpoint."
      },
      {
        id: "q-shs1-m7b-3",
        quizId: "quiz-shs1-math-inequalities",
        questionText: "On a number line, how is the inequality x > 4 represented at x = 4?",
        optionA: "Solid shaded circle",
        optionB: "Open unshaded circle",
        optionC: "Square bracket",
        optionD: "Cross mark",
        correctOption: "B",
        subConcept: "Number Line Conventions",
        explanation: "Strict inequalities (> and <) use open unshaded circles, indicating that the boundary value is excluded.",
        remediationTip: "Open circle for > or <; solid circle for ≥ or ≤."
      },
      {
        id: "q-shs1-m7b-4",
        quizId: "quiz-shs1-math-inequalities",
        questionText: "Solve for y: (y + 1) / 3 > (y - 1) / 2.",
        optionA: "y < 5",
        optionB: "y > 5",
        optionC: "y < -5",
        optionD: "y > -5",
        correctOption: "A",
        subConcept: "Fractional Inequalities",
        explanation: "Multiply by 6: 2(y + 1) > 3(y - 1) → 2y + 2 > 3y - 3 → 5 > y → y < 5.",
        remediationTip: "2y - 3y > -3 - 2 → -y > -5 → y < 5."
      },
      {
        id: "q-shs1-m7b-5",
        quizId: "quiz-shs1-math-inequalities",
        questionText: "If 3x + 4 ≤ 19, what is the MAXIMUM integer value of x?",
        optionA: "4",
        optionB: "5",
        optionC: "6",
        optionD: "7",
        correctOption: "B",
        subConcept: "Maximum Integer Solution",
        explanation: "3x ≤ 15 → x ≤ 5. The largest integer satisfying x ≤ 5 is 5.",
        remediationTip: "x ≤ 5 includes 5 as the maximum."
      },
      {
        id: "q-shs1-m7b-6",
        quizId: "quiz-shs1-math-inequalities",
        questionText: "Solve the double inequality: -3 ≤ 2x - 1 < 7.",
        optionA: "-1 ≤ x < 4",
        optionB: "-2 ≤ x < 3",
        optionC: "-1 ≤ x < 3",
        optionD: "-2 ≤ x < 4",
        correctOption: "A",
        subConcept: "Solving Double Inequalities",
        explanation: "Add 1 to all three parts: -2 ≤ 2x < 8. Divide by 2: -1 ≤ x < 4.",
        remediationTip: "Perform operations on all 3 parts of the double inequality."
      },
      {
        id: "q-shs1-m7b-7",
        quizId: "quiz-shs1-math-inequalities",
        questionText: "Find the truth set of 4 - x < 2x - 5.",
        optionA: "{x : x < 3}",
        optionB: "{x : x > 3}",
        optionC: "{x : x > -3}",
        optionD: "{x : x < 1}",
        correctOption: "B",
        subConcept: "Truth Set Notation",
        explanation: "4 + 5 < 2x + x → 9 < 3x → 3 < x → x > 3. Truth set is {x : x > 3}.",
        remediationTip: "Collect variable terms on the side where coefficient stays positive."
      },
      {
        id: "q-shs1-m7b-8",
        quizId: "quiz-shs1-math-inequalities",
        questionText: "What is the smallest prime number that satisfies 2x - 5 ≥ 3?",
        optionA: "2",
        optionB: "3",
        optionC: "5",
        optionD: "7",
        correctOption: "C",
        subConcept: "Prime Number Inequality Solutions",
        explanation: "2x ≥ 8 → x ≥ 4. The smallest prime number greater than or equal to 4 is 5.",
        remediationTip: "Prime numbers: 2, 3, 5, 7, 11... If x ≥ 4, the smallest prime is 5."
      },
      {
        id: "q-shs1-m7b-9",
        quizId: "quiz-shs1-math-inequalities",
        questionText: "Solve for x: -4x < 16.",
        optionA: "x < -4",
        optionB: "x > -4",
        optionC: "x < 4",
        optionD: "x > 4",
        correctOption: "B",
        subConcept: "Division by Negative Scalar",
        explanation: "Dividing by -4 reverses < to >: x > -4.",
        remediationTip: "Dividing by -4 reverses < to >."
      },
      {
        id: "q-shs1-m7b-10",
        quizId: "quiz-shs1-math-inequalities",
        questionText: "If x is a positive integer and 3x - 2 < 10, how many elements are in the solution set?",
        optionA: "2",
        optionB: "3",
        optionC: "4",
        optionD: "5",
        correctOption: "B",
        subConcept: "Counting Integer Solutions",
        explanation: "3x < 12 → x < 4. Positive integers strictly less than 4 are {1, 2, 3}. That is 3 elements.",
        remediationTip: "Positive integers start at 1: {1, 2, 3}."
      }
    ]
  },

  // ==========================================
  // TOPIC 8: Simultaneous Linear Equations
  // ==========================================
  "shs1-math-t2-simultaneous-equations": {
    id: "quiz-shs1-math-simultaneous",
    topicId: "shs1-math-t2-simultaneous-equations",
    title: "Simultaneous Linear Equations Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m8b-1",
        quizId: "quiz-shs1-math-simultaneous",
        questionText: "If 2x + y = 7 and x - y = 2, find the value of x.",
        optionA: "2",
        optionB: "3",
        optionC: "4",
        optionD: "5",
        correctOption: "B",
        subConcept: "Elimination by Addition",
        explanation: "Add the two equations: 3x = 9 → x = 3.",
        remediationTip: "Add equations directly when variable terms have opposite signs (+y and -y)."
      },
      {
        id: "q-shs1-m8b-2",
        quizId: "quiz-shs1-math-simultaneous",
        questionText: "3 pens and 2 notebooks cost GH₵ 29. 1 pen and 2 notebooks cost GH₵ 19. Find the cost of one pen.",
        optionA: "GH₵ 3",
        optionB: "GH₵ 5",
        optionC: "GH₵ 7",
        optionD: "GH₵ 8",
        correctOption: "B",
        subConcept: "Simultaneous Cost Problem",
        explanation: "Subtract equations: (3p + 2n) - (p + 2n) = 29 - 19 → 2p = 10 → p = 5.",
        remediationTip: "Subtracting eliminates 2n."
      },
      {
        id: "q-shs1-m8b-3",
        quizId: "quiz-shs1-math-simultaneous",
        questionText: "Find y if 4x + 3y = 18 and x = 3.",
        optionA: "1",
        optionB: "2",
        optionC: "3",
        optionD: "4",
        correctOption: "B",
        subConcept: "Substitution Evaluation",
        explanation: "4(3) + 3y = 18 → 12 + 3y = 18 → 3y = 6 → y = 2.",
        remediationTip: "Substitute x = 3 directly."
      },
      {
        id: "q-shs1-m8b-4",
        quizId: "quiz-shs1-math-simultaneous",
        questionText: "Solve simultaneously: x + 2y = 8 and 3x - 2y = 8. What is the value of y?",
        optionA: "2",
        optionB: "4",
        optionC: "6",
        optionD: "0",
        correctOption: "A",
        subConcept: "Finding the Second Variable",
        explanation: "Add equations: 4x = 16 → x = 4. Substitute into Eq 1: 4 + 2y = 8 → 2y = 4 → y = 2.",
        remediationTip: "Always find both variables; the question asks for y."
      },
      {
        id: "q-shs1-m8b-5",
        quizId: "quiz-shs1-math-simultaneous",
        questionText: "If 2x - 3y = 1 and 3x + y = 7, find (x, y).",
        optionA: "(2, 1)",
        optionB: "(1, 2)",
        optionC: "(3, -1)",
        optionD: "(2, 3)",
        correctOption: "A",
        subConcept: "System Solution Pair",
        explanation: "Multiply Eq 2 by 3: 9x + 3y = 21. Add to Eq 1: 11x = 22 → x = 2. Then y = 7 - 3(2) = 1.",
        remediationTip: "Multiply to match coefficients of y, then add."
      },
      {
        id: "q-shs1-m8b-6",
        quizId: "quiz-shs1-math-simultaneous",
        questionText: "The sum of two numbers is 35 and their difference is 11. What is the smaller number?",
        optionA: "12",
        optionB: "14",
        optionC: "23",
        optionD: "24",
        correctOption: "A",
        subConcept: "Number Word Problem",
        explanation: "x + y = 35 and x - y = 11. Adding gives 2x = 46 → x = 23. Smaller number y = 35 - 23 = 12.",
        remediationTip: "Find both numbers (23 and 12) and select the smaller one."
      },
      {
        id: "q-shs1-m8b-7",
        quizId: "quiz-shs1-math-simultaneous",
        questionText: "If 5x + 2y = 16 and 3x + 2y = 12, find the value of x - y.",
        optionA: "-1",
        optionB: "0",
        optionC: "1",
        optionD: "-3",
        correctOption: "A",
        subConcept: "Evaluating Derived Simultaneous Expressions",
        explanation: "Subtract: 2x = 4 → x = 2. 5(2) + 2y = 16 → 10 + 2y = 16 → 2y = 6 → y = 3. Then x - y = 2 - 3 = -1.",
        remediationTip: "x = 2, y = 3. 2 - 3 = -1."
      },
      {
        id: "q-shs1-m8b-8",
        quizId: "quiz-shs1-math-simultaneous",
        questionText: "Which method is best suited when one variable has a coefficient of 1 (e.g. x + 4y = 9)?",
        optionA: "Elimination method",
        optionB: "Substitution method",
        optionC: "Trial and error",
        optionD: "Completing the square",
        correctOption: "B",
        subConcept: "Method Selection Strategy",
        explanation: "Substitution is most efficient because the variable can be isolated without introducing fractions (x = 9 - 4y).",
        remediationTip: "Isolate x = 9 - 4y directly."
      },
      {
        id: "q-shs1-m8b-9",
        quizId: "quiz-shs1-math-simultaneous",
        questionText: "Solve for x: 3x - y = 7 and 2x + 3y = 1.",
        optionA: "1",
        optionB: "2",
        optionC: "-1",
        optionD: "3",
        correctOption: "B",
        subConcept: "Elimination with Unequal Coefficients",
        explanation: "Multiply Eq 1 by 3: 9x - 3y = 21. Add to Eq 2: 11x = 22 → x = 2.",
        remediationTip: "Multiply first equation by 3 to eliminate y."
      },
      {
        id: "q-shs1-m8b-10",
        quizId: "quiz-shs1-math-simultaneous",
        questionText: "Two angles are supplementary (add to 180°). One angle is 40° larger than the other. What is the smaller angle?",
        optionA: "50°",
        optionB: "70°",
        optionC: "90°",
        optionD: "110°",
        correctOption: "B",
        subConcept: "Geometric Simultaneous Problem",
        explanation: "x + y = 180 and x - y = 40. 2x = 220 → x = 110°. Smaller angle y = 180 - 110 = 70°.",
        remediationTip: "Supplementary means sum is 180°."
      }
    ]
  },

  // ==========================================
  // TOPIC 9: Ratio, Proportion, Rates of Work & Commercial Percentages
  // ==========================================
  "shs1-math-t2-ratio-rates-percentages": {
    id: "quiz-shs1-math-ratio-rates",
    topicId: "shs1-math-t2-ratio-rates-percentages",
    title: "Ratio, Rates & Percentages Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m9b-1",
        quizId: "quiz-shs1-math-ratio-rates",
        questionText: "Share GH₵ 1,200 between Kofi and Ama in the ratio 3 : 5. What is Ama's share?",
        optionA: "GH₵ 450",
        optionB: "GH₵ 600",
        optionC: "GH₵ 750",
        optionD: "GH₵ 800",
        correctOption: "C",
        subConcept: "Ratio Division",
        explanation: "Total parts = 3 + 5 = 8. Ama = (5/8) × 1,200 = 5 × 150 = GH₵ 750.",
        remediationTip: "Ama's fraction is 5/8 of the total amount."
      },
      {
        id: "q-shs1-m9b-2",
        quizId: "quiz-shs1-math-ratio-rates",
        questionText: "If y is inversely proportional to x, and y = 8 when x = 3, find y when x = 6.",
        optionA: "4",
        optionB: "16",
        optionC: "12",
        optionD: "2",
        correctOption: "A",
        subConcept: "Inverse Proportion Constant",
        explanation: "xy = k = 8 × 3 = 24. When x = 6: y = 24 / 6 = 4.",
        remediationTip: "In inverse proportion, product xy is constant."
      },
      {
        id: "q-shs1-m9b-3",
        quizId: "quiz-shs1-math-ratio-rates",
        questionText: "A car travels 240 km in 3 hours. What is its average speed in km/h?",
        optionA: "70",
        optionB: "75",
        optionC: "80",
        optionD: "90",
        correctOption: "C",
        subConcept: "Average Speed Formula",
        explanation: "Speed = Distance / Time = 240 / 3 = 80 km/h.",
        remediationTip: "Divide distance by time."
      },
      {
        id: "q-shs1-m9b-4",
        quizId: "quiz-shs1-math-ratio-rates",
        questionText: "If 8 men can dig a trench in 6 days, how many days will 12 men take working at the same rate?",
        optionA: "3 days",
        optionB: "4 days",
        optionC: "5 days",
        optionD: "9 days",
        correctOption: "B",
        subConcept: "Inverse Rate of Work",
        explanation: "Total man-days = 8 × 6 = 48. Days for 12 men = 48 / 12 = 4 days.",
        remediationTip: "Man-days remain constant: 8 × 6 = 12 × d."
      },
      {
        id: "q-shs1-m9b-5",
        quizId: "quiz-shs1-math-ratio-rates",
        questionText: "An item originally priced at GH₵ 400 is discounted by 15%. What is the sale price?",
        optionA: "GH₵ 340",
        optionB: "GH₵ 350",
        optionC: "GH₵ 360",
        optionD: "GH₵ 385",
        correctOption: "A",
        subConcept: "Percentage Discount",
        explanation: "Discount = 15% of 400 = 60. Sale price = 400 - 60 = GH₵ 340 (or 400 × 0.85 = 340).",
        remediationTip: "Multiply by (1 - 0.15) = 0.85."
      },
      {
        id: "q-shs1-m9b-6",
        quizId: "quiz-shs1-math-ratio-rates",
        questionText: "Pipe A fills a tank in 4 hours and Pipe B fills it in 6 hours. How long will both take working together?",
        optionA: "2 hours",
        optionB: "2.4 hours",
        optionC: "5 hours",
        optionD: "10 hours",
        correctOption: "B",
        subConcept: "Combined Rates of Work",
        explanation: "Combined rate = 1/4 + 1/6 = 3/12 + 2/12 = 5/12 per hour. Time = 12/5 = 2.4 hours (2 hours 24 mins).",
        remediationTip: "Add rates (1/A + 1/B), then take reciprocal."
      },
      {
        id: "q-shs1-m9b-7",
        quizId: "quiz-shs1-math-ratio-rates",
        questionText: "A trader buys a television for GH₵ 1,500 and sells it for GH₵ 1,800. What is the percentage profit?",
        optionA: "15%",
        optionB: "16.7%",
        optionC: "20%",
        optionD: "25%",
        correctOption: "C",
        subConcept: "Percentage Profit on Cost Price",
        explanation: "Profit = 1,800 - 1,500 = 300. Percentage profit = (300 / 1,500) × 100% = 20%.",
        remediationTip: "Profit is always calculated over the COST price."
      },
      {
        id: "q-shs1-m9b-8",
        quizId: "quiz-shs1-math-ratio-rates",
        questionText: "If the ratio of boys to girls in a school is 4 : 5 and there are 240 boys, how many girls are there?",
        optionA: "192",
        optionB: "300",
        optionC: "320",
        optionD: "360",
        correctOption: "B",
        subConcept: "Proportional Scaling",
        explanation: "4 parts = 240 → 1 part = 60. Girls = 5 parts = 5 × 60 = 300.",
        remediationTip: "Divide 240 by 4 to get 1 part, then multiply by 5."
      },
      {
        id: "q-shs1-m9b-9",
        quizId: "quiz-shs1-math-ratio-rates",
        questionText: "Convert 72 km/h into meters per second (m/s).",
        optionA: "15 m/s",
        optionB: "20 m/s",
        optionC: "25 m/s",
        optionD: "30 m/s",
        correctOption: "B",
        subConcept: "Unit Conversion of Speed",
        explanation: "72 × (1,000 / 3,600) = 72 × (5/18) = 4 × 5 = 20 m/s.",
        remediationTip: "Multiply by 5/18 to convert km/h to m/s."
      },
      {
        id: "q-shs1-m9b-10",
        quizId: "quiz-shs1-math-ratio-rates",
        questionText: "After a 20% salary increase, Kwame earns GH₵ 3,600. What was his original salary?",
        optionA: "GH₵ 2,880",
        optionB: "GH₵ 3,000",
        optionC: "GH₵ 3,200",
        optionD: "GH₵ 3,400",
        correctOption: "B",
        subConcept: "Reverse Percentage",
        explanation: "Original × 1.20 = 3,600 → Original = 3,600 / 1.20 = GH₵ 3,000.",
        remediationTip: "Divide the new value by 1.20 (do NOT just subtract 20% of 3600)."
      }
    ]
  },

  // ==========================================
  // TOPIC 10: Change of Subject of Formula
  // ==========================================
  "shs1-math-t2-change-of-subject": {
    id: "quiz-shs1-math-change-subject",
    topicId: "shs1-math-t2-change-of-subject",
    title: "Change of Subject Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m10b-1",
        quizId: "quiz-shs1-math-change-subject",
        questionText: "Make r the subject of the formula: A = πr² (r > 0).",
        optionA: "r = √(A / π)",
        optionB: "r = A / π",
        optionC: "r = √(Aπ)",
        optionD: "r = (A / π)²",
        correctOption: "A",
        subConcept: "Isolating Squared Variable",
        explanation: "Divide by π: r² = A / π. Take square root: r = √(A / π).",
        remediationTip: "Divide by π first, then square root."
      },
      {
        id: "q-shs1-m10b-2",
        quizId: "quiz-shs1-math-change-subject",
        questionText: "Make t the subject of: v = u + at.",
        optionA: "t = (v - u) / a",
        optionB: "t = (v + u) / a",
        optionC: "t = a(v - u)",
        optionD: "t = v - u - a",
        correctOption: "A",
        subConcept: "Linear Formula Rearrangement",
        explanation: "Subtract u: at = v - u. Divide by a: t = (v - u) / a.",
        remediationTip: "Subtract u first, then divide by a."
      },
      {
        id: "q-shs1-m10b-3",
        quizId: "quiz-shs1-math-change-subject",
        questionText: "Make x the subject of: y = (2x + 1) / (x - 3).",
        optionA: "x = (3y + 1) / (y - 2)",
        optionB: "x = (3y - 1) / (y + 2)",
        optionC: "x = (2y + 1) / (y - 3)",
        optionD: "x = (y + 3) / (2y - 1)",
        correctOption: "A",
        subConcept: "Variable Appearing in Numerator and Denominator",
        explanation: "y(x - 3) = 2x + 1 → yx - 3y = 2x + 1 → yx - 2x = 3y + 1 → x(y - 2) = 3y + 1 → x = (3y + 1) / (y - 2).",
        remediationTip: "Clear denominator, group all x terms on one side, factor out x."
      },
      {
        id: "q-shs1-m10b-4",
        quizId: "quiz-shs1-math-change-subject",
        questionText: "Make h the subject of: V = 1/3 πr²h.",
        optionA: "h = 3V / (πr²)",
        optionB: "h = V / (3πr²)",
        optionC: "h = 3πr² / V",
        optionD: "h = √(3V / π)",
        correctOption: "A",
        subConcept: "Cone Volume Formula Rearrangement",
        explanation: "Multiply by 3: 3V = πr²h. Divide by πr²: h = 3V / (πr²).",
        remediationTip: "Multiply by 3 first: 3V = πr²h."
      },
      {
        id: "q-shs1-m10b-5",
        quizId: "quiz-shs1-math-change-subject",
        questionText: "Make L the subject of: T = 2π√(L / g).",
        optionA: "L = g(T / 2π)²",
        optionB: "L = (T / 2πg)²",
        optionC: "L = 2π√(Tg)",
        optionD: "L = gT² / 2π",
        correctOption: "A",
        subConcept: "Isolating Variable Under Square Root",
        explanation: "T / (2π) = √(L / g). Square both sides: (T / 2π)² = L / g. Multiply by g: L = g(T / 2π)² = gT² / (4π²).",
        remediationTip: "Isolate radical, square both sides, multiply by g."
      },
      {
        id: "q-shs1-m10b-6",
        quizId: "quiz-shs1-math-change-subject",
        questionText: "Make b the subject of: A = 1/2(a + b)h.",
        optionA: "b = (2A / h) - a",
        optionB: "b = (2A - a) / h",
        optionC: "b = 2A / (h - a)",
        optionD: "b = (A / 2h) - a",
        correctOption: "A",
        subConcept: "Trapezium Area Formula",
        explanation: "2A = (a + b)h → 2A / h = a + b → b = (2A / h) - a.",
        remediationTip: "Multiply by 2, divide by h, subtract a."
      },
      {
        id: "q-shs1-m10b-7",
        quizId: "quiz-shs1-math-change-subject",
        questionText: "If 1/f = 1/u + 1/v, make f the subject.",
        optionA: "f = u + v",
        optionB: "f = uv / (u + v)",
        optionC: "f = (u + v) / uv",
        optionD: "f = uv",
        correctOption: "B",
        subConcept: "Lens Formula Inversion",
        explanation: "1/f = (v + u) / uv. Taking reciprocal of both sides gives f = uv / (u + v).",
        remediationTip: "Combine fractions on RHS first, then invert."
      },
      {
        id: "q-shs1-m10b-8",
        quizId: "quiz-shs1-math-change-subject",
        questionText: "Make x the subject of: y = a - bx.",
        optionA: "x = (a - y) / b",
        optionB: "x = (y - a) / b",
        optionC: "x = (a + y) / b",
        optionD: "x = b(a - y)",
        correctOption: "A",
        subConcept: "Negative Variable Transposition",
        explanation: "bx = a - y → x = (a - y) / b.",
        remediationTip: "Add bx to left side to make it positive: bx + y = a."
      },
      {
        id: "q-shs1-m10b-9",
        quizId: "quiz-shs1-math-change-subject",
        questionText: "Make c the subject of: E = mc² (c > 0).",
        optionA: "c = √(E / m)",
        optionB: "c = E / m",
        optionC: "c = √(Em)",
        optionD: "c = (E / m)²",
        correctOption: "A",
        subConcept: "Einstein Mass-Energy Relation",
        explanation: "c² = E / m → c = √(E / m).",
        remediationTip: "Divide by m, then take square root."
      },
      {
        id: "q-shs1-m10b-10",
        quizId: "quiz-shs1-math-change-subject",
        questionText: "Make p the subject of: q = √(p² + r²).",
        optionA: "p = √(q² - r²)",
        optionB: "p = q - r",
        optionC: "p = √(q² + r²)",
        optionD: "p = q² - r²",
        correctOption: "A",
        subConcept: "Pythagorean Radical Rearrangement",
        explanation: "Square both sides: q² = p² + r² → p² = q² - r² → p = √(q² - r²).",
        remediationTip: "Square both sides: q² = p² + r², so p² = q² - r²."
      }
    ]
  },

  // ==========================================
  // TOPIC 11: Relations, Functions & Graphs
  // ==========================================
  "shs1-math-t2-relations-functions": {
    id: "quiz-shs1-math-relations-functions",
    topicId: "shs1-math-t2-relations-functions",
    title: "Relations & Functions Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m11b-1",
        quizId: "quiz-shs1-math-relations-functions",
        questionText: "Given f(x) = 4x - 7, what is the image of -3?",
        optionA: "-5",
        optionB: "-19",
        optionC: "5",
        optionD: "19",
        correctOption: "B",
        subConcept: "Function Evaluation",
        explanation: "f(-3) = 4(-3) - 7 = -12 - 7 = -19.",
        remediationTip: "Substitute x = -3."
      },
      {
        id: "q-shs1-m11b-2",
        quizId: "quiz-shs1-math-relations-functions",
        questionText: "Which of the following relations is a FUNCTION?",
        optionA: "{(1, 2), (1, 3), (2, 4)}",
        optionB: "{(2, 5), (3, 5), (4, 5)}",
        optionC: "{(0, 1), (0, 2), (0, 3)}",
        optionD: "{(3, 4), (3, 6), (5, 8)}",
        correctOption: "B",
        subConcept: "Definition of a Function",
        explanation: "In a function, no domain element can map to two distinct outputs. In B, every input (2, 3, 4) is unique.",
        remediationTip: "Check that no x value repeats with different y values."
      },
      {
        id: "q-shs1-m11b-3",
        quizId: "quiz-shs1-math-relations-functions",
        questionText: "If f(x) = 2x + 1 and f(k) = 15, find k.",
        optionA: "6",
        optionB: "7",
        optionC: "8",
        optionD: "9",
        correctOption: "B",
        subConcept: "Pre-image Calculation",
        explanation: "2k + 1 = 15 → 2k = 14 → k = 7.",
        remediationTip: "Equate expression to 15 and solve for k."
      },
      {
        id: "q-shs1-m11b-4",
        quizId: "quiz-shs1-math-relations-functions",
        questionText: "What is the domain of f(x) = 1 / (x - 5)?",
        optionA: "All real numbers except x = 5",
        optionB: "All real numbers except x = 0",
        optionC: "x > 5 only",
        optionD: "All real numbers",
        correctOption: "A",
        subConcept: "Domain of Rational Function",
        explanation: "Denominator cannot be 0, so x - 5 ≠ 0 → x ≠ 5.",
        remediationTip: "Exclude values that make the denominator zero."
      },
      {
        id: "q-shs1-m11b-5",
        quizId: "quiz-shs1-math-relations-functions",
        questionText: "If f(x) = x² - 3x, find f(-2).",
        optionA: "2",
        optionB: "10",
        optionC: "-2",
        optionD: "-10",
        correctOption: "B",
        subConcept: "Quadratic Function Evaluation",
        explanation: "f(-2) = (-2)² - 3(-2) = 4 + 6 = 10.",
        remediationTip: "(-2)² = +4 and -3 × (-2) = +6."
      },
      {
        id: "q-shs1-m11b-6",
        quizId: "quiz-shs1-math-relations-functions",
        questionText: "What is the range of f(x) = 2x for domain D = {1, 2, 3}?",
        optionA: "{1, 2, 3}",
        optionB: "{2, 4, 6}",
        optionC: "{3, 4, 5}",
        optionD: "{2, 3, 4}",
        correctOption: "B",
        subConcept: "Range from Discrete Domain",
        explanation: "f(1)=2, f(2)=4, f(3)=6. Range is {2, 4, 6}.",
        remediationTip: "Calculate image for each member of the domain."
      },
      {
        id: "q-shs1-m11b-7",
        quizId: "quiz-shs1-math-relations-functions",
        questionText: "What test is used on a graph to determine if it represents a function?",
        optionA: "Horizontal line test",
        optionB: "Vertical line test",
        optionC: "Parallel line test",
        optionD: "Perpendicular line test",
        correctOption: "B",
        subConcept: "Vertical Line Test",
        explanation: "If any vertical line intersects the graph at more than one point, the graph is NOT a function.",
        remediationTip: "Vertical lines test if an input x has multiple outputs y."
      },
      {
        id: "q-shs1-m11b-8",
        quizId: "quiz-shs1-math-relations-functions",
        questionText: "If f(x) = 3x - 2 and g(x) = x + 4, find f(g(1)).",
        optionA: "13",
        optionB: "15",
        optionC: "17",
        optionD: "5",
        correctOption: "A",
        subConcept: "Composite Function Evaluation",
        explanation: "g(1) = 1 + 4 = 5. Then f(5) = 3(5) - 2 = 15 - 2 = 13.",
        remediationTip: "Evaluate inner function g(1) first, then plug into f."
      },
      {
        id: "q-shs1-m11b-9",
        quizId: "quiz-shs1-math-relations-functions",
        questionText: "What is the y-intercept of the function f(x) = 5x - 8?",
        optionA: "5",
        optionB: "-8",
        optionC: "8",
        optionD: "8/5",
        correctOption: "B",
        subConcept: "y-intercept from Function",
        explanation: "At y-intercept, x = 0: f(0) = 5(0) - 8 = -8.",
        remediationTip: "Set x = 0 to find the y-intercept."
      },
      {
        id: "q-shs1-m11b-10",
        quizId: "quiz-shs1-math-relations-functions",
        questionText: "If f: x → ax + 3 and f(2) = 11, find the value of a.",
        optionA: "2",
        optionB: "4",
        optionC: "5",
        optionD: "7",
        correctOption: "B",
        subConcept: "Finding Function Parameter",
        explanation: "2a + 3 = 11 → 2a = 8 → a = 4.",
        remediationTip: "Set 2a + 3 = 11."
      }
    ]
  },

  // ==========================================
  // TOPIC 12: Variation (Direct, Inverse, Joint & Partial)
  // ==========================================
  "shs1-math-t2-variation": {
    id: "quiz-shs1-math-variation",
    topicId: "shs1-math-t2-variation",
    title: "Variation Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m12b-1",
        quizId: "quiz-shs1-math-variation",
        questionText: "If y varies directly as x², and y = 12 when x = 2, find y when x = 3.",
        optionA: "18",
        optionB: "27",
        optionC: "36",
        optionD: "48",
        correctOption: "B",
        subConcept: "Direct Variation with Powers",
        explanation: "y = kx² → 12 = k(2²) = 4k → k = 3. When x = 3: y = 3(3²) = 3(9) = 27.",
        remediationTip: "Find constant k = 3 first, then multiply by 3² = 9."
      },
      {
        id: "q-shs1-m12b-2",
        quizId: "quiz-shs1-math-variation",
        questionText: "Which equation represents 'z varies directly as x and inversely as the square root of y'?",
        optionA: "z = kx√y",
        optionB: "z = kx / √y",
        optionC: "z = k√y / x",
        optionD: "z = k / (x√y)",
        correctOption: "B",
        subConcept: "Joint Variation Formulation",
        explanation: "Directly as x places x in numerator; inversely as √y places √y in denominator: z = kx / √y.",
        remediationTip: "Direct goes in numerator, inverse in denominator."
      },
      {
        id: "q-shs1-m12b-3",
        quizId: "quiz-shs1-math-variation",
        questionText: "P is partly constant and partly varies as q. Which formula represents this partial variation?",
        optionA: "P = kq",
        optionB: "P = c + kq",
        optionC: "P = c / kq",
        optionD: "P = ckq",
        correctOption: "B",
        subConcept: "Partial Variation Form",
        explanation: "Partly constant (c) and partly varies as q (kq) is written as P = c + kq.",
        remediationTip: "Partial variation combines a constant term plus a variation term."
      },
      {
        id: "q-shs1-m12b-4",
        quizId: "quiz-shs1-math-variation",
        questionText: "If y varies inversely as x, what happens to y when x is DOUBLED?",
        optionA: "y is doubled",
        optionB: "y is halved",
        optionC: "y is quadrupled",
        optionD: "y remains unchanged",
        correctOption: "B",
        subConcept: "Inverse Variation Behavior",
        explanation: "Since y = k/x, replacing x with 2x gives y_new = k / (2x) = (1/2)y. y is halved.",
        remediationTip: "In inverse variation, doubling the input halves the output."
      },
      {
        id: "q-shs1-m12b-5",
        quizId: "quiz-shs1-math-variation",
        questionText: "V varies jointly as h and r². If V = 150 when h = 2 and r = 5, find constant k.",
        optionA: "2",
        optionB: "3",
        optionC: "5",
        optionD: "6",
        correctOption: "B",
        subConcept: "Joint Variation Constant",
        explanation: "V = k·h·r² → 150 = k(2)(5²) = k(2)(25) = 50k → k = 150 / 50 = 3.",
        remediationTip: "150 = 50k → k = 3."
      },
      {
        id: "q-shs1-m12b-6",
        quizId: "quiz-shs1-math-variation",
        questionText: "If y varies directly as x, and y = 15 when x = 5, what is the value of x when y = 24?",
        optionA: "6",
        optionB: "8",
        optionC: "10",
        optionD: "12",
        correctOption: "B",
        subConcept: "Direct Variation Solving for x",
        explanation: "y = kx → 15 = 5k → k = 3. When y = 24: 24 = 3x → x = 8.",
        remediationTip: "k = 3. Then x = 24 / 3 = 8."
      },
      {
        id: "q-shs1-m12b-7",
        quizId: "quiz-shs1-math-variation",
        questionText: "In partial variation C = a + bn, C = 50 when n = 10, and C = 70 when n = 20. Find constant b.",
        optionA: "2",
        optionB: "3",
        optionC: "5",
        optionD: "10",
        correctOption: "A",
        subConcept: "Partial Variation Simultaneous System",
        explanation: "a + 10b = 50 and a + 20b = 70. Subtract: 10b = 20 → b = 2.",
        remediationTip: "Subtract equations to eliminate constant a."
      },
      {
        id: "q-shs1-m12b-8",
        quizId: "quiz-shs1-math-variation",
        questionText: "If p varies inversely as the square of q, by what factor does p change if q is multiplied by 3?",
        optionA: "p is multiplied by 3",
        optionB: "p is multiplied by 9",
        optionC: "p is divided by 9",
        optionD: "p is divided by 3",
        correctOption: "C",
        subConcept: "Inverse Square Variation",
        explanation: "p = k / q². If q becomes 3q, denominator becomes (3q)² = 9q². Thus p is divided by 9.",
        remediationTip: "Square the factor 3 to get 9 in the denominator."
      },
      {
        id: "q-shs1-m12b-9",
        quizId: "quiz-shs1-math-variation",
        questionText: "If y is directly proportional to (x + 1), and y = 12 when x = 2, find y when x = 5.",
        optionA: "20",
        optionB: "24",
        optionC: "28",
        optionD: "30",
        correctOption: "B",
        subConcept: "Linear Shift Variation",
        explanation: "y = k(x + 1) → 12 = k(2 + 1) = 3k → k = 4. When x = 5: y = 4(5 + 1) = 4(6) = 24.",
        remediationTip: "Remember to add 1 before multiplying by k: 4 × 6 = 24."
      },
      {
        id: "q-shs1-m12b-10",
        quizId: "quiz-shs1-math-variation",
        questionText: "What type of variation describes electrical resistance R = ρL / A where ρ is constant?",
        optionA: "Direct variation only",
        optionB: "Inverse variation only",
        optionC: "Joint variation",
        optionD: "Partial variation",
        correctOption: "C",
        subConcept: "Classifying Variation Types",
        explanation: "R varies directly as length L and inversely as area A; this combination is Joint Variation.",
        remediationTip: "Combining direct and inverse components constitutes joint variation."
      }
    ]
  },

  // ==========================================
  // TOPIC 13: Plane Geometry I: Angles & Parallel Lines
  // ==========================================
  "shs1-math-t3-plane-geometry-angles": {
    id: "quiz-shs1-math-angles",
    topicId: "shs1-math-t3-plane-geometry-angles",
    title: "Angles & Parallel Lines Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m13b-1",
        quizId: "quiz-shs1-math-angles",
        questionText: "Two parallel lines are cut by a transversal. If one interior angle is 65°, what is its co-interior (allied) angle?",
        optionA: "65°",
        optionB: "115°",
        optionC: "125°",
        optionD: "295°",
        correctOption: "B",
        subConcept: "Co-interior Angles",
        explanation: "Co-interior angles lie between parallel lines on the same side of the transversal and sum to 180°: 180° - 65° = 115°.",
        remediationTip: "Co-interior angles add up to 180°."
      },
      {
        id: "q-shs1-m13b-2",
        quizId: "quiz-shs1-math-angles",
        questionText: "What geometric relationship makes 'Z-angles' between parallel lines equal?",
        optionA: "Vertically opposite angles",
        optionB: "Alternate interior angles",
        optionC: "Corresponding angles",
        optionD: "Supplementary angles",
        correctOption: "B",
        subConcept: "Alternate Interior Angles",
        explanation: "Z-shaped angles formed between parallel lines and a transversal are alternate interior angles and are always equal.",
        remediationTip: "Alternate angles form a Z-shape and are equal."
      },
      {
        id: "q-shs1-m13b-3",
        quizId: "quiz-shs1-math-angles",
        questionText: "The angles on a straight line are (2x)°, (3x)°, and 40°. Find the value of x.",
        optionA: "20°",
        optionB: "28°",
        optionC: "32°",
        optionD: "35°",
        correctOption: "B",
        subConcept: "Angles on a Straight Line",
        explanation: "2x + 3x + 40 = 180 → 5x = 140 → x = 28°.",
        remediationTip: "Angles on a straight line sum to 180°."
      },
      {
        id: "q-shs1-m13b-4",
        quizId: "quiz-shs1-math-angles",
        questionText: "Two vertically opposite angles are given by (4x - 10)° and (2x + 30)°. Find x.",
        optionA: "10°",
        optionB: "15°",
        optionC: "20°",
        optionD: "25°",
        correctOption: "C",
        subConcept: "Vertically Opposite Angles",
        explanation: "4x - 10 = 2x + 30 → 2x = 40 → x = 20°.",
        remediationTip: "Vertically opposite angles are equal."
      },
      {
        id: "q-shs1-m13b-5",
        quizId: "quiz-shs1-math-angles",
        questionText: "What is the sum of angles around a single point?",
        optionA: "90°",
        optionB: "180°",
        optionC: "270°",
        optionD: "360°",
        correctOption: "D",
        subConcept: "Angles at a Point",
        explanation: "Angles meeting at a common vertex completing a full rotation sum to 360°.",
        remediationTip: "A complete circle around a point is 360°."
      },
      {
        id: "q-shs1-m13b-6",
        quizId: "quiz-shs1-math-angles",
        questionText: "If two angles are complementary, their sum is:",
        optionA: "45°",
        optionB: "90°",
        optionC: "180°",
        optionD: "360°",
        correctOption: "B",
        subConcept: "Complementary Angles Definition",
        explanation: "Complementary angles sum to 90°. Supplementary angles sum to 180°.",
        remediationTip: "Complementary = 90°; Supplementary = 180°."
      },
      {
        id: "q-shs1-m13b-7",
        quizId: "quiz-shs1-math-angles",
        questionText: "In an isosceles triangle, the vertex angle is 40°. What is the measure of each base angle?",
        optionA: "40°",
        optionB: "70°",
        optionC: "80°",
        optionD: "140°",
        correctOption: "B",
        subConcept: "Isosceles Triangle Base Angles",
        explanation: "(180° - 40°) / 2 = 140° / 2 = 70° each.",
        remediationTip: "Base angles of an isosceles triangle are equal."
      },
      {
        id: "q-shs1-m13b-8",
        quizId: "quiz-shs1-math-angles",
        questionText: "Which letter pattern identifies CORRESPONDING angles formed by parallel lines?",
        optionA: "Z-pattern",
        optionB: "F-pattern",
        optionC: "C-pattern",
        optionD: "X-pattern",
        correctOption: "B",
        subConcept: "Corresponding Angles Visual",
        explanation: "Corresponding angles sit in the same relative position and form an F-pattern. They are equal.",
        remediationTip: "F-shape = Corresponding angles."
      },
      {
        id: "q-shs1-m13b-9",
        quizId: "quiz-shs1-math-angles",
        questionText: "An exterior angle of a triangle is 110°. If one opposite interior angle is 45°, what is the other opposite interior angle?",
        optionA: "45°",
        optionB: "55°",
        optionC: "65°",
        optionD: "70°",
        correctOption: "C",
        subConcept: "Exterior Angle of a Triangle Theorem",
        explanation: "Exterior angle = Sum of two opposite interior angles: 110° = 45° + x → x = 110° - 45° = 65°.",
        remediationTip: "Exterior angle equals the sum of the two opposite interior angles."
      },
      {
        id: "q-shs1-m13b-10",
        quizId: "quiz-shs1-math-angles",
        questionText: "If an angle is five times its complement, what is the angle?",
        optionA: "15°",
        optionB: "45°",
        optionC: "75°",
        optionD: "80°",
        correctOption: "C",
        subConcept: "Complementary Angles Algebraic Word Problem",
        explanation: "Let complement = x. Angle = 5x. 5x + x = 90° → 6x = 90° → x = 15°. Angle = 5(15°) = 75°.",
        remediationTip: "The angle is 5 × 15° = 75°."
      }
    ]
  },

  // ==========================================
  // TOPIC 14: Polygons (Interior & Exterior Angles)
  // ==========================================
  "shs1-math-t3-polygons": {
    id: "quiz-shs1-math-polygons",
    topicId: "shs1-math-t3-polygons",
    title: "Polygons Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m14b-1",
        quizId: "quiz-shs1-math-polygons",
        questionText: "What is the sum of the interior angles of a hexagon (6-sided polygon)?",
        optionA: "360°",
        optionB: "540°",
        optionC: "720°",
        optionD: "900°",
        correctOption: "C",
        subConcept: "Sum of Interior Angles",
        explanation: "Sum = (n - 2) × 180° = (6 - 2) × 180° = 4 × 180° = 720°.",
        remediationTip: "Formula: (n - 2) × 180°."
      },
      {
        id: "q-shs1-m14b-2",
        quizId: "quiz-shs1-math-polygons",
        questionText: "Each exterior angle of a regular polygon is 40°. How many sides does it have?",
        optionA: "8",
        optionB: "9",
        optionC: "10",
        optionD: "12",
        correctOption: "B",
        subConcept: "Sides of Regular Polygon",
        explanation: "n = 360° / exterior angle = 360° / 40° = 9 (nonagon).",
        remediationTip: "Divide 360° by the exterior angle."
      },
      {
        id: "q-shs1-m14b-3",
        quizId: "quiz-shs1-math-polygons",
        questionText: "Each interior angle of a regular polygon is 140°. Find the number of sides.",
        optionA: "8",
        optionB: "9",
        optionC: "10",
        optionD: "12",
        correctOption: "B",
        subConcept: "Interior to Exterior Conversion",
        explanation: "Exterior angle = 180° - 140° = 40°. Then n = 360° / 40° = 9 sides.",
        remediationTip: "Find exterior angle (180 - interior), then divide 360° by exterior angle."
      },
      {
        id: "q-shs1-m14b-4",
        quizId: "quiz-shs1-math-polygons",
        questionText: "What is the sum of the exterior angles of ANY convex polygon with 15 sides?",
        optionA: "360°",
        optionB: "540°",
        optionC: "1,800°",
        optionD: "2,340°",
        correctOption: "A",
        subConcept: "Sum of Exterior Angles Property",
        explanation: "The sum of exterior angles of ANY convex polygon is ALWAYS 360°, regardless of the number of sides.",
        remediationTip: "Exterior angle sum is always 360° for every polygon."
      },
      {
        id: "q-shs1-m14b-5",
        quizId: "quiz-shs1-math-polygons",
        questionText: "What is the name of a polygon with 8 sides?",
        optionA: "Heptagon",
        optionB: "Octagon",
        optionC: "Nonagon",
        optionD: "Decagon",
        correctOption: "B",
        subConcept: "Polygon Nomenclature",
        explanation: "An 8-sided polygon is an octagon. (7 is heptagon, 9 is nonagon, 10 is decagon).",
        remediationTip: "8 sides = Octagon."
      },
      {
        id: "q-shs1-m14b-6",
        quizId: "quiz-shs1-math-polygons",
        questionText: "If the interior angles of a pentagon are x°, 2x°, (x + 30)°, (2x - 10)°, and 100°, what is the value of x?",
        optionA: "50°",
        optionB: "60°",
        optionC: "70°",
        optionD: "80°",
        correctOption: "C",
        subConcept: "Solving for Polygon Angles",
        explanation: "Sum of pentagon interior angles = (5 - 2) × 180° = 540°. x + 2x + x + 30 + 2x - 10 + 100 = 540 → 6x + 120 = 540 → 6x = 420 → x = 70°.",
        remediationTip: "Equate the sum of angles to (5 - 2) × 180° = 540°."
      },
      {
        id: "q-shs1-m14b-7",
        quizId: "quiz-shs1-math-polygons",
        questionText: "What is each interior angle of a regular octagon?",
        optionA: "120°",
        optionB: "135°",
        optionC: "140°",
        optionD: "144°",
        correctOption: "B",
        subConcept: "Regular Octagon Interior Angle",
        explanation: "Exterior angle = 360° / 8 = 45°. Interior angle = 180° - 45° = 135°.",
        remediationTip: "Exterior = 45°; Interior = 180 - 45 = 135°."
      },
      {
        id: "q-shs1-m14b-8",
        quizId: "quiz-shs1-math-polygons",
        questionText: "How many diagonals can be drawn in a hexagon from all vertices?",
        optionA: "6",
        optionB: "9",
        optionC: "12",
        optionD: "15",
        correctOption: "B",
        subConcept: "Number of Diagonals Formula [n(n-3)/2]",
        explanation: "Diagonals = n(n - 3) / 2 = 6(3) / 2 = 9.",
        remediationTip: "Formula: n(n - 3) / 2."
      },
      {
        id: "q-shs1-m14b-9",
        quizId: "quiz-shs1-math-polygons",
        questionText: "If the ratio of interior angle to exterior angle of a regular polygon is 7 : 2, how many sides does it have?",
        optionA: "8",
        optionB: "9",
        optionC: "10",
        optionD: "12",
        correctOption: "B",
        subConcept: "Angle Ratio in Regular Polygons",
        explanation: "Interior + Exterior = 180°. 7 + 2 = 9 parts = 180° → 1 part = 20°. Exterior = 2 × 20° = 40°. Sides n = 360° / 40° = 9.",
        remediationTip: "Find the exterior angle first using the ratio parts."
      },
      {
        id: "q-shs1-m14b-10",
        quizId: "quiz-shs1-math-polygons",
        questionText: "Can a regular polygon have an interior angle of 155°?",
        optionA: "Yes, it has 12 sides",
        optionB: "No, because 360° is not divisible by the exterior angle 25°",
        optionC: "Yes, it has 15 sides",
        optionD: "No, because interior angles cannot exceed 150°",
        correctOption: "B",
        subConcept: "Testing Validity of Regular Polygons",
        explanation: "If interior is 155°, exterior = 180° - 155° = 25°. 360° / 25° = 14.4 (not an integer). A polygon cannot have a fractional number of sides.",
        remediationTip: "The number of sides n = 360 / exterior must be a whole integer."
      }
    ]
  },

  // ==========================================
  // TOPIC 15: Coordinate Geometry I: Straight Lines
  // ==========================================
  "shs1-math-t3-coordinate-geometry-1": {
    id: "quiz-shs1-math-coord-geom-1",
    topicId: "shs1-math-t3-coordinate-geometry-1",
    title: "Coordinate Geometry I Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m15b-1",
        quizId: "quiz-shs1-math-coord-geom-1",
        questionText: "What is the midpoint of the line segment joining P(-2, 5) and Q(4, 1)?",
        optionA: "(1, 3)",
        optionB: "(2, 6)",
        optionC: "(3, 2)",
        optionD: "(1, 2)",
        correctOption: "A",
        subConcept: "Midpoint Formula",
        explanation: "Midpoint = ((-2 + 4)/2, (5 + 1)/2) = (2/2, 6/2) = (1, 3).",
        remediationTip: "Average the x-values and average the y-values."
      },
      {
        id: "q-shs1-m15b-2",
        quizId: "quiz-shs1-math-coord-geom-1",
        questionText: "Find the gradient of the line passing through (1, -2) and (3, 4).",
        optionA: "1",
        optionB: "2",
        optionC: "3",
        optionD: "-3",
        correctOption: "C",
        subConcept: "Gradient Formula",
        explanation: "m = (4 - (-2)) / (3 - 1) = 6 / 2 = 3.",
        remediationTip: "m = (y₂ - y₁) / (x₂ - x₁)."
      },
      {
        id: "q-shs1-m15b-3",
        quizId: "quiz-shs1-math-coord-geom-1",
        questionText: "What is the y-intercept of the line 3x + 2y = 8?",
        optionA: "3",
        optionB: "4",
        optionC: "8",
        optionD: "-4",
        correctOption: "B",
        subConcept: "y-intercept Calculation",
        explanation: "Set x = 0: 2y = 8 → y = 4.",
        remediationTip: "At the y-intercept, x = 0."
      },
      {
        id: "q-shs1-m15b-4",
        quizId: "quiz-shs1-math-coord-geom-1",
        questionText: "Calculate the distance between points A(1, 2) and B(4, 6).",
        optionA: "3",
        optionB: "4",
        optionC: "5",
        optionD: "7",
        correctOption: "C",
        subConcept: "Distance Formula",
        explanation: "d = √[(4 - 1)² + (6 - 2)²] = √[3² + 4²] = √(9 + 16) = √25 = 5 units.",
        remediationTip: "d = √[(x₂ - x₁)² + (y₂ - y₁)²]."
      },
      {
        id: "q-shs1-m15b-5",
        quizId: "quiz-shs1-math-coord-geom-1",
        questionText: "What is the equation of a straight line with slope -2 passing through (0, 3)?",
        optionA: "y = 2x + 3",
        optionB: "y = -2x + 3",
        optionC: "y = -2x - 3",
        optionD: "2x + y = -3",
        correctOption: "B",
        subConcept: "Slope-Intercept Equation",
        explanation: "y = mx + c where m = -2 and c = 3: y = -2x + 3.",
        remediationTip: "y = mx + c directly applies when given slope and y-intercept."
      },
      {
        id: "q-shs1-m15b-6",
        quizId: "quiz-shs1-math-coord-geom-1",
        questionText: "Find the x-intercept of the line 4x - 3y = 12.",
        optionA: "3",
        optionB: "-3",
        optionC: "4",
        optionD: "-4",
        correctOption: "A",
        subConcept: "x-intercept Calculation",
        explanation: "At x-intercept, y = 0: 4x = 12 → x = 3.",
        remediationTip: "Set y = 0 to find x-intercept."
      },
      {
        id: "q-shs1-m15b-7",
        quizId: "quiz-shs1-math-coord-geom-1",
        questionText: "What is the gradient of any horizontal line parallel to the x-axis?",
        optionA: "0",
        optionB: "1",
        optionC: "-1",
        optionD: "Undefined",
        correctOption: "A",
        subConcept: "Horizontal Line Slope",
        explanation: "On a horizontal line, change in y is zero (Δy = 0), so slope m = 0 / Δx = 0.",
        remediationTip: "Horizontal lines have slope 0; vertical lines have undefined slope."
      },
      {
        id: "q-shs1-m15b-8",
        quizId: "quiz-shs1-math-coord-geom-1",
        questionText: "If the midpoint of segment AB is M(3, 4) and A is (1, 2), what are the coordinates of B?",
        optionA: "(2, 3)",
        optionB: "(5, 6)",
        optionC: "(4, 6)",
        optionD: "(5, 8)",
        correctOption: "B",
        subConcept: "Finding Endpoint from Midpoint",
        explanation: "(1 + x_b)/2 = 3 → 1 + x_b = 6 → x_b = 5. (2 + y_b)/2 = 4 → 2 + y_b = 8 → y_b = 6. B is (5, 6).",
        remediationTip: "Multiply midpoint by 2 and subtract point A."
      },
      {
        id: "q-shs1-m15b-9",
        quizId: "quiz-shs1-math-coord-geom-1",
        questionText: "Write the equation of the line passing through (2, 5) with gradient 3 in general form Ax + By + C = 0.",
        optionA: "3x - y - 1 = 0",
        optionB: "3x + y - 1 = 0",
        optionC: "3x - y + 1 = 0",
        optionD: "x - 3y + 13 = 0",
        correctOption: "A",
        subConcept: "General Form of Straight Line",
        explanation: "y - 5 = 3(x - 2) → y - 5 = 3x - 6 → 3x - y - 1 = 0.",
        remediationTip: "Rearrange to make the x-term positive: 3x - y - 1 = 0."
      },
      {
        id: "q-shs1-m15b-10",
        quizId: "quiz-shs1-math-coord-geom-1",
        questionText: "What is the gradient of a vertical line with equation x = 5?",
        optionA: "0",
        optionB: "5",
        optionC: "Undefined",
        optionD: "1",
        correctOption: "C",
        subConcept: "Vertical Line Slope",
        explanation: "For a vertical line, Δx = 0, which results in division by zero. The slope is undefined.",
        remediationTip: "Vertical lines have undefined gradient."
      }
    ]
  },

  // ==========================================
  // TOPIC 16: Mensuration I: Perimeter & Area of Plane Shapes
  // ==========================================
  "shs1-math-t3-mensuration-plane-shapes": {
    id: "quiz-shs1-math-mensuration-plane",
    topicId: "shs1-math-t3-mensuration-plane-shapes",
    title: "Mensuration of Plane Shapes Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m16b-1",
        quizId: "quiz-shs1-math-mensuration-plane",
        questionText: "Find the area of a trapezium with parallel sides of 8 cm and 14 cm and height 5 cm.",
        optionA: "45 cm²",
        optionB: "55 cm²",
        optionC: "60 cm²",
        optionD: "110 cm²",
        correctOption: "B",
        subConcept: "Area of Trapezium",
        explanation: "Area = 1/2(a + b)h = 1/2(8 + 14) × 5 = 11 × 5 = 55 cm².",
        remediationTip: "Average of parallel sides times perpendicular height."
      },
      {
        id: "q-shs1-m16b-2",
        quizId: "quiz-shs1-math-mensuration-plane",
        questionText: "A circular pizza has a diameter of 28 cm. Find its area (take π = 22/7).",
        optionA: "88 cm²",
        optionB: "616 cm²",
        optionC: "1,232 cm²",
        optionD: "2,464 cm²",
        correctOption: "B",
        subConcept: "Area of Circle",
        explanation: "Radius r = 14 cm. Area = πr² = (22/7) × 14 × 14 = 616 cm².",
        remediationTip: "Radius is half the diameter (r = 14 cm)."
      },
      {
        id: "q-shs1-m16b-3",
        quizId: "quiz-shs1-math-mensuration-plane",
        questionText: "What is the length of an arc of a circle of radius 14 cm subtending 90° at the center? (π = 22/7)",
        optionA: "11 cm",
        optionB: "22 cm",
        optionC: "44 cm",
        optionD: "88 cm",
        correctOption: "B",
        subConcept: "Arc Length",
        explanation: "Arc = (90/360) × 2πr = (1/4) × 2 × (22/7) × 14 = 22 cm.",
        remediationTip: "Arc length = (θ/360) × 2πr."
      },
      {
        id: "q-shs1-m16b-4",
        quizId: "quiz-shs1-math-mensuration-plane",
        questionText: "Find the perimeter of a sector of radius 7 cm with arc length 11 cm.",
        optionA: "18 cm",
        optionB: "25 cm",
        optionC: "32 cm",
        optionD: "39 cm",
        correctOption: "B",
        subConcept: "Sector Perimeter (Arc + 2r)",
        explanation: "Perimeter = Arc length + 2r = 11 + 2(7) = 11 + 14 = 25 cm.",
        remediationTip: "Always add the two straight radius edges: Perimeter = Arc + 2r."
      },
      {
        id: "q-shs1-m16b-5",
        quizId: "quiz-shs1-math-mensuration-plane",
        questionText: "Find the area of a parallelogram with base 12 cm and perpendicular height 7 cm.",
        optionA: "42 cm²",
        optionB: "84 cm²",
        optionC: "96 cm²",
        optionD: "168 cm²",
        correctOption: "B",
        subConcept: "Parallelogram Area",
        explanation: "Area = base × height = 12 × 7 = 84 cm².",
        remediationTip: "Area of parallelogram is base × height (do NOT divide by 2)."
      },
      {
        id: "q-shs1-m16b-6",
        quizId: "quiz-shs1-math-mensuration-plane",
        questionText: "Find the area of a rhombus whose diagonals measure 10 cm and 16 cm.",
        optionA: "80 cm²",
        optionB: "160 cm²",
        optionC: "52 cm²",
        optionD: "40 cm²",
        correctOption: "A",
        subConcept: "Rhombus Area from Diagonals",
        explanation: "Area = 1/2(d₁ × d₂) = 1/2(10 × 16) = 80 cm².",
        remediationTip: "Area of rhombus = half the product of its diagonals."
      },
      {
        id: "q-shs1-m16b-7",
        quizId: "quiz-shs1-math-mensuration-plane",
        questionText: "What is the area of a sector of radius 6 cm with central angle 60°? (Leave answer in terms of π)",
        optionA: "2π cm²",
        optionB: "6π cm²",
        optionC: "12π cm²",
        optionD: "36π cm²",
        correctOption: "B",
        subConcept: "Sector Area in Terms of π",
        explanation: "Area = (60/360) × π × 6² = (1/6) × 36π = 6π cm².",
        remediationTip: "Area = (θ/360) × πr²."
      },
      {
        id: "q-shs1-m16b-8",
        quizId: "quiz-shs1-math-mensuration-plane",
        questionText: "A right-angled triangle has legs of length 9 cm and 12 cm. What is its perimeter?",
        optionA: "36 cm",
        optionB: "30 cm",
        optionC: "42 cm",
        optionD: "54 cm",
        correctOption: "A",
        subConcept: "Right Triangle Perimeter with Pythagoras",
        explanation: "Hypotenuse = √(9² + 12²) = √(81 + 144) = √225 = 15 cm. Perimeter = 9 + 12 + 15 = 36 cm.",
        remediationTip: "Calculate the hypotenuse first using Pythagoras theorem."
      },
      {
        id: "q-shs1-m16b-9",
        quizId: "quiz-shs1-math-mensuration-plane",
        questionText: "If the area of a square is 144 cm², what is its perimeter?",
        optionA: "24 cm",
        optionB: "36 cm",
        optionC: "48 cm",
        optionD: "72 cm",
        correctOption: "C",
        subConcept: "Square Area to Perimeter",
        explanation: "Side s = √144 = 12 cm. Perimeter = 4s = 4 × 12 = 48 cm.",
        remediationTip: "Take square root of area to get side, then multiply by 4."
      },
      {
        id: "q-shs1-m16b-10",
        quizId: "quiz-shs1-math-mensuration-plane",
        questionText: "Find the area of an equilateral triangle of side length 6 cm.",
        optionA: "9√3 cm²",
        optionB: "18√3 cm²",
        optionC: "36√3 cm²",
        optionD: "18 cm²",
        correctOption: "A",
        subConcept: "Equilateral Triangle Area Formula",
        explanation: "Area = (√3 / 4)s² = (√3 / 4) × 36 = 9√3 cm².",
        remediationTip: "Formula: (√3 / 4)s²."
      }
    ]
  },

  // ==========================================
  // TOPIC 17: Statistics I: Data Collection, Presentation & Frequency Tables
  // ==========================================
  "shs1-math-t3-statistics-frequency-tables": {
    id: "quiz-shs1-math-statistics-1",
    topicId: "shs1-math-t3-statistics-frequency-tables",
    title: "Statistics I Quiz",
    timeLimitMinutes: 15,
    passScorePercentage: 70,
    questions: [
      {
        id: "q-shs1-m17b-1",
        quizId: "quiz-shs1-math-statistics-1",
        questionText: "Find the median of the dataset: 8, 3, 7, 2, 9, 4, 6.",
        optionA: "4",
        optionB: "6",
        optionC: "7",
        optionD: "8",
        correctOption: "B",
        subConcept: "Median of Odd Number of Values",
        explanation: "Sort ascending: 2, 3, 4, 6, 7, 8, 9. The middle (4th) number is 6.",
        remediationTip: "Always sort data in ascending order first."
      },
      {
        id: "q-shs1-m17b-2",
        quizId: "quiz-shs1-math-statistics-1",
        questionText: "In a school of 180 students, 45 walk to school. What is the angle representing this group on a pie chart?",
        optionA: "45°",
        optionB: "60°",
        optionC: "90°",
        optionD: "120°",
        correctOption: "C",
        subConcept: "Pie Chart Sector Angles",
        explanation: "Angle = (45 / 180) × 360° = (1/4) × 360° = 90°.",
        remediationTip: "Sector angle = (frequency / total) × 360°."
      },
      {
        id: "q-shs1-m17b-3",
        quizId: "quiz-shs1-math-statistics-1",
        questionText: "What is the mode of the dataset: 4, 5, 5, 6, 7, 7, 7, 8, 9?",
        optionA: "5",
        optionB: "6",
        optionC: "7",
        optionD: "8",
        correctOption: "C",
        subConcept: "Finding Mode",
        explanation: "7 occurs 3 times, which is more frequent than any other value.",
        remediationTip: "Mode is the value that appears most often."
      },
      {
        id: "q-shs1-m17b-4",
        quizId: "quiz-shs1-math-statistics-1",
        questionText: "Find the mean of the numbers: 12, 15, 18, 20, 25.",
        optionA: "16",
        optionB: "18",
        optionC: "19",
        optionD: "20",
        correctOption: "B",
        subConcept: "Arithmetic Mean",
        explanation: "Sum = 12 + 15 + 18 + 20 + 25 = 90. Mean = 90 / 5 = 18.",
        remediationTip: "Sum all numbers and divide by count."
      },
      {
        id: "q-shs1-m17b-5",
        quizId: "quiz-shs1-math-statistics-1",
        questionText: "What is the median of an EVEN number of values: 4, 7, 10, 14, 18, 22?",
        optionA: "10",
        optionB: "12",
        optionC: "14",
        optionD: "13.5",
        correctOption: "B",
        subConcept: "Median of Even Dataset",
        explanation: "Two middle numbers are 10 and 14. Median = (10 + 14) / 2 = 24 / 2 = 12.",
        remediationTip: "Average the two middle numbers for even sample sizes."
      },
      {
        id: "q-shs1-m17b-6",
        quizId: "quiz-shs1-math-statistics-1",
        questionText: "In a frequency table, the sum of frequencies ∑f represents:",
        optionA: "The highest score",
        optionB: "The total number of observations (data items)",
        optionC: "The mean score",
        optionD: "The class width",
        correctOption: "B",
        subConcept: "Frequency Table Properties",
        explanation: "∑f is the total count of all data values collected.",
        remediationTip: "Sum of frequencies equals the total sample size N."
      },
      {
        id: "q-shs1-m17b-7",
        quizId: "quiz-shs1-math-statistics-1",
        questionText: "What is the range of the numbers: 23, 11, 45, 8, 34, 19?",
        optionA: "34",
        optionB: "37",
        optionC: "45",
        optionD: "8",
        correctOption: "B",
        subConcept: "Statistical Range",
        explanation: "Range = Highest value - Lowest value = 45 - 8 = 37.",
        remediationTip: "Range = Maximum - Minimum."
      },
      {
        id: "q-shs1-m17b-8",
        quizId: "quiz-shs1-math-statistics-1",
        questionText: "Scores: 1, 2, 3 with frequencies 3, 5, 2. What is the mean score?",
        optionA: "1.8",
        optionB: "1.9",
        optionC: "2.0",
        optionD: "2.2",
        correctOption: "B",
        subConcept: "Mean from Frequency Table",
        explanation: "∑fx = (1×3) + (2×5) + (3×2) = 3 + 10 + 6 = 19. ∑f = 3 + 5 + 2 = 10. Mean = 19 / 10 = 1.9.",
        remediationTip: "Divide ∑fx by ∑f."
      },
      {
        id: "q-shs1-m17b-9",
        quizId: "quiz-shs1-math-statistics-1",
        questionText: "A pie chart sector has an angle of 120°. What fraction of the total data does it represent?",
        optionA: "1/4",
        optionB: "1/3",
        optionC: "1/2",
        optionD: "2/5",
        correctOption: "B",
        subConcept: "Pie Chart Fraction",
        explanation: "120° / 360° = 1/3.",
        remediationTip: "Divide the angle by 360° to find the fraction."
      },
      {
        id: "q-shs1-m17b-10",
        quizId: "quiz-shs1-math-statistics-1",
        questionText: "If the mean of five numbers 3, 7, 8, x, 12 is 8, find x.",
        optionA: "8",
        optionB: "10",
        optionC: "12",
        optionD: "14",
        correctOption: "B",
        subConcept: "Solving for Missing Value from Mean",
        explanation: "Sum = 5 × 8 = 40. 3 + 7 + 8 + x + 12 = 30 + x = 40 → x = 10.",
        remediationTip: "Total sum = Mean × Count. Then subtract the known numbers."
      }
    ]
  }
};


