// Ghanaian JHS 3 Ghanaian Language (Akuapem Twi) Quizzes
// Based on NaCCA / GES Common Core Programme (CCP) Curriculum
// 10 Topics × 10 Questions = 100 BECE-Standard Questions

import { TopicQuiz } from './types';

export const JHS3_TWI_QUIZZES: Record<string, TopicQuiz> = {
  "jhs3-twi-t1-kasammara-kasa-mfonin-nkyia": {
    "id": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
    "topicId": "jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
    "title": "Kasammara, Kasa Mfonin ne Nkyia Ahorow BECE Sɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-twi-t1-q1",
        "quizId": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
        "questionText": "Sɛ wokɔbɔɔ obi a ɔredi aduan anwummere a, nkyia a ɛfata sɛ wode ma no ne hefa?",
        "optionA": "Mema wo adwo",
        "optionB": "Kuta mu oo",
        "optionC": "Ayekoo adwuma",
        "optionD": "Akwaaba m'adamfo",
        "correctOption": "B",
        "subConcept": "Akan Nkyia Amammerɛ",
        "explanation": "Wɔ Akan amammerɛ mu, sɛ wokɔto obi a ɔrididi a, nkyia pɔtee a wɔde kyea no ne 'Kuta mu oo' anaa 'Meto wo aduane mu', na odidifo no nso bua sɛ 'Yaa-kuta'.",
        "remediationTip": "Kae sɛ Akanfo bu aduanedi sɛ biribi a obiara wɔ ho hokwan sɛ ɔkuta mu kɛse."
      },
      {
        "id": "jhs3-twi-t1-q2",
        "quizId": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
        "questionText": "Kasasu bɛn na ɛda adi wɔ kasamu yi mu: 'Kofi yɛ gyata wɔ agoprama no so'?",
        "optionA": "Kasatɔ (Metaphor)",
        "optionB": "Nsɛso (Simile)",
        "optionC": "Nipadwuma (Personification)",
        "optionD": "Kasammɔkwaa (Euphemism)",
        "correctOption": "A",
        "subConcept": "Kasa Mfonin",
        "explanation": "Kasatɔ (Metaphor) yɛ berɛ a wɔde biribi toto biribi foforɔ ho tẽẽ a wɔmfa 'sɛ' anaa 'te sɛ' nni dwuma. Wɔde gyata ato Kofi ho tẽẽ.",
        "remediationTip": "Nsɛso de 'sɛ' anaa 'te sɛ' toto ho; Kasatɔ de ka kyerɛ sɛ ɛno ankasa ne biribi no."
      },
      {
        "id": "jhs3-twi-t1-q3",
        "quizId": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
        "questionText": "Sɛ abofra kyea ne papa anɔpa sɛ 'Mema wo akye agya' a, mmuae bɛn na ɛfata sɛ papa no de bua no?",
        "optionA": "Yaa ason",
        "optionB": "Yaa ɔba",
        "optionC": "Yaa agya",
        "optionD": "Yaa anua",
        "correctOption": "B",
        "subConcept": "Nkyia Mmuae Ahorow",
        "explanation": "Sɛ abofra kyea ne maame anaa ne papa a, ɔpanyin no gye so sɛ 'Yaa ɔba' (gye sɛ wɔbɛbɔ ne nton anaa agya abusuakuw).",
        "remediationTip": "Agya gye so sɛ 'Yaa ɔba' kyerɛ ne ba."
      },
      {
        "id": "jhs3-twi-t1-q4",
        "quizId": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
        "questionText": "Kasasu a wɔde nipasu, nneyɛe anaa suban hyɛ biribi a ɛnni nkwa anaa aboa mu no, wɔfrɛ no dɛn?",
        "optionA": "Kasatɔ",
        "optionB": "Kasa-ntoboase",
        "optionC": "Nipadwuma (Personification)",
        "optionD": "Abɛbuo",
        "correctOption": "C",
        "subConcept": "Nipadwuma Nhwɛso",
        "explanation": "Nipadwuma (Personification) yɛ berɛ a wɔfa nipa nneyɛe te sɛ kasa, su, asaw hyɛ biribi a ɛnyɛ nipa mu, sɛ nhwɛso 'Mframa no suee anadwo no'.",
        "remediationTip": "Nipa + Dwuma = de nipa dwumadie ma abuabuo anaa nnoɔma afoforo."
      },
      {
        "id": "jhs3-twi-t1-q5",
        "quizId": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
        "questionText": "Kasamu a edidi so yi mu nea ɛwɔ he na ɛyɛ 'Nsɛso' (Simile) pa ara?",
        "optionA": "Kwaku yɛ abotokura wɔ fie ha.",
        "optionB": "Ama ho yɛ fɛ te sɛ nsoromma a ɛrehyerɛn.",
        "optionC": "Osuo no bo afuw kɛse nnɛ.",
        "optionD": "Nana ama ne nan so kɔ akuraa.",
        "correctOption": "B",
        "subConcept": "Nsɛso (Simile)",
        "explanation": "'Ama ho yɛ fɛ te sɛ nsoromma' yɛ Nsɛso efisɛ wɔde 'te sɛ' na ɛtotoo ho pefee.",
        "remediationTip": "Nsɛso (Simile) da adi pefee bere a wohu 'te sɛ' anaa 'sɛ'."
      },
      {
        "id": "jhs3-twi-t1-q6",
        "quizId": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
        "questionText": "Sɛ ɔbarima kɔbaabi na ɔkyea 'Mema mo akye' na obi bua no sɛ 'Yaa ason' a, dɛn na ɛno kyerɛ fa n'abusuakuw ho?",
        "optionA": "Ɔyɛ Aduana abusua mu nipa",
        "optionB": "Ɔyɛ Ɔyoko abusua mu nipa",
        "optionC": "Ɔyɛ Asona abusua mu nipa",
        "optionD": "Ɔyɛ Ɛkoɔna abusua mu nipa",
        "correctOption": "C",
        "subConcept": "Akanfo Nkyia Gyeso ne Abusua",
        "explanation": "Akan amammerɛ mu, 'Yaa ason' yɛ nkyia gyeso ma Asonafo, sɛnea 'Yaa beraku' gyina hɔ ma Asakyiri/Aduana.",
        "remediationTip": "Asonafo gyeso ne 'Yaa ason'."
      },
      {
        "id": "jhs3-twi-t1-q7",
        "quizId": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
        "questionText": "Sɛ wopɛ sɛ wokyea obi a ɔwɔ adwuma mu sɛ ɔreyɛ adwuma denneennen a, dɛn na wobɛka akyerɛ no?",
        "optionA": "Mema wo awiabere",
        "optionB": "Ayekoo",
        "optionC": "Kuta mu oo",
        "optionD": "Akwaaba",
        "correctOption": "B",
        "subConcept": "Adwuma Nkyia",
        "explanation": "'Ayekoo' ne nkyia koro pɛ a wɔde kyea adwumayɛfo, na wɔn nso gye so sɛ 'Yaa ayeh' anaa 'Yaa adwuma'.",
        "remediationTip": "Ayekoo kɔ ma obi a ɔreyɛ adwuma."
      },
      {
        "id": "jhs3-twi-t1-q8",
        "quizId": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
        "questionText": "Bere a Akanfo rekyea ɔpanyin anaa ahemfo no, suban bɛn na ɛfata sɛ woda no adi?",
        "optionA": "Hyɛ kyɛw na bɔ wo nsam gu wo bɔtɔ mu",
        "optionB": "Tutu wo kyɛw, pa wo ntoma bɔ wo basamu, na brɛ wo ho ase",
        "optionC": "Tene wo nsa kɔ n'anim na nante kɔ n'anim tẽẽ",
        "optionD": "Kasa denneennen na gyina ne nifa so",
        "correctOption": "B",
        "subConcept": "Obuo wɔ Nkyia mu",
        "explanation": "Wɔ Akan obuo amammerɛ mu, sɛ wode nkyia rema ɔpanyin anaa ɔhene a, wututu wo kyɛw, pa wo ntoma abasa so na wobɔ wo mu ase de kyerɛ anidaho ne obuo.",
        "remediationTip": "Ɔhene anim kɔ gye obuo: tutu kyɛw na pa ntoma."
      },
      {
        "id": "jhs3-twi-t1-q9",
        "quizId": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
        "questionText": "'Asuogya nhwiren no resaw wɔ mframa dinn no mu.' Kasasu bɛn na ɛwɔ kasamu yi mu?",
        "optionA": "Nipadwuma",
        "optionB": "Nsɛso",
        "optionC": "Kasatɔ",
        "optionD": "Anifere kasa",
        "correctOption": "A",
        "subConcept": "Nipadwuma Mfonin",
        "explanation": "Nhwiren nni nsa ne nan a ɛbɛsaw sɛ nipa, enti asaw a wɔde ama nhwiren no yɛ Nipadwuma (Personification).",
        "remediationTip": "Sɛ biribi a ɛnyɛ nipa yɛ ade a nipa nkutoo yɛ a, ɛyɛ Nipadwuma."
      },
      {
        "id": "jhs3-twi-t1-q10",
        "quizId": "quiz-jhs3-twi-t1-kasammara-kasa-mfonin-nkyia",
        "questionText": "Mfaso kɛse bɛn na ɛwɔ kasa mfonin ne nkyia pa a obi de di dwuma so wɔ Akanfo asetenam?",
        "optionA": "Ɛma nipa ho yɛ tan kɛse wɔ akuraa so",
        "optionB": "Ɛyɛ nyansa ne suban pa a ɛde nidi ne asomdwoe ba nnipa ntam",
        "optionC": "Ɛma obi to fam ntɛm wɔ nhoma sua mu",
        "optionD": "Ɛbrɛ ahotɔ ase wɔ adwumam",
        "correctOption": "B",
        "subConcept": "Nkyia ne Kasamfonin Mfaso",
        "explanation": "Kasa mfonin ma kasa yɛ dɛ na nkyia pa nso de obu, asomdwoe, ne nkabom ba mpɔtam hɔ.",
        "remediationTip": "Nkyia ne obu yɛ Akan suban pa a ɛka nnipa bɔ mu."
      }
    ]
  },
  "jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu": {
    "id": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
    "topicId": "jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
    "title": "Kasa Fãhorow: Adeyɔ, Edin, ne Nsianimu BECE Sɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-twi-t2-q1",
        "quizId": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
        "questionText": "Wɔ kasamu yi mu: 'Yaw twaa kɛtɛ kɛse no', asɛmfua bɛn na ɛyɛ Adeyɔ (Verb)?",
        "optionA": "Yaw",
        "optionB": "twaa",
        "optionC": "kɛtɛ",
        "optionD": "kɛse",
        "correctOption": "B",
        "subConcept": "Adeyɔ (Verbs)",
        "explanation": "'twaa' yɛ adeyɔ efisɛ ɛno na ɛkyerɛ dwuma anaa ade pɔtee a Yaw yɛe wɔ kasamu no mu.",
        "remediationTip": "Adeyɔ yɛ asɛmfua a ɛkyerɛ adeyɛ anaa nneyɛe."
      },
      {
        "id": "jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu-q2",
        "quizId": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
        "questionText": "Nsianimu a edi asɛmfua anim a wɔfrɛ no Enyinim-nsianimu (Prefix) no, wobɛhu bi wɔ asɛmfua bɛn mu?",
        "optionA": "mmofra",
        "optionB": "nhoma",
        "optionC": "kasafo",
        "optionD": "adwumayɛni",
        "correctOption": "A",
        "subConcept": "Nsianimu (Affixes)",
        "explanation": "Wɔ 'mmofra' mu no, 'm-' no yɛ enyinim nsianimu a ɛdane 'abofra' kɔ dodow kabea mu.",
        "remediationTip": "Enyinim nsianimu ba asɛmfua anim (te sɛ m-, n-, a-)."
      },
      {
        "id": "jhs3-twi-t2-q3",
        "quizId": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
        "questionText": "Asɛmfua a edidi so yi mu nea ɛwɔ he na ɛyɛ 'Edinpa' (Proper Noun)?",
        "optionA": "dua",
        "optionB": "Kumase",
        "optionC": "abofra",
        "optionD": "oguan",
        "correctOption": "B",
        "subConcept": "Edin Ahorow (Nouns)",
        "explanation": "'Kumase' yɛ edinpa efisɛ ɛyɛ beae pɔtee bi din a wɔde ahyɛase nkrataafua kɛse twerɛ.",
        "remediationTip": "Edinpa kyerɛ nipa din, beae din anaa berɛ pɔtee din."
      },
      {
        "id": "jhs3-twi-t2-q4",
        "quizId": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
        "questionText": "Edinkyerɛfo (Pronoun) bɛn na ɛfata sɛ yɛde si 'Kofi ne Ama' ananmu wɔ kasamu mu?",
        "optionA": "me",
        "optionB": "wo",
        "optionC": "ɔno",
        "optionD": "wɔn",
        "correctOption": "D",
        "subConcept": "Edinkyerɛfo (Pronouns)",
        "explanation": "'Kofi ne Ama' yɛ nnipa baanu (dodow), enti edinkyerɛfo a esi wɔn ananmu ne 'wɔn'.",
        "remediationTip": "Nnipa mmienu anaa nea ɛboro saa a obi nka ho gyina hɔ ma 'wɔn'."
      },
      {
        "id": "jhs3-twi-t2-q5",
        "quizId": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
        "questionText": "Adeyɛbɔkyerɛfo (Adverb) a ɛwɔ kasamu yi mu ne nea ɛwɔ he: 'Akosua nantee brɛoo kɔɔ fie'?",
        "optionA": "Akosua",
        "optionB": "nantee",
        "optionC": "brɛoo",
        "optionD": "fie",
        "correctOption": "C",
        "subConcept": "Adeyɛbɔkyerɛfo",
        "explanation": "'brɛoo' kyerɛ kwan anaa su a Akosua faa so nantee, enti ɛyɛ adeyɛbɔkyerɛfo a ɛkyerɛ ɔkwan a ade kɔɔ so.",
        "remediationTip": "Adeyɛbɔkyerɛfo kyerɛ sɛnea ade siie, berɛ a ɛsii, anaa faako a ɛsii."
      },
      {
        "id": "jhs3-twi-t2-q6",
        "quizId": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
        "questionText": "Sɛ yɛpɛ sɛ yɛyɛ adeyɔ 'kasa' kabea a ɛrekae (Negation) a, ɛbɛyɛ dɛn?",
        "optionA": "rekasa",
        "optionB": "kasae",
        "optionC": "nnkasa",
        "optionD": "bɛkasa",
        "correctOption": "C",
        "subConcept": "Adeyɔ Kabea a Ɛnkae",
        "explanation": "Wɔ Twi mu, sɛ yɛreyɛ kabea a ɛnkae (negative) a, yɛde 'n-' anaa 'm-' hyɛ adeyɔ no anim: kasa -> nnkasa / nkasa.",
        "remediationTip": "De 'n-' anaa 'm-' to adeyɔ anim ma ɛnyɛ kabea a ɛnkae."
      },
      {
        "id": "jhs3-twi-t2-q7",
        "quizId": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
        "questionText": "Wɔ kasamu yi mu: 'Me kɔmfo ba kura poma tenten', asɛmfua 'tenten' yɛ dɛn wɔ kasa fãhorow mu?",
        "optionA": "Edinkyerɛfo",
        "optionB": "Edin (Noun)",
        "optionC": "Adeyɔ (Verb)",
        "optionD": "Kyerɛfo / Edin-nkyerɛkyerɛmufo (Adjective)",
        "correctOption": "D",
        "subConcept": "Edin-nkyerɛkyerɛmufo (Adjectives)",
        "explanation": "'tenten' rekyerɛ poma no su ne ne tenten, enti ɛyɛ edin-nkyerɛkyerɛmufo (Adjective).",
        "remediationTip": "Edin-nkyerɛkyerɛmufo kyerɛ sɛnea edin bi te."
      },
      {
        "id": "jhs3-twi-t2-q8",
        "quizId": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
        "questionText": "Akyi-nsianimu (Suffix) a ɛkyerɛ nipa a ɔyɛ dwuma bi wɔ asɛmfua 'okuafo' mu ne hefa?",
        "optionA": "o-",
        "optionB": "kua",
        "optionC": "-fo",
        "optionD": "-ku",
        "correctOption": "C",
        "subConcept": "Akyi-nsianimu Dwumadie",
        "explanation": "'-fo' yɛ akyi-nsianimu a wɔka bɔ edin no akyi de kyerɛ nipa a ɔte beae bi anaa ɔyɛ adwuma bi (te sɛ okuafo, ɔkyerɛkyerɛfo).",
        "remediationTip": "Akyi-nsianimu ba asɛmfua akyi."
      },
      {
        "id": "jhs3-twi-t2-q9",
        "quizId": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
        "questionText": "Nkabomde (Conjunction) a ɛwɔ kasamu yi mu ne nea ɛwɔ he: 'Me baa fie nanso manhu obiara'?",
        "optionA": "Me",
        "optionB": "baa",
        "optionC": "nanso",
        "optionD": "obiara",
        "correctOption": "C",
        "subConcept": "Nkabomde (Conjunctions)",
        "explanation": "'nanso' yɛ nkabomde a ɛde kasamufã abien no kabɔ mu de kyerɛ nsonsonoe.",
        "remediationTip": "Nkabomde bom kasamufã ahorow abien anaa nea ɛboro saa."
      },
      {
        "id": "jhs3-twi-t2-q10",
        "quizId": "quiz-jhs3-twi-t2-kasa-fãhorow-adeyɔ-ne-nsianimu",
        "questionText": "Kabea bɛn na ɛda adi wɔ adeyɔ 'redidi' mu?",
        "optionA": "Mprempren kabea a ɛkɔ so (Present Continuous)",
        "optionB": "Dada kabea (Past Tense)",
        "optionC": "Daakye kabea (Future Tense)",
        "optionD": "Ahyɛde kabea (Imperative)",
        "correctOption": "A",
        "subConcept": "Adeyɔ Kabea Ahorow",
        "explanation": "Enyinim-nsianimu 're-' a ɛbata adeyɔ 'didi' ho no kyerɛ dwuma a ɛrekɔ so mprempren ara (Continuous Tense).",
        "remediationTip": "'re-' bata adeyɔ ho a ɛkyerɛ ade a ɛrekɔ so seesei."
      }
    ]
  },
  "jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa": {
    "id": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
    "topicId": "jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
    "title": "Kasamufã: Asɛntɔdwe, Asɛntwafo ne Asɛnyiwa BECE Sɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-twi-t3-q1",
        "quizId": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
        "questionText": "Asɛntɔdwe (Subject) a ɛwɔ kasamu yi mu ne nea ɛwɔ he: 'Akosua noaa fufuo dɛdɛɛdɛ anwummere yi'?",
        "optionA": "Akosua",
        "optionB": "noaa",
        "optionC": "fufuo",
        "optionD": "anwummere",
        "correctOption": "A",
        "subConcept": "Asɛntɔdwe (Subject)",
        "explanation": "Asɛntɔdwe yɛ nipa anaa biribi a kasamu no fa ne ho anaa nea ɔyɛɛ dwuma no. Akosua na ɔnoaa aduane no.",
        "remediationTip": "Bisa sɛ 'Hena na ɔyɛɛ adeyɔ no?' Nea obua ne Asɛntɔdwe."
      },
      {
        "id": "jhs3-twi-t3-q2",
        "quizId": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
        "questionText": "Wɔ kasamu koro no ara mu ('Akosua noaa fufuo dɛdɛɛdɛ'), asɛnyiwa tẽẽ (Direct Object) ne hefa?",
        "optionA": "Akosua",
        "optionB": "noaa",
        "optionC": "fufuo",
        "optionD": "dɛdɛɛdɛ",
        "correctOption": "C",
        "subConcept": "Asɛnyiwa Tẽẽ (Direct Object)",
        "explanation": "'fufuo' ne ade a adeyɔ 'noaa' no kɔtɔɔ so tẽẽ, enti ɛyɛ asɛnyiwa tẽẽ.",
        "remediationTip": "Asɛnyiwa tẽẽ bua asɛmbisa 'Dɛn na wɔyɛe?'"
      },
      {
        "id": "jhs3-twi-t3-q3",
        "quizId": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
        "questionText": "Asɛntwafo (Predicate) wɔ Akan kasamu mu kura nnoɔma bɛn pa ara?",
        "optionA": "Asɛntɔdwe nkutoo",
        "optionB": "Adeyɔ ne emu nkyerɛkyerɛmu/asɛnyiwa nyinaa",
        "optionC": "Nkabomde nkutoo",
        "optionD": "Edin nkutoo",
        "correctOption": "B",
        "subConcept": "Asɛntwafo Nkyerɛase",
        "explanation": "Asɛntwafo (Predicate) ne kasamu fã a edi asɛntɔdwe no akyi a adeyɔ ne asɛnyiwa anaa akyerɛkyerɛmufo hyɛ mu.",
        "remediationTip": "Asɛntwafo kyerɛ nea asɛntɔdwe no yɛe anaa nea ɛtoo no."
      },
      {
        "id": "jhs3-twi-t3-q4",
        "quizId": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
        "questionText": "Kasamu bɛn na ɛyɛ 'Kasamutie' (Simple Sentence)?",
        "optionA": "Kofi didii nanso wammee.",
        "optionB": "Ama kɔɔ sukuu nansa yi.",
        "optionC": "Sɛ osuo tɔ a, yɛbɛkɔ fie.",
        "optionD": "Kwadwo rekasa bere a ne nua resu.",
        "correctOption": "B",
        "subConcept": "Kasamutie Nhwɛso",
        "explanation": "'Ama kɔɔ sukuu nansa yi' kura asɛntɔdwe baako (Ama) ne adeyɔ koro pɛ (kɔɔ), enti ɛyɛ Kasamutie.",
        "remediationTip": "Kasamutie kura adeyɔfo koro pɛ a adwene a edi mu wom."
      },
      {
        "id": "jhs3-twi-t3-q5",
        "quizId": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
        "questionText": "Kasamu a ɛwɔ asɛnkoro titiriw ne asɛnketewa (subordinate clause) a ɛbata ho no, wɔfrɛ no dɛn?",
        "optionA": "Kasamutie",
        "optionB": "Kasamunkabom (Compound sentence)",
        "optionC": "Kasamudede (Complex sentence)",
        "optionD": "Kasamu a enni awiei",
        "correctOption": "C",
        "subConcept": "Kasamudede (Complex Sentence)",
        "explanation": "Kasamudede kura asɛn-titiriw (independent clause) baako ne asɛnketewa (dependent clause) baako anaa nea ɛboro saa.",
        "remediationTip": "Kasamudede kura asɛnketewa a entumi nnyina ne ho so."
      },
      {
        "id": "jhs3-twi-t3-q6",
        "quizId": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
        "questionText": "Wɔ kasamu yi mu: 'Papa maame no maa abofra no sika', asɛnyiwa a ɛntẽẽ (Indirect Object) ne hefa?",
        "optionA": "sika",
        "optionB": "maa",
        "optionC": "Papa maame no",
        "optionD": "abofra no",
        "correctOption": "D",
        "subConcept": "Asɛnyiwa a Ɛntẽẽ (Indirect Object)",
        "explanation": "'abofra no' ne nipa a ogyee sika no (recipient), enti ɔyɛ asɛnyiwa a ɛntẽẽ, bere a 'sika' yɛ asɛnyiwa tẽẽ.",
        "remediationTip": "Asɛnyiwa a ɛntẽẽ kyerɛ hena na adeyɛ no bae maa no."
      },
      {
        "id": "jhs3-twi-t3-q7",
        "quizId": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
        "questionText": "Kasamu bɛn na ɛyɛ 'Ahyɛde Kasamu' (Imperative sentence)?",
        "optionA": "So wokɔɔ sukuu nnɛ?",
        "optionB": "Due, m'adamfo pa!",
        "optionC": "Kɔ fie ntɛm seesei ara!",
        "optionD": "Kofi yɛ ɔkyerɛkyerɛfo wɔ kurow yi mu.",
        "correctOption": "C",
        "subConcept": "Kasamu Ahorow",
        "explanation": "'Kɔ fie ntɛm seesei ara!' yɛ ahyɛde a ɛrehyɛ obi ma ɔnyɛ biribi tẽẽ.",
        "remediationTip": "Ahyɛde kasamu de adeyɔ na efi ase tẽẽ de ma ahyɛde."
      },
      {
        "id": "jhs3-twi-t3-q8",
        "quizId": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
        "questionText": "Sɛnea yɛbɛyɛ na yɛahu kasamu bi asɛntɔdwe no, asɛmbisa bɛn na yɛbisa?",
        "optionA": "Hena anaa Dɛn na ɔyɛɛ adeyɔ no?",
        "optionB": "Ɛhefa na ade no kɔe?",
        "optionC": "Dɛn nti na ɛyɛ kɛse?",
        "optionD": "Da bɛn na ɔbɛba?",
        "correctOption": "A",
        "subConcept": "Asɛntɔdwe Hwehwɛ",
        "explanation": "Asɛntɔdwe yɛ adeyɔfo, enti sɛ wobisa 'Hena na ɔreyɛ' anaa 'Dɛn na ɛreyɛ' a, nea obua ne asɛntɔdwe no.",
        "remediationTip": "Asɛntɔdwe = Adwumayɛfo / Nea kasamu no fa ne ho."
      },
      {
        "id": "jhs3-twi-t3-q9",
        "quizId": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
        "questionText": "Kasamunkabom (Compound sentence) mu no, asɛnkoro abien no te sɛn?",
        "optionA": "Baako ntumi nnyina ne ho so koraa",
        "optionB": "Mmienu no nyinaa yɛ nsɛnkoro a emu biara tumi gyina ne ho so sɛ kasamu",
        "optionC": "Enni adeyɔ koraa wom",
        "optionD": "Edin baako pɛ na ɛbom yɛ adwuma",
        "correctOption": "B",
        "subConcept": "Kasamunkabom Su",
        "explanation": "Kasamunkabom yɛ nsɛn-titiriw (independent clauses) mmienu a nkabomde te sɛ 'nanso', 'na', 'enti' aka abɔ mu.",
        "remediationTip": "Kasamunkabom fã biara tumi gyina ne ho so."
      },
      {
        "id": "jhs3-twi-t3-q10",
        "quizId": "quiz-jhs3-twi-t3-kasamufã-asɛntɔdwe-ne-asɛnyiwa",
        "questionText": "Ahyɛnsode bɛn na ɛfata sɛ yɛde wie asɛmbisa kasamu?",
        "optionA": "Awiei ahyɛnsode / Pɔw (.)",
        "optionB": "Nteɛteɛmu ahyɛnsode (!)",
        "optionC": "Asɛmbisa ahyɛnsode (?)",
        "optionD": "Kɔma (,)",
        "correctOption": "C",
        "subConcept": "Ahyɛnsode Dwumadie",
        "explanation": "Asɛmbisa kasamu biara wie wɔ asɛmbisa ahyɛnsode (?) so.",
        "remediationTip": "Asɛmbisa ahyɛnsode (?) gyina hɔ ma asɛmbisa a wie."
      }
    ]
  },
  "jhs3-twi-t4-nkasafii-ne-kasasu-ahorow": {
    "id": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
    "topicId": "jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
    "title": "Nkasafii, Kasabebree ne Kasasu Ahorow BECE Sɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-twi-t4-q1",
        "quizId": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
        "questionText": "Sɛ Akanfo ka sɛ 'Nana kɔ akuraa' a, dɛn na ɛno kyerɛ tẽẽ?",
        "optionA": "Nana kɔtuu kwan kɔɔ akuraa bi so",
        "optionB": "Nana awu",
        "optionC": "Nana anya adwuma foforɔ",
        "optionD": "Nana rehyɛ ahemfie foforɔ",
        "correctOption": "B",
        "subConcept": "Nkasafii: Owuo Kasasu",
        "explanation": "Wɔ Akan amammerɛ mu, wɔmmɔ ɔhene wuo din tẽẽ. Wɔka sɛ 'Dua kɛse abu' anaa 'Nana kɔ akuraa' de da owuo adi wɔ nkasafii kwan so.",
        "remediationTip": "Wɔmfa kasapa nka ɔhene wuo; nkasafii na wɔde ka."
      },
      {
        "id": "jhs3-twi-t4-q2",
        "quizId": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
        "questionText": "Nkasafii 'Ne nsa ka fam' asekyerɛ ne dɛn?",
        "optionA": "Wanya sika pii",
        "optionB": "Ɔyɛ ɔbemfo",
        "optionC": "Ne ho akyere no anaa wahia",
        "optionD": "Ɔnte apɔw koraa",
        "correctOption": "C",
        "subConcept": "Nkasafii Asekyerɛ",
        "explanation": "'Ne nsa ka fam' kyerɛ sɛ nipa no anya ohia kɛse anaa ne sika ne n'ahode asã ma wayɛ mmɔborɔ.",
        "remediationTip": "Ne nsa ka fam = Wahia / Ohiani."
      },
      {
        "id": "jhs3-twi-t4-q3",
        "quizId": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
        "questionText": "Sɛ obi ka sɛ 'Ɔkɔ baabi pɔtee' anaa 'Ɔkɔ tiafi' a, nkasafii bɛn na ɔde redi dwuma?",
        "optionA": "Ɔrekɔ gua so akɔtɔ nnoɔma",
        "optionB": "Ɔrekɔ agyanan (toilet)",
        "optionC": "Ɔrekɔ asɔre",
        "optionD": "Ɔrekɔ n'adamfo fie",
        "correctOption": "B",
        "subConcept": "Nkasafii: Agyanan Kasasu",
        "explanation": "Akanfo mfa animtiaa nka agyanankɔ ho asɛm tẽẽ wɔ nipa anim; wɔka sɛ 'mekɔ baabi' anaa 'mekɔ kurotia'.",
        "remediationTip": "Nkasafii ma yɛkwati kasafĩ a ɛmfata nipa anim ka."
      },
      {
        "id": "jhs3-twi-t4-q4",
        "quizId": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
        "questionText": "Nkasafii 'N'ani abere' kyerɛ dɛn wɔ Akanfo kasa mu?",
        "optionA": "N'ani ayɛ kɔɔ efisɛ ɔnte apɔw",
        "optionB": "Wabɔ mmɔden kɛse anaa n'ani da nnoɔma so pa ara",
        "optionC": "Ɔpɛ asaw kɛse",
        "optionD": "Ɔnnkasa yiye",
        "correctOption": "B",
        "subConcept": "Nkasafii Asekyerɛ",
        "explanation": "'N'ani abere' kyerɛ sɛ obi ayɛ nsi, wabɔ mmɔden anaa n'ani da ade bi a ɔreyɛ so denneennen.",
        "remediationTip": "Ani a abere kyerɛ nsi, ahoɔden ne mmɔdenbɔ."
      },
      {
        "id": "jhs3-twi-t4-q5",
        "quizId": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
        "questionText": "Dɛn nti na Akanfo de Nkasafii (Euphemism) di dwuma wɔ wɔn nkɔmmɔbɔ mu?",
        "optionA": "Sɛnea ɛbɛyɛ na wɔbɛtoto nkurɔfo mfonin agu adiwo",
        "optionB": "Sɛnea ɛbɛma kasafĩ agyigya na abuade aboro so",
        "optionC": "Sɛnea wɔbɛkwati animguase, kasafĩ, na wɔada obuo ne amammere mu anidaho adi",
        "optionD": "Sɛnea wɔbɛpata aban ma wɔantua tow",
        "correctOption": "C",
        "subConcept": "Nkasafii Mfaso",
        "explanation": "Nkasafii yɛ ɔkwan a wɔfa so de kasa pa a ɛfata sesa nsɛm a ne ka yɛ ya anaa ɛfĩ, de kyerɛ obu ne anidaho.",
        "remediationTip": "Nkasafii ma obu kɔ soro na ɛkwati kasafĩ."
      },
      {
        "id": "jhs3-twi-t4-q6",
        "quizId": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
        "questionText": "Sɛ obi ka sɛ 'Ɔkɔɔ afikyifie na waguan' a, dɛn na ɛno ase kyerɛ?",
        "optionA": "Ɔkɔɔ agyanan",
        "optionB": "Ɔdwanee fii akono",
        "optionC": "Ɔrekɔ asu nsuo",
        "optionD": "Ɔreguare wɔ nsuwa mu",
        "correctOption": "A",
        "subConcept": "Nkasafii Ahorow",
        "explanation": "'Afikyifie' anaa 'duam' yɛ agyanan beae din a wɔde nkasafii bobɔ.",
        "remediationTip": "Afikyifie = Tiafi / Agyanan."
      },
      {
        "id": "jhs3-twi-t4-q7",
        "quizId": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
        "questionText": "Nkasafii 'Ɔretu n'anan mu' kyerɛ dɛn?",
        "optionA": "Ɔrenante anaa ɔretu kwan",
        "optionB": "Ɔresawe",
        "optionC": "Ne nan abu",
        "optionD": "Ɔte fie baako pɛ",
        "correctOption": "A",
        "subConcept": "Nkasafii ne Kasabebree",
        "explanation": "'Tu n'anan mu' kyerɛ sɛ obi renante anaa ɔrehuruhuru kɔ baabi ntɛmntɛm.",
        "remediationTip": "Tu anan mu = Nante ntɛm."
      },
      {
        "id": "jhs3-twi-t4-q8",
        "quizId": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
        "questionText": "Sɛ obi ka sɛ 'Ɔbea no afu wo' anaa 'Ɔbea no kura afuru' a, nkasafii pa a Akanfo de si ananmu ne dɛn?",
        "optionA": "Ɔbea no adidi pii",
        "optionB": "Ɔbea no nyinsɛn (ɔyɛ banyinsɛnfo)",
        "optionC": "Ɔbea no nsa ka fam",
        "optionD": "Ɔbea no yare kɛse",
        "correctOption": "B",
        "subConcept": "Nkasafii wɔ Awo mu",
        "explanation": "'Nyinsɛn' yɛ asɛm a wɔmfa animtiaa nka no sɛ 'wafu wo'; wɔka sɛ 'ɔyɛ banyinsɛnfo' anaa 'ne ho te sɛ obi a ɔwɔ awotwaa mu'.",
        "remediationTip": "Nkasafii wɔ awo mu da obuo kɛse adi ma mmea."
      },
      {
        "id": "jhs3-twi-t4-q9",
        "quizId": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
        "questionText": "Kasasu a wɔde di dwuma bere a wɔrekasa akyerɛ ɔhene wɔ ahemfie no, wɔfrɛ no dɛn?",
        "optionA": "Mmɔfra kasa",
        "optionB": "Ahemfie kasa / Kasa pa a obu hyɛ mu",
        "optionC": "Gua so kasa",
        "optionD": "Atirimuɔden kasa",
        "correctOption": "B",
        "subConcept": "Kasa Nhyehyɛe (Registers)",
        "explanation": "Ahemfie kasa yɛ kasasu titiriw a ɛkura anidaho, nkasafii ne abɛbuo kɛse a wɔde kasa kyerɛ nananom ahemfo.",
        "remediationTip": "Ahemfie kasa da obuo ne anidaho a ɛwɔ soro kɛse adi."
      },
      {
        "id": "jhs3-twi-t4-q10",
        "quizId": "quiz-jhs3-twi-t4-nkasafii-ne-kasasu-ahorow",
        "questionText": "Sɛ obi ka sɛ 'Wadidi n'atem' a, nea ɛkyerɛ ne dɛn?",
        "optionA": "Wayɛ aduan kɛse ama no",
        "optionB": "Wabɔ no ahohora anaa wayeyaw no",
        "optionC": "Wama no akatua kɛse",
        "optionD": "Wabɔ no mpae",
        "correctOption": "B",
        "subConcept": "Nkasafii Asekyerɛ",
        "explanation": "'Didi atem' kyerɛ sɛ obi ayeyaw ne yɔnko anaa waka nsɛmmɔne akyerɛ no.",
        "remediationTip": "Didi atem = Yeyaw obi / Kasa bɔne kyerɛ obi."
      }
    ]
  },
  "jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa": {
    "id": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
    "topicId": "jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
    "title": "Mmɛ ne Abɛbuo mu Nyansa BECE Sɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-twi-t5-q1",
        "quizId": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
        "questionText": "To ɛbɛ yi toa so: 'Tikoro nnkɔ ______.'",
        "optionA": "agyina",
        "optionB": "asɔre",
        "optionC": "adwuma",
        "optionD": "akuraa",
        "correctOption": "A",
        "subConcept": "Akan Mmɛ a Wɔatoa So",
        "explanation": "Ɛbɛ no ne: 'Tikoro nnkɔ agyina'. Ɛkyerɛ sɛ onipa baako pɛ ntumi nsi gyinae a ɛmu pi a obi foforɔ nka ho.",
        "remediationTip": "Tikoro nnkɔ agyina kyerɛ nkabom ne afotu a obi gye fi n'afɛfo hɔ."
      },
      {
        "id": "jhs3-twi-t5-q2",
        "quizId": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
        "questionText": "Nyansa bɛn na ɛhyɛ ɛbɛ yi mu: 'Abofra hu ne nsa hohoro a, ɔne mpanyimfo didi'?",
        "optionA": "Sɛ abofra yɛ kɛse a, ɔbɛnya sika",
        "optionB": "Suban pa, anidaho ne obuo de nidi brɛ abofra ma mpanyimfo bu no",
        "optionC": "Ɛsɛ sɛ abofra di aduan bere biara",
        "optionD": "Mpanyimfo pɛ aduanedi sen mmɔfra",
        "correctOption": "B",
        "subConcept": "Abɛbuo mu Nyansa",
        "explanation": "Ɛbɛ yi kyerɛ sɛ sɛ abofra bɔ ne bra yiye na obu mpanyimfo a, ɔbɛnya nidi ne anuonyam wɔ mpanyimfo anim.",
        "remediationTip": "Nsa hohoro gyina hɔ ma suban pa ne anidaho."
      },
      {
        "id": "jhs3-twi-t5-q3",
        "quizId": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
        "questionText": "Ɛbɛ 'Dua baako gye mframa a, ɛbu' kyerɛ dɛn?",
        "optionA": "Mframaden kɛse betumi abu mfuw nyinaa",
        "optionB": "Nkabom ne baakoyɛ ma ahoɔden, nanso baakofo de, ɔto fam ntɛm",
        "optionC": "Dua a ɛyɛ duru ntumi nnyina",
        "optionD": "Ɛnyɛ papa sɛ yebetwa nnuaba",
        "correctOption": "B",
        "subConcept": "Nkabom Ho Mmɛ",
        "explanation": "Ɛbɛ yi kyerɛ baakoyɛ ho mfaso. Sɛ nnuadua bebree bom gyina a, mframa ntumi mmu wɔn, nanso dua baako de, ɛbɛbu ntɛm.",
        "remediationTip": "Dua baako = baakofo; mframa bu no ntɛm."
      },
      {
        "id": "jhs3-twi-t5-q4",
        "quizId": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
        "questionText": "To ɛbɛ yi toa so: 'Wosum borɔferɛ a, na ______.'",
        "optionA": "wosum kwadu",
        "optionB": "wudi bi",
        "optionC": "wutwa bi",
        "optionD": "wofifi bi",
        "correctOption": "A",
        "subConcept": "Akan Mmɛ Nhyehyɛe",
        "explanation": "Ɛbɛ no kɔ so sɛ: 'Wosum borɔferɛ a, na wosum kwadu.' Ɛkyerɛ nnipa mmienu a wɔbɔ mu yɛ biribi de botae koro pɛ pɛ mfaso.",
        "remediationTip": "Wosum borɔferɛ a, na wosum kwadu."
      },
      {
        "id": "jhs3-twi-t5-q5",
        "quizId": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
        "questionText": "Ɛbɛ bɛn na ɛkyerɛ sɛ 'Akwantuo ma onipa hunu nnoɔma bebree na ɔnya nyansa'?",
        "optionA": "Akokɔ nante na sɛ oprepre a, na ne nan bewu",
        "optionB": "Anomaa a ɔntu nua, onhu baabi a aburoo bere",
        "optionC": "Baabi a asukɔ nni no, anomaa nsuo mu na wɔnɔm",
        "optionD": "Kwaterekwa se ɔbɛma wo ntoma a, tie ne din",
        "correctOption": "B",
        "subConcept": "Nyansapɛ Ho Mmɛ",
        "explanation": "'Anomaa a ɔntu nua, onhu baabi a aburoo bere' kyerɛ sɛ onipa a ɔntu kwan nhwehwɛ adwene nnya nyansa kɛse te sɛ nea watu kwan ahu wiase.",
        "remediationTip": "Akwantuo ma nyansa = Anomaa a ontu..."
      },
      {
        "id": "jhs3-twi-t5-q6",
        "quizId": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
        "questionText": "To ɛbɛ yi toa so: 'Obi nnim a, ______.'",
        "optionA": "obi yera",
        "optionB": "obi kyerɛ",
        "optionC": "obi bisa",
        "optionD": "obi kɔ",
        "correctOption": "B",
        "subConcept": "Akan Mmɛ a Wɔatoa So",
        "explanation": "'Obi nnim a, obi kyerɛ' yɛ ɛbɛ a ɛkyerɛ sɛ nhomasua ne nkyerɛkyerɛ yɛ ade a ɛho hia onipa asetenam.",
        "remediationTip": "Obi nnim a, obi kyerɛ."
      },
      {
        "id": "jhs3-twi-t5-q7",
        "quizId": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
        "questionText": "Ɛbɛ 'Kwaterekwa se ɔbɛma wo ntoma a, tie ne din' asekyerɛ pa ara ne dɛn?",
        "optionA": "Kwaterekwa kura ntoma pii wɔ ne dan mu",
        "optionB": "Sɛ obi a onni hwee hyɛ wo bɔ a, hwɛ ne tebea ansa na woagye no adi",
        "optionC": "Ɛsɛ sɛ wogye kyɛfa biara fi obiara hɔ",
        "optionD": "Ntoma yɛ ade a ɛsom bo kɛse",
        "correctOption": "B",
        "subConcept": "Abɛbuo Asekyerɛ",
        "explanation": "Kwaterekwa nni ntoma a ɔhyɛ mpo, enti sɛ ɔse ɔbɛma wo ntoma a, ɛsɛ sɛ wuhun sɛ ɔntumi nyɛ biribi a ɔnni bi.",
        "remediationTip": "Kwaterekwa nni ntoma; n'ahyɛbɔ nni fam."
      },
      {
        "id": "jhs3-twi-t5-q8",
        "quizId": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
        "questionText": "Wɔ Akan asɛnni ne kasa mu, mfaso bɛn na ɛbɛ bu ma kasamafo?",
        "optionA": "Ɛma kasa no yɛ kusuu a emu nna hɔ",
        "optionB": "Ɛkata nyansa so na ɛyɛ asɛm no dɛ de ma atiefo te asɛm no ase ntɛm",
        "optionC": "Ɛkasa tia ahemfo kɛse",
        "optionD": "Ɛbrɛ obi suban ase koraa",
        "correctOption": "B",
        "subConcept": "Abɛbuo Mfaso",
        "explanation": "Akanfo ka sɛ: 'Abɛbuo ne kɛtɛ a wɔde sa asɛm.' Ɛma kasa no yɛ dɛ, de nyansa to gua, na ɛma atiefo nya asuade.",
        "remediationTip": "Abɛbuo ma kasa yɛ dɛ na ɛhyɛ asɛm mu dzen."
      },
      {
        "id": "jhs3-twi-t5-q9",
        "quizId": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
        "questionText": "To ɛbɛ yi toa so: 'Hu m'ani so mma me, ne ______.'",
        "optionA": "ɔbaatan pa",
        "optionB": "enti na atwe mmienu nam",
        "optionC": "adwuma pa",
        "optionD": "ahoɔden pa",
        "correctOption": "B",
        "subConcept": "Akan Mmɛ Nhyehyɛe",
        "explanation": "Ɛbɛ no ne: 'Hu m'ani so mma me, enti na atwe mmienu nam.' Ɛkyerɛ mmoa ne boa a nnipa mmienu de ma wɔn ho wɔn ho.",
        "remediationTip": "Hu m'ani so mma me = Mmoaboro ne nkabom."
      },
      {
        "id": "jhs3-twi-t5-q10",
        "quizId": "quiz-jhs3-twi-t5-mmɛ-ne-abɛbuo-mu-nyansa",
        "questionText": "Sɛ obi ka ɛbɛ bi kyerɛ mpanyimfo a, kasa pa bɛn na ɛfata sɛ ɔka de hyɛ ase de bu obu?",
        "optionA": "Mpanin se meka sɛ...",
        "optionB": "Mpanin mbu bɛ kɛkɛ na...",
        "optionC": "Mpanimfo se mebɔ mo mmarato na...",
        "optionD": "Mpanin se ɛbɛ nni nidi enti...",
        "correctOption": "B",
        "subConcept": "Abɛbuo Kasa Mmara",
        "explanation": "Akanfo amammerɛ mu, sɛ abofra anaa kasamafo rebu bɛ wɔ mpanyimfo anim a, ɔka sɛ 'Mpanin mbu bɛ kɛkɛ...' anaa 'Mpanin se sɛbe o...'.",
        "remediationTip": "Bu obu bere a worebu bɛ wɔ mpanyimfo anim."
      }
    ]
  },
  "jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow": {
    "id": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
    "topicId": "jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
    "title": "Nsɛmtwerɛ ne Nkrataatwerɛ Ahorow BECE Sɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-twi-t6-q1",
        "quizId": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
        "questionText": "Adrɛs (Address) ahe na ɛsɛ sɛ ɛba Adwuma krataa (Formal Letter) atifi?",
        "optionA": "Adrɛs baako pɛ wɔ nifa so",
        "optionB": "Adrɛs abien: otwerɛfo adrɛs wɔ nifa so, na ogyefo de wɔ benkum so",
        "optionC": "Adrɛs mmiɛnsa",
        "optionD": "Enni adrɛs koraa",
        "correctOption": "B",
        "subConcept": "Adwuma Krataa Nhyehyɛe",
        "explanation": "Adwuma krataa (Formal letter) kura adrɛs ahorow abien: otwerɛfo dea wɔ atifi nifa so, na ogyefo no dea nso wɔ benkum so wɔ otwerɛfo de akyi.",
        "remediationTip": "Adwuma krataa = adrɛs 2; Adamfofa krataa = adrɛs 1."
      },
      {
        "id": "jhs3-twi-t6-q2",
        "quizId": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
        "questionText": "Nsɛmtwerɛ (Essay) biara mu no, afã titiriw mmiɛnsa bɛn na ɛwom?",
        "optionA": "Ahyɛase, Emu Nsɛmtitiriw, ne Awiei",
        "optionB": "Adrɛs, Nkyia, ne Edin",
        "optionC": "Kasatɔ, Nsɛso, ne Abɛbuo",
        "optionD": "Asɛntɔdwe, Adeyɔ, ne Asɛnyiwa",
        "correctOption": "A",
        "subConcept": "Nsɛmtwerɛ Afãhorow",
        "explanation": "Nsɛmtwerɛ biara kura: Mfiase (Introduction), Emu nsɛmtitiriw (Body paragraphs), ne Awiei/Nkwaemuka (Conclusion).",
        "remediationTip": "Nsɛmtwerɛ kura mfiase, emu nsɛm, ne awiei a edi mu."
      },
      {
        "id": "jhs3-twi-t6-q3",
        "quizId": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
        "questionText": "Nkyia bɛn na ɛfata sɛ wode hyɛ Adamfofa krataa (Informal letter) ase?",
        "optionA": "Owura a ɔsom bo,",
        "optionB": "M'adamfo pa Kwame,",
        "optionC": "Adwuma sohwɛfo,",
        "optionD": "Ɔpanyin a ɔhyɛ aban mu,",
        "correctOption": "B",
        "subConcept": "Adamfofa Krataa Nkyia",
        "explanation": "'M'adamfo pa Kwame,' yɛ nkyia a ɛyɛ dɛ na ɛfata adamfofa krataa efisɛ otwerɛfo ne ogyefo yɛ nnamfo.",
        "remediationTip": "Adamfofa krataa kura nkyia a obu ne ahokeka wom kyerɛ adamfo."
      },
      {
        "id": "jhs3-twi-t6-q4",
        "quizId": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
        "questionText": "Awiei bɛn na ɛfata sɛ wode wie Adwuma krataa (Formal letter)?",
        "optionA": "Mene w'adamfo pa a medɔ wo,",
        "optionB": "Mene wo somfo nokwafo,",
        "optionC": "Kyea wo maame ma me,",
        "optionD": "Yɛbɛhyia daakye,",
        "correctOption": "B",
        "subConcept": "Adwuma Krataa Awiei",
        "explanation": "'Mene wo somfo nokwafo,' (Yours faithfully / sincerely) na wɔde wie adwuma krataa de kyerɛ obu ne animuonyam.",
        "remediationTip": "Adwuma krataa wie de 'Mene wo somfo nokwafo' anaa 'Mene wo nkoa'."
      },
      {
        "id": "jhs3-twi-t6-q5",
        "quizId": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
        "questionText": "Nsɛmtwerɛ a otwerɛfo gyina nnyinaso so si faako a ɔwɔ fa asɛm bi ho kyerɛ nnoɔma pa ne bɔne no, wɔfrɛ no dɛn?",
        "optionA": "Akyinnyegye Nsɛmtwerɛ (Argumentative / Debate)",
        "optionB": "Nkyerɛkyerɛmu Nsɛmtwerɛ (Descriptive)",
        "optionC": "Abakɔsɛm Nsɛmtwerɛ (Narrative)",
        "optionD": "Krataa a wɔtwerɛ kɔma adamfo",
        "correctOption": "A",
        "subConcept": "Akyinnyegye Nsɛmtwerɛ",
        "explanation": "Akyinnyegye nsɛmtwerɛ yɛ nea otwerɛfo kura adwene pɔtee bi na ɔde nnyinaso pii si so de twe atiefo ma wogye ne nsusuwii di.",
        "remediationTip": "Akyinnyegye = gyina fã baako so na ma nnyinaso a emu yɛ den."
      },
      {
        "id": "jhs3-twi-t6-q6",
        "quizId": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
        "questionText": "Asɛmfua titiriw a ɛwɔ nkyekyem biara mfiase a ɛkyerɛ adwene titiriw a ɛwɔ saa nkyekyem no mu no, wɔfrɛ no dɛn?",
        "optionA": "Kasatɔ",
        "optionB": "Asɛntitiriw Kasamu (Topic Sentence)",
        "optionC": "Asɛnketewa",
        "optionD": "Nkabomde",
        "correctOption": "B",
        "subConcept": "Nkyekyem Nhyehyɛe",
        "explanation": "Topic sentence (Asɛntitiriw kasamu) ne kasamu a ɛkyerɛ adwene titiriw a nkyekyem no mu nsɛm nyinaa bɛbɔ ho ban.",
        "remediationTip": "Asɛntitiriw kasamu da adwene titiriw a ɛwɔ nkyekyem no mu adi."
      },
      {
        "id": "jhs3-twi-t6-q7",
        "quizId": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
        "questionText": "Bere a woretwerɛ Twi kasa mu nsɛm no, baabi bɛn na Kɔma (,) ho hia pa ara?",
        "optionA": "Kasamu biara a ewie pɛɛ",
        "optionB": "Sɛ worepaapae nnoɔma bebree mu wɔ kasamu mu anaa woregye w'ahome",
        "optionC": "Bere a worebisa asɛm kɛse",
        "optionD": "Krataa no atifi nkutoo",
        "correctOption": "B",
        "subConcept": "Kasammara Ahyɛnsode Dwumadie",
        "explanation": "Kɔma (,) ma ahomegye ketewaa wɔ kasamu mu na ɛpaapae din ne nnoɔma a ɛtoatoa so mu.",
        "remediationTip": "Kɔma = ahomegye ketewa ne nnoɔma mpaepaemu."
      },
      {
        "id": "jhs3-twi-t6-q8",
        "quizId": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
        "questionText": "Nsɛmtwerɛ bɛn na ɛkasa kyerɛ sɛnea beae bi te, sɛnea obi suban ne ne ho te ma atiefo tumi de wɔn adwene hu mfonin no?",
        "optionA": "Nkyerɛkyerɛmu Nsɛmtwerɛ (Descriptive Essay)",
        "optionB": "Akyinnyegye Nsɛmtwerɛ",
        "optionC": "Amannebɔ Krataa",
        "optionD": "Nkrasɛm Ketewa",
        "correctOption": "A",
        "subConcept": "Nkyerɛkyerɛmu Nsɛmtwerɛ",
        "explanation": "Descriptive essay kyerɛkyerɛ beae, nipa, anaa ade bi su mu pɛpɛɛpɛ ma atiefo tumi fa wɔn adwene hu no yiye.",
        "remediationTip": "Nkyerɛkyerɛmu nsɛmtwerɛ de kasa mfonin ne nkyerɛkyerɛmu to gua."
      },
      {
        "id": "jhs3-twi-t6-q9",
        "quizId": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
        "questionText": "Sɛ wotwerɛ adwuma krataa a, asɛmti (Heading / Title) no te sɛn?",
        "optionA": "Ɛsɛ sɛ wɔde nkrataafua nketewa koraa twerɛ",
        "optionB": "Ɛsɛ sɛ ɛda nkyia no akyi, wɔtwerɛ no nkrataafua akɛse mu na wɔtease ase",
        "optionC": "Wɔntwerɛ asɛmti koraa wɔ adwuma krataa mu",
        "optionD": "Wɔde to krataa no awiei pɔtee",
        "correctOption": "B",
        "subConcept": "Adwuma Krataa Asɛmti",
        "explanation": "Wɔ adwuma krataa mu, asɛmti ba nkyia no akyi, wɔtwerɛ no nkrataafua akɛse mu (Capital letters) na wɔtease ase (underline).",
        "remediationTip": "Asɛmti wɔ adwuma krataa mu da nkyia akyi na wɔtease ase."
      },
      {
        "id": "jhs3-twi-t6-q10",
        "quizId": "quiz-jhs3-twi-t6-nsɛmtwerɛ-nkrataa-ahorow",
        "questionText": "Mfaso titiriw a ɛwɔ so sɛ obi nim krataatwerɛ ne nsɛmtwerɛ pa wɔ Twi mu ne dɛn?",
        "optionA": "Ɛbɛma watumi atu n'adamfo fo wɔ aban mu nkutoo",
        "optionB": "Ɛbɛma watumi ada n'adwene ne Akan nyansa adi pefee wɔ twerɛ mu na wadi nkonim wɔ WAEC BECE mu",
        "optionC": "Ɛbɛma watumi asua borɔfo kasa nkutoo",
        "optionD": "Ɛbɛma obiara abu no sɛ ɔkyerɛkyerɛfo wɔ sukuupɔn mu",
        "correctOption": "B",
        "subConcept": "Krataatwerɛ Mfaso",
        "explanation": "Twi nsɛmtwerɛ pa ma osuani nya nimdeɛ a ɛkorɔn wɔ n'ankasa kasa mu, kura amammerɛ mu, na odi nkonim wɔ BECE nsɔhwɛ mu.",
        "remediationTip": "Krataatwerɛ pa ma nkontabuo ne nimdeɛ kɔ anim."
      }
    ]
  },
  "jhs3-twi-t7-amammere-bragoro-ne-babadinto": {
    "id": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
    "topicId": "jhs3-twi-t7-amammere-bragoro-ne-babadinto",
    "title": "Akan Amammerɛ: Bragoro ne Babadinto BECE Sɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-twi-t7-q1",
        "quizId": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
        "questionText": "Da bɛn na Akanfo taa to abofra a wɔawo no foforɔ din wɔ amammerɛ kwan so?",
        "optionA": "Da a wɔwoo no no ara",
        "optionB": "Nnawɔtwe akyi (Da a ɛto so awɔtwe)",
        "optionC": "Bosome a edi kan akyi",
        "optionD": "Afe baako akyi",
        "correctOption": "B",
        "subConcept": "Babadinto Berɛ",
        "explanation": "Akanfo to abofra din wɔ da a ɛto so awɔtwe (nnawɔtwe akyi) efisɛ wogye di sɛ abofra no atena fam afi abɔfra yare ne asamando nsɛm mu.",
        "remediationTip": "Babadinto ba nnawɔtwe akyi (da a ɛto so 8)."
      },
      {
        "id": "jhs3-twi-t7-q2",
        "quizId": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
        "questionText": "Nnoɔma abien bɛn na wɔde sɔ abofra tɛkrɛma so wɔ dintoɔ amanne mu de kyerɛ nokwaredi?",
        "optionA": "Nsuo ne Nsa",
        "optionB": "Asikyire ne Nkyene",
        "optionC": "Ngo ne Mako",
        "optionD": "Nkate ne Aburoo",
        "correctOption": "A",
        "subConcept": "Dintoɔ Nneɛma",
        "explanation": "Wɔde nsuo ne nsa ka abofra tɛkrɛma ka sɛ: 'Wose nsuo a nsuo, wose nsa a nsa' de kyerɛkyerɛ no nokwaredi kɛse.",
        "remediationTip": "Nsuo ne Nsa = Nokwaredi wɔ dintoɔ mu."
      },
      {
        "id": "jhs3-twi-t7-q3",
        "quizId": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
        "questionText": "Aduane titiriw bɛn na Akanfo noa ma brani (abaayewa a ɔrebɔ bra) didi wɔ Bragoro mu?",
        "optionA": "Fufuo ne nkwan",
        "optionB": "Ɔtɔ (ɛmo anaa bayerɛ ɔtɔ) a nkosua gu so",
        "optionC": "Banku ne mako",
        "optionD": "Ampesi ne nkontomire",
        "correctOption": "B",
        "subConcept": "Bragoro Aduane",
        "explanation": "Ɔtɔ a nkosua gu so ne aduane titiriw a wɔma brani didi de bɔ mpae ma no nya awo dɔkɔdɔkɔ ne ahotɔ.",
        "remediationTip": "Ɔtɔ ne nkosua gyina hɔ ma awoɔ ne ahotɔ wɔ Bragoro mu."
      },
      {
        "id": "jhs3-twi-t7-q4",
        "quizId": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
        "questionText": "Dɛn nti na wɔhyɛ brani sɛ ɔmmene kosua no mum ansa na wannyae?",
        "optionA": "Sɛnea ɛbɛyɛ na n'ano bɛyɛ dɛ kɛse",
        "optionB": "Sɛnea ɛbɛma ne yam awo ba pa a ɔkura nipadua a edi mu a biribiara nka no",
        "optionC": "Sɛnea ɛbɛma watu mmirika ntɛm",
        "optionD": "Sɛnea ɛbɛyɛ na ne nua nsa bɛka bi",
        "correctOption": "B",
        "subConcept": "Bragoro Amanne mu Nyansa",
        "explanation": "Wɔmene kosua no mum de bɔ mpae sɛ ne yam mpae mma awoɔ pa a biribiara nsei mma no daakye.",
        "remediationTip": "Kosua a wɔmene mum kyerɛ ba a edi mu a ne ho tew."
      },
      {
        "id": "jhs3-twi-t7-q5",
        "quizId": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
        "questionText": "Sɛ ababaawa bi nyinsɛn bere a wɔnyɛɛ ne bragoro a, dɛn na Akanfo frɛ saa asɛm no?",
        "optionA": "Kyiribra",
        "optionB": "Ayeforɔhyia",
        "optionC": "Agyapadie",
        "optionD": "Babadinto",
        "correctOption": "A",
        "subConcept": "Kyiribra Amammerɛ",
        "explanation": "'Kyiribra' yɛ amumɔsɛm ne animguase kɛse wɔ Akan amammerɛ mu; ɛkyerɛ sɛ abayewa anyinsɛn bere a wɔnyɛɛ ne bragoro.",
        "remediationTip": "Kyiribra = Anyinsɛn bere a wɔnyɛɛ bragoro."
      },
      {
        "id": "jhs3-twi-t7-q6",
        "quizId": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
        "questionText": "Wɔ Akan dintoɔ mu no, hena na ɔwɔ hokwan kɛse sɛ ɔto abofra din?",
        "optionA": "Abofra no wofa",
        "optionB": "Abofra no papa (agya)",
        "optionC": "Kurow no sohene",
        "optionD": "Abofra no yere",
        "correctOption": "B",
        "subConcept": "Dintoɔ Hokwan",
        "explanation": "Wɔ Akan amammerɛ mu, agya na ɔwɔ hokwan sɛ ɔto abofra din efisɛ agya ntoro ne nsonroma na abofra kura.",
        "remediationTip": "Papa/Agya na ɔto ne ba din wɔ babadinto mu."
      },
      {
        "id": "jhs3-twi-t7-q7",
        "quizId": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
        "questionText": "Beae bɛn na Akanfo de brani kɔ kɔguare no wɔ bragoro ahyɛase?",
        "optionA": "Asuogya (subon anaa asubɔnten ho)",
        "optionB": "Gua kɛse so",
        "optionC": "Ahemfie adihoc",
        "optionD": "Asɔredan mu",
        "correctOption": "A",
        "subConcept": "Asuoguare wɔ Bragoro mu",
        "explanation": "Wɔde brani kɔ asuogya ma mpanyinfo mmea de nsuo ne aduru titiriw guare no de te ne ho fi abofra bra mu.",
        "remediationTip": "Asuoguare te ababaawa ho na ɛde no kɔ mmanyinbra mu."
      },
      {
        "id": "jhs3-twi-t7-amammere-bragoro-ne-babadinto-q8",
        "quizId": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
        "questionText": "Mfaso bɛn na Bragoro amammerɛ de brɛ ababaawa no ankasa?",
        "optionA": "Ɛma onya akatua kɛse fi aban hɔ",
        "optionB": "Ɛma onya ahotɔ, obu, afotu pa fa aware ne awo ho, na ɛbɔ no ban fi nna muna mu",
        "optionC": "Ɛma ɔto nnuan kɛse kɔ asuten so",
        "optionD": "Ɛma ɔtumi kɔ akono ntɛm",
        "correctOption": "B",
        "subConcept": "Bragoro Mfaso",
        "explanation": "Bragoro ma mmea mpanimfo tu ababaawa no fo fa asetenapa, aware, ahotew ne anidaho ho.",
        "remediationTip": "Bragoro ma afotu, ahoteɛ, ne anidaho kɔ soro."
      },
      {
        "id": "jhs3-twi-t7-q9",
        "quizId": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
        "questionText": "Din a Akanfo de ma abofra a ɛgyina da a wɔwoo no so (te sɛ Kwadwo, Kwabena, Yaaba) no, wɔfrɛ no dɛn?",
        "optionA": "Kradin (Akan Da-din)",
        "optionB": "Agyadin",
        "optionC": "Abusua din",
        "optionD": "Mmeran",
        "correctOption": "A",
        "subConcept": "Kradin Nkyerɛase",
        "explanation": "Kradin yɛ din a abofra kura fi n'awo da pɔtee (te sɛ Dwoada = Kwadwo/Adwoa).",
        "remediationTip": "Da a wɔwoo abofra ma no ne Kradin."
      },
      {
        "id": "jhs3-twi-t7-q10",
        "quizId": "quiz-jhs3-twi-t7-amammere-bragoro-ne-babadinto",
        "questionText": "Dɛn na Babadinto amammerɛ no kyerɛkyerɛ abofra no daakye abrabɔ mu?",
        "optionA": "Sɛ ɔmfa ne ho mmɔ ahohwisɛm",
        "optionB": "Nokwaredi, suban pa, ne abusuabɔ kronkron wɔ mpɔtam hɔ",
        "optionC": "Sɛ ɔnkɔ akuraa kɔkyere mmoa",
        "optionD": "Sɛ ɔntua tow biara da",
        "correctOption": "B",
        "subConcept": "Babadinto Mfaso",
        "explanation": "Babadinto kyerɛkyerɛ abofra nokwaredi (nsuo ne nsa afotu), abuobuo, ne edin pa a ɛsɛ sɛ ɔbɔ ho ban.",
        "remediationTip": "Edin pa ne nokwaredi ne dintoɔ botae."
      }
    ]
  },
  "jhs3-twi-t8-amammere-aware-ne-agyaapade": {
    "id": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
    "topicId": "jhs3-twi-t8-amammere-aware-ne-agyaapade",
    "title": "Akan Amammerɛ: Awaregyae, Awareware ne Agyapadie BECE Sɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-twi-t8-q1",
        "quizId": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
        "questionText": "Bere a aberante pɛ sɛ ɔware ababaawa no, adinam / dwumadie a edi kan a n'abusuafo yɛ kɔ ababaawa no fifo ne dɛn?",
        "optionA": "Ti-nsa tẽẽ",
        "optionB": "Kasa-sie / Kasagye (Abɔsamu / Kɔkɔɔkɔ)",
        "optionC": "Ayeforɔhyia apontɔ kɛse",
        "optionD": "Akonta-sekan",
        "correctOption": "B",
        "subConcept": "Akan Aware Nhyehyɛe",
        "explanation": "Dwuma a edi kan ne 'Kasagye' anaa 'Abɔsamu' (Knocking rite), a wɔde bɔko akɔbisa sɛ abaayewa no wɔ hɔ anaa obi akuta ne nsam.",
        "remediationTip": "Kasagye / Kɔkɔɔkɔ edi kan wɔ aware biara mu."
      },
      {
        "id": "jhs3-twi-t8-q2",
        "quizId": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
        "questionText": "Nsã titiriw a aberante no de ma ababaawa no fiefo de si aware no so dua wɔ amammerɛ kwan so no, wɔfrɛ no dɛn?",
        "optionA": "Tiri-nsa",
        "optionB": "Akonta-sekan",
        "optionC": "Tamfo-nsa",
        "optionD": "Nsamangu",
        "correctOption": "A",
        "subConcept": "Tiri-nsa Dwumadie",
        "explanation": "Tiri-nsa ne nsã a wɔtua de hyɛ aware no mu den. Sɛ wɔgye tiri-nsa wie pɛ a, aware no afa amammerɛ kwan so.",
        "remediationTip": "Tiri-nsa si aware no so dua wɔ Akan amammerɛ mu."
      },
      {
        "id": "jhs3-twi-t8-q3",
        "quizId": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
        "questionText": "Sika anaa akyɛde a ayeforɔ no kunu de ma ayeforɔ no nuabaninom mmarima no, wɔfrɛ no dɛn?",
        "optionA": "Akonta-sekan",
        "optionB": "Danta-sika",
        "optionC": "Agya-ntoma",
        "optionD": "Tiri-nsa",
        "correctOption": "A",
        "subConcept": "Akonta-sekan",
        "explanation": "'Akonta-sekan' yɛ sika anaa nneɛma a wɔde ma akontafo mmarima de pata wɔn na wɔbɔ wɔn yere no ban.",
        "remediationTip": "Akonta-sekan kɔ ma akontafo mmarima."
      },
      {
        "id": "jhs3-twi-t8-q4",
        "quizId": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
        "questionText": "Dɛn nti na Akanfo yɛ nhwehwɛmu kɛse ansa na wɔagye aware atom?",
        "optionA": "Sɛnea ɛbɛyɛ na wobetumi atua sika kakraa bi",
        "optionB": "Sɛnea wɔbɛhunu yare bɔne, abusuabɔ koro (mogya baako), brabɔne ne asoɔden wɔ abusua no mu",
        "optionC": "Sɛnea wobetumi aguan akɔ amannɔne ntɛm",
        "optionD": "Sɛnea wobetumi asesa abofra no din",
        "correctOption": "B",
        "subConcept": "Aware Nhwehwɛmu Botae",
        "explanation": "Nhwehwɛmu no botae ne sɛ wɔbɛkwati mogyafra (incest), yare a ɛtumi kɔ ba so te sɛ ɔbram, na wɔahunu suban pa.",
        "remediationTip": "Nhwehwɛmu bɔ mma foforɔ ne abusua no ho ban."
      },
      {
        "id": "jhs3-twi-t8-q5",
        "quizId": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
        "questionText": "Wɔ Akan amammerɛ dedaw mu, sɛ ɔbarima wuo na wanhyɛ samansɛw a, hena na odi n'ade kɛse?",
        "optionA": "Ne yere",
        "optionB": "Ne mma",
        "optionC": "Ne wofase (ne nuabea ba)",
        "optionD": "Ne kurontihene",
        "correctOption": "C",
        "subConcept": "Akan Agyapadie Nhyehyɛe",
        "explanation": "Akanfo di ade kɔ wofase efisɛ Akanfo agyapadie di nua mmea awo ntoatoaso akyi (Matrilineal inheritance).",
        "remediationTip": "Akan dedaw mu: Wɔfa wuo a, wɔfase na odi n'ade."
      },
      {
        "id": "jhs3-twi-t8-q6",
        "quizId": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
        "questionText": "Mmara bɛn na Ghana aban hyehyɛe wɔ afe 1985 mu de siesiee agyapade kyɛ maa awarefo ne mma?",
        "optionA": "PNDC Law 111 (Intestate Succession Law)",
        "optionB": "Ghana Police Service Act",
        "optionC": "Local Governance Act",
        "optionD": "Chieftaincy Act",
        "correctOption": "A",
        "subConcept": "PNDC Law 111 Mmara",
        "explanation": "PNDC Law 111 de ahobammɔ baa ayeforɔ ne mmofra agyapade kyɛ mu bere a ɔkununom anaa awofo awu a wɔannyɛ nkrataatwerɛ (will).",
        "remediationTip": "PNDC Law 111 bɔ mmofra ne okunafo agyapade ho ban."
      },
      {
        "id": "jhs3-twi-t8-q7",
        "quizId": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
        "questionText": "Sɛ awarefo pɛ sɛ wogyae aware wɔ amammerɛ kwan so a, amanne titiriw bɛn na ɛkɔ so?",
        "optionA": "Hyiregu ne Ti-nsa san de ma",
        "optionB": "Nsawɔtwe apontɔ kɛse",
        "optionC": "Akonta-sekan foforo tua",
        "optionD": "Babadinto foforo yɛ",
        "correctOption": "A",
        "subConcept": "Awaregyae Amanne",
        "explanation": "Awaregyae mu no, wɔsiesie nsɛm na wɔgu hyire de kyerɛ sɛ aware no agyae, na sɛ ɛfata a, wɔsan de tiri-nsa kɔma.",
        "remediationTip": "Hyiregu kyerɛ awaregyae a adi mu wɔ Akanfo mu."
      },
      {
        "id": "jhs3-twi-t8-q8",
        "quizId": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
        "questionText": "Nnoɔma a edidi so yi mu nea ɛwɔ he na ebetumi de awaregyae aba?",
        "optionA": "Nkabom ne anidaho a ɛwɔ fie",
        "optionB": "Awaresɛe, atirimuɔden, abaatwa (boniayɛ) ne atoro",
        "optionC": "Mmofra dodow a wɔwɔ fie",
        "optionD": "Okuafo a ɔbɔ mmɔden",
        "correctOption": "B",
        "subConcept": "Awaregyae Nnyinaso",
        "explanation": "Awaresɛe, obuo a enni hɔ, basabasa, ne basabasayɛ de awaregyae ba.",
        "remediationTip": "Awaresɛe ne abaatwa sɛe aware ntɛm."
      },
      {
        "id": "jhs3-twi-t8-q9",
        "quizId": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
        "questionText": "'Samansɛw' asekyerɛ ne dɛn wɔ Akan amammerɛ mu?",
        "optionA": "Nsɛm a owufo kurae ansa na ɔrewu a ɔtwerɛe anaa ɔka kyerɛɛ abusuafo fa n'agyapade ho (Oral Will)",
        "optionB": "Ayisɛm mu nsɛm nkutoo",
        "optionC": "Ahemfie nsɛm a wɔka kyerɛ ahemfo",
        "optionD": "Mmɔfra agoprama so nsɛm",
        "correctOption": "A",
        "subConcept": "Samansɛw Nkyerɛase",
        "explanation": "Samansɛw yɛ nsɛm anaa ahyɛde a onipa ka ansa na ɔrewu kyerɛ sɛnea wɔnkyɛ n'agyapade mma ne mma ne n'abusuafo.",
        "remediationTip": "Samansɛw = Nsɛm a owufo de gyae fa n'agyapadie ho."
      },
      {
        "id": "jhs3-twi-t8-q10",
        "quizId": "quiz-jhs3-twi-t8-amammere-aware-ne-agyaapade",
        "questionText": "Mfaso bɛn na Akanfo aware nhyehyɛe de brɛ mpɔtam?",
        "optionA": "Ɛma mmarima de akode tu mpɔtam kuro",
        "optionB": "Ɛkabɔ mmusua abien bɔ mu ma asomdwoe, nkabom, ne mmofra ntetee pa ba",
        "optionC": "Ɛma ohia dɔɔso wɔ nkuraa so",
        "optionD": "Ɛbrɛ abusua tumi ase koraa",
        "correctOption": "B",
        "subConcept": "Aware Mfaso",
        "explanation": "Akan aware nyɛ nipa baanu nkutoo aware, na mmom ɛka mmusua abien nyinaa bɔ mu ma asomdwoe ba.",
        "remediationTip": "Akan aware ka mmusua nyinaa bɔ mu koro."
      }
    ]
  },
  "jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando": {
    "id": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
    "topicId": "jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
    "title": "Akan Amammerɛ: Owuo, Ayiyɔ ne Asamando BECE Sɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-twi-t9-q1",
        "quizId": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
        "questionText": "Nsuo a wɔde gu onipa a ɔrehyia owuo anom ansa na ne kra afi ne mu no, wɔfrɛ no dɛn?",
        "optionA": "Asukɔdeɛ",
        "optionB": "Hyiregu",
        "optionC": "Nsawa",
        "optionD": "Tiri-nsa",
        "correctOption": "A",
        "subConcept": "Asukɔdeɛ Amammerɛ",
        "explanation": "Akanfo gye di sɛ owufo tu kwan kɔ Asamando a ɔkɔm de no, enti wɔde 'asukɔdeɛ' gu n'anom de ma no akwansodeɛ.",
        "remediationTip": "Asukɔdeɛ = Nsuo a wɔgu nea ɔrewu anom."
      },
      {
        "id": "jhs3-twi-t9-q2",
        "quizId": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
        "questionText": "Beae a Akanfo gye di sɛ nnipa a wanyin na wɔabɔ bra pa wu a wɔkɔtena hɔ no, wɔfrɛ hɔ dɛn?",
        "optionA": "Asamando",
        "optionB": "Gua so",
        "optionC": "Asuten",
        "optionD": "Ahensie",
        "correctOption": "A",
        "subConcept": "Asamando Gyidi",
        "explanation": "Asamando ne nananom nsamanfo tenabea a wɔkɔtena bere a wɔawu wɔ wiase ha.",
        "remediationTip": "Asamando ne nananom nsamanfo kurow."
      },
      {
        "id": "jhs3-twi-t9-q3",
        "quizId": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
        "questionText": "Sika a ayifo tu wɔ ayi ase de boa abusua no ma wɔtua ayikafo ka no, wɔfrɛ no dɛn?",
        "optionA": "Nsawa",
        "optionB": "Akonta-sekan",
        "optionC": "Hyire sika",
        "optionD": "Tiri-nsa",
        "correctOption": "A",
        "subConcept": "Nsawa wɔ Ayiyɔ mu",
        "explanation": "'Nsawa' yɛ sika a ahɔho ne ayifo bɔ de boa awufo fiefo de soasoa ayiyɔ ka.",
        "remediationTip": "Nsawa boa abusua no ma wɔtua ayi ho ka."
      },
      {
        "id": "jhs3-twi-t9-q4",
        "quizId": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
        "questionText": "Da bɛn na Akanfo di kan yɛ ayi ho amanne a edi kan koraa bere a obi awu no?",
        "optionA": "Nsawɔtwe da (Da a ɛto so awɔtwe)",
        "optionB": "Adaduanan (Day 40)",
        "optionC": "Afe baako",
        "optionD": "Mfe anum akyi",
        "correctOption": "A",
        "subConcept": "Ayiyɔ Berɛ Nhyehyɛe",
        "explanation": "Nsawɔtwe (da a ɛto so 8) ne amanne a edi kan a abusua hyia bom hu faako a wɔbɛfa agyina na wɔahyehyɛ ayi no.",
        "remediationTip": "Nsawɔtwe dzi kan ansa na adaduanan ne afehyia aba."
      },
      {
        "id": "jhs3-twi-t9-q5",
        "quizId": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
        "questionText": "Owuo a ɛnam akwanhyia bɔne te sɛ awudifo nsam, dua abu agu obi so anaa abomfiɛ so no, wɔfrɛ no owuo bɛn?",
        "optionA": "Atɔfo wuo",
        "optionB": "Nyinkyerɛ wuo",
        "optionC": "Asamando wuo",
        "optionD": "Dintoɔ wuo",
        "correctOption": "A",
        "subConcept": "Atɔfo Wuo",
        "explanation": "Owuo biara a ɛyɛ prɛko pɛ anaa akwanhyia a emu yɛ den a enni amanne pa wɔfrɛ no 'Atɔfo wuo', na wɔnyɛ ho ayi kɛse.",
        "remediationTip": "Atɔfo wuo = Akwanhyia wuo anaa awudie."
      },
      {
        "id": "jhs3-twi-t9-q6",
        "quizId": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
        "questionText": "Dɛn nti na Akanfo gu nsa ma nsamanfo na wɔkɔka wɔn anim asɛm bere biara?",
        "optionA": "Efisɛ wogye di sɛ nananom nsamanfo nwee nsa da",
        "optionB": "Efisɛ wogye di sɛ nsamanfo te ase honhom mu na wɔbɔ abusua no ho ban",
        "optionC": "Efisɛ wɔpɛ sɛ nsa no sa ntɛm",
        "optionD": "Sɛnea ɛbɛyɛ na wɔbɛpam ahɔho",
        "correctOption": "B",
        "subConcept": "Nsamangu Gyidi",
        "explanation": "Akanfo gye di sɛ nananom nsamanfo wɔ nkwa wɔ honhom mu na wɔbɛtumi abɔ mmusua ho ban afi mmusu ho.",
        "remediationTip": "Nsamangu de obuo ma nananom a wɔwɔ Asamando."
      },
      {
        "id": "jhs3-twi-t9-q7",
        "quizId": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
        "questionText": "Atade kɔkɔɔ anaa tuntum (te sɛ Kɔbene ne Brisi) a Akanfo hyɛ kɔ ayi ase no kyerɛ dɛn?",
        "optionA": "Anigye ne ahotɔ kɛse",
        "optionB": "Awerɛhow, awerɛkyekye ne sunsum mu apereperedi",
        "optionC": "Ahonyade ne sika pii",
        "optionD": "Abɔfra bra",
        "correctOption": "B",
        "subConcept": "Ayi Ntoma Su",
        "explanation": "Kɔbene, kuntunkuni ne tuntum gyina hɔ ma awerɛhow a emu yɛ den a aka abusua no.",
        "remediationTip": "Kɔkɔɔ ne tuntum = Awerɛhow ntoma wɔ ayi ase."
      },
      {
        "id": "jhs3-twi-t9-q8",
        "quizId": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
        "questionText": "Sɛ ɔpanyin a wanyin yiye a wanya mma ne mmanana wu a, ntoma fitaa a wɔhyɛ no kyerɛ dɛn?",
        "optionA": "Nkonimdi ne anigye sɛ wadi mfe pii na wanyin kɔ asamando baabi pa",
        "optionB": "Ohia a aka ne fifo",
        "optionC": "Ahennie mmara a wɔabubu",
        "optionD": "Mogyafra a aba kurow no mu",
        "correctOption": "A",
        "subConcept": "Ntoma Fitaa wɔ Ayi mu",
        "explanation": "Sɛ obi nyin kɔkyɛ paa kɔka nananom ho a, wɔhyɛ ntoma fitaa de hyɛ nkonimdi ne nna nyinkyerɛ no anuonyam.",
        "remediationTip": "Ntoma fitaa kyerɛ nkonimdi ma opanyin a wanyin kakraka."
      },
      {
        "id": "jhs3-twi-t9-q9",
        "quizId": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
        "questionText": "Dwuma titiriw a Okunafo yɛ bere a ne hokafo awu a wɔfrɛ no 'Okunaye' no botae ne dɛn?",
        "optionA": "Sɛ wɔde te okunafo no ho fi owufo no honhom mu na wɔbɔ no ban",
        "optionB": "Sɛ wɔbɛma watua tow kɛse ma ahemfo",
        "optionC": "Sɛ wɔbɛhyɛ no ma waguan afi kurow no mu",
        "optionD": "Sɛ wɔbɛgye ne sika nyinaa",
        "correctOption": "A",
        "subConcept": "Okunaye Amammerɛ",
        "explanation": "Okunaye yɛ amanne a wɔyɛ de pata owufo honhom na wɔte okunafo no ho ma ɔbɛtumi atena ase asomdwoe mu.",
        "remediationTip": "Okunaye te okunafo ho fi sunsum bɔne ho."
      },
      {
        "id": "jhs3-twi-t9-q10",
        "quizId": "quiz-jhs3-twi-t9-amammere-owuo-ayiyɔ-ne-asamando",
        "questionText": "Mfaso bɛn na ayiyɔ amammerɛ de brɛ Akan abusuafo?",
        "optionA": "Ɛma wɔn nsa ka agyapade a wɔampere ho hwee",
        "optionB": "Ɛka abusua a wɔabɔ petee bom, ɛhyɛ baakoyɛ mu den, na ɛma wɔkae owufo no nnwuma pa",
        "optionC": "Ɛsɛe sika pii a mfaso nni so koraa da",
        "optionD": "Ɛma ahemfo paw adidifo foforo",
        "correctOption": "B",
        "subConcept": "Ayiyɔ Mfaso",
        "explanation": "Ayiyɔ kabɔ abusuafo a wɔwɔ baabiara bom ma wosua nkabom ne awerɛkyekye.",
        "remediationTip": "Ayi kura abusua nkabom ne awerɛkyekye."
      }
    ]
  },
  "jhs3-twi-t10-ahemfo-ahemfie-ne-abusua": {
    "id": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
    "topicId": "jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
    "title": "Ahennie, Ahemfie Dwumadie ne Abusua Kuw BECE Sɔhwɛ",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-twi-t10-q1",
        "quizId": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
        "questionText": "Wɔ Akan ahemfie mu no, hena na ɔyɛ ɔkasafo ma ɔhene na ɔno nso de amanfo nsɛm kɔto ɔhene anim?",
        "optionA": "Krontihene",
        "optionB": "Ɔkyeame",
        "optionC": "Gyaasehene",
        "optionD": "Sanaahene",
        "correctOption": "B",
        "subConcept": "Ɔkyeame Dwumadie",
        "explanation": "Ɔkyeame na ɔkura poma kyerɛ ahenfie kasa, na ɔno ne ɔhene ano a ɔkasa kyerɛ ɔmanfo.",
        "remediationTip": "Ɔkyeame ne ɔhene ano ne n'akasafo."
      },
      {
        "id": "jhs3-twi-t10-q2",
        "quizId": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
        "questionText": "Ɔhemaa gyinabea bɛn na ɛwɔ soro kɛse bere a akonnwa bi da mpan na wɔrepaw ɔhene foforɔ?",
        "optionA": "Ɔno na ɔwɔ hokwan kɛse sɛ ɔpaw ɔhene foforɔ kyerɛ abusuafo ne mpanimfo",
        "optionB": "Ɔno na ɔbɔ atumpan wɔ ahemfie",
        "optionC": "Ɔno na ɔhwɛ fotoɔ ne sika so",
        "optionD": "Ɔno na ɔtwa nnuaba wɔ ahemfie mfuw mu",
        "correctOption": "A",
        "subConcept": "Ɔhemaa Gyinabea",
        "explanation": "Ɔhemaa na ɔkyerɛ ɔpanyin a ɔfata sɛ ɔbɛtena akonnwa so (kingmaker), na ɔtumi paw nipa mprɛnsa kɔpem sɛ mpanimfo bɛpene so.",
        "remediationTip": "Ɔhemaa na ɔpaw ɔhene foforo."
      },
      {
        "id": "jhs3-twi-t10-q3",
        "quizId": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
        "questionText": "Akraboa (totem) bɛn na ɛgyina hɔ ma Ɔyokoɔ abusuakuw?",
        "optionA": "Ɔkɔdeɛ (Eagle)",
        "optionB": "Ɔkraman (Dog)",
        "optionC": "Kwaakwaadabi / Anene (Crow)",
        "optionD": "Ɔkore (Parrot)",
        "correctOption": "A",
        "subConcept": "Ɔyokoɔ Abusuakuw Akraboa",
        "explanation": "Ɔyokoɔ abusuakuw akraboa ne Ɔkɔdeɛ (Eagle), a ɛkyerɛ anuonyam, ahoɔden ne tumi kɛse.",
        "remediationTip": "Ɔyokoɔ = Ɔkɔdeɛ (Eagle)."
      },
      {
        "id": "jhs3-twi-t10-q4",
        "quizId": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
        "questionText": "Abusuakuw bɛn na wɔn akraboa ne Ɔkraman a ɔkura ogya wɔ n'anom?",
        "optionA": "Aduana",
        "optionB": "Asona",
        "optionC": "Asakyiri",
        "optionD": "Bretuo",
        "correctOption": "A",
        "subConcept": "Aduana Abusuakuw Akraboa",
        "explanation": "Aduanafo akraboa ne Ɔkraman a ɔkura ogya wɔ n'anom, efisɛ wogye di sɛ wɔn na wɔde ogya baa wiase.",
        "remediationTip": "Aduana = Ɔkraman a ɔkura ogya."
      },
      {
        "id": "jhs3-twi-t10-q5",
        "quizId": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
        "questionText": "Hena na ɔhwɛ ahemfie dan, nnuan ne ahemfie fiefo nyinaa so (Palace administrator)?",
        "optionA": "Gyaasehene",
        "optionB": "Krontihene",
        "optionC": "Adontenhene",
        "optionD": "Twafohene",
        "correctOption": "A",
        "subConcept": "Gyaasehene Dwumadie",
        "explanation": "Gyaasehene ne sahene a ɔhwɛ ahemfie no mu nnoɔma nyinaa so, ahemfie fiefo, ne ɔhene nsaase sohwɛ.",
        "remediationTip": "Gyaasehene = Ahemfie mu sohwɛfo kɛse."
      },
      {
        "id": "jhs3-twi-t10-q6",
        "quizId": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
        "questionText": "Sanaahene dwumadie titiriw wɔ ahemfie ne dɛn?",
        "optionA": "Ɔno na ɔhwɛ ahemfie sika ne fotoɔ so (Treasurer)",
        "optionB": "Ɔno na ɔkura afoa kɔ akono",
        "optionC": "Ɔno na ɔto dwom ma ɔhene",
        "optionD": "Ɔno na ɔbɔ atumpan",
        "correctOption": "A",
        "subConcept": "Sanaahene Dwumadie",
        "explanation": "Sanaaho/Sanaahene na ɔkura Sanaa (fotoɔ) a sika ne agyapade hyɛ mu, enti ɔno ne sikasohwɛfo.",
        "remediationTip": "Sanaaho/Sanaahene = Sikasohwɛfo (Treasurer)."
      },
      {
        "id": "jhs3-twi-t10-q7",
        "quizId": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
        "questionText": "Asona abusuakuw akraboa titiriw ne hefa?",
        "optionA": "Kwaakwaadabi / Anene",
        "optionB": "Ɔsebɔ",
        "optionC": "Ɔwɔ",
        "optionD": "Apatiprɛ",
        "correctOption": "A",
        "subConcept": "Asona Abusuakuw Akraboa",
        "explanation": "Asonafo akraboa ne Kwaakwaadabi (Crow), a ɔwɔ ti kɛse ne kɔn fitaa a ɛkyerɛ ahoteɛ ne anifere.",
        "remediationTip": "Asona = Kwaakwaadabi (Crow)."
      },
      {
        "id": "jhs3-twi-t10-q8",
        "quizId": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
        "questionText": "Sahene bɛn na ɔdi akono dɔm no kan tẽẽ (vanguard commander)?",
        "optionA": "Twafohene",
        "optionB": "Krontihene",
        "optionC": "Kyidomhene",
        "optionD": "Gyaasehene",
        "correctOption": "A",
        "subConcept": "Akan Asafo ne Asrafo Nhyehyɛe",
        "explanation": "Twafohene ne sahene a ɔdi dɔm no anim akono tẽẽ de twa kwan ma asrafo a aka no di n'akyi.",
        "remediationTip": "Twafohene = Sahene a odi kan kɔ akono (Vanguard)."
      },
      {
        "id": "jhs3-twi-t10-q9",
        "quizId": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
        "questionText": "Akanfo abusuakuw ahe na ɛwɔ hɔ a abusua biara fi mu bae?",
        "optionA": "Abusuakuw awɔtwe (8)",
        "optionB": "Abusuakuw dumien (12)",
        "optionC": "Abusuakuw anan (4)",
        "optionD": "Abusuakuw aduonu (20)",
        "correctOption": "A",
        "subConcept": "Akan Mmusuakuw Dodow",
        "explanation": "Akan mmusuakuw titiriw yɛ awɔtwe (8): Ɔyokoɔ, Bretuo, Aduana, Asona, Asenie, Ɛkoɔna, Asakyiri, ne Agona.",
        "remediationTip": "Akan mmusuakuw titiriw yɛ awɔtwe (8)."
      },
      {
        "id": "jhs3-twi-t10-q10",
        "quizId": "quiz-jhs3-twi-t10-ahemfo-ahemfie-ne-abusua",
        "questionText": "Mfaso titiriw bɛn na ahennie ne abusua nhyehyɛe de brɛ Ghana amanyɔsɛm nnɛ?",
        "optionA": "Ɛbrɛ aban adwuma ase",
        "optionB": "Ɛbɔ asomdwoe ho ban, siesie ntawntawdi, na ɛkura yɛn amammerɛ ne nipasu mu",
        "optionC": "Ɛma nkurɔfo mfa mbra nni dwuma",
        "optionD": "Ɛma ahemfo tow mpona kɔ amannɔne",
        "correctOption": "B",
        "subConcept": "Ahennie Mfaso wɔ Ghana",
        "explanation": "Ahennie kura Ghana amammerɛ mu, de asomdwoe ba mpɔtam, na ɛboa aban wɔ mpɔtam nkɔso mu.",
        "remediationTip": "Ahennie ne abusua yɛ asomdwoe ne amammerɛ fapem."
      }
    ]
  }
};
