// Ghanaian JHS 1 Akuapem Twi Practice Quizzes
// Based on NaCCA / GES Common Core Programme (CCP) Curriculum
// 15 Topics × 10 Questions = 150 BECE-Standard Questions

import { TopicQuiz } from './types';

export const JHS1_TWI_QUIZZES: Record<string, TopicQuiz> = {
  "jhs1-twi-t1-akyerwamba": {
    "id": "quiz-jhs1-twi-akyerwamba",
    "topicId": "jhs1-twi-t1-akyerwamba",
    "title": "Akuapem Twi Akyerɛwamba ne Nnyegyei Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-aky-1",
        "quizId": "quiz-jhs1-twi-akyerwamba",
        "questionText": "Akuapem Twi akyerɛwamba a yɛde twerɛ kasa no si ahe pɛpɛɛpɛ?",
        "optionA": "Aduonu nsia (26)",
        "optionB": "Aduonu mmienu (22)",
        "optionC": "Aduonu anan (24)",
        "optionD": "Aduonu (20)",
        "correctOption": "B",
        "subConcept": "Twi Alphabet Count",
        "explanation": "Akuapem Twi akyerɛwamba yɛ aduonu mmienu (22). C, J, Q, V, X, Z nka Twi akyerɛwamba ho.",
        "remediationTip": "Twi alphabet has 22 letters, unlike English which has 26."
      },
      {
        "id": "q-twi-aky-2",
        "quizId": "quiz-jhs1-twi-akyerwamba",
        "questionText": "Akyerɛwamba a ɛdidi so yi mu nea ɛwɔ he na ƐNKA Akuapem Twi akyerɛwamba ho?",
        "optionA": "Ɛ",
        "optionB": "Ɔ",
        "optionC": "J",
        "optionD": "Y",
        "correctOption": "C",
        "subConcept": "Non-Twi Letters",
        "explanation": "Akyerɛwde 'J' nni Twi akyerɛwamba mu korakora; yɛde 'gy' na esi n'ananmu.",
        "remediationTip": "Letters C, J, Q, V, X, Z do not exist in the Akan orthography."
      },
      {
        "id": "q-twi-aky-3",
        "quizId": "quiz-jhs1-twi-akyerwamba",
        "questionText": "Anom nnyegyei (vowels) ahe na ɛwɔ Akuapem Twi mu?",
        "optionA": "Anum (5)",
        "optionB": "Ason (7)",
        "optionC": "Awotwe (8)",
        "optionD": "Akron (9)",
        "correctOption": "B",
        "subConcept": "Twi Vowel Count",
        "explanation": "Twi anom nnyegyei yɛ ason (7): A, E, Ɛ, I, O, Ɔ, U.",
        "remediationTip": "Akan/Twi has 7 primary oral vowels (A, E, Ɛ, I, O, Ɔ, U)."
      },
      {
        "id": "q-twi-aky-4",
        "quizId": "quiz-jhs1-twi-akyerwamba",
        "questionText": "Nnyegyepɛn (digraph) bɛn na yɛbɛhũ wɔ asɛmfua 'gyina' mu?",
        "optionA": "ky",
        "optionB": "hy",
        "optionC": "gy",
        "optionD": "dw",
        "correctOption": "C",
        "subConcept": "Digraph Identification",
        "explanation": "Asɛmfua 'gyina' hyɛ ase ne nnyegyepɛn 'gy'.",
        "remediationTip": "Digraphs combine two consonants to make one sound: gy, ky, hy, ny, tw, dw, kw, hw."
      },
      {
        "id": "q-twi-aky-5",
        "quizId": "quiz-jhs1-twi-akyerwamba",
        "questionText": "Asɛmfua bɛn na ɛkura nnyegyei a ɛyɛ hwene nnyegyei (nasal vowel)?",
        "optionA": "Kasa",
        "optionB": "Kã",
        "optionC": "Pono",
        "optionD": "Dua",
        "correctOption": "B",
        "subConcept": "Nasal Vowels",
        "explanation": "'Kã' kura hwene nnyegyei 'ã' efisɛ mframa fa hwene mu bere a yɛrebɔ no.",
        "remediationTip": "Nasal vowels have a tilde over the vowel (ã, ẽ, ɛ̃, ĩ, õ, ɔ̃, ũ)."
      },
      {
        "id": "q-twi-aky-6",
        "quizId": "quiz-jhs1-twi-akyerwamba",
        "questionText": "Anom nnyegyei bɛn na ɛyɛ 'nnyegyei tsentsen' (high/tense vowel)?",
        "optionA": "Ɛ",
        "optionB": "Ɔ",
        "optionC": "A",
        "optionD": "I",
        "correctOption": "D",
        "subConcept": "Tense vs Lax Vowels",
        "explanation": "/i, u, e, o/ yɛ nnyegyei tsentsen (high/tense vowels), na /ɛ, ɔ, a/ yɛ nnyegyei ntiantia.",
        "remediationTip": "High/tense vowels in Twi are /i, u, e, o/."
      },
      {
        "id": "q-twi-aky-7",
        "quizId": "quiz-jhs1-twi-akyerwamba",
        "questionText": "Nsonsonoe bɛn na ɛda nsɛmfua 'te' ne 'tɛ' ntam?",
        "optionA": "'te' kyerɛ flat na 'tɛ' kyerɛ hear",
        "optionB": "'te' kyerɛ hear/live na 'tɛ' kyerɛ flat/spread",
        "optionC": "Nsɛmfua mmienu no kyerɛ ade koro pɛ",
        "optionD": "'te' yɛ edin na 'tɛ' yɛ adeyɛ",
        "correctOption": "B",
        "subConcept": "Minimal Pairs e vs ɛ",
        "explanation": "'te' de 'e' na ɛkyerɛ to hear or to live; 'tɛ' de 'ɛ' na ɛkyerɛ to be flat.",
        "remediationTip": "Distinguish 'e' (close) from 'ɛ' (open) to understand different meanings."
      },
      {
        "id": "q-twi-aky-8",
        "quizId": "quiz-jhs1-twi-akyerwamba",
        "questionText": "Nnyegyepɛn ahe na ɛwɔ Akuapem Twi mu a yɛtaa de di dwuma?",
        "optionA": "Awotwe (8)",
        "optionB": "Anan (4)",
        "optionC": "Aduanu (20)",
        "optionD": "Dumienu (12)",
        "correctOption": "A",
        "subConcept": "Digraph Count",
        "explanation": "Nnyegyepɛn titiriw awotwe (8) no ne: gy, ky, hy, ny, tw, dw, kw, hw.",
        "remediationTip": "The 8 major Akan digraphs are gy, ky, hy, ny, tw, dw, kw, hw."
      },
      {
        "id": "q-twi-aky-9",
        "quizId": "quiz-jhs1-twi-akyerwamba",
        "questionText": "Sɛ yɛrepaepae asɛmfua 'atwerɛ' mu a, sɛnea ɛbɛyɛ pɛpɛɛpɛ ne:",
        "optionA": "at-we-rɛ",
        "optionB": "a-twe-rɛ",
        "optionC": "atw-e-rɛ",
        "optionD": "a-tw-erɛ",
        "correctOption": "B",
        "subConcept": "Syllabification of Digraphs",
        "explanation": "Wɔmpaepae nnyegyepɛn 'tw' mu; nkyekyem no yɛ a-twe-rɛ.",
        "remediationTip": "Never split a digraph across syllables when dividing words."
      },
      {
        "id": "q-twi-aky-10",
        "quizId": "quiz-jhs1-twi-akyerwamba",
        "questionText": "Twi kasa yɛ kasa a ɛwɔ anofafa ne nne nteɛso (tone). Eyi kyerɛ sɛ:",
        "optionA": "Nne kɔ soro anaa fam na ɛsesa asɛmfua nkyerɛase",
        "optionB": "Wɔmfa anofafa nnkasa koraa",
        "optionC": "Kasa no nni akyerɛwamba",
        "optionD": "Borɔfo akyerɛwamba na ɛkyerɛ nkyerɛase",
        "correctOption": "A",
        "subConcept": "Tonal Nature of Twi",
        "explanation": "Twi yɛ tone language; nne soro anaa fam (high or low tone) tumi sesa asɛmfua no nkyerɛase.",
        "remediationTip": "Pitch/tone in Twi determines meaning (e.g. kòfi = Friday boy vs kòfí = coffee)."
      }
    ]
  },
  "jhs1-twi-t2-nnyegyekoro": {
    "id": "quiz-jhs1-twi-nnyegyekoro",
    "topicId": "jhs1-twi-t2-nnyegyekoro",
    "title": "Nnyegyekorɔ ne Nnawɔtwe Nnyegyei Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-nny-1",
        "quizId": "quiz-jhs1-twi-nnyegyekoro",
        "questionText": "Dɛn ne 'Nnyegyekorɔ' (Vowel Harmony) wɔ Twi kasa mu?",
        "optionA": "Akyerɛwamba a wɔde ka kasa afoforo ho",
        "optionB": "Mmara a ɛkyerɛ anom nnyegyei kuw a ɛfata sɛ ɛbom tena asɛmfua mu",
        "optionC": "Edin a wɔde to mmɔfra wɔ Memeneda",
        "optionD": "Borɔfo nsɛm a yɛfa gu Twi mu",
        "correctOption": "B",
        "subConcept": "Definition of Vowel Harmony",
        "explanation": "Nnyegyekorɔ yɛ mmara a ɛma anom nnyegyei kuw koro (tense anaa lax) kabom di dwuma.",
        "remediationTip": "Vowel harmony ensures vowels in a word agree in phonetic quality."
      },
      {
        "id": "q-twi-nny-2",
        "quizId": "quiz-jhs1-twi-nnyegyekoro",
        "questionText": "Sɛ adeyɛ no mu nnyegyei yɛ 'i' (e.g., 'didi') a, edin-nsiananmu 'me' bɛdane bɛn wɔ Akuapem Twi mu?",
        "optionA": "ma",
        "optionB": "mo",
        "optionC": "mi",
        "optionD": "mɛ",
        "correctOption": "C",
        "subConcept": "Pronoun Harmony with High Vowels",
        "explanation": "Esiane nnyegyekorɔ nti, 'me' dane 'mi' wɔ adeyɛ a ɛkura /i, u/ anim (e.g. mididi).",
        "remediationTip": "Subject pronoun 'me' becomes 'mi' before high vowels like /i/ and /u/."
      },
      {
        "id": "q-twi-nny-3",
        "quizId": "quiz-jhs1-twi-nnyegyekoro",
        "questionText": "Asɛmfua bɛn na wɔatwerɛ no pɛpɛɛpɛ sɛnea Akuapem Twi nnyegyekorɔ mmara te?",
        "optionA": "Me kura",
        "optionB": "Mikura",
        "optionC": "Mɛkura",
        "optionD": "Makura",
        "correctOption": "B",
        "subConcept": "Orthographic Application of Harmony",
        "explanation": "Wɔ Akuapem Twi mu no, yɛtwerɛ no sɛ 'Mikura' efisɛ /u/ yɛ tense vowel a ɛdane 'me' kɔ 'mi'.",
        "remediationTip": "Write 'Mikura' as one unified verb-subject complex in Akuapem Twi."
      },
      {
        "id": "q-twi-nny-4",
        "quizId": "quiz-jhs1-twi-nnyegyekoro",
        "questionText": "Dɛn nti na yɛka sɛ 'mekɔ' na ɛnyɛ 'mikɔ'?",
        "optionA": "Efisɛ 'kɔ' kura lax vowel 'ɔ', enti 'me' nnsesa kɔ 'mi'",
        "optionB": "Efisɛ 'kɔ' yɛ borɔfo asɛmfua",
        "optionC": "Efisɛ 'mekɔ' nni nnyegyekorɔ mu",
        "optionD": "Efisɛ 'kɔ' yɛ edin na ɛnyɛ adeyɛ",
        "correctOption": "A",
        "subConcept": "Low Vowel Harmony Condition",
        "explanation": "'ɔ' yɛ lax/open vowel, enti edin-nsiananmu no kɔ so yɛ 'me' na ɛnyɛ 'mi'.",
        "remediationTip": "'me' remains 'me' before low/lax vowels /ɛ, ɔ, a/."
      },
      {
        "id": "q-twi-nny-5",
        "quizId": "quiz-jhs1-twi-nnyegyekoro",
        "questionText": "Sɛ nnyegyei /n-/ reba adeyɛ a ɛhyɛ ase ne 'b' anim a, nnyegyei bɛn na esi n'ananmu?",
        "optionA": "/r/",
        "optionB": "/m/",
        "optionC": "/s/",
        "optionD": "/k/",
        "correctOption": "B",
        "subConcept": "Nasal Assimilation",
        "explanation": "/n-/ sesa kɔ /m-/ anim ma 'b' ne 'p' (e.g. n-bɔ bɛyɛ mmɔ; n-ba bɛyɛ mma).",
        "remediationTip": "The alveolar nasal /n/ assimilates to bilabial /m/ before /b/ and /p/."
      },
      {
        "id": "q-twi-nny-6",
        "quizId": "quiz-jhs1-twi-nnyegyekoro",
        "questionText": "Dɛn ne asɛmfua a ɛkyerɛ 'ahomtew' (elision) wɔ Twi kasa mu?",
        "optionA": "Nsɛmfua a wɔde ka ho ma ɛyɛ kɛse",
        "optionB": "Nnyegyei a ɛyera bere a nsɛmfua mmienu hyia no ntɛmntɛm",
        "optionC": "Akyerɛw kɛse a wɔde hyɛ ase",
        "optionD": "Din a agya de to n'abofra",
        "correctOption": "B",
        "subConcept": "Elision (Ahomtew)",
        "explanation": "Ahomtew yɛ nnyegyei a ɛyera anaa ɛpopa bere a yɛrekasa ntɛmntɛm.",
        "remediationTip": "Elision refers to the dropping or deletion of a sound in rapid speech."
      },
      {
        "id": "q-twi-nny-7",
        "quizId": "quiz-jhs1-twi-nnyegyekoro",
        "questionText": "Nnyegyei kuw bɛn na wɔfrɛ no 'Ekuw Tsentsen' (Tense/Advanced Tongue Root)?",
        "optionA": "{a, ɛ, ɔ}",
        "optionB": "{i, e, o, u}",
        "optionC": "{k, g, h}",
        "optionD": "{b, d, f}",
        "correctOption": "B",
        "subConcept": "+ATR Vowels",
        "explanation": "{i, e, o, u} yɛ +ATR anaa nnyegyei tsentsen wɔ Akanfo kasa mu.",
        "remediationTip": "The 4 tense vowels are i, e, o, u."
      },
      {
        "id": "q-twi-nny-8",
        "quizId": "quiz-jhs1-twi-nnyegyekoro",
        "questionText": "Sɛ yɛka sɛ 'ɔbatu' a, nnyegyekorɔ mmara ma edin-nsiananmu 'ɔ' no sesa bɛyɛ dɛn wɔ keka mu?",
        "optionA": "ɛbatu",
        "optionB": "obatu",
        "optionC": "abatu",
        "optionD": "yɛbatu",
        "correctOption": "B",
        "subConcept": "3rd Person Pronoun Harmony",
        "explanation": "'ɔ' sesa kɔ 'o' anim ma tense vowel /u/ wɔ adeyɛ mu (o-tu).",
        "remediationTip": "The third person pronoun 'ɔ' becomes 'o' before high vowels."
      },
      {
        "id": "q-twi-nny-9",
        "quizId": "quiz-jhs1-twi-nnyegyekoro",
        "questionText": "Asɛmfua 'bubu' kura anom nnyegyei bɛn?",
        "optionA": "Ɔ",
        "optionB": "U",
        "optionC": "Ɛ",
        "optionD": "A",
        "correctOption": "B",
        "subConcept": "Vowel Identification in Verb",
        "explanation": "'bubu' kura nnyegyei 'u' mprɛnsa/mprɛnu a ɛyɛ tense vowel.",
        "remediationTip": "'bubu' contains vowel /u/."
      },
      {
        "id": "q-twi-nny-10",
        "quizId": "quiz-jhs1-twi-nnyegyekoro",
        "questionText": "Mfaso titiriw a nnyegyekorɔ de ba Twi kasa mu ne dɛn?",
        "optionA": "Ɛma kasa no yɛ dɛ na ɛyɛ mmerɛw sɛ yɛbɛbɔ n'ano",
        "optionB": "Ɛma kasa no yɛ den ma afoforo nte ase",
        "optionC": "Ɛsesa Borɔfo kasa kɔ Twi mu",
        "optionD": "Ɛma yɛtumi twerɛ mfonini pii",
        "correctOption": "A",
        "subConcept": "Purpose of Vowel Harmony",
        "explanation": "Nnyegyekorɔ ma kasa no nnyegyei yɛ pɛpɛɛpɛ a ɛnyɛ den sɛ yɛbɛbɔ ano.",
        "remediationTip": "Vowel harmony ensures ease of pronunciation and melodic flow in Akan speech."
      }
    ]
  },
  "jhs1-twi-t3-kasamufa-edin": {
    "id": "quiz-jhs1-twi-kasamufa-edin",
    "topicId": "jhs1-twi-t3-kasamufa-edin",
    "title": "Kasamufa: Edin ne Edin-nsiananmu Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-edin-1",
        "quizId": "quiz-jhs1-twi-kasamufa-edin",
        "questionText": "Dɛn ne 'Edin Pa' (Proper Noun) wɔ kasa mu?",
        "optionA": "Din kɛkɛ a yɛde bɔ ade biara",
        "optionB": "Din pɔtee a yɛde bɔ nipa, beae, anaa asubɔnten",
        "optionC": "Adeyɛ a ɛkyerɛ adwuma",
        "optionD": "Asɛmfua a ɛkyerɛ baabi a ade te",
        "correctOption": "B",
        "subConcept": "Proper Noun Definition",
        "explanation": "Edin Pa yɛ din pɔtee te sɛ Kofi, Akropong, Densu, Ghana a yɛhyɛ ase ne akyerɛw kɛse.",
        "remediationTip": "Proper nouns name specific persons, places, or rivers and begin with capitals."
      },
      {
        "id": "q-twi-edin-2",
        "quizId": "quiz-jhs1-twi-kasamufa-edin",
        "questionText": "Nsɛmfua a ɛdidi so yi mu nea ɛwɔ he na ɛyɛ Edin Pa?",
        "optionA": "abofra",
        "optionB": "kurow",
        "optionC": "Kumase",
        "optionD": "dua",
        "correctOption": "C",
        "subConcept": "Proper Noun Identification",
        "explanation": "'Kumase' yɛ kuropɔn din pɔtee, enti ɛyɛ Edin Pa.",
        "remediationTip": "Names of specific towns like 'Kumase' are proper nouns."
      },
      {
        "id": "q-twi-edin-3",
        "quizId": "quiz-jhs1-twi-kasamufa-edin",
        "questionText": "Edin 'ɔba' dodow (plural) wɔ Akuapem Twi mu ne:",
        "optionA": "mmofra",
        "optionB": "mma",
        "optionC": "abofra",
        "optionD": "mmarima",
        "correctOption": "B",
        "subConcept": "Plural of Nouns",
        "explanation": "'ɔba' (child/offspring) dodow yɛ 'mma'.",
        "remediationTip": "Singular 'ɔba' becomes plural 'mma'."
      },
      {
        "id": "q-twi-edin-4",
        "quizId": "quiz-jhs1-twi-kasamufa-edin",
        "questionText": "Edin bɛn na ɛyɛ 'Edin a Wɔntumi Nkan' (Uncountable Noun)?",
        "optionA": "aponkye",
        "optionB": "dada",
        "optionC": "nsuo",
        "optionD": "krataa",
        "correctOption": "C",
        "subConcept": "Uncountable Nouns",
        "explanation": "'Nsuo' yɛ nneɛma a yɛntumi nkan baako baako, enti ɛyɛ edin a wɔntumi nkan.",
        "remediationTip": "Liquids and granular items like 'nsuo' (water) are uncountable."
      },
      {
        "id": "q-twi-edin-5",
        "quizId": "quiz-jhs1-twi-kasamufa-edin",
        "questionText": "Dɛn ne 'Edin-nsiananmu' (Pronoun)?",
        "optionA": "Asɛmfua a egyina hɔ ma edin na yɛammɔ din no mprenpreŋ",
        "optionB": "Asɛmfua a ɛka adeyɛ ho",
        "optionC": "Din a agya de to abofra",
        "optionD": "Akyerɛwamba a yɛde wie kasamu",
        "correctOption": "A",
        "subConcept": "Pronoun Definition",
        "explanation": "Edin-nsiananmu gyina hɔ ma edin (e.g., me, wo, ɔ, yɛ, mo, wɔ).",
        "remediationTip": "Pronouns replace nouns in sentences to avoid repetition."
      },
      {
        "id": "q-twi-edin-6",
        "quizId": "quiz-jhs1-twi-kasamufa-edin",
        "questionText": "Edin-nsiananmu a egyina hɔ ma 'Ɔkasafo Dodow' (1st Person Plural) ne:",
        "optionA": "Me",
        "optionB": "Wo",
        "optionC": "Yɛ",
        "optionD": "Mo",
        "correctOption": "C",
        "subConcept": "1st Person Plural Pronoun",
        "explanation": "'Yɛ' kyerɛ 'we/us' (1st Person Plural).",
        "remediationTip": "First person plural 'we' in Twi is 'Yɛ'."
      },
      {
        "id": "q-twi-edin-7",
        "quizId": "quiz-jhs1-twi-kasamufa-edin",
        "questionText": "Edin 'pono' dodow yɛ dɛn?",
        "optionA": "apono",
        "optionB": "mpono",
        "optionC": "npono",
        "optionD": "pononom",
        "correctOption": "B",
        "subConcept": "Plural with Nasal Prefix",
        "explanation": "Efisɛ 'p' yɛ bilabial nti, yɛde 'm-' gu anim ma ɛbɛyɛ 'mpono'.",
        "remediationTip": "Use prefix 'm-' before p and b to make plural (pono -> mpono)."
      },
      {
        "id": "q-twi-edin-8",
        "quizId": "quiz-jhs1-twi-kasamufa-edin",
        "questionText": "Wɔ Twi kasa mu no, nsonsonoe bɛn na ɛda barima ne bea edin-nsiananmu ntam?",
        "optionA": "Barima yɛ 'he' na bea yɛ 'she'",
        "optionB": "Nsonoe biara nni ntam; 'ɔ' gyina hɔ ma barima ne bea nyinaa",
        "optionC": "Barima de 'ɔ' na bea de 'ɛ'",
        "optionD": "Barima de 'me' na bea de 'wo'",
        "correctOption": "B",
        "subConcept": "Gender Neutrality in Twi Pronouns",
        "explanation": "Twi edin-nsiananmu 'ɔ' nkyɛ mu mfa barima anaa bea nsonoe; ɛgyina hɔ ma he/she nyinaa.",
        "remediationTip": "Third person singular 'ɔ' in Twi applies equally to male and female."
      },
      {
        "id": "q-twi-edin-9",
        "quizId": "quiz-jhs1-twi-kasamufa-edin",
        "questionText": "Nsɛmfua a ɛdidi so yi mu nea ɛwɔ he na ɛyɛ 'Edin a Yɛhu no Adwenem Kɛkɛ' (Abstract Noun)?",
        "optionA": "ɔpono",
        "optionB": "anigye",
        "optionC": "abofra",
        "optionD": "dɔteɛ",
        "correctOption": "B",
        "subConcept": "Abstract Nouns",
        "explanation": "'Anigye' (joy/happiness) yɛ ade a yɛte nka wɔ koma mu na yɛntumi mfa nsa nka.",
        "remediationTip": "Feelings and qualities like 'anigye' (joy) are abstract nouns."
      },
      {
        "id": "q-twi-edin-10",
        "quizId": "quiz-jhs1-twi-kasamufa-edin",
        "questionText": "Fa edin-nsiananmu a ɛfata wie kasamu yi: 'Kwame ne Kofi kɔɔ gua so; ___ tɔɔ nnoɔma bebree.'",
        "optionA": "ɔ",
        "optionB": "wɔ",
        "optionC": "me",
        "optionD": "wo",
        "correctOption": "B",
        "subConcept": "3rd Person Plural Pronoun in Context",
        "explanation": "Kwame ne Kofi yɛ nnipa baanu (dodow), enti edin-nsiananmu a ɛfata ne 'wɔ' (they).",
        "remediationTip": "Refer to two or more other people using 'wɔ' (they)."
      }
    ]
  },
  "jhs1-twi-t4-adey": {
    "id": "quiz-jhs1-twi-adey",
    "topicId": "jhs1-twi-t4-adey",
    "title": "Adeyɛ ne Ɔkyerɛfo Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-ade-1",
        "quizId": "quiz-jhs1-twi-adey",
        "questionText": "Dɛn ne 'Adeyɛ' (Verb) dwumadi titiriw wɔ kasamu mu?",
        "optionA": "Ɛkyerɛ adwuma anaa nneyɛe a obi reyɛ",
        "optionB": "Ɛbɔ beae a obi te din",
        "optionC": "Ɛkyerɛ nkontabuo nnoɔma",
        "optionD": "Ɛka edin abien bom",
        "correctOption": "A",
        "subConcept": "Verb Definition",
        "explanation": "Adeyɛ kyerɛ adwuma, nneyɛe anaa biribi a eresi wɔ kasamu mu.",
        "remediationTip": "Verbs represent actions, states, or occurrences."
      },
      {
        "id": "q-twi-ade-2",
        "quizId": "quiz-jhs1-twi-adey",
        "questionText": "Akyerɛwde bɛn na yɛde to adeyɛ anim de kyerɛ 'Mprempren Berɛ a Ɛkɔ So' (Present Continuous)?",
        "optionA": "bɛ-",
        "optionB": "re-",
        "optionC": "a-",
        "optionD": "n-",
        "correctOption": "B",
        "subConcept": "Present Continuous Aspect",
        "explanation": "Yɛde 're-' to adeyɛ anim de kyerɛ adwuma a eresi seesei ara (e.g. rekɔ, redidi).",
        "remediationTip": "Prefix 're-' marks progressive/continuous action happening right now."
      },
      {
        "id": "q-twi-ade-3",
        "quizId": "quiz-jhs1-twi-adey",
        "questionText": "Kasamu bɛn na ɛkura adeyɛ wɔ 'Daakye Berɛ' (Future Tense) mu?",
        "optionA": "Ama kɔ sukuu daa.",
        "optionB": "Ama rekɔ sukuu.",
        "optionC": "Ama bɛkɔ sukuu ɔkyena.",
        "optionD": "Ama kɔe nnɛra.",
        "correctOption": "C",
        "subConcept": "Future Tense Marker",
        "explanation": "'bɛkɔ' kura ahyɛnsode 'bɛ-' a ɛkyerɛ daakye berɛ (future tense).",
        "remediationTip": "Prefix 'bɛ-' marks future tense in Twi."
      },
      {
        "id": "q-twi-ade-4",
        "quizId": "quiz-jhs1-twi-adey",
        "questionText": "Sɛ yɛpow adeyɛ 'kɔ' (saying does not go) a, sɛnea yɛtwerɛ no ne:",
        "optionA": "ɔnkɔ",
        "optionB": "ɔnnkɔ",
        "optionC": "ɔmmkɔ",
        "optionD": "ɔrenkɔ",
        "correctOption": "A",
        "subConcept": "Verb Negation",
        "explanation": "Yɛde 'n-' to 'kɔ' anim na yɛanya 'ɔnkɔ' (he/she does not go).",
        "remediationTip": "Prefix 'n-' negates verbs starting with k, t, d, s, etc."
      },
      {
        "id": "q-twi-ade-5",
        "quizId": "quiz-jhs1-twi-adey",
        "questionText": "Sɛ adeyɛ hyɛ ase ne 'b' (e.g., 'bɔ') na yɛpɛ sɛ yɛpow no a, akyerɛwde bɛn na yɛde to anim?",
        "optionA": "n-",
        "optionB": "m-",
        "optionC": "r-",
        "optionD": "w-",
        "correctOption": "B",
        "subConcept": "Negative Nasal Assimilation",
        "explanation": "Efisɛ 'b' yɛ bilabial consonant nti, yɛde 'm-' na ɛpow no: 'ɔmmɔ bɔɔl'.",
        "remediationTip": "Verbs starting with b or p are negated with 'm-' (e.g., mmɔ)."
      },
      {
        "id": "q-twi-ade-6",
        "quizId": "quiz-jhs1-twi-adey",
        "questionText": "Dɛn ne 'Ɔkyerɛfo' (Adjective) dwumadi?",
        "optionA": "Ɛkyerɛkyerɛ edin su mu kɔ akyiri",
        "optionB": "Ɛpow adeyɛ wɔ kasamu mu",
        "optionC": "Ɛbata akyerɛwamba ho",
        "optionD": "Ɛwie asɛmbisa kasamu",
        "correctOption": "A",
        "subConcept": "Adjective Definition",
        "explanation": "Ɔkyerɛfo kyerɛkyerɛ edin su (ahosuo, kɛseɛ, bɔberɛ) mu kɔ akyiri.",
        "remediationTip": "Adjectives describe or qualify nouns."
      },
      {
        "id": "q-twi-ade-7",
        "quizId": "quiz-jhs1-twi-adey",
        "questionText": "Wɔ Twi kasamu mu no, baabi bɛn na ɔkyerɛfo taa gyina?",
        "optionA": "Edin no anim pɛpɛɛpɛ",
        "optionB": "Edin no akyi daa",
        "optionC": "Kasamu no ahyɛase",
        "optionD": "Akyi-pɔ no akyi",
        "correctOption": "B",
        "subConcept": "Adjective Placement",
        "explanation": "Wɔ Twi mu no, ɔkyerɛfo di edin akyi (e.g., 'dua kɛse', 'atade kɔkɔɔ').",
        "remediationTip": "Unlike English, Twi adjectives come AFTER the noun they describe."
      },
      {
        "id": "q-twi-ade-8",
        "quizId": "quiz-jhs1-twi-adey",
        "questionText": "Wɔ kasamu 'Kofi tuu mmirikatuo kɛse' mu no, asɛmfua bɛn ne adeyɛ no?",
        "optionA": "Kofi",
        "optionB": "tuu",
        "optionC": "mmirikatuo",
        "optionD": "kɛse",
        "correctOption": "B",
        "subConcept": "Verb Identification",
        "explanation": "'tuu' (ran) na ɛyɛ adeyɛ (past tense of 'tu').",
        "remediationTip": "'tuu' indicates the action performed by the subject."
      },
      {
        "id": "q-twi-ade-9",
        "quizId": "quiz-jhs1-twi-adey",
        "questionText": "Wɔ kasamu 'Ama hyɛ atade tuntum' mu no, asɛmfua bɛn ne ɔkyerɛfo no?",
        "optionA": "Ama",
        "optionB": "hyɛ",
        "optionC": "atade",
        "optionD": "tuntum",
        "correctOption": "D",
        "subConcept": "Adjective Identification",
        "explanation": "'tuntum' (black) kyerɛ atade no ahosuo, enti ɛyɛ ɔkyerɛfo.",
        "remediationTip": "'tuntum' describes the color of the dress."
      },
      {
        "id": "q-twi-ade-10",
        "quizId": "quiz-jhs1-twi-adey",
        "questionText": "Kasamu a adeyɛ no wom wɔ 'Berɛ a Atwam' (Past Tense) mu ne:",
        "optionA": "Kwadwo redidi.",
        "optionB": "Kwadwo didii anɔpa yi.",
        "optionC": "Kwadwo bɛdidi ɔkyena.",
        "optionD": "Kwadwo didi daa.",
        "correctOption": "B",
        "subConcept": "Past Tense Marker",
        "explanation": "'didii' kura nnyegyei a wɔatwe no tenten (-i) a ɛkyerɛ sɛ adwuma no atwam.",
        "remediationTip": "Lengthened terminal vowel or '-e/-ɛ' suffix marks past tense."
      }
    ]
  },
  "jhs1-twi-t5-kasamu": {
    "id": "quiz-jhs1-twi-kasamu",
    "topicId": "jhs1-twi-t5-kasamu",
    "title": "Kasamu Nhyehyɛe ne Akyerɛw Nsɛnkyerɛnne Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-kas-1",
        "quizId": "quiz-jhs1-twi-kasamu",
        "questionText": "Nhyehyɛe titiriw bɛn na Akuapem Twi kasamu kura?",
        "optionA": "SVO (Ɔyɛfo - Adeyɛ - Adeyɛfo)",
        "optionB": "SOV (Ɔyɛfo - Adeyɛfo - Adeyɛ)",
        "optionC": "VSO (Adeyɛ - Ɔyɛfo - Adeyɛfo)",
        "optionD": "OVS (Adeyɛfo - Adeyɛ - Ɔyɛfo)",
        "correctOption": "A",
        "subConcept": "SVO Word Order",
        "explanation": "Akuapem Twi di SVO nhyehyɛe akyi: Subject (Ɔyɛfo) - Verb (Adeyɛ) - Object (Adeyɛfo).",
        "remediationTip": "Standard Twi sentence order is Subject + Verb + Object (SVO)."
      },
      {
        "id": "q-twi-kas-2",
        "quizId": "quiz-jhs1-twi-kasamu",
        "questionText": "Wɔ kasamu 'Yaw tɔɔ aponkye' mu no, hwan ne 'Ɔyɛfo' (Subject)?",
        "optionA": "Yaw",
        "optionB": "tɔɔ",
        "optionC": "aponkye",
        "optionD": "Yaw tɔɔ",
        "correctOption": "A",
        "subConcept": "Subject Identification",
        "explanation": "'Yaw' na ɔreyɛ adwuma no (tɔɔ), enti ɔno ne Ɔyɛfo no.",
        "remediationTip": "The entity performing the action is the subject."
      },
      {
        "id": "q-twi-kas-3",
        "quizId": "quiz-jhs1-twi-kasamu",
        "questionText": "Kasamu a ɛwie ne asɛmbisa nsɛnkyerɛnne (?) na wɔfrɛ no:",
        "optionA": "Asɛmka Kasamu",
        "optionB": "Asɛmbisa Kasamu",
        "optionC": "Ahyɛde Kasamu",
        "optionD": "Ahodwiriw Kasamu",
        "correctOption": "B",
        "subConcept": "Interrogative Sentences",
        "explanation": "Asɛmbisa Kasamu bisa asɛm na ɛwie ne asɛmbisa nsɛnkyerɛnne (?).",
        "remediationTip": "Questions that ask for info and end with '?' are interrogative sentences."
      },
      {
        "id": "q-twi-kas-4",
        "quizId": "quiz-jhs1-twi-kasamu",
        "questionText": "Kasamu 'Bue pono no seesei ara!' yɛ kasamu bɛn?",
        "optionA": "Asɛmbisa Kasamu",
        "optionB": "Ahyɛde Kasamu",
        "optionC": "Asɛmka Kasamu",
        "optionD": "Kasamufa",
        "correctOption": "B",
        "subConcept": "Imperative Sentences",
        "explanation": "Ɛma ahyɛde pɔtee ma obi yɛ biribi, enti ɛyɛ Ahyɛde Kasamu (Imperative).",
        "remediationTip": "A command giving an order is an imperative sentence."
      },
      {
        "id": "q-twi-kas-5",
        "quizId": "quiz-jhs1-twi-kasamu",
        "questionText": "Akyerɛw nsɛnkyerɛnne bɛn na yɛde wie Asɛmka Kasamu (Declarative sentence)?",
        "optionA": "Asɛmbisa nsɛnkyerɛnne (?)",
        "optionB": "Akyi-pɔ / Ewie-pɔ (.)",
        "optionC": "Ahodwiriw nsɛnkyerɛnne (!)",
        "optionD": "Kɔma (,)",
        "correctOption": "B",
        "subConcept": "Full Stop Usage",
        "explanation": "Asɛmka kasamu wie ne akyi-pɔ (full stop - .).",
        "remediationTip": "Declarative statements end with a period/full stop (.)."
      },
      {
        "id": "q-twi-kas-6",
        "quizId": "quiz-jhs1-twi-kasamu",
        "questionText": "Kasamu bɛn na ɛkyerɛ 'Ahodwiriw' (Exclamation)?",
        "optionA": "Ao, dua no kɛseɛ bɛn ni!",
        "optionB": "Me kɔ sukuu daa.",
        "optionC": "Wobɛkɔ fie anwummerɛ yi?",
        "optionD": "Bra ha ntɛm.",
        "correctOption": "A",
        "subConcept": "Exclamatory Sentences",
        "explanation": "Kasamu no da ahodwiriw ne anigye kɛse adi na ɛwie ne (!) nsɛnkyerɛnne.",
        "remediationTip": "Sentences expressing strong surprise ending with '!' are exclamatory."
      },
      {
        "id": "q-twi-kas-7",
        "quizId": "quiz-jhs1-twi-kasamu",
        "questionText": "Dwuma bɛn na Kɔma (,) di wɔ kasamu mu?",
        "optionA": "Ɛwie kasamu koraa",
        "optionB": "Ɛma okenkanfo gye n'ahome kakra na ɛpaepae nsɛm ntam",
        "optionC": "Ɛbisa asɛm pɔtee",
        "optionD": "Ɛsesa edin kɔ adeyɛ mu",
        "correctOption": "B",
        "subConcept": "Comma Usage",
        "explanation": "Kɔma (comma) ma yɛgye ahome kakra na yɛpaepae nnoɔma a wɔahyehyɛ ntam.",
        "remediationTip": "Commas indicate short pauses and separate list items."
      },
      {
        "id": "q-twi-kas-8",
        "quizId": "quiz-jhs1-twi-kasamu",
        "questionText": "Mmara bɛn na ɛfa kasamu ahyɛase akyerɛwde ho?",
        "optionA": "Wɔde akyerɛw ketewa biara hyɛ ase",
        "optionB": "Wɔde akyerɛw kɛse (capital letter) na ɛhyɛ kasamu biara ase",
        "optionC": "Wɔmfa akyerɛwamba nhyɛ ase",
        "optionD": "Wɔde kɔma hyɛ ase",
        "correctOption": "B",
        "subConcept": "Capitalization Rules",
        "explanation": "Kasamu pa biara hyɛ ase ne akyerɛw kɛse (capital letter).",
        "remediationTip": "Every sentence must begin with an uppercase/capital letter."
      },
      {
        "id": "q-twi-kas-9",
        "quizId": "quiz-jhs1-twi-kasamu",
        "questionText": "Wɔ kasamu 'Kofi tow bɔɔl' mu no, bɔɔl gyina hɔ ma dɛn?",
        "optionA": "Ɔyɛfo",
        "optionB": "Adeyɛ",
        "optionC": "Adeyɛfo / Nea adeyɛ to no (Object)",
        "optionD": "Ɔkyerɛfo",
        "correctOption": "C",
        "subConcept": "Direct Object Identification",
        "explanation": "'bɔɔl' ne ade a adeyɛ 'tow' no to no, enti ɛno ne Adeyɛfo (Object).",
        "remediationTip": "The direct recipient of the action is the Object."
      },
      {
        "id": "q-twi-kas-10",
        "quizId": "quiz-jhs1-twi-kasamu",
        "questionText": "Kasamu a wɔahyehyɛ no pɛpɛɛpɛ a mfomso biara nni mu ne:",
        "optionA": "kofi kɔ sukuu nnɛ?",
        "optionB": "Kofi kɔ sukuu nnɛ.",
        "optionC": "kofi kɔ sukuu nnɛ!",
        "optionD": "Kofi kɔ sukuu nnɛ,",
        "correctOption": "B",
        "subConcept": "Standard Sentence Punctuation",
        "explanation": "'Kofi kɔ sukuu nnɛ.' hyɛ ase ne capital 'K' na ɛwie ne akyi-pɔ (.).",
        "remediationTip": "Proper sentence starts with capital letter and ends with a full stop."
      }
    ]
  },
  "jhs1-twi-t6-nkyea": {
    "id": "quiz-jhs1-twi-nkyea",
    "topicId": "jhs1-twi-t6-nkyea",
    "title": "Nkyea ne Nnyeso wɔ Akuapem Twi mu Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-nky-1",
        "quizId": "quiz-jhs1-twi-nkyea",
        "questionText": "Nkyea bɛn na yɛde kyea anɔpatutuutu wɔ Akuapem Twi mu?",
        "optionA": "Mema wo adwo",
        "optionB": "Mema wo aha",
        "optionC": "Mema wo akye (Makye)",
        "optionD": "Nante yiye",
        "correctOption": "C",
        "subConcept": "Morning Greeting",
        "explanation": "Anɔpa nkyea ne 'Mema wo akye' anaa 'Makye'.",
        "remediationTip": "'Makye' / 'Mema wo akye' is the greeting for morning."
      },
      {
        "id": "q-twi-nky-2",
        "quizId": "quiz-jhs1-twi-nkyea",
        "questionText": "Sɛ wokyea Agya anaa barima panin a, ne nnyeso pa ne dɛn?",
        "optionA": "Yaa-Ena",
        "optionB": "Yaa-Agya",
        "optionC": "Yaa-Nua",
        "optionD": "Yaa-Asɔn",
        "correctOption": "B",
        "subConcept": "Response to Father/Elder Male",
        "explanation": "Sɛ wokyea agya anaa barima panin a, ne nnyeso ne 'Yaa-Agya'.",
        "remediationTip": "Response to father or senior male is 'Yaa-Agya'."
      },
      {
        "id": "q-twi-nky-3",
        "quizId": "quiz-jhs1-twi-nkyea",
        "questionText": "Sɛ wokyea Ɛna anaa ɔbea panin a, ne nnyeso pa ne dɛn?",
        "optionA": "Yaa-Agya",
        "optionB": "Yaa-Ena",
        "optionC": "Yaa-Nua",
        "optionD": "Yaa-Obosi",
        "correctOption": "B",
        "subConcept": "Response to Mother/Elder Female",
        "explanation": "Sɛ wokyea ɛna anaa ɔbea panin a, ne nnyeso ne 'Yaa-Ena'.",
        "remediationTip": "Response to mother or senior female is 'Yaa-Ena'."
      },
      {
        "id": "q-twi-nky-4",
        "quizId": "quiz-jhs1-twi-nkyea",
        "questionText": "Nsa bɛn na Akan amanne kyerɛ sɛ wɔmfa nkyea obi da korakora?",
        "optionA": "Nsa nifa",
        "optionB": "Nsa benkum",
        "optionC": "Nsa mmienu",
        "optionD": "Nsatea",
        "correctOption": "B",
        "subConcept": "Prohibition of Left Hand",
        "explanation": "Nsa benkum a wɔde kyea yɛ akyiwade kɛse a ɛkyerɛ obubɔne ne nidi a enni hɔ.",
        "remediationTip": "Never use the left hand (nsa benkum) to greet or gesture."
      },
      {
        "id": "q-twi-nky-5",
        "quizId": "quiz-jhs1-twi-nkyea",
        "questionText": "Sɛ wokɔ nnipakuw anaa agyina bi mu a, fahe na yɛhyɛ nkyea ase kɔ baabi?",
        "optionA": "Firi benkum kɔ nifa",
        "optionB": "Firi nifa kɔ benkum daa",
        "optionC": "Firi mfinimfini",
        "optionD": "Baabiara a wopɛ",
        "correctOption": "B",
        "subConcept": "Direction of Greeting in Gathering",
        "explanation": "Wɔ Akanfo amanne mu no, yɛhyɛ nkyea ase firi nifa so kɔ benkum so daa.",
        "remediationTip": "Always greet a gathering from your right to your left."
      },
      {
        "id": "q-twi-nky-6",
        "quizId": "quiz-jhs1-twi-nkyea",
        "questionText": "Nkyea bɛn na yɛde ma obi a ɔredidi wɔ afe mu?",
        "optionA": "Akwaaba",
        "optionB": "Kuta mu o / Ahyɛda o",
        "optionC": "Kuse",
        "optionD": "Yaagya",
        "correctOption": "B",
        "subConcept": "Greeting Someone Eating",
        "explanation": "Sɛ obi redidi a, yɛka sɛ 'Kuta mu o' anaa 'Ahyɛda o' de kyea no.",
        "remediationTip": "When meeting someone eating, politely say 'Kuta mu o' or 'Kitam'."
      },
      {
        "id": "q-twi-nky-7",
        "quizId": "quiz-jhs1-twi-nkyea",
        "questionText": "Nkyea bɛn na yɛde kyea wɔ anwummerɛ bere a owia akɔtɔ?",
        "optionA": "Mema wo aha",
        "optionB": "Mema wo adwo (Madwo)",
        "optionC": "Makye",
        "optionD": "Nante yiye",
        "correctOption": "B",
        "subConcept": "Evening Greeting",
        "explanation": "Anwummerɛ nkyea ne 'Mema wo adwo' anaa 'Madwo'.",
        "remediationTip": "'Madwo' / 'Mema wo adwo' is the evening greeting."
      },
      {
        "id": "q-twi-nky-8",
        "quizId": "quiz-jhs1-twi-nkyea",
        "questionText": "Sɛ obi hyehyɛ n'adwuma mu guamu a, nkyea bɛn na yɛde ma no?",
        "optionA": "Adwuma o / Ayekoo",
        "optionB": "Kuse",
        "optionC": "Yaa-Agya",
        "optionD": "Duue",
        "correctOption": "A",
        "subConcept": "Greeting Someone Working",
        "explanation": "Sɛ obi reyɛ adwuma a, yɛma no 'Ayekoo' anaa 'Adwuma o', na obua sɛ 'Yaa-aye'.",
        "remediationTip": "Praise and greet a worker with 'Ayekoo'."
      },
      {
        "id": "q-twi-nky-9",
        "quizId": "quiz-jhs1-twi-nkyea",
        "questionText": "Mfaso bɛn na ɛwɔ nkyea so wɔ Akuapem man mu?",
        "optionA": "Ɛkyerɛ obu, aban, anigye ne nidi a ɛda nnipa ntam",
        "optionB": "Ɛma obi nya sika bebree ntɛm",
        "optionC": "Ɛsɛe abusuafo nkitahodi",
        "optionD": "Ɛpam ahɔho firi kurom",
        "correctOption": "A",
        "subConcept": "Significance of Greetings",
        "explanation": "Nkyea bu nipa anim kwan na ɛda obu ne ayamye adi wɔ amansan mu.",
        "remediationTip": "Greetings foster communal respect, peace, and harmony."
      },
      {
        "id": "q-twi-nky-10",
        "quizId": "quiz-jhs1-twi-nkyea",
        "questionText": "Sɛ wokyea wo mfɛfo anaa wo nua a, ne nnyeso pa ne dɛn?",
        "optionA": "Yaa-Agya",
        "optionB": "Yaa-Ena",
        "optionC": "Yaa-Nua",
        "optionD": "Yaa-Nana",
        "correctOption": "C",
        "subConcept": "Peer Greeting Response",
        "explanation": "Sɛ wokyea wo nua anaa wo tipɛn a, obua sɛ 'Yaa-Nua'.",
        "remediationTip": "Response between siblings and peers is 'Yaa-Nua'."
      }
    ]
  },
  "jhs1-twi-t7-kradin": {
    "id": "quiz-jhs1-twi-kradin",
    "topicId": "jhs1-twi-t7-kradin",
    "title": "Akanfo Kradin ne Agyadin Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-kra-1",
        "quizId": "quiz-jhs1-twi-kradin",
        "questionText": "Kradin a wɔde ma barima a wɔwoo no Fiada ne bɛn?",
        "optionA": "Kwasi",
        "optionB": "Kwadwo",
        "optionC": "Kofi",
        "optionD": "Kwame",
        "correctOption": "C",
        "subConcept": "Friday Male Soul Name",
        "explanation": "Fiada barima kradin ne Kofi.",
        "remediationTip": "Friday male born is Kofi; female is Afia/Afua."
      },
      {
        "id": "q-twi-kra-2",
        "quizId": "quiz-jhs1-twi-kradin",
        "questionText": "Kradin a wɔde ma ɔbea a wɔwoo no Dwoada ne bɛn?",
        "optionA": "Akua",
        "optionB": "Adwoa",
        "optionC": "Abenaa",
        "optionD": "Yaa",
        "correctOption": "B",
        "subConcept": "Monday Female Soul Name",
        "explanation": "Dwoada bea kradin ne Adwoa (barima ne Kwadwo).",
        "remediationTip": "Monday female born is Adwoa; male is Kwadwo."
      },
      {
        "id": "q-twi-kra-3",
        "quizId": "quiz-jhs1-twi-kradin",
        "questionText": "Mmrane (Appellation) bɛn na ɛbata kradin 'Kwasi' ho?",
        "optionA": "Bodua / Obosi",
        "optionB": "Okoto",
        "optionC": "Preko",
        "optionD": "Atoapem",
        "correctOption": "A",
        "subConcept": "Sunday Name Appellation",
        "explanation": "Kwasi mmrane ne Bodua anaa Obosi.",
        "remediationTip": "Kwasi's appellation is Bodua / Obosi."
      },
      {
        "id": "q-twi-kra-4",
        "quizId": "quiz-jhs1-twi-kradin",
        "questionText": "Mmrane 'Preko' bata kradin bɛn ho?",
        "optionA": "Kofi",
        "optionB": "Kwaku",
        "optionC": "Yaw",
        "optionD": "Kwabena",
        "correctOption": "C",
        "subConcept": "Thursday Name Appellation",
        "explanation": "Yaw mmrane ne 'Preko' (the bold/brave warrior).",
        "remediationTip": "Yaw corresponds to the appellation 'Preko'."
      },
      {
        "id": "q-twi-kra-5",
        "quizId": "quiz-jhs1-twi-kradin",
        "questionText": "Kradin a wɔde to barima a wɔwoo no Memeneda ne bɛn?",
        "optionA": "Kwame",
        "optionB": "Kwabena",
        "optionC": "Kwaku",
        "optionD": "Kwasi",
        "correctOption": "A",
        "subConcept": "Saturday Male Soul Name",
        "explanation": "Memeneda barima kradin ne Kwame (bea ne Ama).",
        "remediationTip": "Saturday male born is Kwame; female is Ama."
      },
      {
        "id": "q-twi-kra-6",
        "quizId": "quiz-jhs1-twi-kradin",
        "questionText": "Mmrane bɛn na ɛbata kradin 'Kwadwo' ho?",
        "optionA": "Okoto / Okotoa",
        "optionB": "Bodua",
        "optionC": "Ogyam",
        "optionD": "Atobi",
        "correctOption": "A",
        "subConcept": "Monday Name Appellation",
        "explanation": "Kwadwo mmrane ne Okoto / Okotoa (the humble, calm soul).",
        "remediationTip": "Kwadwo is associated with Okoto."
      },
      {
        "id": "q-twi-kra-7",
        "quizId": "quiz-jhs1-twi-kradin",
        "questionText": "Sɛ wɔwo mma ntafo (twins) a, din bɛn na wɔtaa de to wɔn?",
        "optionA": "Ata ne Ataa",
        "optionB": "Tawiah ne Nyankomago",
        "optionC": "Kofi ne Ama",
        "optionD": "Ofori ne Addo",
        "correctOption": "A",
        "subConcept": "Twin Names",
        "explanation": "Ntaafo din ne Ata (barima) ne Ataa (bea).",
        "remediationTip": "Twins in Akan tradition are named Ata (boy) and Ataa (girl)."
      },
      {
        "id": "q-twi-kra-8",
        "quizId": "quiz-jhs1-twi-kradin",
        "questionText": "Abofra a wɔwoo no ntafo akyi pɛpɛɛpɛ no, din bɛn na wɔde to no?",
        "optionA": "Nyankomago",
        "optionB": "Tawiah",
        "optionC": "Abam",
        "optionD": "Badu",
        "correctOption": "B",
        "subConcept": "Child Born After Twins",
        "explanation": "Abofra a odi ntafo akyi no, ne din ne Tawiah.",
        "remediationTip": "The child born directly after twins is named Tawiah."
      },
      {
        "id": "q-twi-kra-9",
        "quizId": "quiz-jhs1-twi-kradin",
        "questionText": "Dɛn ne 'Agyadin' wɔ Akanfo amanne mu?",
        "optionA": "Din a abofra kra kura fi awo mu",
        "optionB": "Din a agya de firi n'abusua anaa n'awofo mu to n'abofra",
        "optionC": "Din a sukuu akyerɛkyerɛfo de to abofra",
        "optionD": "Din a wɔde to nsuo ho",
        "correctOption": "B",
        "subConcept": "Patrilineal Surname / Agyadin",
        "explanation": "Agyadin yɛ din a agya de fi ne nuanom anaa n'awofo din mu de to n'abofra (e.g. Ofori, Addo).",
        "remediationTip": "Agyadin is the patronymic/surname bestowed by the father."
      },
      {
        "id": "q-twi-kra-10",
        "quizId": "quiz-jhs1-twi-kradin",
        "questionText": "Wukuada bea kradin pɔtee ne bɛn?",
        "optionA": "Abenaa",
        "optionB": "Akua",
        "optionC": "Yaa",
        "optionD": "Afia",
        "correctOption": "B",
        "subConcept": "Wednesday Female Soul Name",
        "explanation": "Wukuada bea kradin ne Akua (barima ne Kwaku).",
        "remediationTip": "Wednesday female born is Akua; male is Kwaku."
      }
    ]
  },
  "jhs1-twi-t8-abusua": {
    "id": "quiz-jhs1-twi-abusua",
    "topicId": "jhs1-twi-t8-abusua",
    "title": "Abusua Nhyehyɛe wɔ Akuapem Man mu Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-abu-1",
        "quizId": "quiz-jhs1-twi-abusua",
        "questionText": "Akanfo mmusua akɛse no si ahe pɛpɛɛpɛ?",
        "optionA": "Anan (4)",
        "optionB": "Ason (7)",
        "optionC": "Awotwe (8)",
        "optionD": "Du (10)",
        "correctOption": "C",
        "subConcept": "Eight Akan Clans",
        "explanation": "Akanfo mmusua akɛse no yɛ awotwe (8).",
        "remediationTip": "There are 8 principal Akan maternal clans (Mmusua Awotwe)."
      },
      {
        "id": "q-twi-abu-2",
        "quizId": "quiz-jhs1-twi-abusua",
        "questionText": "Ahyɛnsode (totem) bɛn na ɛbata Ɔyokoɔ abusua ho?",
        "optionA": "Ɔsebo (Leopard)",
        "optionB": "Ɔkɔdeɛ (Falcon / Hawk)",
        "optionC": "Ɔkraman (Dog)",
        "optionD": "Akoo (Parrot)",
        "correctOption": "B",
        "subConcept": "Oyoko Clan Totem",
        "explanation": "Ɔyokoɔ abusua ahyɛnsode ne Ɔkɔdeɛ (Falcon/Hawk).",
        "remediationTip": "Oyoko clan's symbol is the Ɔkɔdeɛ (falcon/hawk)."
      },
      {
        "id": "q-twi-abu-3",
        "quizId": "quiz-jhs1-twi-abusua",
        "questionText": "Ahyɛnsode bɛn na ɛbata Aduana abusua ho?",
        "optionA": "Ɔkraman a ɔkura ogya n'anomu",
        "optionB": "Kwaakwaadabi",
        "optionC": "Ɔpɛte",
        "optionD": "Ɛkoɔ",
        "correctOption": "A",
        "subConcept": "Aduana Clan Totem",
        "explanation": "Aduana abusua ahyɛnsode ne Ɔkraman a ɔkura gya wɔ n'anomu.",
        "remediationTip": "Aduana clan's symbol is the dog with fire in its mouth."
      },
      {
        "id": "q-twi-abu-4",
        "quizId": "quiz-jhs1-twi-abusua",
        "questionText": "Akanfo gye di sɛ abofra nya 'mogya' firi hwan nkyɛn?",
        "optionA": "Agya",
        "optionB": "Maame",
        "optionC": "N'adamfo",
        "optionD": "Ɔhene",
        "correctOption": "B",
        "subConcept": "Matrilineal Blood Origin",
        "explanation": "Akanfo gye di sɛ mogya fi maame nkyɛn, na sunsum fi agya nkyɛn.",
        "remediationTip": "Blood (mogya) is inherited maternally; spirit (sunsum) paternally."
      },
      {
        "id": "q-twi-abu-5",
        "quizId": "quiz-jhs1-twi-abusua",
        "questionText": "Hwan ne 'Wɔfa' wɔ Akan abusua mu?",
        "optionA": "Agya nua barima",
        "optionB": "Maame nua barima",
        "optionC": "Maame nuabea",
        "optionD": "Agya papa",
        "correctOption": "B",
        "subConcept": "Maternal Uncle Role",
        "explanation": "Maame nua barima na wɔfrɛ no Wɔfa (maternal uncle).",
        "remediationTip": "Wɔfa is the maternal uncle (mother's brother)."
      },
      {
        "id": "q-twi-abu-6",
        "quizId": "quiz-jhs1-twi-abusua",
        "questionText": "Hwan ne 'Sewaa' wɔ Akan abusua mu?",
        "optionA": "Maame nuabea",
        "optionB": "Agya nuabea",
        "optionC": "Maame maame",
        "optionD": "Wɔfa yere",
        "correctOption": "B",
        "subConcept": "Paternal Aunt Role",
        "explanation": "Agya nuabea na wɔfrɛ no Sewaa (paternal aunt).",
        "remediationTip": "Sewaa is the father's sister (paternal aunt)."
      },
      {
        "id": "q-twi-abu-7",
        "quizId": "quiz-jhs1-twi-abusua",
        "questionText": "Ahyɛnsode bɛn na ɛbata Asona abusua ho?",
        "optionA": "Kwaakwaadabi / Anene (Crow) anaa Ɔwɔ",
        "optionB": "Ɔsebo",
        "optionC": "Ɛkoɔ",
        "optionD": "Ɔkɔdeɛ",
        "correctOption": "A",
        "subConcept": "Asona Clan Totem",
        "explanation": "Asona abusua ahyɛnsode ne Kwaakwaadabi (crow) anaa ɔwɔ.",
        "remediationTip": "Asona clan's totem is the crow (kwaakwaadabi) or snake."
      },
      {
        "id": "q-twi-abu-8",
        "quizId": "quiz-jhs1-twi-abusua",
        "questionText": "Ahyɛnsode bɛn na ɛbata Bretuo abusua ho?",
        "optionA": "Ɔsebo / Ɛtwi (Leopard)",
        "optionB": "Akoo",
        "optionC": "Ɔkraman",
        "optionD": "Apan",
        "correctOption": "A",
        "subConcept": "Bretuo Clan Totem",
        "explanation": "Bretuo abusua ahyɛnsode ne Ɔsebo (Leopard).",
        "remediationTip": "Bretuo clan's emblem is the leopard (Ɔsebo)."
      },
      {
        "id": "q-twi-abu-9",
        "quizId": "quiz-jhs1-twi-abusua",
        "questionText": "Akan amanne mu no, dɛn nti na obi nware ne busuani a wɔfiri abusua koro mu?",
        "optionA": "Efisɛ wɔkura mogya koro na wɔbu no sɛ nuanom pɛpɛɛpɛ (Incest taboo)",
        "optionB": "Efisɛ sika nni hɔ",
        "optionC": "Efisɛ ahemfo mpene so",
        "optionD": "Efisɛ agya mpɛ saa awareɛ no",
        "correctOption": "A",
        "subConcept": "Clan Exogamy Taboo",
        "explanation": "Wɔbu nnipa a wɔwɔ abusua koro mu sɛ mogya koro, enti awareɛ a ɛte saa yɛ akyiwade (mogyafra).",
        "remediationTip": "Marriage within the same maternal clan is considered incestuous (mogyafra)."
      },
      {
        "id": "q-twi-abu-10",
        "quizId": "quiz-jhs1-twi-abusua",
        "questionText": "Dwuma titiriw bɛn na Agya Ntoro/Sunsum di wɔ abofra abrabɔ mu?",
        "optionA": "Ɛma abofra no sunsum, suban pa ne ahobammɔ",
        "optionB": "Ɛsesa maame abusua",
        "optionC": "Ɛkyerɛ sɛ abofra no nni hene da",
        "optionD": "Ɛsɛe abofra no ntetee",
        "correctOption": "A",
        "subConcept": "Role of Paternal Ntoro",
        "explanation": "Agya Ntoro na ɛbɔ abofra no ho ban sunsum mu na ɛma no suban pa.",
        "remediationTip": "The father's ntoro bestows spiritual protection and moral character."
      }
    ]
  },
  "jhs1-twi-t9-abawobo": {
    "id": "quiz-jhs1-twi-abawobo",
    "topicId": "jhs1-twi-t9-abawobo",
    "title": "Abawobɔ ne Abadinto Ho Amanne Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-aba-1",
        "quizId": "quiz-jhs1-twi-abawobo",
        "questionText": "Nnafua ahe na Akanfo twɛn ansa na wɔabɔ abawobɔ na wɔato abofra foforo din?",
        "optionA": "Nnafua ebiasa (3)",
        "optionB": "Nnafua awotwe (8)",
        "optionC": "Nnafua aduanan (40)",
        "optionD": "Bosome koro",
        "correctOption": "B",
        "subConcept": "Outdooring 8th Day Timing",
        "explanation": "Wɔtwɛn nnafua awotwe (8 days) ansa na wɔayɛ abadinto no.",
        "remediationTip": "Akan outdooring and naming takes place on the 8th day after birth."
      },
      {
        "id": "q-twi-aba-2",
        "quizId": "quiz-jhs1-twi-abawobo",
        "questionText": "Bere bɛn wɔ da no mu na wɔtaa yɛ abadinto amanne no?",
        "optionA": "Anɔpatutuutu ansa na owia apue",
        "optionB": "Awia keteketee",
        "optionC": "Anadwutuutu",
        "optionD": "Anwummerɛ bere a woredidi",
        "correctOption": "A",
        "subConcept": "Time of Outdooring Ceremony",
        "explanation": "Wɔyɛ abadinto amanne no anɔpatutuutu ansa na owia repue kɛse.",
        "remediationTip": "Outdooring rites are conducted at dawn/early morning."
      },
      {
        "id": "q-twi-aba-3",
        "quizId": "quiz-jhs1-twi-abawobo",
        "questionText": "Amanne titiriw bɛn na ɔpanyin no de nsu ne nsa yɛ ma abofra no?",
        "optionA": "Ɔde gu ne nsam ma ɔnom",
        "optionB": "Ɔde ka abofra no tɛkrɛma mprɛnsa de kyerɛkyerɛ nokwaredi",
        "optionC": "Ɔde ware no",
        "optionD": "Ɔde petepete fie no nyinaa",
        "correctOption": "B",
        "subConcept": "Water and Wine Ritual",
        "explanation": "Ɔde ka abofra no tɛkrɛma mprɛnsa ka sɛ: 'Sɛ woka sɛ nsu a, ɛnneɛ nsu; sɛ woka sɛ nsa a, ɛnneɛ nsa'.",
        "remediationTip": "Water and wine are touched to the tongue 3 times to instill truthfulness."
      },
      {
        "id": "q-twi-aba-4",
        "quizId": "quiz-jhs1-twi-abawobo",
        "questionText": "Nsu ne Nsa amanne no fapem ne suban pa bɛn na ɛhwehwɛ fi abofra no nkyɛn?",
        "optionA": "Akokoɔduru",
        "optionB": "Nokwaredi ne adwumaden",
        "optionC": "Sika pɛ",
        "optionD": "Ahoɔfɛ",
        "correctOption": "B",
        "subConcept": "Truthfulness Virtue (Nokwaredi)",
        "explanation": "Amanne no kyerɛ nokwaredi — sɛ ɔbɛka nokware wɔ biribiara mu.",
        "remediationTip": "The water and wine test symbolizes moral uprightness and integrity."
      },
      {
        "id": "q-twi-aba-5",
        "quizId": "quiz-jhs1-twi-abawobo",
        "questionText": "Wɔ Akan amanne mu no, hwan na ɔwɔ asɛdeɛ sɛ ɔto abofra din?",
        "optionA": "Maame nko ara",
        "optionB": "Agya",
        "optionC": "Sukuu panyin",
        "optionD": "Kurom panyin",
        "correctOption": "B",
        "subConcept": "Father's Naming Right",
        "explanation": "Agya na ɔto abofra din efisɛ n'abofra no kura ne sunsum.",
        "remediationTip": "Naming the child is exclusively the right and responsibility of the father."
      },
      {
        "id": "q-twi-aba-6",
        "quizId": "quiz-jhs1-twi-abawobo",
        "questionText": "Nsatea bɛn na ɔpanyin no de ka abofra no tɛkrɛma bere a ɔde nsu ne nsa rehyɛ n'anomu?",
        "optionA": "Kɔkɔteɛkɔkɔ (Kokurobeti / Index finger)",
        "optionB": "Kokurobetie (Thumb)",
        "optionC": "Nsatea ketewa",
        "optionD": "Nsamfã",
        "correctOption": "A",
        "subConcept": "Finger Used in Ritual",
        "explanation": "Wɔde nsa kɔkɔteɛkɔkɔ (index finger) na ɛka abofra no tɛkrɛma.",
        "remediationTip": "The elder dips the index finger (kɔkɔteɛkɔkɔ) into the water and wine."
      },
      {
        "id": "q-twi-aba-7",
        "quizId": "quiz-jhs1-twi-abawobo",
        "questionText": "Akyɛde bɛn na agya no soma kɔma abofra no maame wɔ abadinto da no?",
        "optionA": "Tuo ne afoa",
        "optionB": "Atade, samina, ngo, ne akyɛde a wɔde hwɛ abofra no",
        "optionC": "Ntoma tuntum nkutoo",
        "optionD": "Aponkye a wawu",
        "correctOption": "B",
        "subConcept": "Paternal Outdooring Gifts",
        "explanation": "Agya no soma akyɛde (atade, samina, sika) de da maame no ase na ɔde hwɛ abofra no.",
        "remediationTip": "The father provides soap, cloth, oils, and money to appreciate the mother."
      },
      {
        "id": "q-twi-aba-8",
        "quizId": "quiz-jhs1-twi-abawobo",
        "questionText": "Adɛn nti na Akanfo twɛn nnafua awotwe ansa na wɔabɔ abawobɔ?",
        "optionA": "Wɔtwɛn de hu sɛ abofra no bɛtena wiase ampa anaa ɔbɛsan akɔ asaman",
        "optionB": "Efisɛ sika ntaa mma ntɛm",
        "optionC": "Efisɛ abofra no ntumi nna",
        "optionD": "Efisɛ ahemfo da",
        "correctOption": "A",
        "subConcept": "Reason for the 8-Day Period",
        "explanation": "Akanfo gye di sɛ abofra no yɛ ɔhɔho a ebia ɔbɛsan akɔ asaman kosii sɛ nnafua awotwe betwam.",
        "remediationTip": "The 8-day waiting period confirms whether the child has come to stay permanently."
      },
      {
        "id": "q-twi-aba-9",
        "quizId": "quiz-jhs1-twi-abawobo",
        "questionText": "Atade ahosuo bɛn na awofo ne abusuafo taa hyɛ wɔ abadinto da?",
        "optionA": "Kɔkɔɔ",
        "optionB": "Fitaa",
        "optionC": "Tuntum",
        "optionD": "Bribri",
        "correctOption": "B",
        "subConcept": "White Attire for Outdooring",
        "explanation": "Wɔhyɛ ntoma fitaa de kyerɛ anigye, nkonimdi, ne asomdwoe.",
        "remediationTip": "White clothing represents joy and victory over childbirth dangers."
      },
      {
        "id": "q-twi-aba-10",
        "quizId": "quiz-jhs1-twi-abawobo",
        "questionText": "Amanne bɛn na abusuafo ne ahɔho yɛ de hyira abofra foforo no wɔ dwumadi no wiei?",
        "optionA": "Wɔgu no aba (wɔde sika ne akyɛde ma no)",
        "optionB": "Wɔbɔ no turo",
        "optionC": "Wɔpam no firi dan mu",
        "optionD": "Wɔma no kɔ adwuma",
        "correctOption": "A",
        "subConcept": "Presentation of Gifts (Aba gu)",
        "explanation": "Wɔgu abofra no aba de kyerɛ sɛ wɔagye no ato mu na wɔhyira no.",
        "remediationTip": "Guests give cash and baby gifts ('gu aba') to bless the newborn."
      }
    ]
  },
  "jhs1-twi-t10-bragoro": {
    "id": "quiz-jhs1-twi-bragoro",
    "topicId": "jhs1-twi-t10-bragoro",
    "title": "Bra Yɛ ne Bragoro Ho Amanne Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-bra-1",
        "quizId": "quiz-jhs1-twi-bragoro",
        "questionText": "Dɛn ne 'Bragoro' wɔ Akan amanne mu?",
        "optionA": "Amanne a wɔyɛ ma abaayewa a wadu mfe mu (puberty) a wabu ne nsa a edi kan",
        "optionB": "Afahyɛ a wɔdi wɔ afe awiei",
        "optionC": "Ayeforohye a aberante ware ɔbea",
        "optionD": "Abadinto a wɔto abofra din",
        "correctOption": "A",
        "subConcept": "Puberty Rites Definition",
        "explanation": "Bragoro yɛ amanne a wɔyɛ ma abaayewa a wabu ne nsa a edi kan de kyerɛ sɛ wanyin.",
        "remediationTip": "Bragoro is the female puberty initiation ceremony in Akan culture."
      },
      {
        "id": "q-twi-bra-2",
        "quizId": "quiz-jhs1-twi-bragoro",
        "questionText": "Akyiwade kɛse bɛn na Akanfo frɛ no 'Kyiribra'?",
        "optionA": "Abaayewa a wannyɛ bragoro na mmom ɔnyinsɛnee",
        "optionB": "Abaayewa a waware panyin",
        "optionC": "Aberante a wankɔ asuaso",
        "optionD": "Obi a wankyea mpanin",
        "correctOption": "A",
        "subConcept": "Kyiribra Taboo",
        "explanation": "Kyiribra kyerɛ sɛ abaayewa bi nyinsɛn a wanyɛ bragoro, a ɛyɛ akyiwade kɛse wɔ Akanfo mu.",
        "remediationTip": "Kyiribra is the grave taboo of becoming pregnant prior to puberty rites."
      },
      {
        "id": "q-twi-bra-3",
        "quizId": "quiz-jhs1-twi-bragoro",
        "questionText": "Aduane titiriw bɛn na wɔyɛ ma brafo no we kosua ka ho wɔ bragoro berɛ mu?",
        "optionA": "Ɛmo ne nkruma",
        "optionB": "Ɛtoɔ (mashed yam with palm oil)",
        "optionC": "Banku ne mako",
        "optionD": "Fufuo ne abɛnkwan",
        "correctOption": "B",
        "subConcept": "Ɛtoɔ Ritual Food",
        "explanation": "Wɔyɛ ɛtoɔ a wɔde ngo kɔkɔɔ afra mu na wɔde kosua a yanoa ma no.",
        "remediationTip": "Brafo is fed 'ɛtoɔ' (mashed yam) and boiled whole eggs for fertility."
      },
      {
        "id": "q-twi-bra-4",
        "quizId": "quiz-jhs1-twi-bragoro",
        "questionText": "Kosua a wɔde ma brafo no we no, sɛnea ɔwe no pɛpɛɛpɛ ne sɛ:",
        "optionA": "Ɔwe no ma emu bu nkyekyem nkyekyem",
        "optionB": "Ɔmene no mũ anaa ɔwe no nyinaa a ne se nka mu",
        "optionC": "Ɔtow kyene asubɔnten mu",
        "optionD": "Ɔfa ma ne maame",
        "correctOption": "B",
        "subConcept": "Swallowing the Whole Egg",
        "explanation": "Wɔhwɛ kwan sɛ ɔbɛmene kosua no mũ anaa ɔwe no a ne se nka mu de kyerɛ awoɔ pa daakye.",
        "remediationTip": "The initiate swallows the egg whole without biting it with teeth."
      },
      {
        "id": "q-twi-bra-5",
        "quizId": "quiz-jhs1-twi-bragoro",
        "questionText": "Baabi bɛn na wɔde abaayewa no kɔware no anɔpatutuutu wɔ bragoro mu?",
        "optionA": "Asubɔnten mu",
        "optionB": "Sukuu dan mu",
        "optionC": "Guaso",
        "optionD": "Ahemfie pono akyi",
        "correctOption": "A",
        "subConcept": "Ritual Bath at the Stream",
        "explanation": "Wɔkɔware no wɔ asubɔnten mu de hohoro ne ho fi nyinaa gu.",
        "remediationTip": "A ritual purifying bath takes place at a natural stream/river."
      },
      {
        "id": "q-twi-bra-6",
        "quizId": "quiz-jhs1-twi-bragoro",
        "questionText": "Hwan na abaayewa no kɔka kyerɛ no nea edi kan bere a wabu ne nsa?",
        "optionA": "N'agya",
        "optionB": "Ne maame",
        "optionC": "Ɔhene",
        "optionD": "N'adamfo barima",
        "correctOption": "B",
        "subConcept": "First Informing the Mother",
        "explanation": "Ɔka kyerɛ ne maame, na ne maame nso kɔbɔ Ɔhemmaa anaa aberewa amanneɛ.",
        "remediationTip": "The girl confides first in her mother upon noticing menarche."
      },
      {
        "id": "q-twi-bra-7",
        "quizId": "quiz-jhs1-twi-bragoro",
        "questionText": "Ade bɛn so na abaayewa no tena bere a wɔresiesie no wɔ fie?",
        "optionA": "Kahyre (cloth pad/ring) so",
        "optionB": "Dadesɛn so",
        "optionC": "Fam anhwea so",
        "optionD": "Apono so",
        "correctOption": "A",
        "subConcept": "Sitting on Kahyre",
        "explanation": "Ɔtena kahyre so ma wɔhyɛ no kente ne ahweneɛ fɛfɛɛfɛ.",
        "remediationTip": "The initiate sits elevated on a kahyre (cloth ring pad)."
      },
      {
        "id": "q-twi-bra-8",
        "quizId": "quiz-jhs1-twi-bragoro",
        "questionText": "Tete no, asotwe bɛn na na wɔde ma aberante ne abaayewa a wɔyɛɛ Kyiribra?",
        "optionA": "Wɔpam wɔn firi kurow no mu kɔ asubɔnten agya anaa kwaem",
        "optionB": "Wɔma wɔn sika bebree",
        "optionC": "Wɔyɛ wɔn ahemfo",
        "optionD": "Wɔde wɔn kɔ sukuu kɛse mu",
        "correctOption": "A",
        "subConcept": "Consequences of Kyiribra",
        "explanation": "Wɔpam wɔn firi kurom hɔ kɔ asubɔnten agya de kyerɛ sɛ wɔasɛe kurom animuonyam.",
        "remediationTip": "Offenders of Kyiribra were banished or heavily fined and ostracized."
      },
      {
        "id": "q-twi-bra-9",
        "quizId": "quiz-jhs1-twi-bragoro",
        "questionText": "Afotu bɛn na mmerewa tu brafo no bere a wɔyɛ amanne no ma no?",
        "optionA": "Sɛnea ɔbɛhwɛ ne ho so yiye, awarefo nneyɛe pa, ne fie hwɛ",
        "optionB": "Sɛnea ɔbɛkɔ akodi mu",
        "optionC": "Sɛnea ɔbɛpam ahiafo",
        "optionD": "Sɛnea ɔbɛtwe mpanin aso",
        "correctOption": "A",
        "subConcept": "Moral and Domestic Counseling",
        "explanation": "Mmerewa no tu no fo fa suban pa, fie siesie, awareɛ ho afotu, ne nidi ho.",
        "remediationTip": "Elders provide moral, marital, and personal hygiene guidance."
      },
      {
        "id": "q-twi-bra-10",
        "quizId": "quiz-jhs1-twi-bragoro",
        "questionText": "Mfaso bɛn na Bragoro de ba abaayewa no abrabɔ mu?",
        "optionA": "Ɛhyɛ no anuonyam na ɛbɔ ne bra ho ban ma otumi ware fɛfɛɛfɛ daakye",
        "optionB": "Ɛma ɔbɛyɛ sikafo ntɛmntɛm",
        "optionC": "Ɛmma ɔnkenkan nhoma bio",
        "optionD": "Ɛma ɔpam n'abusuafo",
        "correctOption": "A",
        "subConcept": "Significance of Bragoro",
        "explanation": "Bragoro ma abaayewa no nya obu kɛse wɔ amansan anim na ɔkora ne ho so yiye.",
        "remediationTip": "Bragoro instills chastity, dignity, and readiness for adulthood."
      }
    ]
  },
  "jhs1-twi-t11-aware": {
    "id": "quiz-jhs1-twi-aware",
    "topicId": "jhs1-twi-t11-aware",
    "title": "Ayeforohye ne Aware Ho Amanne Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-awa-1",
        "quizId": "quiz-jhs1-twi-aware",
        "questionText": "Dɛn ne anammɔn a edi kan pɛ a aberante abusua fa so bere a wɔpɛ sɛ wɔware abeawa bi?",
        "optionA": "Tiri Nsa tuatua",
        "optionB": "Kɔkɔɔkɔ (Knocking rites)",
        "optionC": "Aponkye kum",
        "optionD": "Ayeforohye guaso",
        "correctOption": "B",
        "subConcept": "Knocking Ceremony (Kɔkɔɔkɔ)",
        "explanation": "Kɔkɔɔkɔ na edi kan; aberante abusua de nsa kɔbɔ abeawa no abusua pono mu kyerɛ wɔn tirimpɔw.",
        "remediationTip": "Kɔkɔɔkɔ (knocking) is the introductory step to declare marital intentions."
      },
      {
        "id": "q-twi-awa-2",
        "quizId": "quiz-jhs1-twi-aware",
        "questionText": "Adɛn nti na mmusua mmienu no yɛ 'Nhwehwɛmu' (Investigation) ansa na awareɛ no agyina?",
        "optionA": "De hu sɛ yare bɔne (kokoram, asram) anaa sekpow biara nni abusua no mu",
        "optionB": "De hu sɛ aberante no wɔ kar pii",
        "optionC": "De hu beae a wɔbɛkɔ akwantu",
        "optionD": "De pam agya no fi fie",
        "correctOption": "A",
        "subConcept": "Background Investigation (Ahwehwɛde)",
        "explanation": "Wɔhwehwɛ abusua no mu yiye na wɔanware kɔ yare bɔne, abosonsom bɔne anaa korɔnobɔ mu.",
        "remediationTip": "Families investigate hereditary diseases, criminal history, and witchcraft."
      },
      {
        "id": "q-twi-awa-3",
        "quizId": "quiz-jhs1-twi-aware",
        "questionText": "Nsa anaa sika titiriw bɛn na ɛma awareɛ gyina mmara so wɔ Akanfo amanne mu?",
        "optionA": "Akonta-gye-sekan",
        "optionB": "Tiri Nsa (Head Wine)",
        "optionC": "Kɔkɔɔkɔ nsa",
        "optionD": "Abaayewa akyɛde",
        "correctOption": "B",
        "subConcept": "Tiri Nsa Validation",
        "explanation": "Tiri Nsa na ɛma aware no gyina; sɛ wɔanma tiri nsa a, mmara mmu no sɛ awarefo.",
        "remediationTip": "Tiri Nsa seals and legalizes the marriage contract under customary law."
      },
      {
        "id": "q-twi-awa-4",
        "quizId": "quiz-jhs1-twi-aware",
        "questionText": "Hwan na wɔde 'Akonta-gye-sekan' ma no wɔ aware amanne mu?",
        "optionA": "Abeawa no nuanom mmarima (brothers)",
        "optionB": "Abeawa no maame",
        "optionC": "Ɔhene no ahenkwaa",
        "optionD": "Sukuu kyerɛkyerɛfo",
        "correctOption": "A",
        "subConcept": "Akonta-gye-sekan Recipient",
        "explanation": "Akonta-gye-sekan yɛ akyɛde a aberante de ma abeawa no nuanom mmarima (brothers-in-law).",
        "remediationTip": "Akonta-gye-sekan is paid to the bride's brothers."
      },
      {
        "id": "q-twi-awa-5",
        "quizId": "quiz-jhs1-twi-aware",
        "questionText": "Wɔ Akanfo amanne mu no, awareɛ yɛ nkitahodi a ɛda hwan ne hwan ntam?",
        "optionA": "Aberante ne abeawa no nkutoo",
        "optionB": "Mmusua mmienu no nyinaa ntam",
        "optionC": "Aban ne polisifo ntam",
        "optionD": "Adanfo mmienu ntam",
        "correctOption": "B",
        "subConcept": "Inter-Family Alliance in Marriage",
        "explanation": "Awareɛ yɛ mmusua mmienu ntam asɛm na ɛnyɛ nnipa mmienu no nkutoo ntam asɛm.",
        "remediationTip": "Traditional Akan marriage is an alliance between two extended families."
      },
      {
        "id": "q-twi-awa-6",
        "quizId": "quiz-jhs1-twi-aware",
        "questionText": "Sɛ aberante de aware nnoɔma ba a, asɛm bɛn na abeawa abusua bisa abeawa no ansa na wɔagye?",
        "optionA": "Wɔbisa no sɛ ɔpɛ aberante no ampa na wɔnnye nsa no anaa",
        "optionB": "Wɔbisa no sɛ ɔbɛkɔ borɔfo man mu anaa",
        "optionC": "Wɔbisa no sɛ otumi noa aduane",
        "optionD": "Wɔbisa no ne sukuu afe",
        "correctOption": "A",
        "subConcept": "Bride's Consent Verification",
        "explanation": "Wɔbisa abeawa no n'apɛdeɛ mprɛnsa ansa na wɔagye nsa no, na awareɛ no anyɛ ahyɛde.",
        "remediationTip": "The bride must give her free, explicit consent before drinks are received."
      },
      {
        "id": "q-twi-awa-7",
        "quizId": "quiz-jhs1-twi-aware",
        "questionText": "Dɛn ne mfaso a ɛwɔ awareɛ so ma ɔman ne abusua?",
        "optionA": "Ɛka mmusua bɔ mu na ɛma awoɔ pa ba ma abusua no kɔ so",
        "optionB": "Ɛma obiara gyae adwumayɛ",
        "optionC": "Ɛsɛe asomdwoe wɔ kurom",
        "optionD": "Ɛma wɔpam agya firi n'adwumam",
        "correctOption": "A",
        "subConcept": "Benefits of Marriage",
        "explanation": "Awareɛ ma baakoyɛ, awoɔ pa, ne nidi kɛse ba mmusua ntam.",
        "remediationTip": "Marriage strengthens communal solidarity and procreation."
      },
      {
        "id": "q-twi-awa-8",
        "quizId": "quiz-jhs1-twi-aware",
        "questionText": "Nsa a wɔde kɔbɔ kɔkɔɔkɔ no, sɛ abeawa no kpo aberante no a, dɛn na esie?",
        "optionA": "Wɔsan de nsa no ma aberante abusua na asɛm no ba awiei",
        "optionB": "Wɔhyɛ no ma ɔware aberante no",
        "optionC": "Wɔde aberante no to afiase",
        "optionD": "Wɔhyew abeawa no ntoma",
        "correctOption": "A",
        "subConcept": "Rejection of Marriage Proposal",
        "explanation": "Sɛ abeawa no ampene so a, wɔsan de nsa no ma aberante abusua asomdwoe mu.",
        "remediationTip": "If the woman refuses consent, drinks are returned peacefully."
      },
      {
        "id": "q-twi-awa-9",
        "quizId": "quiz-jhs1-twi-aware",
        "questionText": "Akyɛde bɛn na aberante taa de ma abeawa no maame de da no ase?",
        "optionA": "Tuo ne asrãfodeɛ",
        "optionB": "Ntoma pa, kente, dadesɛn, ne sika (Maame gye dadesɛn)",
        "optionC": "Mpaboa a asɛe",
        "optionD": "Krataa kɛkɛ",
        "correctOption": "B",
        "subConcept": "Mother's Cooking Pot (Dadesɛn)",
        "explanation": "Wɔma maame ntoma ne dadesɛn de da no ase wɔ abeawa no ntetee ho.",
        "remediationTip": "The bride's mother receives cloth and a cooking pot (dadesɛn) in gratitude."
      },
      {
        "id": "q-twi-awa-10",
        "quizId": "quiz-jhs1-twi-aware",
        "questionText": "Wɔ awareɛ mu no, asɛde titiriw bɛn na ɛda okunu so?",
        "optionA": "Ɔhwɛ ne yere ne ne mma yiyedi, aduane, ntoma, ne baabi a wɔbɛda so",
        "optionB": "Ɔma ne yere kɔtɔ aduane daa a ɔmma no sika",
        "optionC": "Ɔpam n'abusuafo nyinaa",
        "optionD": "Ɔntua ne mma sukuu ka",
        "correctOption": "A",
        "subConcept": "Husband's Customary Duties",
        "explanation": "Okunu asɛde ne sɛ ɔbɛhwɛ ne fie so yiye na wadɔ ne yere ne ne mma.",
        "remediationTip": "The husband must feed, shelter, clothe, and provide for his family."
      }
    ]
  },
  "jhs1-twi-t12-afahye": {
    "id": "quiz-jhs1-twi-afahye",
    "topicId": "jhs1-twi-t12-afahye",
    "title": "Akuapemfo Afahyɛ: Odwira ne Adae Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-afa-1",
        "quizId": "quiz-jhs1-twi-afahye",
        "questionText": "Afahyɛ titiriw bɛn na Akuapemfo di no afe biara wɔ Akropong-Akuapem?",
        "optionA": "Hogbetsotso",
        "optionB": "Odwira",
        "optionC": "Homowo",
        "optionD": "Aboakyer",
        "correctOption": "B",
        "subConcept": "Akuapem Odwira Festival",
        "explanation": "Odwira yɛ Akuapemfo afahyɛ kɛse a Okuapehene ne ne manfo di no wɔ Akropong.",
        "remediationTip": "The principal festival celebrated at Akropong-Akuapem is Odwira."
      },
      {
        "id": "q-twi-afa-2",
        "quizId": "quiz-jhs1-twi-afahye",
        "questionText": "Dɛn ne asɛmfua 'dwira' asekyerɛ wɔ Twi kasa mu?",
        "optionA": "Didi anigye mu",
        "optionB": "Hohoro ho / Tew ho fi (Purification)",
        "optionC": "Pam ahɔho",
        "optionD": "Tu kwan kɔ akyiri",
        "correctOption": "B",
        "subConcept": "Meaning of Odwira",
        "explanation": "'Dwira' kyerɛ hohoro ho anaa tew ho firi fi ne mmusu nyinaa ho.",
        "remediationTip": "Odwira derives from 'dwira', meaning cleansing and purification."
      },
      {
        "id": "q-twi-afa-3",
        "quizId": "quiz-jhs1-twi-afahye",
        "questionText": "Akodi kɛse bɛn nkonimdi a esii afe 1826 na ɛmaa Odwira afahyɛ kɔɔ soro kɛse wɔ Akuapem?",
        "optionA": "Katamanso akodi",
        "optionB": "Sagrenti akodi",
        "optionC": "Feyiase akodi",
        "optionD": "Yaa Asantewaa akodi",
        "correctOption": "A",
        "subConcept": "Katamanso War 1826",
        "explanation": "Katamanso akodi (1826) a Akuapemfo ne wɔn nkabomfo dii nkonim no maa Odwira gyinaa fann.",
        "remediationTip": "Odwira festival gained prominence following the 1826 Katamanso victory."
      },
      {
        "id": "q-twi-afa-4",
        "quizId": "quiz-jhs1-twi-afahye",
        "questionText": "Adae afahyɛ (Akwasidae ne Awukudae) ba nnafua ahe biara?",
        "optionA": "Nnafua aduasa (30)",
        "optionB": "Nnafua aduanan mmienu (42 days)",
        "optionC": "Nnafua aduoson (70)",
        "optionD": "Afe koro biara",
        "correctOption": "B",
        "subConcept": "Adae Cycle Duration",
        "explanation": "Adae afahyɛ kɔ so nnafua aduanan mmienu (42 days) biara.",
        "remediationTip": "Adae occurs on a 42-day rotational calendar cycle."
      },
      {
        "id": "q-twi-afa-5",
        "quizId": "quiz-jhs1-twi-afahye",
        "questionText": "Adae afahyɛ a ɛtɔ Kwasiada no, wɔfrɛ no dɛn?",
        "optionA": "Awukudae",
        "optionB": "Akwasidae",
        "optionC": "Fofie",
        "optionD": "Memenedae",
        "correctOption": "B",
        "subConcept": "Akwasidae Identification",
        "explanation": "Adae a ɛtɔ Kwasiada no ne Akwasidae.",
        "remediationTip": "Adae falling on Sunday is Akwasidae."
      },
      {
        "id": "q-twi-afa-6",
        "quizId": "quiz-jhs1-twi-afahye",
        "questionText": "Adae afahyɛ a ɛtɔ Wukuada no, wɔfrɛ no dɛn?",
        "optionA": "Akwasidae",
        "optionB": "Awukudae",
        "optionC": "Kurabena",
        "optionD": "Dapaa",
        "correctOption": "B",
        "subConcept": "Awukudae Identification",
        "explanation": "Adae a ɛtɔ Wukuada no ne Awukudae.",
        "remediationTip": "Adae falling on Wednesday is Awukudae."
      },
      {
        "id": "q-twi-afa-7",
        "quizId": "quiz-jhs1-twi-afahye",
        "questionText": "Amanne titiriw bɛn na ahemfo yɛ wɔ Nkonwafie wɔ Adae afahyɛ berɛ mu?",
        "optionA": "Wɔgu nsa ma nananom nsamanfo de srɛ asomdwoe ne nhyira ma ɔman no",
        "optionB": "Wɔgu nkonwa no nyinaa gu fam",
        "optionC": "Wɔtwerɛ mfonini gu nkonwa no so",
        "optionD": "Wɔtɔn nkonwa tuntum no",
        "correctOption": "A",
        "subConcept": "Libation in Stool Room",
        "explanation": "Wɔgu nsa na wɔbɔ mpae ma nsamanfo ahemfo wɔ nkonwafie.",
        "remediationTip": "Chiefs pour libation to ancestors in the black stool room on Adae."
      },
      {
        "id": "q-twi-afa-8",
        "quizId": "quiz-jhs1-twi-afahye",
        "questionText": "Beae pɔtee bɛn na Okuapehene ne n'ahemfo kɔ bere a wɔrekɔdwira ahengwa no ho fi wɔ Odwira mu?",
        "optionA": "Amanprobi",
        "optionB": "Mampong sukuu",
        "optionC": "Aburi nsuo ano",
        "optionD": "Nsawam guaso",
        "correctOption": "A",
        "subConcept": "Amanprobi Sacred Grounds",
        "explanation": "Wɔkɔ Amanprobi a nananom ahemfo a wodi kan sie hɔ no kɔyɛ amanne no.",
        "remediationTip": "Purification rites take place at Amanprobi, the ancestral cemetery."
      },
      {
        "id": "q-twi-afa-9",
        "quizId": "quiz-jhs1-twi-afahye",
        "questionText": "Mfaso bɛn na Odwira afahyɛ de ba Akuapem man mpontu mu?",
        "optionA": "Ɛka manfo a wɔwɔ akyirikyiri bɔ mu ma wɔbom susuw mpontu nnwuma ho na sika ba kurom",
        "optionB": "Ɛma nnipa nyinaa tu kɔ mpoano",
        "optionC": "Ɛsiw sukuukɔ kwan",
        "optionD": "Ɛsesa ahemfo abodin",
        "correctOption": "A",
        "subConcept": "Socio-Economic Value of Festivals",
        "explanation": "Afahyɛ de baakoyɛ, sikasɛm mpontu, ne nkɔso nnwuma ba ɔman no mu.",
        "remediationTip": "Festivals unite citizens to fund developmental projects."
      },
      {
        "id": "q-twi-afa-10",
        "quizId": "quiz-jhs1-twi-afahye",
        "questionText": "Afahyɛ foforo bɛn na Akuapem Guan manfo te sɛ Larteh ne Kyerepon di no?",
        "optionA": "Ohum Afahyɛ",
        "optionB": "Kundum",
        "optionC": "Damba",
        "optionD": "Bakatue",
        "correctOption": "A",
        "subConcept": "Ohum Festival of Guans",
        "explanation": "Akuapem Guanfo (Larteh, Kyerepon) di Ohum afahyɛ (Ohumkan ne Ohumkyire).",
        "remediationTip": "Guan communities in Akuapem observe Ohum festival."
      }
    ]
  },
  "jhs1-twi-t13-abebusem": {
    "id": "quiz-jhs1-twi-abebusem",
    "topicId": "jhs1-twi-t13-abebusem",
    "title": "Akuapem Twi Abɛbusɛm ne Ne Nkyerɛase Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-abe-1",
        "quizId": "quiz-jhs1-twi-abebusem",
        "questionText": "Wie abɛbu yi: 'Ti koro nkɔ ___'",
        "optionA": "gua",
        "optionB": "agyina",
        "optionC": "kwaem",
        "optionD": "afahyɛ",
        "correctOption": "B",
        "subConcept": "Proverb Completion",
        "explanation": "'Ti koro nkɔ agyina' kyerɛ sɛ nipa baako adwene nso adwumaden ho; nkabom na eye.",
        "remediationTip": "Proverb: 'Ti koro nkɔ agyina' (One head does not go into council)."
      },
      {
        "id": "q-twi-abe-2",
        "quizId": "quiz-jhs1-twi-abebusem",
        "questionText": "Dɛn ne abɛbu 'Ti koro nkɔ agyina' asekyerɛ pɔtee?",
        "optionA": "Nipa baako pɛ na onim biribiara",
        "optionB": "Afotutu ne baakoyɛ ma adwene mu da hɔ fann sen nipa baako pɛ",
        "optionC": "Obiara ntena fie da",
        "optionD": "Nnipa mmienu nka asɛm da",
        "correctOption": "B",
        "subConcept": "Proverb Meaning",
        "explanation": "Ɛkyerɛ mfaso a ɛwɔ baakoyɛ ne afotu so.",
        "remediationTip": "Collective counsel is superior to isolated thinking."
      },
      {
        "id": "q-twi-abe-3",
        "quizId": "quiz-jhs1-twi-abebusem",
        "questionText": "Wie abɛbu yi: 'Abofra hu ne nsa hohoro a, ɔne ___ didi.'",
        "optionA": "mmofra",
        "optionB": "mpanyimfo",
        "optionC": "n'atamfo",
        "optionD": "ahemfo",
        "correctOption": "B",
        "subConcept": "Proverb Completion",
        "explanation": "'Abofra hu ne nsa hohoro a, ɔne mpanyimfo didi' kyerɛ sɛ suban pa ma wonya nidi kɛse.",
        "remediationTip": "Proverb: When a child washes his hands clean, he dines with elders."
      },
      {
        "id": "q-twi-abe-4",
        "quizId": "quiz-jhs1-twi-abebusem",
        "questionText": "Abɛbu bɛn na ɛkyerɛ sɛ adwuma den a obi yɛ no bɔ no ban firi ohia ho?",
        "optionA": "Wosuro didi a, wofa kɔm",
        "optionB": "Ti koro nkɔ agyina",
        "optionC": "Agya bi wu a, agya bi te ase",
        "optionD": "Akokɔ nane tia ne ba so a, ɛnkum no",
        "correctOption": "A",
        "subConcept": "Hard Work Proverb",
        "explanation": "'Wosuro didi a, wofa kɔm' kyerɛ sɛ adwumaden na ɛma anigye ne ahonyade.",
        "remediationTip": "'Wosuro didi a, wofa kɔm' warns that fear of exertion breeds poverty."
      },
      {
        "id": "q-twi-abe-5",
        "quizId": "quiz-jhs1-twi-abebusem",
        "questionText": "Dɛn ne abɛbu 'Akokɔ nane tia ne ba so a, ɛnkum no' asekyerɛ?",
        "optionA": "Ɔwofo asotwe a ɔde ma ne ba no fapem ne ɔdɔ ne ntetee pa na ɛnyɛ sɛ ɔpɛ sɛ ɔsɛe no",
        "optionB": "Akokɔ yɛ aboa bɔne",
        "optionC": "Mmofra nsuro awofo",
        "optionD": "Awofo nyɛ adwuma",
        "correctOption": "A",
        "subConcept": "Parental Discipline Meaning",
        "explanation": "Awofo kasakyea ne nteɛso yɛ ɔdɔ a wɔwɔ ma wɔn mma na ɛnyɛ tan.",
        "remediationTip": "Parental discipline aims to reform and guide, not to harm."
      },
      {
        "id": "q-twi-abe-6",
        "quizId": "quiz-jhs1-twi-abebusem",
        "questionText": "Sɛ worebɛbɔ abɛbu wɔ mpanyimfo anim a, asɛm bɛn na woka de bu wɔn anim kwan?",
        "optionA": "'Mpanin se...' anaa 'Maka bi akyi'",
        "optionB": "'Munnkasa bio!'",
        "optionC": "'Me na menim sen mo'",
        "optionD": "'Menni hwee bɛka'",
        "correctOption": "A",
        "subConcept": "Etiquette of Quoting Proverbs",
        "explanation": "Wɔka 'Mpanin se...' anaa 'Maka bi akyi' de bu mpanin no anim kwan.",
        "remediationTip": "Always preface proverbs before elders with 'Mpaninfo se...'."
      },
      {
        "id": "q-twi-abe-7",
        "quizId": "quiz-jhs1-twi-abebusem",
        "questionText": "Wie abɛbu yi: 'Baanu so a, ___'",
        "optionA": "ɛmma emu nnyɛ duru",
        "optionB": "ebubu",
        "optionC": "ɛyera ntɛm",
        "optionD": "ɛnsɛe da",
        "correctOption": "A",
        "subConcept": "Proverb Completion",
        "explanation": "'Baanu so a, ɛmma emu nnyɛ duru' kyerɛ sɛ nkabom ma adwuma yɛ mmerɛw.",
        "remediationTip": "Proverb: 'Baanu so a, ɛmma emu nnyɛ duru' (Two carrying a load eases the weight)."
      },
      {
        "id": "q-twi-abe-8",
        "quizId": "quiz-jhs1-twi-abebusem",
        "questionText": "Mpanin ka sɛ: 'Obanyansafo na wɔbɔ no bɛ, na ___'",
        "optionA": "wɔnka no asɛm",
        "optionB": "wɔmma no aduane",
        "optionC": "wɔmmu no",
        "optionD": "wɔntwerɛ krataa mma no",
        "correctOption": "A",
        "subConcept": "The Wise Child Proverb",
        "explanation": "'Obanyansafo na wɔbɔ no bɛ na wɔnnka no asɛm' kyerɛ sɛ oniferefo de abɛbu nsohyɛ pɛ te asɛm ase.",
        "remediationTip": "To the wise child, one speaks in proverbs, not lengthy explanations."
      },
      {
        "id": "q-twi-abe-9",
        "quizId": "quiz-jhs1-twi-abebusem",
        "questionText": "Abɛbu bɛn na ɛkyerɛ sɛ sɛ panyin bi wu mpo a, obi foforo bɛba abɛboa fie?",
        "optionA": "Agya bi wu a, agya bi te ase",
        "optionB": "Ti koro nkɔ agyina",
        "optionC": "Wosuro didi a wofa kɔm",
        "optionD": "Abofra hu ne nsa hohoro",
        "correctOption": "A",
        "subConcept": "Continuity Proverb",
        "explanation": "'Agya bi wu a, agya bi te ase' kyerɛ sɛ asetena kɔ so na afoforo hyɛ ananmu.",
        "remediationTip": "'Agya bi wu a, agya bi te ase' speaks of hope and continuity."
      },
      {
        "id": "q-twi-abe-10",
        "quizId": "quiz-jhs1-twi-abebusem",
        "questionText": "Mfaso kɛse bɛn na abɛbusɛm de ba Twi kasa atwerɛ mu wɔ BECE nsohwɛ mu?",
        "optionA": "Ɛma atwerɛ no nya animuonyam na ɛda kasadwini nyansa adi ma wonya mfonyin kɛse",
        "optionB": "Ɛsesa Twi kasa kɔ Ga mu",
        "optionC": "Ɛma atwerɛ no wie ntɛmntɛm a kyerɛw biara nni mu",
        "optionD": "Ɛpam asɔrefo fi sukuu mu",
        "correctOption": "A",
        "subConcept": "Value in Exam Essays",
        "explanation": "Abɛbu siesie atwerɛ no fɛfɛɛfɛ na ɛda nimdeɛ a emu dɔ adi ma BECE asɔfo no.",
        "remediationTip": "Incorporating proverbs enriches essays and boosts literature scores."
      }
    ]
  },
  "jhs1-twi-t14-anansesem": {
    "id": "quiz-jhs1-twi-anansesem",
    "topicId": "jhs1-twi-t14-anansesem",
    "title": "Anansesɛm ne Mmoguo Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-ana-1",
        "quizId": "quiz-jhs1-twi-anansesem",
        "questionText": "Sɛ anansesɛmfo no rebɛhyɛ anansesɛm ase a, dɛn na ɔbɔ pampim?",
        "optionA": "'Anansesɛm o!'",
        "optionB": "'Yese so o!'",
        "optionC": "'Mema mo akye!'",
        "optionD": "'Agya bi wu!'",
        "correctOption": "A",
        "subConcept": "Opening Call in Storytelling",
        "explanation": "Anansesɛmfo no bɔ pampim sɛ: 'Anansesɛm o!'.",
        "remediationTip": "The storyteller opens with 'Anansesɛm o!'."
      },
      {
        "id": "q-twi-ana-2",
        "quizId": "quiz-jhs1-twi-anansesem",
        "questionText": "Atiefo no bua anansesɛmfo no ahyɛase asɛm no dɛn?",
        "optionA": "'Yese so o!'",
        "optionB": "'Yaa-Agya!'",
        "optionC": "'Akwaaba!'",
        "optionD": "'Yɛte wo nka!'",
        "correctOption": "A",
        "subConcept": "Audience Response",
        "explanation": "Atiefo no bua ntɛm ara sɛ: 'Yese so o!'.",
        "remediationTip": "The audience responds together: 'Yese so o!'."
      },
      {
        "id": "q-twi-ana-3",
        "quizId": "quiz-jhs1-twi-anansesem",
        "questionText": "Kwaku Ananse yere a wɔtaa bɔ ne din wɔ anansesɛm mu ne hwan?",
        "optionA": "Okonore Yaa",
        "optionB": "Afia Pokuaa",
        "optionC": "Akosua Mansa",
        "optionD": "Adwoa Fofie",
        "correctOption": "A",
        "subConcept": "Ananse's Wife",
        "explanation": "Kwaku Ananse yere ne Okonore Yaa (anaa Aso).",
        "remediationTip": "Ananse's wife in Akan folklore is Okonore Yaa."
      },
      {
        "id": "q-twi-ana-4",
        "quizId": "quiz-jhs1-twi-anansesem",
        "questionText": "Kwaku Ananse ba barima a ɔkura nyansa ne anifere kɛse no din ne hwan?",
        "optionA": "Ntikuma",
        "optionB": "Kweku Tsin",
        "optionC": "Tawiah",
        "optionD": "Bodua",
        "correctOption": "A",
        "subConcept": "Ananse's Son Ntikuma",
        "explanation": "Ntikuma na ɔyɛ Ananse ba a ɔtaa fa nyansa hu n'agya anifere nnoɔma.",
        "remediationTip": "Ntikuma is Ananse's sharp, inquisitive son."
      },
      {
        "id": "q-twi-ana-5",
        "quizId": "quiz-jhs1-twi-anansesem",
        "questionText": "Dɛn ne 'Mmoguo' wɔ anansesɛm mu?",
        "optionA": "Dwom a atiefo anaa asɛmkafo to gu anansesɛm mu de gye ahome na ɛma agoru no yɛ dɛ",
        "optionB": "Aduane a wɔdi anwummerɛ",
        "optionC": "Akyerɛwamba nhoma",
        "optionD": "Asotwe a wɔde ma korɔmfo",
        "correctOption": "A",
        "subConcept": "Mmoguo (Folk Songs)",
        "explanation": "Mmoguo yɛ dwom a wɔto de hyɛ agoru no mu ahoɔden na ɛma atiefo nna nntɔ.",
        "remediationTip": "Mmoguo are traditional musical interludes sung during stories."
      },
      {
        "id": "q-twi-ana-6",
        "quizId": "quiz-jhs1-twi-anansesem",
        "questionText": "Suban bɔne bɛn na Kwaku Ananse taa da no adi a ɛde no kɔ amanehunu mu?",
        "optionA": "Apɛpemmɔ ne adugudeɛ (Greed and selfishness)",
        "optionB": "Ahobrɛase",
        "optionC": "Yamhye",
        "optionD": "Nokwaredi",
        "correctOption": "A",
        "subConcept": "Ananse's Greed Flaw",
        "explanation": "Ananse pɛ nnoɔma nyinaa ma ne ho nkutoo (apɛpemmɔ), na eyi de asotwe ba ne so.",
        "remediationTip": "Ananse's major moral flaw is greed and excessive trickery."
      },
      {
        "id": "q-twi-ana-7",
        "quizId": "quiz-jhs1-twi-anansesem",
        "questionText": "Sɛ anansesɛmfo no rewie n'asɛm no a, kasamu bɛn na ɔde kyerɛ awiei?",
        "optionA": "'M'anansesɛm a metoe yi, sɛ ɛyɛ dɛ o, sɛ ɛnyɛ dɛ o, ebi nkɔ baabi na ebi mmra me nkyɛn'",
        "optionB": "'Meda mo ase, monkɔ fie'",
        "optionC": "'Asɛm no asɛe koraa'",
        "optionD": "'Mompam Ananse firi kurom'",
        "correctOption": "A",
        "subConcept": "Traditional Story Closing Formula",
        "explanation": "Kasamu yi na wɔde wie anansesɛm de kyerɛ sɛ asɛm no yɛ nsiesiei ne afotu.",
        "remediationTip": "Traditional Akan folk tales close with the formula: 'M'anansesɛm a metoe yi...'."
      },
      {
        "id": "q-twi-ana-8",
        "quizId": "quiz-jhs1-twi-anansesem",
        "questionText": "Bere bɛn wɔ da no mu na Akanfo tete no taa to anansesɛm?",
        "optionA": "Anwummerɛ bere a osram apue",
        "optionB": "Awia keteketee bere a owia rehyehye",
        "optionC": "Anɔpatutuutu bere a wɔrekɔ afum",
        "optionD": "Sukuu bere mu",
        "correctOption": "A",
        "subConcept": "Storytelling Time Tradition",
        "explanation": "Wɔto anansesɛm anwummerɛ bere a adwumayɛ asa na osram repue.",
        "remediationTip": "Tales were told in the moonlight evenings after farm work."
      },
      {
        "id": "q-twi-ana-9",
        "quizId": "quiz-jhs1-twi-anansesem",
        "questionText": "Mfaso titiriw bɛn na mmoguo de ma atiefo wɔ agoru no mu?",
        "optionA": "Ɛma wɔn ani da hɔ na wɔn nsa ka agoru no fã bi to dwom",
        "optionB": "Ɛma wɔda ntɛm",
        "optionC": "Ɛma anansesɛmfo no bɔ ne ho ka",
        "optionD": "Ɛpam mmofra fi fie",
        "correctOption": "A",
        "subConcept": "Function of Mmoguo",
        "explanation": "Mmoguo gye atiefo ahome, ma anigye, na ɛka wɔn bɔ mu to dwom.",
        "remediationTip": "Mmoguo keeps the audience awake, engaged, and participating actively."
      },
      {
        "id": "q-twi-ana-10",
        "quizId": "quiz-jhs1-twi-anansesem",
        "questionText": "Botae titiriw a ɛwɔ anansesɛm akyi ma mmofra ntetee ne dɛn?",
        "optionA": "De kyerɛkyerɛ mmofra suban pa, nyansa, ne nsunsuanso a ɛwɔ nneyɛe bɔne mu",
        "optionB": "De ma mmofra sua borɔfo",
        "optionC": "De ma mmofra hu sɛnea wɔbɔ tuo",
        "optionD": "De pam anansewaa fi dan mu",
        "correctOption": "A",
        "subConcept": "Moral Purpose of Folklore",
        "explanation": "Anansesɛm botae ne sɛ ɛbɛkyerɛ mmofra abrabɔ pa na wɔatwe wɔn ho afi aniteɛ ne bɔne ho.",
        "remediationTip": "Ananse folktales serve as a pedagogical tool for moral instruction."
      }
    ]
  },
  "jhs1-twi-t15-atwere": {
    "id": "quiz-jhs1-twi-atwere",
    "topicId": "jhs1-twi-t15-atwere",
    "title": "Twi Akenkan, Ntease ne Atwerɛ Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-twi-atw-1",
        "quizId": "quiz-jhs1-twi-atwere",
        "questionText": "Afã horo ahe na ɛwɔ 'Krataa a Yɛtwerɛ Kɔma Ɔyɔnko' (Informal Letter) mu?",
        "optionA": "Afã anum (5)",
        "optionB": "Afã mmienu (2)",
        "optionC": "Afã awotwe (8)",
        "optionD": "Afã du (10)",
        "correctOption": "A",
        "subConcept": "Parts of an Informal Letter",
        "explanation": "Afã anum no ne: Address ne da, Nkyea, Ahyɛase, Emu Nsɛm, ne Awiei/Nkonkabɔ.",
        "remediationTip": "Friendly letters have 5 parts: address/date, salutation, intro, body, sign-off."
      },
      {
        "id": "q-twi-atw-2",
        "quizId": "quiz-jhs1-twi-atwere",
        "questionText": "Baabi bɛn na otwerɛfo no twerɛ n'address ne da wɔ krataa a ɔretwerɛ kɔma n'adamfo mu?",
        "optionA": "Nifa so atifi pɛpɛɛpɛ (Top right corner)",
        "optionB": "Benkum so fam",
        "optionC": "Mfinimfini",
        "optionD": "Krataa no akyi koraa",
        "correctOption": "A",
        "subConcept": "Address Placement",
        "explanation": "Address ne da gyina krataa no nifa so atifi (top right corner).",
        "remediationTip": "The sender's address and date are written at the top right-hand corner."
      },
      {
        "id": "q-twi-atw-3",
        "quizId": "quiz-jhs1-twi-atwere",
        "questionText": "Nkyea a ɛfata sɛ wode hyɛ krataa a woretwerɛ kɔma wo nua Kwame ase ne:",
        "optionA": "'Me nua dɔfo Kwame,'",
        "optionB": "'Owura Panyin,'",
        "optionC": "'Mema wo adwuma,'",
        "optionD": "'Kɔ fie ntɛm,'",
        "correctOption": "A",
        "subConcept": "Friendly Letter Salutation",
        "explanation": "Wɔ krataa a ɛkɔma adamfo mu no, fa 'Me nua dɔfo Kwame,' kyea no anigye mu.",
        "remediationTip": "Use affectionate salutations like 'Me nua dɔfo Kwame,' for peers."
      },
      {
        "id": "q-twi-atw-4",
        "quizId": "quiz-jhs1-twi-atwere",
        "questionText": "Sɛ wowie krataa a woretwerɛ kɔma wo dɔfo bi a, sɛnea wowie no wɔ nifa so fam ne:",
        "optionA": "'Wo nua nokwafo, / Kwadwo'",
        "optionB": "'Mede obu kɛse ma wo, / Owura Kofi'",
        "optionC": "'Krataa no asa, / Mensah'",
        "optionD": "'Me kɔ da, / Kwame'",
        "correctOption": "A",
        "subConcept": "Informal Subscription Sign-off",
        "explanation": "Wɔ adamfo krataa mu no, yɛtwerɛ 'Wo nua nokwafo' anaa 'W'adamfo pa', afei edin koro pɛ.",
        "remediationTip": "Sign off with 'Wo nua nokwafo,' followed by your first name only."
      },
      {
        "id": "q-twi-atw-5",
        "quizId": "quiz-jhs1-twi-atwere",
        "questionText": "Wɔ Akenkan ne Ntease (Comprehension) mu no, kwan pa bɛn na wofa so bua nsɛmmisa?",
        "optionA": "Fa kasamu a edi mu a egyina nsɛmfua pɔtee a ɛwɔ akenkan no mu bua tẽẽ",
        "optionB": "Fa w'adwene foforo a enni akenkan no mu bua",
        "optionC": "Twerɛ asɛm koro pɛ mprɛnsa",
        "optionD": "Fa Borɔfo kasa bua nsɛmbisa no",
        "correctOption": "A",
        "subConcept": "Comprehension Answering Technique",
        "explanation": "Bua nsɛmbisa no tẽẽ fa kasamu a edi mu firi akenkan asɛm no ankasa mu.",
        "remediationTip": "Answer strictly based on facts provided in the passage using complete sentences."
      },
      {
        "id": "q-twi-atw-6",
        "quizId": "quiz-jhs1-twi-atwere",
        "questionText": "Address ahe na ɛsɛ sɛ ɛba krataa a yɛtwerɛ kɔma panin anaa adwumayɛbea (Formal Letter) so?",
        "optionA": "Address mmienu (Sender & Recipient addresses)",
        "optionB": "Address koro pɛ",
        "optionC": "Address ebiasa",
        "optionD": "Address biara nni so",
        "correctOption": "A",
        "subConcept": "Formal Letter Address Count",
        "explanation": "Formal letter kura address mmienu: Otwerɛfo no de (top right) ne Ogyeefo no de (left side).",
        "remediationTip": "Formal letters require two addresses: the writer's and recipient's."
      },
      {
        "id": "q-twi-atw-7",
        "quizId": "quiz-jhs1-twi-atwere",
        "questionText": "Mmara bɛn na ɛwɔ hɔ fa nkyekyem (paragraphs) a yɛkyɛ mu wɔ atwerɛ mu?",
        "optionA": "Nkyekyem biara kura adwene kɛse baako pɛ a wɔakyerɛkyerɛ mu fann",
        "optionB": "Twerɛ asɛm no nyinaa wɔ nkyekyem koro pɛ mu",
        "optionC": "Nkyekyem biara nni akyi-pɔ",
        "optionD": "Mfa kasamu foforo biara nhyɛ ase",
        "correctOption": "A",
        "subConcept": "Paragraph Unity in Essays",
        "explanation": "Nkyekyem biara kura adwene titiriw baako (one main idea per paragraph).",
        "remediationTip": "Each paragraph should focus on one central theme or argument."
      },
      {
        "id": "q-twi-atw-8",
        "quizId": "quiz-jhs1-twi-atwere",
        "questionText": "Mfomso kɛse bɛn na sukuuni biara nni ho kwan sɛ ɔyɛ wɔ Twi atwerɛ nsohwɛ mu?",
        "optionA": "Borɔfo nsɛmfua a ɔde bɛfrafra Twi no mu",
        "optionB": "Abɛbu a ɔde bɛhyɛ n'atwerɛ mu",
        "optionC": "Akyerɛwamba pa a ɔde bɛtwerɛ",
        "optionD": "Nkyekyem a ɔbɛpaepae mu",
        "correctOption": "A",
        "subConcept": "Avoid English Code-Switching",
        "explanation": "Borɔfo asɛmfua a wobɛtwerɛ wɔ Twi mu no sɛe mfonyin kɛse (loss of marks).",
        "remediationTip": "Never insert English words or slang into your Twi essays."
      },
      {
        "id": "q-twi-atw-9",
        "quizId": "quiz-jhs1-twi-atwere",
        "questionText": "Nkabomde (conjunction) pa bɛn na yɛde ka adwene abien bom wɔ kasamu mu?",
        "optionA": "nanso",
        "optionB": "pono",
        "optionC": "tuntum",
        "optionD": "kɛse",
        "correctOption": "A",
        "subConcept": "Conjunctions in Writing",
        "explanation": "'nanso' (but) yɛ nkabomde a ɛka nsɛm abien a ɛsono wɔn bɔ mu.",
        "remediationTip": "'nanso' (but) is a linking conjunction."
      },
      {
        "id": "q-twi-atw-10",
        "quizId": "quiz-jhs1-twi-atwere",
        "questionText": "Krataa a yɛtwerɛ kɔma panin (Formal letter) mu no, asɛmti (Heading/Title) no gyina baabi bɛn?",
        "optionA": "Nkyea no akyi pɛpɛɛpɛ ansa na ahyɛase abaa",
        "optionB": "Address no atifi",
        "optionC": "Awiei pɔtee no akyi",
        "optionD": "Krataa no akyi",
        "correctOption": "A",
        "subConcept": "Heading in Formal Letters",
        "explanation": "Asɛmti no da nkyea no akyi pɛpɛɛpɛ, na yɛtwerɛ no akyerɛw akɛse mu anaa yɛtwe n'ase kwan.",
        "remediationTip": "The capitalized title sits directly below the formal salutation."
      }
    ]
  }
};
