// Ghanaian JHS 1 French Language Practice Quizzes
// Based on NaCCA / GES Common Core Programme (CCP) Curriculum
// 15 Topics × 10 Questions = 150 BECE-Standard Questions

import { TopicQuiz } from './types';

export const JHS1_FRENCH_QUIZZES: Record<string, TopicQuiz> = {
  "jhs1-fre-t1-salutations": {
    "id": "quiz-jhs1-fre-salutations",
    "topicId": "jhs1-fre-t1-salutations",
    "title": "Salutations, Présentations et Politesse Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-sal-1",
        "quizId": "quiz-jhs1-fre-salutations",
        "questionText": "Quelle salutation utilise-t-on le MATIN pour saluer son professeur ?",
        "optionA": "Bonne nuit, Monsieur !",
        "optionB": "Bonjour, Monsieur !",
        "optionC": "Bonsoir, Monsieur !",
        "optionD": "À plus tard, Monsieur !",
        "correctOption": "B",
        "subConcept": "Morning Greeting",
        "explanation": "Le matin, on utilise la formule de politesse 'Bonjour, Monsieur !'. 'Bonne nuit' n'est utilisé qu'avant d'aller dormir.",
        "remediationTip": "Morning/afternoon greeting is 'Bonjour'. Evening greeting is 'Bonsoir'."
      },
      {
        "id": "q-fre-sal-2",
        "quizId": "quiz-jhs1-fre-salutations",
        "questionText": "Comment demande-t-on poliment le nom d'un camarade de classe (informel) ?",
        "optionA": "Quel âge as-tu ?",
        "optionB": "Comment t'appelles-tu ?",
        "optionC": "Où habites-tu ?",
        "optionD": "D'où viens-tu ?",
        "correctOption": "B",
        "subConcept": "Asking Name",
        "explanation": "'Comment t'appelles-tu ?' signifie 'What is your name?' en s'adressant à un camarade de son âge.",
        "remediationTip": "Use 'Comment t'appelles-tu ?' to ask a peer's name."
      },
      {
        "id": "q-fre-sal-3",
        "quizId": "quiz-jhs1-fre-salutations",
        "questionText": "Complétez la phrase: 'Moi, je ___ Kwame Mensah.'",
        "optionA": "t'appelles",
        "optionB": "m'appelle",
        "optionC": "s'appelle",
        "optionD": "vous appelez",
        "correctOption": "B",
        "subConcept": "Verbe S'appeler",
        "explanation": "Avec le pronom sujet 'Je', la forme réfléchie du verbe s'appeler est 'm'appelle' (Je m'appelle).",
        "remediationTip": "Je m'appelle, Tu t'appelles, Il/Elle s'appelle."
      },
      {
        "id": "q-fre-sal-4",
        "quizId": "quiz-jhs1-fre-salutations",
        "questionText": "Quelle formule utilise-t-on pour saluer un ami le SOIR à 19h00 ?",
        "optionA": "Bonjour !",
        "optionB": "Bonsoir !",
        "optionC": "Bonne nuit !",
        "optionD": "Bonne après-midi !",
        "correctOption": "B",
        "subConcept": "Evening Greeting",
        "explanation": "Dès que le soir tombe (vers 18h-19h), on salue les gens en disant 'Bonsoir !'.",
        "remediationTip": "'Bonsoir' is the correct evening greeting."
      },
      {
        "id": "q-fre-sal-5",
        "quizId": "quiz-jhs1-fre-salutations",
        "questionText": "Que signifie l'expression 'Comment allez-vous ?' en anglais ?",
        "optionA": "Where are you going?",
        "optionB": "How are you doing? (formal / plural)",
        "optionC": "What is your name?",
        "optionD": "How old are you?",
        "correctOption": "B",
        "subConcept": "Asking Welfare Formally",
        "explanation": "'Comment allez-vous ?' est la formule formelle pour demander 'How are you?' à un adulte ou à plusieurs personnes.",
        "remediationTip": "'Comment allez-vous ?' = How are you doing? (polite/formal)."
      },
      {
        "id": "q-fre-sal-6",
        "quizId": "quiz-jhs1-fre-salutations",
        "questionText": "Que répond une fille pour dire 'Pleased to meet you' en français ?",
        "optionA": "Enchanté",
        "optionB": "Enchantée",
        "optionC": "Au revoir",
        "optionD": "Merci",
        "correctOption": "B",
        "subConcept": "Enchanté(e) Agreement",
        "explanation": "Une fille ajoute un 'e' d'accord féminin pour écrire 'Enchantée !' (Pleased to meet you).",
        "remediationTip": "Male says 'Enchanté'; female says 'Enchantée' (with extra 'e')."
      },
      {
        "id": "q-fre-sal-7",
        "quizId": "quiz-jhs1-fre-salutations",
        "questionText": "Quelle expression utilise-t-on pour prendre congé lorsqu'on reverra la personne LE LENDEMAIN ?",
        "optionA": "À bientôt !",
        "optionB": "À demain !",
        "optionC": "Adieu !",
        "optionD": "Bonne nuit !",
        "correctOption": "B",
        "subConcept": "Taking Leave (À demain)",
        "explanation": "'À demain !' signifie 'See you tomorrow!'. 'Demain' signifie 'tomorrow'.",
        "remediationTip": "'À demain' = See you tomorrow; 'À bientôt' = See you soon."
      },
      {
        "id": "q-fre-sal-8",
        "quizId": "quiz-jhs1-fre-salutations",
        "questionText": "Quelle salutation informelle est couramment utilisée entre jeunes pour dire à la fois 'Hello' et 'Goodbye' ?",
        "optionA": "Monsieur",
        "optionB": "Salut",
        "optionC": "Pardon",
        "optionD": "Plaît-il",
        "correctOption": "B",
        "subConcept": "Informal Salut",
        "explanation": "'Salut !' est un terme informel utilisé entre amis qui signifie à la fois 'Hi' et 'Bye'.",
        "remediationTip": "'Salut' is informal for both Hi and Bye among peers."
      },
      {
        "id": "q-fre-sal-9",
        "quizId": "quiz-jhs1-fre-salutations",
        "questionText": "Comment présente-t-on son camarade de classe nommé Kofi à sa mère ?",
        "optionA": "Voici mon ami Kofi.",
        "optionB": "Je m'appelle Kofi.",
        "optionC": "Kofi a douze ans.",
        "optionD": "Au revoir Kofi.",
        "correctOption": "A",
        "subConcept": "Introducing Someone (Voici)",
        "explanation": "'Voici mon ami Kofi' signifie 'This is my friend Kofi', utilisé pour présenter quelqu'un.",
        "remediationTip": "Use 'Voici...' to introduce someone nearby."
      },
      {
        "id": "q-fre-sal-10",
        "quizId": "quiz-jhs1-fre-salutations",
        "questionText": "Quand dit-on 'Bonne nuit !' en français ?",
        "optionA": "À midi avant de manger",
        "optionB": "Le soir au moment d'aller dormir",
        "optionC": "Quand on arrive à une fête le soir",
        "optionD": "Le matin au réveil",
        "correctOption": "B",
        "subConcept": "Bonne nuit Usage",
        "explanation": "'Bonne nuit !' se dit uniquement au moment de se coucher pour dormir (Good night).",
        "remediationTip": "Say 'Bonne nuit' right before going to sleep, never upon arriving in the evening."
      }
    ]
  },
  "jhs1-fre-t2-alphabet": {
    "id": "quiz-jhs1-fre-alphabet",
    "topicId": "jhs1-fre-t2-alphabet",
    "title": "L'Alphabet Français et les Accents Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-alp-1",
        "quizId": "quiz-jhs1-fre-alphabet",
        "questionText": "Combien de lettres et de voyelles comporte l'alphabet français ?",
        "optionA": "24 lettres dont 4 voyelles",
        "optionB": "26 lettres dont 6 voyelles (A, E, I, O, U, Y)",
        "optionC": "28 lettres dont 5 voyelles",
        "optionD": "30 lettres dont 7 voyelles",
        "correctOption": "B",
        "subConcept": "Alphabet Count & Vowels",
        "explanation": "L'alphabet français compte 26 lettres: 6 voyelles (A, E, I, O, U, Y) et 20 consonnes.",
        "remediationTip": "French alphabet: 26 letters with 6 vowels (A, E, I, O, U, Y)."
      },
      {
        "id": "q-fre-alp-2",
        "quizId": "quiz-jhs1-fre-alphabet",
        "questionText": "Quel accent français se place UNIQUEMENT sur la lettre 'e' comme dans le mot 'école' ?",
        "optionA": "L'accent grave (è)",
        "optionB": "L'accent aigu (é)",
        "optionC": "L'accent circonflexe (ê)",
        "optionD": "La cédille (ç)",
        "correctOption": "B",
        "subConcept": "Accent Aigu",
        "explanation": "L'accent aigu (é) ne se place que sur la lettre 'e' pour produire le son fermé /e/ (ex: école, élève).",
        "remediationTip": "Accent aigu (é) only goes on the letter 'e'."
      },
      {
        "id": "q-fre-alp-3",
        "quizId": "quiz-jhs1-fre-alphabet",
        "questionText": "Quelle est la fonction de la CÉDILLE (ç) dans le mot 'français' ?",
        "optionA": "Elle rend la lettre muette",
        "optionB": "Elle donne à la lettre 'c' le son doux /s/ devant a, o, u",
        "optionC": "Elle allonge la prononciation du mot",
        "optionD": "Elle indique une question",
        "correctOption": "B",
        "subConcept": "La Cédille",
        "explanation": "La cédille placée sous le 'c' devant 'a', 'o', 'u' adoucit le son pour qu'il se prononce /s/ et non /k/.",
        "remediationTip": "A cedilla (ç) changes a hard /k/ sound into a soft /s/ sound."
      },
      {
        "id": "q-fre-alp-4",
        "quizId": "quiz-jhs1-fre-alphabet",
        "questionText": "Quelle est la différence de sens entre 'ou' et 'où' ?",
        "optionA": "'ou' signifie 'where' et 'où' signifie 'or'",
        "optionB": "'ou' signifie 'or' et 'où' (avec accent grave) signifie 'where'",
        "optionC": "Les deux mots ont exactement le même sens",
        "optionD": "'où' est un nom d'animal",
        "correctOption": "B",
        "subConcept": "Homophones ou vs où",
        "explanation": "'ou' (sans accent) est une conjonction qui signifie 'or' ('thé ou café ?'). 'où' (avec accent grave) indique le lieu: 'where'.",
        "remediationTip": "'ou' = or; 'où' (with accent grave) = where."
      },
      {
        "id": "q-fre-alp-5",
        "quizId": "quiz-jhs1-fre-alphabet",
        "questionText": "Quel accent porte le mot 'père' et 'mère' ?",
        "optionA": "L'accent aigu (é)",
        "optionB": "L'accent grave (è)",
        "optionC": "Le tréma (ë)",
        "optionD": "L'apostrophe",
        "correctOption": "B",
        "subConcept": "Accent Grave",
        "explanation": "'Père' et 'mère' portent un accent grave (è) pour produire le son ouvert /ɛ/.",
        "remediationTip": "'Père', 'mère', and 'frère' all take an accent grave (è)."
      },
      {
        "id": "q-fre-alp-6",
        "quizId": "quiz-jhs1-fre-alphabet",
        "questionText": "Quel signe orthographique en forme de petit chapeau (^) trouve-t-on sur 'hôtel' et 'fête' ?",
        "optionA": "L'accent aigu",
        "optionB": "L'accent circonflexe",
        "optionC": "La cédille",
        "optionD": "Le trait d'union",
        "correctOption": "B",
        "subConcept": "Accent Circonflexe",
        "explanation": "L'accent circonflexe (^) ressemble à un petit chapeau sur les voyelles (hôtel, fête, forêt).",
        "remediationTip": "The 'little hat' accent is the accent circonflexe (â, ê, î, ô, û)."
      },
      {
        "id": "q-fre-alp-7",
        "quizId": "quiz-jhs1-fre-alphabet",
        "questionText": "Que signifie le TRÉMA (deux points: ë, ï) dans un mot comme 'Noël' ?",
        "optionA": "Il indique qu'il faut prononcer les deux voyelles séparément",
        "optionB": "Il indique que la lettre est muette",
        "optionC": "Il transforme le mot au pluriel",
        "optionD": "Il rend le son nasal",
        "correctOption": "A",
        "subConcept": "Le Tréma",
        "explanation": "Le tréma sépare la prononciation de deux voyelles voisines (No-ël au lieu de Nel).",
        "remediationTip": "A tréma (ë, ï) separates the pronunciation of two adjacent vowels."
      },
      {
        "id": "q-fre-alp-8",
        "quizId": "quiz-jhs1-fre-alphabet",
        "questionText": "Comment écrit-on correctement 'le élève' en appliquant l'élision française ?",
        "optionA": "le élève",
        "optionB": "l'élève",
        "optionC": "la élève",
        "optionD": "les élève",
        "correctOption": "B",
        "subConcept": "Élision",
        "explanation": "Devant un mot commençant par une voyelle, 'le' ou 'la' perd sa voyelle et prend une apostrophe: l'élève.",
        "remediationTip": "Drop the 'e' or 'a' before a vowel and use an apostrophe: l'élève."
      },
      {
        "id": "q-fre-alp-9",
        "quizId": "quiz-jhs1-fre-alphabet",
        "questionText": "En français, quelle est la prononciation de la lettre 'G' par rapport à la lettre 'J' ?",
        "optionA": "'G' se prononce /ʒe/ et 'J' se prononce /ʒi/",
        "optionB": "'G' se prononce /dʒi/ et 'J' se prononce /dʒe/",
        "optionC": "Les deux lettres se prononcent exactement pareil",
        "optionD": "'G' est toujours muet",
        "correctOption": "A",
        "subConcept": "Phonétique G et J",
        "explanation": "Attention au piège classique pour les anglophones: en français, la lettre G se prononce /ʒe/ et la lettre J se prononce /ʒi/.",
        "remediationTip": "Remember: French 'G' is pronounced /ʒe/; French 'J' is pronounced /ʒi/."
      },
      {
        "id": "q-fre-alp-10",
        "quizId": "quiz-jhs1-fre-alphabet",
        "questionText": "Quel mot ci-dessous exige l'ajout d'une CÉDILLE pour être correctement orthographié ?",
        "optionA": "garcon (garçon)",
        "optionB": "cahier",
        "optionC": "classe",
        "optionD": "craie",
        "correctOption": "A",
        "subConcept": "Cédille Application",
        "explanation": "Sans cédille, 'garcon' se lirait 'garkon'. Il faut écrire 'garçon' avec une cédille pour avoir le son /s/.",
        "remediationTip": "'garçon' requires a cedilla (ç) before 'o' to sound like /s/."
      }
    ]
  },
  "jhs1-fre-t3-nombres": {
    "id": "quiz-jhs1-fre-nombres",
    "topicId": "jhs1-fre-t3-nombres",
    "title": "Les Nombres de 0 à 100 et l'Âge Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-num-1",
        "quizId": "quiz-jhs1-fre-nombres",
        "questionText": "Quel verbe utilise-t-on en français pour exprimer son ÂGE ?",
        "optionA": "Le verbe ÊTRE",
        "optionB": "Le verbe AVOIR",
        "optionC": "Le verbe FAIRE",
        "optionD": "Le verbe ALLER",
        "correctOption": "B",
        "subConcept": "Verbe Avoir pour l'Âge",
        "explanation": "En français, on utilise le verbe AVOIR pour exprimer l'âge: 'J'ai douze ans' (et non 'Je suis douze ans').",
        "remediationTip": "Always use AVOIR for age: 'J'ai ... ans'."
      },
      {
        "id": "q-fre-num-2",
        "quizId": "quiz-jhs1-fre-nombres",
        "questionText": "Comment traduit-on correctement 'I am 13 years old' en français ?",
        "optionA": "Je suis treize ans.",
        "optionB": "J'ai treize ans.",
        "optionC": "J'ai seize ans.",
        "optionD": "Je m'appelle treize.",
        "correctOption": "B",
        "subConcept": "Stating Age (J'ai 13 ans)",
        "explanation": "'Treize' est 13. Avec le verbe avoir, on dit 'J'ai treize ans.'",
        "remediationTip": "13 = treize; 'J'ai treize ans.'"
      },
      {
        "id": "q-fre-num-3",
        "quizId": "quiz-jhs1-fre-nombres",
        "questionText": "Comment écrit-on le nombre 70 en français ?",
        "optionA": "Septante",
        "optionB": "Soixante-dix",
        "optionC": "Sept-dix",
        "optionD": "Soixante-vingt",
        "correctOption": "B",
        "subConcept": "Number 70",
        "explanation": "En français standard, 70 se forme par l'addition de 60 + 10: 'soixante-dix'.",
        "remediationTip": "70 = soixante-dix (60 + 10)."
      },
      {
        "id": "q-fre-num-4",
        "quizId": "quiz-jhs1-fre-nombres",
        "questionText": "Comment écrit-on le nombre 80 en toutes lettres ?",
        "optionA": "Huit-dix",
        "optionB": "Quatre-vingts",
        "optionC": "Quatre-vingt-dix",
        "optionD": "Soixante-vingt",
        "correctOption": "B",
        "subConcept": "Number 80",
        "explanation": "80 se forme par 4 × 20: 'quatre-vingts'. Notez qu'il prend un 's' lorsqu'il n'est pas suivi d'un autre chiffre.",
        "remediationTip": "80 = quatre-vingts (with an 's')."
      },
      {
        "id": "q-fre-num-5",
        "quizId": "quiz-jhs1-fre-nombres",
        "questionText": "Quel nombre correspond à 'quatre-vingt-quinze' ?",
        "optionA": "85",
        "optionB": "95",
        "optionC": "75",
        "optionD": "90",
        "correctOption": "B",
        "subConcept": "Number 95",
        "explanation": "'Quatre-vingts' (80) + 'quinze' (15) = 95 ('quatre-vingt-quinze').",
        "remediationTip": "80 + 15 = 95 (quatre-vingt-quinze)."
      },
      {
        "id": "q-fre-num-6",
        "quizId": "quiz-jhs1-fre-nombres",
        "questionText": "Quel est le résultat en français de l'opération: 'Dix plus cinq égale ___' ?",
        "optionA": "douze",
        "optionB": "quinze",
        "optionC": "quatorze",
        "optionD": "seize",
        "correctOption": "B",
        "subConcept": "Simple Addition",
        "explanation": "10 (dix) + 5 (cinq) = 15 (quinze).",
        "remediationTip": "10 + 5 = 15 (quinze)."
      },
      {
        "id": "q-fre-num-7",
        "quizId": "quiz-jhs1-fre-nombres",
        "questionText": "Pourquoi le nombre 81 s'écrit-il 'quatre-vingt-un' et NON 'quatre-vingts-un' ?",
        "optionA": "Parce que le 's' tombe dès que 'quatre-vingts' est suivi d'un autre chiffre",
        "optionB": "Parce que c'est un nombre impair",
        "optionC": "Parce que c'est une faute d'impression",
        "optionD": "Parce que 'un' commence par une voyelle",
        "correctOption": "A",
        "subConcept": "Spelling Rule for 81",
        "explanation": "La règle orthographique veut que 'vingt' perde son 's' pluriel dès qu'il est suivi d'un autre numéral: quatre-vingt-un, quatre-vingt-deux.",
        "remediationTip": "80 has an 's' (quatre-vingts), but 81 loses the 's' (quatre-vingt-un)."
      },
      {
        "id": "q-fre-num-8",
        "quizId": "quiz-jhs1-fre-nombres",
        "questionText": "Comment dit-on 'seize' en chiffres arabes ?",
        "optionA": "6",
        "optionB": "16",
        "optionC": "60",
        "optionD": "26",
        "correctOption": "B",
        "subConcept": "Number 16",
        "explanation": "'Seize' correspond au chiffre 16 en français.",
        "remediationTip": "16 = seize; 6 = six; 60 = soixante."
      },
      {
        "id": "q-fre-num-9",
        "quizId": "quiz-jhs1-fre-nombres",
        "questionText": "Quelle question pose-t-on pour demander l'âge d'un ami ?",
        "optionA": "Quelle heure est-il ?",
        "optionB": "Quel âge as-tu ?",
        "optionC": "Combien ça coûte ?",
        "optionD": "Où vas-tu ?",
        "correctOption": "B",
        "subConcept": "Asking Age",
        "explanation": "'Quel âge as-tu ?' est la question exacte pour demander l'âge à un pair.",
        "remediationTip": "Ask age using 'Quel âge as-tu ?'."
      },
      {
        "id": "q-fre-num-10",
        "quizId": "quiz-jhs1-fre-nombres",
        "questionText": "Résolvez en français: 'Cinquante moins vingt égale ___'.",
        "optionA": "dix",
        "optionB": "trente",
        "optionC": "quarante",
        "optionD": "soixante",
        "correctOption": "B",
        "subConcept": "Subtraction in French",
        "explanation": "50 (cinquante) - 20 (vingt) = 30 (trente).",
        "remediationTip": "50 - 20 = 30 (trente)."
      }
    ]
  },
  "jhs1-fre-t4-objetsclasse": {
    "id": "quiz-jhs1-fre-objetsclasse",
    "topicId": "jhs1-fre-t4-objetsclasse",
    "title": "Les Objets de la Classe et Articles Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-obj-1",
        "quizId": "quiz-jhs1-fre-objetsclasse",
        "questionText": "Quel article indéfini convient pour le mot masculin 'cahier' ?",
        "optionA": "une",
        "optionB": "un",
        "optionC": "des",
        "optionD": "la",
        "correctOption": "B",
        "subConcept": "Article Indéfini Masculin",
        "explanation": "'Cahier' est un nom masculin singulier: 'un cahier' (an exercise book).",
        "remediationTip": "Masculine nouns take 'un'; feminine nouns take 'une'."
      },
      {
        "id": "q-fre-obj-2",
        "quizId": "quiz-jhs1-fre-objetsclasse",
        "questionText": "Quel article indéfini convient pour le mot féminin 'règle' (ruler) ?",
        "optionA": "un",
        "optionB": "une",
        "optionC": "le",
        "optionD": "des",
        "correctOption": "B",
        "subConcept": "Article Indéfini Féminin",
        "explanation": "'Règle' est féminin singulier: 'une règle'.",
        "remediationTip": "Ruler is feminine: 'une règle'."
      },
      {
        "id": "q-fre-obj-3",
        "quizId": "quiz-jhs1-fre-objetsclasse",
        "questionText": "Comment traduit-on 'The board' (blackboard/whiteboard) en français ?",
        "optionA": "La table",
        "optionB": "Le tableau",
        "optionC": "La trousse",
        "optionD": "Le stylo",
        "correctOption": "B",
        "subConcept": "Classroom Items (Tableau)",
        "explanation": "The board is 'le tableau' en français.",
        "remediationTip": "The board = le tableau."
      },
      {
        "id": "q-fre-obj-4",
        "quizId": "quiz-jhs1-fre-objetsclasse",
        "questionText": "Quel est le pluriel de l'expression 'C'est un livre' ?",
        "optionA": "C'est des livres",
        "optionB": "Ce sont des livres",
        "optionC": "Ce sont les livres",
        "optionD": "Ils ont des livres",
        "correctOption": "B",
        "subConcept": "Plural of C'est un",
        "explanation": "Le pluriel de 'C'est un' est 'Ce sont des' suivi du nom au pluriel: 'Ce sont des livres.'",
        "remediationTip": "Plural of 'C'est un...' is 'Ce sont des...'."
      },
      {
        "id": "q-fre-obj-5",
        "quizId": "quiz-jhs1-fre-objetsclasse",
        "questionText": "Quel article défini utilise-t-on devant le mot féminin 'gomme' ?",
        "optionA": "Le",
        "optionB": "La",
        "optionC": "L'",
        "optionD": "Les",
        "correctOption": "B",
        "subConcept": "Article Défini La",
        "explanation": "'Gomme' est féminin et commence par une consonne: 'la gomme' (the eraser).",
        "remediationTip": "Eraser is feminine: 'la gomme'."
      },
      {
        "id": "q-fre-obj-6",
        "quizId": "quiz-jhs1-fre-objetsclasse",
        "questionText": "Que signifie le mot 'une trousse' dans la classe ?",
        "optionA": "A school uniform",
        "optionB": "A pencil case",
        "optionC": "A chalk piece",
        "optionD": "A school bell",
        "correctOption": "B",
        "subConcept": "Vocabulary Trousse",
        "explanation": "'Une trousse' est le petit étui dans lequel on range ses stylos et crayons (pencil case).",
        "remediationTip": "'Une trousse' = a pencil case."
      },
      {
        "id": "q-fre-obj-7",
        "quizId": "quiz-jhs1-fre-objetsclasse",
        "questionText": "Complétez: 'Le maître écrit sur ___ tableau avec de ___ craie.'",
        "optionA": "la, la",
        "optionB": "le, la",
        "optionC": "un, le",
        "optionD": "les, les",
        "correctOption": "B",
        "subConcept": "Articles in Context",
        "explanation": "'Tableau' est masculin (le tableau) et 'craie' est féminin (la craie).",
        "remediationTip": "Le tableau (masculine), la craie (feminine)."
      },
      {
        "id": "q-fre-obj-8",
        "quizId": "quiz-jhs1-fre-objetsclasse",
        "questionText": "Quel objet sert à tailler les crayons à mine ?",
        "optionA": "Un stylo",
        "optionB": "Un taille-crayon",
        "optionC": "Un cartable",
        "optionD": "Un classeur",
        "correctOption": "B",
        "subConcept": "Taille-crayon",
        "explanation": "Un taille-crayon est l'instrument qui sert à tailler les crayons (pencil sharpener).",
        "remediationTip": "Pencil sharpener = un taille-crayon."
      },
      {
        "id": "q-fre-obj-9",
        "quizId": "quiz-jhs1-fre-objetsclasse",
        "questionText": "Que répond-on à la question 'Qu'est-ce que c'est ?' en montrant une règle ?",
        "optionA": "Il s'appelle règle.",
        "optionB": "C'est une règle.",
        "optionC": "Elle est règle.",
        "optionD": "Voici règle.",
        "correctOption": "B",
        "subConcept": "Answering Qu'est-ce que c'est",
        "explanation": "On répond par 'C'est un/une...' → 'C'est une règle.'",
        "remediationTip": "Answer with 'C'est un/une...'."
      },
      {
        "id": "q-fre-obj-10",
        "quizId": "quiz-jhs1-fre-objetsclasse",
        "questionText": "Pourquoi écrit-on 'L'école' au lieu de 'La école' ?",
        "optionA": "Parce que école est un mot masculin",
        "optionB": "Pour éviter la rencontre de deux voyelles (élision)",
        "optionC": "Parce que c'est un mot étranger",
        "optionD": "C'est une faute d'orthographe",
        "correctOption": "B",
        "subConcept": "Elision with L'",
        "explanation": "Quand l'article 'la' ou 'le' précède une voyelle, la voyelle s'élide en 'l'': l'école.",
        "remediationTip": "Elision (l') prevents vowel collision: l'école."
      }
    ]
  },
  "jhs1-fre-t5-nationalite": {
    "id": "quiz-jhs1-fre-nationalite",
    "topicId": "jhs1-fre-t5-nationalite",
    "title": "Nationalités, Pays et Prépositions Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-nat-1",
        "quizId": "quiz-jhs1-fre-nationalite",
        "questionText": "Quel est le féminin de la nationalité 'ghanéen' ?",
        "optionA": "ghanéene",
        "optionB": "ghanéenne",
        "optionC": "ghanéese",
        "optionD": "ghanéane",
        "correctOption": "B",
        "subConcept": "Féminin de Ghanéen",
        "explanation": "Les nationalités en -ien doublent le 'n' et ajoutent un 'e': ghanéen → ghanéenne.",
        "remediationTip": "Ghanéen becomes ghanéenne in the feminine (double 'n')."
      },
      {
        "id": "q-fre-nat-2",
        "quizId": "quiz-jhs1-fre-nationalite",
        "questionText": "Quelle préposition utilise-t-on devant le pays masculin 'Ghana' pour dire 'in Ghana' ?",
        "optionA": "en",
        "optionB": "au",
        "optionC": "à",
        "optionD": "aux",
        "correctOption": "B",
        "subConcept": "Préposition AU",
        "explanation": "Le Ghana est un pays masculin (ne se termine pas par 'e'); il prend donc la préposition 'AU': 'au Ghana'.",
        "remediationTip": "Masculine countries take AU: au Ghana, au Togo, au Nigéria."
      },
      {
        "id": "q-fre-nat-3",
        "quizId": "quiz-jhs1-fre-nationalite",
        "questionText": "Quelle préposition utilise-t-on devant le pays féminin 'Côte d'Ivoire' ?",
        "optionA": "au",
        "optionB": "en",
        "optionC": "à la",
        "optionD": "aux",
        "correctOption": "B",
        "subConcept": "Préposition EN",
        "explanation": "La Côte d'Ivoire est un pays féminin (se termine par 'e'); il prend la préposition 'EN': 'en Côte d'Ivoire'.",
        "remediationTip": "Feminine countries ending in 'e' take EN: en Côte d'Ivoire, en France."
      },
      {
        "id": "q-fre-nat-4",
        "quizId": "quiz-jhs1-fre-nationalite",
        "questionText": "Quel est le féminin de 'togolais' ?",
        "optionA": "togolaine",
        "optionB": "togolaise",
        "optionC": "togolaisenne",
        "optionD": "togolaiseuse",
        "correctOption": "B",
        "subConcept": "Féminin de Togolais",
        "explanation": "Togolais prend un 'e' au féminin: togolaise (prononcé avec le son /z/).",
        "remediationTip": "Togolais → togolaise (add 'e')."
      },
      {
        "id": "q-fre-nat-5",
        "quizId": "quiz-jhs1-fre-nationalite",
        "questionText": "Complétez avec le verbe être: 'Fatou vient d'Abidjan, elle ___ ivoirienne.'",
        "optionA": "es",
        "optionB": "est",
        "optionC": "a",
        "optionD": "suis",
        "correctOption": "B",
        "subConcept": "Verbe Être pour Nationalité",
        "explanation": "Avec le pronom 'elle', la 3e personne du verbe être est 'est': 'elle est ivoirienne.'",
        "remediationTip": "Use 'est' with il/elle: elle est ivoirienne."
      },
      {
        "id": "q-fre-nat-6",
        "quizId": "quiz-jhs1-fre-nationalite",
        "questionText": "Comment appelle-t-on un habitant du Burkina Faso ?",
        "optionA": "Un Burkinier",
        "optionB": "Un Burkinabé",
        "optionC": "Un Burkinien",
        "optionD": "Un Burkinan",
        "correctOption": "B",
        "subConcept": "Nationalité Burkinabé",
        "explanation": "L'habitant du Burkina Faso est un Burkinabé (ou une Burkinabè).",
        "remediationTip": "A citizen of Burkina Faso is a Burkinabé."
      },
      {
        "id": "q-fre-nat-7",
        "quizId": "quiz-jhs1-fre-nationalite",
        "questionText": "Quelle préposition de lieu convient pour le pays pluriel 'les États-Unis' ?",
        "optionA": "au",
        "optionB": "aux",
        "optionC": "en",
        "optionD": "à",
        "correctOption": "B",
        "subConcept": "Préposition AUX",
        "explanation": "Pour les pays dont le nom est pluriel, on utilise la préposition 'AUX': 'aux États-Unis'.",
        "remediationTip": "Plural country names take AUX: aux États-Unis."
      },
      {
        "id": "q-fre-nat-8",
        "quizId": "quiz-jhs1-fre-nationalite",
        "questionText": "Quelle question permet de s'enquérir de la nationalité de quelqu'un ?",
        "optionA": "Quel âge as-tu ?",
        "optionB": "Quelle est ta nationalité ?",
        "optionC": "Comment vas-tu ?",
        "optionD": "Qu'est-ce que c'est ?",
        "correctOption": "B",
        "subConcept": "Asking Nationality",
        "explanation": "'Quelle est ta nationalité ?' ou 'De quelle nationalité es-tu ?' demande la nationalité.",
        "remediationTip": "Ask nationality with 'Quelle est ta nationalité ?'."
      },
      {
        "id": "q-fre-nat-9",
        "quizId": "quiz-jhs1-fre-nationalite",
        "questionText": "Comment dit-on en français: 'John is Nigerian and his sister is Nigerian too' ?",
        "optionA": "John est nigérian et sa sœur est nigériane aussi.",
        "optionB": "John est nigériane et sa sœur est nigérian aussi.",
        "optionC": "John a nigérian et sa sœur a nigériane.",
        "optionD": "John est nigérian et sa sœur est nigérian.",
        "correctOption": "A",
        "subConcept": "Nationality Gender Agreement",
        "explanation": "John est masculin (nigérian) et sa sœur est féminine (nigériane).",
        "remediationTip": "John is nigérian; his sister is nigériane."
      },
      {
        "id": "q-fre-nat-10",
        "quizId": "quiz-jhs1-fre-nationalite",
        "questionText": "Quelle nationalité ci-dessous a la MÊME forme au masculin et au féminin car elle se termine déjà par 'e' ?",
        "optionA": "français",
        "optionB": "suisse",
        "optionC": "ivoirien",
        "optionD": "américain",
        "correctOption": "B",
        "subConcept": "Invariable Nationality (Suisse)",
        "explanation": "Les adjectifs de nationalité qui se terminent déjà par 'e' au masculin ne changent pas au féminin: suisse (un homme suisse, une femme suisse).",
        "remediationTip": "'suisse' remains unchanged in the feminine."
      }
    ]
  },
  "jhs1-fre-t6-famille": {
    "id": "quiz-jhs1-fre-famille",
    "topicId": "jhs1-fre-t6-famille",
    "title": "La Famille et Adjectifs Possessifs Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-fam-1",
        "quizId": "quiz-jhs1-fre-famille",
        "questionText": "Quel adjectif possessif (my) utilise-t-on devant le mot féminin 'mère' ?",
        "optionA": "mon",
        "optionB": "ma",
        "optionC": "mes",
        "optionD": "ton",
        "correctOption": "B",
        "subConcept": "Possessif Ma",
        "explanation": "'Mère' est féminin singulier: on dit 'ma mère' (my mother).",
        "remediationTip": "Feminine singular takes 'ma': ma mère, ma sœur."
      },
      {
        "id": "q-fre-fam-2",
        "quizId": "quiz-jhs1-fre-famille",
        "questionText": "Quel adjectif possessif (my) utilise-t-on devant le mot masculin 'père' ?",
        "optionA": "ma",
        "optionB": "mon",
        "optionC": "mes",
        "optionD": "sa",
        "correctOption": "B",
        "subConcept": "Possessif Mon",
        "explanation": "'Père' est masculin singulier: on dit 'mon père' (my father).",
        "remediationTip": "Masculine singular takes 'mon': mon père, mon frère."
      },
      {
        "id": "q-fre-fam-3",
        "quizId": "quiz-jhs1-fre-famille",
        "questionText": "Quel adjectif possessif pluriel utilise-t-on pour 'my brothers' ?",
        "optionA": "mon frères",
        "optionB": "mes frères",
        "optionC": "ma frères",
        "optionD": "ses frères",
        "correctOption": "B",
        "subConcept": "Possessif Mes",
        "explanation": "Au pluriel, 'my' devient 'mes' quel que soit le genre du nom: 'mes frères' (my brothers).",
        "remediationTip": "Plural takes 'mes': mes frères, mes sœurs, mes parents."
      },
      {
        "id": "q-fre-fam-4",
        "quizId": "quiz-jhs1-fre-famille",
        "questionText": "Pourquoi dit-on 'MON amie' et non 'MA amie', bien que 'amie' soit un mot féminin ?",
        "optionA": "Parce que amie est masculin",
        "optionB": "Pour éviter la collision de deux voyelles (a-a)",
        "optionC": "C'est une erreur de grammaire",
        "optionD": "Parce que l'ami est un garçon",
        "correctOption": "B",
        "subConcept": "Exception Mon Amie",
        "explanation": "Devant un nom féminin commençant par une voyelle, 'ma' devient 'mon' pour assurer une liaison fluide et éviter le hiatus: 'mon amie', 'mon école'.",
        "remediationTip": "Use 'mon' (not 'ma') before feminine words starting with a vowel."
      },
      {
        "id": "q-fre-fam-5",
        "quizId": "quiz-jhs1-fre-famille",
        "questionText": "Comment appelle-t-on le frère de son père en français ?",
        "optionA": "Le cousin",
        "optionB": "L'oncle",
        "optionC": "Le grand-père",
        "optionD": "Le neveu",
        "correctOption": "B",
        "subConcept": "Family Relations (Oncle)",
        "explanation": "Le frère de son père ou de sa mère est 'l'oncle' (uncle).",
        "remediationTip": "Father's or mother's brother is 'l'oncle'."
      },
      {
        "id": "q-fre-fam-6",
        "quizId": "quiz-jhs1-fre-famille",
        "questionText": "Comment appelle-t-on la mère de sa mère en français ?",
        "optionA": "La tante",
        "optionB": "La grand-mère",
        "optionC": "La cousine",
        "optionD": "La nièce",
        "correctOption": "B",
        "subConcept": "Grand-mère",
        "explanation": "La mère de son père ou de sa mère est 'la grand-mère' (grandmother).",
        "remediationTip": "Grandmother is 'la grand-mère'."
      },
      {
        "id": "q-fre-fam-7",
        "quizId": "quiz-jhs1-fre-famille",
        "questionText": "Complétez: 'Kofi parle avec ___ sœur.' (his sister)",
        "optionA": "son",
        "optionB": "sa",
        "optionC": "ses",
        "optionD": "mon",
        "correctOption": "B",
        "subConcept": "Possessif Sa",
        "explanation": "En français, l'adjectif possessif s'accorde avec le nom possédé: 'sœur' est féminin, donc on utilise 'sa sœur' (his sister).",
        "remediationTip": "'Sœur' is feminine, so use 'sa sœur' for his/her sister."
      },
      {
        "id": "q-fre-fam-8",
        "quizId": "quiz-jhs1-fre-famille",
        "questionText": "Comment dit-on 'daughter' en français ?",
        "optionA": "la fille",
        "optionB": "le fils",
        "optionC": "la sœur",
        "optionD": "la nièce",
        "correctOption": "A",
        "subConcept": "Fille vs Fils",
        "explanation": "'La fille' signifie daughter (ou girl); 'le fils' signifie son.",
        "remediationTip": "'La fille' = daughter; 'le fils' = son."
      },
      {
        "id": "q-fre-fam-9",
        "quizId": "quiz-jhs1-fre-famille",
        "questionText": "Quel possessif (your - informel) convient pour 'your parents' ?",
        "optionA": "ton parents",
        "optionB": "tes parents",
        "optionC": "ta parents",
        "optionD": "ses parents",
        "correctOption": "B",
        "subConcept": "Possessif Tes",
        "explanation": "'Parents' est pluriel: on utilise 'tes' avec 'tu' ('tes parents').",
        "remediationTip": "Plural possessive for 'tu' is 'tes': tes parents."
      },
      {
        "id": "q-fre-fam-10",
        "quizId": "quiz-jhs1-fre-famille",
        "questionText": "Comment dit-on 'We are five in my family' en français ?",
        "optionA": "Nous sommes cinq dans ma famille.",
        "optionB": "Nous avons cinq dans mon famille.",
        "optionC": "Je suis cinq dans famille.",
        "optionD": "Ils sont cinq avec moi.",
        "correctOption": "A",
        "subConcept": "Describing Family Size",
        "explanation": "'Nous sommes cinq dans ma famille' est l'expression exacte et idiomatique.",
        "remediationTip": "'Nous sommes cinq dans ma famille' = We are 5 in my family."
      }
    ]
  },
  "jhs1-fre-t7-corpshumain": {
    "id": "quiz-jhs1-fre-corpshumain",
    "topicId": "jhs1-fre-t7-corpshumain",
    "title": "Le Corps Humain et la Douleur Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-cor-1",
        "quizId": "quiz-jhs1-fre-corpshumain",
        "questionText": "Comment contracte-t-on 'à + le' dans l'expression de douleur: 'J'ai mal ___ ventre' ?",
        "optionA": "à la",
        "optionB": "au",
        "optionC": "aux",
        "optionD": "à l'",
        "correctOption": "B",
        "subConcept": "Contraction Au",
        "explanation": "'Ventre' est masculin singulier ('le ventre'). 'À + le' se contracte obligatoirement en 'AU': 'J'ai mal au ventre'.",
        "remediationTip": "'à + le' contracts into 'au': au ventre, au dos."
      },
      {
        "id": "q-fre-cor-2",
        "quizId": "quiz-jhs1-fre-corpshumain",
        "questionText": "Comment contracte-t-on 'à + les' pour exprimer un mal de dents: 'J'ai mal ___ dents' ?",
        "optionA": "au",
        "optionB": "aux",
        "optionC": "à la",
        "optionD": "à l'",
        "correctOption": "B",
        "subConcept": "Contraction Aux",
        "explanation": "'Dents' est pluriel ('les dents'). 'À + les' se contracte en 'AUX': 'J'ai mal aux dents'.",
        "remediationTip": "'à + les' contracts into 'aux': aux dents, aux yeux."
      },
      {
        "id": "q-fre-cor-3",
        "quizId": "quiz-jhs1-fre-corpshumain",
        "questionText": "Quelle partie du corps est 'la tête' ?",
        "optionA": "The chest",
        "optionB": "The head",
        "optionC": "The neck",
        "optionD": "The hand",
        "correctOption": "B",
        "subConcept": "La Tête",
        "explanation": "'La tête' signifie 'the head'. 'J'ai mal à la tête' = I have a headache.",
        "remediationTip": "La tête = the head."
      },
      {
        "id": "q-fre-cor-4",
        "quizId": "quiz-jhs1-fre-corpshumain",
        "questionText": "Quel est le pluriel irrégulier du mot 'un œil' (an eye) ?",
        "optionA": "des œils",
        "optionB": "les yeux",
        "optionC": "des œiles",
        "optionD": "les oreilles",
        "correctOption": "B",
        "subConcept": "Pluriel Œil → Yeux",
        "explanation": "Le pluriel de 'un œil' est complètement irrégulier: 'les yeux' (eyes).",
        "remediationTip": "One eye = un œil; both eyes = les yeux."
      },
      {
        "id": "q-fre-cor-5",
        "quizId": "quiz-jhs1-fre-corpshumain",
        "questionText": "Quel est le genre du mot 'main' (hand) en français ?",
        "optionA": "Toujours masculin (un main)",
        "optionB": "Féminin (une main / la main)",
        "optionC": "Neutre",
        "optionD": "Variable",
        "correctOption": "B",
        "subConcept": "Genre de Main",
        "explanation": "'Main' est un mot féminin: 'la main', 'une main'. On dit: 'Lave-toi les mains.'",
        "remediationTip": "Hand is feminine: 'la main'."
      },
      {
        "id": "q-fre-cor-6",
        "quizId": "quiz-jhs1-fre-corpshumain",
        "questionText": "Complétez: 'Le joueur de football est tombé, il a mal ___ genou.'",
        "optionA": "au",
        "optionB": "à la",
        "optionC": "aux",
        "optionD": "à l'",
        "correctOption": "A",
        "subConcept": "Au Genou",
        "explanation": "'Genou' est masculin singulier (le genou): à + le → 'au genou'.",
        "remediationTip": "Genou is masculine: au genou."
      },
      {
        "id": "q-fre-cor-7",
        "quizId": "quiz-jhs1-fre-corpshumain",
        "questionText": "Que signifie 'Il est grand et mince' ?",
        "optionA": "He is short and fat",
        "optionB": "He is tall and slim",
        "optionC": "He is old and rich",
        "optionD": "He is sick and tired",
        "correctOption": "B",
        "subConcept": "Physical Description",
        "explanation": "'Grand' signifie tall; 'mince' signifie slim/thin. 'Il est grand et mince' = He is tall and slim.",
        "remediationTip": "Grand = tall; petit = short; mince = slim; gros = fat."
      },
      {
        "id": "q-fre-cor-8",
        "quizId": "quiz-jhs1-fre-corpshumain",
        "questionText": "Comment dit-on 'ear' en français ?",
        "optionA": "Le nez",
        "optionB": "L'oreille",
        "optionC": "Le bras",
        "optionD": "La jambe",
        "correctOption": "B",
        "subConcept": "L'Oreille",
        "explanation": "'L'oreille' (féminin) est l'organe de l'ouïe (ear).",
        "remediationTip": "Ear = l'oreille."
      },
      {
        "id": "q-fre-cor-9",
        "quizId": "quiz-jhs1-fre-corpshumain",
        "questionText": "Complétez pour exprimer un mal d'oreille: 'Ama a mal ___ oreille droite.'",
        "optionA": "au",
        "optionB": "à l'",
        "optionC": "à la",
        "optionD": "aux",
        "correctOption": "B",
        "subConcept": "À l'Oreille",
        "explanation": "'Oreille' commence par une voyelle: on utilise 'à l'' → 'à l'oreille'.",
        "remediationTip": "Before a vowel, use 'à l'': à l'oreille, à l'œil."
      },
      {
        "id": "q-fre-cor-10",
        "quizId": "quiz-jhs1-fre-corpshumain",
        "questionText": "Quelle partie du corps relie la tête aux épaules ?",
        "optionA": "Le cou",
        "optionB": "Le genou",
        "optionC": "Le pied",
        "optionD": "Le coude",
        "correctOption": "A",
        "subConcept": "Le Cou",
        "explanation": "'Le cou' est la partie du corps qui relie la tête au tronc (neck).",
        "remediationTip": "Neck = le cou; elbow = le coude."
      }
    ]
  },
  "jhs1-fre-t8-vetementscouleurs": {
    "id": "quiz-jhs1-fre-vetementscouleurs",
    "topicId": "jhs1-fre-t8-vetementscouleurs",
    "title": "Les Vêtements et les Couleurs Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-vet-1",
        "quizId": "quiz-jhs1-fre-vetementscouleurs",
        "questionText": "Où se place généralement l'adjectif de COULEUR par rapport au nom en français ?",
        "optionA": "Toujours avant le nom (un bleu pantalon)",
        "optionB": "Généralement après le nom (un pantalon bleu)",
        "optionC": "Au début de la phrase",
        "optionD": "À la fin du paragraphe",
        "correctOption": "B",
        "subConcept": "Position of Color Adjectives",
        "explanation": "En français, les adjectifs de couleur se placent presque toujours APRÈS le nom qu'ils qualifient: 'un pantalon bleu', 'une robe rouge'.",
        "remediationTip": "Color adjectives always come AFTER the noun: une robe rouge."
      },
      {
        "id": "q-fre-vet-2",
        "quizId": "quiz-jhs1-fre-vetementscouleurs",
        "questionText": "Quel est le féminin de l'adjectif 'blanc' (white) ?",
        "optionA": "blanque",
        "optionB": "blanche",
        "optionC": "blance",
        "optionD": "blancette",
        "correctOption": "B",
        "subConcept": "Féminin de Blanc",
        "explanation": "Le féminin régulier de 'blanc' est 'blanche' (ex: une chemise blanche).",
        "remediationTip": "Blanc (masc) → blanche (fem)."
      },
      {
        "id": "q-fre-vet-3",
        "quizId": "quiz-jhs1-fre-vetementscouleurs",
        "questionText": "Quelles sont les DEUX couleurs invariables qui ne prennent JAMAIS de 'e' ni de 's' au féminin ou au pluriel ?",
        "optionA": "Noir et blanc",
        "optionB": "Orange et marron",
        "optionC": "Bleu et vert",
        "optionD": "Rouge et jaune",
        "correctOption": "B",
        "subConcept": "Invariable Colors (Orange & Marron)",
        "explanation": "'Orange' et 'marron' sont des noms de fruits utilisés comme couleurs; ils sont totalement invariables (pas de 'e', pas de 's').",
        "remediationTip": "'Orange' and 'marron' NEVER take an 's' or 'e'."
      },
      {
        "id": "q-fre-vet-4",
        "quizId": "quiz-jhs1-fre-vetementscouleurs",
        "questionText": "Complétez avec l'accord correct: 'Ama porte une jupe ___.' (vert)",
        "optionA": "vert",
        "optionB": "verte",
        "optionC": "vertes",
        "optionD": "verts",
        "correctOption": "B",
        "subConcept": "Accord Féminin de Vert",
        "explanation": "'Jupe' est féminin singulier: l'adjectif 'vert' prend un 'e' → 'une jupe verte'.",
        "remediationTip": "Feminine takes 'e': une jupe verte."
      },
      {
        "id": "q-fre-vet-5",
        "quizId": "quiz-jhs1-fre-vetementscouleurs",
        "questionText": "Quel vêtement masculin désigne un 'pantalon court' souvent porté par les élèves de JHS ?",
        "optionA": "Une robe",
        "optionB": "Un short",
        "optionC": "Une jupe",
        "optionD": "Une cravate",
        "correctOption": "B",
        "subConcept": "Short Masculin",
        "explanation": "'Un short' (masculin) est la culotte courte portée à l'école.",
        "remediationTip": "Short is masculine: un short."
      },
      {
        "id": "q-fre-vet-6",
        "quizId": "quiz-jhs1-fre-vetementscouleurs",
        "questionText": "Complétez: 'Les élèves portent des chaussures ___.' (noir)",
        "optionA": "noir",
        "optionB": "noires",
        "optionC": "noirs",
        "optionD": "noire",
        "correctOption": "B",
        "subConcept": "Chaussures Noires",
        "explanation": "'Chaussures' est féminin pluriel (une chaussure): l'adjectif prend 'es' → 'des chaussures noires'.",
        "remediationTip": "'Chaussures' is feminine plural: des chaussures noires."
      },
      {
        "id": "q-fre-vet-7",
        "quizId": "quiz-jhs1-fre-vetementscouleurs",
        "questionText": "Quel verbe utilise-t-on pour dire 'to wear clothes' en français ?",
        "optionA": "Manger",
        "optionB": "Porter",
        "optionC": "Habiter",
        "optionD": "Parler",
        "correctOption": "B",
        "subConcept": "Verbe Porter",
        "explanation": "Le verbe 'porter' signifie 'to wear' (ou 'to carry'): 'Je porte un uniforme.'",
        "remediationTip": "'Porter' = to wear."
      },
      {
        "id": "q-fre-vet-8",
        "quizId": "quiz-jhs1-fre-vetementscouleurs",
        "questionText": "Que porte un homme élégant autour du cou avec une chemise ?",
        "optionA": "Une ceinture",
        "optionB": "Une cravate",
        "optionC": "Une chaussette",
        "optionD": "Une jupe",
        "correctOption": "B",
        "subConcept": "Une Cravate",
        "explanation": "'Une cravate' (tie) se porte autour du cou avec une chemise.",
        "remediationTip": "Tie = une cravate."
      },
      {
        "id": "q-fre-vet-9",
        "quizId": "quiz-jhs1-fre-vetementscouleurs",
        "questionText": "Quelle couleur s'écrit de la MÊME manière au masculin et au féminin singulier ?",
        "optionA": "bleu",
        "optionB": "rouge",
        "optionC": "noir",
        "optionD": "vert",
        "correctOption": "B",
        "subConcept": "Rouge Invariable au Féminin",
        "explanation": "'Rouge' se termine déjà par 'e' au masculin, donc il ne change pas au féminin (un stylo rouge, une robe rouge).",
        "remediationTip": "Adjectives already ending in 'e' don't add another 'e': rouge, jaune, rose."
      },
      {
        "id": "q-fre-vet-10",
        "quizId": "quiz-jhs1-fre-vetementscouleurs",
        "questionText": "Comment écrit-on correctement 'orange shoes' en français ?",
        "optionA": "des chaussures oranges",
        "optionB": "des chaussures orange",
        "optionC": "des oranges chaussures",
        "optionD": "des chaussures orangees",
        "correctOption": "B",
        "subConcept": "Chaussures Orange",
        "explanation": "'Orange' est invariable et ne prend jamais de 's': 'des chaussures orange'.",
        "remediationTip": "Orange is invariable: des chaussures orange (no 's')."
      }
    ]
  },
  "jhs1-fre-t9-tempsdate": {
    "id": "quiz-jhs1-fre-tempsdate",
    "topicId": "jhs1-fre-t9-tempsdate",
    "title": "Jours, Mois, Date et Météo Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-dat-1",
        "quizId": "quiz-jhs1-fre-tempsdate",
        "questionText": "Quel est le PREMIER jour de la semaine dans le calendrier scolaire en français ?",
        "optionA": "Dimanche",
        "optionB": "Lundi",
        "optionC": "Mardi",
        "optionD": "Samedi",
        "correctOption": "B",
        "subConcept": "Premier Jour de la Semaine",
        "explanation": "En français, la semaine commence par le lundi (Monday).",
        "remediationTip": "French weeks start on Monday (lundi)."
      },
      {
        "id": "q-fre-dat-2",
        "quizId": "quiz-jhs1-fre-tempsdate",
        "questionText": "Comment écrit-on le premier jour d'un mois en français ?",
        "optionA": "Le un (le 1)",
        "optionB": "Le premier (le 1er)",
        "optionC": "Le début",
        "optionD": "La une",
        "correctOption": "B",
        "subConcept": "Le Premier du Mois",
        "explanation": "Pour le jour numéro 1 d'un mois, on dit et écrit toujours 'le premier' (le 1er), jamais 'le un'.",
        "remediationTip": "Always say 'le premier' (le 1er) for the 1st of any month."
      },
      {
        "id": "q-fre-dat-3",
        "quizId": "quiz-jhs1-fre-tempsdate",
        "questionText": "Quel mois précède immédiatement le mois de MARS ?",
        "optionA": "Janvier",
        "optionB": "Février",
        "optionC": "Avril",
        "optionD": "Mai",
        "correctOption": "B",
        "subConcept": "Mois de l'Année (Février)",
        "explanation": "Février est le deuxième mois de l'année, précédant mars.",
        "remediationTip": "Janvier → Février → Mars → Avril."
      },
      {
        "id": "q-fre-dat-4",
        "quizId": "quiz-jhs1-fre-tempsdate",
        "questionText": "Comment exprime-t-on qu'il fait chaud en français ?",
        "optionA": "Il est chaud.",
        "optionB": "Il fait chaud.",
        "optionC": "Il a chaud.",
        "optionD": "Le temps a chaud.",
        "correctOption": "B",
        "subConcept": "Météo Il fait chaud",
        "explanation": "Pour la météo, on utilise la formule impersonnelle 'Il fait...' → 'Il fait chaud.'",
        "remediationTip": "Weather uses 'Il fait...': Il fait chaud, Il fait beau."
      },
      {
        "id": "q-fre-dat-5",
        "quizId": "quiz-jhs1-fre-tempsdate",
        "questionText": "Quelle formule impersonnelle signifie 'It is raining' ?",
        "optionA": "Il pleut.",
        "optionB": "Il neige.",
        "optionC": "Il vente.",
        "optionD": "Il tombe l'eau.",
        "correctOption": "A",
        "subConcept": "Il Pleut",
        "explanation": "'Il pleut' vient du verbe pleuvoir et signifie 'It is raining'.",
        "remediationTip": "'Il pleut' = It is raining."
      },
      {
        "id": "q-fre-dat-6",
        "quizId": "quiz-jhs1-fre-tempsdate",
        "questionText": "Est-ce que les jours de la semaine et les mois prennent une MAJUSCULE en français ?",
        "optionA": "Oui, toujours comme en anglais",
        "optionB": "Non, ils s'écrivent avec une lettre minuscule",
        "optionC": "Seulement le dimanche",
        "optionD": "Seulement au pluriel",
        "correctOption": "B",
        "subConcept": "Minuscules pour Jours et Mois",
        "explanation": "Contrairement à l'anglais, les jours et mois s'écrivent avec une minuscule en français (lundi, mardi, janvier...).",
        "remediationTip": "Days and months use lowercase letters in French: lundi, mars."
      },
      {
        "id": "q-fre-dat-7",
        "quizId": "quiz-jhs1-fre-tempsdate",
        "questionText": "Quel est le jour saint de prière en congrégation pour les chrétiens en français ?",
        "optionA": "Vendredi",
        "optionB": "Dimanche",
        "optionC": "Samedi",
        "optionD": "Mercredi",
        "correctOption": "B",
        "subConcept": "Dimanche",
        "explanation": "'Dimanche' est Sunday en français, jour traditionnel du culte chrétien.",
        "remediationTip": "Dimanche = Sunday."
      },
      {
        "id": "q-fre-dat-8",
        "quizId": "quiz-jhs1-fre-tempsdate",
        "questionText": "Comment traduit-on 'Ghana Independence Day is on the 6th of March' ?",
        "optionA": "L'Indépendance du Ghana est au six de mars.",
        "optionB": "La fête de l'Indépendance du Ghana est le 6 mars.",
        "optionC": "L'Indépendance est en 6 mars.",
        "optionD": "Ghana est six mars.",
        "correctOption": "B",
        "subConcept": "Date du 6 Mars",
        "explanation": "La structure de la date est 'le + chiffre + mois' sans préposition 'de': 'le 6 mars'.",
        "remediationTip": "Date formula: le + number + month (le 6 mars)."
      },
      {
        "id": "q-fre-dat-9",
        "quizId": "quiz-jhs1-fre-tempsdate",
        "questionText": "Quel mois de l'année compte seulement 28 ou 29 jours ?",
        "optionA": "Avril",
        "optionB": "Février",
        "optionC": "Juin",
        "optionD": "Novembre",
        "correctOption": "B",
        "subConcept": "Février 28/29 Jours",
        "explanation": "Février est le mois le plus court de l'année avec 28 jours (29 lors des années bissextiles).",
        "remediationTip": "Février has 28 or 29 days."
      },
      {
        "id": "q-fre-dat-10",
        "quizId": "quiz-jhs1-fre-tempsdate",
        "questionText": "Que signifie l'expression météorologique: 'Il y a du soleil' ?",
        "optionA": "It is windy",
        "optionB": "It is sunny",
        "optionC": "It is foggy",
        "optionD": "It is night",
        "correctOption": "B",
        "subConcept": "Il y a du Soleil",
        "explanation": "'Il y a du soleil' signifie qu'il fait ensoleillé (It is sunny).",
        "remediationTip": "'Il y a du soleil' = It is sunny."
      }
    ]
  },
  "jhs1-fre-t10-heure": {
    "id": "quiz-jhs1-fre-heure",
    "topicId": "jhs1-fre-t10-heure",
    "title": "L'Heure et les Activités Quotidiennes Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-heu-1",
        "quizId": "quiz-jhs1-fre-heure",
        "questionText": "Quelle question pose-t-on pour demander l'heure à quelqu'un ?",
        "optionA": "Quel âge as-tu ?",
        "optionB": "Quelle heure est-il ?",
        "optionC": "Où est la montre ?",
        "optionD": "Combien d'heures travailles-tu ?",
        "correctOption": "B",
        "subConcept": "Asking Time",
        "explanation": "'Quelle heure est-il ?' est la formule standard pour demander 'What time is it?'.",
        "remediationTip": "Ask time with 'Quelle heure est-il ?'."
      },
      {
        "id": "q-fre-heu-2",
        "quizId": "quiz-jhs1-fre-heure",
        "questionText": "Comment dit-on 'It is 8:15' (quarter past eight) en français ?",
        "optionA": "Il est huit heures quinze minutes.",
        "optionB": "Il est huit heures et quart.",
        "optionC": "Il est huit heures et demie.",
        "optionD": "Il est neuf heures moins le quart.",
        "correctOption": "B",
        "subConcept": "Et Quart (:15)",
        "explanation": "Pour les quarts d'heure (:15), on utilise 'et quart': 'Il est huit heures et quart'.",
        "remediationTip": ":15 is 'et quart'."
      },
      {
        "id": "q-fre-heu-3",
        "quizId": "quiz-jhs1-fre-heure",
        "questionText": "Comment dit-on 'It is 8:30' (half past eight) en français ?",
        "optionA": "Il est huit heures et quart.",
        "optionB": "Il est huit heures et demie.",
        "optionC": "Il est neuf heures moins le quart.",
        "optionD": "Il est huit heures trente-deux.",
        "correctOption": "B",
        "subConcept": "Et Demie (:30)",
        "explanation": "Pour la demi-heure (:30), on utilise 'et demie': 'Il est huit heures et demie'.",
        "remediationTip": ":30 is 'et demie'."
      },
      {
        "id": "q-fre-heu-4",
        "quizId": "quiz-jhs1-fre-heure",
        "questionText": "Comment exprime-t-on 12:00 PM (midi) en français ?",
        "optionA": "Il est minuit.",
        "optionB": "Il est midi.",
        "optionC": "Il est douze heures du matin.",
        "optionD": "Il est le soleil.",
        "correctOption": "B",
        "subConcept": "Midi (12:00 PM)",
        "explanation": "12:00 PM en pleine journée est 'midi': 'Il est midi.'",
        "remediationTip": "12:00 PM = midi; 12:00 AM = minuit."
      },
      {
        "id": "q-fre-heu-5",
        "quizId": "quiz-jhs1-fre-heure",
        "questionText": "Comment exprime-t-on 12:00 AM (minuit) en français ?",
        "optionA": "Il est midi.",
        "optionB": "Il est minuit.",
        "optionC": "Il est zéro heure pile.",
        "optionD": "Il est la nuit.",
        "correctOption": "B",
        "subConcept": "Minuit (12:00 AM)",
        "explanation": "12:00 AM au milieu de la nuit est 'minuit': 'Il est minuit.'",
        "remediationTip": "12:00 midnight = Il est minuit."
      },
      {
        "id": "q-fre-heu-6",
        "quizId": "quiz-jhs1-fre-heure",
        "questionText": "Comment dit-on 'It is 8:45' (quarter to nine) en français ?",
        "optionA": "Il est huit heures quarante-cinq.",
        "optionB": "Il est neuf heures moins le quart.",
        "optionC": "Il est neuf heures et quart.",
        "optionD": "Il est huit heures moins le quart.",
        "correctOption": "B",
        "subConcept": "Moins le Quart (:45)",
        "explanation": "Pour :45, on avance à l'heure suivante et on retranche le quart: 'Il est neuf heures moins le quart'.",
        "remediationTip": "8:45 = Il est neuf heures moins le quart."
      },
      {
        "id": "q-fre-heu-7",
        "quizId": "quiz-jhs1-fre-heure",
        "questionText": "Quel verbe pronominal exprime 'to wake up' dans la routine matinale ?",
        "optionA": "Se coucher",
        "optionB": "Se réveiller",
        "optionC": "Se promener",
        "optionD": "Se taire",
        "correctOption": "B",
        "subConcept": "Se Réveiller",
        "explanation": "'Se réveiller' signifie to wake up: 'Je me réveille à six heures.'",
        "remediationTip": "'Se réveiller' = to wake up; 'se coucher' = to go to sleep."
      },
      {
        "id": "q-fre-heu-8",
        "quizId": "quiz-jhs1-fre-heure",
        "questionText": "Pourquoi écrit-on 'Il est une heure' SANS 's' à heure ?",
        "optionA": "C'est une exception sans raison",
        "optionB": "Parce que 'une' est au singulier",
        "optionC": "Parce que heure est masculin",
        "optionD": "C'est une faute d'orthographe",
        "correctOption": "B",
        "subConcept": "Une Heure Singulier",
        "explanation": "'Une heure' est au singulier (1 hour), donc 'heure' ne prend pas de 's'. À partir de deux heures (2+), on ajoute un 's'.",
        "remediationTip": "'Il est une heure' (no 's'); 'Il est deux heures' (add 's')."
      },
      {
        "id": "q-fre-heu-9",
        "quizId": "quiz-jhs1-fre-heure",
        "questionText": "Quelle phrase décrit correctement le fait d'aller au lit le soir ?",
        "optionA": "Je me lave à 21h.",
        "optionB": "Je me couche à 21h.",
        "optionC": "Je me réveille à 21h.",
        "optionD": "Je vais à l'école à 21h.",
        "correctOption": "B",
        "subConcept": "Se Coucher",
        "explanation": "'Se coucher' signifie aller au lit pour dormir: 'Je me couche à 21h.'",
        "remediationTip": "Go to bed = se coucher."
      },
      {
        "id": "q-fre-heu-10",
        "quizId": "quiz-jhs1-fre-heure",
        "questionText": "Comment dit-on 'at 7:00 AM' dans une phrase comme 'Je vais à l'école ___' ?",
        "optionA": "dans sept heures",
        "optionB": "à sept heures",
        "optionC": "sur sept heures",
        "optionD": "en sept heures",
        "correctOption": "B",
        "subConcept": "Préposition À pour l'Heure",
        "explanation": "Pour indiquer l'heure d'un événement, on utilise la préposition 'à': 'à sept heures' (at 7 o'clock).",
        "remediationTip": "Use 'à' before time: à 7 heures, à midi."
      }
    ]
  },
  "jhs1-fre-t11-animaux": {
    "id": "quiz-jhs1-fre-animaux",
    "topicId": "jhs1-fre-t11-animaux",
    "title": "Les Animaux et Prépositions de Lieu Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-anm-1",
        "quizId": "quiz-jhs1-fre-animaux",
        "questionText": "Quel animal domestique aboie et garde la maison en disant 'Ouah-ouah' ?",
        "optionA": "Le chat",
        "optionB": "Le chien",
        "optionC": "Le cheval",
        "optionD": "Le canard",
        "correctOption": "B",
        "subConcept": "Le Chien",
        "explanation": "Le chien (dog) est l'animal de compagnie qui aboie et surveille la maison.",
        "remediationTip": "Dog = le chien."
      },
      {
        "id": "q-fre-anm-2",
        "quizId": "quiz-jhs1-fre-animaux",
        "questionText": "Quel grand animal sauvage d'Afrique est surnommé 'le roi de la forêt' ?",
        "optionA": "L'éléphant",
        "optionB": "Le lion",
        "optionC": "Le léopard",
        "optionD": "Le crocodile",
        "correctOption": "B",
        "subConcept": "Le Lion",
        "explanation": "Le lion est traditionnellement célébré comme le roi des animaux.",
        "remediationTip": "Lion = le lion (king of beasts)."
      },
      {
        "id": "q-fre-anm-3",
        "quizId": "quiz-jhs1-fre-animaux",
        "questionText": "Comment traduit-on 'The cat is UNDER the table' en français ?",
        "optionA": "Le chat est sur la table.",
        "optionB": "Le chat est sous la table.",
        "optionC": "Le chat est dans la table.",
        "optionD": "Le chat est devant la table.",
        "correctOption": "B",
        "subConcept": "Préposition Sous",
        "explanation": "'Sous' signifie 'under/underneath': 'Le chat est sous la table.'",
        "remediationTip": "Under = sous; on = sur."
      },
      {
        "id": "q-fre-anm-4",
        "quizId": "quiz-jhs1-fre-animaux",
        "questionText": "Comment traduit-on 'The bird is ON the branch' ?",
        "optionA": "L'oiseau est sous la branche.",
        "optionB": "L'oiseau est sur la branche.",
        "optionC": "L'oiseau est derrière la branche.",
        "optionD": "L'oiseau est sans la branche.",
        "correctOption": "B",
        "subConcept": "Préposition Sur",
        "explanation": "'Sur' signifie 'on/on top of': 'L'oiseau est sur la branche.'",
        "remediationTip": "On = sur."
      },
      {
        "id": "q-fre-anm-5",
        "quizId": "quiz-jhs1-fre-animaux",
        "questionText": "Quel animal d'élevage pond des œufs et glousse dans la basse-cour ?",
        "optionA": "La chèvre",
        "optionB": "La poule",
        "optionC": "La brebis",
        "optionD": "La jument",
        "correctOption": "B",
        "subConcept": "La Poule",
        "explanation": "'La poule' (hen) pond les œufs et élève les poussins.",
        "remediationTip": "Hen = la poule; rooster = le coq."
      },
      {
        "id": "q-fre-anm-6",
        "quizId": "quiz-jhs1-fre-animaux",
        "questionText": "Quel animal sauvage est le plus grand mammifère terrestre avec une longue trompe ?",
        "optionA": "La girafe",
        "optionB": "L'éléphant",
        "optionC": "L'hippopotame",
        "optionD": "Le rhinocéros",
        "correctOption": "B",
        "subConcept": "L'Éléphant",
        "explanation": "L'éléphant est le plus grand animal terrestre doté d'une trompe et de défenses en ivoire.",
        "remediationTip": "Elephant = l'éléphant."
      },
      {
        "id": "q-fre-anm-7",
        "quizId": "quiz-jhs1-fre-animaux",
        "questionText": "Quel reptile redoutable vit dans les rivières et les lagunes ?",
        "optionA": "Le canard",
        "optionB": "Le crocodile",
        "optionC": "Le singe",
        "optionD": "Le zèbre",
        "correctOption": "B",
        "subConcept": "Le Crocodile",
        "explanation": "Le crocodile est un reptile aquatique vivant dans les rivières tropicales.",
        "remediationTip": "Crocodile = le crocodile."
      },
      {
        "id": "q-fre-anm-8",
        "quizId": "quiz-jhs1-fre-animaux",
        "questionText": "Que signifie la préposition 'DERRIÈRE' dans: 'La chèvre est derrière la maison' ?",
        "optionA": "In front of",
        "optionB": "Behind",
        "optionC": "Next to",
        "optionD": "Between",
        "correctOption": "B",
        "subConcept": "Préposition Derrière",
        "explanation": "'Derrière' signifie 'behind'. L'opposé est 'devant' (in front of).",
        "remediationTip": "Derrière = behind; devant = in front of."
      },
      {
        "id": "q-fre-anm-9",
        "quizId": "quiz-jhs1-fre-animaux",
        "questionText": "Comment appelle-t-on le petit du chien ?",
        "optionA": "Le chaton",
        "optionB": "Le chiot",
        "optionC": "Le poussin",
        "optionD": "L'agneau",
        "correctOption": "B",
        "subConcept": "Le Chiot",
        "explanation": "Le petit du chien est un chiot (puppy).",
        "remediationTip": "Puppy = un chiot; kitten = un chaton."
      },
      {
        "id": "q-fre-anm-10",
        "quizId": "quiz-jhs1-fre-animaux",
        "questionText": "Lequel des animaux ci-dessous est un animal DOMESTIQUE ?",
        "optionA": "Le léopard",
        "optionB": "Le mouton",
        "optionC": "Le serpent",
        "optionD": "La girafe",
        "correctOption": "B",
        "subConcept": "Animaux Domestiques",
        "explanation": "Le mouton (sheep) est élevé à la ferme pour sa laine et sa viande.",
        "remediationTip": "Mouton is a domestic farm animal."
      }
    ]
  },
  "jhs1-fre-t12-nourriture": {
    "id": "quiz-jhs1-fre-nourriture",
    "topicId": "jhs1-fre-t12-nourriture",
    "title": "Nourriture, Repas et Articles Partitifs Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-nou-1",
        "quizId": "quiz-jhs1-fre-nourriture",
        "questionText": "Comment appelle-t-on le repas pris LE MATIN au réveil ?",
        "optionA": "Le déjeuner",
        "optionB": "Le petit-déjeuner",
        "optionC": "Le dîner",
        "optionD": "Le goûter",
        "correctOption": "B",
        "subConcept": "Le Petit-Déjeuner",
        "explanation": "Le premier repas de la journée le matin est le petit-déjeuner (breakfast).",
        "remediationTip": "Breakfast = le petit-déjeuner."
      },
      {
        "id": "q-fre-nou-2",
        "quizId": "quiz-jhs1-fre-nourriture",
        "questionText": "Quel article partitif utilise-t-on devant le nom masculin 'pain' dans 'Je mange ___ pain' ?",
        "optionA": "de la",
        "optionB": "du",
        "optionC": "des",
        "optionD": "de l'",
        "correctOption": "B",
        "subConcept": "Article Partitif Du",
        "explanation": "'Pain' est masculin singulier ('le pain'): on utilise l'article partitif 'du' → 'Je mange du pain'.",
        "remediationTip": "Masculine food takes 'du': du pain, du riz, du poisson."
      },
      {
        "id": "q-fre-nou-3",
        "quizId": "quiz-jhs1-fre-nourriture",
        "questionText": "Quel article partitif utilise-t-on devant le nom féminin 'viande' dans 'Elle mange ___ viande' ?",
        "optionA": "du",
        "optionB": "de la",
        "optionC": "de l'",
        "optionD": "des",
        "correctOption": "B",
        "subConcept": "Article Partitif De la",
        "explanation": "'Viande' est féminin singulier: on utilise 'de la' → 'de la viande'.",
        "remediationTip": "Feminine food takes 'de la': de la viande, de la salade."
      },
      {
        "id": "q-fre-nou-4",
        "quizId": "quiz-jhs1-fre-nourriture",
        "questionText": "Que deviennent TOUS les articles partitifs (du, de la, des) dans une phrase NÉGATIVE (ne...pas) ?",
        "optionA": "Ils restent inchangés",
        "optionB": "Ils se transforment tous en 'DE' (ou 'D'')",
        "optionC": "Ils deviennent 'du'",
        "optionD": "Ils sont remplacés par 'un'",
        "correctOption": "B",
        "subConcept": "Partitive in Negative Sentences",
        "explanation": "À la forme négative, 'du', 'de la', 'de l'', 'des' deviennent simplement 'de' (ou 'd'' devant voyelle): 'Je ne mange pas de viande.'",
        "remediationTip": "In negative sentences, du/de la/des turn into DE (or D')."
      },
      {
        "id": "q-fre-nou-5",
        "quizId": "quiz-jhs1-fre-nourriture",
        "questionText": "Complétez la phrase négative: 'Kofi boit du lait, mais Kwame ne boit pas ___ lait.'",
        "optionA": "du",
        "optionB": "de",
        "optionC": "des",
        "optionD": "le",
        "correctOption": "B",
        "subConcept": "Pas de Lait",
        "explanation": "À la négation, 'du lait' devient obligatoirement 'de lait': 'ne boit pas de lait'.",
        "remediationTip": "Negative rule: pas + DE + noun."
      },
      {
        "id": "q-fre-nou-6",
        "quizId": "quiz-jhs1-fre-nourriture",
        "questionText": "Quel article partitif utilise-t-on devant 'eau' (mot commençant par une voyelle) ?",
        "optionA": "du",
        "optionB": "de l'",
        "optionC": "de la",
        "optionD": "des",
        "correctOption": "B",
        "subConcept": "Article Partitif De l'",
        "explanation": "'Eau' commence par une voyelle: on utilise 'de l'' → 'Je bois de l'eau'.",
        "remediationTip": "Before a vowel, use 'de l'': de l'eau."
      },
      {
        "id": "q-fre-nou-7",
        "quizId": "quiz-jhs1-fre-nourriture",
        "questionText": "Lequel des éléments suivants est un FRUIT tropical courant au Ghana ?",
        "optionA": "L'oignon",
        "optionB": "La mangue",
        "optionC": "Le piment",
        "optionD": "Le gombo",
        "correctOption": "B",
        "subConcept": "Fruits (La Mangue)",
        "explanation": "La mangue (mango), la banane et l'ananas sont des fruits délicieux.",
        "remediationTip": "Mango = la mangue."
      },
      {
        "id": "q-fre-nou-8",
        "quizId": "quiz-jhs1-fre-nourriture",
        "questionText": "Quelle expression française utilise le verbe AVOIR pour dire 'I am hungry' ?",
        "optionA": "Je suis faim.",
        "optionB": "J'ai faim.",
        "optionC": "Je mange faim.",
        "optionD": "J'ai soif.",
        "correctOption": "B",
        "subConcept": "Avoir Faim",
        "explanation": "En français, on a faim (verbe avoir): 'J'ai faim' = I am hungry. 'J'ai soif' = I am thirsty.",
        "remediationTip": "I am hungry = J'ai faim (uses verb avoir)."
      },
      {
        "id": "q-fre-nou-9",
        "quizId": "quiz-jhs1-fre-nourriture",
        "questionText": "Comment appelle-t-on le repas pris à MIDI ?",
        "optionA": "Le petit-déjeuner",
        "optionB": "Le déjeuner",
        "optionC": "Le dîner",
        "optionD": "Le souper",
        "correctOption": "B",
        "subConcept": "Le Déjeuner",
        "explanation": "Le repas de midi est 'le déjeuner' (lunch).",
        "remediationTip": "Lunch = le déjeuner."
      },
      {
        "id": "q-fre-nou-10",
        "quizId": "quiz-jhs1-fre-nourriture",
        "questionText": "Comment dit-on 'I drink water' en français standard ?",
        "optionA": "Je mange l'eau.",
        "optionB": "Je bois de l'eau.",
        "optionC": "Je bois l'eau.",
        "optionD": "Je suis eau.",
        "correctOption": "B",
        "subConcept": "Boire de l'Eau",
        "explanation": "On utilise le verbe boire + article partitif 'de l'': 'Je bois de l'eau.'",
        "remediationTip": "I drink water = Je bois de l'eau."
      }
    ]
  },
  "jhs1-fre-t13-professions": {
    "id": "quiz-jhs1-fre-professions",
    "topicId": "jhs1-fre-t13-professions",
    "title": "Les Métiers et Professions Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-pro-1",
        "quizId": "quiz-jhs1-fre-professions",
        "questionText": "Quelle règle s'applique à l'ARTICLE quand on indique une profession après le verbe ÊTRE ?",
        "optionA": "On doit toujours mettre 'un' ou 'une' (Il est un docteur)",
        "optionB": "On supprime l'article indéfini (Il est docteur)",
        "optionC": "On utilise toujours 'le' ou 'la'",
        "optionD": "On utilise le pluriel",
        "correctOption": "B",
        "subConcept": "Omission of Article after Être",
        "explanation": "Après le verbe être, l'article est supprimé devant les professions: 'Il est médecin', 'Elle est institutrice'.",
        "remediationTip": "Never use 'un/une' after être for professions: 'Il est médecin'."
      },
      {
        "id": "q-fre-pro-2",
        "quizId": "quiz-jhs1-fre-professions",
        "questionText": "Quel est le féminin de 'un instituteur' (elementary teacher) ?",
        "optionA": "une instituteuse",
        "optionB": "une institutrice",
        "optionC": "une institutère",
        "optionD": "une instituteur",
        "correctOption": "B",
        "subConcept": "Féminin en -trice",
        "explanation": "Les mots en -teur deviennent -trice au féminin: un instituteur → une institutrice, un directeur → une directrice.",
        "remediationTip": "-teur becomes -trice: instituteur → institutrice."
      },
      {
        "id": "q-fre-pro-3",
        "quizId": "quiz-jhs1-fre-professions",
        "questionText": "Quel est le féminin de 'un infirmier' (nurse) ?",
        "optionA": "une infirmière",
        "optionB": "une infirmiuse",
        "optionC": "une infirmienne",
        "optionD": "une infirmitrice",
        "correctOption": "A",
        "subConcept": "Féminin en -ière",
        "explanation": "Les mots en -ier font leur féminin en -ière: infirmier → infirmière, boulanger → boulangère.",
        "remediationTip": "-ier becomes -ière: infirmier → infirmière."
      },
      {
        "id": "q-fre-pro-4",
        "quizId": "quiz-jhs1-fre-professions",
        "questionText": "Quel est le féminin de 'un chanteur' (singer) ?",
        "optionA": "une chantrice",
        "optionB": "une chanteuse",
        "optionC": "une chantière",
        "optionD": "une chantienne",
        "correctOption": "B",
        "subConcept": "Féminin en -euse",
        "explanation": "Les mots dérivés de verbes en -eur deviennent -euse: un chanteur → une chanteuse (de chanter).",
        "remediationTip": "-eur becomes -euse: chanteur → chanteuse."
      },
      {
        "id": "q-fre-pro-5",
        "quizId": "quiz-jhs1-fre-professions",
        "questionText": "Quel professionnel soigne les malades dans un hôpital ?",
        "optionA": "Le maçon",
        "optionB": "Le médecin (ou docteur)",
        "optionC": "Le chauffeur",
        "optionD": "Le menuisier",
        "correctOption": "B",
        "subConcept": "Le Médecin",
        "explanation": "Le médecin (ou docteur) examine et soigne les malades à l'hôpital ou à la clinique.",
        "remediationTip": "Doctor = le médecin / docteur."
      },
      {
        "id": "q-fre-pro-6",
        "quizId": "quiz-jhs1-fre-professions",
        "questionText": "Quel professionnel conduit des avions de ligne dans les airs ?",
        "optionA": "Le mécanicien",
        "optionB": "Le pilote",
        "optionC": "Le capitaine de navire",
        "optionD": "L'artisan",
        "correctOption": "B",
        "subConcept": "Le Pilote",
        "explanation": "Le pilote est la personne qui pilote un avion.",
        "remediationTip": "Pilot = le pilote."
      },
      {
        "id": "q-fre-pro-7",
        "quizId": "quiz-jhs1-fre-professions",
        "questionText": "Quel est le féminin de 'un mécanicien' ?",
        "optionA": "une mécanicière",
        "optionB": "une mécanicienne",
        "optionC": "une mécanicieuse",
        "optionD": "une mécanitrice",
        "correctOption": "B",
        "subConcept": "Féminin en -ienne",
        "explanation": "Les métiers en -ien doublent le 'n' et prennent 'e': mécanicien → mécanicienne, pharmacien → pharmacienne.",
        "remediationTip": "-ien becomes -ienne: mécanicien → mécanicienne."
      },
      {
        "id": "q-fre-pro-8",
        "quizId": "quiz-jhs1-fre-professions",
        "questionText": "Comment dit-on en français: 'In the future, I want to be a teacher' ?",
        "optionA": "À l'avenir, je veux être un professeur.",
        "optionB": "À l'avenir, je veux être professeur.",
        "optionC": "À l'avenir, j'ai professeur.",
        "optionD": "Dans futur, je suis professeur.",
        "correctOption": "B",
        "subConcept": "Expressing Career Ambition",
        "explanation": "On dit 'À l'avenir, je veux être professeur' (sans article 'un').",
        "remediationTip": "'Je veux être professeur' (omit 'un')."
      },
      {
        "id": "q-fre-pro-9",
        "quizId": "quiz-jhs1-fre-professions",
        "questionText": "Quel artisan fabrique des meubles en bois (tables, chaises, portes) ?",
        "optionA": "Le boulanger",
        "optionB": "Le menuisier",
        "optionC": "Le tailleur",
        "optionD": "Le boucher",
        "correctOption": "B",
        "subConcept": "Le Menuisier",
        "explanation": "Le menuisier (carpenter) travaille le bois pour créer des tables, armoires et portes.",
        "remediationTip": "Carpenter = le menuisier."
      },
      {
        "id": "q-fre-pro-10",
        "quizId": "quiz-jhs1-fre-professions",
        "questionText": "Quel commerçant fabrique et vend du pain frais et des croissants ?",
        "optionA": "L'épicier",
        "optionB": "Le boulanger",
        "optionC": "Le cordonnier",
        "optionD": "Le libraire",
        "correctOption": "B",
        "subConcept": "Le Boulanger",
        "explanation": "Le boulanger prépare et cuit le pain dans la boulangerie.",
        "remediationTip": "Baker = le boulanger."
      }
    ]
  },
  "jhs1-fre-t14-verbeser": {
    "id": "quiz-jhs1-fre-verbeser",
    "topicId": "jhs1-fre-t14-verbeser",
    "title": "Verbes du 1er Groupe (-ER) au Présent Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-ver-1",
        "quizId": "quiz-jhs1-fre-verbeser",
        "questionText": "Quelles sont les 6 terminaisons des verbes réguliers en -ER au présent de l'indicatif ?",
        "optionA": "-s, -s, -t, -ons, -ez, -ent",
        "optionB": "-e, -es, -e, -ons, -ez, -ent",
        "optionC": "-is, -is, -it, -issons, -issez, -issent",
        "optionD": "-ai, -as, -a, -ons, -ez, -ont",
        "correctOption": "B",
        "subConcept": "-ER Verb Endings",
        "explanation": "Les terminaisons du 1er groupe au présent sont: -e (je), -es (tu), -e (il/elle), -ons (nous), -ez (vous), -ent (ils/elles).",
        "remediationTip": "Present endings for -ER verbs: -e, -es, -e, -ons, -ez, -ent."
      },
      {
        "id": "q-fre-ver-2",
        "quizId": "quiz-jhs1-fre-verbeser",
        "questionText": "Conjuguez le verbe PARLER avec le pronom 'Tu': 'Tu ___ français.'",
        "optionA": "parle",
        "optionB": "parles",
        "optionC": "parlez",
        "optionD": "parlons",
        "correctOption": "B",
        "subConcept": "Conjugation Tu Parles",
        "explanation": "Avec 'Tu', les verbes en -ER prennent la terminaison '-es': 'Tu parles'.",
        "remediationTip": "'Tu' always ends in '-es' with -ER verbs: Tu parles."
      },
      {
        "id": "q-fre-ver-3",
        "quizId": "quiz-jhs1-fre-verbeser",
        "questionText": "Conjuguez le verbe HABITER avec 'Je': '___ à Accra.'",
        "optionA": "Je habite",
        "optionB": "J'habite",
        "optionC": "J'habites",
        "optionD": "Je habites",
        "correctOption": "B",
        "subConcept": "Elision J'habite",
        "explanation": "'Habiter' commence par un 'h' muet: 'Je' s'élide en 'J'' et prend la terminaison '-e' → 'J'habite'.",
        "remediationTip": "Use J' before silent h or vowels: J'habite."
      },
      {
        "id": "q-fre-ver-4",
        "quizId": "quiz-jhs1-fre-verbeser",
        "questionText": "Pourquoi écrit-on 'Nous MANGEONS' avec un 'e' devant 'ons' ?",
        "optionA": "Pour garder le son doux /ʒ/ de la lettre 'g'",
        "optionB": "C'est une erreur que l'on tolère",
        "optionC": "Parce que manger est un verbe irrégulier",
        "optionD": "Pour faire rimer le verbe",
        "correctOption": "A",
        "subConcept": "Particularité de Manger",
        "explanation": "Sans le 'e', 'mangons' se prononcerait avec un son dur /g/ (man-gon). Le 'e' préserve le son doux /ʒ/.",
        "remediationTip": "Verbs ending in -ger add 'e' before -ons: Nous mangeons."
      },
      {
        "id": "q-fre-ver-5",
        "quizId": "quiz-jhs1-fre-verbeser",
        "questionText": "Conjuguez REGARDER avec le sujet pluriel 'Kofi et Ama': 'Kofi et Ama ___ la télévision.'",
        "optionA": "regarde",
        "optionB": "regardent",
        "optionC": "regardons",
        "optionD": "regardez",
        "correctOption": "B",
        "subConcept": "3rd Person Plural -ent",
        "explanation": "'Kofi et Ama' équivaut au pronom 'Ils' (3e personne du pluriel); la terminaison est '-ent' (muet): 'regardent'.",
        "remediationTip": "Plural subject takes '-ent': regardent."
      },
      {
        "id": "q-fre-ver-6",
        "quizId": "quiz-jhs1-fre-verbeser",
        "questionText": "Est-ce que la terminaison '-ent' à la 3e personne du pluriel (ils parlent) se prononce à l'oral ?",
        "optionA": "Oui, elle se prononce comme 'dent'",
        "optionB": "Non, la terminaison '-ent' est totalement muette",
        "optionC": "Seulement devant une consonne",
        "optionD": "Elle se prononce /en/",
        "correctOption": "B",
        "subConcept": "Silent -ent Ending",
        "explanation": "La terminaison '-ent' des verbes est muette. 'Ils parlent' se prononce exactement comme 'il parle' /il parl/.",
        "remediationTip": "The '-ent' ending on plural verbs is completely silent."
      },
      {
        "id": "q-fre-ver-7",
        "quizId": "quiz-jhs1-fre-verbeser",
        "questionText": "Quel verbe en -ER ci-dessous est IRRÉGULIER et n'appartient PAS au premier groupe ?",
        "optionA": "Aimer",
        "optionB": "Aller",
        "optionC": "Chanter",
        "optionD": "Danser",
        "correctOption": "B",
        "subConcept": "Exception Verbe Aller",
        "explanation": "Le verbe 'ALLER' se termine par -ER mais il est du 3e groupe car sa conjugaison est complètement irrégulière (je vais, tu vas, il va...).",
        "remediationTip": "ALLER is irregular (3rd group), not a regular 1st group verb."
      },
      {
        "id": "q-fre-ver-8",
        "quizId": "quiz-jhs1-fre-verbeser",
        "questionText": "Conjuguez ÉCOUTER avec 'Vous': 'Vous ___ le professeur.'",
        "optionA": "écoutons",
        "optionB": "écoutez",
        "optionC": "écoute",
        "optionD": "écoutent",
        "correctOption": "B",
        "subConcept": "Conjugation Vous Écoutez",
        "explanation": "La terminaison avec 'Vous' est '-ez': 'Vous écoutez'.",
        "remediationTip": "'Vous' takes '-ez': Vous écoutez."
      },
      {
        "id": "q-fre-ver-9",
        "quizId": "quiz-jhs1-fre-verbeser",
        "questionText": "Conjuguez AIMER avec 'Nous': 'Nous ___ le français.'",
        "optionA": "aimez",
        "optionB": "aimons",
        "optionC": "aiment",
        "optionD": "aimes",
        "correctOption": "B",
        "subConcept": "Conjugation Nous Aimons",
        "explanation": "Avec 'Nous', la terminaison est '-ons': 'Nous aimons'.",
        "remediationTip": "'Nous' takes '-ons': Nous aimons."
      },
      {
        "id": "q-fre-ver-10",
        "quizId": "quiz-jhs1-fre-verbeser",
        "questionText": "Comment obtient-on le RADICAL d'un verbe du 1er groupe avant d'ajouter les terminaisons ?",
        "optionA": "En ajoutant -ER à la fin",
        "optionB": "En supprimant la terminaison -ER de l'infinitif",
        "optionC": "En traduisant le verbe en anglais",
        "optionD": "En doublant la première lettre",
        "correctOption": "B",
        "subConcept": "Finding the Verb Radical",
        "explanation": "Pour trouver le radical, on enlève simplement -ER: Parl-er → radical = parl-.",
        "remediationTip": "Remove '-er' to get the stem: Chant-er → chant-."
      }
    ]
  },
  "jhs1-fre-t15-verbesirreguliers": {
    "id": "quiz-jhs1-fre-verbesirreguliers",
    "topicId": "jhs1-fre-t15-verbesirreguliers",
    "title": "ÊTRE, AVOIR, ALLER, FAIRE et la Négation Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-fre-irr-1",
        "quizId": "quiz-jhs1-fre-verbesirreguliers",
        "questionText": "Conjuguez le verbe ÊTRE avec 'Nous': 'Nous ___ en classe.'",
        "optionA": "avons",
        "optionB": "sommes",
        "optionC": "êtes",
        "optionD": "sont",
        "correctOption": "B",
        "subConcept": "Être avec Nous",
        "explanation": "La forme de ÊTRE avec 'Nous' est 'sommes': 'Nous sommes en classe.'",
        "remediationTip": "Nous sommes (ÊTRE)."
      },
      {
        "id": "q-fre-irr-2",
        "quizId": "quiz-jhs1-fre-verbesirreguliers",
        "questionText": "Quelle est la différence phonétique entre 'Ils sont' (être) et 'Ils ont' (avoir) ?",
        "optionA": "'Ils sont' se prononce avec un son /s/ et 'Ils ont' avec un son /z/",
        "optionB": "Les deux s'entendent exactement de la même manière",
        "optionC": "'Ils ont' a un son muet",
        "optionD": "'Ils sont' se termine par un 't' sonore",
        "correctOption": "A",
        "subConcept": "Phonétique Ils sont vs Ils ont",
        "explanation": "'Ils sont' (être) se prononce /il son/ avec le son /s/. 'Ils ont' (avoir) fait la liaison sonore /il-z-on/ avec le son /z/.",
        "remediationTip": "'Ils sont' = /s/ sound; 'Ils ont' = /z/ sound."
      },
      {
        "id": "q-fre-irr-3",
        "quizId": "quiz-jhs1-fre-verbesirreguliers",
        "questionText": "Conjuguez le verbe ALLER avec 'Je': 'Je ___ à l'église.'",
        "optionA": "vas",
        "optionB": "vais",
        "optionC": "va",
        "optionD": "alle",
        "correctOption": "B",
        "subConcept": "Aller avec Je",
        "explanation": "Avec 'Je', la forme de ALLER au présent est 'vais': 'Je vais à l'église.'",
        "remediationTip": "Je vais (ALLER)."
      },
      {
        "id": "q-fre-irr-4",
        "quizId": "quiz-jhs1-fre-verbesirreguliers",
        "questionText": "Conjuguez le verbe FAIRE avec 'Vous': 'Vous ___ vos devoirs.'",
        "optionA": "faisez",
        "optionB": "faites",
        "optionC": "faisons",
        "optionD": "font",
        "correctOption": "B",
        "subConcept": "Faire avec Vous",
        "explanation": "La 2e personne du pluriel de FAIRE est 'faites' (attention: 'faisez' n'existe pas en français !): 'Vous faites vos devoirs.'",
        "remediationTip": "'Vous faites' (never write 'faisez')."
      },
      {
        "id": "q-fre-irr-5",
        "quizId": "quiz-jhs1-fre-verbesirreguliers",
        "questionText": "Comment transforme-t-on la phrase affirmative 'Je suis fatigué' à la forme NÉGATIVE ?",
        "optionA": "Je suis pas fatigué.",
        "optionB": "Je ne suis pas fatigué.",
        "optionC": "Je pas suis fatigué.",
        "optionD": "Ne je suis pas fatigué.",
        "correctOption": "B",
        "subConcept": "Négation avec Ne...pas",
        "explanation": "En français standard, on encadre le verbe conjugué avec 'ne' et 'pas': 'Je ne suis pas fatigué.'",
        "remediationTip": "Wrap verb with 'ne ... pas': Je ne suis pas."
      },
      {
        "id": "q-fre-irr-6",
        "quizId": "quiz-jhs1-fre-verbesirreguliers",
        "questionText": "Quand 'ne' précède un verbe commençant par une voyelle, comment s'écrit-il ?",
        "optionA": "ne",
        "optionB": "n'",
        "optionC": "no",
        "optionD": "ni",
        "correctOption": "B",
        "subConcept": "Élision N'",
        "explanation": "Devant une voyelle ou un h muet, 'ne' s'élide en 'n'': 'Je n'ai pas de stylo', 'Il n'aime pas le riz'.",
        "remediationTip": "Use 'n'' before vowels: n'ai pas, n'aime pas."
      },
      {
        "id": "q-fre-irr-7",
        "quizId": "quiz-jhs1-fre-verbesirreguliers",
        "questionText": "Conjuguez le verbe AVOIR avec 'Ils': 'Ils ___ faim.'",
        "optionA": "ont",
        "optionB": "sont",
        "optionC": "font",
        "optionD": "vont",
        "correctOption": "A",
        "subConcept": "Avoir avec Ils",
        "explanation": "La forme de AVOIR avec 'Ils' est 'ont': 'Ils ont faim.'",
        "remediationTip": "Ils ont (AVOIR)."
      },
      {
        "id": "q-fre-irr-8",
        "quizId": "quiz-jhs1-fre-verbesirreguliers",
        "questionText": "Conjuguez le verbe ALLER avec 'Ils / Elles': 'Les élèves ___ au marché.'",
        "optionA": "allent",
        "optionB": "vont",
        "optionC": "font",
        "optionD": "va",
        "correctOption": "B",
        "subConcept": "Aller avec Ils",
        "explanation": "La forme de ALLER avec 'Ils/Elles' est 'vont': 'Les élèves vont au marché.'",
        "remediationTip": "Ils vont (ALLER)."
      },
      {
        "id": "q-fre-irr-9",
        "quizId": "quiz-jhs1-fre-verbesirreguliers",
        "questionText": "Quelle phrase négative est correctement orthographiée ?",
        "optionA": "Elle a pas un stylo.",
        "optionB": "Elle n'a pas de stylo.",
        "optionC": "Elle ne a pas de stylo.",
        "optionD": "Elle pas a un stylo.",
        "correctOption": "B",
        "subConcept": "Negative Article Transformation",
        "explanation": "L'élision 'n'' est requise devant 'a' et l'article indéfini 'un' devient 'de' à la négation: 'Elle n'a pas de stylo.'",
        "remediationTip": "'Elle n'a pas de stylo' (n' + de)."
      },
      {
        "id": "q-fre-irr-10",
        "quizId": "quiz-jhs1-fre-verbesirreguliers",
        "questionText": "Conjuguez le verbe FAIRE avec 'Ils': 'Kofi et Kojo ___ du football.'",
        "optionA": "font",
        "optionB": "faient",
        "optionC": "faisons",
        "optionD": "faitent",
        "correctOption": "A",
        "subConcept": "Faire avec Ils",
        "explanation": "La 3e personne du pluriel de FAIRE est 'font': 'Kofi et Kojo font du football.'",
        "remediationTip": "Ils font (FAIRE)."
      }
    ]
  }
};
