// Ghanaian JHS 3 French Quizzes
// Based on NaCCA / GES Common Core Programme (CCP) Curriculum
// 12 Topics × 10 Questions = 120 BECE-Standard Questions

import { TopicQuiz } from './types';

export const JHS3_FRENCH_QUIZZES: Record<string, TopicQuiz> = {
  "jhs3-fre-t1-identite-biographie-presentation": {
    "id": "quiz-jhs3-fre-t1-identite-biographie-presentation",
    "topicId": "jhs3-fre-t1-identite-biographie-presentation",
    "title": "L'Identité Personnelle, l'Autobiographie et la Présentation de Soi BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t1-q1",
        "quizId": "quiz-jhs3-fre-t1-identite-biographie-presentation",
        "questionText": "Quelle phrase exprime correctement l'âge d'un élève en français ?",
        "optionA": "Je suis quatorze ans.",
        "optionB": "J'ai quatorze ans.",
        "optionC": "Je fais quatorze ans.",
        "optionD": "Mon âge est quatorze ans d'années.",
        "correctOption": "B",
        "subConcept": "Expression de l'Âge",
        "explanation": "En français, l'âge s'exprime obligatoirement avec le verbe AVOIR conjugué au présent (J'ai quatorze ans), jamais avec le verbe Être.",
        "remediationTip": "Ne traduisez pas littéralement de l'anglais : utilisez 'J'ai... ans'."
      },
      {
        "id": "jhs3-fre-t1-q2",
        "quizId": "quiz-jhs3-fre-t1-identite-biographie-presentation",
        "questionText": "Complétez la phrase suivante pour une candidate féminine : 'Ama est née en 2011 et elle est ______.'",
        "optionA": "ghanéen",
        "optionB": "ghanéens",
        "optionC": "ghanéenne",
        "optionD": "ghanéennes",
        "correctOption": "C",
        "subConcept": "Accord des Adjectifs de Nationalité",
        "explanation": "L'adjectif de nationalité s'accorde en genre avec le sujet. Pour une fille (Ama, elle), on ajoute 'ne' : ghanéenne.",
        "remediationTip": "Masculin = ghanéen ; Féminin = ghanéenne."
      },
      {
        "id": "jhs3-fre-t1-q3",
        "quizId": "quiz-jhs3-fre-t1-identite-biographie-presentation",
        "questionText": "Quelle préposition doit-on utiliser pour introduire une ville de résidence dans la phrase : 'Koffi habite ______ Kumasi' ?",
        "optionA": "en",
        "optionB": "au",
        "optionC": "à",
        "optionD": "dans",
        "correctOption": "C",
        "subConcept": "Prépositions devant les Noms de Villes",
        "explanation": "Devant un nom de ville, on emploie systématiquement la préposition 'à' avec accent grave (à Kumasi, à Accra, à Paris).",
        "remediationTip": "Utilisez 'à' devant les noms de villes : à Accra, à Tamale, à Takoradi."
      },
      {
        "id": "jhs3-fre-t1-q4",
        "quizId": "quiz-jhs3-fre-t1-identite-biographie-presentation",
        "questionText": "Sur une fiche d'identité officielle du BECE, que signifie le mot 'Prénom' ?",
        "optionA": "Surname or Family Name",
        "optionB": "First Name or Given Name",
        "optionC": "Date of Birth",
        "optionD": "School Attendance Number",
        "correctOption": "B",
        "subConcept": "Vocabulaire de la Fiche d'Identité",
        "explanation": "'Nom' désigne le nom de famille (Surname), tandis que 'Prénom' désigne le nom de baptême ou premier prénom (First name).",
        "remediationTip": "Nom = Family Name / Surname ; Prénom = First name."
      },
      {
        "id": "jhs3-fre-t1-q5",
        "quizId": "quiz-jhs3-fre-t1-identite-biographie-presentation",
        "questionText": "Choisissez la forme correcte du participe passé : 'Akosua est ______ le 10 avril 2010.'",
        "optionA": "né",
        "optionB": "née",
        "optionC": "nés",
        "optionD": "nées",
        "correctOption": "B",
        "subConcept": "Accord du Participe Passé 'né'",
        "explanation": "Le participe passé conjugué avec l'auxiliaire ÊTRE s'accorde avec le sujet. Akosua étant de sexe féminin singulier, on écrit 'née'.",
        "remediationTip": "Akosua est une fille -> ajoutez un 'e' final : 'née'."
      },
      {
        "id": "jhs3-fre-t1-q6",
        "quizId": "quiz-jhs3-fre-t1-identite-biographie-presentation",
        "questionText": "Comment dit-on en français : 'He is hardworking and punctual' ?",
        "optionA": "Il est travail et point.",
        "optionB": "Il est travailleur et ponctuel.",
        "optionC": "Il est travailleuse et ponctuelle.",
        "optionD": "Il a travailleur et ponctuel.",
        "correctOption": "B",
        "subConcept": "Description Morale et Qualités",
        "explanation": "Pour un sujet masculin singulier (Il), les adjectifs qualificatifs masculins sont 'travailleur' et 'ponctuel'.",
        "remediationTip": "Masculin : travailleur, ponctuel ; Féminin : travailleuse, ponctuelle."
      },
      {
        "id": "jhs3-fre-t1-q7",
        "quizId": "quiz-jhs3-fre-t1-identite-biographie-presentation",
        "questionText": "Quelle préposition s'emploie directement devant une année calendaire dans la phrase : 'Je suis né ______ 2011' ?",
        "optionA": "à",
        "optionB": "en",
        "optionC": "au",
        "optionD": "sur",
        "correctOption": "B",
        "subConcept": "Prépositions Temporelles",
        "explanation": "L'année seule est toujours introduite par la préposition 'en' (en 2011, en 1957). La date complète prend 'le' (le 6 mars 1957).",
        "remediationTip": "En + année (en 2011) ; Le + date complète (le 15 août 2011)."
      },
      {
        "id": "jhs3-fre-t1-q8",
        "quizId": "quiz-jhs3-fre-t1-identite-biographie-presentation",
        "questionText": "Complétez la phrase par le verbe convenable : 'Comment tu ______ ?'",
        "optionA": "t'appelles",
        "optionB": "s'appelle",
        "optionC": "vous appelez",
        "optionD": "t'appeler",
        "correctOption": "A",
        "subConcept": "Conjugaison du Verbe S'appeler",
        "explanation": "Avec le pronom sujet 'tu', le verbe pronominal s'appeler se conjugue : 'tu t'appelles' (avec deux 'l' et terminaison 'es').",
        "remediationTip": "Je m'appelle, tu t'appelles, il/elle s'appelle."
      },
      {
        "id": "jhs3-fre-t1-q9",
        "quizId": "quiz-jhs3-fre-t1-identite-biographie-presentation",
        "questionText": "Quelle est la forme féminine de l'adjectif qualificatif 'curieux' ?",
        "optionA": "curieuxe",
        "optionB": "curieuse",
        "optionC": "curieutrice",
        "optionD": "curieusse",
        "correctOption": "B",
        "subConcept": "Formation du Féminin des Adjectifs en -eux",
        "explanation": "Les adjectifs terminés par -eux au masculin font leur féminin régulier en -euse (curieux -> curieuse, courageux -> courageuse).",
        "remediationTip": "-eux au masculin devient -euse au féminin (heureux -> heureuse)."
      },
      {
        "id": "jhs3-fre-t1-q10",
        "quizId": "quiz-jhs3-fre-t1-identite-biographie-presentation",
        "questionText": "Quelle formule permet d'exprimer son rêve professionnel sans commettre de faute d'article au BECE ?",
        "optionA": "Je veux être un médecin.",
        "optionB": "Je voudrais être médecin.",
        "optionC": "J'aime médecin être.",
        "optionD": "Je suis devenir médecin.",
        "correctOption": "B",
        "subConcept": "Expression des Métiers avec Être",
        "explanation": "Après le verbe être, les noms de métiers s'emploient sans article indéfini : 'Je voudrais être médecin' (et NON 'un médecin').",
        "remediationTip": "Pas d'article après le verbe être devant les métiers : 'être médecin', 'être enseignant'."
      }
    ]
  },
  "jhs3-fre-t2-famille-liens-sociaux": {
    "id": "quiz-jhs3-fre-t2-famille-liens-sociaux",
    "topicId": "jhs3-fre-t2-famille-liens-sociaux",
    "title": "La Famille, les Arbres Généalogiques et les Relations Sociales BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t2-q1",
        "quizId": "quiz-jhs3-fre-t2-famille-liens-sociaux",
        "questionText": "Complétez avec l'adjectif possessif approprié : 'Koffi aime beaucoup ______ école.'",
        "optionA": "sa",
        "optionB": "son",
        "optionC": "ses",
        "optionD": "leur",
        "correctOption": "B",
        "subConcept": "Euphonie des Adjectifs Possessifs",
        "explanation": "Bien que 'école' soit féminin, il commence par une voyelle. Pour éviter le hiatus, on remplace 'sa' par 'son' : 'son école'.",
        "remediationTip": "Devant un nom féminin commençant par une voyelle, utilisez 'mon, ton, son'."
      },
      {
        "id": "jhs3-fre-t2-q2",
        "quizId": "quiz-jhs3-fre-t2-famille-liens-sociaux",
        "questionText": "Comment appelle-t-on le frère de mon père ou de ma mère en français ?",
        "optionA": "Le neveu",
        "optionB": "Le cousin",
        "optionC": "L'oncle",
        "optionD": "Le beau-frère",
        "correctOption": "C",
        "subConcept": "Vocabulaire de la Parenté",
        "explanation": "Le frère du père ou de la mère est l'oncle. Le fils du frère ou de la sœur est le neveu.",
        "remediationTip": "Frère du père/mère = oncle ; Sœur du père/mère = tante."
      },
      {
        "id": "jhs3-fre-t2-q3",
        "quizId": "quiz-jhs3-fre-t2-famille-liens-sociaux",
        "questionText": "Quelle est la traduction française exacte de 'elder brother' ?",
        "optionA": "Le frère ancien",
        "optionB": "Le grand frère ou frère aîné",
        "optionC": "Le petit frère",
        "optionD": "Le frère cadet",
        "correctOption": "B",
        "subConcept": "Termes de Fratrie",
        "explanation": "'Elder brother' se traduit par 'le frère aîné' (ou grand frère). 'Younger brother' se traduit par 'le frère cadet'.",
        "remediationTip": "Aîné = plus âgé (elder) ; Cadet = plus jeune (younger)."
      },
      {
        "id": "jhs3-fre-t2-q4",
        "quizId": "quiz-jhs3-fre-t2-famille-liens-sociaux",
        "questionText": "Complétez la phrase : 'Les enfants obéissent toujours à ______ parents.'",
        "optionA": "leur",
        "optionB": "leurs",
        "optionC": "ses",
        "optionD": "nos",
        "correctOption": "B",
        "subConcept": "Possessifs Pluriels (Leur vs Leurs)",
        "explanation": "Le sujet est à la 3e personne du pluriel (Les enfants) et le nom possédé est pluriel (parents), donc on utilise 'leurs' avec un 's'.",
        "remediationTip": "Leur + nom singulier ; Leurs + nom pluriel."
      },
      {
        "id": "jhs3-fre-t2-q5",
        "quizId": "quiz-jhs3-fre-t2-famille-liens-sociaux",
        "questionText": "Qui est le fils de mon oncle ou de ma tante ?",
        "optionA": "Mon neveu",
        "optionB": "Mon parrain",
        "optionC": "Mon cousin",
        "optionD": "Mon beau-fils",
        "correctOption": "C",
        "subConcept": "Relations Familiales",
        "explanation": "Le fils de l'oncle ou de la tante est le cousin (cousine au féminin).",
        "remediationTip": "Fils de l'oncle/tante = cousin ; Fille de l'oncle/tante = cousine."
      },
      {
        "id": "jhs3-fre-t2-q6",
        "quizId": "quiz-jhs3-fre-t2-famille-liens-sociaux",
        "questionText": "Choisissez l'adjectif possessif correct pour cette phrase : 'Amina écrit une lettre à ______ amie française.'",
        "optionA": "ma",
        "optionB": "sa",
        "optionC": "son",
        "optionD": "ses",
        "correctOption": "C",
        "subConcept": "Règle d'Euphonie devant Voyelle",
        "explanation": "'Amie' est féminin singulier mais commence par la voyelle 'a'. On emploie 'son' pour éviter la cacophonie sonore 'sa amie'.",
        "remediationTip": "On dit 'son amie' et JAMAIS 'sa amie'."
      },
      {
        "id": "jhs3-fre-t2-q7",
        "quizId": "quiz-jhs3-fre-t2-famille-liens-sociaux",
        "questionText": "Quelle phrase décrit correctement la profession de la mère sans faute grammaticale ?",
        "optionA": "Ma mère est une infirmière gentille.",
        "optionB": "Ma mère est infirmière.",
        "optionC": "Ma mère travaille infirmière.",
        "optionD": "La profession de ma mère est infirmière de métier.",
        "correctOption": "B",
        "subConcept": "Grammaire des Professions",
        "explanation": "Après le verbe être, la profession s'emploie sans article : 'Ma mère est infirmière'.",
        "remediationTip": "Sujet + être + profession sans article (ex: Il est médecin, elle est infirmière)."
      },
      {
        "id": "jhs3-fre-t2-q8",
        "quizId": "quiz-jhs3-fre-t2-famille-liens-sociaux",
        "questionText": "Comment appelle-t-on deux enfants nés du même accouchement en même temps ?",
        "optionA": "Des cousins germains",
        "optionB": "Des jumeaux (ou jumelles)",
        "optionC": "Des aînés",
        "optionD": "Des neveux",
        "correctOption": "B",
        "subConcept": "Vocabulaire de la Famille",
        "explanation": "Deux enfants nés lors du même accouchement sont des jumeaux (garçons ou mixte) ou des jumelles (deux filles).",
        "remediationTip": "Jumeaux = twins (garçons) ; Jumelles = twins (filles)."
      },
      {
        "id": "jhs3-fre-t2-q9",
        "quizId": "quiz-jhs3-fre-t2-famille-liens-sociaux",
        "questionText": "Dans un arbre généalogique, les parents de mon père et de ma mère sont mes :",
        "optionA": "grands-parents",
        "optionB": "arrière-cousins",
        "optionC": "oncles par alliance",
        "optionD": "beaux-pères",
        "correctOption": "A",
        "subConcept": "Arbre Généalogique",
        "explanation": "Les parents des parents sont les grands-parents (le grand-père et la grand-mère).",
        "remediationTip": "Parents de mes parents = grands-parents."
      },
      {
        "id": "jhs3-fre-t2-q10",
        "quizId": "quiz-jhs3-fre-t2-famille-liens-sociaux",
        "questionText": "Complétez avec le possessif qui convient : 'Paul et moi, nous aimons ______ maison.'",
        "optionA": "notre",
        "optionB": "nos",
        "optionC": "leur",
        "optionD": "votre",
        "correctOption": "A",
        "subConcept": "Adjectifs Possessifs de la 1ère Personne du Pluriel",
        "explanation": "'Paul et moi' équivaut au pronom 'nous'. Le nom possédé 'maison' est singulier, on emploie donc 'notre' (nos pour le pluriel).",
        "remediationTip": "Nous -> notre (singulier), nos (pluriel)."
      }
    ]
  },
  "jhs3-fre-t3-corps-sante-maladies": {
    "id": "quiz-jhs3-fre-t3-corps-sante-maladies",
    "topicId": "jhs3-fre-t3-corps-sante-maladies",
    "title": "Le Corps Humain, l'Hygiène, les Maladies et les Consultations BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t3-q1",
        "quizId": "quiz-jhs3-fre-t3-corps-sante-maladies",
        "questionText": "Complétez correctement avec la forme contractée : 'Kwame a mangé trop de piment, il a très mal ______ ventre.'",
        "optionA": "à la",
        "optionB": "au",
        "optionC": "aux",
        "optionD": "à le",
        "correctOption": "B",
        "subConcept": "Contraction avec Avoir Mal À",
        "explanation": "'Ventre' est un nom masculin singulier (le ventre). La préposition 'à' fusionne avec 'le' pour donner 'au' : 'avoir mal au ventre'.",
        "remediationTip": "À + LE = AU (au ventre, au dos, au genou)."
      },
      {
        "id": "jhs3-fre-t3-q2",
        "quizId": "quiz-jhs3-fre-t3-corps-sante-maladies",
        "questionText": "Quelle phrase exprime correctement des douleurs dentaires en français ?",
        "optionA": "Elle a mal à la dent.",
        "optionB": "Elle a mal aux dents.",
        "optionC": "Elle a mal à les dents.",
        "optionD": "Elle a mal au dents.",
        "correctOption": "B",
        "subConcept": "Contraction au Pluriel",
        "explanation": "Le mot 'dents' est au pluriel. À + les = AUX : 'Elle a mal aux dents'.",
        "remediationTip": "À + LES = AUX (aux dents, aux yeux, aux oreilles)."
      },
      {
        "id": "jhs3-fre-t3-q3",
        "quizId": "quiz-jhs3-fre-t3-corps-sante-maladies",
        "questionText": "Quel est le genre du mot 'main' en français ?",
        "optionA": "Masculin (le main)",
        "optionB": "Féminin (la main)",
        "optionC": "Neutre",
        "optionD": "Variable selon la personne",
        "correctOption": "B",
        "subConcept": "Genre des Parties du Corps",
        "explanation": "'Main' est un nom féminin (la main). On dit donc : 'J'ai mal à la main droite'.",
        "remediationTip": "'La main' est un piège classique : bien que terminant par consonne, c'est un nom féminin."
      },
      {
        "id": "jhs3-fre-t3-q4",
        "quizId": "quiz-jhs3-fre-t3-corps-sante-maladies",
        "questionText": "Comment appelle-t-on le document écrit par un médecin contenant la liste des médicaments prescrits ?",
        "optionA": "Une facture d'achat",
        "optionB": "Une ordonnance médicale",
        "optionC": "Une lettre de congé",
        "optionD": "Un bulletin de notes",
        "correctOption": "B",
        "subConcept": "Vocabulaire Médical",
        "explanation": "L'ordonnance est la prescription écrite par un médecin ordonnant les remèdes au pharmacien.",
        "remediationTip": "Prescription = ordonnance médicale."
      },
      {
        "id": "jhs3-fre-t3-q5",
        "quizId": "quiz-jhs3-fre-t3-corps-sante-maladies",
        "questionText": "Quel symptôme typique du paludisme (malaria) correspond à l'anglais 'fever and chills' ?",
        "optionA": "La faim et la soif",
        "optionB": "La fièvre et les frissons",
        "optionC": "La toux et la joie",
        "optionD": "Le sommeil et le rire",
        "correctOption": "B",
        "subConcept": "Symptômes des Maladies",
        "explanation": "'Fever' se traduit par 'la fièvre' et 'chills' par 'les frissons'. Ce sont les symptômes majeurs du paludisme.",
        "remediationTip": "Fièvre = fever ; Frissons = chills."
      },
      {
        "id": "jhs3-fre-t3-q6",
        "quizId": "quiz-jhs3-fre-t3-corps-sante-maladies",
        "questionText": "Complétez la phrase : 'Après avoir lu toute la nuit, Kofi a mal ______ yeux.'",
        "optionA": "au",
        "optionB": "à l'",
        "optionC": "aux",
        "optionD": "à la",
        "correctOption": "C",
        "subConcept": "Contraction avec les Yeux",
        "explanation": "'Yeux' est le pluriel irrégulier de 'œil'. Étant au pluriel, on contracte : à + les = AUX yeux.",
        "remediationTip": "Yeux est au pluriel -> 'mal aux yeux'."
      },
      {
        "id": "jhs3-fre-t3-q7",
        "quizId": "quiz-jhs3-fre-t3-corps-sante-maladies",
        "questionText": "Comment un médecin demande-t-il poliment à un patient où se situe sa douleur ?",
        "optionA": "Qui êtes-vous ?",
        "optionB": "Où avez-vous mal ?",
        "optionC": "Pourquoi venez-vous ici ?",
        "optionD": "Quand partez-vous ?",
        "correctOption": "B",
        "subConcept": "Dialogue Médical",
        "explanation": "'Où avez-vous mal ?' est la question médicale standard pour localiser la douleur du patient.",
        "remediationTip": "'Où avez-vous mal ?' = Where does it hurt?"
      },
      {
        "id": "jhs3-fre-t3-q8",
        "quizId": "quiz-jhs3-fre-t3-corps-sante-maladies",
        "questionText": "Quel conseil d'hygiène préventive permet de lutter efficacement contre la propagation du choléra au Ghana ?",
        "optionA": "Manger des mangues non lavées cueillies par terre",
        "optionB": "Se laver soigneusement les mains au savon et boire de l'eau potable bouillie",
        "optionC": "Dormir sans moustiquaire près des marais",
        "optionD": "Jeter les ordures ménagères dans les caniveaux ouverts",
        "correctOption": "B",
        "subConcept": "Hygiène Préventive",
        "explanation": "Le lavage régulier des mains avec de l'eau propre et du savon et la consommation d'eau traitée empêchent la contamination par le choléra.",
        "remediationTip": "L'hygiène des mains et l'eau potable préviennent les maladies hydriques."
      },
      {
        "id": "jhs3-fre-t3-q9",
        "quizId": "quiz-jhs3-fre-t3-corps-sante-maladies",
        "questionText": "Complétez avec la préposition correcte : 'Akosua a mal ______ tête depuis ce matin.'",
        "optionA": "au",
        "optionB": "à la",
        "optionC": "aux",
        "optionD": "à l'",
        "correctOption": "B",
        "subConcept": "Contraction avec Noms Féminins",
        "explanation": "'Tête' est un nom féminin commençant par une consonne. Il n'y a pas de contraction : 'à la tête'.",
        "remediationTip": "À LA tête (pas de contraction au féminin consonne)."
      },
      {
        "id": "jhs3-fre-t3-q10",
        "quizId": "quiz-jhs3-fre-t3-corps-sante-maladies",
        "questionText": "Que dit le pharmacien lorsqu'il indique comment consommer un médicament ?",
        "optionA": "Voici votre reçu d'impôt.",
        "optionB": "Prenez deux comprimés trois fois par jour après les repas.",
        "optionC": "Retournez à l'école immédiatement.",
        "optionD": "Ne buvez jamais d'eau minérale.",
        "correctOption": "B",
        "subConcept": "Posologie Pharmaceutique",
        "explanation": "La posologie précise le nombre de prises et le moment de consommation des médicaments (comprimés/sirop).",
        "remediationTip": "Posologie = mode d'emploi et dosage des médicaments."
      }
    ]
  },
  "jhs3-fre-t4-ecole-education-avenir": {
    "id": "quiz-jhs3-fre-t4-ecole-education-avenir",
    "topicId": "jhs3-fre-t4-ecole-education-avenir",
    "title": "L'École, la Vie Scolaire et les Métiers d'Avenir BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t4-q1",
        "quizId": "quiz-jhs3-fre-t4-ecole-education-avenir",
        "questionText": "Quelle matière scolaire correspond à l'acronyme anglais 'ICT' au Ghana ?",
        "optionA": "L'Histoire",
        "optionB": "L'Informatique (ou Technologie de l'Information)",
        "optionC": "L'Éducation Physique",
        "optionD": "L'Économie Domestique",
        "correctOption": "B",
        "subConcept": "Vocabulaire des Disciplines",
        "explanation": "ICT (Information and Communications Technology) se traduit par 'l'informatique' ou les 'technologies de l'information et de la communication' (TIC).",
        "remediationTip": "ICT = L'informatique."
      },
      {
        "id": "jhs3-fre-t4-q2",
        "quizId": "quiz-jhs3-fre-t4-ecole-education-avenir",
        "questionText": "Complétez la phrase au futur simple : 'Après le BECE, les élèves ______ au lycée.'",
        "optionA": "iront",
        "optionB": "vont",
        "optionC": "iraient",
        "optionD": "ira",
        "correctOption": "A",
        "subConcept": "Futur Simple du Verbe Aller",
        "explanation": "Le sujet 'les élèves' est à la 3e personne du pluriel (ils). Le futur simple du verbe aller est 'ils iront'.",
        "remediationTip": "Aller au futur simple : j'irai, tu iras, il ira, nous irons, vous irez, ils iront."
      },
      {
        "id": "jhs3-fre-t4-q3",
        "quizId": "quiz-jhs3-fre-t4-ecole-education-avenir",
        "questionText": "Comment dit-on en français : 'The headmaster addresses the students at assembly' ?",
        "optionA": "Le professeur écrit aux élèves.",
        "optionB": "Le directeur s'adresse aux élèves lors du rassemblement.",
        "optionC": "L'élève parle au préfet dans la cour.",
        "optionD": "Le chauffeur conduit les élèves à l'école.",
        "correctOption": "B",
        "subConcept": "Vie Scolaire Quotidienne",
        "explanation": "Headmaster = le directeur/le proviseur ; assembly = le rassemblement matinal.",
        "remediationTip": "Assembly = rassemblement matinal ; Headmaster = directeur."
      },
      {
        "id": "jhs3-fre-t4-q4",
        "quizId": "quiz-jhs3-fre-t4-ecole-education-avenir",
        "questionText": "Quelle phrase justifie correctement une préférence scolaire avec un connecteur de cause ?",
        "optionA": "J'aime le français mais c'est difficile.",
        "optionB": "J'adore les mathématiques parce qu'elles développent mon esprit logique.",
        "optionC": "Je déteste les sciences donc je lis.",
        "optionD": "Les cours finissent car midi sonne.",
        "correctOption": "B",
        "subConcept": "Argumentation Scolaire",
        "explanation": "'Parce que' introduit la raison logique pour laquelle on apprécie une discipline.",
        "remediationTip": "Utilisez 'parce que' ou 'car' pour justifier votre matière préférée."
      },
      {
        "id": "jhs3-fre-t4-q5",
        "quizId": "quiz-jhs3-fre-t4-ecole-education-avenir",
        "questionText": "Comment appelle-t-on la personne qui défend les accusés devant un tribunal de justice ?",
        "optionA": "Un médecin",
        "optionB": "Un comptable",
        "optionC": "Un avocat (ou une avocate)",
        "optionD": "Un maçon",
        "correctOption": "C",
        "subConcept": "Vocabulaire des Métiers",
        "explanation": "L'avocat (avocate au féminin) est le professionnel du droit qui défend ses clients au tribunal.",
        "remediationTip": "Lawyer = avocat (masculin) / avocate (féminin)."
      },
      {
        "id": "jhs3-fre-t4-q6",
        "quizId": "quiz-jhs3-fre-t4-ecole-education-avenir",
        "questionText": "Mettez le verbe au futur simple : 'Si tu travailles bien, tu (réussir) ______ à ton examen.'",
        "optionA": "réussis",
        "optionB": "réussiras",
        "optionC": "réussirais",
        "optionD": "réussira",
        "correctOption": "B",
        "subConcept": "Règle Si + Présent = Futur Simple",
        "explanation": "Avec 'tu' au futur simple, les verbes en -ir prennent la terminaison '-as' sur l'infinitif complet : 'tu réussiras'.",
        "remediationTip": "Tu + verbe régulier au futur simple prend la terminaison '-as'."
      },
      {
        "id": "jhs3-fre-t4-q7",
        "quizId": "quiz-jhs3-fre-t4-ecole-education-avenir",
        "questionText": "Où les élèves vont-ils emprunter des romans et faire des recherches documentaires silencieuses ?",
        "optionA": "À la cantine",
        "optionB": "À la bibliothèque",
        "optionC": "Dans les vestiaires",
        "optionD": "Sur le terrain de football",
        "correctOption": "B",
        "subConcept": "Lieux de l'Établissement",
        "explanation": "La bibliothèque scolaire est le lieu dédié à la lecture, à la recherche et à l'emprunt d'ouvrages.",
        "remediationTip": "Library = bibliothèque (Attention : 'librairie' est une boutique où l'on achète des livres !)."
      },
      {
        "id": "jhs3-fre-t4-q8",
        "quizId": "quiz-jhs3-fre-t4-ecole-education-avenir",
        "questionText": "Quel est le féminin de la profession 'infirmier' ?",
        "optionA": "infirmière",
        "optionB": "infirmiere",
        "optionC": "infirmièresse",
        "optionD": "infirmienne",
        "correctOption": "A",
        "subConcept": "Féminin des Métiers en -ier",
        "explanation": "Les métiers terminés par -ier font leur féminin en -ière avec un accent grave sur le 'e' (infirmier -> infirmière, cuisinier -> cuisinière).",
        "remediationTip": "-ier au masculin devient -ière au féminin."
      },
      {
        "id": "jhs3-fre-t4-q9",
        "quizId": "quiz-jhs3-fre-t4-ecole-education-avenir",
        "questionText": "À quelle heure la sonnerie retentit-elle pour la pause de récréation (10h30) ?",
        "optionA": "À dix heures moins le quart",
        "optionB": "À dix heures et demie",
        "optionC": "À onze heures pile",
        "optionD": "À neuf heures et quart",
        "correctOption": "B",
        "subConcept": "L'Heure et les Activités Scolaires",
        "explanation": "10h30 s'exprime en français par 'dix heures et demie' (ou dix heures trente).",
        "remediationTip": "10h30 = dix heures et demie ; 10h15 = dix heures et quart."
      },
      {
        "id": "jhs3-fre-t4-q10",
        "quizId": "quiz-jhs3-fre-t4-ecole-education-avenir",
        "questionText": "Que signifie l'expression d'ambition : 'Mon rêve est de devenir ingénieur agronome' ?",
        "optionA": "Je déteste l'agriculture moderne.",
        "optionB": "Mon ambition est de concevoir des solutions agricoles scientifiques pour nourrir le pays.",
        "optionC": "Je veux vendre des engrais sur le marché.",
        "optionD": "Je dors pendant les cours de sciences.",
        "correctOption": "B",
        "subConcept": "Ambitions de Carrières",
        "explanation": "L'ingénieur agronome applique les sciences et la technologie pour développer l'agriculture et la sécurité alimentaire.",
        "remediationTip": "Agronome = expert en sciences de l'agriculture."
      }
    ]
  },
  "jhs3-fre-t5-maison-environnement-ville": {
    "id": "quiz-jhs3-fre-t5-maison-environnement-ville",
    "topicId": "jhs3-fre-t5-maison-environnement-ville",
    "title": "La Maison, les Pièces, le Quartier et la Protection de l'Environnement BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t5-q1",
        "quizId": "quiz-jhs3-fre-t5-maison-environnement-ville",
        "questionText": "Complétez avec la préposition contractée exacte : 'Le supermarché se trouve juste à côté ______ grand marché.'",
        "optionA": "de la",
        "optionB": "du",
        "optionC": "des",
        "optionD": "de le",
        "correctOption": "B",
        "subConcept": "Prépositions de Lieu Contractées",
        "explanation": "'Marché' est masculin singulier (le marché). De + le = DU : 'à côté du grand marché'.",
        "remediationTip": "De + le = du ; De + les = des."
      },
      {
        "id": "jhs3-fre-t5-q2",
        "quizId": "quiz-jhs3-fre-t5-maison-environnement-ville",
        "questionText": "Dans quelle pièce de la maison prépare-t-on les repas quotidiens ?",
        "optionA": "La salle de bains",
        "optionB": "La cuisine",
        "optionC": "Le salon",
        "optionD": "La chambre à coucher",
        "correctOption": "B",
        "subConcept": "Pièces de la Maison",
        "explanation": "La cuisine est la pièce où les repas sont préparés et cuisinés.",
        "remediationTip": "Kitchen = la cuisine ; Living room = le salon."
      },
      {
        "id": "jhs3-fre-t5-q3",
        "quizId": "quiz-jhs3-fre-t5-maison-environnement-ville",
        "questionText": "Comment dit-on en français : 'Turn left at the traffic light' ?",
        "optionA": "Allez tout droit vers les feux.",
        "optionB": "Tournez à gauche au feu tricolore.",
        "optionC": "Tournez à droite après la route.",
        "optionD": "Traversez le carrefour sans regarder.",
        "correctOption": "B",
        "subConcept": "Donner un Itinéraire",
        "explanation": "'Turn left' = tournez à gauche ; 'traffic light' = le feu tricolore (ou feux de signalisation).",
        "remediationTip": "Gauche = left ; Droite = right ; Tout droit = straight ahead."
      },
      {
        "id": "jhs3-fre-t5-q4",
        "quizId": "quiz-jhs3-fre-t5-maison-environnement-ville",
        "questionText": "Quel terme français désigne l'orpaillage clandestin qui pollue les cours d'eau au Ghana ?",
        "optionA": "L'agriculture biologique",
        "optionB": "L'orpaillage illégal (ou galamsey)",
        "optionC": "La pêche artisanale",
        "optionD": "Le reboisement forestier",
        "correctOption": "B",
        "subConcept": "Enjeux Environnementaux Ghanéens",
        "explanation": "L'orpaillage illégal (communément appelé galamsey au Ghana) est l'extraction minière artisanale clandestine polluant les rivières au mercure.",
        "remediationTip": "Galamsey = l'orpaillage illégal / clandestin."
      },
      {
        "id": "jhs3-fre-t5-q5",
        "quizId": "quiz-jhs3-fre-t5-maison-environnement-ville",
        "questionText": "Complétez la règle écologique : 'Il faut toujours jeter les déchets plastiques dans ______.'",
        "optionA": "les caniveaux",
        "optionB": "la poubelle",
        "optionC": "les rivières",
        "optionD": "la rue",
        "correctOption": "B",
        "subConcept": "Civisme et Environnement",
        "explanation": "Pour préserver la propreté de l'école et de la ville, les ordures doivent être déposées dans la poubelle, évitant ainsi d'obstruer les caniveaux.",
        "remediationTip": "Dustbin = la poubelle ; Gutter = le caniveau."
      },
      {
        "id": "jhs3-fre-t5-q6",
        "quizId": "quiz-jhs3-fre-t5-maison-environnement-ville",
        "questionText": "Complétez avec la préposition convenable : 'Notre école est située en face ______ banques commerciales.'",
        "optionA": "de la",
        "optionB": "du",
        "optionC": "des",
        "optionD": "de les",
        "correctOption": "C",
        "subConcept": "Contraction avec Noms Pluriels",
        "explanation": "'Banques' est au pluriel. De + les = DES : 'en face des banques'.",
        "remediationTip": "En face de + les = en face des."
      },
      {
        "id": "jhs3-fre-t5-q7",
        "quizId": "quiz-jhs3-fre-t5-maison-environnement-ville",
        "questionText": "Quel meuble trouve-t-on habituellement dans le salon pour s'asseoir confortablement à plusieurs ?",
        "optionA": "Le lit",
        "optionB": "Le canapé (ou sofa)",
        "optionC": "La cuisinière",
        "optionD": "L'évier",
        "correctOption": "B",
        "subConcept": "Mobilier de la Maison",
        "explanation": "Le canapé (ou divan/sofa) est le meuble de salon conçu pour accueillir confortablement plusieurs personnes assises.",
        "remediationTip": "Canapé / fauteuil = sofa / armchair in the living room."
      },
      {
        "id": "jhs3-fre-t5-q8",
        "quizId": "quiz-jhs3-fre-t5-maison-environnement-ville",
        "questionText": "Quelle action citoyenne permet de lutter activement contre la déforestation au Ghana ?",
        "optionA": "Brûler les forêts pendant la saison sèche",
        "optionB": "Planter régulièrement des arbres (le reboisement)",
        "optionC": "Couper les arbres centenaires pour faire du charbon",
        "optionD": "Polluer les nappes phréatiques",
        "correctOption": "B",
        "subConcept": "Protection des Écosystèmes",
        "explanation": "Planter des arbres (reboisement) régénère la couverture forestière, freine l'érosion et protège le climat.",
        "remediationTip": "Reboisement / planter des arbres = tree planting."
      },
      {
        "id": "jhs3-fre-t5-q9",
        "quizId": "quiz-jhs3-fre-t5-maison-environnement-ville",
        "questionText": "Traduisez en français : 'The pharmacy is between the police station and the hospital.'",
        "optionA": "La pharmacie est derrière le commissariat.",
        "optionB": "La pharmacie est entre le commissariat de police et l'hôpital.",
        "optionC": "La pharmacie est loin de la police et de l'hôpital.",
        "optionD": "La pharmacie est sur l'hôpital et la police.",
        "correctOption": "B",
        "subConcept": "Préposition 'Entre'",
        "explanation": "'Between' se traduit par la préposition 'entre' reliant deux éléments de repère.",
        "remediationTip": "Between X and Y = Entre X et Y."
      },
      {
        "id": "jhs3-fre-t5-q10",
        "quizId": "quiz-jhs3-fre-t5-maison-environnement-ville",
        "questionText": "Pourquoi les caniveaux bouchés par des sachets d'eau provoquent-ils des inondations lors de la saison des pluies ?",
        "optionA": "L'eau de pluie s'évapore instantanément dans le ciel",
        "optionB": "L'eau pluviale ne peut plus circuler librement et refoule sur les chaussées et dans les habitations",
        "optionC": "Les caniveaux absorbent toute l'eau sous la terre",
        "optionD": "Les sachets en plastique purifient l'eau des rivières",
        "correctOption": "B",
        "subConcept": "Conséquences de la Pollution Urbaine",
        "explanation": "Les déchets non biodégradables bloquent l'écoulement des eaux de pluie dans les drains, provoquant de graves inondations dans les villes.",
        "remediationTip": "Les déchets bloquent l'écoulement de l'eau, provoquant des inondations."
      }
    ]
  },
  "jhs3-fre-t6-nourriture-cuisine-marche": {
    "id": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
    "topicId": "jhs3-fre-t6-nourriture-cuisine-marche",
    "title": "L'Alimentation, les Recettes Ghanéennes et les Achats BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t6-q1",
        "quizId": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
        "questionText": "Complétez la phrase affirmative : 'À midi, Kofi mange ______ riz au gras avec du poulet.'",
        "optionA": "de la",
        "optionB": "du",
        "optionC": "des",
        "optionD": "de l'",
        "correctOption": "B",
        "subConcept": "Articles Partitifs Affirmatifs",
        "explanation": "'Riz' est un nom masculin singulier (le riz). L'article partitif masculin est DU : 'manger du riz'.",
        "remediationTip": "Masculin = DU (du riz, du poisson, du pain)."
      },
      {
        "id": "jhs3-fre-t6-q2",
        "quizId": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
        "questionText": "Quelle est la règle de transformation des partitifs (du, de la, des) à la forme négative ?",
        "optionA": "Ils restent totalement inchangés.",
        "optionB": "Ils deviennent obligatoirement 'DE' ou 'D'' devant voyelle.",
        "optionC": "Ils sont remplacés par 'un' ou 'une'.",
        "optionD": "Ils sont supprimés sans rien mettre à la place.",
        "correctOption": "B",
        "subConcept": "Partitifs à la Forme Négative",
        "explanation": "À la forme négative avec 'ne... pas', DU, DE LA, DE L', DES se transforment toujours en 'de' ou 'd'' (ex: Je ne mange pas DE viande).",
        "remediationTip": "Négation = DE ou D' (Je ne bois pas de lait, je ne bois pas d'eau)."
      },
      {
        "id": "jhs3-fre-t6-q3",
        "quizId": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
        "questionText": "Mettez la phrase à la forme négative : 'Ama boit du thé le matin.'",
        "optionA": "Ama ne boit pas du thé le matin.",
        "optionB": "Ama ne boit pas de thé le matin.",
        "optionC": "Ama ne boit jamais du thé le matin.",
        "optionD": "Ama ne thé boit pas le matin.",
        "correctOption": "B",
        "subConcept": "Application de la Négation avec Partitif",
        "explanation": "'Du thé' devient 'de thé' sous l'action de la négation 'ne... pas' : 'Ama ne boit pas de thé'.",
        "remediationTip": "Ne... pas de thé (jamais 'pas du thé')."
      },
      {
        "id": "jhs3-fre-t6-q4",
        "quizId": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
        "questionText": "Comment traduit-on le plat ghanéen 'Jollof rice' en français ?",
        "optionA": "Le riz blanc bouilli",
        "optionB": "Le riz au gras (ou riz jollof)",
        "optionC": "Le gâteau de riz sucré",
        "optionD": "La soupe de riz froid",
        "correctOption": "B",
        "subConcept": "Plats Ghanéens en Français",
        "explanation": "En français d'Afrique de l'Ouest, le jollof rice est couramment appelé 'le riz au gras' ou 'le riz sénégalais/jollof'.",
        "remediationTip": "Jollof rice = le riz au gras."
      },
      {
        "id": "jhs3-fre-t6-q5",
        "quizId": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
        "questionText": "Quelle boisson matinale populaire au Ghana préparée à base de pâte de maïs fermentée correspond au 'koko' ?",
        "optionA": "Le café noir",
        "optionB": "La bouillie de maïs",
        "optionC": "Le jus de coco frais",
        "optionD": "Le vin de palme",
        "correctOption": "B",
        "subConcept": "Boissons et Repas du Matin",
        "explanation": "Le koko est une 'bouillie de maïs' épicée consommée au petit déjeuner avec du pain ou des beignets (koose).",
        "remediationTip": "Koko = la bouillie de maïs."
      },
      {
        "id": "jhs3-fre-t6-q6",
        "quizId": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
        "questionText": "Complétez avec le partitif convenable : 'Les élèves ont soif, ils demandent ______ eau fraîche.'",
        "optionA": "de la",
        "optionB": "du",
        "optionC": "de l'",
        "optionD": "des",
        "correctOption": "C",
        "subConcept": "Partitif devant Voyelle",
        "explanation": "'Eau' est un nom féminin commençant par une voyelle. On emploie donc 'de l'' pour l'élision sonore : 'de l'eau'.",
        "remediationTip": "Devant voyelle : de l'eau, de l'huile, de l'orangeade."
      },
      {
        "id": "jhs3-fre-t6-q7",
        "quizId": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
        "questionText": "Que demande un client poli au serveur dans un restaurant pour connaître la liste des plats et les prix ?",
        "optionA": "La facture d'électricité",
        "optionB": "La carte (ou le menu)",
        "optionC": "Le livre de classe",
        "optionD": "Le journal d'hier",
        "correctOption": "B",
        "subConcept": "Dialogue au Restaurant",
        "explanation": "Le client demande 'la carte' ou 'le menu' pour choisir son repas.",
        "remediationTip": "Menu / food list = la carte ou le menu."
      },
      {
        "id": "jhs3-fre-t6-q8",
        "quizId": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
        "questionText": "Comment un acheteur au marché de Makola demande-t-il poliment une réduction de prix à la marchande ?",
        "optionA": "C'est gratuit aujourd'hui ?",
        "optionB": "C'est trop cher ! Veuillez diminuer un peu le prix s'il vous plaît.",
        "optionC": "Je refuse de payer quoi que ce soit.",
        "optionD": "Donnez-moi vos marchandises sans argent.",
        "correctOption": "B",
        "subConcept": "Marchander au Marché",
        "explanation": "'Diminuer un peu le prix' est la formule usuelle pour négocier et marchander courtoisement sur les marchés francophones.",
        "remediationTip": "Négocier = 'Diminuez un peu le prix s'il vous plaît'."
      },
      {
        "id": "jhs3-fre-t6-q9",
        "quizId": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
        "questionText": "Complétez après l'expression de quantité : 'Maman a acheté un kilo ______ tomates au marché.'",
        "optionA": "des",
        "optionB": "de",
        "optionC": "du",
        "optionD": "de la",
        "correctOption": "B",
        "subConcept": "Expressions de Quantité",
        "explanation": "Après les expressions de quantité (un kilo, un litre, beaucoup, peu), on emploie toujours 'de' ou 'd'', JAMAIS 'des'.",
        "remediationTip": "Un kilo DE tomates, beaucoup DE bananes."
      },
      {
        "id": "jhs3-fre-t6-q10",
        "quizId": "quiz-jhs3-fre-t6-nourriture-cuisine-marche",
        "questionText": "Quelle formule emploie-t-on pour demander l'addition à la fin d'un repas au restaurant ?",
        "optionA": "L'addition, s'il vous plaît !",
        "optionB": "Où est la sortie de secours ?",
        "optionC": "Encore un repas s'il vous plaît !",
        "optionD": "Quel est votre prénom ?",
        "correctOption": "A",
        "subConcept": "Payer au Restaurant",
        "explanation": "L'addition (bill) est le document indiquant le montant à payer au restaurant.",
        "remediationTip": "The bill = l'addition s'il vous plaît."
      }
    ]
  },
  "jhs3-fre-t7-vetements-mode-achats": {
    "id": "quiz-jhs3-fre-t7-vetements-mode-achats",
    "topicId": "jhs3-fre-t7-vetements-mode-achats",
    "title": "Les Vêtements, la Mode Ghanéenne et les Démonstratifs BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t7-q1",
        "quizId": "quiz-jhs3-fre-t7-vetements-mode-achats",
        "questionText": "Complétez avec le démonstratif qui convient : '______ habit traditionnel coûte très cher.'",
        "optionA": "Ce",
        "optionB": "Cet",
        "optionC": "Cette",
        "optionD": "Ces",
        "correctOption": "B",
        "subConcept": "Adjectif Démonstratif CET devant H muet",
        "explanation": "'Habit' est un nom masculin singulier commençant par un h muet. L'adjectif démonstratif masculin devant voyelle ou h muet est CET : 'Cet habit'.",
        "remediationTip": "Masculin voyelle/h = CET ; Masculin consonne = CE."
      },
      {
        "id": "jhs3-fre-t7-q2",
        "quizId": "quiz-jhs3-fre-t7-vetements-mode-achats",
        "questionText": "Quel adjectif de couleur reste invariable en genre et en nombre en français ?",
        "optionA": "Bleu",
        "optionB": "Blanc",
        "optionC": "Marron",
        "optionD": "Noir",
        "correctOption": "C",
        "subConcept": "Invariabilité des Couleurs",
        "explanation": "'Marron' et 'orange' sont des noms employés comme adjectifs de couleur et restent strictement invariables (ex: des robes marron, des jupes orange).",
        "remediationTip": "Marron et orange ne prennent JAMAIS de 's' ni de 'e'."
      },
      {
        "id": "jhs3-fre-t7-q3",
        "quizId": "quiz-jhs3-fre-t7-vetements-mode-achats",
        "questionText": "Comment appelle-t-on le tissu royal ghanéen tissé à la main porté lors des grandes célébrations ?",
        "optionA": "Le denim",
        "optionB": "Le kente",
        "optionC": "Le polyester",
        "optionD": "Le velours",
        "correctOption": "B",
        "subConcept": "Textiles Traditionnels Ghanéens",
        "explanation": "Le kente est le prestigieux tissu traditionnel ghanéen tissé par les artisans d'Ashanti et de la Volta.",
        "remediationTip": "Kente = tissu traditionnel ghanéen tissé."
      },
      {
        "id": "jhs3-fre-t7-q4",
        "quizId": "quiz-jhs3-fre-t7-vetements-mode-achats",
        "questionText": "Complétez la phrase : 'Kofi essaie ______ chaussures noires dans la boutique.'",
        "optionA": "ce",
        "optionB": "cette",
        "optionC": "ces",
        "optionD": "cet",
        "correctOption": "C",
        "subConcept": "Démonstratif au Pluriel",
        "explanation": "'Chaussures' est un nom au pluriel. Le démonstratif pluriel pour le masculin et le féminin est CES : 'ces chaussures'.",
        "remediationTip": "Pluriel = CES (ces chaussures, ces pantalons)."
      },
      {
        "id": "jhs3-fre-t7-q5",
        "quizId": "quiz-jhs3-fre-t7-vetements-mode-achats",
        "questionText": "Quelle question pose-t-on à un client pour connaître la pointure de ses chaussures ?",
        "optionA": "Quelle est votre couleur préférée ?",
        "optionB": "Quelle est votre pointure ?",
        "optionC": "Combien pèse votre pied ?",
        "optionD": "Quelle est votre taille de chemise ?",
        "correctOption": "B",
        "subConcept": "Pointure vs Taille",
        "explanation": "Pour les chaussures, la mesure s'appelle la 'pointure' ; pour les vêtements (pantalons, robes), on parle de 'taille'.",
        "remediationTip": "Chaussures = pointure ; Vêtements = taille."
      },
      {
        "id": "jhs3-fre-t7-q6",
        "quizId": "quiz-jhs3-fre-t7-vetements-mode-achats",
        "questionText": "Accordez correctement l'adjectif de couleur : 'Ama porte une jolie chemise ______.'",
        "optionA": "blanc",
        "optionB": "blanche",
        "optionC": "blanches",
        "optionD": "blancs",
        "correctOption": "B",
        "subConcept": "Accord des Couleurs au Féminin",
        "explanation": "'Chemise' est féminin singulier. L'adjectif 'blanc' fait son féminin régulier en 'blanche'.",
        "remediationTip": "Blanc (masculin) -> Blanche (féminin)."
      },
      {
        "id": "jhs3-fre-t7-q7",
        "quizId": "quiz-jhs3-fre-t7-vetements-mode-achats",
        "questionText": "Complétez avec le démonstratif convenable : '______ jeune fille porte une belle robe kente.'",
        "optionA": "Ce",
        "optionB": "Cet",
        "optionC": "Cette",
        "optionD": "Ces",
        "correctOption": "C",
        "subConcept": "Démonstratif Féminin Singulier",
        "explanation": "'Fille' est féminin singulier. L'adjectif démonstratif féminin est CETTE : 'Cette jeune fille'.",
        "remediationTip": "Féminin singulier = CETTE."
      },
      {
        "id": "jhs3-fre-t7-q8",
        "quizId": "quiz-jhs3-fre-t7-vetements-mode-achats",
        "questionText": "Où va un client dans un magasin de vêtements pour essayer un pantalon en toute intimité ?",
        "optionA": "À la caisse",
        "optionB": "Dans la cabine d'essayage",
        "optionC": "Dans la vitrine",
        "optionD": "Sur le comptoir",
        "correctOption": "B",
        "subConcept": "Magasin de Mode",
        "explanation": "La cabine d'essayage (fitting room) est l'espace réservé aux clients pour essayer les habits avant achat.",
        "remediationTip": "Fitting room = la cabine d'essayage."
      },
      {
        "id": "jhs3-fre-t7-q9",
        "quizId": "quiz-jhs3-fre-t7-vetements-mode-achats",
        "questionText": "Traduisez en français : 'This leather belt is very strong.'",
        "optionA": "Ce ceinture en fer est forte.",
        "optionB": "Cette ceinture en cuir est très solide.",
        "optionC": "Cet ceinture de plastique est fragile.",
        "optionD": "Ces ceintures sont dures.",
        "correctOption": "B",
        "subConcept": "Matière et Démonstratif",
        "explanation": "'Ceinture' est féminin (cette ceinture) ; 'leather' se traduit par 'en cuir' ; 'strong' par 'solide'.",
        "remediationTip": "Cuir = leather ; Cette ceinture en cuir."
      },
      {
        "id": "jhs3-fre-t7-q10",
        "quizId": "quiz-jhs3-fre-t7-vetements-mode-achats",
        "questionText": "Quel vêtement traditionnel ample et brodé est particulièrement porté par les hommes dans les régions du Nord du Ghana ?",
        "optionA": "Le maillot de bain",
        "optionB": "Le batakari (ou fugu)",
        "optionC": "Le kilt écossais",
        "optionD": "La salopette",
        "correctOption": "B",
        "subConcept": "Vêtements Traditionnels du Ghana",
        "explanation": "Le batakari (ou fugu) est la tunique traditionnelle en coton lourd rayé originaire des régions septentrionales du Ghana.",
        "remediationTip": "Batakari / Fugu = tenue traditionnelle du Nord du Ghana."
      }
    ]
  },
  "jhs3-fre-t8-voyages-transports-tourisme": {
    "id": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
    "topicId": "jhs3-fre-t8-voyages-transports-tourisme",
    "title": "Les Voyages, les Moyens de Transport et le Tourisme BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t8-q1",
        "quizId": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
        "questionText": "Quelle préposition doit-on utiliser pour un voyageur se déplaçant à l'intérieur d'un autobus ?",
        "optionA": "à",
        "optionB": "en",
        "optionC": "par",
        "optionD": "sur",
        "correctOption": "B",
        "subConcept": "Prépositions des Véhicules Fermés",
        "explanation": "Pour tous les moyens de transport fermés dans lesquels on pénètre, on emploie la préposition EN : en bus, en car, en train, en voiture, en avion.",
        "remediationTip": "EN bus, EN car, EN taxi, EN avion."
      },
      {
        "id": "jhs3-fre-t8-q2",
        "quizId": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
        "questionText": "Complétez la phrase par la préposition correcte : 'Tous les matins, les élèves vont au collège ______ pied.'",
        "optionA": "en",
        "optionB": "à",
        "optionC": "dans",
        "optionD": "avec",
        "correctOption": "B",
        "subConcept": "Préposition pour la Marche",
        "explanation": "On dit toujours 'À pied', car la marche s'effectue sur ses propres jambes sans véhicule fermé.",
        "remediationTip": "À pied (jamais 'en pied')."
      },
      {
        "id": "jhs3-fre-t8-q3",
        "quizId": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
        "questionText": "Quel site touristique mondialement célèbre situé près de Cape Coast est connu pour sa passerelle suspendue au-dessus de la canopée ?",
        "optionA": "Le lac Bosomtwe",
        "optionB": "Le parc national de Kakum",
        "optionC": "La place de l'Étoile Noire",
        "optionD": "Le barrage d'Akosombo",
        "correctOption": "B",
        "subConcept": "Patrimoine Touristique du Ghana",
        "explanation": "Le parc national de Kakum est réputé pour sa spectaculaire passerelle suspendue dans les arbres (canopy walkway).",
        "remediationTip": "Parc de Kakum = passerelle suspendue dans la forêt tropicale."
      },
      {
        "id": "jhs3-fre-t8-q4",
        "quizId": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
        "questionText": "Comment appelle-t-on le minibus de transport en commun populaire au Ghana en français ?",
        "optionA": "Le ferryboat",
        "optionB": "Le trotro",
        "optionC": "Le téléphérique",
        "optionD": "La calèche",
        "correctOption": "B",
        "subConcept": "Transports Urbains Ghanéens",
        "explanation": "Le 'trotro' est le terme désignant le minibus de transport en commun dans le contexte ghanéen.",
        "remediationTip": "Trotro = minibus de transport local."
      },
      {
        "id": "jhs3-fre-t8-q5",
        "quizId": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
        "questionText": "Où achète-t-on son ticket avant de monter dans le car interurbain à la gare routière ?",
        "optionA": "Au guichet de vente des billets",
        "optionB": "Chez le mécanicien",
        "optionC": "Au restaurant du coin",
        "optionD": "À la pharmacie",
        "correctOption": "A",
        "subConcept": "Vocabulaire de la Gare Routière",
        "explanation": "Les billets se prennent au guichet de la gare routière auprès du billeteur ou guichetier.",
        "remediationTip": "Ticket counter = le guichet."
      },
      {
        "id": "jhs3-fre-t8-q6",
        "quizId": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
        "questionText": "Complétez la phrase : 'Koffi aime rouler ______ bicyclette le week-end.'",
        "optionA": "en",
        "optionB": "à",
        "optionC": "vers",
        "optionD": "par",
        "correctOption": "B",
        "subConcept": "Préposition des Deux-Roues",
        "explanation": "Pour les deux-roues que l'on enfourche (vélo, bicyclette, moto), on emploie la préposition À : 'à bicyclette', 'à moto'.",
        "remediationTip": "À vélo, À moto, À bicyclette."
      },
      {
        "id": "jhs3-fre-t8-q7",
        "quizId": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
        "questionText": "Quel fort historique côtier au Ghana a été construit par les Portugais en 1482 et figure au patrimoine mondial de l'UNESCO ?",
        "optionA": "Le Fort Saint-Georges d'Elmina",
        "optionB": "Le Fort Kumasi",
        "optionC": "Le Fort Good Hope",
        "optionD": "Le Fort Rattray",
        "correctOption": "A",
        "subConcept": "Monuments Historiques du Ghana",
        "explanation": "Le château / fort Saint-Georges d'Elmina a été érigé par les navigateurs portugais en 1482 et rappelle la mémoire historique de la côte de l'or.",
        "remediationTip": "Fort d'Elmina = érigé en 1482 sur la côte ghanéenne."
      },
      {
        "id": "jhs3-fre-t8-q8",
        "quizId": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
        "questionText": "Comment dit-on en français : 'The plane lands at Kotoka International Airport' ?",
        "optionA": "L'avion décolle de la piste.",
        "optionB": "L'avion atterrit à l'Aéroport International de Kotoka.",
        "optionC": "L'avion vole au-dessus du port.",
        "optionD": "L'avion navigue sur le lac.",
        "correctOption": "B",
        "subConcept": "Vocabulaire Aéronautique",
        "explanation": "'Lands' = atterrit (du verbe atterrir). L'action inverse est 'décoller' (take off).",
        "remediationTip": "Atterrir = to land ; Décoller = to take off."
      },
      {
        "id": "jhs3-fre-t8-q9",
        "quizId": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
        "questionText": "Quelle question pose-t-on pour connaître le tarif d'un déplacement à la gare routière ?",
        "optionA": "Qui conduit le bus ?",
        "optionB": "Combien coûte le trajet jusqu'à Kumasi ?",
        "optionC": "Où sont les toilettes publiques ?",
        "optionD": "Quel temps fera-t-il demain ?",
        "correctOption": "B",
        "subConcept": "Renseignements de Voyage",
        "explanation": "'Combien coûte le trajet... ?' est la formulation standard pour s'enquérir du prix d'un voyage.",
        "remediationTip": "Demander le prix d'un voyage = 'Combien coûte le trajet ?'."
      },
      {
        "id": "jhs3-fre-t8-q10",
        "quizId": "quiz-jhs3-fre-t8-voyages-transports-tourisme",
        "questionText": "Quel parc animalier du Nord du Ghana permet d'observer des troupeaux d'éléphants sauvages en milieu naturel ?",
        "optionA": "Le zoo de Kumasi",
        "optionB": "Le parc national de Mole",
        "optionC": "La forêt d'Achimota",
        "optionD": "Le jardin botanique d'Aburi",
        "correctOption": "B",
        "subConcept": "Tourisme Écologique au Ghana",
        "explanation": "Le parc national de Mole, situé dans la région des Savanes près de Damongo, est la plus grande réserve faunique du Ghana réputée pour ses éléphants.",
        "remediationTip": "Parc de Mole = safari et éléphants sauvages dans le Nord du Ghana."
      }
    ]
  },
  "jhs3-fre-t9-temps-meteo-saisons": {
    "id": "quiz-jhs3-fre-t9-temps-meteo-saisons",
    "topicId": "jhs3-fre-t9-temps-meteo-saisons",
    "title": "Le Temps Quotidien, la Météo et les Saisons BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t9-q1",
        "quizId": "quiz-jhs3-fre-t9-temps-meteo-saisons",
        "questionText": "Quelle tournure impersonnelle s'emploie pour décrire une météo ensoleillée en français ?",
        "optionA": "Le soleil est chaud.",
        "optionB": "Il fait du soleil (ou il fait beau).",
        "optionC": "Le ciel a du feu.",
        "optionD": "Il est beaucoup de lumière.",
        "correctOption": "B",
        "subConcept": "Structures Impersonnelles Météo",
        "explanation": "Les expressions météorologiques emploient 'IL FAIT' + adjectif/nom partitif : 'Il fait beau', 'Il fait du soleil'.",
        "remediationTip": "Il fait beau / Il fait du soleil (jamais 'le temps est beau')."
      },
      {
        "id": "jhs3-fre-t9-q2",
        "quizId": "quiz-jhs3-fre-t9-temps-meteo-saisons",
        "questionText": "Distinguez l'état météorologique de la sensation corporelle : 'En plein soleil, ______ très chaud, alors ______ soif.'",
        "optionA": "j'ai ; il fait",
        "optionB": "il fait ; j'ai",
        "optionC": "il est ; je suis",
        "optionD": "je fais ; il a",
        "correctOption": "B",
        "subConcept": "Il fait chaud vs J'ai chaud/soif",
        "explanation": "La météo extérieure utilise 'Il fait' (il fait très chaud) ; la sensation corporelle utilise le verbe avoir (j'ai soif).",
        "remediationTip": "Météo = Il fait chaud ; Sensation de la personne = J'ai chaud / J'ai soif."
      },
      {
        "id": "jhs3-fre-t9-q3",
        "quizId": "quiz-jhs3-fre-t9-temps-meteo-saisons",
        "questionText": "Quelle période climatique caractérisée par un vent sec et poussiéreux souffle sur le Ghana entre décembre et février ?",
        "optionA": "La mousson marine",
        "optionB": "L'harmattan",
        "optionC": "La saison des neiges",
        "optionD": "Le typhon",
        "correctOption": "B",
        "subConcept": "Saisons Tropicales : Harmattan",
        "explanation": "L'harmattan est l'alizé continental sec et poussiéreux soufflant du désert du Sahara sur l'Afrique de l'Ouest de décembre à février.",
        "remediationTip": "Harmattan = vent sec et poussiéreux du Sahara (décembre-février)."
      },
      {
        "id": "jhs3-fre-t9-q4",
        "quizId": "quiz-jhs3-fre-t9-temps-meteo-saisons",
        "questionText": "Complétez par le verbe météorologique au présent : 'Prends ton parapluie parce qu'______ des cordes dehors !'",
        "optionA": "il pleut",
        "optionB": "il pluit",
        "optionC": "il pleuvoir",
        "optionD": "il a plu",
        "correctOption": "A",
        "subConcept": "Conjugaison du Verbe Pleuvoir",
        "explanation": "Le verbe impersonnel pleuvoir se conjugue à la 3e personne du singulier au présent : 'il pleut'. 'Il pleut des cordes' signifie qu'il pleut abondamment.",
        "remediationTip": "Verbe pleuvoir au présent = Il pleut."
      },
      {
        "id": "jhs3-fre-t9-q5",
        "quizId": "quiz-jhs3-fre-t9-temps-meteo-saisons",
        "questionText": "Que porte un élève prudent pour se protéger de la pluie torrentielle en rentrant de l'école ?",
        "optionA": "Un maillot de bain",
        "optionB": "Un imperméable (ou k-way)",
        "optionC": "Des lunettes de soleil",
        "optionD": "Des sandales à lanières fines",
        "correctOption": "B",
        "subConcept": "Vêtements Adaptés à la Pluie",
        "explanation": "L'imperméable est le vêtement étanche imperméable à l'eau qui protège le corps de la pluie.",
        "remediationTip": "Raincoat = un imperméable."
      },
      {
        "id": "jhs3-fre-t9-q6",
        "quizId": "quiz-jhs3-fre-t9-temps-meteo-saisons",
        "questionText": "Comment dit-on en français : 'The sky is overcast and cloudy' ?",
        "optionA": "Le ciel est bleu et étincelant.",
        "optionB": "Le ciel est couvert et nuageux.",
        "optionC": "Le ciel est ensoleillé.",
        "optionD": "Le ciel n'existe pas.",
        "correctOption": "B",
        "subConcept": "Description du Ciel",
        "explanation": "Overcast = couvert ; cloudy = nuageux. 'Le ciel est couvert et nuageux'.",
        "remediationTip": "Nuageux = cloudy ; Couvert = overcast."
      },
      {
        "id": "jhs3-fre-t9-q7",
        "quizId": "quiz-jhs3-fre-t9-temps-meteo-saisons",
        "questionText": "Quelle activité de plein air les jeunes ghanéens pratiquent-ils volontiers quand il fait un beau soleil le samedi après-midi ?",
        "optionA": "Dormir avec deux couvertures",
        "optionB": "Jouer au football ou aller à la plage",
        "optionC": "Regarder la pluie tomber par la fenêtre",
        "optionD": "Allumer un feu dans la chambre",
        "correctOption": "B",
        "subConcept": "Loisirs selon la Météo",
        "explanation": "Par beau temps, les activités récréatives de plein air (football, baignade à la plage de Labadi ou Kokrobite) sont privilégiées.",
        "remediationTip": "Beau temps -> activités extérieures (football, plage, pique-nique)."
      },
      {
        "id": "jhs3-fre-t9-q8",
        "quizId": "quiz-jhs3-fre-t9-temps-meteo-saisons",
        "questionText": "Complétez la phrase météorologique : 'Pendant l'orage violent, il y a eu des éclairs et ______.'",
        "optionA": "du tonnerre",
        "optionB": "du sel",
        "optionC": "de la neige",
        "optionD": "du soleil éclatant",
        "correctOption": "A",
        "subConcept": "Phénomènes Orageux",
        "explanation": "L'orage s'accompagne d'éclairs (lightning) et de tonnerre (thunder). En français : 'des éclairs et du tonnerre'.",
        "remediationTip": "Éclairs = lightning ; Tonnerre = thunder."
      },
      {
        "id": "jhs3-fre-t9-q9",
        "quizId": "quiz-jhs3-fre-t9-temps-meteo-saisons",
        "questionText": "Quel soin traditionnel au beurre de karité est particulièrement recommandé pendant l'harmattan au Ghana ?",
        "optionA": "S'enduire le corps pour hydrater la peau sèche et les lèvres",
        "optionB": "Boire le pot de beurre fondu au déjeuner",
        "optionC": "Frotter ses cahiers de classe",
        "optionD": "Laver son uniforme scolaire avec",
        "correctOption": "A",
        "subConcept": "Pratiques Locales de l'Harmattan",
        "explanation": "Le beurre de karité (shea butter) protège la peau et les lèvres contre le dessèchement extrême causé par le vent de l'harmattan.",
        "remediationTip": "Le beurre de karité hydrate la peau contre le vent sec de l'harmattan."
      },
      {
        "id": "jhs3-fre-t9-q10",
        "quizId": "quiz-jhs3-fre-t9-temps-meteo-saisons",
        "questionText": "Quelle phrase météorologique annonce une météo fraîche et agréable le matin sur les plateaux d'Aburi ?",
        "optionA": "Il fait un froid polaire avec de la glace.",
        "optionB": "Il fait frais et le vent est doux.",
        "optionC": "Le feu brûle les montagnes.",
        "optionD": "Il pleut des pierres sur les routes.",
        "correctOption": "B",
        "subConcept": "Expression de la Fraîcheur",
        "explanation": "'Il fait frais' décrit une température douce, vivifiante et agréable, typique des collines boisées d'Aburi le matin.",
        "remediationTip": "Cool/chilly = il fait frais."
      }
    ]
  },
  "jhs3-fre-t10-temps-verbaux-passe-compose-imparfait": {
    "id": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
    "topicId": "jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
    "title": "Passé Composé et Imparfait dans la Narration BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t10-q1",
        "quizId": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
        "questionText": "Accordez correctement le participe passé avec l'auxiliaire ÊTRE : 'Hier soir, les filles sont ______ à l'heure.'",
        "optionA": "arrivé",
        "optionB": "arrivée",
        "optionC": "arrivés",
        "optionD": "arrivées",
        "correctOption": "D",
        "subConcept": "Accord du Participe Passé avec ÊTRE",
        "explanation": "Avec l'auxiliaire ÊTRE, le participe passé s'accorde avec le sujet. 'Les filles' étant féminin pluriel, on ajoute 'es' : 'arrivées'.",
        "remediationTip": "Féminin pluriel avec ÊTRE -> terminaison -ées (arrivées, parties, revenues)."
      },
      {
        "id": "jhs3-fre-t10-q2",
        "quizId": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
        "questionText": "Quel auxiliaire doit-on employer pour conjuguer le verbe de mouvement 'partir' au passé composé ?",
        "optionA": "Avoir (J'ai parti)",
        "optionB": "Être (Je suis parti)",
        "optionC": "Faire (Je fais parti)",
        "optionD": "Aller (Je vais parti)",
        "correctOption": "B",
        "subConcept": "Auxiliaire des Verbes de Mouvement",
        "explanation": "Le verbe 'partir' fait partie des 16 verbes de déplacement intransitifs qui se conjuguent impérativement avec l'auxiliaire ÊTRE.",
        "remediationTip": "Partir se conjugue avec Être : Je suis parti(e)."
      },
      {
        "id": "jhs3-fre-t10-q3",
        "quizId": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
        "questionText": "Quelles sont les terminaisons universelles de l'Imparfait de l'indicatif pour tous les verbes français ?",
        "optionA": "-ai, -as, -a, -ons, -ez, -ont",
        "optionB": "-ais, -ais, -ait, -ions, -iez, -aient",
        "optionC": "-e, -es, -e, -ons, -ez, -ent",
        "optionD": "-is, -is, -it, -issons, -issez, -issent",
        "correctOption": "B",
        "subConcept": "Terminaisons de l'Imparfait",
        "explanation": "Les terminaisons de l'imparfait sont invariablement les mêmes pour tous les groupes : -ais, -ais, -ait, -ions, -iez, -aient.",
        "remediationTip": "Imparfait : -ais, -ais, -ait, -ions, -iez, -aient."
      },
      {
        "id": "jhs3-fre-t10-q4",
        "quizId": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
        "questionText": "Complétez la phrase narrative : 'Pendant que les enfants (jouer) ______ dans la cour, un orage a éclaté.'",
        "optionA": "ont joué",
        "optionB": "jouaient",
        "optionC": "joueront",
        "optionD": "jouent",
        "correctOption": "B",
        "subConcept": "Action Continue avec Pendant Que",
        "explanation": "'Pendant que' introduit une action continue d'arrière-plan dans le passé qui s'exprime à l'Imparfait : 'jouaient'.",
        "remediationTip": "Pendant que + Imparfait pour exprimer l'action en cours."
      },
      {
        "id": "jhs3-fre-t10-q5",
        "quizId": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
        "questionText": "Quel temps verbal marque l'action soudaine et ponctuelle qui interrompt le décor dans une narration ?",
        "optionA": "Le Présent",
        "optionB": "Le Passé Composé",
        "optionC": "L'Imparfait",
        "optionD": "Le Plus-que-parfait",
        "correctOption": "B",
        "subConcept": "Rôle Narratif du Passé Composé",
        "explanation": "Le passé composé exprime l'action ponctuelle, achevée et soudaine (foreground action) qui fait progresser l'histoire.",
        "remediationTip": "Passé composé = événement soudain ; Imparfait = arrière-plan continu."
      },
      {
        "id": "jhs3-fre-t10-q6",
        "quizId": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
        "questionText": "Quel est le participe passé irrégulier du verbe 'prendre' au passé composé ?",
        "optionA": "prendu",
        "optionB": "pris",
        "optionC": "prené",
        "optionD": "prisé",
        "correctOption": "B",
        "subConcept": "Participes Passés Irréguliers",
        "explanation": "Le verbe prendre a pour participe passé irrégulier 'pris' : J'ai pris, tu as pris, il a pris.",
        "remediationTip": "Prendre -> pris ; Comprendre -> compris ; Apprendre -> appris."
      },
      {
        "id": "jhs3-fre-t10-q7",
        "quizId": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
        "questionText": "Mettez le verbe être à l'imparfait : 'Quand nous (être) ______ jeunes, nous habitions à Takoradi.'",
        "optionA": "sommes",
        "optionB": "étions",
        "optionC": "avions",
        "optionD": "serons",
        "correctOption": "B",
        "subConcept": "Conjugaison d'Être à l'Imparfait",
        "explanation": "Le verbe être a pour radical unique à l'imparfait 'ét-'. Avec le sujet 'nous', cela donne 'nous étions'.",
        "remediationTip": "Être à l'imparfait : j'étais, tu étais, il était, nous étions, vous étiez, ils étaient."
      },
      {
        "id": "jhs3-fre-t10-q8",
        "quizId": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
        "questionText": "Quel connecteur temporel introduit presque toujours le Passé Composé en provoquant une rupture soudaine ?",
        "optionA": "D'habitude",
        "optionB": "Soudain (ou Tout à coup)",
        "optionC": "Autrefois",
        "optionD": "Tous les soirs",
        "correctOption": "B",
        "subConcept": "Marqueurs Temporels Narratifs",
        "explanation": "'Soudain' et 'tout à coup' annoncent une surprise ou un événement inattendu, appelant le Passé Composé.",
        "remediationTip": "Soudain / Tout à coup = Passé Composé."
      },
      {
        "id": "jhs3-fre-t10-q9",
        "quizId": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
        "questionText": "Accordez correctement : 'Mary et Akosua sont (descendre) ______ du trotro au carrefour.'",
        "optionA": "descendu",
        "optionB": "descendue",
        "optionC": "descendus",
        "optionD": "descendues",
        "correctOption": "D",
        "subConcept": "Accord avec Sujet Féminin Pluriel",
        "explanation": "Le sujet 'Mary et Akosua' est féminin pluriel (elles). Le verbe descendre utilisant Être, on ajoute 'es' : 'descendues'.",
        "remediationTip": "Elles sont descendues (féminin pluriel avec Être = -es)."
      },
      {
        "id": "jhs3-fre-t10-q10",
        "quizId": "quiz-jhs3-fre-t10-temps-verbaux-passe-compose-imparfait",
        "questionText": "Quelle phrase illustre une habitude répétée dans le passé nécessitant l'imparfait ?",
        "optionA": "Hier à 14 heures pile, le bus a klaxonné.",
        "optionB": "Chaque matin, mon grand-père se levait à cinq heures pour aller au champ.",
        "optionC": "Le voleur a sauté par-dessus le mur en une seconde.",
        "optionD": "Elle est partie sans rien dire.",
        "correctOption": "B",
        "subConcept": "Imparfait d'Habitude",
        "explanation": "'Chaque matin' indique la répétition et l'habitude passée, fonction première de l'Imparfait ('se levait').",
        "remediationTip": "Chaque jour / D'habitude = Imparfait d'habitude."
      }
    ]
  },
  "jhs3-fre-t11-futur-simple-conditionnel-souhaits": {
    "id": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
    "topicId": "jhs3-fre-t11-futur-simple-conditionnel-souhaits",
    "title": "Le Futur Simple et le Conditionnel BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t11-q1",
        "quizId": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
        "questionText": "Quel est le radical irrégulier du verbe 'ÊTRE' au futur simple ?",
        "optionA": "êt-",
        "optionB": "ser-",
        "optionC": "aur-",
        "optionD": "ét-",
        "correctOption": "B",
        "subConcept": "Radicaux Irréguliers du Futur",
        "explanation": "Au futur simple, le verbe ÊTRE adopte le radical 'ser-' : je serai, tu seras, il sera, nous serons, vous serez, ils seront.",
        "remediationTip": "Être au futur = ser- (Je serai) ; Avoir au futur = aur- (J'aurai)."
      },
      {
        "id": "jhs3-fre-t11-q2",
        "quizId": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
        "questionText": "Appliquez la règle conditionnelle avec 'SI' : 'Si Kofi (étudier) ______ sérieusement, il réussira au BECE.'",
        "optionA": "étudiera",
        "optionB": "étudie",
        "optionC": "étudiait",
        "optionD": "étudierait",
        "correctOption": "B",
        "subConcept": "Règle Si + Présent",
        "explanation": "Dans la subordonnée introduite par 'Si', le verbe se met obligatoirement au Présent de l'indicatif : 'Si Kofi étudie...'. Le futur dans la proposition avec 'si' est une faute majeure.",
        "remediationTip": "SI + PRÉSENT = FUTUR SIMPLE (Jamais de futur immédiatement après Si !)."
      },
      {
        "id": "jhs3-fre-t11-q3",
        "quizId": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
        "questionText": "Conjuguez le verbe 'AVOIR' au futur simple avec le sujet 'ils' :",
        "optionA": "ils avront",
        "optionB": "ils auront",
        "optionC": "ils avaient",
        "optionD": "ils aurons",
        "correctOption": "B",
        "subConcept": "Futur du Verbe Avoir",
        "explanation": "Le radical de avoir est 'aur-'. La terminaison pour 'ils' au futur est '-ont' : 'ils auront'.",
        "remediationTip": "Ils auront (avec -ont, car c'est la 3e personne du pluriel)."
      },
      {
        "id": "jhs3-fre-t11-q4",
        "quizId": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
        "questionText": "Quelle formule exprime poliment un souhait de carrière en utilisant le conditionnel présent ?",
        "optionA": "Je veux être médecin immédiatement !",
        "optionB": "J'aimerais devenir diplomate à l'avenir.",
        "optionC": "Je serai président que vous vouliez ou non.",
        "optionD": "Donnez-moi le poste d'avocat !",
        "correctOption": "B",
        "subConcept": "Conditionnel de Politesse",
        "explanation": "'J'aimerais' ou 'Je voudrais' adoucit l'expression de la volonté et formule une ambition avec élégance.",
        "remediationTip": "'J'aimerais' / 'Je voudrais' = I would like."
      },
      {
        "id": "jhs3-fre-t11-q5",
        "quizId": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
        "questionText": "Quel est le futur simple du verbe 'FAIRE' avec le sujet 'nous' ?",
        "optionA": "nous faisons",
        "optionB": "nous ferons",
        "optionC": "nous fairons",
        "optionD": "nous faisions",
        "correctOption": "B",
        "subConcept": "Futur du Verbe Faire",
        "explanation": "Le radical de faire au futur est 'fer-'. Avec 'nous', la forme correcte est 'nous ferons'.",
        "remediationTip": "Faire au futur simple : je ferai, tu feras, il fera, nous ferons."
      },
      {
        "id": "jhs3-fre-t11-q6",
        "quizId": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
        "questionText": "Complétez la phrase conditionnelle : 'Si nous avons de l'argent, nous (voyager) ______ en France.'",
        "optionA": "voyageons",
        "optionB": "voyagerons",
        "optionC": "voyagions",
        "optionD": "voyagerions",
        "correctOption": "B",
        "subConcept": "Conséquence au Futur Simple",
        "explanation": "La condition étant au présent ('avons'), la conséquence dans la proposition principale se conjugue au Futur Simple : 'nous voyagerons'.",
        "remediationTip": "Si + présent -> futur simple (nous voyagerons)."
      },
      {
        "id": "jhs3-fre-t11-q7",
        "quizId": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
        "questionText": "Quelle est la terminaison du futur simple pour le pronom 'je' ?",
        "optionA": "-ais",
        "optionB": "-ai",
        "optionC": "-e",
        "optionD": "-as",
        "correctOption": "B",
        "subConcept": "Terminaison de la 1ère Personne au Futur",
        "explanation": "Au futur simple, 'je' prend toujours la terminaison '-ai' sans 's' (ex: je parlerai, j'irai, je serai). Le '-ais' appartient au conditionnel.",
        "remediationTip": "Futur simple avec Je = -ai (Je parlerai) ; Conditionnel = -ais (Je parlerais)."
      },
      {
        "id": "jhs3-fre-t11-q8",
        "quizId": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
        "questionText": "Quel est le radical du verbe 'VENIR' au futur simple ?",
        "optionA": "ven-",
        "optionB": "viendr-",
        "optionC": "venir-",
        "optionD": "vondr-",
        "correctOption": "B",
        "subConcept": "Radical de Venir au Futur",
        "explanation": "Le verbe venir prend le radical irrégulier 'viendr-' au futur simple : je viendrai, tu viendras, ils viendront.",
        "remediationTip": "Venir au futur = viendr- (Je viendrai)."
      },
      {
        "id": "jhs3-fre-t11-q9",
        "quizId": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
        "questionText": "Dans un restaurant, comment commande-t-on un verre d'eau de façon très polie ?",
        "optionA": "Je veux un verre d'eau maintenant.",
        "optionB": "Je voudrais un verre d'eau, s'il vous plaît.",
        "optionC": "Apporte de l'eau rapidement.",
        "optionD": "Donne-moi l'eau.",
        "correctOption": "B",
        "subConcept": "Usage Pratique du Conditionnel",
        "explanation": "'Je voudrais' est la formule de politesse par excellence en français pour commander ou solliciter un service.",
        "remediationTip": "Commandes polies : 'Je voudrais...' + nom ou infinitif."
      },
      {
        "id": "jhs3-fre-t11-q10",
        "quizId": "quiz-jhs3-fre-t11-futur-simple-conditionnel-souhaits",
        "questionText": "Conjuguez au futur simple : 'L'année prochaine, vous (finir) ______ le collège.'",
        "optionA": "finissez",
        "optionB": "finirez",
        "optionC": "finiriez",
        "optionD": "finissons",
        "correctOption": "B",
        "subConcept": "Futur des Verbes en -IR",
        "explanation": "Pour les verbes réguliers en -ir comme finir, on garde l'infinitif complet et on ajoute la terminaison de vous (-ez) : 'vous finirez'.",
        "remediationTip": "Vous finirez (infinitif finir + ez)."
      }
    ]
  },
  "jhs3-fre-t12-production-ecrite-lettres-essais": {
    "id": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
    "topicId": "jhs3-fre-t12-production-ecrite-lettres-essais",
    "title": "Production Écrite BECE: La Lettre Amicale et la Rédaction BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-fre-t12-q1",
        "quizId": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
        "questionText": "Où doit-on placer le lieu et la date sur la feuille d'une lettre amicale en français ?",
        "optionA": "En bas à gauche de la page",
        "optionB": "En haut à droite de la page",
        "optionC": "Au milieu tout en bas",
        "optionD": "Sous la signature finale",
        "correctOption": "B",
        "subConcept": "Mise en Page de la Lettre Amicale",
        "explanation": "Le lieu d'expédition et la date s'écrivent toujours dans le coin supérieur droit (ex: 'Accra, le 15 juin 2026').",
        "remediationTip": "Lieu et date = En haut à droite."
      },
      {
        "id": "jhs3-fre-t12-q2",
        "quizId": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
        "questionText": "Quelle formule d'appel convient pour débuter une lettre adressée à un camarade garçon au BECE ?",
        "optionA": "Monsieur le Directeur,",
        "optionB": "Cher Kofi,",
        "optionC": "Chère Ama,",
        "optionD": "Madame l'Enseignante,",
        "correctOption": "B",
        "subConcept": "Formule d'Appel Amicale",
        "explanation": "Pour un garçon ami, on utilise 'Cher + Prénom' (Cher Kofi). Pour une fille amie, on écrit 'Chère + Prénom' (Chère Ama).",
        "remediationTip": "Garçon = Cher [Nom] ; Fille = Chère [Nom]."
      },
      {
        "id": "jhs3-fre-t12-q3",
        "quizId": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
        "questionText": "Comment doit-on signer une lettre amicale au BECE selon les directives officielles du WAEC ?",
        "optionA": "Avec son nom de famille complet et son numéro d'index",
        "optionB": "Avec son prénom uniquement (ex: Kwame)",
        "optionC": "Par une fausse signature en dessin",
        "optionD": "Avec le nom de son établissement scolaire",
        "correctOption": "B",
        "subConcept": "Signature de la Lettre Amicale",
        "explanation": "Dans une lettre amicale, on ne signe que par son prénom (ex: Kwame). Mentionner son nom complet ou son numéro de table est interdit.",
        "remediationTip": "Lettre amicale = signature par le prénom seul."
      },
      {
        "id": "jhs3-fre-t12-q4",
        "quizId": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
        "questionText": "Quel connecteur logique permet d'introduire le tout premier argument ou la première étape d'une narration ?",
        "optionA": "Enfin",
        "optionB": "Tout d'abord (ou D'abord)",
        "optionC": "Cependant",
        "optionD": "En conclusion",
        "correctOption": "B",
        "subConcept": "Connecteurs Logiques d'Ouverture",
        "explanation": "'D'abord' ou 'Tout d'abord' signale le début chronologique d'un récit ou d'une argumentation.",
        "remediationTip": "Première étape = D'abord / Tout d'abord."
      },
      {
        "id": "jhs3-fre-t12-q5",
        "quizId": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
        "questionText": "Quelle phrase d'introduction canonique permet de prendre des nouvelles de son correspondant dans une lettre ?",
        "optionA": "Donne-moi ton argent immédiatement.",
        "optionB": "Comment vas-tu ? J'espère que tu te portes bien ainsi que toute ta famille.",
        "optionC": "Je n'ai pas le temps de te parler aujourd'hui.",
        "optionD": "Pourquoi m'écris-tu cette lettre ?",
        "correctOption": "B",
        "subConcept": "Salutations Épistolaires",
        "explanation": "Prendre chaleureusement des nouvelles du destinataire et de ses proches est la politesse requise dans l'introduction d'une lettre amicale.",
        "remediationTip": "Introduction de lettre = salutations et vœux de santé."
      },
      {
        "id": "jhs3-fre-t12-q6",
        "quizId": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
        "questionText": "Quel connecteur logique marque une opposition ou un contraste entre deux idées ?",
        "optionA": "De plus",
        "optionB": "Mais (ou Cependant)",
        "optionC": "Premièrement",
        "optionD": "Ensuite",
        "correctOption": "B",
        "subConcept": "Connecteurs d'Opposition",
        "explanation": "'Mais' et 'cependant' indiquent une nuance, une réserve ou une opposition entre deux propositions.",
        "remediationTip": "Opposition = Mais / Cependant / Pourtant."
      },
      {
        "id": "jhs3-fre-t12-q7",
        "quizId": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
        "questionText": "Quelle formule de prise de congé chaleureuse termine couramment une lettre entre bons amis ?",
        "optionA": "Veuillez agréer mes salutations distinguées,",
        "optionB": "Ton ami dévoué (ou Amitiés),",
        "optionC": "C'est fini pour toujours,",
        "optionD": "À jamais étranger,",
        "correctOption": "B",
        "subConcept": "Formule de Clôture Amicale",
        "explanation": "'Ton ami dévoué', 'Amitiés' ou 'Affectueusement' sont les formules de prise de congé naturelles entre amis proches.",
        "remediationTip": "Conclusion amicale = 'Ton ami dévoué,' ou 'Amitiés,'."
      },
      {
        "id": "jhs3-fre-t12-q8",
        "quizId": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
        "questionText": "Pourquoi est-il capital d'aérer son devoir en plusieurs paragraphes distincts au BECE ?",
        "optionA": "Pour utiliser toute l'encre du stylo",
        "optionB": "Pour structurer clairement chaque idée principale et rendre la copie agréable et facile à noter pour le correcteur",
        "optionC": "Parce que les paragraphes sont interdits en anglais",
        "optionD": "Pour cacher les fautes de grammaire",
        "correctOption": "B",
        "subConcept": "Organisation et Paragraphes",
        "explanation": "Un texte aéré en paragraphes (introduction, développement, conclusion) démontre la maturité rédactionnelle du candidat et facilite la lecture.",
        "remediationTip": "Chaque paragraphe développe une idée distincte précédée d'un alinéa."
      },
      {
        "id": "jhs3-fre-t12-q9",
        "quizId": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
        "questionText": "Quel connecteur de conclusion annonce la fin d'un texte rédigé ?",
        "optionA": "D'abord",
        "optionB": "Enfin (ou En conclusion)",
        "optionC": "Par exemple",
        "optionD": "Pendant ce temps",
        "correctOption": "B",
        "subConcept": "Connecteurs de Conclusion",
        "explanation": "'Enfin', 'En conclusion' ou 'Finalement' annoncent le point final et la synthèse du développement.",
        "remediationTip": "Conclusion = Enfin / En conclusion / Finalement."
      },
      {
        "id": "jhs3-fre-t12-q10",
        "quizId": "quiz-jhs3-fre-t12-production-ecrite-lettres-essais",
        "questionText": "Que doit faire impérativement un candidat pendant les 5 dernières minutes de l'épreuve de rédaction ?",
        "optionA": "Poser son stylo et regarder ses voisins",
        "optionB": "Relire attentivement sa copie pour corriger les accords des adjectifs, des participes passés et la ponctuation",
        "optionC": "Effacer toute sa rédaction pour recommencer",
        "optionD": "Dessiner des fleurs sur sa feuille",
        "correctOption": "B",
        "subConcept": "Stratégie de Relecture au BECE",
        "explanation": "Une relecture minutieuse permet de traquer et corriger les fautes d'accord (féminin, pluriel) et les terminaisons verbales, sauvant plusieurs points décisifs.",
        "remediationTip": "Toujours relire sa copie pour corriger les accords de genre et de nombre !"
      }
    ]
  }
};
