// Ghanaian JHS 3 Mathematics Quizzes
// Based on NaCCA / GES Common Core Programme (CCP) Curriculum
// 14 Topics × 10 Questions = 140 BECE-Standard Questions

import { TopicQuiz } from './types';

export const JHS3_MATH_QUIZZES: Record<string, TopicQuiz> = {
  "jhs3-math-t1-real-numbers-surds": {
    "id": "quiz-jhs3-math-t1-real-numbers-surds",
    "topicId": "jhs3-math-t1-real-numbers-surds",
    "title": "Real Numbers, Standard Form, Indices & Surds BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs3math-t1-1",
        "quizId": "quiz-jhs3-math-t1-real-numbers-surds",
        "questionText": "Which of the following is an irrational number?",
        "optionA": "√49",
        "optionB": "0.333...",
        "optionC": "√12",
        "optionD": "-5/8",
        "correctOption": "C",
        "subConcept": "Rational vs Irrational Numbers",
        "explanation": "√12 = √(4 × 3) = 2√3, which has a non-terminating, non-recurring decimal expansion and cannot be written as a fraction of integers.",
        "remediationTip": "Square roots of non-perfect squares (like √2, √3, √12) are irrational numbers."
      },
      {
        "id": "q-jhs3math-t1-2",
        "quizId": "quiz-jhs3-math-t1-real-numbers-surds",
        "questionText": "Express 0.000405 in standard form.",
        "optionA": "4.05 × 10^-4",
        "optionB": "4.05 × 10^-3",
        "optionC": "40.5 × 10^-5",
        "optionD": "0.405 × 10^-3",
        "correctOption": "A",
        "subConcept": "Standard Form Scientific Notation",
        "explanation": "To express 0.000405 in standard form A × 10^n, move the decimal point 4 places to the right to place it between 4 and 0: 4.05 × 10^-4.",
        "remediationTip": "In standard form A × 10^n, the number A must satisfy 1 ≤ A < 10."
      },
      {
        "id": "q-jhs3math-t1-3",
        "quizId": "quiz-jhs3-math-t1-real-numbers-surds",
        "questionText": "Evaluate (2.4 × 10^7) ÷ (6.0 × 10^3), leaving your answer in standard form.",
        "optionA": "4.0 × 10^4",
        "optionB": "4.0 × 10^3",
        "optionC": "0.4 × 10^4",
        "optionD": "4.0 × 10^10",
        "correctOption": "B",
        "subConcept": "Operations in Standard Form",
        "explanation": "(2.4 / 6.0) × 10^(7 - 3) = 0.4 × 10^4. Converting to standard form (1 ≤ A < 10): 0.4 × 10^4 = (4.0 × 10^-1) × 10^4 = 4.0 × 10^3.",
        "remediationTip": "Remember to normalize 0.4 × 10^4 into valid standard form: 4.0 × 10^3."
      },
      {
        "id": "q-jhs3math-t1-4",
        "quizId": "quiz-jhs3-math-t1-real-numbers-surds",
        "questionText": "Evaluate 64^(-2/3).",
        "optionA": "-16",
        "optionB": "1/16",
        "optionC": "1/8",
        "optionD": "16",
        "correctOption": "B",
        "subConcept": "Negative Fractional Indices",
        "explanation": "64^(-2/3) = 1 / (64^(2/3)). The cube root of 64 is 4 (since 4³ = 64). Then square: 4² = 16. Thus, 1 / 16.",
        "remediationTip": "Negative power inverts the base; fractional power 2/3 means cube root first, then square."
      },
      {
        "id": "q-jhs3math-t1-5",
        "quizId": "quiz-jhs3-math-t1-real-numbers-surds",
        "questionText": "If 3^(2x - 1) = 81, find the value of x.",
        "optionA": "2",
        "optionB": "2.5",
        "optionC": "3",
        "optionD": "4",
        "correctOption": "B",
        "subConcept": "Exponential Equations",
        "explanation": "Express 81 in base 3: 81 = 3^4. Since bases are equal: 2x - 1 = 4  =>  2x = 5  =>  x = 5/2 = 2.5.",
        "remediationTip": "Express both sides with the same base, then equate the exponents."
      },
      {
        "id": "q-jhs3math-t1-6",
        "quizId": "quiz-jhs3-math-t1-real-numbers-surds",
        "questionText": "Simplify the surd √75 into the form a√b.",
        "optionA": "3√5",
        "optionB": "5√3",
        "optionC": "15√5",
        "optionD": "25√3",
        "correctOption": "B",
        "subConcept": "Simplifying Surds",
        "explanation": "Find the largest perfect square factor of 75, which is 25: √75 = √(25 × 3) = √25 × √3 = 5√3.",
        "remediationTip": "Factor out the largest perfect square (4, 9, 16, 25, 36, etc.) from under the square root sign."
      },
      {
        "id": "q-jhs3math-t1-7",
        "quizId": "quiz-jhs3-math-t1-real-numbers-surds",
        "questionText": "Simplify: √48 - √27 + √12.",
        "optionA": "3√3",
        "optionB": "5√3",
        "optionC": "√33",
        "optionD": "7√3",
        "correctOption": "A",
        "subConcept": "Addition and Subtraction of Surds",
        "explanation": "√48 = √(16 × 3) = 4√3; √27 = √(9 × 3) = 3√3; √12 = √(4 × 3) = 2√3. Combine: 4√3 - 3√3 + 2√3 = (4 - 3 + 2)√3 = 3√3.",
        "remediationTip": "Simplify each individual surd first before combining like surd terms."
      },
      {
        "id": "q-jhs3math-t1-8",
        "quizId": "quiz-jhs3-math-t1-real-numbers-surds",
        "questionText": "What is the value of (2a^3b^-2)^0 where a ≠ 0 and b ≠ 0?",
        "optionA": "0",
        "optionB": "1",
        "optionC": "2",
        "optionD": "2a^3",
        "correctOption": "B",
        "subConcept": "Zero Index Law",
        "explanation": "According to the Zero Index Law, any non-zero algebraic expression raised to the power of 0 equals 1.",
        "remediationTip": "Any quantity inside parentheses raised to power zero is 1: (anything)^0 = 1."
      },
      {
        "id": "q-jhs3math-t1-9",
        "quizId": "quiz-jhs3-math-t1-real-numbers-surds",
        "questionText": "Simplify: (x^5 × x^-2) / x^4.",
        "optionA": "x^-1",
        "optionB": "x^3",
        "optionC": "x^7",
        "optionD": "x^0",
        "correctOption": "A",
        "subConcept": "Laws of Indices",
        "explanation": "Numerator: x^(5 + (-2)) = x^3. Then divide: x^3 / x^4 = x^(3 - 4) = x^-1 (or 1/x).",
        "remediationTip": "Add exponents when multiplying like bases; subtract exponents when dividing."
      },
      {
        "id": "q-jhs3math-t1-10",
        "quizId": "quiz-jhs3-math-t1-real-numbers-surds",
        "questionText": "Expand and simplify: (√5 + 2)(√5 - 2).",
        "optionA": "1",
        "optionB": "9",
        "optionC": "√5 - 4",
        "optionD": "3",
        "correctOption": "A",
        "subConcept": "Conjugate Surd Expansion",
        "explanation": "This is the difference of two squares: (√5)² - (2)² = 5 - 4 = 1.",
        "remediationTip": "Applying (a + b)(a - b) = a² - b² to conjugate surds eliminates the radical."
      }
    ]
  },
  "jhs3-math-t2-algebra-expansion-factorization": {
    "id": "quiz-jhs3-math-t2-algebra-expansion-factorization",
    "topicId": "jhs3-math-t2-algebra-expansion-factorization",
    "title": "Algebraic Expressions & Factorization BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs3math-t2-1",
        "quizId": "quiz-jhs3-math-t2-algebra-expansion-factorization",
        "questionText": "Expand and simplify: (2x - 3)(3x + 4).",
        "optionA": "6x² - x - 12",
        "optionB": "6x² + x - 12",
        "optionC": "6x² - 12",
        "optionD": "6x² - 17x - 12",
        "correctOption": "A",
        "subConcept": "Binomial Expansion",
        "explanation": "(2x)(3x) + (2x)(4) - 3(3x) - 3(4) = 6x² + 8x - 9x - 12 = 6x² - x - 12.",
        "remediationTip": "Use FOIL: First (6x²), Outside (+8x), Inside (-9x), Last (-12); then combine like terms."
      },
      {
        "id": "q-jhs3math-t2-2",
        "quizId": "quiz-jhs3-math-t2-algebra-expansion-factorization",
        "questionText": "What is the expansion of (3a - 2b)²?",
        "optionA": "9a² - 4b²",
        "optionB": "9a² - 12ab + 4b²",
        "optionC": "9a² - 6ab + 4b²",
        "optionD": "9a² + 4b²",
        "correctOption": "B",
        "subConcept": "Perfect Square Expansion",
        "explanation": "(3a - 2b)² = (3a)² - 2(3a)(2b) + (2b)² = 9a² - 12ab + 4b².",
        "remediationTip": "Never forget the middle term 2ab in (a - b)² = a² - 2ab + b²."
      },
      {
        "id": "q-jhs3math-t2-3",
        "quizId": "quiz-jhs3-math-t2-algebra-expansion-factorization",
        "questionText": "Factorize completely: 2ax - 3ay - 2bx + 3by.",
        "optionA": "(2x - 3y)(a - b)",
        "optionB": "(2x + 3y)(a - b)",
        "optionC": "(2x - 3y)(a + b)",
        "optionD": "(ax - by)(2 - 3)",
        "correctOption": "A",
        "subConcept": "Factorization by Grouping",
        "explanation": "Group in pairs: a(2x - 3y) - b(2x - 3y) = (2x - 3y)(a - b). Note that factoring out -b changes +3by to -3y.",
        "remediationTip": "When factoring out a negative factor from the second pair, reverse the internal sign."
      },
      {
        "id": "q-jhs3math-t2-4",
        "quizId": "quiz-jhs3-math-t2-algebra-expansion-factorization",
        "questionText": "Factorize completely: 49x² - 16y².",
        "optionA": "(7x - 4y)²",
        "optionB": "(7x - 4y)(7x + 4y)",
        "optionC": "(49x - 16y)(x + y)",
        "optionD": "7(x - y)(7x + 4y)",
        "correctOption": "B",
        "subConcept": "Difference of Two Squares",
        "explanation": "49x² - 16y² = (7x)² - (4y)². Applying a² - b² = (a - b)(a + b) yields (7x - 4y)(7x + 4y).",
        "remediationTip": "Recognize difference of two squares: a² - b² = (a - b)(a + b)."
      },
      {
        "id": "q-jhs3math-t2-5",
        "quizId": "quiz-jhs3-math-t2-algebra-expansion-factorization",
        "questionText": "Factorize completely: 3x² - 75.",
        "optionA": "3(x - 5)²",
        "optionB": "3(x - 5)(x + 5)",
        "optionC": "(3x - 15)(x + 5)",
        "optionD": "3(x² - 25)",
        "correctOption": "B",
        "subConcept": "Two-Step Factorization",
        "explanation": "First factor out the common factor 3: 3(x² - 25). Then factorize the difference of squares: 3(x - 5)(x + 5).",
        "remediationTip": "Always remove the highest common factor (HCF) first before applying difference of squares."
      },
      {
        "id": "q-jhs3math-t2-6",
        "quizId": "quiz-jhs3-math-t2-algebra-expansion-factorization",
        "questionText": "Factorize the quadratic expression: x² - 8x + 15.",
        "optionA": "(x - 3)(x - 5)",
        "optionB": "(x + 3)(x + 5)",
        "optionC": "(x - 1)(x - 15)",
        "optionD": "(x - 2)(x - 6)",
        "correctOption": "A",
        "subConcept": "Factoring Quadratic Trinomials (a=1)",
        "explanation": "We need two factors of +15 whose sum is -8. The factors are -3 and -5 since (-3) × (-5) = 15 and (-3) + (-5) = -8. Thus (x - 3)(x - 5).",
        "remediationTip": "Find two numbers whose product equals the constant term c and sum equals the middle coefficient b."
      },
      {
        "id": "q-jhs3math-t2-7",
        "quizId": "quiz-jhs3-math-t2-algebra-expansion-factorization",
        "questionText": "Factorize: 2x² + 5x - 3.",
        "optionA": "(2x - 1)(x + 3)",
        "optionB": "(2x + 1)(x - 3)",
        "optionC": "(2x - 3)(x + 1)",
        "optionD": "(x - 1)(2x + 3)",
        "correctOption": "A",
        "subConcept": "Factoring Quadratic Trinomials (a≠1)",
        "explanation": "Product ac = 2 × (-3) = -6. Factors of -6 that add to +5 are +6 and -1. Split middle term: 2x² + 6x - x - 3 = 2x(x + 3) - 1(x + 3) = (2x - 1)(x + 3).",
        "remediationTip": "Split the middle term into two terms using factors of ac before grouping in pairs."
      },
      {
        "id": "q-jhs3math-t2-8",
        "quizId": "quiz-jhs3-math-t2-algebra-expansion-factorization",
        "questionText": "Simplify the algebraic fraction: (x² - 9) / (2x - 6).",
        "optionA": "(x + 3) / 2",
        "optionB": "(x - 3) / 2",
        "optionC": "x / 2",
        "optionD": "(x + 9) / 6",
        "correctOption": "A",
        "subConcept": "Simplifying Algebraic Fractions",
        "explanation": "Factorize numerator: (x - 3)(x + 3). Factorize denominator: 2(x - 3). Cancel common factor (x - 3): (x + 3) / 2.",
        "remediationTip": "Factorize both numerator and denominator completely before canceling common binomial factors."
      },
      {
        "id": "q-jhs3math-t2-9",
        "quizId": "quiz-jhs3-math-t2-algebra-expansion-factorization",
        "questionText": "Evaluate without using a calculator: 75² - 25².",
        "optionA": "2,500",
        "optionB": "5,000",
        "optionC": "5,625",
        "optionD": "10,000",
        "correctOption": "B",
        "subConcept": "Numerical Evaluation via DOTS",
        "explanation": "Apply a² - b² = (a - b)(a + b): (75 - 25)(75 + 25) = 50 × 100 = 5,000.",
        "remediationTip": "Use difference of two squares to evaluate numerical squares rapidly without tedious multiplication."
      },
      {
        "id": "q-jhs3math-t2-10",
        "quizId": "quiz-jhs3-math-t2-algebra-expansion-factorization",
        "questionText": "Factorize: 4x² - 12x + 9.",
        "optionA": "(2x - 3)²",
        "optionB": "(2x + 3)²",
        "optionC": "(4x - 3)(x - 3)",
        "optionD": "(2x - 9)(2x - 1)",
        "correctOption": "A",
        "subConcept": "Perfect Square Trinomial",
        "explanation": "Recognize (2x)² - 2(2x)(3) + (3)² = (2x - 3)².",
        "remediationTip": "Check if the first and last terms are perfect squares and the middle term is 2 × √first × √last."
      }
    ]
  },
  "jhs3-math-t3-linear-equations-inequalities": {
    "id": "quiz-jhs3-math-t3-linear-equations-inequalities",
    "topicId": "jhs3-math-t3-linear-equations-inequalities",
    "title": "Linear Equations & Inequalities BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs3math-t3-1",
        "quizId": "quiz-jhs3-math-t3-linear-equations-inequalities",
        "questionText": "Solve for x: 3(2x - 4) - 2(x + 1) = 14.",
        "optionA": "7",
        "optionB": "6",
        "optionC": "5",
        "optionD": "4",
        "correctOption": "A",
        "subConcept": "Linear Equations with Brackets",
        "explanation": "Expand: 6x - 12 - 2x - 2 = 14 -> 4x - 14 = 14 -> 4x = 28 -> x = 7.",
        "remediationTip": "Be careful with -2(x + 1) = -2x - 2; both signs inside become negative."
      },
      {
        "id": "q-jhs3math-t3-2",
        "quizId": "quiz-jhs3-math-t3-linear-equations-inequalities",
        "questionText": "Solve the fractional equation: (x + 2) / 3 - (x - 1) / 2 = 1.",
        "optionA": "x = -1",
        "optionB": "x = 1",
        "optionC": "x = -5",
        "optionD": "x = 5",
        "correctOption": "B",
        "subConcept": "Fractional Linear Equations",
        "explanation": "Multiply every term by LCM 6: 2(x + 2) - 3(x - 1) = 6 -> 2x + 4 - 3x + 3 = 6 -> -x + 7 = 6 -> -x = -1 -> x = 1.",
        "remediationTip": "Multiplying -3 by (x - 1) gives -3x + 3. Watch the double negative!"
      },
      {
        "id": "q-jhs3math-t3-3",
        "quizId": "quiz-jhs3-math-t3-linear-equations-inequalities",
        "questionText": "Find the truth set of the inequality: 5 - 2x < 11.",
        "optionA": "{x : x < -3}",
        "optionB": "{x : x > -3}",
        "optionC": "{x : x < 3}",
        "optionD": "{x : x > 3}",
        "correctOption": "B",
        "subConcept": "Solving Inequalities",
        "explanation": "-2x < 11 - 5 -> -2x < 6. Divide both sides by -2 and REVERSE the inequality sign: x > -3. Truth set = {x : x > -3}.",
        "remediationTip": "Remember: Dividing by a negative number flips the inequality symbol from < to >."
      },
      {
        "id": "q-jhs3math-t3-4",
        "quizId": "quiz-jhs3-math-t3-linear-equations-inequalities",
        "questionText": "Which symbol is used on a number line to show that the boundary number IS included in the inequality x ≤ 4?",
        "optionA": "Solid (closed) circle at 4",
        "optionB": "Open circle at 4",
        "optionC": "Double arrow at 4",
        "optionD": "Cross mark at 4",
        "correctOption": "A",
        "subConcept": "Number Line Graphing",
        "explanation": "A solid (filled) circle indicates that the endpoint is included in the solution set (≤ or ≥). An open circle is used for < or >.",
        "remediationTip": "Solid dot = included (≤, ≥); Open dot = not included (<, >)."
      },
      {
        "id": "q-jhs3math-t3-5",
        "quizId": "quiz-jhs3-math-t3-linear-equations-inequalities",
        "questionText": "Solve the inequality: (2x - 3) / 4 ≥ (x - 1) / 3.",
        "optionA": "x ≥ 5",
        "optionB": "x ≥ 2.5",
        "optionC": "x ≤ 5",
        "optionD": "x ≥ 1",
        "correctOption": "B",
        "subConcept": "Fractional Inequalities",
        "explanation": "Multiply by LCM 12: 3(2x - 3) ≥ 4(x - 1) -> 6x - 9 ≥ 4x - 4 -> 6x - 4x ≥ -4 + 9 -> 2x ≥ 5 -> x ≥ 5/2 (x ≥ 2.5).",
        "remediationTip": "Multiply through by positive 12; the inequality sign does not flip because 12 is positive."
      },
      {
        "id": "q-jhs3math-t3-6",
        "quizId": "quiz-jhs3-math-t3-linear-equations-inequalities",
        "questionText": "If 3 is added to twice a certain number, the result is at most 17. Find the maximum possible value of the number.",
        "optionA": "7",
        "optionB": "8",
        "optionC": "10",
        "optionD": "14",
        "correctOption": "A",
        "subConcept": "Word Problem with Inequality",
        "explanation": "'At most' means ≤: 2x + 3 ≤ 17 -> 2x ≤ 14 -> x ≤ 7. The maximum possible value is 7.",
        "remediationTip": "'At most' corresponds to the ≤ symbol; 'At least' corresponds to the ≥ symbol."
      },
      {
        "id": "q-jhs3math-t3-7",
        "quizId": "quiz-jhs3-math-t3-linear-equations-inequalities",
        "questionText": "Solve for y: (3/y) + 4 = 10.",
        "optionA": "1/2",
        "optionB": "2",
        "optionC": "3",
        "optionD": "18",
        "correctOption": "A",
        "subConcept": "Variable in Denominator",
        "explanation": "3/y = 10 - 4 -> 3/y = 6. Cross-multiply: 6y = 3 -> y = 3/6 = 1/2.",
        "remediationTip": "Subtract the constant term first, then cross-multiply to solve for the denominator variable."
      },
      {
        "id": "q-jhs3math-t3-8",
        "quizId": "quiz-jhs3-math-t3-linear-equations-inequalities",
        "questionText": "What is the truth set of integers for the double inequality -3 < x ≤ 2?",
        "optionA": "{-2, -1, 0, 1, 2}",
        "optionB": "{-3, -2, -1, 0, 1, 2}",
        "optionC": "{-2, -1, 0, 1}",
        "optionD": "{-3, -2, -1, 0, 1}",
        "correctOption": "A",
        "subConcept": "Double Inequalities & Truth Sets",
        "explanation": "Since -3 < x, -3 is not included (starts at -2). Since x ≤ 2, 2 is included. Integers: {-2, -1, 0, 1, 2}.",
        "remediationTip": "Strict inequality < excludes the boundary value; inclusive inequality ≤ includes it."
      },
      {
        "id": "q-jhs3math-t3-9",
        "quizId": "quiz-jhs3-math-t3-linear-equations-inequalities",
        "questionText": "A rectangular field has length (2x + 1) m and width 5 m. If its perimeter is 32 m, find the value of x.",
        "optionA": "5",
        "optionB": "5.5",
        "optionC": "6",
        "optionD": "7",
        "correctOption": "A",
        "subConcept": "Linear Equation Modeling (Perimeter)",
        "explanation": "Perimeter = 2(l + w) = 2[(2x + 1) + 5] = 32 -> 2(2x + 6) = 32 -> 4x + 12 = 32 -> 4x = 20 -> x = 5.",
        "remediationTip": "Perimeter of rectangle is 2(length + width); set equal to 32 and solve for x."
      },
      {
        "id": "q-jhs3math-t3-10",
        "quizId": "quiz-jhs3-math-t3-linear-equations-inequalities",
        "questionText": "Solve the inequality: 4x - 7 > 6x + 5.",
        "optionA": "x < -6",
        "optionB": "x > -6",
        "optionC": "x < 6",
        "optionD": "x > 6",
        "correctOption": "A",
        "subConcept": "Inequality Sign Inversion",
        "explanation": "4x - 6x > 5 + 7 -> -2x > 12. Divide by -2 and reverse sign: x < -6.",
        "remediationTip": "Remember: Dividing by -2 reverses > to <."
      }
    ]
  },
  "jhs3-math-t4-simultaneous-equations": {
    "id": "quiz-jhs3-math-t4-simultaneous-equations",
    "topicId": "jhs3-math-t4-simultaneous-equations",
    "title": "Simultaneous Linear Equations BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs3math-t4-1",
        "quizId": "quiz-jhs3-math-t4-simultaneous-equations",
        "questionText": "Solve simultaneously: x + y = 9 and x - y = 3.",
        "optionA": "x = 6, y = 3",
        "optionB": "x = 5, y = 4",
        "optionC": "x = 7, y = 2",
        "optionD": "x = 8, y = 1",
        "correctOption": "A",
        "subConcept": "Elimination Method",
        "explanation": "Add the two equations: (x + x) + (y - y) = 9 + 3 -> 2x = 12 -> x = 6. Substitute x = 6 into first equation: 6 + y = 9 -> y = 3.",
        "remediationTip": "When coefficients of y are +1 and -1, adding the equations eliminates y immediately."
      },
      {
        "id": "q-jhs3math-t4-2",
        "quizId": "quiz-jhs3-math-t4-simultaneous-equations",
        "questionText": "Solve simultaneously for x and y: 2x + 3y = 13 and y = x - 4.",
        "optionA": "x = 5, y = 1",
        "optionB": "x = 4, y = 0",
        "optionC": "x = 6, y = 2",
        "optionD": "x = 3, y = -1",
        "correctOption": "A",
        "subConcept": "Substitution Method",
        "explanation": "Substitute (x - 4) for y in the first equation: 2x + 3(x - 4) = 13 -> 2x + 3x - 12 = 13 -> 5x = 25 -> x = 5. Then y = 5 - 4 = 1.",
        "remediationTip": "Use substitution when one equation already gives a variable as the subject."
      },
      {
        "id": "q-jhs3math-t4-3",
        "quizId": "quiz-jhs3-math-t4-simultaneous-equations",
        "questionText": "What represents the solution of a pair of simultaneous equations on a Cartesian graph?",
        "optionA": "The coordinates of their point of intersection",
        "optionB": "The y-intercept of the first line",
        "optionC": "The x-intercept of the second line",
        "optionD": "The midpoint between both origins",
        "correctOption": "A",
        "subConcept": "Graphical Solution Interpretation",
        "explanation": "The point where the two lines intersect has coordinates (x, y) that satisfy both equations simultaneously.",
        "remediationTip": "The intersection point of two linear graphs gives the unique simultaneous solution."
      },
      {
        "id": "q-jhs3math-t4-4",
        "quizId": "quiz-jhs3-math-t4-simultaneous-equations",
        "questionText": "If 3x + 2y = 16 and 2x + 2y = 12, what is the value of x?",
        "optionA": "4",
        "optionB": "2",
        "optionC": "3",
        "optionD": "5",
        "correctOption": "A",
        "subConcept": "Direct Subtraction Elimination",
        "explanation": "Subtract equation 2 from equation 1 directly: (3x - 2x) + (2y - 2y) = 16 - 12 -> x = 4.",
        "remediationTip": "Since the coefficients of y are identical (+2y), subtract to eliminate y immediately."
      },
      {
        "id": "q-jhs3math-t4-5",
        "quizId": "quiz-jhs3-math-t4-simultaneous-equations",
        "questionText": "The cost of 2 shirts and 3 pairs of socks is GH₵ 95. The cost of 3 shirts and 2 pairs of socks is GH₵ 110. Find the cost of one shirt.",
        "optionA": "GH₵ 28.00",
        "optionB": "GH₵ 25.00",
        "optionC": "GH₵ 30.00",
        "optionD": "GH₵ 15.00",
        "correctOption": "A",
        "subConcept": "Word Problem Formulation",
        "explanation": "(1) 2s + 3p = 95; (2) 3s + 2p = 110. Multiply (1) by 2: 4s + 6p = 190. Multiply (2) by 3: 9s + 6p = 330. Subtract: 5s = 140 -> s = GH₵ 28.00.",
        "remediationTip": "Eliminate socks (p) by equalizing their coefficients to 6."
      },
      {
        "id": "q-jhs3math-t4-6",
        "quizId": "quiz-jhs3-math-t4-simultaneous-equations",
        "questionText": "Solve for x: 3x - 4y = 7 and x + 2y = 9.",
        "optionA": "x = 5",
        "optionB": "x = 4",
        "optionC": "x = 3",
        "optionD": "x = 2",
        "correctOption": "A",
        "subConcept": "Elimination by Multiplication",
        "explanation": "Multiply the second equation by 2: 2x + 4y = 18. Add to first equation: (3x + 2x) + (-4y + 4y) = 7 + 18 -> 5x = 25 -> x = 5.",
        "remediationTip": "Multiply by 2 to make the y coefficients -4 and +4, then add to eliminate y."
      },
      {
        "id": "q-jhs3math-t4-7",
        "quizId": "quiz-jhs3-math-t4-simultaneous-equations",
        "questionText": "Two numbers have a sum of 28 and a difference of 8. What is the larger number?",
        "optionA": "18",
        "optionB": "20",
        "optionC": "16",
        "optionD": "14",
        "correctOption": "A",
        "subConcept": "Number Word Problems",
        "explanation": "Let numbers be x and y (x > y): x + y = 28; x - y = 8. Add equations: 2x = 36 -> x = 18.",
        "remediationTip": "x = (Sum + Difference) / 2 = (28 + 8) / 2 = 18."
      },
      {
        "id": "q-jhs3math-t4-8",
        "quizId": "quiz-jhs3-math-t4-simultaneous-equations",
        "questionText": "If 2x - y = 5 and 3x + 2y = 11, what is the value of y?",
        "optionA": "1",
        "optionB": "-1",
        "optionC": "3",
        "optionD": "2",
        "correctOption": "A",
        "subConcept": "Finding Second Unknown",
        "explanation": "Multiply first equation by 2: 4x - 2y = 10. Add to second: 7x = 21 -> x = 3. Then 2(3) - y = 5 -> 6 - y = 5 -> y = 1.",
        "remediationTip": "Always read carefully to see whether the question asks for x, y, or both."
      },
      {
        "id": "q-jhs3math-t4-9",
        "quizId": "quiz-jhs3-math-t4-simultaneous-equations",
        "questionText": "What happens on a graph if two simultaneous linear equations have NO solution?",
        "optionA": "The two lines are parallel and never intersect",
        "optionB": "The two lines are perpendicular",
        "optionC": "The two lines pass through the origin",
        "optionD": "The two lines lie on top of each other",
        "correctOption": "A",
        "subConcept": "Inconsistent Systems",
        "explanation": "Parallel lines have the same gradient and never meet, meaning there is no coordinate pair that satisfies both equations.",
        "remediationTip": "Parallel lines have no point of intersection and therefore have no simultaneous solution."
      },
      {
        "id": "q-jhs3math-t4-10",
        "quizId": "quiz-jhs3-math-t4-simultaneous-equations",
        "questionText": "A father is 3 times as old as his son. In 12 years time, he will be twice as old as his son. How old is the son now?",
        "optionA": "12 years",
        "optionB": "10 years",
        "optionC": "15 years",
        "optionD": "14 years",
        "correctOption": "A",
        "subConcept": "Age Problem Modeling",
        "explanation": "Let son's age = s, father's age = f: (1) f = 3s. (2) In 12 years: f + 12 = 2(s + 12). Substitute f = 3s: 3s + 12 = 2s + 24 -> s = 12 years.",
        "remediationTip": "Remember to add 12 to BOTH the father's and son's ages when looking ahead 12 years."
      }
    ]
  },
  "jhs3-math-t5-quadratic-equations": {
    "id": "quiz-jhs3-math-t5-quadratic-equations",
    "topicId": "jhs3-math-t5-quadratic-equations",
    "title": "Quadratic Equations & Graphs BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs3math-t5-1",
        "quizId": "quiz-jhs3-math-t5-quadratic-equations",
        "questionText": "Find the roots of the quadratic equation: x² - 7x + 12 = 0.",
        "optionA": "x = 3 and x = 4",
        "optionB": "x = -3 and x = -4",
        "optionC": "x = 2 and x = 6",
        "optionD": "x = -2 and x = -6",
        "correctOption": "A",
        "subConcept": "Zero Product Property",
        "explanation": "Factorize: (x - 3)(x - 4) = 0. Either x - 3 = 0 => x = 3; or x - 4 = 0 => x = 4.",
        "remediationTip": "Set each factor to zero to find the roots."
      },
      {
        "id": "q-jhs3math-t5-2",
        "quizId": "quiz-jhs3-math-t5-quadratic-equations",
        "questionText": "Solve the equation: 2x² - 8x = 0.",
        "optionA": "x = 0 and x = 4",
        "optionB": "x = 4 only",
        "optionC": "x = 2 and x = 4",
        "optionD": "x = 0 and x = -4",
        "correctOption": "A",
        "subConcept": "Common Factor in Quadratic",
        "explanation": "Factor out 2x: 2x(x - 4) = 0. Either 2x = 0 => x = 0; or x - 4 = 0 => x = 4. (Never divide by x!).",
        "remediationTip": "Dividing by x eliminates the root x = 0. Factor out 2x instead."
      },
      {
        "id": "q-jhs3math-t5-3",
        "quizId": "quiz-jhs3-math-t5-quadratic-equations",
        "questionText": "What are the roots of x² - 25 = 0?",
        "optionA": "x = ±5",
        "optionB": "x = 5 only",
        "optionC": "x = 25",
        "optionD": "x = ±25",
        "correctOption": "A",
        "subConcept": "Difference of Squares Equation",
        "explanation": "(x - 5)(x + 5) = 0  =>  x = 5 or x = -5 (x = ±5).",
        "remediationTip": "Taking the square root of both sides gives both positive and negative roots: ±5."
      },
      {
        "id": "q-jhs3math-t5-4",
        "quizId": "quiz-jhs3-math-t5-quadratic-equations",
        "questionText": "Solve: 3x² + 5x - 2 = 0.",
        "optionA": "x = 1/3 and x = -2",
        "optionB": "x = -1/3 and x = 2",
        "optionC": "x = 1 and x = -6",
        "optionD": "x = 2/3 and x = -1",
        "correctOption": "A",
        "subConcept": "Factorizing ax² + bx + c = 0",
        "explanation": "Product ac = -6. Factors: +6 and -1. 3x² + 6x - x - 2 = 3x(x + 2) - 1(x + 2) = (3x - 1)(x + 2) = 0. Roots: x = 1/3, x = -2.",
        "remediationTip": "Split the middle term: 3x - 1 = 0 => x = 1/3; x + 2 = 0 => x = -2."
      },
      {
        "id": "q-jhs3math-t5-5",
        "quizId": "quiz-jhs3-math-t5-quadratic-equations",
        "questionText": "What is the shape of the graph of any quadratic function y = ax² + bx + c?",
        "optionA": "A parabola",
        "optionB": "A hyperbola",
        "optionC": "A circle",
        "optionD": "A straight line",
        "correctOption": "A",
        "subConcept": "Parabolic Graph Properties",
        "explanation": "A quadratic function produces a symmetrical U-shaped or ∩-shaped curve called a parabola.",
        "remediationTip": "Quadratic curves are parabolas; linear graphs are straight lines."
      },
      {
        "id": "q-jhs3math-t5-6",
        "quizId": "quiz-jhs3-math-t5-quadratic-equations",
        "questionText": "How are the roots of ax² + bx + c = 0 identified from the graph of y = ax² + bx + c?",
        "optionA": "The x-coordinates where the curve intersects the x-axis",
        "optionB": "The y-intercept of the curve",
        "optionC": "The coordinates of the highest point",
        "optionD": "The origin (0, 0)",
        "correctOption": "A",
        "subConcept": "Graphical Identification of Roots",
        "explanation": "The equation equals zero when y = 0, which corresponds to the points where the parabola crosses the x-axis.",
        "remediationTip": "Roots are the x-intercepts of the quadratic curve (where y = 0)."
      },
      {
        "id": "q-jhs3math-t5-7",
        "quizId": "quiz-jhs3-math-t5-quadratic-equations",
        "questionText": "What is the equation of the axis of symmetry for the parabola y = x² - 6x + 5?",
        "optionA": "x = 3",
        "optionB": "x = -3",
        "optionC": "x = 6",
        "optionD": "y = 3",
        "correctOption": "A",
        "subConcept": "Axis of Symmetry Formula",
        "explanation": "Axis of symmetry formula: x = -b / (2a) = -(-6) / (2 × 1) = 6 / 2 = 3. Equation is x = 3.",
        "remediationTip": "Axis of symmetry: x = -b / (2a); it is always a vertical line 'x = constant'."
      },
      {
        "id": "q-jhs3math-t5-8",
        "quizId": "quiz-jhs3-math-t5-quadratic-equations",
        "questionText": "If the coefficient of x² is NEGATIVE (e.g. y = -x² + 4x + 1), what type of turning point does the parabola have?",
        "optionA": "A Maximum turning point (∩-shape)",
        "optionB": "A Minimum turning point (U-shape)",
        "optionC": "No turning point",
        "optionD": "An inflection point",
        "correctOption": "A",
        "subConcept": "Maximum vs Minimum Curves",
        "explanation": "When a < 0, the parabola opens downward like a hill (∩-shape), reaching a peak or Maximum point.",
        "remediationTip": "Negative a = downward hill (Maximum); Positive a = upward bowl (Minimum)."
      },
      {
        "id": "q-jhs3math-t5-9",
        "quizId": "quiz-jhs3-math-t5-quadratic-equations",
        "questionText": "Find the roots of: (x - 5)(x + 2) = 0.",
        "optionA": "x = 5 and x = -2",
        "optionB": "x = -5 and x = 2",
        "optionC": "x = 5 and x = 2",
        "optionD": "x = -5 and x = -2",
        "correctOption": "A",
        "subConcept": "Factored Equation Roots",
        "explanation": "x - 5 = 0 => x = 5; x + 2 = 0 => x = -2.",
        "remediationTip": "Change the signs of the constants inside the factors to find the roots."
      },
      {
        "id": "q-jhs3math-t5-10",
        "quizId": "quiz-jhs3-math-t5-quadratic-equations",
        "questionText": "The product of two consecutive positive integers is 56. What are the integers?",
        "optionA": "7 and 8",
        "optionB": "6 and 7",
        "optionC": "8 and 9",
        "optionD": "5 and 6",
        "correctOption": "A",
        "subConcept": "Quadratic Word Problem",
        "explanation": "Let integers be n and n + 1: n(n + 1) = 56 -> n² + n - 56 = 0 -> (n + 8)(n - 7) = 0. Since positive, n = 7, and n + 1 = 8.",
        "remediationTip": "Consecutive integers are n and n + 1; discard the negative root (-8)."
      }
    ]
  },
  "jhs3-math-t6-change-of-subject": {
    "id": "quiz-jhs3-math-t6-change-of-subject",
    "topicId": "jhs3-math-t6-change-of-subject",
    "title": "Change of Subject of Formulae BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs3math-t6-1",
        "quizId": "quiz-jhs3-math-t6-change-of-subject",
        "questionText": "If v = u + at, make 'a' the subject of the formula.",
        "optionA": "a = (v - u) / t",
        "optionB": "a = (v + u) / t",
        "optionC": "a = v - ut",
        "optionD": "a = vt - u",
        "correctOption": "A",
        "subConcept": "Linear Subject Isolation",
        "explanation": "Subtract u: v - u = at. Divide by t: a = (v - u) / t.",
        "remediationTip": "Undo addition with subtraction, then undo multiplication with division."
      },
      {
        "id": "q-jhs3math-t6-2",
        "quizId": "quiz-jhs3-math-t6-change-of-subject",
        "questionText": "Make 'r' the subject of the circle area formula: A = πr².",
        "optionA": "r = √(A / π)",
        "optionB": "r = A / π",
        "optionC": "r = √(Aπ)",
        "optionD": "r = (A / π)²",
        "correctOption": "A",
        "subConcept": "Formulas with Squares",
        "explanation": "Divide by π: r² = A / π. Take the positive square root: r = √(A / π).",
        "remediationTip": "Isolate the squared variable first, then take the square root of both sides."
      },
      {
        "id": "q-jhs3math-t6-3",
        "quizId": "quiz-jhs3-math-t6-change-of-subject",
        "questionText": "Make 'h' the subject of the cylinder volume formula: V = πr²h.",
        "optionA": "h = V / (πr²)",
        "optionB": "h = Vπr²",
        "optionC": "h = √(V / πr)",
        "optionD": "h = (V - π) / r²",
        "correctOption": "A",
        "subConcept": "Isolating Factors",
        "explanation": "Divide both sides by the product (πr²): h = V / (πr²).",
        "remediationTip": "Divide by the entire coefficient multiplying h."
      },
      {
        "id": "q-jhs3math-t6-4",
        "quizId": "quiz-jhs3-math-t6-change-of-subject",
        "questionText": "Given that y = √(x + 3), make 'x' the subject.",
        "optionA": "x = y² - 3",
        "optionB": "x = (y - 3)²",
        "optionC": "x = y² + 3",
        "optionD": "x = √(y - 3)",
        "correctOption": "A",
        "subConcept": "Clearing Square Roots",
        "explanation": "Square both sides: y² = x + 3. Subtract 3: x = y² - 3.",
        "remediationTip": "Squaring both sides eliminates the outer radical: (√(x + 3))² = x + 3."
      },
      {
        "id": "q-jhs3math-t6-5",
        "quizId": "quiz-jhs3-math-t6-change-of-subject",
        "questionText": "Make 'x' the subject of the relation: y = (ax + b) / c.",
        "optionA": "x = (cy - b) / a",
        "optionB": "x = (cy + b) / a",
        "optionC": "x = cy - ab",
        "optionD": "x = (c - b) / ay",
        "correctOption": "A",
        "subConcept": "Clearing Denominators",
        "explanation": "Multiply by c: cy = ax + b. Subtract b: cy - b = ax. Divide by a: x = (cy - b) / a.",
        "remediationTip": "Clear the denominator first by multiplying, then isolate the x term."
      },
      {
        "id": "q-jhs3math-t6-6",
        "quizId": "quiz-jhs3-math-t6-change-of-subject",
        "questionText": "If 1/f = 1/u + 1/v, make 'f' the subject.",
        "optionA": "f = (uv) / (u + v)",
        "optionB": "f = u + v",
        "optionC": "f = (u + v) / (uv)",
        "optionD": "f = uv",
        "correctOption": "A",
        "subConcept": "Reciprocal Formulae",
        "explanation": "Combine RHS fractions: 1/f = (v + u) / (uv). Invert both sides: f = (uv) / (u + v).",
        "remediationTip": "Combine fractions on the RHS first, then invert both sides to find f."
      },
      {
        "id": "q-jhs3math-t6-7",
        "quizId": "quiz-jhs3-math-t6-change-of-subject",
        "questionText": "Given that P = 2(l + w), make 'w' the subject.",
        "optionA": "w = (P / 2) - l",
        "optionB": "w = P - 2l",
        "optionC": "w = (P - l) / 2",
        "optionD": "w = P / (2l)",
        "correctOption": "A",
        "subConcept": "Perimeter Formula Subject",
        "explanation": "Divide by 2: P / 2 = l + w. Subtract l: w = (P / 2) - l  (or w = (P - 2l) / 2).",
        "remediationTip": "Divide by 2 first, then subtract l from the quotient."
      },
      {
        "id": "q-jhs3math-t6-8",
        "quizId": "quiz-jhs3-math-t6-change-of-subject",
        "questionText": "Make 'x' the subject of: y = (2x - 3) / (x + 1).",
        "optionA": "x = (y + 3) / (2 - y)",
        "optionB": "x = (y - 3) / (2 + y)",
        "optionC": "x = (2y + 1) / (y - 3)",
        "optionD": "x = (3 - y) / (2 - y)",
        "correctOption": "A",
        "subConcept": "Target Variable in Both Terms",
        "explanation": "Cross-multiply: y(x + 1) = 2x - 3 -> yx + y = 2x - 3. Group x terms: y + 3 = 2x - yx -> y + 3 = x(2 - y) -> x = (y + 3) / (2 - y).",
        "remediationTip": "Group terms with x on one side and factor out x."
      },
      {
        "id": "q-jhs3math-t6-9",
        "quizId": "quiz-jhs3-math-t6-change-of-subject",
        "questionText": "In the kinetic energy formula E = (1/2)mv², make 'v' the subject.",
        "optionA": "v = √(2E / m)",
        "optionB": "v = 2E / m",
        "optionC": "v = √(E / 2m)",
        "optionD": "v = (2E / m)²",
        "correctOption": "A",
        "subConcept": "Physics Formula Rearrangement",
        "explanation": "Multiply by 2: 2E = mv². Divide by m: v² = 2E / m. Take square root: v = √(2E / m).",
        "remediationTip": "Clear the 1/2 fraction by multiplying by 2 before dividing by m."
      },
      {
        "id": "q-jhs3math-t6-10",
        "quizId": "quiz-jhs3-math-t6-change-of-subject",
        "questionText": "Make 'T' the subject of: I = (P × R × T) / 100.",
        "optionA": "T = (100 × I) / (P × R)",
        "optionB": "T = (I × P × R) / 100",
        "optionC": "T = (100 × P) / (I × R)",
        "optionD": "T = (I × R) / (100 × P)",
        "correctOption": "A",
        "subConcept": "Simple Interest Subject",
        "explanation": "Multiply by 100: 100I = PRT. Divide by PR: T = (100I) / (PR).",
        "remediationTip": "Multiply by 100 to clear the fraction, then divide by P and R."
      }
    ]
  },
  "jhs3-math-t7-business-math": {
    "id": "quiz-jhs3-math-t7-business-math",
    "topicId": "jhs3-math-t7-business-math",
    "title": "Business Mathematics BECE Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "q-jhs3math-t7-1",
        "quizId": "quiz-jhs3-math-t7-business-math",
        "questionText": "A trader bought a bag of rice for GH₵ 600 and sold it for GH₵ 750. Calculate the percentage profit.",
        "optionA": "25%",
        "optionB": "20%",
        "optionC": "15%",
        "optionD": "30%",
        "correctOption": "A",
        "subConcept": "Percentage Profit Calculation",
        "explanation": "Profit = SP - CP = 750 - 600 = GH₵ 150. % Profit = (Profit / CP) × 100% = (150 / 600) × 100% = 25%.",
        "remediationTip": "Always divide profit by the COST PRICE (600), never by the selling price (750)."
      },
      {
        "id": "q-jhs3math-t7-2",
        "quizId": "quiz-jhs3-math-t7-business-math",
        "questionText": "An article is sold for GH₵ 460 at a profit of 15%. What was the cost price of the article?",
        "optionA": "GH₵ 400.00",
        "optionB": "GH₵ 391.00",
        "optionC": "GH₵ 420.00",
        "optionD": "GH₵ 380.00",
        "correctOption": "A",
        "subConcept": "Finding Cost Price from Selling Price",
        "explanation": "SP represents 115% of CP: 1.15 × CP = 460  =>  CP = 460 / 1.15 = GH₵ 400.00.",
        "remediationTip": "Cost Price = [Selling Price × 100] / [100 + % Profit]."
      },
      {
        "id": "q-jhs3math-t7-3",
        "quizId": "quiz-jhs3-math-t7-business-math",
        "questionText": "Calculate the Simple Interest on GH₵ 2,400 for 3 years at 5% per annum.",
        "optionA": "GH₵ 360.00",
        "optionB": "GH₵ 120.00",
        "optionC": "GH₵ 480.00",
        "optionD": "GH₵ 240.00",
        "correctOption": "A",
        "subConcept": "Simple Interest Formula",
        "explanation": "I = (P × R × T) / 100 = (2,400 × 5 × 3) / 100 = 24 × 15 = GH₵ 360.00.",
        "remediationTip": "Simple Interest = (Principal × Rate × Time) / 100."
      },
      {
        "id": "q-jhs3math-t7-4",
        "quizId": "quiz-jhs3-math-t7-business-math",
        "questionText": "How long will it take a principal of GH₵ 5,000 to earn an interest of GH₵ 1,000 at a rate of 10% per annum simple interest?",
        "optionA": "2 years",
        "optionB": "3 years",
        "optionC": "4 years",
        "optionD": "5 years",
        "correctOption": "A",
        "subConcept": "Finding Time in Simple Interest",
        "explanation": "T = (100 × I) / (P × R) = (100 × 1,000) / (5,000 × 10) = 100,000 / 50,000 = 2 years.",
        "remediationTip": "Rearrange interest formula: Time T = (100 × I) / (P × R)."
      },
      {
        "id": "q-jhs3math-t7-5",
        "quizId": "quiz-jhs3-math-t7-business-math",
        "questionText": "A radio set marked at GH₵ 350 is sold at a cash discount of 10%. How much does a customer pay?",
        "optionA": "GH₵ 315.00",
        "optionB": "GH₵ 325.00",
        "optionC": "GH₵ 335.00",
        "optionD": "GH₵ 35.00",
        "correctOption": "A",
        "subConcept": "Cash Discount Calculation",
        "explanation": "Discount = 10% of 350 = GH₵ 35. Amount paid = Marked Price - Discount = 350 - 35 = GH₵ 315.00.",
        "remediationTip": "Customer pays 90% of marked price: 0.90 × 350 = GH₵ 315.00."
      },
      {
        "id": "q-jhs3math-t7-6",
        "quizId": "quiz-jhs3-math-t7-business-math",
        "questionText": "If an item costing GH₵ 200 is sold for GH₵ 170, what is the percentage loss?",
        "optionA": "15%",
        "optionB": "30%",
        "optionC": "17.6%",
        "optionD": "12.5%",
        "correctOption": "A",
        "subConcept": "Percentage Loss",
        "explanation": "Loss = CP - SP = 200 - 170 = GH₵ 30. % Loss = (30 / 200) × 100% = 15%.",
        "remediationTip": "Percentage loss is always calculated on the cost price: (Loss / CP) × 100%."
      },
      {
        "id": "q-jhs3math-t7-7",
        "quizId": "quiz-jhs3-math-t7-business-math",
        "questionText": "A customer buys goods worth GH₵ 800 subject to Value Added Tax (VAT) of 15%. What is the total amount paid?",
        "optionA": "GH₵ 920.00",
        "optionB": "GH₵ 900.00",
        "optionC": "GH₵ 815.00",
        "optionD": "GH₵ 120.00",
        "correctOption": "A",
        "subConcept": "VAT Calculation",
        "explanation": "VAT = 15% of 800 = 0.15 × 800 = GH₵ 120. Total paid = 800 + 120 = GH₵ 920.00.",
        "remediationTip": "VAT is added to the purchase price: Total = Goods Price + VAT Amount."
      },
      {
        "id": "q-jhs3math-t7-8",
        "quizId": "quiz-jhs3-math-t7-business-math",
        "questionText": "A motorcycle bought for GH₵ 10,000 depreciates at a rate of 10% per annum. What is its value at the end of 2 years?",
        "optionA": "GH₵ 8,100.00",
        "optionB": "GH₵ 8,000.00",
        "optionC": "GH₵ 9,000.00",
        "optionD": "GH₵ 7,290.00",
        "correctOption": "A",
        "subConcept": "Asset Depreciation",
        "explanation": "End of Year 1: 10,000 - 10% = GH₵ 9,000. End of Year 2: 9,000 - 10% of 9,000 = 9,000 - 900 = GH₵ 8,100.00. (Formula: 10,000 × (0.9)² = 8,100).",
        "remediationTip": "Depreciation decreases value each year: Value = P(1 - R/100)^n."
      },
      {
        "id": "q-jhs3math-t7-9",
        "quizId": "quiz-jhs3-math-t7-business-math",
        "questionText": "What is the Compound Interest on GH₵ 1,000 for 2 years at 10% per annum compounded annually?",
        "optionA": "GH₵ 210.00",
        "optionB": "GH₵ 200.00",
        "optionC": "GH₵ 100.00",
        "optionD": "GH₵ 1,210.00",
        "correctOption": "A",
        "subConcept": "Compound Interest",
        "explanation": "Year 1 Amount = 1,000 × 1.10 = GH₵ 1,100. Year 2 Amount = 1,100 × 1.10 = GH₵ 1,210. Compound Interest = Amount - Principal = 1,210 - 1,000 = GH₵ 210.00.",
        "remediationTip": "Compound interest includes interest earned on the previous year's interest."
      },
      {
        "id": "q-jhs3math-t7-10",
        "quizId": "quiz-jhs3-math-t7-business-math",
        "questionText": "Calculate the simple interest on GH₵ 1,800 for 8 months at 5% per annum.",
        "optionA": "GH₵ 60.00",
        "optionB": "GH₵ 72.00",
        "optionC": "GH₵ 90.00",
        "optionD": "GH₵ 720.00",
        "correctOption": "A",
        "subConcept": "Time in Months Simple Interest",
        "explanation": "Time T = 8/12 = 2/3 year. I = (1,800 × 5 × 2/3) / 100 = 18 × 5 × (2/3) = 90 × (2/3) = GH₵ 60.00.",
        "remediationTip": "Always divide months by 12 to convert time into years in the simple interest formula."
      }
    ]
  },
  "jhs3-math-t8-ratios-proportions-rates": {
    "id": "quiz-jhs3-math-t8-ratios-proportions-rates",
    "topicId": "jhs3-math-t8-ratios-proportions-rates",
    "title": "Ratios, Direct/Inverse Proportions & Rates of Work BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-math-q71",
        "quizId": "quiz-jhs3-math-t8-ratios-proportions-rates",
        "questionText": "Three partners, Kofi, Ama, and Yao, share a profit of GH₵ 84,000 in the ratio 2 : 5 : 7. How much does Ama receive?",
        "optionA": "GH₵ 12,000",
        "optionB": "GH₵ 30,000",
        "optionC": "GH₵ 42,000",
        "optionD": "GH₵ 35,000",
        "correctOption": "B",
        "subConcept": "Ratio Sharing",
        "explanation": "Total ratio parts = 2 + 5 + 7 = 14. Ama's share is (5/14) * 84,000 = 5 * 6,000 = GH₵ 30,000.",
        "remediationTip": "Find the total number of parts first by summing all terms in the ratio, then calculate the individual fraction."
      },
      {
        "id": "jhs3-math-q72",
        "quizId": "quiz-jhs3-math-t8-ratios-proportions-rates",
        "questionText": "If 12 builders can construct a boundary wall in 15 days, how many days will 20 builders take working at the identical rate?",
        "optionA": "9 days",
        "optionB": "25 days",
        "optionC": "10 days",
        "optionD": "8 days",
        "correctOption": "A",
        "subConcept": "Inverse Proportion",
        "explanation": "Inverse proportion: Days * Workers = Constant. Total worker-days = 12 * 15 = 180. Days for 20 builders = 180 / 20 = 9 days.",
        "remediationTip": "More workers mean fewer days. Remember that inverse variation requires multiplying the quantities to find the constant product k."
      },
      {
        "id": "jhs3-math-q73",
        "quizId": "quiz-jhs3-math-t8-ratios-proportions-rates",
        "questionText": "A motorist travels a distance of 270 km in 3 hours 45 minutes. Calculate his average speed in km/h.",
        "optionA": "75 km/h",
        "optionB": "72 km/h",
        "optionC": "80 km/h",
        "optionD": "68 km/h",
        "correctOption": "B",
        "subConcept": "Speed, Distance, Time",
        "explanation": "Convert 3 hours 45 minutes to hours: 3 + 45/60 = 3.75 hours (or 15/4 h). Average speed = Distance / Time = 270 / 3.75 = 72 km/h.",
        "remediationTip": "WAEC trap: Never divide 270 by 3.45! 45 minutes is 3/4 of an hour (0.75 h), not 0.45."
      },
      {
        "id": "jhs3-math-q74",
        "quizId": "quiz-jhs3-math-t8-ratios-proportions-rates",
        "questionText": "Pipe A can fill a water reservoir in 6 hours, while Pipe B can fill it in 3 hours. How long will it take both pipes working simultaneously to fill the reservoir?",
        "optionA": "4.5 hours",
        "optionB": "2.5 hours",
        "optionC": "2.0 hours",
        "optionD": "1.5 hours",
        "correctOption": "C",
        "subConcept": "Rates of Work",
        "explanation": "Combined rate = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2 reservoir per hour. Time taken = 1 / (1/2) = 2 hours.",
        "remediationTip": "Add the rates of work per unit time (fractions), then invert the resulting fraction to find the total time."
      },
      {
        "id": "jhs3-math-q75",
        "quizId": "quiz-jhs3-math-t8-ratios-proportions-rates",
        "questionText": "If y varies directly as x^2, and y = 45 when x = 3, determine the value of y when x = 5.",
        "optionA": "75",
        "optionB": "125",
        "optionC": "100",
        "optionD": "225",
        "correctOption": "B",
        "subConcept": "Direct Variation",
        "explanation": "y = k*x^2 => 45 = k*(3)^2 = 9k => k = 5. When x = 5, y = 5*(5)^2 = 5 * 25 = 125.",
        "remediationTip": "Always find the constant of proportionality k first before substituting the new variable value."
      },
      {
        "id": "jhs3-math-q76",
        "quizId": "quiz-jhs3-math-t8-ratios-proportions-rates",
        "questionText": "A food stock can sustain 40 boarding students for 18 days. If 8 new students join the hostel, how many days will the same stock last?",
        "optionA": "15 days",
        "optionB": "12 days",
        "optionC": "16 days",
        "optionD": "21.6 days",
        "correctOption": "A",
        "subConcept": "Inverse Proportion",
        "explanation": "Total student-days = 40 * 18 = 720. New total students = 40 + 8 = 48. Days = 720 / 48 = 15 days.",
        "remediationTip": "Remember to add the new arrivals to get the total number of students before dividing."
      },
      {
        "id": "jhs3-math-q77",
        "quizId": "quiz-jhs3-math-t8-ratios-proportions-rates",
        "questionText": "Convert a vehicular speed of 90 km/h into metres per second (m/s).",
        "optionA": "20 m/s",
        "optionB": "30 m/s",
        "optionC": "25 m/s",
        "optionD": "32 m/s",
        "correctOption": "C",
        "subConcept": "Unit Conversions in Rates",
        "explanation": "To convert km/h to m/s, multiply by 5/18 (since 1000m / 3600s = 5/18): 90 * (5/18) = 5 * 5 = 25 m/s.",
        "remediationTip": "Multiply km/h by 5/18 to get m/s; multiply m/s by 18/5 to get km/h."
      },
      {
        "id": "jhs3-math-q78",
        "quizId": "quiz-jhs3-math-t8-ratios-proportions-rates",
        "questionText": "If the ratio a : b = 3 : 4 and b : c = 8 : 9, find the combined ratio a : b : c in its simplest form.",
        "optionA": "3 : 8 : 9",
        "optionB": "6 : 8 : 9",
        "optionC": "3 : 4 : 9",
        "optionD": "6 : 12 : 9",
        "correctOption": "B",
        "subConcept": "Compound Ratios",
        "explanation": "Equalize the common term b: a:b = 3:4 = 6:8. Since b:c = 8:9, the combined ratio is 6 : 8 : 9.",
        "remediationTip": "Make the middle term equal in both ratios by finding their LCM."
      },
      {
        "id": "jhs3-math-q79",
        "quizId": "quiz-jhs3-math-t8-ratios-proportions-rates",
        "questionText": "A tap fills a 240-litre tank in 20 minutes. What is the rate of water flow in litres per hour?",
        "optionA": "12 L/h",
        "optionB": "720 L/h",
        "optionC": "480 L/h",
        "optionD": "600 L/h",
        "correctOption": "B",
        "subConcept": "Rate of Flow",
        "explanation": "Rate in litres/minute = 240 / 20 = 12 L/min. There are 60 minutes in an hour: 12 * 60 = 720 litres per hour.",
        "remediationTip": "Ensure the time unit matches the required rate dimension (hours vs minutes)."
      },
      {
        "id": "jhs3-math-q80",
        "quizId": "quiz-jhs3-math-t8-ratios-proportions-rates",
        "questionText": "A map is drawn to a scale of 1 : 50,000. If two towns are 8 cm apart on the map, what is the actual ground distance in kilometres?",
        "optionA": "4 km",
        "optionB": "40 km",
        "optionC": "0.4 km",
        "optionD": "400 km",
        "correctOption": "A",
        "subConcept": "Map Scale & Proportions",
        "explanation": "Actual distance = 8 cm * 50,000 = 400,000 cm. Convert to km: 400,000 / 100 = 4,000 m; 4,000 / 1,000 = 4 km.",
        "remediationTip": "1 km = 1,000 m = 100,000 cm. Divide distance in cm by 100,000 to convert to km directly."
      }
    ]
  },
  "jhs3-math-t9-vectors-bearings": {
    "id": "quiz-jhs3-math-t9-vectors-bearings",
    "topicId": "jhs3-math-t9-vectors-bearings",
    "title": "Vectors in 2D & 3-Figure Compass Bearings BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-math-q81",
        "quizId": "quiz-jhs3-math-t9-vectors-bearings",
        "questionText": "Given vectors u = (3, -4) and v = (-1, 7), find the resultant column vector u + 2v.",
        "optionA": "(1, 10)",
        "optionB": "(2, 3)",
        "optionC": "(5, 10)",
        "optionD": "(1, 6)",
        "correctOption": "A",
        "subConcept": "Vector Arithmetic",
        "explanation": "2v = 2(-1, 7) = (-2, 14). u + 2v = (3 + (-2), -4 + 14) = (1, 10).",
        "remediationTip": "Multiply scalar 2 into both top and bottom components before adding component-wise."
      },
      {
        "id": "jhs3-math-q82",
        "quizId": "quiz-jhs3-math-t9-vectors-bearings",
        "questionText": "Calculate the magnitude of vector m = (-5, 12).",
        "optionA": "17 units",
        "optionB": "7 units",
        "optionC": "13 units",
        "optionD": "169 units",
        "correctOption": "C",
        "subConcept": "Vector Magnitude",
        "explanation": "|m| = sqrt((-5)^2 + (12)^2) = sqrt(25 + 144) = sqrt(169) = 13 units.",
        "remediationTip": "Remember that (-5)^2 is +25, not -25! Magnitudes are always positive square roots."
      },
      {
        "id": "jhs3-math-q83",
        "quizId": "quiz-jhs3-math-t9-vectors-bearings",
        "questionText": "The bearing of point Q from point P is 070°. What is the back bearing of P from Q?",
        "optionA": "250°",
        "optionB": "160°",
        "optionC": "290°",
        "optionD": "200°",
        "correctOption": "A",
        "subConcept": "Back Bearings",
        "explanation": "Since the forward bearing is less than 180°, add 180°: 070° + 180° = 250°.",
        "remediationTip": "Rule for back bearing: If bearing < 180°, add 180°. If bearing >= 180°, subtract 180°."
      },
      {
        "id": "jhs3-math-q84",
        "quizId": "quiz-jhs3-math-t9-vectors-bearings",
        "questionText": "The position vectors of points A and B are OA = (2, 3) and OB = (8, -5). Find the displacement vector AB.",
        "optionA": "(10, -2)",
        "optionB": "(-6, 8)",
        "optionC": "(6, -8)",
        "optionD": "(6, 2)",
        "correctOption": "C",
        "subConcept": "Displacement Vectors",
        "explanation": "Vector AB = OB - OA = (8 - 2, -5 - 3) = (6, -8).",
        "remediationTip": "Always calculate displacement as destination minus starting position: AB = OB - OA."
      },
      {
        "id": "jhs3-math-q85",
        "quizId": "quiz-jhs3-math-t9-vectors-bearings",
        "questionText": "Which of the following represents a bearing written in correct three-figure notation?",
        "optionA": "45°",
        "optionB": "N 45° E",
        "optionC": "045°",
        "optionD": "45.0°",
        "correctOption": "C",
        "subConcept": "Bearing Notation",
        "explanation": "Three-figure bearings must always have three digits measured clockwise from True North (000° to 360°), hence 045°.",
        "remediationTip": "Never omit the leading zero for bearings under 100° in WAEC exams."
      },
      {
        "id": "jhs3-math-q86",
        "quizId": "quiz-jhs3-math-t9-vectors-bearings",
        "questionText": "If vector p = (4, k) and |p| = 5, what are the possible values of k?",
        "optionA": "k = ±1",
        "optionB": "k = ±3",
        "optionC": "k = ±9",
        "optionD": "k = 3 only",
        "correctOption": "B",
        "subConcept": "Magnitude Equation",
        "explanation": "|p|^2 = 4^2 + k^2 = 5^2 => 16 + k^2 = 25 => k^2 = 9 => k = ±3.",
        "remediationTip": "Taking the square root yields both positive and negative solutions (±3)."
      },
      {
        "id": "jhs3-math-q87",
        "quizId": "quiz-jhs3-math-t9-vectors-bearings",
        "questionText": "A ship sails 12 km Due East, then 5 km Due North. What is its straight-line distance from the starting harbour?",
        "optionA": "17 km",
        "optionB": "13 km",
        "optionC": "14 km",
        "optionD": "15 km",
        "correctOption": "B",
        "subConcept": "Displacement and Pythagoras",
        "explanation": "East and North form a right angle: Distance = sqrt(12^2 + 5^2) = sqrt(144 + 25) = sqrt(169) = 13 km.",
        "remediationTip": "East and North directions are perpendicular (90°), allowing direct application of the Pythagorean theorem."
      },
      {
        "id": "jhs3-math-q88",
        "quizId": "quiz-jhs3-math-t9-vectors-bearings",
        "questionText": "If vectors a = (2, -3) and b = (6, y) are parallel, find the value of y.",
        "optionA": "-9",
        "optionB": "9",
        "optionC": "-6",
        "optionD": "-1",
        "correctOption": "A",
        "subConcept": "Parallel Vectors",
        "explanation": "Parallel vectors are scalar multiples: b = k*a. Here 6 = k * 2 => k = 3. Therefore, y = 3 * (-3) = -9.",
        "remediationTip": "Two vectors are parallel if their corresponding components have equal ratios: x2/x1 = y2/y1."
      },
      {
        "id": "jhs3-math-q89",
        "quizId": "quiz-jhs3-math-t9-vectors-bearings",
        "questionText": "The bearing of Town B from Town A is 235°. What is the bearing of Town A from Town B?",
        "optionA": "055°",
        "optionB": "125°",
        "optionC": "325°",
        "optionD": "045°",
        "correctOption": "A",
        "subConcept": "Back Bearings",
        "explanation": "Since the forward bearing is 235° (> 180°), subtract 180°: 235° - 180° = 055°.",
        "remediationTip": "Always write the final answer in 3 digits with a leading zero: 055°."
      },
      {
        "id": "jhs3-math-q90",
        "quizId": "quiz-jhs3-math-t9-vectors-bearings",
        "questionText": "Given u = (x, 4) and v = (3, 2). If u - v = (5, 2), find x.",
        "optionA": "2",
        "optionB": "8",
        "optionC": "-2",
        "optionD": "7",
        "correctOption": "B",
        "subConcept": "Vector Equation",
        "explanation": "x - 3 = 5 => x = 5 + 3 = 8.",
        "remediationTip": "Equate corresponding horizontal (top) components to form a simple linear equation."
      }
    ]
  },
  "jhs3-math-t10-trigonometry-right-angled": {
    "id": "quiz-jhs3-math-t10-trigonometry-right-angled",
    "topicId": "jhs3-math-t10-trigonometry-right-angled",
    "title": "Right-Angled Trigonometry, Angles of Elevation & Depression BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-math-q91",
        "quizId": "quiz-jhs3-math-t10-trigonometry-right-angled",
        "questionText": "In a right-angled triangle, the side opposite angle θ is 6 cm and the adjacent side is 8 cm. What is the value of tan θ in simplest form?",
        "optionA": "3/5",
        "optionB": "4/3",
        "optionC": "3/4",
        "optionD": "4/5",
        "correctOption": "C",
        "subConcept": "Trigonometric Ratios (SOH CAH TOA)",
        "explanation": "tan θ = Opposite / Adjacent = 6 / 8 = 3/4.",
        "remediationTip": "Remember TOA: Tangent = Opposite / Adjacent."
      },
      {
        "id": "jhs3-math-q92",
        "quizId": "quiz-jhs3-math-t10-trigonometry-right-angled",
        "questionText": "A ladder 10 metres long leans against a vertical wall, making an angle of 60° with the level ground. How far up the wall does the ladder reach? (sin 60° = 0.866)",
        "optionA": "5.0 m",
        "optionB": "8.66 m",
        "optionC": "7.07 m",
        "optionD": "10.0 m",
        "correctOption": "B",
        "subConcept": "Trigonometry Application",
        "explanation": "sin 60° = Height / 10 => Height = 10 * sin 60° = 10 * 0.866 = 8.66 m.",
        "remediationTip": "The ladder is the hypotenuse; the wall height is the opposite side to the ground angle: sin θ = Opp / Hyp."
      },
      {
        "id": "jhs3-math-q93",
        "quizId": "quiz-jhs3-math-t10-trigonometry-right-angled",
        "questionText": "From the top of a cliff 40 m high, the angle of depression of a boat on the sea is 30°. How far is the boat from the base of the cliff? (tan 30° = 0.5774)",
        "optionA": "69.28 m",
        "optionB": "23.10 m",
        "optionC": "80.00 m",
        "optionD": "46.19 m",
        "correctOption": "A",
        "subConcept": "Angle of Depression",
        "explanation": "By alternate angles, angle of elevation from boat to cliff top is 30°. tan 30° = 40 / d => d = 40 / tan 30° = 40 / 0.5774 ≈ 69.28 m.",
        "remediationTip": "WAEC Examiner Note: Angle of depression is measured downward from the horizontal sight line, which equals the angle of elevation from the ground by alternate interior angles."
      },
      {
        "id": "jhs3-math-q94",
        "quizId": "quiz-jhs3-math-t10-trigonometry-right-angled",
        "questionText": "What is the exact value of cos 60°?",
        "optionA": "sqrt(3)/2",
        "optionB": "1/2",
        "optionC": "1/sqrt(2)",
        "optionD": "sqrt(3)",
        "correctOption": "B",
        "subConcept": "Special Angles",
        "explanation": "cos 60° = 1/2 = 0.5.",
        "remediationTip": "Memorize special angles for BECE: sin 30° = cos 60° = 1/2; sin 60° = cos 30° = sqrt(3)/2."
      },
      {
        "id": "jhs3-math-q95",
        "quizId": "quiz-jhs3-math-t10-trigonometry-right-angled",
        "questionText": "In triangle ABC right-angled at B, AC = 13 cm and AB = 12 cm. Find cos A.",
        "optionA": "5/13",
        "optionB": "12/13",
        "optionC": "5/12",
        "optionD": "12/5",
        "correctOption": "B",
        "subConcept": "Trigonometric Ratios",
        "explanation": "cos A = Adjacent / Hypotenuse = AB / AC = 12 / 13.",
        "remediationTip": "Side AB is adjacent to angle A and AC is the hypotenuse (opposite the 90° angle)."
      },
      {
        "id": "jhs3-math-q96",
        "quizId": "quiz-jhs3-math-t10-trigonometry-right-angled",
        "questionText": "A vertical flagpole casts a shadow of 15 m when the angle of elevation of the sun is 45°. Calculate the height of the flagpole.",
        "optionA": "15 m",
        "optionB": "10.6 m",
        "optionC": "21.2 m",
        "optionD": "30 m",
        "correctOption": "A",
        "subConcept": "Angle of Elevation",
        "explanation": "tan 45° = Height / Shadow. Since tan 45° = 1, Height / 15 = 1 => Height = 15 m.",
        "remediationTip": "When the angle of elevation is 45°, opposite side equals adjacent side (height = shadow)."
      },
      {
        "id": "jhs3-math-q97",
        "quizId": "quiz-jhs3-math-t10-trigonometry-right-angled",
        "questionText": "If sin x = 4/5, what is the value of cos x for an acute angle x?",
        "optionA": "3/5",
        "optionB": "5/4",
        "optionC": "3/4",
        "optionD": "1/5",
        "correctOption": "A",
        "subConcept": "Pythagorean Triples in Trig",
        "explanation": "In a 3-4-5 right triangle, opposite = 4, hypotenuse = 5, adjacent = sqrt(5^2 - 4^2) = 3. Thus, cos x = 3/5.",
        "remediationTip": "Recognize the 3-4-5 right-angled triangle identity: sin^2(x) + cos^2(x) = 1."
      },
      {
        "id": "jhs3-math-q98",
        "quizId": "quiz-jhs3-math-t10-trigonometry-right-angled",
        "questionText": "An observer at the top of a building 20 m high sees a car on the road at an angle of depression of 45°. How far is the car from the base of the building?",
        "optionA": "10 m",
        "optionB": "20 m",
        "optionC": "28.3 m",
        "optionD": "40 m",
        "correctOption": "B",
        "subConcept": "Angle of Depression",
        "explanation": "tan 45° = Height / Distance => 1 = 20 / Distance => Distance = 20 m.",
        "remediationTip": "At 45°, the horizontal distance equals the vertical height."
      },
      {
        "id": "jhs3-math-q99",
        "quizId": "quiz-jhs3-math-t10-trigonometry-right-angled",
        "questionText": "Which trigonometric ratio is equal to the reciprocal of tan θ?",
        "optionA": "sin θ / cos θ",
        "optionB": "cos θ / sin θ",
        "optionC": "1 / cos θ",
        "optionD": "1 / sin θ",
        "correctOption": "B",
        "subConcept": "Trig Identities",
        "explanation": "tan θ = sin θ / cos θ. Therefore, 1 / tan θ = cos θ / sin θ (cotangent).",
        "remediationTip": "Recall that tan θ = Opp/Adj, so its reciprocal is Adj/Opp = cos θ / sin θ."
      },
      {
        "id": "jhs3-math-q100",
        "quizId": "quiz-jhs3-math-t10-trigonometry-right-angled",
        "questionText": "In triangle PQR with right angle at Q, angle P = 30° and PR = 16 cm. Find the length of QR.",
        "optionA": "8 cm",
        "optionB": "8*sqrt(3) cm",
        "optionC": "32 cm",
        "optionD": "12 cm",
        "correctOption": "A",
        "subConcept": "Trigonometric Calculations",
        "explanation": "QR is opposite to angle P (30°). sin 30° = QR / PR => 1/2 = QR / 16 => QR = 16 * 1/2 = 8 cm.",
        "remediationTip": "In a 30°-60°-90° triangle, the side opposite 30° is always exactly half the hypotenuse."
      }
    ]
  },
  "jhs3-math-t11-plane-geometry-circles": {
    "id": "quiz-jhs3-math-t11-plane-geometry-circles",
    "topicId": "jhs3-math-t11-plane-geometry-circles",
    "title": "Plane Geometry: Angles in Polygons & Circle Theorems BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-math-q101",
        "quizId": "quiz-jhs3-math-t11-plane-geometry-circles",
        "questionText": "Calculate the sum of the interior angles of a regular hexagon (6-sided polygon).",
        "optionA": "360°",
        "optionB": "540°",
        "optionC": "720°",
        "optionD": "900°",
        "correctOption": "C",
        "subConcept": "Interior Angles of Polygons",
        "explanation": "Sum = (n - 2) * 180° = (6 - 2) * 180° = 4 * 180° = 720°.",
        "remediationTip": "Use the universal polygon formula Sum = (n - 2) * 180°, where n is the number of sides."
      },
      {
        "id": "jhs3-math-q102",
        "quizId": "quiz-jhs3-math-t11-plane-geometry-circles",
        "questionText": "Each interior angle of a regular polygon is 140°. How many sides does the polygon have?",
        "optionA": "7",
        "optionB": "8",
        "optionC": "9",
        "optionD": "10",
        "correctOption": "C",
        "subConcept": "Exterior and Interior Angles",
        "explanation": "Exterior angle = 180° - 140° = 40°. Number of sides n = 360° / exterior angle = 360° / 40° = 9 sides (nonagon).",
        "remediationTip": "Finding the exterior angle (180° - interior angle) first is the fastest and least error-prone method."
      },
      {
        "id": "jhs3-math-q103",
        "quizId": "quiz-jhs3-math-t11-plane-geometry-circles",
        "questionText": "In a circle with centre O, the angle subtended by an arc at the centre is 116°. What is the angle subtended by the same arc at any point on the circumference?",
        "optionA": "232°",
        "optionB": "58°",
        "optionC": "64°",
        "optionD": "29°",
        "correctOption": "B",
        "subConcept": "Circle Theorem: Centre vs Circumference",
        "explanation": "Angle at centre is twice the angle at the circumference subtended by the same arc: Angle = 116° / 2 = 58°.",
        "remediationTip": "The angle at the circumference is always HALF of the angle at the centre."
      },
      {
        "id": "jhs3-math-q104",
        "quizId": "quiz-jhs3-math-t11-plane-geometry-circles",
        "questionText": "An angle inscribed in a semicircle is always equal to:",
        "optionA": "45°",
        "optionB": "60°",
        "optionC": "90°",
        "optionD": "180°",
        "correctOption": "C",
        "subConcept": "Angle in a Semicircle (Thales' Theorem)",
        "explanation": "By Thales' theorem, the angle subtended by a diameter at any point on the circumference is always a right angle (90°).",
        "remediationTip": "Whenever a triangle is inscribed in a circle with one side as the diameter, the angle opposite the diameter is 90°."
      },
      {
        "id": "jhs3-math-q105",
        "quizId": "quiz-jhs3-math-t11-plane-geometry-circles",
        "questionText": "In a cyclic quadrilateral ABCD, angle A = 74°. What is the size of the opposite angle C?",
        "optionA": "74°",
        "optionB": "106°",
        "optionC": "16°",
        "optionD": "286°",
        "correctOption": "B",
        "subConcept": "Cyclic Quadrilaterals",
        "explanation": "Opposite angles in a cyclic quadrilateral sum up to 180°: Angle C = 180° - 74° = 106°.",
        "remediationTip": "Remember: Opposite angles of a quadrilateral whose 4 vertices touch the circle are supplementary (add to 180°)."
      },
      {
        "id": "jhs3-math-q106",
        "quizId": "quiz-jhs3-math-t11-plane-geometry-circles",
        "questionText": "What is the angle between a tangent to a circle and the radius drawn to the point of contact?",
        "optionA": "45°",
        "optionB": "60°",
        "optionC": "90°",
        "optionD": "180°",
        "correctOption": "C",
        "subConcept": "Tangent-Radius Theorem",
        "explanation": "A tangent to a circle is perpendicular (90°) to the radius at the point of contact.",
        "remediationTip": "Radius meets tangent at 90°. This creates right triangles for solving unknown lengths using Pythagoras."
      },
      {
        "id": "jhs3-math-q107",
        "quizId": "quiz-jhs3-math-t11-plane-geometry-circles",
        "questionText": "What is the sum of the exterior angles of any convex polygon with n sides?",
        "optionA": "(n - 2) * 180°",
        "optionB": "180°",
        "optionC": "360°",
        "optionD": "360° / n",
        "correctOption": "C",
        "subConcept": "Exterior Angles Sum",
        "explanation": "The sum of exterior angles of ANY convex polygon is always constant and equals 360°, regardless of the number of sides.",
        "remediationTip": "Exterior angle sum is always 360° whether it has 3, 5, 10, or 100 sides."
      },
      {
        "id": "jhs3-math-q108",
        "quizId": "quiz-jhs3-math-t11-plane-geometry-circles",
        "questionText": "Angles in the same segment of a circle are:",
        "optionA": "Supplementary",
        "optionB": "Complementary",
        "optionC": "Equal",
        "optionD": "Twice each other",
        "correctOption": "C",
        "subConcept": "Angles in the Same Segment",
        "explanation": "Angles subtended by the same chord/arc in the same segment of a circle are equal.",
        "remediationTip": "Look for the butterfly/bow-tie shape in circle geometry diagrams; the angles at the circumference are equal."
      },
      {
        "id": "jhs3-math-q109",
        "quizId": "quiz-jhs3-math-t11-plane-geometry-circles",
        "questionText": "A tangent line PT of length 12 cm touches a circle at T. The centre of the circle is O and the radius OT is 5 cm. Find the distance OP from point P to the centre.",
        "optionA": "13 cm",
        "optionB": "17 cm",
        "optionC": "7 cm",
        "optionD": "15 cm",
        "correctOption": "A",
        "subConcept": "Tangent and Pythagoras",
        "explanation": "Angle OTP = 90°. By Pythagoras: OP^2 = OT^2 + PT^2 = 5^2 + 12^2 = 25 + 144 = 169 => OP = 13 cm.",
        "remediationTip": "OP is the hypotenuse because it lies opposite the 90° angle between radius OT and tangent PT."
      },
      {
        "id": "jhs3-math-q110",
        "quizId": "quiz-jhs3-math-t11-plane-geometry-circles",
        "questionText": "If the exterior angle of a regular polygon is 30°, how many lines of symmetry does the polygon have?",
        "optionA": "6",
        "optionB": "10",
        "optionC": "12",
        "optionD": "24",
        "correctOption": "C",
        "subConcept": "Polygons and Symmetry",
        "explanation": "Number of sides n = 360° / 30° = 12. A regular polygon with n sides has exactly n lines of symmetry, so it has 12.",
        "remediationTip": "A regular n-gon has exactly n lines of symmetry and rotational symmetry of order n."
      }
    ]
  },
  "jhs3-math-t12-mensuration-perimeter-area-volume": {
    "id": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
    "topicId": "jhs3-math-t12-mensuration-perimeter-area-volume",
    "title": "Mensuration: Cylinders, Cones, Pyramids & Prisms BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-math-q111",
        "quizId": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
        "questionText": "Calculate the volume of a closed cylinder with radius 7 cm and height 10 cm. (Take π = 22/7)",
        "optionA": "440 cm³",
        "optionB": "1,540 cm³",
        "optionC": "770 cm³",
        "optionD": "3,080 cm³",
        "correctOption": "B",
        "subConcept": "Cylinder Volume",
        "explanation": "V = π * r^2 * h = (22/7) * 7^2 * 10 = (22/7) * 49 * 10 = 22 * 7 * 10 = 1,540 cm³.",
        "remediationTip": "Cylinder volume formula is Base Area * Height = π * r^2 * h."
      },
      {
        "id": "jhs3-math-q112",
        "quizId": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
        "questionText": "Find the total surface area of a closed cylinder of radius 7 cm and height 10 cm. (Take π = 22/7)",
        "optionA": "440 cm²",
        "optionB": "594 cm²",
        "optionC": "748 cm²",
        "optionD": "880 cm²",
        "correctOption": "C",
        "subConcept": "Cylinder Total Surface Area",
        "explanation": "TSA = 2πr(r + h) = 2 * (22/7) * 7 * (7 + 10) = 44 * 17 = 748 cm².",
        "remediationTip": "WAEC Examiner Note: Check if the question asks for open cylinder (πr² + 2πrh) or closed cylinder (2πr² + 2πrh)."
      },
      {
        "id": "jhs3-math-q113",
        "quizId": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
        "questionText": "Calculate the volume of a right circular cone of radius 6 cm and vertical height 14 cm. (Take π = 22/7)",
        "optionA": "528 cm³",
        "optionB": "1,584 cm³",
        "optionC": "264 cm³",
        "optionD": "176 cm³",
        "correctOption": "A",
        "subConcept": "Cone Volume",
        "explanation": "V = (1/3) * π * r^2 * h = (1/3) * (22/7) * 36 * 14 = (1/3) * 22 * 36 * 2 = 22 * 12 * 2 = 528 cm³.",
        "remediationTip": "Cone volume is one-third the volume of a cylinder with the same base and height: (1/3)πr²h."
      },
      {
        "id": "jhs3-math-q114",
        "quizId": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
        "questionText": "A cone has a base radius of 5 cm and a slant height (l) of 13 cm. Calculate its curved surface area. (Take π = 3.142)",
        "optionA": "204.23 cm²",
        "optionB": "65π cm²",
        "optionC": "90π cm²",
        "optionD": "130π cm²",
        "correctOption": "B",
        "subConcept": "Curved Surface Area of Cone",
        "explanation": "Curved surface area = π * r * l = π * 5 * 13 = 65π cm² (or ≈ 204.23 cm²). Option B gives the exact π value 65π cm².",
        "remediationTip": "Curved surface area of a cone uses the slant height l (πrl), not the vertical height h."
      },
      {
        "id": "jhs3-math-q115",
        "quizId": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
        "questionText": "Find the volume of a rectangular pyramid with a base of length 9 cm, width 4 cm, and vertical height 10 cm.",
        "optionA": "360 cm³",
        "optionB": "120 cm³",
        "optionC": "180 cm³",
        "optionD": "90 cm³",
        "correctOption": "B",
        "subConcept": "Pyramid Volume",
        "explanation": "V = (1/3) * Base Area * Height = (1/3) * (9 * 4) * 10 = (1/3) * 36 * 10 = 120 cm³.",
        "remediationTip": "Pyramid volume formula is always (1/3) * Base Area * Height."
      },
      {
        "id": "jhs3-math-q116",
        "quizId": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
        "questionText": "A right triangular prism has a cross-sectional right triangle with base 6 cm and height 8 cm. If the length of the prism is 15 cm, calculate its volume.",
        "optionA": "720 cm³",
        "optionB": "360 cm³",
        "optionC": "180 cm³",
        "optionD": "540 cm³",
        "correctOption": "B",
        "subConcept": "Prism Volume",
        "explanation": "Base area = (1/2) * 6 * 8 = 24 cm². Volume = Base Area * Length = 24 * 15 = 360 cm³.",
        "remediationTip": "Volume of any prism = Uniform cross-sectional area * Length."
      },
      {
        "id": "jhs3-math-q117",
        "quizId": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
        "questionText": "What is the total surface area of a solid sphere of radius 7 cm? (Take π = 22/7)",
        "optionA": "616 cm²",
        "optionB": "154 cm²",
        "optionC": "1,437.3 cm²",
        "optionD": "308 cm²",
        "correctOption": "A",
        "subConcept": "Sphere Surface Area",
        "explanation": "Surface Area = 4 * π * r^2 = 4 * (22/7) * 7 * 7 = 4 * 22 * 7 = 616 cm².",
        "remediationTip": "The surface area of a sphere is 4 times the area of its great circle: 4πr²."
      },
      {
        "id": "jhs3-math-q118",
        "quizId": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
        "questionText": "A cylindrical tin has an open top. Its radius is 3.5 cm and height is 10 cm. Find its external surface area. (Take π = 22/7)",
        "optionA": "258.5 cm²",
        "optionB": "220 cm²",
        "optionC": "297 cm²",
        "optionD": "192.5 cm²",
        "correctOption": "A",
        "subConcept": "Open Cylinder Surface Area",
        "explanation": "Open top TSA = πr² + 2πrh = (22/7)*(3.5)^2 + 2*(22/7)*3.5*10 = 38.5 + 220 = 258.5 cm².",
        "remediationTip": "Notice that an open tin has only 1 circular base: πr² + 2πrh."
      },
      {
        "id": "jhs3-math-q119",
        "quizId": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
        "questionText": "If the radius of a cylinder is doubled while keeping its height constant, its volume increases by a factor of:",
        "optionA": "2",
        "optionB": "4",
        "optionC": "8",
        "optionD": "16",
        "correctOption": "B",
        "subConcept": "Scale Factors in Volume",
        "explanation": "V = π * r^2 * h. If r becomes 2r, new V = π * (2r)^2 * h = 4πr^2h = 4 * V.",
        "remediationTip": "Because radius is squared in the volume formula, doubling r multiplies volume by 2^2 = 4."
      },
      {
        "id": "jhs3-math-q120",
        "quizId": "quiz-jhs3-math-t12-mensuration-perimeter-area-volume",
        "questionText": "A sector of a circle of radius 14 cm has a central angle of 90°. Calculate the perimeter of the sector. (Take π = 22/7)",
        "optionA": "22 cm",
        "optionB": "50 cm",
        "optionC": "36 cm",
        "optionD": "44 cm",
        "correctOption": "B",
        "subConcept": "Perimeter of Sector",
        "explanation": "Arc length = (90/360) * 2 * (22/7) * 14 = (1/4) * 88 = 22 cm. Perimeter of sector = Arc length + 2r = 22 + 2(14) = 22 + 28 = 50 cm.",
        "remediationTip": "WAEC Examiner Note: Many candidates forget to add the two straight boundary radii (2r) to the arc length when calculating sector perimeter!"
      }
    ]
  },
  "jhs3-math-t13-geometric-transformations": {
    "id": "quiz-jhs3-math-t13-geometric-transformations",
    "topicId": "jhs3-math-t13-geometric-transformations",
    "title": "Rigid Geometric Transformations: Reflection, Rotation & Translation BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-math-q121",
        "quizId": "quiz-jhs3-math-t13-geometric-transformations",
        "questionText": "Find the coordinates of the image of point P(3, -5) under reflection in the x-axis.",
        "optionA": "(-3, -5)",
        "optionB": "(3, 5)",
        "optionC": "(-3, 5)",
        "optionD": "(5, 3)",
        "correctOption": "B",
        "subConcept": "Reflection in x-axis",
        "explanation": "Reflection in the x-axis keeps the x-coordinate unchanged and negates the y-coordinate: (x, y) -> (x, -y). Thus, (3, -5) -> (3, 5).",
        "remediationTip": "Reflection in x-axis: (x, -y). Reflection in y-axis: (-x, y)."
      },
      {
        "id": "jhs3-math-q122",
        "quizId": "quiz-jhs3-math-t13-geometric-transformations",
        "questionText": "What is the image of point A(-4, 7) when reflected in the line y = x?",
        "optionA": "(7, -4)",
        "optionB": "(-7, 4)",
        "optionC": "(-4, -7)",
        "optionD": "(4, -7)",
        "correctOption": "A",
        "subConcept": "Reflection in y = x",
        "explanation": "Reflection in the line y = x swaps the coordinates: (x, y) -> (y, x). Thus, (-4, 7) -> (7, -4).",
        "remediationTip": "Reflection in y = x swaps x and y. Reflection in y = -x swaps and negates both: (-y, -x)."
      },
      {
        "id": "jhs3-math-q123",
        "quizId": "quiz-jhs3-math-t13-geometric-transformations",
        "questionText": "Point Q(2, 6) is translated by the vector T = (-5, 3). Determine the coordinates of its image Q'.",
        "optionA": "(7, 3)",
        "optionB": "(-3, 9)",
        "optionC": "(-3, 3)",
        "optionD": "(3, 9)",
        "correctOption": "B",
        "subConcept": "Translation Vector",
        "explanation": "Q' = Q + T = (2 + (-5), 6 + 3) = (-3, 9).",
        "remediationTip": "Translation simply adds the column vector to the original point coordinates: Image = Object + Translation vector."
      },
      {
        "id": "jhs3-math-q124",
        "quizId": "quiz-jhs3-math-t13-geometric-transformations",
        "questionText": "Find the image of point B(5, 2) under a rotation of 90° anticlockwise about the origin (0, 0).",
        "optionA": "(2, 5)",
        "optionB": "(-2, 5)",
        "optionC": "(2, -5)",
        "optionD": "(-5, -2)",
        "correctOption": "B",
        "subConcept": "Rotation 90° Anticlockwise",
        "explanation": "Rotation of 90° anticlockwise (or 270° clockwise) maps (x, y) to (-y, x). Thus, (5, 2) -> (-2, 5).",
        "remediationTip": "Remember rotation rules about origin: 90° anticlockwise -> (-y, x); 180° -> (-x, -y); 270° anticlockwise / 90° clockwise -> (y, -x)."
      },
      {
        "id": "jhs3-math-q125",
        "quizId": "quiz-jhs3-math-t13-geometric-transformations",
        "questionText": "Point C(-3, -8) is rotated through 180° about the origin. What are the coordinates of its image C'?",
        "optionA": "(3, 8)",
        "optionB": "(-8, -3)",
        "optionC": "(8, 3)",
        "optionD": "(-3, 8)",
        "correctOption": "A",
        "subConcept": "Rotation through 180°",
        "explanation": "Rotation of 180° about origin maps (x, y) to (-x, -y). Thus, (-3, -8) -> (3, 8).",
        "remediationTip": "A 180° rotation simply changes the signs of both coordinates."
      },
      {
        "id": "jhs3-math-q126",
        "quizId": "quiz-jhs3-math-t13-geometric-transformations",
        "questionText": "An enlargement with scale factor k = -2 is applied to point D(3, -1) with the origin as centre. Find the image D'.",
        "optionA": "(6, -2)",
        "optionB": "(-6, 2)",
        "optionC": "(1, 1)",
        "optionD": "(-5, -3)",
        "correctOption": "B",
        "subConcept": "Enlargement with Negative Scale Factor",
        "explanation": "D' = k * D = -2 * (3, -1) = (-6, 2).",
        "remediationTip": "Multiply both coordinates by the scale factor k. A negative factor inverts the image across the centre."
      },
      {
        "id": "jhs3-math-q127",
        "quizId": "quiz-jhs3-math-t13-geometric-transformations",
        "questionText": "If the translation vector T maps point M(1, 4) to M'(5, 1), what is T?",
        "optionA": "(4, -3)",
        "optionB": "(-4, 3)",
        "optionC": "(6, 5)",
        "optionD": "(4, 3)",
        "correctOption": "A",
        "subConcept": "Finding Translation Vector",
        "explanation": "T = M' - M = (5 - 1, 1 - 4) = (4, -3).",
        "remediationTip": "Translation vector = Image - Object."
      },
      {
        "id": "jhs3-math-q128",
        "quizId": "quiz-jhs3-math-t13-geometric-transformations",
        "questionText": "Which of the following geometric transformations changes the size of an object?",
        "optionA": "Reflection",
        "optionB": "Rotation",
        "optionC": "Translation",
        "optionD": "Enlargement (scale factor ≠ 1)",
        "correctOption": "D",
        "subConcept": "Isometric vs Non-isometric Transformations",
        "explanation": "Reflection, rotation, and translation are isometries (preserve shape and size / congruent). Enlargement changes size, producing similar shapes.",
        "remediationTip": "Rigid transformations preserve length and area; enlargement alters area by k²."
      },
      {
        "id": "jhs3-math-q129",
        "quizId": "quiz-jhs3-math-t13-geometric-transformations",
        "questionText": "A triangle with area 12 cm² is enlarged by a scale factor of 3. What is the area of the resulting image triangle?",
        "optionA": "36 cm²",
        "optionB": "72 cm²",
        "optionC": "108 cm²",
        "optionD": "144 cm²",
        "correctOption": "C",
        "subConcept": "Area Scale Factor",
        "explanation": "Area of image = (Scale factor)^2 * Original area = 3^2 * 12 = 9 * 12 = 108 cm².",
        "remediationTip": "Linear scale factor = k; Area scale factor = k²; Volume scale factor = k³."
      },
      {
        "id": "jhs3-math-q130",
        "quizId": "quiz-jhs3-math-t13-geometric-transformations",
        "questionText": "What is the image of point (x, y) after reflection in the y-axis followed by reflection in the x-axis?",
        "optionA": "(y, x)",
        "optionB": "(-x, -y)",
        "optionC": "(x, -y)",
        "optionD": "(-y, -x)",
        "correctOption": "B",
        "subConcept": "Composite Transformations",
        "explanation": "Reflection in y-axis: (x, y) -> (-x, y). Then reflection in x-axis: (-x, y) -> (-x, -y). This is equivalent to a 180° rotation about the origin.",
        "remediationTip": "Reflecting in both axes successively is identical to a half-turn (180° rotation) about the origin."
      }
    ]
  },
  "jhs3-math-t14-data-handling-probability": {
    "id": "quiz-jhs3-math-t14-data-handling-probability",
    "topicId": "jhs3-math-t14-data-handling-probability",
    "title": "Statistics: Mean, Median, Mode & Experimental Probability BECE Diagnostic Quiz",
    "timeLimitMinutes": 12,
    "passScorePercentage": 60,
    "questions": [
      {
        "id": "jhs3-math-q131",
        "quizId": "quiz-jhs3-math-t14-data-handling-probability",
        "questionText": "The marks of 7 students in a math test are: 8, 12, 15, 12, 9, 14, 14. Find the median mark.",
        "optionA": "12",
        "optionB": "13",
        "optionC": "14",
        "optionD": "11.7",
        "correctOption": "A",
        "subConcept": "Median of Ungrouped Data",
        "explanation": "Arrange the data in ascending order: 8, 9, 12, 12, 14, 14, 15. The middle value (4th term) is 12.",
        "remediationTip": "Always arrange the data in ascending or descending order before finding the middle value."
      },
      {
        "id": "jhs3-math-q132",
        "quizId": "quiz-jhs3-math-t14-data-handling-probability",
        "questionText": "The mean of the numbers 4, 7, 10, x, and 15 is 9. Find the value of x.",
        "optionA": "8",
        "optionB": "9",
        "optionC": "11",
        "optionD": "7",
        "correctOption": "B",
        "subConcept": "Mean Calculation",
        "explanation": "Total sum = 5 * 9 = 45. Known sum = 4 + 7 + 10 + 15 = 36. x = 45 - 36 = 9.",
        "remediationTip": "Multiply the mean by the count n to get the total sum, then subtract known terms."
      },
      {
        "id": "jhs3-math-q133",
        "quizId": "quiz-jhs3-math-t14-data-handling-probability",
        "questionText": "A fair 6-sided die is rolled once. What is the probability of obtaining a prime number?",
        "optionA": "1/6",
        "optionB": "1/3",
        "optionC": "1/2",
        "optionD": "2/3",
        "correctOption": "C",
        "subConcept": "Probability of Simple Events",
        "explanation": "Possible outcomes: {1, 2, 3, 4, 5, 6} (6 total). Prime numbers are {2, 3, 5} (3 primes). Probability = 3 / 6 = 1/2.",
        "remediationTip": "WAEC Examiner Note: 1 is NOT a prime number! Prime numbers on a die are 2, 3, and 5."
      },
      {
        "id": "jhs3-math-q134",
        "quizId": "quiz-jhs3-math-t14-data-handling-probability",
        "questionText": "A bag contains 5 red balls, 4 blue balls, and 3 yellow balls. A ball is drawn at random. What is the probability that it is NOT blue?",
        "optionA": "1/3",
        "optionB": "2/3",
        "optionC": "1/4",
        "optionD": "3/4",
        "correctOption": "B",
        "subConcept": "Complementary Probability",
        "explanation": "Total balls = 5 + 4 + 3 = 12. Non-blue balls = 5 + 3 = 8. P(Not blue) = 8 / 12 = 2/3 (or 1 - 4/12 = 2/3).",
        "remediationTip": "P(Not Event) = 1 - P(Event)."
      },
      {
        "id": "jhs3-math-q135",
        "quizId": "quiz-jhs3-math-t14-data-handling-probability",
        "questionText": "Consider the frequency table: Score (x): 1, 2, 3, 4; Frequency (f): 3, 5, 8, 4. Find the modal score.",
        "optionA": "8",
        "optionB": "3",
        "optionC": "2",
        "optionD": "4",
        "correctOption": "B",
        "subConcept": "Mode from Frequency Table",
        "explanation": "The highest frequency is 8, which corresponds to the score 3. Therefore, the mode is 3.",
        "remediationTip": "WAEC trap: The mode is the SCORE with the highest frequency, NOT the frequency itself (3, not 8)."
      },
      {
        "id": "jhs3-math-q136",
        "quizId": "quiz-jhs3-math-t14-data-handling-probability",
        "questionText": "For the frequency table with scores x = [1, 2, 3, 4] and frequencies f = [3, 5, 8, 4], calculate the mean score.",
        "optionA": "2.65",
        "optionB": "2.50",
        "optionC": "3.00",
        "optionD": "2.80",
        "correctOption": "A",
        "subConcept": "Mean from Frequency Table",
        "explanation": "Sum of f = 3 + 5 + 8 + 4 = 20. Sum of fx = (1*3) + (2*5) + (3*8) + (4*4) = 3 + 10 + 24 + 16 = 53. Mean = 53 / 20 = 2.65.",
        "remediationTip": "Mean = Σ(f*x) / Σf. Always make a neat column for f*x and sum both f and f*x."
      },
      {
        "id": "jhs3-math-q137",
        "quizId": "quiz-jhs3-math-t14-data-handling-probability",
        "questionText": "In a pie chart, a sector of 120° represents 60 bags of cocoa. What is the total number of bags represented in the whole pie chart?",
        "optionA": "180 bags",
        "optionB": "240 bags",
        "optionC": "120 bags",
        "optionD": "360 bags",
        "correctOption": "A",
        "subConcept": "Pie Chart Angles",
        "explanation": "Full pie chart = 360°. Since 120° represents 60 bags, 360° represents (360 / 120) * 60 = 3 * 60 = 180 bags.",
        "remediationTip": "Use the ratio Angle / 360° = Frequency / Total."
      },
      {
        "id": "jhs3-math-q138",
        "quizId": "quiz-jhs3-math-t14-data-handling-probability",
        "questionText": "Two fair coins are tossed simultaneously. What is the probability of getting at least one head?",
        "optionA": "1/4",
        "optionB": "1/2",
        "optionC": "3/4",
        "optionD": "1",
        "correctOption": "C",
        "subConcept": "Sample Space Probability",
        "explanation": "Sample space: {HH, HT, TH, TT} (4 outcomes). Outcomes with at least one head: {HH, HT, TH} (3 outcomes). P = 3/4.",
        "remediationTip": "\"At least one\" means 1 or more. Only the outcome {TT} fails the condition."
      },
      {
        "id": "jhs3-math-q139",
        "quizId": "quiz-jhs3-math-t14-data-handling-probability",
        "questionText": "What is the probability of an impossible event?",
        "optionA": "-1",
        "optionB": "0",
        "optionC": "0.5",
        "optionD": "1",
        "correctOption": "B",
        "subConcept": "Probability Scale",
        "explanation": "Probability always lies between 0 (impossible) and 1 (certain). An impossible event has probability 0.",
        "remediationTip": "Probability can never be negative or greater than 1."
      },
      {
        "id": "jhs3-math-q140",
        "quizId": "quiz-jhs3-math-t14-data-handling-probability",
        "questionText": "In a class of 40 students, 24 study French, 20 study ICT, and 8 study neither. If a student is chosen at random, what is the probability that the student studies both subjects?",
        "optionA": "3/10",
        "optionB": "1/5",
        "optionC": "2/5",
        "optionD": "1/2",
        "correctOption": "A",
        "subConcept": "Venn Diagram Probability",
        "explanation": "Students studying at least one subject = 40 - 8 = 32. n(F ∪ I) = n(F) + n(I) - n(F ∩ I) => 32 = 24 + 20 - n(Both) => 32 = 44 - n(Both) => n(Both) = 12. P(Both) = 12 / 40 = 3/10.",
        "remediationTip": "Use the inclusion-exclusion principle: n(A ∪ B) = n(A) + n(B) - n(A ∩ B)."
      }
    ]
  }
};
